### ISSUE TITLE
Present Bazel test results in 'Test Runner Tab' style

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#1]
Hi,
First and foremost I want to say thank you and kudos for your work on the plugin and OSSing it.
I think it's an important piece in the Bazel eco-system.
I wanted to know what you think about extending the plugin so that it will integrate into the [Test Runner Tab](https://www.jetbrains.com/help/idea/2016.1/test-runner-tab.html).
That is one of the substantial changes one experiences when switching from a "regular" maven intellij project to its bazel equivalent.

Additionally I have some other thoughts on improvements but I don't want to pile on if you're not ready yet so if you'd rather I wait, before opening a few additional issues, so that you can get your ducks in a row that's totally fine.

Again, thank you!

**Comment by brendandouglas** [comment]
Thanks! It's great to hear it's being used.

Presenting the Bazel test results in a similar style to the Test Runner Tab (by integrating with it, if practical) is one of our top open bugs. We're actively working on it.

We'd love to hear your thoughts on what else can be improved -- feel free to send them all through!

**Comment by ittaiz** [comment]
Awesome, thanks. I'll open them now.
Since I don't really have a good place to comment on things that work great I'll take this stage to say that the BUILD file support of auto-complete and navigation is awesome 👍

**Comment by brendandouglas** [comment]
This should be fixed in the most recent release (2017.01.30) -- please let us know if there are any issues.

**Comment by ittaiz** [comment]
Wow, amazing! Well done. Opened a few problems with it in #55
