### ISSUE TITLE
Discover test targets when right-clicking on a folder

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#10]
This relates to #4 but I think is somewhat different. If it duplicates please feel free to close.
The use-case is right clicking on a test folder and getting the option from the "run" sub menu to choose to run all targets in this package (sub packages also?) _and_ a specific target from the list of targets the plugin identifies that exist in this package.

**Comment by brendandouglas** [comment]
The first part should be already supported (creating a run configuration including all java test targets underneath the selected package/class/method).

We don't want to clutter the context menu with too many options, so perhaps creating a configuration running a specific target is best done via the BUILD target directly.

**Comment by ittaiz** [comment]
The first part indeed exists. I meant, and was probably unclear, that I'm referring to adding functionality and not replacing it.
I think that using a run sub menu can help with the clutter greatly. Have you looked at the pants IntelliJ screenshot? It looks rather useful

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
