### ISSUE TITLE
local variable mis-targeted for click-through navigation in starlark

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/intellij#1003]
In a starlark function, if you declare a variable foo, and you import a struct containing a function pointer also named foo, then the intellij navigation gets mixed up and mistakes the symbol in the struct for the local one. 

This is notably the case where you are putting together utilities or grouped functions which you want to namespace, using a struct.

E.g. 
> blah.bzl
```
def _some_foo_function():
    pass

blah = struct(
    foo = _some_foo_function,
)
```

> something.bzl
```
load(":blah.bzl", "blah")
def whatever()
        foo = "foo"
            
        blah.foo(
            name = "something",
            param = "something else",
        )
```

In this situation, if you commend-click on the `foo` part of `blah.foo` it will navigate to the local variable `foo` and not to the function

**Comment by cgruber** [comment]
Note - starlark is just fine with this - this is purely about the click-through navigation and the model of the code in the IDE.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
