### ISSUE TITLE
Target search

### ISSUE THREAD

**Issue by arjantop** [bazelbuild/intellij#1006]
When adding library dependencies you currently start typing "//" and get nice autocomplete. But you always have to "complete" left-to-right as you would specify a directly in bash.

It would be great it you could search target by some string "foo" and get all targets that contain foo in the path. This could be an additional action (or something similar). This would be of great help when specifying dependencies (you not not need to know the namespace).

Example:
```
Targets:
//a/b/foo
//a/b/bar
//d/foo

Typing "foo":
//a/b/foo
//d/foo
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
