### ISSUE TITLE
Layout editor doesn't show when opening layout xml files

### ISSUE THREAD

**Issue by vickyyy** [bazelbuild/intellij#101]
It is easy to reproduce, just clone the official tutorial https://github.com/bazelbuild/examples.git, and import WORKSPACE tutorial and BUILD file android/BUILD.

**Comment by jvoung** [comment]
For now there is a setting that you must turn on "Use the layout editor for layout XML files. May freeze IDE" in Settings > Other Settings > Bazel Settings.

We had some performance issues with large projects so it was made opt-in for now.

**Comment by jvoung** [comment]
The setting has been removed so marking this issue obsolete (assuming that the setting was the issue -- please correct if that wasn't actually the case):
https://github.com/bazelbuild/intellij/commit/c0fc89da4d7ffcef11bc2acfa7d67315493762eb#diff-ebe9c46ddb8bf9ed11e04f24ee6efba5
