### ISSUE TITLE
Pass ANDROID_HOME to bazel command

### ISSUE THREAD

**Issue by likan999** [bazelbuild/intellij#102]
It is a common practice to omit path in android_sdk_repository in WORKSPACE file because typically when a repository is shared between multiple persons, and they have different install location of Android SDK, it is better to rely on ANDROID_HOME environment variable to indicate the path of the sdk.

On MacOSX, when Android Studio app is started via clicking the icon in Applications folder or launchpad, the environment doesn't respect .bash_profile or .bashrc, therefore the environment variable is not set.

There are a couple of work arounds: 1) always start the app from terminal; 2) manually modify Info.plist file of "Android Studio.app": https://superuser.com/a/541068

It is nice if the plugin can do something smarter. If there is no ANDROID_HOME environment variable, when invoking the underlying bazel command, the plugin should pass it with ANDROID_HOME set to 1) sdk location in Android Studio settings; 2) "Path variables" in the Android Studio preferences.

**Comment by omo** [comment]
This is same for Linux in some extent: You can (and I do) launch AS through GUI, not from the terminal.
In Linux you can set ANDROID_HOME in `.profile`, but I'd rather let AS+Bazel use its own Android SDK, which would be the same as the one ANDROID_HOME points in many cases.

Yet another option might be just waiting for https://github.com/bazelbuild/bazel/issues/4047 being fixed.

**Comment by mai93** [comment]
Hello @likan999 and @omo do you still see this issue with newer versions of the plugin and the IDE?

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
