### ISSUE TITLE
Subtractive targets in Run/Debug Configurations

### ISSUE THREAD

**Issue by dtormoen** [bazelbuild/intellij#1026]
When setting a target expression in a Run/Debug Configuration, you are unable to use subtractive patterns. It appears it is an issue with the text field validation because Bazel does support these types of expressions.

For example running bazel on the command line like this properly excludes the targets I want to skip:
```
bazel test -- //...:all -//my-really-slow-tests/...:all
```

but setting a target expression of `//...:all -//my-really-slow-tests/...:all` will display an error message in the CLion Run/Debug configurations. `Error: Invalid package name '//...': package name component contains only '.' characters`

**Comment by brendandouglas** [comment]
We don't currently support multiple target patterns for a single run configuration. It works sometimes, but only by accident.

In this case we're treating it as a single target, and our package validation doesn't handle the resulting string.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
