### ISSUE TITLE
Deps to Android support libraries does not show up as external libraries of the project

### ISSUE THREAD

**Issue by likan999** [bazelbuild/intellij#103]
If my android project has deps to Android support libraries, then after import/sync in Android Studio, the support libraries are not shown up as external libraries, therefore in the Java editor their classes will be shown as "Cannot resolve symbol".

To reproduce, just clone the official tutorial https://github.com/bazelbuild/examples.git and "git am" the attached patch, and import the WORKSPACE under "tutorial/" directory, and BUILD file under "tutorial/android/". Note the minSdk and api_level in the patch are not necessary, I have them just because I don't have lower versions of sdk installed.

The OS is Mac OSX.

[diff.txt](https://github.com/bazelbuild/intellij/files/1081187/diff.txt)

**Comment by jvoung** [comment]
Should be handled now in the plugin.

Support libraries used aar_import, and the basics of aar_import now work (https://github.com/bazelbuild/intellij/blob/983a509e55b78aaa5323adc9e2742db783d90d57/aswb/src/com/google/idea/blaze/android/sync/model/AarLibrary.java, and related code)
