### ISSUE TITLE
[Goland] Add support typescript integration

### ISSUE THREAD

**Issue by asv** [bazelbuild/intellij#1034]
Goland has basic support for Web development (completion, syntax highlighting, NPM integration), but when trying to import a bazel project combining both Golang and Typescript code, the plugin throws an error: `Error: IntelliJ Ultimate or CLion needed for TypeScript support.`. This error breaks bazel plugin, even if the developer does not edit TypeScript files.

The simplest, it seems to me, is to add Golang support here (`PlatformUtils.isGoIde()`): https://github.com/bazelbuild/intellij/blob/c240371fbc3b3756b5faa2fa7f60130cb22327b2/javascript/src/com/google/idea/blaze/typescript/BlazeTypescriptSyncPlugin.java#L209

**Comment by brendandouglas** [comment]
Thanks for letting us know -- that check should be calling #isLanguageSupportedInIde, earlier in the file. Submitting a fix upstream -- it will land in the release after next.
