### ISSUE TITLE
Java: sources not viewable for junit

### ISSUE THREAD

**Issue by drichelson** [bazelbuild/intellij#1037]
I was able to reproduce this using the java-maven project in the examples repo: https://github.com/bazelbuild/examples/tree/5547cbe71a77c237ab78be0803726102f230e1a5/java-maven

IntelliJ Info:
```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
```

Bazel plugin info:
Running locally built latest master branch: `e82fa3e2419e0f7bd2d251545dd7402be3c49b77` 

Bazel version: `0.25.0`

Steps taken:
1. Open file `com/example/myproject/TestApp.java`
1. Command-click (or equivalent modifier to view source) on the `assertEquals` text on line 14.

Expected Behavior:
IntelliJ should navigate to full source code.

Actual behavior:
IntelliJ navigates to decompiled .class file:
![image](https://user-images.githubusercontent.com/602409/62151582-78fa3900-b2b5-11e9-88ff-9559459542df.png)

**Comment by jin** [comment]
That example using `maven_jar` does not download source jars (we should update that..). `maven_jar` is deprecated, please use `rules_jvm_external` to manage your third party dependencies instead. I've submitted a PR to update it: https://github.com/bazelbuild/examples/pull/107

**Comment by jin** [comment]
<img width="1235" alt="Screen Shot 2019-07-31 at 7 42 14 PM" src="https://user-images.githubusercontent.com/347918/62255507-7558d600-b3cb-11e9-83cc-6b16109a1b32.png">

Looks like it's working :)

**Comment by drichelson** [comment]
Thanks @jin !
