### ISSUE TITLE
Copy belonging target label shortcut

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#105]
Hi,
Is there a way to copy the target label a file belongs to? The idea is that many times when I want to add a dependency on a class I can use `CMD+N` to find the file and then `CMD+SHIFT+C` to copy the file path. From there it's a bit of fiddling to get the target name.
Is there a simpler way in the plugin?
It seems that you already know which target the file belongs to.

**Comment by brendandouglas** [comment]
The quickest way to do this currently:
- right-click > Open Corresponding BUILD file (navigates to the relevant target in the BUILD file)
- right-click again > Copy BUILD target string

Even easier would be to map these actions to hotkeys.

**Comment by ittaiz** [comment]
Thanks!
Is it difficult to expose an aggregate action?

**Comment by brendandouglas** [comment]
Not difficult, it's just that there are many similar actions we could expose, and I don't want to clutter the menus.

I could create the action, but not add it to the menu (allowing users to bind it to a hotkey themselves), but then it's not going to be discoverable.

**Comment by ittaiz** [comment]
please do...
There's always a tradeoff between discoverability and clutter.
This is the first small thing our internal users asked for... (they asked
for some big things as well :) )

**Comment by hmemcpy** [comment]
> I could create the action, but not add it to the menu (allowing users to bind it to a hotkey themselves), but then it's not going to be discoverable.

@brendandouglas can I have a go at that? It's a feature we use a lot at the moment, and having it be a single action would be of great help!
Even if not adding it to the menu by default...

**Comment by brendandouglas** [comment]
Sure, please do!

**Comment by hmemcpy** [comment]
Added a command that adds this functionality (and used it twice myself, already!)
I decided to set the text of the action to be `Copy //:target....'`, where it will show the actual target name (shortened!). Makes it much easier to see what is being copied.

I also think this doesn't clutter the context menu too much. Would love if it could stay as is!
