### ISSUE TITLE
can not resolver the included head signal.h execinfo.h

### ISSUE THREAD

**Issue by wumuzi520** [bazelbuild/intellij#1050]
CLion 2019.1
Bazel 0.28.1
OSX macOS High Serria 10.13.3

![image](https://user-images.githubusercontent.com/2016670/62475121-fdc5e500-b7d6-11e9-8cae-244443111de5.png)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
