### ISSUE TITLE
Add support for j2cl 

### ISSUE THREAD

**Issue by morten-holm** [bazelbuild/intellij#1064]
Please add support for j2cl projects.

This includes j2cl_application, j2cl_library and closure_js_library rules.

**Comment by AugustNagro** [comment]
It works temporarily if you right click the jars in bazel-bin/external and 'Add as Library', but the settings are reverted after sync.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
