### ISSUE TITLE
What is the state of skylark support?

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#11]
I've tried importing a small scala project (built with skylark of course) and it seems it's not supported. The source code appears greyed out and labeled `(unsynced)`.
Interested in learning what's the state of skylark support and what are the thoughts?
This is an area I'm very interested in and if applicable I'd be happy to contribute in a few weeks time once I make some progress on other parts of our bazel setup.
[project](https://github.com/ittaiz/bazel-scala-getting-started) I tried to import for reference.

**Comment by tomlu** [comment]
There isn't any general Skylark support, we have to separately support each language. You can open a feature request for Scala specifically (unless you have already done so). We are currently unclear when/if we'd support that. Thanks!
