### ISSUE TITLE
Bazel plugin should provide an option to override Bazel flags

### ISSUE THREAD

**Issue by dmitry-xnor** [bazelbuild/intellij#110]
We use Python3 and because of that, our repo bazelrc contains `--force_python=PY3 --host_force_python=PY3`. This makes Android SDK barf because Bazel tries (and fails) to convert AAR tool to Python3. In the console we work around that by `--host_force_python=PY2`.

However, there currently doesn't seem to be a way to pass `--host_force_python` (or indeed any other flag) to Bazel from the plugin. IMO there should be such an option, if for no other reason than to work around issues in Android SDK

**Comment by brendandouglas** [comment]
[build_flags](http://ij.bazel.build/docs/project-views.html#build_flags) sounds like what you're looking for.

**Comment by dmitry-xnor** [comment]
Oh, looks like it does it already. I'll try that and reopen if it doesn't work.
