### ISSUE TITLE
Minimize Bazel toolbar when activating another toolbar

### ISSUE THREAD

**Issue by britishdan** [bazelbuild/intellij#1103]
Hi! This is a "nice to have" feature request.
When I run Bazel Build in Intellij, the bazel toolbar opens and shows me the log, which is great. 
I would like the Bazel toolbar to minimize when I activate another toolbar. For example, run or find.
This is similar to how the find toolbar automatically minimizes when running tests.
Currently I'm manually minimizing the bazel toolbar many many times per day and it's getting in the way of my workflow.

Thanks!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
