### ISSUE TITLE
Package level granualrity doesn't honor bazels scope

### ISSUE THREAD

**Issue by rverma-nikiai** [bazelbuild/intellij#1108]
hi all, while using package-level granularity, is there a way if packages are not make visible to other packages, can we make IntelliJ not show that. This works for module-level granularity although.
The structure of code is like
src
  main
    java
      example
        myproject
          App.java
          BUILD <-1
       otherproject
         App2.java
         BUILD <- 2
build 1 is
java_library(
    name = "app",
    srcs = glob(["*.java"]),
    visibility = ["//src/test:__subpackages__"],
    deps = ["@maven//:com_google_guava_guava"],
)
build 2 iis
java_library(
    name = "app2",
    srcs = glob(["*.java"]),
    visibility = ["//src/test:__subpackages__"],
    deps = ["@maven//:com_google_guava_guava"],
)
If we reference App in App2 injtellij allows it, bazel as expected throws visibility error. Would be nice if we can force intellij to mimick the behaviour

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
