### ISSUE TITLE
Plugin does not map Java source directories if there are commented out files in there

### ISSUE THREAD

**Issue by jylin** [bazelbuild/intellij#111]
If a Java package directory contains a ".java" file that's entirely commented out, then the Bazel plugin does not mark that directory as a source directory even though the CLI "bazel build" works fine. There are warnings like "Warning: No package name string found in java source file: <file>" that show up, but I think the plugin should be able to successfully ignore the commented out files and map the source directory.

**Comment by brendandouglas** [comment]
Are there any valid source files in the directory, or are they all entirely commented out?

**Comment by jylin** [comment]
In my case, all the other files were valid and there was just 1 file entirely commented out.

**Comment by brendandouglas** [comment]
Thanks, we'll fix this up for the next release.
