### ISSUE TITLE
Build doesn't work when JAVA_HOME points to Java 11

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/intellij#1118]
The plugin only seems to build with Java 8. When built using Java 11, the following error is seen:

```
ERROR: /Users/user/src/github.com/bazelbuild/intellij/third_party/java/jdk/BUILD:7:1: Executing genrule //third_party/java/jdk:jdk_tools_jar failed (Exit 1) bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp external/local_jdk/lib/tools.jar bazel-out/darwin-fastbuild/bin/third_party/java/jdk/tools.jar'
```

This is because the structure of the JDK has changed.

Oracle no longer support Java 8 for commercial use, so this is becoming a problem, even if OpenJDK support will continue for some time.

**Comment by gertvdijk** [comment]
I can confirm this issue. Moreover, stable Linux distributions have started to stop providing OpenJDK 8, e.g. Debian Buster.

Also reproducible when using Bazel remote JDK 11:

    bazel build  --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 \
                 --javabase=@bazel_tools//tools/jdk:remote_jdk11 \
                 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 \
                 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 \
                 //ijwb:ijwb_bazel_zip --define=ij_product=intellij-beta

**Comment by szinn** [comment]
This issue still occurs when building from master on a mac for intellij-canary.  tools.jar does not exist.  @jin as you authored the third_party/java/jdk/BUILD file that references this unavailable file.

**Comment by fandan-nyc** [comment]
got the same issue 
```
+ intellij::build intellij-ue-latest
+ local intellij_product=intellij-ue-latest
++ echo intellij-ue-latest
++ sed 's/-.*$//g'
+ local shortcut=intellij
+ local plugin_base=
+ case $shortcut in
+ plugin_base=ijwb
+ local build_dir=/tmp/build_output
+ bazel --output_user_root=/tmp/build_output build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-latest
INFO: Analyzed target //ijwb:ijwb_bazel_zip (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/lisipu/src/github/intellij/third_party/java/jdk/BUILD:7:8: Executing genrule //third_party/java/jdk:jdk_tools_jar failed (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp external/local_jdk/lib/tools.jar bazel-out/darwin-fastbuild/bin/third_party/java/jdk/tools.jar'

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cp external/local_jdk/lib/tools.jar bazel-out/darwin-fastbuild/bin/third_party/java/jdk/tools.jar'
```

**Comment by alice-ks** [comment]
This should be fixed by now. The current CI also executes the tests on Java 11 without issues.
