### ISSUE TITLE
Support for configuring minimum required plugin version

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/intellij#1128]
Because of this migration hook: https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/plugin/dependency/ProjectDependencyMigration.java#L38 the `externalDependencies.xml` file is written out every time the project is opened, not just on the initial import, which makes it impossible to configure the minimum required version and check it into the repo.

Given that the comment says it's `Temporary migration code`, can it be removed now?

**Comment by alice-ks** [comment]
I couldn't find that code anymore. Closing this issue as I assume that it was deleted in the meantime.
