### ISSUE TITLE
Behaviour of built in language plugins is affected even when language support is not enabled

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/intellij#1129]
I don't have many details on this at the moment, but we noticed the built in Typescript indexing doesn't work correctly with the plugin loaded, even when we don't enable Typescript and Javascript support.

To fix this we ended up removing `//javascript:plugin_library` as a dependency of the plugin when building it.

The plugin shouldn't be affecting the behaviour of the built in language plugins for languages that aren't enabled.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
