### ISSUE TITLE
Failures when filtering generated code prevent syncing

### ISSUE THREAD

**Issue by acatxnamedvirtue** [bazelbuild/intellij#1138]
Hello!

First off, thank you so much for this plugin! It's been a huge help here at Meetup with our bazel monorepo.

For some reason, we're experiencing an issue when syncing that looks like this:
*parts in [] are truncated for security reasons*

ERROR: [location of my BUILD file] Couldn't build file [module_name]-filtered-gen.jar: Filtering generated code for [build target] failed (Exit 1) JarFilter_bin failed: error executing command bazel-out/host/bin/external/intellij_aspect/JarFilter_bin --filter_jar bazel-out/darwin-fastbuild/bin/[module_name].jar --filter_jar ... (remaining 15 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Sep 03, 2019 10:22:28 AM com.google.idea.blaze.aspect.JarFilter main
SEVERE: Error filtering jars
java.util.zip.ZipException: duplicate entry: [generated_code_file].java
	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
	at com.google.idea.blaze.aspect.JarFilter.filterJars(JarFilter.java:262)
	at com.google.idea.blaze.aspect.JarFilter.main(JarFilter.java:125)
	at com.google.idea.blaze.aspect.JarFilter.main(JarFilter.java:93)

We do some weird code generation, so it isn't terribly surprising that there's an error, but I'm wondering if there's a way to skip this "filtering" process, or make it so that duplicate entries don't prevent syncing from succeeding (and thus leaving unsynced files).

Thanks in advance for any help you can provide!

Tyler Beebe
Senior Software Engineer
Platform Engineering
Meetup

**Comment by brendandouglas** [comment]
Looks like the JavaInfo provider involved has multiple source jars, with java source files duplicated across multiple jars.

I'll add a fix to handle this situation in the next release, but in the meantime there's no easy workaround, or any way to disable this filtering action programmatically.

**Comment by acatxnamedvirtue** [comment]
Debugging a little bit, I've been able to discover that the command that runs (and fails currently) does not fail if I remove the flag for --keep_source_jar [generated-code].srcjar

Thanks so much! I'll patiently wait for the next release :)
