### ISSUE TITLE
Support CLion 2017.2

### ISSUE THREAD

**Issue by daeyun** [bazelbuild/intellij#114]
I updated to CLion 2017.2 and I'm seeing this error

> com.google.idea.blaze.plugin.CMakeWorkspaceOverride@77e8e6df: tried to access field com.jetbrains.cidr.cpp.cmake.workspace.CMakeWorkspace.myProject from class com.google.idea.blaze.plugin.CMakeWorkspaceOverride

And sync works, but the IDE is stuck at "indexing", and auto-completion is not working.

**Comment by brendandouglas** [comment]
We haven't yet released a plugin version compatible with 2017.2.

I'll update this thread when we do (likely around late August).
