### ISSUE TITLE
Support CLion 2019.2

### ISSUE THREAD

**Issue by jin** [bazelbuild/intellij#1140]

**Comment by rangeli** [comment]
I'd be interested in this as well.  The latest version of the plugin currently supports 2019.1.4.

**Comment by da-phil** [comment]
Is there any plan according to when CLion 2019.2 will be supported?
I need to know whether I should just wait a couple of more days or install CLion 2019.1.
Thanks!

**Comment by chenkan0104** [comment]
+1 for CLion

**Comment by mattgodbolt** [comment]
Another +1. Also 2019.3 RC is already out; can we have a tracking issue for that too? Thanks so much!

**Comment by grefab** [comment]
Woohoo! It is there! :)

**Comment by jin** [comment]
Released: https://plugins.jetbrains.com/plugin/9554-bazel/update/69554
