### ISSUE TITLE
CLion/Intellij fail to execute bazel on Centos7

### ISSUE THREAD

**Issue by emidln** [bazelbuild/intellij#1156]
As of #ab22ca6, `setsid(1)` is used with a `--wait` parameter when launching bazel commands. CentOS 7 doesn't support the `--wait` flag for `setsid(1)`. 

A current workaround is to define (inside `~/.intellij-experiments`)
```
blaze.command.process.group=false
```

**Comment by jin** [comment]
Discussed offline with @rohanjoyce - we'll not be fixing this, as `--wait` was added more than 6 years ago. https://github.com/karelzak/util-linux/commit/0dde19974bcbb07ce977992ab04b7dfa752d99b3

Please update to a newer Centos version with `setsid` that supports `--wait`, or disable the experiment using the stated workaround.
