### ISSUE TITLE
Support IntelliJ 2017.2

### ISSUE THREAD

**Issue by fengyang0317** [bazelbuild/intellij#116]
It seems the PyUniversalTestsConfigurationProducer class referred in intellij/sdkcompat/v171/com/google/idea/sdkcompat/python/PyConfigurationProducersList.java does not exist anymore.

Is it safe to just remove that line?

**Comment by brendandouglas** [comment]
The sdkcompat package is there to support building against multiple IntelliJ plugin APIs.

PyUniversalTestsConfigurationProducer existed in 2017.1, so is referenced in sdkcompat/v171.

We haven't yet released a Bazel plugin version supporting 2017.2 -- I'll update this issue when we do.

**Comment by ittaiz** [comment]
Hi,
I saw a release was made 5 days ago. Does it contain the support for 2017.2?

**Comment by brendandouglas** [comment]
That one doesn't, but the next release should. You can also check the version compatibility listed on the jetbrains plugin repo (https://plugins.jetbrains.com/plugin/8609-bazel). 

We always restrict releases to at least the version it was compiled against, so the 'compatible builds' field on that website indicates which plugin API it supports.
