### ISSUE TITLE
Run arbitrary main in scala feature has been broken

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#1172]
Hi,
The ability to right click any main in a scala_library and run it has been broken recently. Unfortunately it wasn't recently enough so it was before the fine grain commits and we don't know which commit did it.
The current situation is that the run configuration is created with a correct before task (I see from the console the right _deploy jar is built) but then the run configuration is somehow configured incorrectly.
I'd love to contribute an e2e for this to cover future regression but not sure where to start.
@jin @brendandouglas would you accept an e2e for this feature? If so can you share a few pointers?

Thanks!

**Comment by liucijus** [comment]
This seems to fail finding artifact after this change:
https://github.com/bazelbuild/intellij/commit/98d0504fa70b3536184f610f5cee00391f772543#diff-c924e38cec968aa15f096048cb42b57fR185

**Comment by ittaiz** [comment]
@brendandouglas @jin @liucijus found that if we revert that one line the feature goes back to working. Would you be open to a PR reverting this?
We'd still love adding a test to protect from such a regression if you can point us towards where

**Comment by jin** [comment]
@ittaiz @liucijus can you provide a Scala repro example for this? For future issue reports, it will really help us if you can provide Scala repro projects as we don't really have expertise on the language.

**Comment by liucijus** [comment]
https://github.com/liucijus/bazel-scala-example can be used to reproduce the problem:
Import Bazel project, unselect scala in project view then click on the green run arrow next to Main class in `com.example.Main`. 
Expected: runs and prints "Hello!"
Actual: Red notification "Failed to find deployable jar when building //:mainlib"

**Comment by liucijus** [comment]
@jin, FYI, I had problems importing example project on custom build from master source: https://github.com/bazelbuild/intellij/issues/1183

**Comment by liucijus** [comment]
Thanks, @jin!
