### ISSUE TITLE
multi-module IJ project

### ISSUE THREAD

**Issue by rverma-nikiai** [bazelbuild/intellij#1173]
With the continuation of #1109, a separate ticket to track multi-module IJ project. The current behavior is there are only 2 predefined modules i.e .ijwb and the root directory. It would be great if we can introduce a fine-grain module system(or adapt existing modules system i.e module-info.java). Alternatively, we should be able to control modules to activate using .bazelproject file. 

@ittaiz please add if I missed something.

**Comment by jin** [comment]
This is https://github.com/bazelbuild/intellij/issues/179. Closing as dupe.
