### ISSUE TITLE
IJ Plugin UI strings refer to internal name Blaze instead of OSS name Bazel

### ISSUE THREAD

**Issue by virusdave** [bazelbuild/intellij#1175]
A few placed in the IJ plugin still display "Blaze" rather than "Bazel".
Example:
![image](https://user-images.githubusercontent.com/6148271/65049410-b1240c80-d933-11e9-9ad7-6063ef2f11d8.png)

![image](https://user-images.githubusercontent.com/6148271/65049433-b84b1a80-d933-11e9-94eb-e10350410e9a.png)

**Comment by jin** [comment]
This has been resolved in https://github.com/bazelbuild/intellij/commit/9aa67de97d01abaeb7fd051579fd3a7d49b16c6e, will be available in the next plugin release.
