### ISSUE TITLE
clion import tensorflow source code failed 

### ISSUE THREAD

**Issue by ccnankai** [bazelbuild/intellij#1177]
I want to try to import the tensorflow source using clion's bazel plugin, and tried many versions, but none of them succeeded. Has anyone succeeded? Please give me advice.
 

![2019-09-18 09-18-44 的屏幕截图](https://user-images.githubusercontent.com/33537489/65096234-d3329300-d9f6-11e9-8774-4f9e0a1118da.png)

**Comment by chaoren** [comment]
This seems like a bazel problem rather than specific to the IntelliJ plugin.
https://github.com/bazelbuild/bazel/issues/642

**Comment by ccnankai** [comment]
@chaoren   But i build sucessfully in terminal  use the version of bazel.

**Comment by chaoren** [comment]
Are you building the same targets in terminal vs in CLion?

The default .bazelproject file uses `//...`. If you can't build that on command line then you won't be able to build that in CLion. You can reduce the targets list in that case.

**Comment by ccnankai** [comment]
Sorry. I am a newbie, I can successfully build tensorflow on the command line   used this command “bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package”  ，but Clion cannot specify build options.
I imported the source code by following the steps below.
 Import bazel projdct->generate from BUILD file(not from scratch) -> ...  , is these steps correct.

**Comment by chaoren** [comment]
> but Clion cannot specify build options

You can add build options to the project view file. Bazel -> Edit Project View File, add a build_options section.

**Comment by ccnankai** [comment]
Which version are you using? I don't have this option under my bazel.
![image](https://user-images.githubusercontent.com/33537489/65297441-6f48cf80-db9a-11e9-88fd-7e7ac56d70db.png)

**Comment by jin** [comment]
> Import bazel projdct->generate from BUILD file(not from scratch) -> ... , is these steps correct.

Please try this instead: choose "Create from scratch" and enter this into the next screen:

```
directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  .

# Automatically includes all relevant targets under the 'directories' above
derive_targets_from_directories: false

targets:
  # If source code isn't resolving, add additional targets that compile it here
  //tensorflow/tools/pip_package:build_pip_package
  
build_flags:
  -c opt 
  --config=cuda
```

**Comment by chaoren** [comment]
There's a bazel button on the menu bar.

**Comment by ccnankai** [comment]
@jin 
 I am the first time a novice uses bazel. Because of the build_flas  -c opt  error, I removed the -c --config option. Finally compelete successfully. 
Next, when I read the source code, can the code be related to each other, and   use CTRL+   to enter the defined location, complete the jump? 
Thank you for your generous help.

**Comment by weinixuehao** [comment]
@ccnankai Do you fixed it ? I also meet this issue .
