### ISSUE TITLE
How to import the tensorflow source code with clion's bazel plugin

### ISSUE THREAD

**Issue by ccnankai** [bazelbuild/intellij#1182]
How to read the tensorflow source code with clion's bazel plugin, how to import and build, I can  read an navigate inside the code base.This problem has been bothering me for a week. Please let me know, failed many times .Thank your very much.

**Comment by chaoren** [comment]
Are you following the instructions from here?
https://ij.bazel.build/docs/import-project.html

Please be clear about which part of the process failed.

**Comment by ccnankai** [comment]
Follow the method taught by jin.   import bazel project -->choose "Create from scratch" -->  edit view file
directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  

# Automatically includes all relevant targets under the 'directories' above
derive_targets_from_directories: false

targets:
  # If source code isn't resolving, add additional targets that compile it here
  //tensorflow/tools/pip_package:build_pip_package
  
build_flags:
  -c opt 
  --config=cuda

Finally compelete successfully.

![image](https://user-images.githubusercontent.com/33537489/65366372-91535800-dc55-11e9-9013-eb0557d31b7a.png)

Why is the code on the left marked as unsynced ?
when I read the source code, can the code be related to each other, and use CTRL+ to enter the code defined location ?I can't read an navigate inside the code base..
![image](https://user-images.githubusercontent.com/33537489/65366374-96b0a280-dc55-11e9-9511-407d6eb90ee5.png)

**Comment by ccnankai** [comment]
@vladmos @vsiva @mikelikespie

**Comment by weinixuehao** [comment]
@ccnankai I have meet the same issue, Do you fixed it?

**Comment by ccnankai** [comment]
Solved, just import directly, know there is a tutorial

**Comment by StephenLeeUSTC** [comment]
> Solved, just import directly,

What? Could you please tell me how to do this...Really annoying.

**Comment by StephenLeeUSTC** [comment]
Just select the directory of tensorflow, and import from scratch...
