### ISSUE TITLE
spurious "--gunit_color=no" added when debugging

### ISSUE THREAD

**Issue by danieldanciu** [bazelbuild/intellij#119]
Using CLion 2017.1.3 on a Ubuntu 16 machine.

When running my project normally, all is peachy. When running in debug mode however, no matter what target I choose, CLion with Bazel is adding a `--gunit_color=no` argument to the command line that executes the binary. 
I have no idea where this argument is coming from, I haven't even found it by grepping the source code of the Bazel plugin nor in any of my CLion config files. Totally baffled.
Here's the full command I see in my Console:

 `/home/dd/.cache/bazel/_bazel_dd/1e0bb3bee2d09d2e4ad3523530d3b40c/execroot/__main__/bazel-out/local-dbg/bin/exp/vmu/vmu_eval_synthetic_main --gunit_color=no`
`ERROR: unknown command line flag 'gunit_color'`

**Comment by brendandouglas** [comment]
Sorry about that, this is a bazel plugin bug.

It has been fixed internally, we just need to upload an updated plugin to the JetBrains plugin repo, which is currently scheduled for August 11.

**Comment by danieldanciu** [comment]
Thanks for the quick reply!

I can't see that flag being set in BuildFlagsProviderImpl.java, so I am wondering if I just pull the code from github and build the plugin, would it fix the problem?

**Comment by danieldanciu** [comment]
Heh, pulled from github, built from source and it all works. Looks like the plugin published for CLion is not quite the same as the github version.

Thanks for your help, looking forward to new version of the plugin - nothing can beat CLion+Bazel as dev tools.
