### ISSUE TITLE
How to disable experimental features?

### ISSUE THREAD

**Issue by thomasj02** [bazelbuild/intellij#1191]
The plugin has a number of features in the source code that are listed as 'experiments'. One in particular, blaze.command.process.group, requires that the system have /usr/bin/setsid that supports the --wait flag. This isn't available even in modern versions for RedHat. 

How can I disable this experimental feature?

**Comment by chaoren** [comment]
You can do this:

```
echo blaze.command.process.group=0 >> $HOME/.intellij-experiments
```
