### ISSUE TITLE
Two minor Windows issues related to file separator

### ISSUE THREAD

**Issue by gmishkin** [bazelbuild/intellij#1203]
When importing a project, the contents of the `.bazelproject` file are stuffed into an editor control that can't handle carriage returns. This prevents importing projects on Windows.

When reading jdeps file it uses `ArtifactLocationDecoderImpl.outputArtifactFromExecRoot` to process the path to the file, there are forward slashes hardcoded in the method. This prevents external libraries from being loaded into the workspace

**Comment by jin** [comment]
:+1: thanks for applying the fix.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
