### ISSUE TITLE
Cannot "Go to source" of external libraries in Java projects

### ISSUE THREAD

**Issue by vmax** [bazelbuild/intellij#1206]
# Issue

_Go to source_ action (Cmd+Click on class name on macOS) only goes to class file if external Java library you go to does not follow Maven source file convention (i.e. `Someclass.java` from `com.example` package will be stored at `com/example/Someclass.java` inside the source JAR.

# Smallest reproducible example

Two bazel workspaces: `@a`, `@b`;

`a/BUILD`:

```
java_library(
    name = "anotherlib",
    srcs = ["Anotherlib.java"],
    visibility = ["//visibility:public"]
)
```

`a/AnotherLib.java`:

```
package com.smth;

public class Anotherlib {
    public Anotherlib() {
        System.err.println("ctor");
    }
}
```

`b/WORKSPACE`:

```
local_repository(
    name = "a",
    path = "/Users/vmax/work/GraknLabs/intellij-reproducible/a",
)
```

`b/BUILD`:

```
java_library(
    name = "main",
    srcs = ["Main.java"],
    deps = ["@a//:anotherlib"],
)
```

`b/Main.java`:

```
import com.smth.Anotherlib;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello");
    }
}
```

* Load `@b` in IntelliJ IDEA with Bazel plugin version `2019.08.19.0.6` (latest at the moment)
* _Go to source_ on `import com.smth.Anotherlib` line
    * expected: `Anotherlib.java`
    * got: `Anotherlib.class`

This root cause of this issue is bazelbuild/bazel#8277 but from what I understand Bazel team is not planning to modify the way source JARs are built.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
