### ISSUE TITLE
Double quotes are parsed incorrectly

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/intellij#1219]
### Problem
When manually entering additional bazel flags which contain quotes, the plugin changes the format.

### Setup:
![image](https://user-images.githubusercontent.com/5273755/65800437-59538580-e12b-11e9-8d99-29b0afdf9d2f.png)

### Result:
```
--test_filter=my.app.AppSpec "--test_arg=-testName \"Name of my spec\"" 
```

Other example:
```
--test_arg=-testName="Name of my spec"
```

Result
```
"--test_arg=-testName=Name of my spec"
```

### Versions
Plugin: `2019.08.19.0.6`
Bazel: `0.29.1`
Intellij: `2019.2.2`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
