### ISSUE TITLE
Missing Auto-sync functionality

### ISSUE THREAD

**Issue by wmmc88** [bazelbuild/intellij#1223]
According to https://ij.bazel.build/docs/bazel-plugin.html#automatic-sync, there should be an autosync option, but in CLion 2019.1.4 with plugin version 2019.08.19.0.5, the option seems to be missing. Looks like it was removed from UI in #899 . Not sure why. Is there another way to enable this?

**Comment by brendandouglas** [comment]
That's a bug in the docs -- auto-syncing isn't available for the bazel plugin.

**Comment by wmmc88** [comment]
Is there a reason that functionality was removed? Do builds auto-sync before actually building?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
