### ISSUE TITLE
feature request: testng runner generation support.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#123]
Bazel Version: 0.5.3
Plugin Version: 2017.07.05.0.2
Intelij Version: 2017.2.1

Specifically being able to use the built in intellij support for testng. Intelij cannot create runners for testng tests as would normally be possible in a mvn/gradle/sbt project.

Trying to launch a package of testng tests from intellij results in an error popup along the lines of "Cannot start compilation: the output path is not specified for module ".workspace".

I suspect this issue might touch upon other test frameworks / runners as well.

**Comment by brendandouglas** [comment]
Thanks for the feature request. If you have a Bazel test target, you can work around this by creating a run configuration for the target directly (e.g. by right-clicking on the test target in the BUILD file).

Similar to Bazel itself, the Bazel plugin has much better support for JUnit, as we've had little demand in the past for TestNG support.

We likely won't have the bandwidth to look at this in the short term, but I'll leave it open -- it's not a huge amount of work, so we may get to it at some point.

**Comment by ittaiz** [comment]
Brendan,
Is using the built in IntelliJ runners even possible in the plugin
architecture?
From what I was able to gather the plugin always delegates to Bazel which
of course doesn't know anything about IntelliJ's runners

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
