### ISSUE TITLE
Error messages are not clickable

### ISSUE THREAD

**Issue by susliko** [bazelbuild/intellij#1240]
I am using the plugin with Scala rules https://github.com/higherkindness/rules_scala.

And whenever I have a compilation error, its message looks like this:
```
ERROR: /my/project/dir/BUILD:7:1: ScalaCompile src/my_app/classes.jar failed (Exit -1)
[Error] src/main/scala/Main.scala:30: *some error*
```
Here the first line is clickable and leads to the BUILD file, corresponding to the target with error in its source code. 
But the second line, which should lead to the buggy source code, is not clickable.

Does this happen because I'm using Scala rules different from https://github.com/bazelbuild/rules_scala or it has to deal with my plugin installation?

**Comment by chaoren** [comment]
It's probably the brackets confusing our error parser.

**Comment by chaoren** [comment]
If you own those scala rules could you get the compile error to match what the parser expects?

https://github.com/bazelbuild/intellij/blob/3a9da3a60ff8509f990a8bed02bbd1d92b41d2c2/base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java#L185

**Comment by chaoren** [comment]
Or we can relax the start of line match.

**Comment by chaoren** [comment]
It looks like the `[Error]` prefix is added by zinc. bazelbuild/rules_scala doesn't do this. This error path format is sort of standardized over all compilers I believe, so I don't think we want to add special support for tools that interfere unnecessarily with the output line. You should take this over to higherkindness/rules_scala. Perhaps there's a zinc flag to disable the `[Error]` prefix for the compiler output.

**Comment by susliko** [comment]
I got it. Thanks!
