### ISSUE TITLE
Mapping of plugin versions to bazel versions they support

### ISSUE THREAD

**Issue by AkshayKhatriKodiak** [bazelbuild/intellij#1242]
Hello,

Is it possible to get a mapping of release versions to which bazel versions they support? I am currently on bazel version 0.23.2 and have been unable to find which version of the plugin supports it. I cannot get Clion to work for me unless I figure this out so this would be of great help, thanks!

**Comment by jin** [comment]
This is on my TODO list.

**Comment by cgbystrom** [comment]
@jin I took a stab at this, posted an idea of testing to https://github.com/cgbystrom/bazel-intellij-compatibility/tree/master Example output can be downloaded from "Releases".

I'm still not sure if just running with the aspects is enough to determine compatibility. Maybe you have a suggestion?

**Comment by jin** [comment]
This is awesome, and I think it's a good start with the aspect! Although this will not run through much of the plugin (non-aspect) code paths, it will catch many of the Starlark and BUILD related breakages.

I think this is something we can turn into a markdown table and publish on a Wiki page / checked in file. cc @brendandouglas

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
