### ISSUE TITLE
Collision with IDEs other than Idea, AndroidStudio and CLion

### ISSUE THREAD

**Issue by cromefire** [bazelbuild/intellij#1245]
All other IDEs seem to use the same directory (`.ijwb`) if you now try to open the project with 2 different IDEs (because `python` and `go` aren't supported in the same IDE), you get an error, that `.ijwb` already exists.

This is bad for multi-language workspaces with IntelliJ IDEs.

**Comment by chaoren** [comment]
Android Studio should be using `.aswb`, and CLion should be using `.clwb`.

**Comment by chaoren** [comment]
Oh, you mean everything besides Android Studio and CLion.

> because `python` and `go` aren't supported in the same IDE

You can have both in IntelliJ ultimate.

**Comment by chaoren** [comment]
Though, I guess we can just add more names. `gowb`, `pcwb`?

**Comment by chaoren** [comment]
You should be able to just open the existing project in the other IDE, then just change the languages in the .bazelproject file.

**Comment by cromefire** [comment]
> You can have both in IntelliJ Ultimate.

I guess you can, but pretty basic, there are pycharm and goland for it

> Though, I guess we can just add more names. gowb, pcwb?

That's what I'd propose, out of my head there are pycharm, goland, webstorm, rubymine, phpstorm, rider and appcode.

Either you'd just have an seperate folder for each, make it customizable or make projects be importable seperately. The first one seems to be the easiest.

> You should be able to just open the existing project in the other IDE, then just change the languages in the .bazelproject file.

You mean change the languages everytime I switch the IDEs? I often have then open in parallel they will probably fight with each other. It also seemed to not like specifying unsupported languages.

**Comment by chaoren** [comment]
> pretty basic, there are pycharm and goland for it

IntelliJ Ultimate contains all features of PyCharm and GoLand.

> make it customizable or make projects be importable seperately

It is actually customizable. You can edit the project data location when you import the project.

> open in parallel they will probably fight with each other

The bazel invocations will lock each other as well.

**Comment by chaoren** [comment]
Given that it's customizable, I'm going to abandon the change for more names.

**Comment by cromefire** [comment]
Totally did not see that, sorry
