### ISSUE TITLE
CLion can't find includes after importing project

### ISSUE THREAD

**Issue by praveen-srinivasan** [bazelbuild/intellij#125]
Hi,
CLion seems unable to find includes in my source files after importing the project. One relevant detail is that in my .bazelproject, in the directories: section, I listed a bunch of directories in my project (at the same level as my WORKSPACE file) instead of the default ".". Would that have something to do with the includes?

**Comment by brendandouglas** [comment]
Some things to check:
- are your source files built by Bazel targets in your .bazelproject 'targets' section?
- are you using a Mac and/or CLion 2017.2? (we don't yet support either use case, though the next release has support for 2017.2)
- do you get any errors when running a non-incremental sync (Bazel > Sync > Non-incremental sync)?

If that's all fine, we might need to look at a project reproducing the problem.

**Comment by praveen-srinivasan** [comment]
Ok - I am using CLion 2017.2 on Linux. So perhaps I should wait for the next release of the plugin.

**Comment by brendandouglas** [comment]
We do plan to add Mac support eventually, but have no immediate plans to do so.

#109 is the issue tracking this.
