### ISSUE TITLE
Set javascript to be supported in WebStorm

### ISSUE THREAD

**Issue by cromefire** [bazelbuild/intellij#1250]
![image](https://user-images.githubusercontent.com/26320625/66517254-160df500-eae3-11e9-90fe-fbe8fe0b4db1.png)

But Javascript (and Typescript) is supported in WebStrom (obviously)

**Comment by chaoren** [comment]
Which version of the blaze plugin are you using?

**Comment by chaoren** [comment]
That error message has been removed for a while now. Please update to a recent plugin version.

**Comment by cromefire** [comment]
I use the latest published (2019.09.03.0.0)

**Comment by cromefire** [comment]
No updates available

**Comment by cromefire** [comment]
Also the latest IDE version and all other plugins are also on their latest version

**Comment by cromefire** [comment]
But you are right I can't find this in the code, maybe a new version needs to be published?

**Comment by chaoren** [comment]
Yeah sorry there's something wrong with our release script for the past month apparently.

**Comment by chaoren** [comment]
Updates are available now: https://plugins.jetbrains.com/plugin/8609-bazel
