### ISSUE TITLE
Clion plugin does not work with 2017.2.1

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/intellij#126]
I tried the plugin from the repository, as well as building from HEAD. In both cases, the plugin works with 2017.1.3 but not with 2017.2.1.

It is the same on both Linux and Mac. On Mac, I am using a custom toolchain through the --crosstool_top flag to get around #109. This is the error I receive:

> Error:Could not build C compiler settings map: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: While loading class com.google.idea.blaze.cpp.BlazeCompilerSettings: class com.google.idea.blaze.cpp.BlazeCompilerSettings has interface com.jetbrains.cidr.lang.workspace.compiler.OCCompilerSettings as super class [Plugin: com.google.idea.bazel.clwb]

**Comment by brendandouglas** [comment]
The next release, scheduled for next week, will support 2017.2. Also see #114

**Comment by siddharthab** [comment]
Thank you , I just thought it worthy of reporting because I was using a plugin built from HEAD.

**Comment by brendandouglas** [comment]
Ah, thanks. This repository is really just here for educational purposes, and isn't kept up-to-date. We build the plugins from a more recent version of the code base.
