### ISSUE TITLE
Bazel plugin for Intellij sets wrong kotlin version

### ISSUE THREAD

**Issue by CharlieCrisp** [bazelbuild/intellij#1274]
I have recently upgraded to the these rules (commit `ab2f9f79912a35af3c1a07849d6fb457c2bfc54b`) and when trying to use Kotlin 1.3 in IntelliJ, I noticed the kotlin "Language version"/"API Version", gets set by the Bazel plugin to be 1.2 on every 'sync'. 

- I'm definitely using 1.3. as bazel builds from the terminal compile 1.3 features. 
- IntelliJ gives a quick-fix using alt-enter that removes the red squiggly lines, however this error comes back upon bazel sync.
- Setting the toolchain manually allows the "Language version"/"API Version" to remain at 1.3 but the error still comes upon syncs and the quick-fix works until the next sync.

**Comment by jin** [comment]
This sounds like an IJwBazel issue. Transferred to bazelbuild/intellij.

**Comment by jin** [comment]
Please provide your version information (IntelliJ Menu -> Bazel -> File an Issue on GitHub, and copy the version information here)

**Comment by CharlieCrisp** [comment]
#### Version information
IdeaUltimate: 2019.2.3
Platform: Mac OS X 10.14.6
Bazel plugin: 2019.10.01.1.1
Bazel: 0.28.1

Problem
![Screenshot 2019-10-18 at 17 05 19](https://user-images.githubusercontent.com/23122367/67110035-bd68e700-f1c9-11e9-93e0-39f16368674f.png)

language setting
![Screenshot 2019-10-18 at 17 05 07](https://user-images.githubusercontent.com/23122367/67110059-c8237c00-f1c9-11e9-9268-eab5c4f208a0.png)

Choosing the quick fix solves the problem until hitting the sync button when it reverts. Language version (as per the second screenshot) is _always_ set to 1.3

**Comment by CharlieCrisp** [comment]
So I may have fixed this by adding kotlin to the `additional_languages` in the `.bazelproject`. Not sure why it has the observed behaviour without this though

**Comment by cgruber** [comment]
What I'm wondering (@jin, @brendandouglas) is whether there's metadata that ought to be given to the aspect, that identifies the kotlin language version (we have that data in the rules_kotlin toolchain).  I just don't know where you need to get that info into the plugin, and if it's just something we need to add to the aspect?

**Comment by brendandouglas** [comment]
That is something we'd like to pick up for external rules.

For internal kotlin rules, we get both the language version and SDK library
jars from the toolchain target, and pass them through to the plugin
(KotlinToolchainIdeInfo).

Last I checked (~1-2 years ago) we couldn't do this for the external rules,
but sounds like that info is available to aspects now?

**Comment by szinn** [comment]
https://github.com/bazelbuild/intellij/pull/1473

Submitted this PR to default the Kotlin version to be 1.3

**Comment by jasonwyatt** [comment]
This is an incredibly frustrating issue given 1.3 has been out for several months now, and 1.4 is coming up quickly. 

It would be nice to have a field available in the project view file to specify which version to allow.

**Comment by szinn** [comment]
Submitted PR https://github.com/bazelbuild/intellij/pull/1566 to pull the version information from the rules_kotlin build

**Comment by DrewKiino** [comment]
bump - can we get this fixed please?
