### ISSUE TITLE
Intellij responding very slow (in minutes) for any user interaction

### ISSUE THREAD

**Issue by kkewlani** [bazelbuild/intellij#128]
I have been using intellij CE 2016.2 for few months now. Since yesterday, it has almost stopped responding to mouse clicks or any kind of interaction. 
I tried checking the logs and found there is some kind of Java Heap Space going on in idea.log
So, I tried increasing the heap space for both intellij and java compiler but none of them works. 

It starts fine but after a minute or so it becomes unresponsive. In order to make the above changes I had to restart it multiple times to get it through but still no good.

Following are the things I have tried:
1. Uninstalled intellij CE 2016.2 and installed CE 2017.2, without removing plugins
2. Did above step by removing plugins
3. installed intellij UE 2016.3 after removing plugins
4. restarted laptop multiple times

With all the above steps, it seems that there might be some other process on my system which might be causing intellij to have this issue. I tried to figure that out by looking into thread dump but it does not help.
It will be really helpful if someone can help me in debugging process to find the real issue and then I can look for some solutions.

I am attaching the log files (idea.log and thread dump). The logs are from Idea UE 2016.3 
[intellij_issue_logs.zip](https://github.com/bazelbuild/intellij/files/1262221/intellij_issue_logs.zip)

Adding logs from idea start up till the issue starts happening
[intellij_issue_logs_from_startup.zip](https://github.com/bazelbuild/intellij/files/1262243/intellij_issue_logs_from_startup.zip)

idea.vmoptions:

-Xms2g
-Xmx3g
-XX:ReservedCodeCacheSize=1024m
-XX:+UseCompressedOops
-XX:MaxPermSize=3072m

**Comment by kkewlani** [comment]
Adding logs from idea start up till the issue starts happening
[intellij_issue_logs_from_startup.zip](https://github.com/bazelbuild/intellij/files/1262243/intellij_issue_logs_from_startup.zip)

**Comment by kkewlani** [comment]
idea.vmoptions:
# custom IntelliJ IDEA VM options

-Xms2g
-Xmx3g
-XX:ReservedCodeCacheSize=1024m
-XX:+UseCompressedOops
-XX:MaxPermSize=3096m

**Comment by brendandouglas** [comment]
If you're having performance problems, best to raise a bug on the JetBrains issue tracker: https://youtrack.jetbrains.com/issues/IDEA

It's generally not a problem with this Bazel plugin specifically.

In your case, this plugin doesn't show up in your logs (presumably it was already uninstalled), so it's definitely an issue with IntelliJ itself, or one of the custom plugin that is installed.
