### ISSUE TITLE
Clion bazel plugin for bazel 0.5.0

### ISSUE THREAD

**Issue by histfuture** [bazelbuild/intellij#1284]
Are there any version of clion bazel plugin support bazel 0.5.0?

**Comment by jin** [comment]
Bazel 0.5.0 was released in May 2017, so we're looking at the IntelliJ and plugin versions that were released around Mid 2017.

We no longer support Bazel 0.5.0.

**Comment by histfuture** [comment]
@jin  Since my project is managed by bazel 0.5.3, what is the oldest bazel version that supported by this plugin?

**Comment by jin** [comment]
Probably one of the earliest versions: https://plugins.jetbrains.com/plugin/8609-bazel/update/42692
