### ISSUE TITLE
Doesn't accurately generate .workspace.iml file

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/intellij#1289]
#### Description of the issue. Please be specific.
In my project it generates the wrong `packagePrefix` 

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Not sure, for some project it works for some it doesn't. I couldn't pin point what exactly makes it break. 

#### Version information
IdeaCommunity: 2019.2.2
Platform: Linux 4.15.0-1057-oem
Bazel plugin: 2019.09.03.0.0
Bazel: 0.29.1

**Comment by sgowroji** [comment]
I'll close the issue. If you still can reproduce it, please reopen.
