### ISSUE TITLE
Import Bazel Project dialog is broken on 2019.3

### ISSUE THREAD

**Issue by jin** [bazelbuild/intellij#1296]
<img width="463" alt="Screen Shot 2019-10-21 at 1 52 19 PM" src="https://user-images.githubusercontent.com/347918/67229824-1626c280-f40a-11e9-929b-08da82ae3c41.png">

**Comment by alice-ks** [comment]
Does this issue still occur? I'm not aware that it would still be present in recent plugin versions within IntelliJ 2020.2. I'm assuming that we fixed this issue in the meantime. Please re-open this bug if you're still running into it.
