### ISSUE TITLE
Feature Request: Allow easier editing of a Bazel external source code when used as new_local_repository

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/intellij#130]
I am developing a small library that is consuming a framework that we are developing, and for ease of use, I would like to be able to edit an external while consuming it in a project.

For my first attempt, I added my external project, and tried to ensure that its files are accessible via `.bazelproject`. Say my projects are `upstream` and `downstream`, such that it is organized as:

* downstream/
     * externals/
         * upstream/

If I navigate to `upstream`, open up a source file, and toggle to the header file, it opens the symlink'd version buried within Bazel's cache, which makes sense due to how the includes are structured.
However, I would like it to open up the project version of the file (which in this case is neighboring the source file), so that project-level code inspection works as expected (Find Usages, etc.).

An initial thought is to write a quick plugin that hooks into any Open Document events, and just resolves the symlink (at least on a Unix system) using something like `readlink -f ${path}` (or even just resolves one level of the symlink, e.g. if I've symlinked my external in for development).

EDIT: It looks like another intermediate would be to change `ArtifactLocationDecoderImpl` to enforce symlink resolution, possibly using the OS version if necessary (at least as a local hack for myself).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
