### ISSUE TITLE
Integration test coverage for generating deployable jar task provider

### ISSUE THREAD

**Issue by ZachiNachshon** [bazelbuild/intellij#1308]
Hey, 

I would like to add an integration test to cover the previously **closed** issue https://github.com/bazelbuild/intellij/issues/1172.
`GenerateDeployableJarTaskProviderTest`  should cover the ability to generate a deployable jar task provider in `scala_library`.

Thanks,
Zachi

**Comment by jin** [comment]
Happy to take additional tests.

**Comment by ZachiNachshon** [comment]
Hey @brendandouglas ,

After looking into the `GenerateDeployableJarTaskProviderTest` flow I wish to implement, it seems more beneficial to implement an end-to-end test based on the [`BazelInvokingIntegrationTest`](https://github.com/bazelbuild/intellij/blob/master/aspect/testing/tests/src/com/google/idea/blaze/aspect/integration/BazelInvokingIntegrationTest.java) that actually builds a deployable jar.

The actual problem for [this issue](https://github.com/bazelbuild/intellij/issues/1172) was the fact that although IntelliJ had a valid run configuration before-launch build step, it failed building a deployable jar.

I believe that by only testing IntelliJ Swing UI, we might miss proper coverage in case of additional changes to this task flow.

I'll be glad to get your input on the matter. In case you think it's not a valid point, It'll be great to hear how do you suggest to properly add good coverage for this task.

Thanks

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
