### ISSUE TITLE
No way to filter for a specific Test methods using ASwB UI

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/intellij#1313]
#### Description of the issue. Please be specific.

When clicking on a small play buttons on the gutter to the left of each test method. I expect it to run only that specific test method. However, it runs all tests in the entire class.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Create a test class with multiple test and attempt to run it

#### Version information
AndroidStudio: 3.5.1
Platform: Linux 4.15.0-1057-oem
Bazel plugin: 2019.10.01.1.1
Bazel: 0.29.1

**Comment by nkoroste** [comment]
@jin I would say it's more of a bug since that's the expect behavior if you compare to what intallij/AS does natively for java or AS with gradle.

**Comment by ThomasCJY** [comment]
Also might be related: if a test is named inside quote like this `` `testName in quote` ``, click the test button will cause error due to the quote being ignored 
```
ERROR: Skipping 'in': no such target '//:in': target 'in' not declared in package '' defined by xxx
```

**Comment by ThomasCJY** [comment]
nvm the quote issue is a false alarm. I created a test repo and verified the test button is only a problem for kotlin tests, java tests is working well. 
https://github.com/bazelbuild/examples/pull/153

**Comment by nkoroste** [comment]
@cgruber fyi about the kotlin rules comment

**Comment by mai93** [comment]
@nkoroste are you still seeing this with new versions of the plugin/IDE?

**Comment by mai93** [comment]
Closing this issue, if you still see it in latest IDE and plugin versions, please reopen.
