### ISSUE TITLE
Import TensorFlow

### ISSUE THREAD

**Issue by joetoth** [bazelbuild/intellij#132]
Using clion 2017.2 and tried a few different versions of bazel to sync tensorflow in order for intellij to index the files. Is there any version of bazel that works? Is the tensorflow project known to import successfully?

**Comment by jvoung** [comment]
Did you run the ./configure script for setup? (https://github.com/bazelbuild/intellij/issues/99#issuecomment-308763905)

What OS (Mac, Win, Linux)?

I tried with plugin Version: 2017.08.29.0.2
IDE version CLion 2017.2.2
tensorflow git commit 8d2a9903128537f7e6bd64c4ca0d1e118962ec31
Bazel version 0.5.2
on Linux

Seems to work okay, though there are some build errors like [1]
E.g., I can goto-definition of "SharedGrpcChannelPtr" from grpc_channel.cc line 251 (return type of FindChannelOnce)

[1] "third-party rule '//third_party/toolchains/cpus/arm:toolchain' lacks a license declaration with one of the following types: notice, reciprocal, permissive, restricted, unencumbered, by_exception_only."
I haven't tried newer bazel versions, maybe that will help with this bit.

**Comment by joetoth** [comment]
Ah awesome, forgot to do that. Seems to work really well. Thanks!

**Comment by ccnankai** [comment]
@joetoth  @jvoung 
Can you successfully import tensorflow, the code can jump successfully? Can you tell me how to configure it? Thank you
