### ISSUE TITLE
Trouble with paths in directories section of .bazelproject when importing project

### ISSUE THREAD

**Issue by LizardWizzard** [bazelbuild/intellij#1322]
Hello thank you for your plugin!

I have troubles with importing project and when I typed in directories of .bazelproject path `..` logs of clion was flooded with exceptions like this:
```
java.lang.IllegalArgumentException: File '/home/me/src' is not under workspace /home/me/src/my_bazel_project
	at com.google.idea.blaze.base.model.primitives.WorkspaceRoot.workspacePathFor(WorkspaceRoot.java:88)
	at com.google.idea.blaze.base.model.primitives.WorkspaceRoot.workspacePathFor(WorkspaceRoot.java:82)
``` 
I understand that this path is incorrect, but when I deleted incorrect path even after restart of clion this error persists so I have to remove `.clwb` and reinstall the plugin.

I tried the above because default configuration with `.` in directories didnt load any source code, but when I entered certain directory it worked. So `.` in directories gives nothing, but path to subdir gives all associated targets. Is this behaviour correct?

Thanks in advance

#### Version information
CLion: 2019.2.4
Platform: Linux 5.0.0-31-generic
Bazel plugin: 2019.10.14.0.0
Bazel: 0.27.2

**Comment by convoi** [comment]
I believe I have a similar issue with IntelliJ Idea 2019.2.4
Before that I could use . as directory and it would resolve my project nicely.
Now I have to specify all directories directly to get anything to show up at all and the root directory cannot be added - meaning WORKSPACE and main BUILD file are not in my project anymore.

**Comment by LizardWizzard** [comment]
I've also encountered this after upgrading from late 2018 version

**Comment by chaoren** [comment]
IIRC, there was a change to hide certain files from the root. That might have caused this issue.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
