### ISSUE TITLE
CLion debug test "address in use"

### ISSUE THREAD

**Issue by mattgodbolt** [bazelbuild/intellij#1326]
When I try and debug a test in CLion I get a test failure, with this in the test output:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //ticks2hdf5:test
-----------------------------------------------------------------------------
Can't bind address: Address already in use.
Exiting
retaining work directory: /tmp/gdbserver_wrapper.UNv5UsDs
```

Looks related to #863 as a lot later an error popup at the bottom of the IDE has a `com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: tcp.localhost:5006: Connection time out` error.

This is with CLion:

```
CLion 2019.2.3
Build #CL-192.6817.18, built on September 24, 2019
Licensed to Matt Godbolt
Subscription is active until April 15, 2020
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.18-200.fc30.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 36
Registry: run.processes.with.pty=TRUE, cidr.max.intellisense.file.length=750000, clion.remote.resync.system.cache=true
Non-Bundled Plugins: com.compilerexplorer.compilerexplorer, io.protostuff.protostuff-jetbrains-plugin, org.intellij.plugins.markdown, com.google.idea.bazel.clwb, org.sylfra.idea.plugins.linessorter, org.toml.lang, org.rust.lang
```

and bazel plugin 2019.10.14.0.0

**Comment by garethellis0** [comment]
I was able to resolve this particular issue by running `pkill -9 gdb`. Obviously not an _ideal_ solution, but it works.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
