### ISSUE TITLE
Jar cache / IntelliJ index corruption

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#1336]
TLDR:
We had a case where a source file wasn't able to resolve another source file from a different target.
Bazel build passed, syncs and even non-incremental syncs didn't resolve the issue but only manually deleting the file of the "problematic" target from the jar cache (`.ijwb/.blaze/libraries`) resolved the issue.

Any thoughts?

More info:
Unresolved file was from `scala_proto_library` and using file belongs to `scala_library`.
Both targets are under `targets` view.

**Comment by brendandouglas** [comment]
That sounds like a serious bug. If you find a way to reproduce it, please let us know and we'll fix it urgently.

Without a way to reproduce it's going to be difficult to track down though.

**Comment by ittaiz** [comment]
Yeah, thought the same. Hoped you’d might have an “aha moment” so tried my
luck.

Any ideas maybe on how to reproduce?

**Comment by ittaiz** [comment]
Just wanted to update that it has happened to 4 more users internally.
Still can't reproduce...

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
