### ISSUE TITLE
can not find toolchain when sync tensorflow on MacOS

### ISSUE THREAD

**Issue by jacquesqiao** [bazelbuild/intellij#134]
> Warning:cc target //tensorflow/contrib/boosted_trees:split_handler_ops_op_lib does not depend on exactly 1 cc toolchain.  Found 0 toolchains.

Hi, I have problems build tensorflow with this plugin on MacOS.

how to build tensorflow with Bazel plugin on MacOS？Is it supports now?

**Comment by brendandouglas** [comment]
We don't yet support using the CLion plugin on Macs. Closing this as a dupe of https://github.com/bazelbuild/intellij/issues/109
