### ISSUE TITLE
Bazel version issue with Mediapipe.

### ISSUE THREAD

**Issue by afsaredrisy** [bazelbuild/intellij#1342]
/home/user/Med/mediapipe-master/WORKSPACE:13:1: Traceback (most recent call last):
	File "/home/user/Med/mediapipe-master/WORKSPACE", line 13
		versions.check(minimum_bazel_version = "0.24.1", ...")
	File "/home/user/.cache/bazel/_bazel_user/0777cb37d575e5092fe0b62d55a00d51/external/bazel_skylib/lib/versions.bzl", line 116, in versions.check
		fail("Current Bazel version is {}; ex...))
Current Bazel version is 1.0.0; expected at most 0.29.1

link for WORKSPACE file
https://github.com/google/mediapipe/blob/master/WORKSPACE

**Comment by brendandouglas** [comment]
This is unrelated to the IntelliJ plugin -- it's either an issue with bazel itself, or whatever else is doing that version check (bazel_skylib?)

Could you file a bug with bazelbuild/bazel instead?
