### ISSUE TITLE
expected value of type 'CcToolchainInfo' for parameter 'cc_toolchain'

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/intellij#1344]
Running into this with Bazel 1.1.0 and IJ plugin 2019.10.14.0.0 (IntelliJ 2019.2). It occurs whenever the target field in .bazelproject includes a cc_toolchain rule. (It handles cc_toolchain_suite just fine.)

Steps to reproduce:
- Follow https://docs.bazel.build/versions/1.1.0/tutorial/cc-toolchain-config.html to set up a C++ toolchain. (NB: The emscripten-clang archive is no longer available for download. You may need comment that out and use a `new_local_repository` to point to a locally installed version.)
- Import the project into IJ. Include `//toolchain:asmjs_toolchain` under `targets` in `.bazelproject`.
- Click the Sync button.

```
ERROR: .../examples/cpp-tutorial/stage1/toolchain/BUILD:23:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_toolchain rule //toolchain:asmjs_toolchain: 
Traceback (most recent call last):
	File ".../examples/cpp-tutorial/stage1/toolchain/BUILD", line 23
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File ".../3e98d693ee240ac89ffd9fa8af1040a7/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(<3 more arguments>)
	File ".../3e98d693ee240ac89ffd9fa8af1040a7/external/intellij_aspect/intellij_info_impl.bzl", line 916, in intellij_info_aspect_impl
		collect_c_toolchain_info(target, <5 more arguments>)
	File ".../3e98d693ee240ac89ffd9fa8af1040a7/external/intellij_aspect/intellij_info_impl.bzl", line 453, in collect_c_toolchain_info
		cc_common.configure_features(<4 more arguments>)
expected value of type 'CcToolchainInfo' for parameter 'cc_toolchain', for call to method configure_features(ctx = None, cc_toolchain, requested_features = [], unsupported_features = []) of 'cc_common'
```

I added some debugging statements to `intellij_info_impl.bzl` (affecting line numbers) and discovered the following:

```
DEBUG: .../3e98d693ee240ac89ffd9fa8af1040a7/external/intellij_aspect/intellij_info_impl.bzl:439:5: <target //toolchain:asmjs_toolchain, keys:[ToolchainInfo, OutputGroupInfo]>
DEBUG: .../3e98d693ee240ac89ffd9fa8af1040a7/external/intellij_aspect/intellij_info_impl.bzl:440:5: struct()
DEBUG: .../3e98d693ee240ac89ffd9fa8af1040a7/external/intellij_aspect/intellij_info_impl.bzl:441:5: ToolchainInfo
```

Even though the cc_toolchain rule advertises the `cc_common.CcToolchainInfo` provider, what's returned via `target[cc_common.CcToolchainInfo]` is a plain `ToolchainInfo`.

The following patch appears to the sidestep the issue, but I don't know that it's correct:

```diff
beasleyr@beasleyr-a02 aspect> diff -u intellij_info_impl.bzl{.orig,}
--- intellij_info_impl.bzl.orig	2019-11-04 11:05:11.000000000 -0500
+++ intellij_info_impl.bzl	2019-11-04 11:15:39.000000000 -0500
@@ -432,6 +432,8 @@
         return False
     if cc_common.CcToolchainInfo not in target:
         return False
+    if type(target[cc_common.CcToolchainInfo]) != "CcToolchainInfo":
+        return False
 
     # cc toolchain to access compiler flags
     cpp_toolchain = target[cc_common.CcToolchainInfo]
```

**Comment by beasleyr-vmw** [comment]
I have a potential PR, but the PR checklist requires prior discussion w/ maintainers.

cc @brendandouglas @jin

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
