### ISSUE TITLE
IntelliJ Sync issues opening the plugin

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/intellij#1355]
I'm trying to contribute towards the plugin, specifically for CLion. However, everytime I import the workspace and import the `clwb` project view, I get a lot of red lines and missing imports when looking at the CLion plugin source, making the IDE useless. I've tried both Ubuntu and macOS, on Bazel 0.29.1. Any ideas?

**Comment by wesleyw72** [comment]
@jin also tried it at BazelCon and got similar issues.

**Comment by jin** [comment]
Oh, I forgot that you have to set up the correct IntelliJ/CLion SDK in the project structure to make this work. 

Specifically: https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html

**Comment by alice-ks** [comment]
Yes, setting up the correct IntelliJ/CLion SDK is important. As there hasn't been any comments since Dec 2019, I assume that this issue isn't current anymore and can be closed.
