### ISSUE TITLE
Disabling remote upload local results when generating an arbitrary deployable jar

### ISSUE THREAD

**Issue by ZachiNachshon** [bazelbuild/intellij#1359]
Hey, 

I would like to suggest about adding the [`--remote_upload_local_results=false`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--remote_upload_local_results) as a permanent flag to [`GenerateDeployableJarTaskProvider.java`](https://github.com/bazelbuild/intellij/blob/master/scala/src/com/google/idea/blaze/scala/run/producers/GenerateDeployableJarTaskProvider.java).
Uploading local arbitrary main jar content is time consuming, pollutes the remote cache and usually redundant.
It'll be great to get some inputs about the topic, think it's a useful feature that might save time for everyone involved.
It's already implemented internally here at Wix and we can see a lot of value from it which we would like to share with the rest of the Scala community.

Thanks

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
