### ISSUE TITLE
"builtin_include_directories" Are Not Used With Custom Toolchain and CLion

### ISSUE THREAD

**Issue by garethellis0** [bazelbuild/intellij#1368]
#### Description of the issue. Please be specific.
When using a custom toolchain with bazel, the `builtin_include_directories` in the `cc_toolchain_config` do not seem to be picked up by the plugin. This manifests with the plugin being unable to find the standard library files. My current fix is to manually `-isystem` flags to the compiler for each of the builtin include directories, like so:
```
    builtin_include_directories_feature = feature(
        name = "builtin_include_directories",
        flag_sets = [
            flag_set(
                actions = [ACTION_NAMES.c_compile, ACTION_NAMES.cpp_compile],
                flag_groups = [flag_group(
                    flags = [
                        "-isystem{}".format(dir)
                        for dir in ctx.attr.builtin_include_directories
                    ],
                )],
            ),
        ],
    )
```

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Happy to provide a repro for this, but it's a fair bit of work together, so would just like to confirm this is not expected behavior first!

#### Version information
CLion: 2019.2.2
Platform: Linux 5.0.0-32-generic
Bazel plugin: 9999
Bazel: 1.0.1

Thanks! :tada:

**Comment by LittleHuba** [comment]
This is still an issue with CLion 2022.2.4 and bazel plugin version 2022.10.18.0.1 and blocks usage of hermetic toolchains in CLion.

**Comment by garethellis0** [comment]
Oh man. It's been over 3 years now, so I definitely don't recall all the details of this. Looking at the codebase this came from, that team has moved on toolchain-wise, but [here] is an example of how we had it setup. 

Not exactly _minimal_, but hopefully should help.
