### ISSUE TITLE
can not import google jsonnet project

### ISSUE THREAD

**Issue by mqliang** [bazelbuild/intellij#137]
I want to use Jetbrains Clion to develop project jsonnet(https://github.com/google/jsonnet). Unfortunately I can not import it:

![image](https://user-images.githubusercontent.com/12423751/31171381-648751c8-a93a-11e7-878f-210371edc15c.png)
![image](https://user-images.githubusercontent.com/12423751/31171388-6cd44e94-a93a-11e7-92e8-3499decab3ff.png)
![image](https://user-images.githubusercontent.com/12423751/31171399-8103121a-a93a-11e7-8038-390798559973.png)
![image](https://user-images.githubusercontent.com/12423751/31171415-9297f658-a93a-11e7-9f74-3a0f4e9b120d.png)
![image](https://user-images.githubusercontent.com/12423751/31171430-9e3e5420-a93a-11e7-9a2a-0fe268072aec.png)

**Comment by mqliang** [comment]
If I select to "Create from scratch" instead of "Import form workspace", then Clion can not find include files.

![image](https://user-images.githubusercontent.com/12423751/31171523-f6b3e110-a93a-11e7-88ea-45ab2a61347d.png)

![image](https://user-images.githubusercontent.com/12423751/31171530-fe6927b2-a93a-11e7-9773-0f292d015bd5.png)
![image](https://user-images.githubusercontent.com/12423751/31171559-1ab6af98-a93b-11e7-844c-c2e9d3694156.png)

**Comment by brendandouglas** [comment]
The 'import from workspace' option is for existing Bazel plugin projects (the wording needs to be improved), and requires a .bazelproject file (documentation [here](http://ij.bazel.build/)).

The issue with standard libraries not resolving on macs is #109. The plugin is not yet supported on macs, though we do intend to add support in the future.

**Comment by brendandouglas** [comment]
I've removed the reference to 'workspace' from that import option for the next release, to make it less confusing.
