### ISSUE TITLE
Coverage cannot find source file when package does not align with root

### ISSUE THREAD

**Issue by d-haxton** [bazelbuild/intellij#1372]
The core issue stems from https://github.com/bazelbuild/intellij/blob/b67030706e8ce4b219a373fc7468bc1614d62e93/java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageRunner.java#L68 where it attempts to "resolve" the file emitted from bazel's coverage.

Unfortunately, that path is constructed via bazel by using the package name: https://github.com/bazelbuild/bazel/blob/master/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoLCOVFormatter.java#L107

What this means is that if the package root is not the workspace root the `WorkspacePathResolver` will not be able to find the file (due to missing folders from the workspace to the package root).

It seems there's a workaround for java (https://github.com/bazelbuild/intellij/blob/b67030706e8ce4b219a373fc7468bc1614d62e93/testing/test_defs.bzl#L116) although I haven't been able to test this or see if this is true at all (a brief readthrough of the code would imply this fixes the issue). 
This does not work for non-java languages such as scala. 

If the answer is to implement this functionality in rules_scala, then I suppose I can take that on. Currently I'm using a hacky-work around which solves my use case.

Historically, `WorkspacePathResolverImpl` had access to `BazelRoots` (now deprecated) which would have found the file (if my understanding of what `BazelRoots` are is correct). See: https://bazel.googlesource.com/intellij/+/a6397369244de2e6afa1627fe9a5637e13322bff/base/src/com/google/idea/blaze/base/sync/workspace/WorkspacePathResolverImpl.java

I'm more than happy to contribute here (if you would like). Some guidance about where or which solution would be incredibly helpful.

**Comment by d-haxton** [comment]
For what it's worth. Here is my patch / current work around:

```
diff --git a/java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageRunner.java b/java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageRunner.java
index f7472e58..c8374f79 100644
--- a/java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageRunner.java
+++ b/java/src/com/google/idea/blaze/java/run/coverage/BlazeCoverageRunner.java
@@ -17,6 +17,8 @@ package com.google.idea.blaze.java.run.coverage;
 
 import com.google.common.annotations.VisibleForTesting;
 import com.google.common.primitives.Ints;
+import com.google.idea.blaze.base.ideinfo.ArtifactLocation;
+import com.google.idea.blaze.base.ideinfo.TargetIdeInfo;
 import com.google.idea.blaze.base.model.BlazeProjectData;
 import com.google.idea.blaze.base.settings.Blaze;
 import com.google.idea.blaze.base.sync.data.BlazeProjectDataManager;
@@ -29,10 +31,9 @@ import com.intellij.openapi.diagnostic.Logger;
 import com.intellij.rt.coverage.data.ClassData;
 import com.intellij.rt.coverage.data.LineData;
 import com.intellij.rt.coverage.data.ProjectData;
-import java.io.File;
-import java.io.FileInputStream;
-import java.io.IOException;
-import java.io.InputStream;
+
+import java.io.*;
+import java.util.HashSet;
 import javax.annotation.Nullable;
 
 /** Loads coverage data when blaze invocation is complete. */
@@ -51,8 +52,18 @@ public class BlazeCoverageRunner extends CoverageRunner {
     if (blazeProjectData == null) {
       return null;
     }
+    HashSet<String> sourceFiles = new HashSet<>();
+
+    for (TargetIdeInfo targetIdeInfo : blazeProjectData.getTargetData().targetMap.targets()) {
+      for (ArtifactLocation artifactLocation : targetIdeInfo.getSources()) {
+        if (artifactLocation != null) {
+          sourceFiles.add(artifactLocation.getRelativePath());
+        }
+      }
+    }
+
     try (FileInputStream stream = new FileInputStream(sessionDataFile)) {
-      return parseCoverage(blazeProjectData.getWorkspacePathResolver(), stream);
+      return parseCoverage(blazeProjectData.getWorkspacePathResolver(), stream, sourceFiles);
     } catch (IOException e) {
       logger.warn(e);
     }
@@ -60,12 +71,23 @@ public class BlazeCoverageRunner extends CoverageRunner {
   }
 
   @VisibleForTesting
-  static ProjectData parseCoverage(WorkspacePathResolver pathResolver, InputStream stream)
+  static ProjectData parseCoverage(WorkspacePathResolver pathResolver, InputStream stream, HashSet<String> sourceFiles)
       throws IOException {
     ProjectData data = new ProjectData();
     BlazeCoverageData blazeData = BlazeCoverageData.parse(stream);
     for (String filePath : blazeData.perFileData.keySet()) {
       File file = pathResolver.resolveToFile(filePath);
+      if (!file.exists()) {
+        for (String sourceFile : sourceFiles) {
+          if (sourceFile.endsWith(filePath)) {
+            File testFile = pathResolver.resolveToFile(sourceFile);
+            if (testFile.exists()) {
+              file = testFile;
+            }
+          }
+        }
+      }
+
       ClassData classData = data.getOrCreateClassData(file.getPath());
       classData.setLines(fromFileData(blazeData.perFileData.get(filePath)));
     }
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
