### ISSUE TITLE
Removed targets aren't removed from Run Configurations

### ISSUE THREAD

**Issue by samolisov** [bazelbuild/intellij#1391]
When I remove a target from the `BUILD` or `.bazelprject` file (in the last case there doesn't matter whether `derive_targets_from_directories` is enabled), the target is not removed from the Run Configurations list after the synchronization. In the code I see the following logic of removing:

```java
  private static void removeInvalidRunConfigurations(Project project) {
    RunManagerImpl manager = RunManagerImpl.getInstanceImpl(project);
    List<RunnerAndConfigurationSettings> toRemove =
        manager
            .getConfigurationSettingsList(BlazeCommandRunConfigurationType.getInstance())
            .stream()
            .filter(s -> isInvalidRunConfig(s.getConfiguration()))
            .collect(Collectors.toList());
    if (!toRemove.isEmpty()) {
      manager.removeConfigurations(toRemove);
    }
  }

  private static boolean isInvalidRunConfig(RunConfiguration config) {
    return config instanceof BlazeCommandRunConfiguration
       && ((BlazeCommandRunConfiguration) config).pendingSetupFailed();
  }

```
(from the `com.google.idea.blaze.base.run.BlazeRunConfigurationSyncListener` class)

Actually, I have no idea what `pendingSetupFailed()` means and the comment to the method doesn't make it clear, I understand it as a running task that pending during a run but not a task removed from the `BUILD` or `.bazelproject` file.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
