### ISSUE TITLE
CLwB compiler wrapper script can't be executed on Windows

### ISSUE THREAD

**Issue by mwerschy** [bazelbuild/intellij#1397]
The `blaze_compiler.sh` compiler wrapper script fails to execute on Windows, causing an `Issues collecting info from C++ compiler` warning while syncing and breaking resolution of system and dependency headers in CLion. An easy workaround is to simply disable the wrapper script on Windows: https://github.com/mwerschy/intellij/commit/c6028fab90f6767e3c9836346b1d56c52c26876b. A better solution would be to make the wrapper script work on Windows. MSYS2 is required already so it isn't necessary to port it, just adjust the call site to not try executing it directly. If you're interested in improving Windows support I can take a look at implementing this. I don't need it for my use-case at the moment and since Windows is still officially unsupported I'm not sure a pull request would be accepted.

On another note, the CLwB build fails on Windows with `InvalidPathException: Illegal char <*> at index 65: [...]\external\clion_2019_2\clion-*`. This can be fixed by simply using `glob` to resolve the wildcard: https://github.com/mwerschy/intellij/commit/ad96a6a16d023513809a1dc730feae87b74a147c. It probably shouldn't work on other systems either or at least show a more user-friendly error.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
