### ISSUE TITLE
Cannot resolve some symbols

### ISSUE THREAD

**Issue by philwo** [bazelbuild/intellij#14]
I've tried to create a project for Bazel itself and got the plug-in to sync successfully. However, some symbols coming from JARs in third_party, e.g. com.google.common.eventbus.EventBus cannot be resolved, so I get an error for example in j/c/g/devtools/build/lib/actions/Executor.java looking like this:

```
    EventBus getEventBus();
    Cannot resolve symbol 'EventBus'
```

Bazel -> Make Project works and Bazel -> Sync Project also works, it's just the IDE that can't find the things.

My project view looks like this:
```
directories:
  src
  third_party
  tools

targets:
  //src/...:all

test_sources:
  src/test/*
  src/tools/generate_workspace/src/test/*
  third_party/ijar/test/*
```

Any idea? Am I doing something wrong here?

**Comment by brendandouglas** [comment]
Sorry for the delay in replying.

I haven't been able to reproduce this. For me, a guava19 library gets added to the project's external libraries during sync.

Can you reproduce with the latest version of IJwB?

**Comment by brendandouglas** [comment]
Please reopen if this is still occurring in the latest version.
