### ISSUE TITLE
IntelliJ doesn't recognize Maven deps from bazel-deps

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/intellij#142]
IntelliJ plugin doesn't recognize the dependencies on 3rd-party jars that comes from bazel-deps tool. A small repro is available at:
https://github.com/gkossakowski/bazel-scala-example/tree/gkk-intellij-import

Once you import the project, the dependency on algebird is not resolved.

Originally discussed: https://groups.google.com/d/msg/bazel-discuss/Kle8mY43X1U/Xk87H-Q6BwAJ
I couldn't get ittai's suggestion to work, though.
This looks related: https://github.com/bazelbuild/intellij/issues/97

**Comment by promiseofcake** [comment]
I have the same problem, it seems to only affect Scala dependencies, java ones end up working fine. I am not sure if it's a problem on the Bazel side -- when I inspect the ijar's they are empty with only a mainfest file.

**Comment by gkossakowski** [comment]
@promiseofcake scala rules introduced `scala_import` recently that carries information that the latest intellij plugin version recognizes

the remaining work is to port `bazel-deps` to emit `scala_import` instead of `scala_library` for external dependencies. I have a hacky branch that implements the switch. the whole trio: intellij plugin, scala rules and bazel-deps works

**Comment by jin** [comment]
Is this still an issue?

**Comment by promiseofcake** [comment]
It has been resolved for me through iterations in the various pieces, Bazel, Bazel Plugin, rules_scala.
