### ISSUE TITLE
Inconsistent PATH when starting IDE with auto-generated launcher script

### ISSUE THREAD

**Issue by gmishkin** [bazelbuild/intellij#1421]
Similar to #789, I started having problems when using an IntelliJ launcher script from a terminal environment where I was in a Python virtual environment. Digging in, it seems like all processes spawned from IntelliJ get launched in an environment that gets captured when the IDE starts, and the way they capture it is they spawn a login shell and capture the environment. However since it's a login shell, /etc/profile and ~/.bash_profile get read again, which causes PATH to change since `path_helper` on macOS doesn't work as documented, or if your ~/.bash_profile is not idempotent.

I entered [IDEA-227407](https://youtrack.jetbrains.com/issue/IDEA-227407) to describe the issue because I feel like they should not do this behavior if the IDE is started from a launcher script. But I wanted to enter an issue here too, in case there is a mechanism you can spawn the bazel command in a normal environment, instead of this hacked up IntelliJ one. Since bazel is so sensitive to changes in PATH.

Let me know if you want any more details, there are more in the linked issue, but I can give them here too.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
