### ISSUE TITLE
When launching an Idea Plugin configuration it should ignore commented lines

### ISSUE THREAD

**Issue by mtoader** [bazelbuild/intellij#1438]
Right now, the generated run config for an intellij_plugin workspace will read `vmoptions` file from the host IDE and paste the output into the run config. 

However, if the file contains comment the run config will fail to start. 

Commented lines should be removed before updating the configuration.

**Comment by alice-ks** [comment]
The PL #1439 was merged as dd13a63 into the repository. Hence, I'm closing this issue.
