### ISSUE TITLE
IntelliJ IDEA doesn't recognize generated python files for protobufs

### ISSUE THREAD

**Issue by eneev-a** [bazelbuild/intellij#144]
IntelliJ IDEA fails to resolve python files generated with genrule.

I use genrule and py_library ([BUILD file](https://github.com/eneev-a/bazelintellij-python-genfiles/blob/master/src/proto/BUILD)) to generate python protos, but IntelliJ doesn't recognize generated files.

To reproduce:
 1. Clone project from https://github.com/eneev-a/bazelintellij-python-genfiles.
 1. In IntelliJ, import Bazel project using existing workspace from the repo.
 1. Use .project-view file to initialize the project (it adds all directories, all targets, adds python language).
 1. After syncing project, note that import on line 1 in [src/python/foo/foo.py](https://github.com/eneev-a/bazelintellij-python-genfiles/blob/master/src/python/foo/foo.py) can't be resolved by IDE,
yet the script runs fine by bazel: ```$ bazel run //src/python/foo:foo ```

**Comment by brendandouglas** [comment]
The Bazel plugin doesn't yet support resolving python genfile imports (because the import path conventions we use internally are completely different).

There's no reason why it can't though -- looks like for Bazel, the import path maps directly to a bazel-genfiles-relative path, so this should be easy.

**Comment by brendandouglas** [comment]
Fixed for the release after next (scheduled for November 3rd).

**Comment by naomi-bancroft-techlabs** [comment]
Hi,

I followed [this stackoverflow question](https://stackoverflow.com/questions/46739611/how-to-make-intellij-idea-recognize-bazel-generated-python-protobufs) here. I'm still experiencing the same problem as in this bug.

Is this issue fixed? I am using version `2020.06.01.1.0` of the bazel plugin.

**Comment by brendandouglas** [comment]
It's likely regressed since the original fix -- the external python rules are changed independently to the internal ones which we support.

**Comment by naomi-bancroft-techlabs** [comment]
Ah, that is too bad....

What would you do to work around this if you were me? I would add the files manually, even, but they're all located in `/home/myusername/.cache/bazel/`, which is outside the root of the workspace, so I'm not sure how.

Thank you for the fast reply.

**Comment by brendandouglas** [comment]
There's no great workaround other than fixing python protobuf support in the plugin unfortunately, and we're really short on time at the moment. I'd be happy to review a PR fixing this though. We try to collect information about python rules here: https://github.com/bazelbuild/intellij/blob/fc11c2f1057598897a495b9140eb7bb6c235125b/aspect/intellij_info_impl.bzl#L255

I'd guess that's failing for your particular python rules (maybe they don't have a 'PyInfo' provider, for example). Alternatively, maybe that's all working, but the heuristics we use to local genfiles from import strings isn't working for this particular py_proto_library rule (that code is in BazelPyGenfilesImportResolverStrategy)
