### ISSUE TITLE
BuildifierBinaryProvider should allow one to provide a per project buildifier binary

### ISSUE THREAD

**Issue by mtoader** [bazelbuild/intellij#1440]
Right now this extension point is quite simple:

```java
public interface BuildifierBinaryProvider {

  ExtensionPointName<BuildifierBinaryProvider> EP_NAME =
      ExtensionPointName.create("com.google.idea.blaze.BuildifierBinaryProvider");

  @Nullable
  File getBuildifierBinary();
}
```
and the default implementation provides a binary that is packed into the plugin at build time. However, said binary doesn't run on mac, and there are situations where a bazel repository wants to provide their own buildifer binary and also want it executed from within a specific Project inferred working dir.

The proposal is to change the extension to get a `Project`, similar to the following:

```java
public interface BuildifierBinaryProvider {

  ExtensionPointName<BuildifierBinaryProvider> EP_NAME =
      ExtensionPointName.create("com.google.idea.blaze.BuildifierBinaryProvider");

  @Nullable
  File getBuildifierBinary(Project project);

  @Nullable
  File getBuildifierExecutionRoot(Project project);
} 
```

update the current implementation to implement this interface, but keep the current functionality, and update the caller to use this interface.

**Comment by chaoren** [comment]
> there are situations where a bazel repository wants to provide their own buildifer binary

Can you give an example? What would this project-specific buildifier do that the generic one can't?

**Comment by mtoader** [comment]
Generically speaking: since the binary can live inside a bazel repo it can be customized with rules that are specific to said repo.

In my particular case, the current implementation doesn't work at all since we are using mac os as a development machine, the main project provides a binary that doesn't really run on mac, and the repo is set up to use a local buildifier binary. 

This is what I get when I try to run it by hand:
```bash
➜ file ./bazel-buildifier && ./bazel-buildifier
./bazel-buildifier: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
zsh: exec format error: ./bazel-buildifier
```

Currently, there is no visible difference in terms of output but I can imagine this state to diverge over time. 
So instead of forcing the project to provide a binary for all the environments, i propose to update the current extension point to let others customize things for them when needed.

**Comment by chaoren** [comment]
If you're running on the mac, shouldn't you always use the mac-specific buildifier? Why is it dependant on project?

**Comment by mtoader** [comment]
Locally, with the change that would close this issue, I am using a mac specific buildifier.  

But that buildifier binary is building being built via bazel from the current project repository so it is project scoped. 

That's the whole reason I've opened this issue :).

**Comment by chaoren** [comment]
I don't think using a buildifier binary built from the opened project is a common enough use case.
Could you not just prebuild the mac binary, put it in one location, and have all projects use that same mac binary? Then you don't need to change the API, just return your mac binary if you detect that the IDE is running on mac.

**Comment by mtoader** [comment]
That would require more coordination (either maintain a common location for that binary or package a fixed version with the forked plugin) for no real benefit. 

To make it work well, I would still need to provide some sort of project context when executing it anyway (for example the --tables=buildifier.json config lives under the project).

And I would have to synchronize plugin releases with buildifier changes in the main repo to make sure they are always in sync.

I can solve this for us by maintaining an internal fork that has this functionality, which I'm doing anyway, but I thought it would be helpful for the main project (especially given the fact that one of the main recommended ways to use the buildifier is by embedding it into your project: https://github.com/bazelbuild/buildtools/tree/master/buildifier#setup-and-usage-via-bazel).

**Comment by chaoren** [comment]
> one of the main recommended ways to use the buildifier is by embedding it into your project

Ah, I didn't know that. That makes it much more compelling.
@brendandouglas what do you think Brendan?

**Comment by mtoader** [comment]
@brendandouglas .. ping?

**Comment by chaoren** [comment]
An sorry, Brendan's on vacation since Monday. He'll be back next year.

**Comment by mtoader** [comment]
@brendandouglas Can you add your input in this issue ?

**Comment by mtoader** [comment]
@brendandouglas ping?
