### ISSUE TITLE
New plugin breaks sync

### ISSUE THREAD

**Issue by KaoruDev** [bazelbuild/intellij#1441]
## Description of the issue. Please be specific.
Syncing the project with `derive_targets_from_directories: true` ends with: `Sync failed`
![image](https://user-images.githubusercontent.com/5273755/69776308-8b478f00-1150-11ea-99a9-f8dd3e4f7310.png)

## What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

Set `derive_targets_from_directories` to `true` and sync your project.

## Version information
IdeaUltimate: 2019.2.4
Platform: Mac OS X 10.14.6
Bazel plugin: 2019.11.14.0.1
Bazel: 1.2.1

## Workaround
Disable `derive_targets_from_directories` and then list `//...` as the targets.
```
# derive_targets_from_directories: true

targets:
  //...
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
