### ISSUE TITLE
Sync is missing imports

### ISSUE THREAD

**Issue by szinn** [bazelbuild/intellij#1445]
I have a project where I import a number of external jar files using maven_install and have build targets that depend on these jars via an @maven//:xxx

When I was editing the BUILD files, everything was fine and all of the maven-imported jar files were showing up as external libraries.  However, when I committed and then synced again, all of them would disappear.  If I added a space to a BUILD file, they would come back.

Debugging through this issue, it seems that the working set defined which targets would be examined for libraries.  However, this doesn't make sense and that all libraries should be considered.

The line of code I narrowed it down to is:

java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java#245
    if (workingSet == null || workingSet.isTargetInWorkingSet(target)) {

I would submit that it doesn't matter if the working set contains the target - the target is needed to determine the imported libraries.

Removing this if statement appears to make the external libraries show up all of the time, independent of the working set.

**Comment by chaoren** [comment]
Can you share your .bazelproject file? This usually happens when you don't have the correct targets in the targets section. We have a setting to automatically add the files that you've modified (working set) to the list of targets to sync, but by default that list comes from your .bazelproject targets section.

**Comment by szinn** [comment]
Here is an example repo:  https://github.com/szinn/Bazel-Kotlin

If you import it from Bazel in IntelliJ, the junit jar file won't be there if you have no changed / added files to the repo.  Add a space to test/BUILD and then resync the workspace and the junit external library shows up.  Remove the space which returns you to no altered files, resync, and junit disappears.

**Comment by szinn** [comment]
It appears that the rules-kotlin plugin is marking all dependencies as UNUSED in the .jdeps file except for the standard Kotlin library ones that get marked as IMPLICIT.
