### ISSUE TITLE
Adding .clwb folder to project view's excluded directories has no effect

### ISSUE THREAD

**Issue by alexfrasson** [bazelbuild/intellij#1449]
Adding .clwb to the list of excluded directories in the project view file (*.bazelproject) seems to have no effect. As shown in example bellow, the folder is still visible within Clion.

### project.bazelproject
```
derive_targets_from_directories: true

directories:
  .
  -.clwb
```

### Current folder structure shown in Clion
```
root_folder─┐
            ├.clwb
            ├foo
            └bar
```

### Expected folder structure shown in Clion
```
root_folder─┐
            ├foo
            └bar
```

### Versions
Bazel: 1.2.0
Bazel plugin: 2019.10.29.0.2
Clion version: 2019.2.5
Ubuntu: 18.04.3

**Comment by chaoren** [comment]
Excluded directories just means exclude from project (i.e., folder turns orange in the project pane and code analysis is not done). They will still be visible in the tree structure.

**Comment by chaoren** [comment]
Also, we explicitly add the project data directory to the project (but exclude subdirectories) so you can easily edit the local .bazelproject file.

**Comment by alexfrasson** [comment]
Would it be possible to make that optional somehow? We don't see the need for editing the local `.bazelproject` file at all since everything is properly setup in our shared `project_name.bazelproject.` I think it is fine to add it by default to the `Project files` or `Project Non-Source Files`, but it would be nice to be able to hide it from `Project` entirely.

And if instead of adding the entire root folder as shown in example above you explicitly add sub-folders, `.clwb` is not actually visible. So `.clwb` is not added to the project by default in all cases.

**Comment by chaoren** [comment]
Even if you don't add the root, the .bazelrpoject file would still be searchable via project-wide find actions (e.g., shift+shift), and we find that very convenient.
Either way, it should have no effect on what you want to happen. Even if we didn't add the local .bazelproject file to the project, you'll still see the directory at the root.

**Comment by alexfrasson** [comment]
Well, I understand that it is convenient and I do think it is good that you make that file easily accessible. I just think it is not intuitive to make the `.clwb` folder visible even though the user explicitly stated that he/she wants to hide it because it does not add any value for him/her.

Of course, it is nothing that prevents users from using the plugin. It would be nice to have that behaviour documented somewhere though.

Btw, thanks for the feedback :)
