### ISSUE TITLE
Create a git tag representing the currently released version of the plugin

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/intellij#146]
See discussion [here](https://github.com/bazelbuild/rules_scala/issues/308#issuecomment-336905464).

We'd like to test the IntelliJ aspect integration tests with new `rules_scala` PRs for both the currently released git version of the intellij plugin and the master version. Right now, determining the git commit corresponding to the released version of the plugin is manual and error-prone. It would be great to use a git tag for automation.

**Comment by brendandouglas** [comment]
This is impractical at the moment -- GitHub is not the source of truth, and there's not a 1:1 mapping between internal commits and git commits.

We plan to eventually set up regular syncs (using copybara) between our internal repo and GitHub, at which point this will be a bit more practical.

We also cut release branches, and cherry-pick fixes onto it while dogfooding. So even when we do have regular syncs, the release tag would be approximate.

Our GitHub repo at HEAD generally tracks the latest released version quite closely though, so for now it might be sufficient to just test against HEAD?

**Comment by greggdonovan** [comment]
> This is impractical at the moment -- GitHub is not the source of truth, and there's not a 1:1 mapping between internal commits and git commits.

OK, thanks. I figured as much from the disclaimer in the README.

> So even when we do have regular syncs, the release tag would be approximate.

I was thinking we could have a release tag for the commit that corresponds to the version live at [plugins.jetbrains.com](https://plugins.jetbrains.com/plugin/8609-bazel). For example, right now the live commit SHA appears to be [this](https://github.com/bazelbuild/intellij/commit/ac2bb7053cd2daf509257a8f0cb2f556deb9df27) according to the user-facing plugins site. 

If there's an internal dogfooding plugins repo, maybe we can have a git tag called `plugins-jetbrains-com` that represents the commit corresponding the public facing version?

**Comment by brendandouglas** [comment]
We can have a git tag corresponding to the tip of the release branch, but it won't generally map to the exact state of the release branch -- because we're only cherry-picking select commits.

In practice though, an approximate release commit should be sufficient though, right?

**Comment by greggdonovan** [comment]
> In practice though, an approximate release commit should be sufficient though, right?

I think so - thanks! We'll want to know if are we breaking the current bazel plugin that users have installed vs. breaking on some code that's still in development.

**Comment by ittaiz** [comment]
Any chance for a manual solution until an automated one arrives? Thanks to fine grain commits and relatively small number of releases this should be relevant, right?

**Comment by jin** [comment]
Releases are now tagged manually: https://github.com/bazelbuild/intellij/releases
