### ISSUE TITLE
Configuring a basic scala project

### ISSUE THREAD

**Issue by tjarvstrand** [bazelbuild/intellij#1461]
Hi  there,

I'm still very new to this to please bear with me as i find parts of the documentation a bit difficult to decipher. I'm using [higherkindness/rules_scala](https://github.com/higherkindness/rules_scala) to build a basic scala project with the following structure:
```
├── BUILD
├── src
│   ├── main
│   │   └── scala
│   │       └── com
│   │           └── example
│   │               └── test
│   │                   ├── Main.scala
│   │                   └── Test.scala
│   └── test
│       └── scala
│           └── com
│               └── example
│                   └── test
│                       └── TestTest.scala
└── WORKSPACE
```

I'm wondering how I can get `src/main/scala` and `src/test/scala` recognized as source directories? If I have to manually specify all source directories it will get very annoying in a monorepo with many modules.

EDIT: Even if I do manually specify both directories, Intellij still warns me that the `package` declaration in the scala files should be `package src.main.scala.com.example.test`. How can I fix that?

**Comment by chaoren** [comment]
Can you show your .bazelproject file?
If you don't want to specify every directory, you can just use the root for the directories section.
Make sure your targets are included in the bazel sync either with the option to automatically derive them from directories or explicitly list them in the targets section.

**Comment by tjarvstrand** [comment]
Hi!

Thanks for the quick reply! I've tried a couple of different ways and realized that even when specifying the directories explicitly Intellij complains that my package declarations to be `src.main.scala.com.example.test`.

I've pushed my example project [here](https://github.com/tjarvstrand/bazel-intellij-test)

**Comment by tjarvstrand** [comment]
Actually, nevermind. PEBKAC :/

Thanks!
