### ISSUE TITLE
Add gutter icon for runnable targets in Blaze Build file

### ISSUE THREAD

**Issue by mitchellaaron** [bazelbuild/intellij#1466]
Background:
Currently you can right-click a build target and get contextual run actions. However this action isn't very discoverable and I was surprised when several of my colleagues didn't know the IDE supported this feature. 

Goal:
I propose that a gutter icon be added to runnable build targets similar to how Intellij already adds a gutter icon to junit tests. 
![Screenshot from 2019-12-04 17-56-39](https://user-images.githubusercontent.com/58445728/70188809-acaffa00-16bf-11ea-9d96-2bdb31d67764.png)

Design:
It seems straightforward leverage the ideas from `BlazeBuildFileRunConfigurationProducer` and put them into a `RunLineMarkerContributor`.

**Comment by brendandouglas** [comment]
This sounds like a good idea. The two main issues I can think of:

- the options should exactly match those you get in the context menu (possibly don't show the 'create' option, to keep it consistent with upstream gutter actions, though personally I use that a lot)
- avoid any work on the EDT

Otherwise, sounds great -- thanks for the suggestion and PR. Rather than go back-and-forth on the PR, I'll look at applying this upstream, modifying to fit our code style, etc.

**Comment by mitchellaaron** [comment]
Good morning, @brendandouglas. That's excellent news, let me if you need any help.

>the options should exactly match those you get in the context menu (possibly don't show the 'create' option, to keep it consistent with upstream gutter actions, though personally I use that a lot)

I may be mistaken but I believe `ExecutorAction.getActions()` eventually gets delegated to
`BlazeBuildFileRunConfigurationProducer` which powers the context menu and will produce the same actions. 

>avoid any work on the EDT

Good point! I was concerned about tying up essential threads but I didn't know what concurrent options were available. My concerns were abated when I took a cursory look at other `RunLineMarkerContributor` classes in the codebase and didn't find any explicit concurrent programming -- although it's no reason not do things correctly in this file.

**Comment by brendandouglas** [comment]
Should be done in the next release -- closing.

**Comment by mitchellaaron** [comment]
Cheers! That's great news. Thank you for getting the feature in.
