### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by dlazerka** [bazelbuild/intellij#148]
Currently, Bazel seems to be working fine with Kotlin, thanks to rules by https://github.com/pubref/rules_kotlin, but whenever IDEA syncs project with BUILD file, it says "Kotlin not configured", and asks to re-enable Kotlin. Also, "Sources root" forgets that `./src/main/kotlin` is a source root.

**Comment by brendandouglas** [comment]
There's no Kotlin support in this plugin, and we don't have any current plans to add support.

We'd welcome contributions adding it though (the scala support code provides a good example of exactly what would be necessary).

**Comment by hsyed** [comment]
@brendandouglas simply stopping the plugin from wiping the kotlin configuration on a workspace sync would lead to a somewhat useable experience. Would this be doable ?

**Comment by brendandouglas** [comment]
Definitely doable. To do that, a kotlin-specific BlazeSyncPlugin extension would need to be written (similar to the existing ones, such as for scala).

It's not something we have the bandwidth to do ourselves, but we'd certainly welcome contributions.

**Comment by pcj** [comment]
Can you update the README then?  The readme says you're not accepting contributions.  Here at #bazelcon and a number of people are talking about this right now, reticent to even try this repo with such a tepid outlook on the status and support of this repo.

**Comment by brendandouglas** [comment]
Good idea, that README definitely needs updating. To clarify, the plugins themselves (uploaded to the JetBrains plugin repository) are kept up to date, and supported.

This repository, on the other hand, is currently not. It is updated somewhat regularly though, and we'd have no trouble upstreaming any patch based off the current repo HEAD. I'll update the README to reflect this.

**Comment by hsyed** [comment]
I've ported/copied most of the Scala plugin into a kotlin plugin.

@brendandouglas Can't figure out how to get the bazel intelij plugins launcher to work -- trying to use my installed IJ ultimate as the plugin JDK the config doesn't seem to be handling the space in the following flag `-Djb.vmOptionsFile=/Applications/IntelliJ IDEA.app/Contents/bin/idea.vmoptions`.

**Comment by brendandouglas** [comment]
Sounds like the VM options field doesn't accept whitespace within arguments. Have you tried quoting it? Otherwise, is that vmoptions file necessary to test the patch?

**Comment by hsyed** [comment]
@brendandouglas I did try quoting it, no form of quoting worked. I am now facing #165.

**Comment by brendandouglas** [comment]
I'll close this one, as we now have Kotlin support thanks to @hsyed!
