### ISSUE TITLE
Pass `testonly` attribute to TargetIdeInfo 

### ISSUE THREAD

**Issue by comchi** [bazelbuild/intellij#1480]
Hello,

So in the current state of things it looks like out of the box Intellij with bazel project doesn't support `Test scope` while you want to find usages of some method or do full text search in your project. The only option to make it work that I know (pls correct me if I wrong) is to specify explicitly test folders in the project view file. The problem I see in this are:
1.It prohibits you from mixing test sources with production sources in same folder since documentation state that it s a regex for directories 
2. It's error prone since you can forget about some folder and it's hard to notice this mistake

The alternative that I'm working right now is to derive the information about each source file and it's belonging to test scope of the project using the `rule name` and `testonly` attribute. The problem that blocks me at the moment is that I can't generate jar with code generated from proto files, it seems like you repackage it somehow in the manner that I can't reproduce it locally. (https://github.com/bazelbuild/intellij/blob/master/proto/proto_deps.jar)

So, my proposal is to add `testonly` attribute to `TargetIdeInfo` (https://github.com/bazelbuild/intellij/blob/d071a73c0a45f8a90fcd67c30eb89364e893f73f/proto/intellij_ide_info.proto#L187).  I believe it will useful even If I will fail miserably with my solution to the described problem, so it's worth adding it anyway.

The example of what I'm asking to do (didn't create PR because of checklist): https://github.com/comchi/intellij/commit/5e57e46018ba6f6918c17fca2410e3e4b3566b03

Also, thanks for the great build system and intellij integration for it.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
