### ISSUE TITLE
CLion 2019.2.5, bazel plugin 2019.11.14.0.1 cannot find stl definitions, nor c/c++ syntax highlights

### ISSUE THREAD

**Issue by immars** [bazelbuild/intellij#1481]
under macosx catalina 10.15.2,

I imported examples/cpp-tutorial as a project, however after the import finished, the IDE do not have syntax highlight and smart completion.

the "Bazel Problems" pane complains about:

![image](https://user-images.githubusercontent.com/1144653/70683268-a8e23000-1cdc-11ea-9e5b-0bd90193370e.png)

I can build the project under command line with bazel.

**Comment by immars** [comment]
Downgrading my bazel version from 1.2.0 to 1.0.0 resolves this issue.

seems that clion plugin doesn't work with bazel >= 1.1.0

**Comment by immars** [comment]
CLion linux version works fine with latest plugin and bazel 1.2.0.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
