### ISSUE TITLE
BUILD file formatting uses LINE_COMMENT_AT_FIRST_COLUMN=true by default

### ISSUE THREAD

**Issue by v3n** [bazelbuild/intellij#1483]
Would love to see this either configurable or set to false by default similar to how projectview is done.

It's a pretty jarring distinction to the rest of our codebase.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
