### ISSUE TITLE
Confused by "Project data directory must not contain the workspace."

### ISSUE THREAD

**Issue by dlazerka** [bazelbuild/intellij#150]
Let's say there's a simple directory structure:
```
src/
    my.py
WORKSPACE
BUILD
```
When importing an existing project, plugin doesn't want to accept "Project data directory" (not sure what it means) to the same location as WORKSPACE file is in:
![screenshot from 2017-10-22 11-04-18](https://user-images.githubusercontent.com/592184/31865008-6e7d0534-b71c-11e7-9e97-af9a06b9e56a.png)

Also, setting it to `src` sub-directory doesn't work either:
![screenshot from 2017-10-22 10-56-28](https://user-images.githubusercontent.com/592184/31865012-7806103c-b71c-11e7-9697-cb8fa7d1360c.png)

Tried moving WORKSPACE under a directory, but got the first error. It seems that workspace and "project data directory" must not intersect completely.

I'm super confused by this. I would assume that "project data directory" is the root location of the project sources, for example. But then how can bazel workspace not intersect with the sources?

Everything works fine in from bazel command-line.

bazel version: 0.7.0
bazel intellij plugin version: 2017.10.09.0.1

**Comment by plumpy** [comment]
The project data directory is where IntelliJ stores its configuration
files, caches, etc. It's not related to your source code and shouldn't be
check into version control, so you don't need it to be in the same
directory as your sources.

**Comment by dlazerka** [comment]
Thank you for explaining.

But isn't that the purpose of `.gitignore`? It's pretty easy to use, I see no problem having IDE-specific files in workspace directory. It has always been like that. Ignoring files was always the default way to omit files from checking in to any version control system, e.g. `svn:ignore` property or even `cvsignore` if we want to go 20+ years ago. Maybe I'm missing something, why did it became an issue now?

Also, inevitably there will be a lot of other files not-for-version-control, like bazel-bin, bazel-out etc, if you use Mac OS, there will be .DS_Store or .Thumbs files.

So you recommend having a separate sibling directory, specially for main project directory, like
```
my-project/
my-project.idea/
```
?

**Comment by dlazerka** [comment]
Just tried that, and had a problem configuring `.bazelproject` directories:
* If I include `.` into directories, it marks the whole project workspace directory as source directory in IDEA. That's wrong, sources are usually put under `src/` for Java, C, .Net projects, and `app/` for JS projects, for what I know, only Python or small C projects prefer putting sources right into the root.
That prevents IDEA of correctly recognizing packages for java code, as it now has to be `package src.main.java.com.example.myproject;` instead of com.example.myproject.

* If I don't include `.` to .bazelproject directories, then other project files are not visible from IDEA project structure, (like README.md, WORKSPACE, and all the doc/, lib/, media/, data/ etc directories that usually accompany sources. Project files are not necessarily all sources.

Also, when I tried to put a BUILD file into the src/main/java/com/example/myproject/mypackage directory (as we used to do in google3), plugin marked `com` directory as the source root as well. Not sure what's the reasoning there (should be `java`). If bazel prefers google-internal style directory structure, I wouldn't mind switching to it, just need to know what it is.

Maybe this is a separate issue though.

**Comment by gautamraj** [comment]
+1

It would be nice to check in .idea/codeStyleSettings.xml and have IntelliJ automatically pick it up. Right now we have to manually symlink it from our git repo into the Intellij project directory.

**Comment by dlazerka** [comment]
Also a pretty strong argument for keeping it in one directory is that all other IntelliJ IDEA language plugins put the project configuration files into the same project directory.

**Comment by brendandouglas** [comment]
This is really just an internal restriction. I agree the Bazel plugin should allow this -- there's no reason to enforce it in the external plugin, we simply haven't written the code to account for this different use case.

**Comment by ssuchter** [comment]
Another reason to fix this is to allow CLI opening of projects.

I have many dozens of possible projects that I use Intellij with. (I've got 10 separate repo clients of our company's main repo, and each one has ~5 different projects that I frequently edit, each is a separate thing in Intellij) Looking through 'recent' projects is a big pain - instead what I like to do is to just cd into the appropriate directory and type 'idea .' For maven projects, this works great. But for Intellij projects, since I have to make the project data directory somewhere else, I have to remember that for those projects, I must cd into that alternate place and open from there. Weird workflow!

**Comment by plumpy** [comment]
Yeah, sorry, I wasn't paying close attention when I wrote that reply and I thought I was replying to an internal Google email. In penance, I'll try to fix this for the Bazel plugin release in threeish weeks.

**Comment by dlazerka** [comment]
@brendandouglas Ah, I see. I thought it was a decision, thanks.
@plumpy That's great! Sorry I didn't know it was Bazel's WIP point. Let me know if you need any help.

**Comment by solomatov** [comment]
Good usecase of this is to store coding style and inspection profiles in the repository. I don't like having a separate repo for this.

**Comment by chaoren** [comment]
A fix should be available by the next release.

**Comment by ittaiz** [comment]
So now we can have the IntelliJ directory in the code directory?

**Comment by chaoren** [comment]
Yes, with the next release, the project data location will default to the root of your workspace.

**Comment by ssuchter** [comment]
Yay!

**Comment by ittaiz** [comment]
Awesome! Well done :)

**Comment by plumpy** [comment]
@chaoren: It's actually two releases out, right?

**Comment by chaoren** [comment]
Err. Yes.

**Comment by plumpy** [comment]
So for those of you waiting, it'll be in 2018.02.26, which should be pushed to the plugin repository on about 2018-03-12.

**Comment by ittaiz** [comment]
Can the source be synced now?
