### ISSUE TITLE
Enable running specific specs2 examples

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#151]
Enable running specific test "methods"/examples/fragments of specs2 like JUnit and scalatest are supported.
Requires work on both the plugin side and on rules_scala.
@hmemcpy has already done some work on it from both sides

**Comment by chaoren** [comment]
Only scalatest is left, right?
Still need better filtering options in scalatest, preferably the same as specs2, i.e., "com.example.TestClass#foo should do bar$", so we can reuse code.

**Comment by chaoren** [comment]
Bug title says specs2. That's finished, so I'll close this.
