### ISSUE TITLE
Add a Parameter in .bazelproject to Prevent Override Project Modules

### ISSUE THREAD

**Issue by ghost** [bazelbuild/intellij#1527]
Phenomenon:
When we click Bazel sync, it will read directories form .bazelproject file and override everything in Project Struct -> Project Settings -> Modules.

Expectation:
I'd love to add a parameter in .bazelproject, like 'override_modules'. If it is set to false, Bazel sync won't override the Modules.
It is useful when we're using Intellij Bazel with Spring plugin. Spring will recognize source code and test code into two different modules, while Bazel will mark every directories into one module ".workspace". Sometimes it will make Spring @Autowired navigation to wrong place. I usually mark Modules manually, but it will be override whenever I click Bazel sync.

**Comment by dsilvasc** [comment]
Would be nice to not include all manually-managed modules in the orphaned list:

https://github.com/bazelbuild/intellij/blob/1b7bfce029ae51f2669feedcc03e0382f001f490/base/src/com/google/idea/blaze/base/sync/projectstructure/ModuleEditorImpl.java#L108-L115
