### ISSUE TITLE
C++ support for automatically add/delete run configurations from BUILD files

### ISSUE THREAD

**Issue by zz-pony** [bazelbuild/intellij#154]
In CLion + CMake world, there are options to automatically add/delete run configurations from CMake files. Is there any support for this in Bazel world? That would be a big plus for larger projects.

![auto run configurations](https://user-images.githubusercontent.com/29513208/32207769-5cf789b0-bdbb-11e7-8830-d49a11ef4180.png)

**Comment by brendandouglas** [comment]
Bazel run configurations are [automatically added](https://ij.bazel.build/docs/run-configurations.html#run-configurations-created-by-default) during sync for any targets individually listed in the project view file.

We don't have any plans to expose an option to add run configurations for all Bazel targets in the project -- that would be unwieldy for larger projects. Note -- you can easily create bazel run configurations by right-clicking on the relevant file / test case / BUILD target.

**Comment by zz-pony** [comment]
I see. Thanks for your quick reply.
