### ISSUE TITLE
CLion Bazel 1.2.1 incompatiability macOS

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/intellij#1545]
When using CLion with the default toolchain on macOS (10.14.6). The plugin fails when invoking `wrapped_clang`. Tested on CLion 2019.2.5, plugin version 2019.12.02.0.0. Bazel 0.29.1 works perfectly fine on this version of CLion and the plugin. Although only a warning, it does result in CLion not being able to find symbols and basic IDE functionality ceases to function. This specifically only happens when Syncing the project, Compile Project works fine.

```
Warning:Unable to check compiler version for "/private/var/tmp/_bazel_wesleywilliams/67e49888db524d169925325d83f7e7d6/execroot/<my_repo>/external/local_config_cc/cc_wrapper.sh".
stderr: "Error: DEVELOPER_DIR not set.
/private/var/tmp/_bazel_wesleywilliams/67e49888db524d169925325d83f7e7d6/execroot/<my_repo>/external/local_config_cc/cc_wrapper.sh: line 56: 21198 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
"
stdout: ""
Check if running the compiler with --version works on the cmdline.
```

**Comment by cpsauer** [comment]
Hey @wesleyw72! I was able to work around this issue by adding the following to my .zshrc
```
export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
```
That shifted the error over to SDKROOT, which I set to the latest I'd installed in the same way.

Agree that this should work out of the box, but hopefully this helps in the meantime :)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
