### ISSUE TITLE
Bazel plugin breaks indent-on-enter in Python files (at least)

### ISSUE THREAD

**Issue by jvolkman** [bazelbuild/intellij#1548]
The Bazel plugin replaces the default `CodeStyleManager` plugin with `BuildifierDelegatingCodeStyleManager` which ultimately extends from the delegating base class `DelegatingCodeStyleManager`.

`DelegatingCodeStyleManager` doesn't currently delegate the `CodeStyleManager.scheduleIndentAdjustment(...)` which is what hitting enter in a Python file appears to rely on for proper indentation.

The simple addition of this method to `DelegatingCodeStyleManager` fixes the issue.

**Comment by brendandouglas** [comment]
Thanks for letting us know. We don't yet properly support 2019.3, so haven't got around to fixes like this one -- we make the change upstream.
