### ISSUE TITLE
IntelliJ Run-> Debug menu item sometimes grayed out for target, 

### ISSUE THREAD

**Issue by anvivi99** [bazelbuild/intellij#1555]
I've seen this issue on both 2019.2 and 2019.3. For bazel command target, the debug menu item under run is grayed out. And, the port field in the configuration does not show in this case too.

**Comment by l1990790120** [comment]
have the same issue on 2021.2.3. did you ever figure this out?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
