### ISSUE TITLE
Bazel 2.0: "native Java rules are deprecated" during Sync operation

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/intellij#1568]
Bazel 2.0 flipped `--incompatible_load_java_rules_from_bzl`, but the IJ plugin's bundled `BUILD.bazel` hasn't been updated to match. Our users run into "external/intellij_aspect/BUILD.bazel:15:1: in java_import rule @intellij_aspect//:jar_filter_lib: The native Java rules are deprecated." upon Bazel > Sync > Sync Project with BUILD files.

IJ version: 2019.2
Plugin version: 2019.12.16.0.4

**Comment by beasleyr-vmw** [comment]
I've instructed our users to patch `~/Library/Application Support/IntelliJIdea2019.2/ijwb/BUILD.bazel` in the meantime. I suspect that https://github.com/beasleyr-vmw/intellij/commit/51d4ed67b1960f7bc03d20268a7b6965d886be0c would resolve this.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
