### ISSUE TITLE
Providing startup options to Bazel

### ISSUE THREAD

**Issue by susliko** [bazelbuild/intellij#1578]
Is there any possibility to provide startup options (https://docs.bazel.build/versions/master/command-line-reference.html#startup-options) to Bazel?

In particular, it would be nice to be able to set --bazelrc option.

**Comment by brendandouglas** [comment]
We intentionally don't support this, because we don't want inconsistent sets of startup options between bazel run from the IDE and from the command line, defeating caching.

**Comment by susliko** [comment]
Understood. Thank you for fast response!
