### ISSUE TITLE
"--override_repository=intellij_aspect=..." in bazel invocation doesn't handle paths with spaces

### ISSUE THREAD

**Issue by jvoung** [bazelbuild/intellij#158]
At least that seems to be the case according to this bazel-discuss thread:
https://groups.google.com/forum/#!msg/bazel-discuss/M5S0uBzzAMg/uOxg9HJDCQAJ

**Comment by brendandouglas** [comment]
Doesn't apply to be causing problems any more, at least with the latest bazel version.

**Comment by regisd** [comment]
@brendandouglas  I'm not sure about the consequences, but on every sync, there is an error message, though.

**Comment by regisd** [comment]
There is a work around:
1. Open **IntelliJ > Help > Edit custom properties**
2. Add
```
idea.plugins.path=~/Library/ApplicationSupport/IdeaIC2019.1/
```

The default plugin path is `~/Library/Application Support/IdeaIC2019.1/` but on Mac OS, there is a symbolic link from ``~/Library/ApplicationSupport/` to ``~/Library/Application Support/`, hence this is the same location. But the space creates confusion to the Bazel plugin, so removing it is a good workaround.

**Comment by cgruber** [comment]
This feels like it's an issue that has been around for 1/3 of a year, and affects mac users pretty regularly. Can this get some eyes on it? It's hitting us with modern ASWB/Bazel/Intellij versions, and this workaround, while handy to have, shouldn't be required of developers, who will have to find this bug.

**Comment by cgruber** [comment]
Sorry - it's been around for years - hasn't been commented on for 1/3 of a year.
