### ISSUE TITLE
Bazel sync breaks Java SDK selection

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/intellij#1584]
Hey there esteemed Bazel team,

When I run the Bazel sync in the IntelliJ plugin, it seems to lose my Java SDK, or maybe it can't detect it properly in Bazel? Even if I set an explicit path / Java runtime, it fails to set this up in IDEA. What I get is a bunch of missing symbols and I must manually select an SDK.

Is this a known issue, or is anyone else running into it?

**Comment by sgammon** [comment]
hey there Bazel team... could you help with this?

**Comment by sgammon** [comment]
@brendandouglas / @jin?

**Comment by sgowroji** [comment]
Hello @sgammon, Could you please provide more details to reproduce the issue at our end. And can you try to test the same with latest bazel plugin and Intellij IDE.  Thanks!

**Comment by sgammon** [comment]
this is so old that i suspect it has been fixed @sgowroji - i'm on M1 now and i've had many fewer problems with bazel and intellij since filing this. will close and re-open if needed :) thank you for the followup.
