### ISSUE TITLE
Unsynced files with custom rule using _cc_toolchain compilation

### ISSUE THREAD

**Issue by milancpp** [bazelbuild/intellij#1593]
We have a custom rule that uses _cc_toolchain C++ compilation. Think of it like cc_shared_library with some twists. It takes a srcs attribute and does return the CcInfo provider.

It seems the Clion plugin does not sync those srcs. How does the plugin determine input files and how can I modify our rule to support this? Thanks!

**Comment by milancpp** [comment]
I think (please correct me if this is wrong) I found the piece of code extracting the source files from the bazel targets: https://github.com/bazelbuild/intellij/blob/d408926abd618124cf3169260db0d13c9c8c415c/aspect/intellij_info_impl.bzl#L397

This is the signature of our custom rule:

```
my_rule = rule(
    implementation = my_rule_impl,
    attrs = {
        "copts": attr.string_list(doc = "Add these options to the C++ compilation command."),
        "srcs": attr.label_list(
            doc = "List of sources and headers to include in the module.",
            allow_files = [".cpp", ".cxx", ".h", ".hpp", ".hxx"],
        ),
        "deps": attr.label_list(
            doc = "A list of modules which are required by this module and modules using this module",
            default = [],
            providers = [[CcInfo]],
        ),
        "strip_include_prefix": attr.label(
            doc = "Directory that can be stripped from include paths",
            allow_single_file = True,
            default = None,
            mandatory = False,
        ),
        "data": attr.label_list(
            doc = "Any data needed during execution (will be linked into runfiles)",
            default = [],
            allow_files = True,
        ),
        "_template": attr.label(
            allow_single_file = True,
            default = "@//some/target:plugin_exports.cpp.in",
        ),
        "_a_private_dependency_for_the_generated_code": attr.label(
            providers = [[CcInfo]],
            default = "@//some/other/library",
        ),

        "_cc_toolchain": attr.label(default = "@bazel_tools//tools/cpp:current_cc_toolchain"),
    },
    provides = [
        CcInfo,
        DefaultInfo,
        _MyPluginInfo
    ],
    fragments = ["cpp"],
    toolchains = [
        "@rules_cc//cc:toolchain_type",
    ],
    output_to_genfiles = True,
)
```


From looking at the code it seems like it SHOULD work (extract and find the sources and headers added to the srcs attribute). Am I missing something?

**Comment by milancpp** [comment]
So it seems the plugin really does have a rule whitelist and only supports the native cc_* rules. We worked around it by replacing the @intellij_aspect using a bazel wrapper script with a custom one that changes the recorded rule kind attribute to one of the native rules if necessary.

**Comment by nicknezis** [comment]
@milancpp Do you have an example of how you solved this? I think I'm having the same issue with some custom Python pex rules. Thank you.

**Comment by milancpp** [comment]
@nicknezis I can't give you our exact setup but basically it boils down to the following steps
* Create a wrapper script (we use Python) and configure it in CLion as Bazel executable
* In that script detect whether it is being called by the CLion plugin by checking for "--tool_tag=ijwb:CLion" in the args
* Filter out "--aspects=@intellij_aspect" and replace it with your own aspect that you need to write

In that aspect you will have to create your own make_intellij_info_aspect (basically reproduce what the regular @intellij_aspect does). In the implementation of the aspect, before you call intellij_info_aspect_impl you will need to check "ctx.rule.kind" if its one of your custom rules. If so just remap it to one of the supported cc_* rules.

Sorry for not being able to share more.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
