### ISSUE TITLE
external dependencies  broken on mac OSX

### ISSUE THREAD

**Issue by thunterdb** [bazelbuild/intellij#16]
I used the plugin with the closest version of IntelliJ I could find (see my pull request) and I tried to load the bazel view provided in `/ijwb`. While the bazel UI seems to work, all the external dependencies such as google commons are shown as missing:

<img width="484" alt="screen shot 2016-08-31 at 5 11 08 pm" src="https://cloud.githubusercontent.com/assets/7594753/18150720/ec790234-6f9d-11e6-8432-920d28d7101d.png">

It seems so obviously broken that I am wondering if something could be wrong on mac. Do you have some suggestion on where to look in the code?

Setup:
OSX 10.11 (El Cap)
bazel 0.3.1
intellij idea: 2016.1.4 and 2016.2.3 (latest)
I tried with both the official and locally build version of the plugin

**Comment by brendandouglas** [comment]
Hi thunterdb,

The project needs a plugin SDK set (in Project Settings > Project SDK). Then IntelliJ's bundled guava library should resolve that import.

**Comment by brendandouglas** [comment]
I'll close this one -- please reopen if it was misdiagnosed, and setting the project's SDK to a plugin SDK didn't fix it.

**Comment by thunterdb** [comment]
That sounds good, thank you.
