### ISSUE TITLE
Error building debug java_binary: "Extension file not found. Unable to load package for '@runtime_classpath//:java_classpath.bzl': The repository could not be resolved."

### ISSUE THREAD

**Issue by roblg** [bazelbuild/intellij#161]
I get the following output (or similar) any time I try to execute a `java_binary` target with a debug run configuration via the plugin:

```
Building debug binary
Command: /Users/rg/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --curses=no --color=no --experimental_ui=no --progress_in_terminal_title=no --aspects=@runtime_classpath//:java_classpath.bzl%java_classpath_aspect --override_repository=intellij_aspect=/Users/rg/Library/Application Support/IntelliJIdea2017.2/ijwb/aspect --output_groups=runtime_classpath --experimental_build_event_binary_file=/var/folders/4q/rm3flsfj6qdd31h6ljx0264h0000gp/T/intellij-bep-3c2f5063-7a0f-4976-ad17-57b250c26730 --noexperimental_build_event_binary_file_path_conversion -- //tomcatRunner:foo


____(11-20 14:33:28.440) Loading complete.  Analyzing...
ERROR: (11-20 14:33:28.443) Extension file not found. Unable to load package for '@runtime_classpath//:java_classpath.bzl': The repository could not be resolved.
ERROR: (11-20 14:33:29.124) Analysis of aspect '@runtime_classpath//:java_classpath.bzl%java_classpath_aspect of //tomcatRunner:foo' failed; build aborted: Extension file not found. Unable to load package for '@runtime_classpath//:java_classpath.bzl': The repository could not be resolved.
____(11-20 14:33:29.124) Elapsed time: 1.953s
____(11-20 14:33:29.125) Waiting for build event protocol upload: 0s____(11-20 14:33:29.125) Waiting for build event protocol upload: 0s
failed (1): bazel build --tool_tag=ijwb:IDEA:ultimate --curses=no --color=no --experimental_ui=no --progress_in_terminal_title=no --aspect...
```

I get this error even with the simplest target I could come up with:

```
java_binary(
  name='foo',
  main_class='com.redfin.tomcatRunner.FooMain',
  srcs = [ 'src/main/java/com/redfin/tomcatRunner/FooMain.java'],
)
```

FooMain.java:

```
package com.redfin.tomcatRunner;

public class FooMain {
    public static void main(String[] args) {
        System.out.println("Hello, World");
    }
}
```

Info:
* bazel 0.7.0
* IntelliJ IDEA (Ultimate) 2017.2.6
* Plugin v 2017.11.06.0.5 
* A colleague on IntelliJ CE is reporting the same behavior.
* "Run" instead of "Debug" works fine.

I saw these message in the bazel console in IntelliJ w/ IntelliJ v2017.2.5 and a 2017.10.x version of the plugin, but they were just messages. I just upgraded to try and get rid of them, and it prevents running the targets completely. 

LMK if there's any other information I can provide.

Thanks!

**Comment by brendandouglas** [comment]
Thanks for letting us know. This is fixed for the next release.

**Comment by ah-edg** [comment]
Workaround:

In IDEA, go to run configurations. Add "Remote". Copy the line labeled "Command line arguments for running remote JVM".

In BUILD, add a copy of the java_binary rule, name it e.g. `idea_debug`. add `javacopts = ["-g"]` and `jvm_flags = ["` **copied line from above** `"]`.

Start your binary with `bazel run idea_debug -- ARGS_FOR_YOUR_PROGRAM` and then start the debug task in IDEA.
