### ISSUE TITLE
IntelliJ IDEA bazel plugin cannot sync kotlin projects

### ISSUE THREAD

**Issue by unoexperto** [bazelbuild/intellij#1634]
**UPD**: I tested it with Bazel 2.0.0 and 2.1.0 on multiple versions of IDEA: 2018.3, 2019.1, 2019.3, 2019.3. Sometimes, probably 1 out of 50 of fresh project imports, it works.

For some reason IDEA's bazel plugin cannot sync project defined with `kt_jvm_library` rule. As result IDE miscategorizes what packages classes belong to and etc. Sadly it's unusable.

Build complies without problem via command line.

Is there anything I could do to fix it ? 

I'm on following configuration (bazel plugin 2019.10.21.0.0-6823f76)

---
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 20, 2020
Subscription is active until July 5, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3993M
Cores: 12
Registry: 
Non-Bundled Plugins: Pythonid, Statistic, YourKit Java Profiler 2019.8-b126 Integration, org.jetbrains.kotlin, org.intellij.scala, com.google.idea.bazel.ijwb, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.hocon, wu.seal.tool.jsontokotlin

---

My BUILD is quite small. For the sake of experiment I compile java files using `java_library` and they sync in IDE.

```
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "main_kotlin",
    srcs = glob([
        "src/main/kotlin/**/*.kt",
        #        "src/main/java/**/*.java",
    ]),
    deps = [
        "@maven//:com_walkmind_extensions_collections",
        "@maven//:io_netty_netty_buffer",
        "@maven//:org_jetbrains_annotations",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)

java_library(
    name = "main_java",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        ":main_kotlin",
    ],
)

```

Example from https://github.com/bazelbuild/rules_kotlin/tree/master/examples/trivial is not working either. No bazel errors on import but IDEA can't sync:

![image](https://user-images.githubusercontent.com/1280853/74097720-7b3f1a80-4ac4-11ea-919f-b06061797ff4.png)

**Comment by sgammon** [comment]
are you sure it's not similar to #1584? the same thing happens to me on mac with a regular Java project, until I properly select my Java SDK. in my environment, oddly enough, kotlin works fine, but only after I select the SDK.

**Comment by unoexperto** [comment]
@sgammon Yep.Java SDK is properly selected and I can navigate to JDK's or Kotlin's standard lib classes.

@brendandouglas / @jin could you please help with it?

**Comment by scorsi** [comment]
Did you tried this inside your `.bazelproject` file:
```yaml
additional_languages:
  kotlin
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
