### ISSUE TITLE
plugin targets not showing up in "Bazel intelij plugin" Configuration.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#165]
Cannot use the "Bazel intelij plugin" configuration editor to create configuration to test plugins as the target dropdown in the configuration contains no entries. It's also not possible to type in a target.

I had a valid plugin launch configuration before the last update.

**Comment by hsyed** [comment]
The build file in `/ijwb` needs to be manually partially synced in order to get the target to show up.

**Comment by brendandouglas** [comment]
Thanks, I've updated the checked in .bazelproject files upstream.

Until that lands here, you can workaround by adding this to your local .bazelproject file:

```
targets:
  //ijwb:ijwb_bazel_dev
```
