### ISSUE TITLE
Javadocs not showing

### ISSUE THREAD

**Issue by mleonhard** [bazelbuild/intellij#1663]
I need the IDE to show javadocs:
> [Matcher.matches()](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/regex/Matcher.html#matches())
> public boolean matches()
> Attempts to match the entire region against the pattern.
> If the match succeeds then more information can be obtained via the start, end, and group methods.
> 
> Returns:
> true if, and only if, the entire region sequence matches this matcher's pattern

But it just shows the method signature:
![screenshot](https://user-images.githubusercontent.com/520739/75103651-624d6380-55b2-11ea-9637-03eefadf03fe.png)

Do you have any ideas for making it show javadocs?

Demo project: [bazelBug1.zip](https://github.com/bazelbuild/intellij/files/4240605/bazelBug1.zip)

Bazel plugin 2020.01.28.0.3
IntelliJ IDEA 2019.2.4 (Community Edition)
Build #IC-192.7142.36, built on October 28, 2019
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: 
Non-Bundled Plugins: google-java-format, org.intellij.plugins.hcl, com.google.idea.bazel.ijwb, Docker, org.sylfra.idea.plugins.linessorter

**Comment by mleonhard** [comment]
This issue is still present after upgrading to:
- IntelliJ IDEA 2019.3.3 (Community Edition)
- Bazel plugin 2020.02.11.0.0

**Comment by brendandouglas** [comment]
That's a JDK class, so sources are attached independently to the Bazel plugin (e.g. https://mkyong.com/java/how-to-attach-jdk-source-code-to-intellij-idea/)

**Comment by mleonhard** [comment]
Bazel downloads a JDK binary and uses it to compile and run tests.  Is there a way to make it also download the source for the exact same JDK version?

**Comment by brendandouglas** [comment]
Perhaps, but that would require changes on the bazel side of things. For now, the recommended approach here is the same as for vanilla IntelliJ usage -- to attach sources to the project JDK through the IDE.
