### ISSUE TITLE
Sources not found for artifacts using maven_install version 2.10 or higher

### ISSUE THREAD

**Issue by btbuxton** [bazelbuild/intellij#1666]
Versions:
bazel 1.0.0
intellij 2019.2.2
intellij-bazel plugin 2019.09.03.0.0
maven_install rule 2.10 - 3.1 (https://github.com/bazelbuild/rules_jvm_external)

maven_install is recommended to download maven artifacts for bazel 2.0 since maven_jar is deprecated. The sources for downloaded artifacts are found for maven_install versions 2.9 or earlier, but starting in 2.10, the sources are no longer found.

This is a blocking issue for Bazel 2.0 adoption.

**Comment by jin** [comment]
Please try rules_jvm_external release 3.2.

**Comment by btbuxton** [comment]
I switched to 3.2 and the sources are still not found.

**Comment by btbuxton** [comment]
I tried again with a clean install and latest intellij bazel plugin. it is now working with the latest 3.2. Closing.
