### ISSUE TITLE
GDB substitute-path is incorrect in CLion

### ISSUE THREAD

**Issue by asm** [bazelbuild/intellij#1670]
When debugging a C++ target in CLion, the plugin attempts to set a substitute path to allow proper source file resolution in GDB.  However, this code has a simple bug: instead of using the workspace path, it uses the workspace's parent directory causing GDB to fail source file resolution.  

Thus, breakpoints are never set and disassembly is shown when exceptions are hit.  See [this line](https://github.com/bazelbuild/intellij/blob/v2020.02.24/clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrLauncher.java#L267) for the issue.  Changing `workspaceRootDirectory.getParent()` to `workspaceRootDirectory.getPath()` resolves the issue.

**Versions:**
CLion 2019.3.4
Using bundled GDB
Bazel Plugin @ [d6af235](https://github.com/bazelbuild/intellij/commit/d6af235f05880dd9bf1518a652fdb21b9b66fbc3)
Ubuntu Linux 16.04.6 LTS

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
