### ISSUE TITLE
Error: Debug: there are no runners for Bazel Command

### ISSUE THREAD

**Issue by gyakushev** [bazelbuild/intellij#1675]
The Debug button is greyed out: cannot run bazel C++ binary in debug mode.
Normal run works fine.
When going to menu Run->Debug->MyConfig->Edit I see the error message at the bottom: `Error: Debug: there are no runners for Bazel Command`
CLion: 2019.2.5

**Comment by chaoren** [comment]
Make sure it's not a sh_binary of some kind wrapping around a cc_binary.
We can only debug cc_binary/cc_test directly.
We won't know what debugger to use if it's a rule type that we don't recognize.

**Comment by chaoren** [comment]
Of course running any of those would still be fine since it's just a blaze run, and we won't need to attach a debugger.

**Comment by gyakushev** [comment]
Thanks! Yes, we had some wrapping rules in our bazel infrastructure. The problem is solved for me.
