### ISSUE TITLE
Support Hot Swap on Remote Debug

### ISSUE THREAD

**Issue by rhollencamp** [bazelbuild/intellij#1677]
Currently Hot Swap ('Run -> Reload Changed Classes') only works on 'Bazel Command' configurations. It would be great if I could connect to an already running JVM (IntelliJ 'Remote' configuration) and still be able to hot swap changes into it

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
