### ISSUE TITLE
Very slow initial load of project

### ISSUE THREAD

**Issue by clrusby** [bazelbuild/intellij#1682]
I just upgraded from CLion 2019.2.5 and bazel plugin 2019.12.02.0.0 to CLion 2019.3.4 and bazel plugin 2020.02.11.0.0.  I'm running on RH7 with Java 8 (revision 102).

Previously, the IDE would open my projects pretty quickly, although I couldn't then run any configurations for a while until the project had sync'd.

Now when I first open a project in the IDE, it hangs on the "Loading .clwb Project" dialog box (with message "Loading components...") for maybe 2-3 minutes, before the IDE opens.  However, when the IDE has opened, the project is already sync'd and ready to run.

Has there been some change in behaviour here?  I prefer the previous behaviour...

Thanks
Chris

**Comment by sgowroji** [comment]
Hello @clrusby, Are you still seeing the issue with the latest bazel plugin release versions and Clion IDE. Thanks!

**Comment by clrusby** [comment]
I'm afraid I stopped using CLion about 18 months ago so wouldn't know.

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
