### ISSUE TITLE
Partial sync takes too much system memory making OS very slow

### ISSUE THREAD

**Issue by linkin8834** [bazelbuild/intellij#1688]
Hi there,

I am wondering if there is support of adding flags such as number of jobs and cores and RAM utilization ratio for IntelliJ bazel plugin such that partial sync of my project would not eat up all OS memory?

Thanks!

**Comment by chaoren** [comment]
You can add [`--jobs`](https://docs.bazel.build/versions/master/user-manual.html#flag--jobs) to the [`build_flags`](https://ij.bazel.build/docs/project-views.html#build_flags) section of your project view.
