### ISSUE TITLE
Unable to run specs2 tests containing non-regex safe characters

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#169]
Currently, tests that are named e.g. `"check that 2+2 == 4"` or `"do something (quietly)"` will not run, because this is not a valid regex, and fail in Bazel validation (see bazelbuild/bazel#4120)

Should the string passed to the test filter be escaped (using [Pattern.quote](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)), or should this be handled in Bazel?

**Comment by hmemcpy** [comment]
After talking this over with @ittaiz, and the folks that handle the java/junit rules in Bazel, it's best to escape the test filter at the sender side, i.e. the plugin.

**Comment by chaoren** [comment]
Fixed with `Pattern.quote` on the test case name.

**Comment by hmemcpy** [comment]
Thanks so much, I was about to send a PR for this as well :)
(got stumbled by writing tests for this, unfortunately `ScInfixExpr`'s reference expressions don't resolve in tests (calling `.resolve()` returns a `null`).

I got initially tripped by the `$` at the end, it needs to be added AFTER the escaped test name, e.g.
`\Qcom.example.MyTest#something should::do something (quietly)\E$`

**Comment by chaoren** [comment]
Yeah we don't have good test coverage for test expressions at all.
Getting the integration tests to work for the test class was already a pain in the ass with all the sentinel classes in the inheritance chain.

**Comment by hmemcpy** [comment]
Yeah :(
Anyway, thanks for this fix, I'll need to tweak this on the rules_scala side, to make sure the escaped pattern is handled correctly.
