### ISSUE TITLE
command clean has mandatory target 

### ISSUE THREAD

**Issue by fal-foyer** [bazelbuild/intellij#1690]
I tried the clean command with the plugin on IntelliJ 2019.3. But the target field is mandatory.
however, that command doesn't support target.  

Maybe, I make something wrong ?

**Comment by sgowroji** [comment]
Hello @fal-foyer, Could you please  elaborate your query with complete details and can you try testing the issue  with the latest bazel plugin and Intellij ide and see if you still able to reproduce on it. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
