### ISSUE TITLE
[NICE TO HAVE] Unable to use Bazel Plugin with IDEA Ultimate 2019.3.3

### ISSUE THREAD

**Issue by kigster** [bazelbuild/intellij#1693]
```
IntelliJ IDEA 2019.3.3  Build #IU-193.6494.35
JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
OS: Mac OS X
Plugin to blame: Bazel version: 9999
Last Action: EditorBackSpace
No SyncPlugin present which provides a default workspace type.
```

I have tries both official plugin from the marketplace and locally built from commit `06c777fa58b00c49fd887279df382f1c41ad49fc` with the following command"

```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2019.3
```

I see the following exception in the IJ log:

```
java.lang.IllegalStateException: No SyncPlugin present which provides a default workspace type.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
	at com.google.idea.blaze.base.sync.projectview.LanguageSupport.getDefaultWorkspaceType(LanguageSupport.java:47)
   ....... etc (many lines removed)
```

I put together a [detailed error report gist](https://gist.github.com/kigster/137bac96f42135d20907c8518dc918cb) — please take a look if you need more information.

Please help. I am stuck! 🥺

**Comment by stefanobaghino-da** [comment]
I had the same issue when starting from a blank installation where I disabled a lot of bundled plugins. I believe the Bazel plugin relies on some bundled plugin to be there at runtime and worked around it by restoring my 2019.2 config that had the plugins enabled. Hope this may help.

**Comment by kigster** [comment]
@stefanobaghino-da I agree with you. I wonder what plugin is needed. Ill see if I can try to turn them all.

**Comment by nollbit** [comment]
I had the same issue, and removing all configuration and restarting with default plugins solved the problem for me as well.

**Comment by kigster** [comment]
To be clear — here is how I was able to restore this on a Mac:

1. Remove `~/Library/Preferences/IntelliJIdea2019.3` folder
2. Start IDEA
3. Choose 'Reset to Default Plugins'
4. Start — Import Bazel Project.

**Comment by rayman1104** [comment]
> @stefanobaghino-da I agree with you. I wonder what plugin is needed. Ill see if I can try to turn them all.

You were right, the problem is lack of some plugins.
Empirically just determined that plugin is JUnit (at least it was a deal breaker for me).

**Comment by AlexeyGy** [comment]
Closing this as a stale issue.

**Comment by stefanobaghino-da** [comment]
> Closing this as a stale issue.

I'm not sure this is stale but it may need some rewording.

Some contributor may be interested in fixing this. Probably just improving the error message to allow people to know how to work around this may help others. 🙂
