### ISSUE TITLE
Debugging support for Starlark

### ISSUE THREAD

**Issue by Rondom** [bazelbuild/intellij#1706]
It would be nice, if the plugin would support debugging Starlark code, i.e. setting breakpoints in Starlark code, single-step, evaluate statements etc.

The Bazel plugin for VS Code has this functionality: https://github.com/bazelbuild/vscode-bazel#using-the-starlark-debugger

**Comment by brendandouglas** [comment]
This should already work for the bazel plugin. For example, right-clicking on a java_library target in a BUILD file, then selecting 'debug blaze build...'

**Comment by Rondom** [comment]
I see, thank you.

**Comment by abhillman** [comment]
This sometimes shows up and it's not clear to me why it does sometimes and not others

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1097794/178128155-7f39723a-7731-413b-938a-daf849e74571.png">


<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1097794/178128157-02d3dc79-1633-4a81-a454-2a8e24d8b69e.png">
