### ISSUE TITLE
Error with dev build on install from jar: "Encountered error while reading extension file 'intellij_info_bundled.bzl'"

### ISSUE THREAD

**Issue by roblg** [bazelbuild/intellij#171]
I couldn't wait for Friday, so I pulled down HEAD (20fcbfec670f4feeb42c34ed0ed157682db19e72) and built it and tried to install it. It allegedly installs fine, but I get an error (twice) about `intellij_info_bundled.bzl`. I'm using bazel 0.8.0, but I got this error w/ 0.7.0 as well, and I get it in two different repositories (internal repo + bazel-intellij repo)

```
# command:
/Users/robert.gay/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --keep_going --experimental_build_event_binary_file=/var/folders/4q/rm3flsfj6qdd31h6ljx0264h0000gp/T/intellij-bep-cd36dd2e-1d17-4edb-85a0-f9206d6210a1 --noexperimental_build_event_binary_file_path_conversion --curses=no --color=no --experimental_ui=no --progress_in_terminal_title=no --define=ij_product=intellij-latest --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/Users/robert.gay/Library/Application Support/IntelliJIdea2017.2/ijwb_bazel.jar/aspect --output_groups=intellij-info-java,intellij-info-py,intellij-info-generic -- //ijwb:all

# output
ERROR: Encountered error while reading extension file 'intellij_info_bundled.bzl': no such package '@intellij_aspect//': /private/var/tmp/_bazel_robert.gay/26b791e9f5b83f093a207d9fbb6765e8/external/intellij_aspect must be an existing directory.
```

I can confirm that the path in question exists, but it's a symlink pointed to a weird/busted place:

```
$ ls -l /private/var/tmp/_bazel_robert.gay/26b791e9f5b83f093a207d9fbb6765e8/external/
# ... 
lrwxr-xr-x   1 robert.gay  wheel    86 Nov 27 16:06 intellij_aspect -> /Users/robert.gay/Library/Application Support/IntelliJIdea2017.2/ijwb_bazel.jar/aspect
# ...
```

Looks like somebody asked about this on bazel-discuss w/ no responses awhile back https://groups.google.com/d/topic/bazel-discuss/p8GkVO_m-uA/discussion.

The README no longer say that we shouldn't expect this to compile/work, so maybe there's an actual bug here when building from source?

I'd love to be able to help beta test this for y'all. :)

edit: added command that was being executed + clarifying context.
edit2: updated title to reflect my belief that it's only a development issue, since others on mailing list saw it on previous versions when building from source as well

**Comment by brendandouglas** [comment]
Thanks for letting us know. The README build instructions were out of date -- you'll need to build `//ijwb:ijwb_bazel_zip`, and install from the zip directly (which bundles both the plugin jar and aspect files).

**Comment by roblg** [comment]
Glad it was easy. The changes to DirectoryStructure took that step from 3 minutes on our build to 5.3s. :drool:

Thanks!

**Comment by promiseofcake** [comment]
Works for me too, thanks! One note is that you need to uninstall the old plugin, restart the IDE and then re-install the newly built plugin and restart the IDE. Otherwise I was running into the same issues even after install.
