### ISSUE TITLE
 **kwargs auto-complete

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/intellij#1714]
Imaging we want to extend a Bazel rule such as py_test. For this we introduce a macro:

`
def extended_py_test(
        name,
        custom_attribute,
        **kwargs):
    native.py_test(
        name = name,
        **kwargs
    )
    _custom_stuff(
        name = name + "_costom_stuff",
        custom_attribute = custom_attribute,
        ...
    )
`

The problem is then is that the auto completion for extended_py_test only shows `custom_attribute` but not all the other attributes supported by py_test (e. g. name, deps, srcs, data, args, compatible_with, default_python_version, deprecation, distribs, exec_compatible_with, exec_properties, features, flaky, imports, legacy_create_init, licenses, local, main, python_version, restricted_to, shard_count, size, srcs_version, stamp, tags, testonly, timeout, toolchains, visibility). To circumvent this problem we could add all those parameters to `extended_py_test` instead of using `**kwargs` - but this does not look nice - how should we deal with it?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
