### ISSUE TITLE
Sporadic error since bazel v0.8.0

### ISSUE THREAD

**Issue by trivigy** [bazelbuild/intellij#173]
Error:Source forest creation failed: /home/trivigy/.cache/bazel/_bazel_trivigy/8245dac4cdce712b9bed756930a752ca/execroot/syncaide/bazel-sync (File exists).

If I manually run `bazel clean --expunge` the error goes away for at least the next build but comes but sporadically. Would appreciate some insight.

**Comment by brendandouglas** [comment]
Thanks, this is a Bazel-side issue (bazelbuild/bazel#3857).
