### ISSUE TITLE
macOS + CLion: debugging broken

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/intellij#1736]
Bazel targets on CLion 2019.3 on macOS can't be debugged; they hang on "Connecting."  Debugging CMake-based projects works fine.

On 2019.2 debugging works, but breakpoints are not honored.

**Comment by HenryYYang** [comment]
I have the same problem.

**Comment by dozer47528** [comment]
I have the same problem.

**Comment by kayasoze** [comment]
Breakpoints still broken on 2020.1.

**Comment by mai93** [comment]
@tpasternak is this also fixed with https://github.com/bazelbuild/intellij/pull/4003?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
