### ISSUE TITLE
ERROR: X:/mediapipe-master/WORKSPACE:282:12: invalid escape sequence: 

### ISSUE THREAD

**Issue by Lotfi-MERAD** [bazelbuild/intellij#1741]
#### Version information
AndroidStudio: 3.6.1
Platform: Windows 10 10.0
Bazel plugin: 2020.02.24.0.3
Bazel: 1.0.1

**Comment by Lotfi-MERAD** [comment]
ERROR: X:/mediapipe-master/WORKSPACE:282:12: invalid escape sequence: \U
ERROR: X:/mediapipe-master/WORKSPACE:282:12: invalid escape sequence: \a
ERROR: X:/mediapipe-master/WORKSPACE:287:12: invalid escape sequence: \U
ERROR: X:/mediapipe-master/WORKSPACE:287:12: invalid escape sequence: \a
ERROR: error loading package 'external': Failed to parse WORKSPACE file
Sync finished
Sync failed

**Comment by Lotfi-MERAD** [comment]
i try to install mediapip in andoid studio any help please?????

**Comment by Jackal-Studios** [comment]
If the path for the SDK/NDK versions is added in the form of C:\Users\[username]\AppData\Local\Android\sdk you need to change the backslashes ( \ ) to normal slashes ( / ) so it will look like "C:/Users/[username]/AppData/Local/Android/sdk"
