### ISSUE TITLE
No structure in External Libraries -> Go Libraries

### ISSUE THREAD

**Issue by AntonIvanov87** [bazelbuild/intellij#1744]
There is no structure in External Libraries -> Go Libraries
![Screenshot from 2020-03-20 15-43-38](https://user-images.githubusercontent.com/3289141/77174602-99d00280-6ac1-11ea-8e94-dbde4a248e6a.png)
I find it useful to "Select Opened File" in the Project view and then to explore neighboring files and packages.
But if you do that with a library file - it will be selected in the External Libraries -> Go Libraries, which does not have any structure, just a list of all files from all libraries.

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/commit/593a8014a48194d2a23479bbd09d230efc2b5b5c
