### ISSUE TITLE
Feature request: directories should understand regex patters similar to test_sources

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/intellij#1745]
Feature request have the `directories:` field accept dir patters similar to what `test_sources`. For example: 
```
directories: 
   # include
   .
   # exclude
   -*/build/*
```
Should add all dirs except of `build` dirs which are often where Gradle places generated output. 

Another useful feature is to do something like:
```
directories: 
   # include
   */java

   # exclude
   -*/build/*
```
For project that don't follow the recommended directory structure this will allow to include all `java` dirs and set them as source root

#### Version information
AndroidStudio: 3.6.1
Platform: Linux 4.15.0-1073-oem
Bazel plugin: 2020.02.24.0.3
Bazel: 999.999.999

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by nkoroste** [comment]
How do I reopen this issue? do you mean to create a brand new one?
