### ISSUE TITLE
Kotlin test classes are only recognized as such by the UI if they have no other top-level members

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/intellij#1750]
In a test class like this:

```
package foo

class FooTest {
  @Test fun fooTest() {}
}

private String.convenienceMethod = process(this)
```

The UI will not show "run bazel test FooTest..." and "debug bazel test FooTest..." unless you re-work the class like so:

```
package foo

class FooTest {
  @Test fun fooTest() {}
  private String.convenienceMethod = process(this)
}
```

In this case, the UI jazz for running/debugging the test directly shows up. 

The former is a very legitimate form in Kotlin, so ideally the IDE would look at the right things, and show the correct UI options (the whole thing runs from the cli fine) 

Also, changing the test_class to "foo.FooTestKt" doesn't help, nor does adding `@file:JvmName("FooTest")`

When you do this, the kotlin plugin itself changes the representation from a "kotlin class" to a "kotlin file" which probably is where aswb is getting the signal.

**Comment by dimsuz** [comment]
Wow, thanks, I was close to banging my head against the wall trying to find why IDE suddenly stopped understanding syntax in my tests, everything was red.

After I moved top-level defs inside of the class it was fixed.

Now the only remaining issue is the errors on top of quoted method names.

![Screenshot from 2020-04-10 21-51-35](https://user-images.githubusercontent.com/42920/79019363-77884c80-7b76-11ea-9f0e-46e88276b499.png)

This is indeed an Android project, but unit tests are a separate beast and this restriction should not hold. And tests compile and run just fine in console.

If this needs to be reported in a separate issue, I can create it.

**Comment by nkoroste** [comment]
Just to confirm, does this mean non of the classes in a given build test target can't have top-level defs? i.e if at least one file in the target has a top-level declaration all test classes in that target loose the ability to debug and break they UI?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
