### ISSUE TITLE
Sync find error ,Unable to start bazel project normally

### ISSUE THREAD

**Issue by Derek-G** [bazelbuild/intellij#1759]
When I imported bazel project, an error appeared in sync. I am not sure how to do it now, I tried to change the name of  /.cache directory, but the same error still occurred after rerun.
IntelliJ IDEA 2018.2.8 (Community Edition)
Build # ic-182.5262.2, built on March 28, 2019
JRE: 1.8.0 comes with _152 - release - 1248 - b22 amd64
JVM: OpenJDK 64-bit Server VM by JetBrains S.R.O.
Linux 4.4.0-139 - generic

Bazel console's message:

Syncing project: Sync (incremental)...
Updating the VCS...
Command: bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --

Running Bazel info...
Command: git diff - name - the status - no - 6618 c8ea55a5fcb13c86c301419d8fc26941bfa3 renames

ERROR: / home/user/cache/bazel _bazel_vagrant/ef369ed8f6ea898d2085c6da7ce1d977 / external/bazel_skylib/lib/unittest BZL: 188:27: the name 'analysis_test_transition' is not defined.
ERROR: ERROR loading package '': Extension 'lib/unittest.bzl' has errors.

= = = = TIMING REPORT = = = =

Sync: 617 ms (231 ms)
BazelInfo: 385 ms
GitDiff: 0 ms

Timing the summary:

BlazeInvocation: 385 ms
Sync failed

**Comment by Derek-G** [comment]
Additional information about bazel version not mentioned above:

Build label: 0.19.2
Build target: bazel - out/k8 - opt/bin/SRC/main/Java/com/Google/devtools/Build/lib/bazel BazelServer_deploy. The jar
Build time: Mon Nov 19 16:25:09 2018 (1542644709)
Build timestamp: 1542644709
Build timestamp as int: 1542644709

**Comment by sgowroji** [comment]
I'll close the issue. If you still can reproduce it, please reopen.
