### ISSUE TITLE
Support Kotlin compiler plugins

### ISSUE THREAD

**Issue by utikeev** [bazelbuild/intellij#1773]
With the [introduction](https://github.com/bazelbuild/rules_kotlin/commit/484f116c1949984697556bcd371ef8eecacc08cb) of `kt_compiler_plugin` rule, it would be great to have support for them in IDE, so the generated code (for example, from [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) plugin) will be resolved correctly.

That can be done by adding 
```
<array>
    <option value="$KOTLIN_BUNDLED$/lib/PLUGIN_JAR_NAME.jar" />
</array>
```
to `component -> facet -> configuration -> compilerArguments -> pluginClasspaths` block of `.workspace.iml` for Kotlin facet.

**Comment by cgruber** [comment]
We have the plugin information now attached to the KtInfo provider. Is there something we can expose further that can give IJ/ASwB hints as to what to add?

**Comment by th0masb** [comment]
Just for clarification for anyone who comes across this you can manually alter `.ijwb/.blaze/modules/.workspace.iml` to change the kotlin facet to look like

```
    <facet type="kotlin-language" name="Kotlin">
      <configuration version="4" platform="JVM 1.8" allPlatforms="JVM [1.8]" useProjectSettings="false">
        <compilerSettings>
          <option name="additionalArguments" value="-Xallow-no-source-files" />
        </compilerSettings>
        <compilerArguments>
          <option name="pluginOptions">
            <array />
          </option>
          <option name="pluginClasspaths">
            <array>
              <option value="$KOTLIN_BUNDLED$/lib/kotlinx-serialization-compiler-plugin.jar" />
            </array>
          </option>
          <option name="errors">
            <ArgumentParseErrors />
          </option>
        </compilerArguments>
      </configuration>
    </facet>
```
in order to workaround the lack of an "official" solution

**Comment by jesseschalken** [comment]
An alternative to the above is to modify the equivalent setting at the project level instead of at the module level.

The file is in `.ijwb/.idea/kotlinc.xml` (you may need to open "File | Settings | Build, Execution, Deployment | Compiler | Kotlin Compiler" and hit "Save" to create this file).

You need to add a `KotlinCommonCompilerArguments` component to the project which you can put the same `pluginClasspaths` option inside.

Example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="KotlinCommonCompilerArguments">
    <option name="pluginClasspaths">
      <array>
        <option value="$KOTLIN_BUNDLED$/lib/kotlinx-serialization-compiler-plugin.jar" />
      </array>
    </option>
  </component>
  <component name="Kotlin2JvmCompilerArguments">
    <option name="jvmTarget" value="11" />
  </component>
</project>
```
