### ISSUE TITLE
Editor tabs for unsynced files are colored, can be confusing

### ISSUE THREAD

**Issue by shivaalroy** [bazelbuild/intellij#1779]
If a file is unsynced, its editor tab will be colored, which can cause confusion, as the highlighted tab is more pronounced than the active tab indicator:
![image](https://user-images.githubusercontent.com/6589287/79263139-367a8b80-7e47-11ea-8c4e-2ab32add23ce.png)

Proposal to create a setting under the Bazel plugin setting as: 

- [x] Color editor tabs for unsynced files

, add the corresponding field to BlazeUserSettings, and then read the field in SyncStatusEditorTabColorProvider. 

The default setting will not change behavior from the status quo. The change should be ~20 lines.

**Comment by chaoren** [comment]
We do want it to be more pronounced. It's usually some problem with the project view if the user's editing an unsynced file, and we want the user to notice. I think there's some value in keeping the plugins setting as lean as possible so users don't get overwhelmed when trying to find a particular setting or just explore the options.

**Comment by shivaalroy** [comment]
I see. I believe there's a valid use case for working on unsynced files, as they could be tagged as `manual` and this situation would occur. I understand the desire to have a lean plugin settings page, so then I'm wondering if there can be some other way for a user to disable this coloring. I'm just looking for something I can do to resolve this for myself.

**Comment by chaoren** [comment]
Have you tried editing Settings -> Appearance & Behavior -> File Colors?

**Comment by chaoren** [comment]
I think we're using the "Problems" color for unsynced files.

**Comment by shivaalroy** [comment]
That was one of the first things I tried, and I just tried it again with no luck. 

I've unchecked all of the boxes ("Enable File Colors", "Use in editor tabs", "Use in project view") and the color still shows up. I create a local color on that setting page that targeted the "Problems" scope, but the unsynced editor tab is not affected by it. Looking at the code in `SyncStatusEditorTabColorProvider.java`, it seems that the tab color is set to a hardcoded value rather marking the file as part of the "Problems" scope. Would it make sense for the bazel plugin to mark file as a "Problem" rather than manually setting the color?

Thanks for taking the time to respond to me, by the way. I appreciate it.

**Comment by chaoren** [comment]
Ah sorry, the file I was looking at actually had problems, so it changed colors when I changed the problems category. This also means that whatever color you choose would just override the existing colors that we set. I think you could just add an Open Files entry and set the color to what regular open files have.

**Comment by shivaalroy** [comment]
I tried this too, and saw this as a workaround. Not exactly ideal as the active tab gets the selected color and inactive tabs get slightly off-colored, so I guess I'll just deal with existing behavior for now.

**Comment by shivaalroy** [comment]
Would have been preferable if the bazel package itself offered some way to modify this, rather than trying to tweak other settings to get the desired behavior.
