### ISSUE TITLE
Support CLion 2020.1

### ISSUE THREAD

**Issue by zhuker** [bazelbuild/intellij#1780]
I know you are working on it
this issue is a placeholder for when it's done (CLion wasn't mentioned only GoLand)
 
![image](https://user-images.githubusercontent.com/4367682/79386600-3ea5fa00-7f1f-11ea-9bf4-36e2a1ddff40.png)
![image](https://user-images.githubusercontent.com/4367682/79386636-482f6200-7f1f-11ea-98ae-5f1dc9304a28.png)
![image](https://user-images.githubusercontent.com/4367682/79386643-4bc2e900-7f1f-11ea-95d4-fd647cd168c1.png)

**Comment by zhuker** [comment]
#1567

**Comment by alice-ks** [comment]
Plugin versions 2020.09.16.0.6+ are compatible with CLion 2020.1. Hence, I'm closing this issue now. Please refer to other existing tracking issues if you're interested in support for newer CLion versions.
