### ISSUE TITLE
Add support for marking folders as resources / test resources in project view file

### ISSUE THREAD

**Issue by jimmyzzxhlh** [bazelbuild/intellij#1784]
There is currently no way to mark folders as resources or test resources in the `.bazelproject`. Without Bazel, in IntelliJ we can mark a folder as a root resource folder or test resource folder, and switching to Packages view will merge src, test, and resource folders nicely. For example, if I have the following folders:

```
src/main/java/some_package/someClass.java
src/main/test/some_package/someClassTest.java
src/main/resources/some_package/resource_file.txt
```

By marking `src/main/resources` folder as the root resource folder in IntelliJ I can see `someClass.java`, `someClassTest.java` and `resource_file.txt` under the same folder in Package view.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
