### ISSUE TITLE
Attention! No symbol directories found - please check your native debug configuration

### ISSUE THREAD

**Issue by weinixuehao** [bazelbuild/intellij#1797]
Android Studio:3.6.3
Bazel-plugin:2020.02.24.0.3
bazel version:2.0.1
NDK:android_ndk_r20b

`Waiting for application to come online: com.google.mediapipe.apps.edgedetectiongpu
Connecting to com.google.mediapipe.apps.edgedetectiongpu
Now Launching Native Debug Session
Attention! No symbol directories found - please check your native debug configuration
$ adb shell cat /data/local/tmp/lldb-server | run-as com.google.mediapipe.apps.edgedetectiongpu sh -c 'cat > /data/data/com.google.mediapipe.apps.edgedetectiongpu/lldb/bin/lldb-server && chmod 700 /data/data/com.google.mediapipe.apps.edgedetectiongpu/lldb/bin/lldb-server'
$ adb shell cat /data/local/tmp/start_lldb_server.sh | run-as com.google.mediapipe.apps.edgedetectiongpu sh -c 'cat > /data/data/com.google.mediapipe.apps.edgedetectiongpu/lldb/bin/start_lldb_server.sh && chmod 700 /data/data/com.google.mediapipe.apps.edgedetectiongpu/lldb/bin/start_lldb_server.sh'
Starting LLDB server: /data/data/com.google.mediapipe.apps.edgedetectiongpu/lldb/bin/start_lldb_server.sh /data/data/com.google.mediapipe.apps.edgedetectiongpu/lldb unix-abstract /com.google.mediapipe.apps.edgedetectiongpu-0 platform-1587902444333.sock "lldb process:gdb-remote packets"
Debugger attached to process 7459`

**Comment by keith** [comment]
I see this too, but can you tell if this is causing specific issues? I think in our case it's a red herring

**Comment by mai93** [comment]
@weinixuehao @keith are you still seeing this with newer versions of AS and the plugin?

**Comment by keith** [comment]
not sure

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
