### ISSUE TITLE
Profiling doesn't work on CLion

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/intellij#1801]
CLion has built in profiling tooling. When using it on a Bazel project, it seems to just execute the tests but not execute the tests under `perf` to collect profiling implementation.

Tested on CLion 2019.1 Linux
Plugin version: 2019.08.19.0.4
Bazel version: 1.2.1

**Comment by wesleyw72** [comment]
Issue raised on Jetbrains support as well https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008184900-CLion-Profiling-with-Bazel.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by mik90** [comment]
Hi, I'd like to bump this request as it'd be very useful

**Comment by auzhva** [comment]
Hi,

This is still missed. Would it be possible to deliver that?

**Comment by dieortin** [comment]
+1

**Comment by Vertexwahn** [comment]
+1
