### ISSUE TITLE
Clion 2020.01 can't find the bazel plugin in MacOS

### ISSUE THREAD

**Issue by Changeset** [bazelbuild/intellij#1803]
![image](https://user-images.githubusercontent.com/5583402/80720316-52607b80-8b2f-11ea-8380-10fa85b5a967.png)

System:MacOS 10.15.3 
Clion Version:2020.01

Is there no support for Clion 2020.01 in MacOS?

**Comment by zhuker** [comment]
#1567 #1780

**Comment by brendandouglas** [comment]
There is no support for CLion 2020.1 yet, though it's something we're looking into now.

**Comment by zhuker** [comment]
@brendandouglas did you figure out how to compile the plugin for clion 2020?

**Comment by brendandouglas** [comment]
Each new version requires changes for plugin API compatibility. We've done that for IJ 2020.1, but not yet for CLion 2020.1.

**Comment by zhuker** [comment]
@brendandouglas any plans for it?

**Comment by brendandouglas** [comment]
Yep, we're looking into it now.

**Comment by zhuker** [comment]
cant wait

**Comment by teddyzhai** [comment]
there is update on the plugin, but for the order version of Clion (2019.3.4). Why???

**Comment by brendandouglas** [comment]
To clarify: updates to this repo are done automatically, synced from upstream. We upload updates to plugins.jetbrains.com (the last update was in April). They coincide with internal releases, which we intentionally keep on older, more stable, and more performant releases -- new JetBrains releases can take a while to stabilize, and any performance regressions can cause massive increases in freezes for our internal users.

As mentioned above, we are currently working on 2020.1 support.

**Comment by shrimptttttttttt** [comment]
I have checked the latest clion version 2020.2 still doesn't support BAZEL.
This cause huge inconvenience for coding with a bazel project. 
Strongly hope you will fix this as soon as possible please. 
Thx very much. 

> To clarify: updates to this repo are done automatically, synced from upstream. We upload updates to plugins.jetbrains.com (the last update was in April). They coincide with internal releases, which we intentionally keep on older, more stable, and more performant releases -- new JetBrains releases can take a while to stabilize, and any performance regressions can cause massive increases in freezes for our internal users.
> 
> As mentioned above, we are currently working on 2020.1 support.

I have checked the latest clion version 2020.2 still doesn't support BAZEL.
This cause huge inconvenience for coding with a bazel project. 
Strongly hope you will fix this as soon as possible please. 
Thx very much.

**Comment by shrimptttttttttt** [comment]
@brendandouglas The latest 2020.2 clion still doesn't support clion. 
Strongly hope you can fix this as soon as possible. 
Thx very much.
