### ISSUE TITLE
Support HotSwapping / Class Reloading for tests

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#181]
This is a follow-up to #50.

It's currently [tricky to implement](https://github.com/bazelbuild/intellij/issues/50#issuecomment-349683764), but it would be great if Bazel could support hotswapping in test projects (scala/java).
Keeping this issue for future discussions of possible implementations.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by donce** [comment]
:+1: on this one - I'm really missing this feature..
