### ISSUE TITLE
Standalone IDE tooling API

### ISSUE THREAD

**Issue by Jonpez2** [bazelbuild/intellij#1827]
I have been noodling for a while with generating .classpath/.project files for VSCode support.  I wonder if it would be possible to refactor this plugin slightly into a library that can be used to generate all the awesome introspection data, and then the plugin proper that uses that data for Intellij.  It seems to me that would enable other IDE support at a far lower cost.

Thank you for listening, and thank you for lovely IJ tooling!

**Comment by brendandouglas** [comment]
The aspect code for communicating with Bazel is a very small part of this
plugin (and the only part which is IDE agnostic).

To modify the plugin for VSCode support, you'd need to write all the code
for (a) running the builds, with the aspect attached, and (b) processing
the result then passing it on to VSCode in whatever format it expects.

That would provide the project setup component of the plugin, though not
the custom language support components.

Definitely possible, but not something we'll likely be working on in the
medium term.

**Comment by Jonpez2** [comment]
Right.  So although that's a tiny part of the plugin, it's a part that exists nowhere else and is not totally trivial to implement - it was in fact easier for me to hack around in your repo, copying and pasting bits around, and depending on the intellij sdk.  I've got something semi-working, but it's a mess.  Having a clean little lib with the functionality that doesn't depend on, say, com.intellij.openapi.extensions.ExtensionPointName, would be lovely.

All we need to beat the current vscode integration is to generate .classpath and .project, and then the redhat vscode plugin will be functional-ish.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
