### ISSUE TITLE
Support abstract test classes in specs2

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#183]
When trying to run an abstract test class (using specs2/junit), it should prompt you for the concrete instance to execute.

**Comment by chaoren** [comment]
We already have this for abstract Java classes, we can probably just reuse that. There's no such thing as overriding an abstract spec2 test expression, right? Can JUnit test methods exist in a specs2 test?

**Comment by hmemcpy** [comment]
@chaoren I just checked:
no, it seems you can't write junit test methods in a specs2 test (thank god! :))

Also, it seems that marking a plain Java JUnit test "abstract" will remove the run markers from individual test methods (because `TestFramework.isTestMethod` returns `false` for abstract JUnit test methods).
I wonder if the same makes sense for specs2 as well? I could simply remove the run markers from specs2 tests in abstract test classes, it's certainly easier to do... But I wonder if implementing inheritor detection per method would make it more usable.
@ittaiz, WDYT?

**Comment by hmemcpy** [comment]
Ok, so I'll send a PR that prevents specs2 test methods in an abstract class from being able to run (similar to Java).
I'll open another issue that proposes making individual test methods in an abstract class runnable.

**Comment by chaoren** [comment]
>  I could simply remove the run markers from specs2 tests in abstract test classes, it's certainly easier to do... But I wonder if implementing inheritor detection per method would make it more usable.

Abstract test class seems like both necessary and sufficient condition for this to happen. So it should be good enough. Plus it's easy.

> I'll open another issue that proposes making individual test methods in an abstract class runnable.

It looks like the Java methods also don't currently do this. I think there might be a good reason why. @brendandouglas do you know?

**Comment by hmemcpy** [comment]
Ok, I've verified that running abstract specs2 classes does work properly (it offers to select a subclass in case there are more than one).
The only thing that didn't work well was running individual test methods in the abstract class - the PR I sent #186 removes the run marker (but not the click menu).
I'm closing this issue for now, since running the test classes works.
