### ISSUE TITLE
Excluded folders should persist across re-sync

### ISSUE THREAD

**Issue by virusdave** [bazelbuild/intellij#1835]
We use this plugin heavily, and there's a general consensus that the current behavior (resetting the selection of excluded folders during a sync) is the wrong approach, leading unnecessarily to very heavy reindexing.

**Comment by brendandouglas** [comment]
The *.bazelproject file is intended to be the source of truth for the project structure.

To exclude folders in a way which persists across sync (and can be shared between users, if you want), add them to the 'directories' section of the bazelproject file, with a '-' prefix (https://ij.bazel.build/docs/project-views.html#directories).

**Comment by virusdave** [comment]
Thanks for the rapid response!  Unfortunately, this makes a strong assumption that there is a single consistent notion of "what should be excluded" that makes sense for an entire repository and all users of it.  This seems like potentially a too-strong assumption for the plugin to make.

For instance, in a large monorepo with thousands of developers, the frontend folks might not care about the backend code and want to be able to (in persistent fashion) exclude those folders to avoid half-hour-long reindexing.  However, the backend folks would be understandably upset if their code were excluded globally.

**Comment by brendandouglas** [comment]
For per-user settings, just have your users create their own project view file which imports your shared one. Then they can customize it however they want.

Alternatively, create one checked-in, shared .bazelproject file per distinct view of what should be ignored.

Internally we have a large monorepo with thousands of devs, and teams create modular groups shared of .bazelproject files representing different views of their project. You can piece together any set of these for your particular project.

**Comment by Leo7654** [comment]
How about to provide option that can put to 'Project Setting > Modules > Exclude files'.
It will be very helpful.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
