### ISSUE TITLE
Python Unittests error and traceback support is broken.

### ISSUE THREAD

**Issue by crutcher** [bazelbuild/intellij#1839]
Python unittests (successful or failed) produce a stub in the TestResults list which list each test target; but for each test inside the target has the name `<no name>` which contains no content.

This is much less info than the Intellij Python pluggin.

Steps to reproduce:
  1. Clone `rules_python`:
     https://github.com/bazelbuild/rules_python.git

  2. Import the project.

  3. Run the tests in `examples/`

I'm using bazel for a monorepo at McDonald's Tech Labs; so we're able to allocate some time towards helping on this if someone could give us basic pointers of where to start looking.

**Comment by brendandouglas** [comment]
Thanks for letting us know. Likely the format of the python test result XML has changed since we added support for this (a few years ago now). The external Bazel python rules are changed independently to the internal ones we see each day, so regressions like this are unfortunately common.

If you do have some time to look into this that would really help us. The relevant class is PyTestContextProvider, but really if you could paste a sample python test result XML file here that would make this quick and easy to fix.

**Comment by crutcher** [comment]
This is what I've got so far. Still need to find time to spin up on debugging the plugin
```
[rules_python:master/]
$ cat bazel-testlogs/examples/version/version_test/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="examples/version/version_test" tests="1" failures="0" errors="0">
    <testcase name="examples/version/version_test" status="run" duration="0" time="0"></testcase>
      <system-out>
Generated test.log (if the file is not UTF-8, then this may be unreadable):
<![CDATA[exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples/version:version_test
-----------------------------------------------------------------------------
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK]]>
      </system-out>
    </testsuite>
</testsuites>
```

**Comment by crutcher** [comment]
Debug is ALSO broken:
```
/usr/bin/setsid --wait /usr/bin/python3.7 /home/crutcher/.IntelliJIdea2019.3/config/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 38419 --file /home/crutcher/.cache/bazel/_bazel_crutcher/ad9b25b155e5676a6a8a4df5c9b5796f/execroot/rules_python/bazel-out/k8-fastbuild/bin/examples/version/version_test VersionTest.test_version
pydev debugger: process 45978 is connecting

Connected to pydev debugger (build 193.7288.26)
Traceback (most recent call last):
  File "/home/crutcher/.cache/bazel/_bazel_crutcher/ad9b25b155e5676a6a8a4df5c9b5796f/execroot/rules_python/bazel-out/k8-fastbuild/bin/examples/version/version_test.runfiles/rules_python/examples/version/version_test.py", line 15, in <module>
    import pip
  File "/home/crutcher/.cache/bazel/_bazel_crutcher/ad9b25b155e5676a6a8a4df5c9b5796f/execroot/rules_python/bazel-out/k8-fastbuild/bin/examples/version/version_test.runfiles/examples_version_pypi__pip_9_0_3/pip/__init__.py", line 21, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1241, in find_spec
  File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
KeyboardInterrupt

Process finished with exit code 1
```

**Comment by vsbogd** [comment]
I made some quick debugging of the issue and I don't see the problem with the XML itself. It looks like the XML is parsed correctly. But the XML itself doesn't contain enough information. For example it doesn't contain names of the individual tests, but instead contains only test suite name. The similar issue in Bazel repo: https://github.com/bazelbuild/bazel/issues/3413

**Comment by vsbogd** [comment]
Above is true at least for `<no name>` issue. Indeed XML contains result of the test in unstructured form nested in `<system-out>` tag and plugin doesn't show it.

**Comment by vsbogd** [comment]
@brendandouglas , could you please look if the above comments make sense?

**Comment by crutcher-dunnavant-techlabs** [comment]
I believe that the second issue is that python3.7 debugging is broken, full stop; due to a change in the default close-on-exec behavior of python sockets in 3.7

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
