### ISSUE TITLE
Permit include directories inside exclude directories.

### ISSUE THREAD

**Issue by crutcher** [bazelbuild/intellij#1842]
In order to work around the lack of python package registration; I'd really like to be able to say this, in order to get proper python indexing.

```
directories:
  .
  -src/{python_tree}
  src/{python_tree}/python
```

but I can't; because:
```
Error:src/{python_tree}/python is included, but that contradicts src/{python_tree} which was excluded
```

**Comment by iamricard** [comment]
Hi @mai93 👋🏼  we're also interested in this feature. Would you be to a PR adding this?

**Comment by iamricard** [comment]
@mai93 👋🏼 hi again, still wondering if you'd be open to a contribution for this

**Comment by iamricard** [comment]
👋🏼 another attempt at offering to work on this, or #1745 which would also solve our issue.

**Comment by mai93** [comment]
Hello @iamricard, sorry for the late response, if you're still interested we can review a PR fixing this.

**Comment by iamricard** [comment]
Oh yay! Ok I'm going to take a stab at it. Is there anything that jumps to mind that immediately sounds like a bad approach when solving ths?
