### ISSUE TITLE
Runner_deploy-ijar.jar leaks into external libraries

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/intellij#1844]
The bazel runner's deploy jar ends up in the external libraries list in the IDE and, because its dependencies are not repackaged, it ends up being a target for click-through type navigation in the IDE. This means, for example, that clicking on ImmutableList ends up going to that jar instead of guava. 

Do _deploy.jar or _deploy-ijar.jar make any sense to leak into the External Libraries set? Are they needed for test running from the IDE? If so, can they somehow be deprioritized so that such cross-linking doesn't mis-target them?

**Comment by brendandouglas** [comment]
This definitely isn't intended. It's likely a bazel-side bug -- these jars shouldn't accessible via JavaInfo.

When we have time, we'll take a look at exactly how these jars are being picked up by the plugin, and either fix it plugin-side or file a bug with bazel

**Comment by jimmyzzxhlh** [comment]
+1. Just want to illustrate how this problem can be annoying.
The other `ImmutableList` class does contain the source code so every time I have to do a switch to view the source code. 

![image](https://user-images.githubusercontent.com/11505867/95661400-e6257300-0ae3-11eb-8cdd-13cda8319410.png)

**Comment by rdesgroppes** [comment]
Adding this to `.bazelrc` already helps:
```
build --explicit_java_test_deps
```
How about making it the default?
