### ISSUE TITLE
Selecting a subclass for an abstract test class incorrectly sets the run configuration title  

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#185]
When running an abstract test class, it will prompt to choose a subclass implementation. After selecting one (e.g. `MySubclassTest`), the title of the run configuration should be updated to show just the name of the subclass, but currently will show: "Bazel test Choose subclass for MySubclassTest".
This happens in both Java and Scala (specs2) tests.

**Comment by brendandouglas** [comment]
Thanks, fixed upstream.
