### ISSUE TITLE
NPE when using CLion to debug with LLDB (macOS)

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/intellij#1868]
A [recent change](https://github.com/bazelbuild/intellij/commit/c7533ce471a0453f8b65609dd0a84f421ecd7446) broke the ability to use LLDB for debugging on macOS. This renders it unusable with CLion 2019.3.6 and plugin version 2020.04.13.0.0 on macOS 10.14.6. The Jetbrains team are looking at resolving the issue of the NPE on there side ([see comment](https://github.com/bazelbuild/intellij/commit/c7533ce471a0453f8b65609dd0a84f421ecd7446#r39159648)). However, the change in the plugin has caused a regression so it would be good to undo that until its fixed in CLion.

**Comment by kayasoze** [comment]
This is the same issue as #1736.

**Comment by mai93** [comment]
@tpasternak is this also fixed with https://github.com/bazelbuild/intellij/pull/4003?
