### ISSUE TITLE
Unable to create run configuration if multiple Scala test classes are defined in a single file

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#188]
Seems that having more than one (specs2) test class, e.g.
```
class MyTest extends SpecWithJUnit
class MyOtherTest extends SpecWithJUnit
```
makes run configuration creation unavailable.

This also happens if there's another top-level "class-like" element, like a Scala trait:
```
class MyTest extends SpecWithJUnit // run configuration creation is unavailable here, and the gutter icon says "Nothing here"
trait Foo
```

The cause seems to be a call to `JUnitConfigurationUtil.isMultipleElementsSelected(context)` from `BlazeJavaTestClassConfigurationProducer`, which is responsible for the test class-level run configurations.

Perhaps this can be split into a Scala-specific producer.

**Comment by hmemcpy** [comment]
@chaoren I would like to handle this, because this is quite common in our codebase. Do you have any suggestions?

**Comment by chaoren** [comment]
`JUnitConfigurationUtil.isMultipleElementsSelected(context)` returning true when `context.containsMultipleSelection()` is false seems... wrong.

**Comment by chaoren** [comment]
I'm not sure if `JUnitConfigurationUtil.isMultipleElementsSelected(context)`'s behavior here is correct, but we'll have to ask Brendan when he gets back from vacation to make sure. If it is correct, we should consider adding an extension point (similar to `JavaTestCaseIdentifier`) instead of splitting a new producer.

**Comment by hmemcpy** [comment]
Hey, this issue is fast becoming quite painful for us, we have many test files with multiple top-level declarations (SUTs, test helpers, etc.)

Any chance you could look at this? I'd be happy to send a PR, if you could hint me where to look :)

**Comment by brendandouglas** [comment]
It is a bug in JUnitConfigurationUtil, I'll fix it up. We originally based that class on PatternConfigurationProducer. That logic has since changed, and now lives in AbstractJavaTestConfigurationProducer.

**Comment by brendandouglas** [comment]
Alright, fixed for JUnit tests upstream (we just call `AbstractJavaTestConfigurationProducer#isMultipleElements` directly now). I haven't tested whether that fixes the scala issue, but if you've only selected one element, and it's actually calling `JUnitConfigurationUtil#isMultipleElementsSelected`, it should be fixed

**Comment by hmemcpy** [comment]
Awesome, thanks very much!

**Comment by hmemcpy** [comment]
Hey @brendandouglas, was this fix released?

**Comment by brendandouglas** [comment]
Closing for now -- please let us know if it's still happening.
