### ISSUE TITLE
Performance problem looking up line markers for specs2 tests

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#189]
Getting a lot of the following messages in the idea.log:
```
WARN - eInsight.daemon.LineMarkerInfo - Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: InfixExpression (class org.jetbrains.plugins.scala.lang.psi.impl.expr.ScInfixExprImpl) instead. First child: Literal (class org.jetbrains.plugins.scala.lang.psi.impl.base.ScLiteralImpl)
```
It is also visible when opening the file -- the run marker for the class is visible immediately, and ones per individual tests appear later.
The culprit is here: https://github.com/bazelbuild/intellij/blob/master/scala/src/com/google/idea/blaze/scala/run/producers/BlazeScalaTestRunLineMarkerContributor.java#L68

Perhaps making a lookup for a specs2 expression from a literal is better?

**Comment by chaoren** [comment]
First child would be the string, but I think that could be an arbitrary string expression. Probably better if we use the operator (should, in, etc), and get the parent of that. Though, I don't know off hand what leaf element that would be.

**Comment by chaoren** [comment]
But the marker will look like this:

```
  "foo"
()  should
      "do bar"
()      in
          { ... }
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
