### ISSUE TITLE
3rdparty is an invalid package name

### ISSUE THREAD

**Issue by mightyguava** [bazelbuild/intellij#19]
Our 3rdparty libraries are located under `//3rparty/java/com/...` and `//3rdparty/:*` (for external jars) rather than Bazel's standard `third_party`. The Intellij plugin doesn't seem to be happy with that and spits out an error from https://github.com/bazelbuild/intellij/blob/13456c22d4225ebb60f67a7e5980e9e72102030e/blaze-base/src/com/google/idea/blaze/base/model/primitives/Label.java#L131

I'm curious why the plugin considers it an invalid package path? The 3rdparty isn't actually part of the java package name.

**Comment by brendandouglas** [comment]
Hi!

The Bazel docs claim package names must start with a lower-case ASCII letter (a–z) (https://www.bazel.io/versions/master/docs/build-ref.html#package-names-package-name), but that certainly doesn't seem to be enforced.

I'll look into updating both those docs and the behavior of this plugin -- thanks!

**Comment by brendandouglas** [comment]
Fixed in the latest release.

**Comment by mightyguava** [comment]
Yay!
