### ISSUE TITLE
"Test framework quit unexpectedly" in IDEA 2017.3

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#190]
Getting this error in the test runner since upgrading to 2017.3, in both the release version of the plugin (2017.11.20.0.4) and when building from source.

I don't see any errors/exceptions in the log file :(

**Comment by chaoren** [comment]
Did you build the plugin against 2017.3?

**Comment by chaoren** [comment]
Weird. I'm getting this in 2017.2 too, and not just for scala tests.

**Comment by chaoren** [comment]
Not scala related. It's due to a recent change we made to the test reporter. I filed a bug internally, so I'll be closing this one.

**Comment by petroseskinder** [comment]
@chaoren: this issue has been closed. However, we (Two Sigma) are still facing this issue with intellij-2017.3

All of our java tests result in it stating "Test Framework quit unexpectedly"

**Comment by chaoren** [comment]
It should be. What version of the plugin are you running?

**Comment by petroseskinder** [comment]
We are running the November 20 release, i.e. "Version: 2017.11.20.0.4"
I imagine the issue was resolved in a later version. Is that correct?

**Comment by petroseskinder** [comment]
> Yes. November 20 was before this issue was even filed.
 
😥 you're right. Thank you for the help.

**Comment by petroseskinder** [comment]
@chaoren This less an issue and more of a question. The [plugin's jetbrains page](https://plugins.jetbrains.com/plugin/8609-bazel) site displays the compatible Intellij builds for the last 10 releases. Is there anywhere I can go to determine compatibility of older releases?

**Comment by brendandouglas** [comment]
We recently removed a lot of old plugin releases, as they were listed as compatible with all future IDEs, causing issues such as this one.

If you're on an older release, you should absolutely upgrade.

**Comment by petroseskinder** [comment]
> We recently removed a lot of old plugin releases, as they were listed as compatible with all future IDEs, causing issues such as this one.

I see. That makes sense. Thank you both.
