### ISSUE TITLE
sync project fails with analysistest 

### ISSUE THREAD

**Issue by cristifalcas** [bazelbuild/intellij#1900]
Add the files from https://docs.bazel.build/versions/master/skylark/testing.html to a folder inside the project.

Sync the project with bazel.

Exception thrown:

```
ERROR: /home/cristifalcas/project/test/BUILD.bazel:6:19: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on provider_contents_test rule //test:provider_contents_test: 
Traceback (most recent call last):
	File "/home/cristifalcas/project/test/BUILD.bazel", line 6
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/home/cristifalcas/.cache/bazel/_bazel_cristifalcas/6b39ea2a9cf0428af321c3c86d3145b0/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(<3 more arguments>)
	File "/home/cristifalcas/.cache/bazel/_bazel_cristifalcas/6b39ea2a9cf0428af321c3c86d3145b0/external/intellij_aspect/intellij_info_impl.bzl", line 1030, in intellij_info_aspect_impl
		ctx.actions.write(ide_info_file, <1 more arguments>)
implementation function of a rule with analysis_test=true may not register actions. Analysis test rules may only return success/failure information via AnalysisTestResultInfo.
```
Command executed by IDE: `$ bazel build --tool_tag=ijwb:IDEA:community --keep_going --build_event_binary_file=/tmp/q --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --remote_download_outputs=all --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/cristifalcas/.IdeaIC2019.3/config/plugins/ijwb/aspect --output_groups=intellij-info-generic,intellij-info-java,intellij-info-py,intellij-resolve-java,intellij-resolve-py -- //test/...`

IntelliJ version used: 2019.3.5, latest bazel plugin.

**Comment by vemana** [comment]
Does the ["no-ide" tag](https://github.com/bazelbuild/intellij/blob/master/aspect/intellij_info_impl.bzl#L925) help?
