### ISSUE TITLE
per-project bazel binary/wrapper path

### ISSUE THREAD

**Issue by dsilvasc** [bazelbuild/intellij#1916]
The bazel binary path right now is configured globally per user.

Since different projects can have different needs encoded as their own bazel wrappers, can this be made per project and saved in the project's `.idea` directory like [what intellij does for gradle projects](https://www.jetbrains.com/help/idea/gradle.html#gradle_version_install)?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
