### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by yebrahim** [bazelbuild/intellij#1920]
I'm getting this error after I tried out Intellij Ultimate then switched to CE:
~~~
Error:Go is no longer supported by the Bazel plugin with IntelliJ Community Edition.
Please install Ultimate Edition and upgrade to the JetBrains Go plugin
~~~

Am I missing something? Should the Bazel plugin work with CE and Golang?

**Comment by brendandouglas** [comment]
Go support is built on top of the JetBrains Go plugin (
https://plugins.jetbrains.com/plugin/9568-go), which is only supported in
Goland and IntelliJ UE.

**Comment by yebrahim** [comment]
I see, thanks. The "no longer" part is misleading then?

Closing.

**Comment by brendandouglas** [comment]
We used to support the open source Go plugin, which worked across all IDEs
(and which the new Go plugin was built from), hence the 'no longer'.

The new plugin is much better though, and gets regular updates and
improvements, so we now use that instead.

**Comment by yebrahim** [comment]
Thanks for the update. IMO it goes against Bazel's open source philosophy. AFAICS Intellij UE is the only editor right now with Bazel + Golang support. :(

**Comment by nfisher** [comment]
Hi @yebrahim it sounds like a limitation imposed by JetBrains/IntelliJ not Bazel. They could allow Go targets to be executed but the overall utility would be limited to what the IDE provides more broadly.
