### ISSUE TITLE
Passing Environement Variables while executing IntelliJ Bazel command

### ISSUE THREAD

**Issue by scorsi** [bazelbuild/intellij#1926]
Hello 👋 

To make it short, I don't find if it's possible so say my if I'm wrong, it's impossible to pass some env var.
While using the CLI I do : `MY_VAR=MY_VAL bazel run //:bin` for example.
How could I achieve that from the IntelliJ runner ?

Maybe it can be achieve with the bazel flags ?

Thanks,

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
