### ISSUE TITLE
c++ language level?

### ISSUE THREAD

**Issue by zhuker** [bazelbuild/intellij#1927]
i started getting these weird warnings recently
is there a setting somewhere for c++ language level?
![image](https://user-images.githubusercontent.com/4367682/85626481-f8a59a80-b621-11ea-8afa-7c89e89c4421.png)

**Comment by zhuker** [comment]
https://stackoverflow.com/questions/55088151/how-to-set-c-standard-in-clion-bazel-project
add this to your `.bazelrc`
```
build --cxxopt="--std=c++1z"
```

**Comment by ctrysbita** [comment]
@zhuker Does this work while using MSVC? Maybe it should be something like `/std:c++20` ?
