### ISSUE TITLE
cannot found bazel

### ISSUE THREAD

**Issue by LMXKO** [bazelbuild/intellij#1935]
#### Description of the issue. Please be specific.
Cannot run program "bazel"
#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
1、installed bazel
2、import a bazel project（choose Generate from NUILD file）
3、Cannot run program "bazel"
#### Version information
IdeaCommunity: 2019.2.3
Platform: Mac OS X 10.15.5
Bazel plugin: 2019.11.14.0.1

**Comment by subotic** [comment]
Did you try to set the Bazel binary location Bazel plugin settings? IntelliJ Preferences -> Other Settings -> Bazel Settings -> Bazel binary location.

**Comment by mai93** [comment]
Hello @LMXKO, are you still seeing this issue after applying @subotic suggestion or with new versions of the plugin?

**Comment by mai93** [comment]
I'll close the issue. If you still can reproduce it, please reopen.
