### ISSUE TITLE
Can't Instal Bazel Plugin from Disk

### ISSUE THREAD

**Issue by jikookforever** [bazelbuild/intellij#1947]
I've tried the last 3 versions and one from 2019, but it still gives me "Plugin 'Bazel' is incompatible with this installation".
Version: CLion 2020.1.2

**Comment by davidgengenbach** [comment]
The plugin is only compatible with an outdated version of CLion,  `2019.3.4` to  `2019.3.6`
(as of 05.07.2020)

That is also the reason why the plugin can not be found on the Plugin Marketplace

**Comment by sravanreddy001** [comment]
Is this going to be supported?

**Comment by alice-ks** [comment]
Plugin versions 2020.09.16.0.6+ are compatible with CLion 2020.1. Hence, I'm closing this issue now. Please refer to other existing tracking issues if you're interested in support for newer CLion versions.
