### ISSUE TITLE
Request: automatically format *.bzl files on save

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/intellij#195]
It'd be nice if there the Bazel plugin had an option to automatically format `bzl` files on save.  When using the open source Bazel, you tend to accumulate many `bzl` files, mostly related to `third_party`.

**Comment by jschaf** [comment]
I found a workaround in the meantime:

1. Install [FileWatcher](https://plugins.jetbrains.com/plugin/7177-file-watchers)
2. Setup a rule like so, (you probably want to disable "Auto-save edited files", it's very aggressive.

![intellij](https://user-images.githubusercontent.com/22385/34459161-438b59e6-ed9c-11e7-9290-f84dfd9131ca.png)

**Comment by brendandouglas** [comment]
The bazel team is working on a Skylark-specific linter/formatter (separate to buildifier for BUILD files). Once that's out, we'll look at auto-formatting .bzl files on save.

**Comment by RNabel** [comment]
According to the `buildifier` codebase, this feature seems to be present - and it looks like the Bazel plugin has started linting my `.bzl` files. Has this been added and can this issue therefore be closed?

**Comment by brendandouglas** [comment]
Thanks, it is fixed now, closing.
