### ISSUE TITLE
Unexpected collapsing of folders in IntelliJ UI on import

### ISSUE THREAD

**Issue by roblg** [bazelbuild/intellij#196]
Possible bug: We're seeing a strange/unhelpful collapsing of filesystem paths in the IntelliJ UI when importing bazel projects. Our projects have a folder structure on disk left over from maven:

```
foo/
  BUILD
  src/
    main/
      java/
    test/
      java/
```

Ideally, we'd like to see this folder structure mirrored in IntelliJ; however, the actual structure we get in the UI is:

```
foo/
  BUILD
  src/
    java/
    java/
```

Our `foo/BUILD` file has:

```
java_library(
  name='lib',
  srcs = glob(['src/main/java/**/*.java']),
  # snip
)

java_test(
    name = 'tests',
    srcs = glob(['src/test/java/**/*.java']),
    # snip
)
```

We also see several other flavors of this collapsing in our codebase, depending on whether, e.g. `src/main/resources` exists as a sibling to `src/main/java`.

**Comment by brendandouglas** [comment]
Thanks for letting us know. We'll fix this up, but in the meantime you can work around it by deselecting 'Hide empty middle packages' in the view options.

**Comment by brendandouglas** [comment]
This appears to be an upstream bug -- if you load the same project with the Bazel plugin disabled (after initially importing it with the Bazel plugin), you'll see the same behavior when 'Hide empty middle packages' is checked.

Now, we already override portions of the project view, so we could override yet more functionality to work around this bug, but I'd prefer to limit the amount of custom project view code -- the upstream project view code is brittle, so it's best to touch it as little as possible.
