### ISSUE TITLE
[Feature request] Support Wildcard Match for `import` in project view file 

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/intellij#1967]
**Background**
Currently bazel project view doesn't support wildcard import like `import ide/custom/*.bazelproject`. We have to specify the full name of the bazelproject file to make it "importable". 
A wild card match could be helpful in the case when:
* we want to Import all project view files under a parent folder
* teams/developers have their customized project view extensions. 

For example, for every team member, by default we are using `main.bazelproject` as the project view.
```
# main.bazelproject
import custom/*.bazelproject

targets:
  #  Put all shared common targets here
  //components/common:core

# other shared configs
...
```
Then under `custom/` folder, each developer could create their own `custom.bazelproject` file to extend the main configuration. For example, they can add extra test targets only used by their feature module. 

```
# custom/mylocal.bazelproject
targets:
  #  Put all shared common targets here
  //feature/myfeature:test

# other customized configs
...
```

We can add `custom/*` into git ignore list so that those `bazelproject` files is locally configurable. Meanwhile, every developer could share the same `main.bazelproject` as project configuration.

Let me know you thoughts. Thanks!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
