### ISSUE TITLE
No autocomplete or debugging on targets using custom rules

### ISSUE THREAD

**Issue by paymog** [bazelbuild/intellij#1968]
#### Description of the issue. Please be specific.
I'm trying to run and debug bazel targets in my workspace which use custom rules also defined in my workspace. I can execute these targets manually from the command line and can hardcode them when setting up a run configuration, but I don't get autocomplete when trying to find the target during configuration editing.

![image](https://user-images.githubusercontent.com/1986950/87694263-f71c4d80-c75b-11ea-9515-5fee326e01b2.png)

Note in this screenshot how I've hardcoded `//helm/api:staging` and that it doesn't show up in the autocomplete list when adding a second target. I can run this target, but the UI doesn't let me debug it which I guess is part of the same problem.

![image](https://user-images.githubusercontent.com/1986950/87694469-3fd40680-c75c-11ea-97d9-1a8e269e2c93.png)

This target uses a custom rule defined in a `helm.bzl` file located in the same workspace. Looking through the docs, it seems like the bazel plugin [ignores some rules](https://ij.bazel.build/docs/project-views.html#derive_targets_from_directories) which might contribute to this.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

I'm still working on a simple repro and will update this question once I have it figured out.

#### Version information
GoLand: 2020.1.4
Platform: Mac OS X 10.15.5
Bazel plugin: 2020.06.25.0.3
Bazel: 2.2.0

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
