### ISSUE TITLE
No `src` nor `test` subdirectories in Project pane

### ISSUE THREAD

**Issue by DimaLiah** [bazelbuild/intellij#197]
![screen shot 2018-01-03 at 10 51 48](https://user-images.githubusercontent.com/29011806/34517375-6b88fb3a-f083-11e7-9324-8197a2dad25d.png)

No `src` nor `test` subdirectories in Project pane, though it exist definitely in the file system.

**Comment by ajrepp** [comment]
@DimaLiah is this possibly a duplicate of #196?

**Comment by brendandouglas** [comment]
It is a dupe, thanks. Closing in favor of #196
