### ISSUE TITLE
Incompitable with CLion 2020+

### ISSUE THREAD

**Issue by stevenleeS0ht** [bazelbuild/intellij#1971]
Request to add support for CLion 2020+

**Comment by stevenleeS0ht** [comment]
@bazelbuild-intellij , @brendandouglas  what are your plans?

**Comment by bigkraig** [comment]
@bazelbuild-intellij , @brendandouglas bump

**Comment by brendandouglas** [comment]
We're working on 2020.1 support currently. I'd expect it to be ready for the release after next (in ~3 weeks). The

**Comment by federicohml** [comment]
@brendandouglas any way I could help? I would like to have the plug in for my workflow.

**Comment by Elentary** [comment]
> We're working on 2020.1 support currently. I'd expect it to be ready for the release after next (in ~3 weeks). The

Can you give some updates on that ?

**Comment by brendandouglas** [comment]
We're moving the beta branch to 2020.1 in the current release, which should be uploaded to GitHub 2-3 weeks from now.

Though if you want something now, you should be able to build the plugin from source now, using `--define=ij_product=clion-beta`

**Comment by brendandouglas** [comment]
The full build invocation will be `bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-beta`

**Comment by mai93** [comment]
Closing as the plugin is now compatible with the latest CLion version.
