### ISSUE TITLE
No way to create a folder

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#198]
I have two options:
* Create a bazel package, but it creates a BUILD file there
* Create a java package, but in this case, the name is limited

Nice to have a create directory action.

**Comment by ittaiz** [comment]
+1
Also when you create a bazel package you have to use one of the hard coded
rule names

**Comment by plumpy** [comment]
FWIW, "create package" will let you use any characters you want, it just presents you with a warning if you use something that isn't a normal package name. You can still click "OK" to create the directory.

This is consistent with a Java source directory in a normal IntelliJ project, which also removes the "create directory" menu item...

**Comment by solomatov** [comment]
@plumpy BTW, what are the plans for the release of the next version of the plugin and start of accepting contributions to it?

**Comment by solomatov** [comment]
@plumpy Also, is there any way not to make . a source directory?

**Comment by brendandouglas** [comment]
A create-directory action sounds like a generally-useful feature the IDE itself should provide, and not really the responsibility of a plugin.

Could you file a feature request with JetBrains instead?

**Comment by ittaiz** [comment]
but this exists when you have a maven based intellij project.
I think this is related to what this plugin does

**Comment by solomatov** [comment]
The problem is that the plugin marks the root directory fo the workspace as a source directory. Use shouldn't do this.
