### ISSUE TITLE
Support option to put project file into the workspace

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#199]
Currently, there's no way to put a project inside of a workspace. Our project is not huge and there it's a good option. We want to share different settings across the project: coding style, run configurations, inspections profiles, etc. To do so, we need to commit .idea folder, but there's no way to do it inside of the workspace.

**Comment by chaoren** [comment]
Dupe of https://github.com/bazelbuild/intellij/issues/150. Working on it.
