### ISSUE TITLE
The IntelliJ Bazel plugin incorrectly identifies source roots if a JPMS module-info.java manifest is declared

### ISSUE THREAD

**Issue by MihaiBojin** [bazelbuild/intellij#1992]
# Reproduction

- `git clone https://github.com/MihaiBojin/java-bazel-template`
- Import in IntelliJ (either keep the included `.ijwb` or start from scratch)
- Sync the project (you will see `src/main/java` correctly identified as a source root
- Create `src/main/java/module-info.java` and define a module, e.g.:
  ```
  module com {
    requires java.base;
    requires java.logging;
  }
```
- Sync the working set
- Notice how `src/main/java/com` becomes the source root

# Impact
This bug makes it very hard to work with JPMS in java projects, since after each bazel sync, the source roots need to be amended.

Bazel plugin version: 2020.07.13.0.2

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
