### ISSUE TITLE
The IntelliJ Bazel plugin does not mark resource and test resource directories

### ISSUE THREAD

**Issue by MihaiBojin** [bazelbuild/intellij#1993]
I could not find a way to declare resources in the project view. After a sync, all previously marked resource directories are cleared and have to be marked again.
This is very cumbersome and results in a lot of time waste.

Bazel plugin version: 2020.07.13.0.2

**Comment by sgowroji** [comment]
Hello @MihaiBojin, Are you still seeing the issue with latest bazel plugin versions. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
