### ISSUE TITLE
Including node_modules folder in .bazelignore with the intellij plugin breaks intellisense for JS, TS, Angular etc projects

### ISSUE THREAD

**Issue by mattem** [bazelbuild/intellij#1994]
It's recommended to list `node_modules` in the `.bazelignore` file, due to making `bazel build //…` very slow (large number of files) or NPM packages that include BUILD or bzl files causing issues.

Since #1194, the plugin has added all items listed in the `.bazelignore` file as excluded in IJ, however this breaks intellisense for Javascript, Typescript and such other projects (eg Angular templates) as IJ doesn't index the node_modules folder.

A quick patch to get us working again internally was to ignore lines in the `.bazelignore` file that contained `node_modules`, to allow IJ to handle these as library roots (if this approach is acceptable, then I'll open a PR for the change).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
