### ISSUE TITLE
2020.2 support

### ISSUE THREAD

**Issue by jvolkman** [bazelbuild/intellij#1998]
Tracking issue for IntelliJ 2020.2, which was [released](https://blog.jetbrains.com/idea/2020/07/intellij-idea-2020-2-is-released/) July 28.

**Comment by jvolkman** [comment]
@unoexperto posted a diff for an earlier EAP release in [this comment](https://github.com/bazelbuild/intellij/issues/1567#issuecomment-653918548).

**Comment by eikemeier** [comment]
Also, [ping JetBrains](https://youtrack.jetbrains.com/issue/CPP-2782) (Vote for the issue by clicking :+1: at the top right)

**Comment by nicknezis** [comment]
Will this repo be updated to support 2020.2? Or is there some kind of blocker?

**Comment by unoexperto** [comment]
@nicknezis I periodically rebuild bazel plugin from master branch for my team. If you want you can try my binary http://u.pc.cd/Lrg7 (no guarantees).

**Comment by nicknezis** [comment]
Thank you. It worked. Do you have a documented process that I can follow? It seems this plugin always lags behind, but I'm not sure why.

**Comment by unoexperto** [comment]
@nicknezis Nothing more than I described in https://github.com/bazelbuild/intellij/issues/1567#issuecomment-653918548. If you guys prefer I can fork official branch so you can build the binary yourself.

**Comment by nicknezis** [comment]
Thanks. I'm happy using your binary. It worked so thanks again. I was partly curious because if I'm building it anyway I might add some Python closures that aren't included in the official build. We use `pex_binary` which doesn't get picked up like `py_binary`. Thanks for the help and info!

**Comment by jitsni** [comment]
I am using the binary, but it doesn't seem resolve external java lib dependencies.

**Comment by unoexperto** [comment]
@jitsni Unfortunately your problem is not specific to my binary. Bazel plugin is notorious for randomly failing which drives me (and my 100 engineers team) nuts. So I can suggest making sure that `fetch_sources` flag is set to `True`. And if it was then I can only suggest trying to re-sync the project from scratch multiple times. Sometimes it takes me entire day to "fix" it.

**Comment by mistic** [comment]
@chaoren could we get some attention here please?

**Comment by zellyn** [comment]
@brendandouglas do y'all have a schedule for releases? No pressure, since I'm sure this is all volunteer work! I'm trying to decide whether to attempt an IntelliJ downgrade, or wait for a release of the Bazel plugin. Thanks!

**Comment by kusold** [comment]
@zellyn regarding downgrades, the Jetbrains Toolbox makes this very easy to do:
<img width="447" alt="Screen Shot 2020-08-24 at 2 59 39 PM" src="https://user-images.githubusercontent.com/509966/91096001-87cb3080-e61a-11ea-8907-6d64aaad4e47.png">

Also, I would suggest pinning your IDE version so that future updates don't break your Bazel usage.
<img width="442" alt="Screen Shot 2020-08-24 at 2 59 56 PM" src="https://user-images.githubusercontent.com/509966/91096007-8b5eb780-e61a-11ea-974e-46ee0d64492e.png">

**Comment by brendandouglas** [comment]
@zellyn, we don't have a schedule for releases. We try to add support for new releases soon after they stabilize, but we're focused on other things (remote development support for internal users) at the moment, so it will be delayed, likely until late September / early October.

**Comment by zellyn** [comment]
@kusold thanks for that tip - I'll give it a try.
@brendandouglas thank you for the update. Clear expectations are almost as good as a recent release :-)

**Comment by ittaiz** [comment]
@brendandouglas when you say "remove development support" you mean something like what VSCode offers (GUI on my machine but brains, sources, bazel invocations on a remote machine) or something like better integration with remote execution?
Asking out of interest since "full" remote dev for Bazel IntelliJ sounds like a dream :)

**Comment by brendandouglas** [comment]
Not full remote development support, but support for bazel invocations on a remote machine. It's internal only and mac only though, and not a great experience.

**Comment by ittaiz** [comment]
Got you.
Thanks for the clarification.
Good luck!

**Comment by crutcher-dunnavant-techlabs** [comment]
My desire for 2020.2 support is tied to our team's desire to begin using the new remote pair-programming tooling:
https://www.jetbrains.com/help/idea/code-with-me.html

**Comment by Leo7654** [comment]
[ijwb_bazel.zip](https://github.com/bazelbuild/intellij/files/5369450/ijwb_bazel.zip)
I have built a custom build myself. I removed scala support. It would not work properly, but I a, uploading this, in case there's somebody really want to use this.

**Comment by mistic** [comment]
@brendandouglas do we have any news here?

**Comment by brendandouglas** [comment]
We're working on 2020.2 support currently. It's not the top priority, so may be a few more weeks before it's completed.

**Comment by aristofun** [comment]
thanks in advance, waiting for it so much

**Comment by tpasternak** [comment]
@brendandouglas thank you, too! Would you accept any contributions in this area? I think I could try to work on it a bit

**Comment by illera88** [comment]
It seems that someone already did it: https://github.com/bazelbuild/intellij/issues/2185

Can you merge so it can work?

**Comment by sambercovici** [comment]
see: #2202

**Comment by alice-ks** [comment]
Sorry that this took a bit longer. The source code should now be compatible with IntelliJ 2020.2. So, you can try building from the tip of master if you don't want to wait for the official release.

For CLion 2020.2, we'll still need some adjustments. Thanks for the pull requests in that area.

**Comment by alice-ks** [comment]
We just pushed a new release of the IntelliJ plugin to the plugin repository. This release is compatible with 2020.2.

**Comment by kusold** [comment]
What plugin version is compatible with 2020.2? `2020.11.17.0.2 Dec 11, 2020` is the latest release that I'm finding, but the change notes (* Bug fixes and internal cleanup.) don't indicate if this is the 2020.2 compatible version or not.

**Comment by gzurowski** [comment]
> What plugin version is compatible with 2020.2? `2020.11.17.0.2 Dec 11, 2020` is the latest release that I'm finding, but the change notes (* Bug fixes and internal cleanup.) don't indicate if this is the 2020.2 compatible version or not.

You need `2020.12.01.0.1` for 2020.2. You can find an overview of plugin versions and their IDE compatibility here: https://plugins.jetbrains.com/plugin/8609-bazel/versions.

**Comment by jvolkman** [comment]
Closing since 2020.2 has been supported for a while now.
