### ISSUE TITLE
Allow importing a project using multiple BUILD files

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#2]
Given a large codebase I might want to import only a subset of it into intellij. That is currently supported with the ability to import from a BUILD file IIUC.
I want to suggest allowing to import using multiple BUILD files.
The use-case is working on a change in a core-library and on one leaf service to get feedback on how the API looks or on an edge case in it. I can choose both BUILD files and load the targets from them.

**Comment by tomlu** [comment]
This semi-advanced use case is covered by manually adding targets and directories to your project view. This is a case where we feel that the sooner you get familiar with the project view format the better. This is such a central file to the bazel plugin experience, and we think the sooner you graduate from using UI to manipulating this file directly the better.

In this regard it would of course help a lot to publish our documentation on the project view! Coming Real Soon Now (TM).

**Comment by ittaiz** [comment]
Fair enough. As with the previous issue I think this helps onboarding of
people who are accustomed to a simpler (and agreed probably less scalable)
flow but it's legitimate to decide this ease won't be beneficial in the
long term

**Comment by tomlu** [comment]
Sure! Your other comments are really good and we may need to rethink the brand new user flow (eg. "Import from BUILD file") with some nicer UI. So far we have been focusing on internal users with large projects and complicated needs.

**Comment by ittaiz** [comment]
Understood.
Thank you for your hard work :)

**Comment by ittaiz** [comment]
Btw, one last thought (which might already be implemented I'm AFK) but if the project view screen supports auto complete of existing targets (I think currently it just uses directories which might or might not be packages) that could also help

**Comment by brendandouglas** [comment]
Auto-complete of build targets in project view files isn't yet supported during project import, though it is supported when you're editing a project view file after the initial import.

**Comment by ittaiz** [comment]
Just now got around to testing it and indeed you're correct, thanks!
What confused me is that the auto complete first uses the directories which can be not packages and only if you "stop" at a directory which is also a packages then typing : and ctrl+space will display the existing targets. maybe worth documenting.
