### ISSUE TITLE
Intellij sync fails when importing Bazel

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/intellij#20]
Reposting from  https://github.com/bazelbuild/bazel/issues/1777

**Comment by dslomov** [comment]
@abergmeier

**Comment by SalzzZ** [comment]
It might be the same as #18

**Comment by abergmeier** [comment]
Seems like it - not sure then why not everyone is experiencing it.

**Comment by brendandouglas** [comment]
Closing as a dupe of [#18 ](https://github.com/bazelbuild/intellij/issues/18).
