### ISSUE TITLE
Need a way to share project settings

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#201]
In our project we have a lot of settings: coding style, inspection settings, etc. We need a way to share them among our team members. Currently, due to the fact that bazel plugin requires workspace directory be separate from the main directory, it's not possible. Nice to have a way to work with this.

**Comment by brendandouglas** [comment]
We're intending to allow the .idea directory to be within the bazel workspace (#150), which should provide a workaround for this issue.
