### ISSUE TITLE
IDE picks up wrong target when it's marked as manual

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/intellij#2010]
IntelliJ CE: 2020.1.4
Bazel plugin: 2020.07.13.0.2
Bazel version: 3.4.1
Sample repo: https://github.com/MikhailTymchukFT/bazel-plugin-bug

There are 2 java classes in a folder `target`: `A.java` and `B.java`.
BUILD file:
```
load("@rules_java//java:defs.bzl", "java_binary", "java_library")


java_library(
    name = "main",
    srcs = glob(["target/**/*.java"])
)

java_binary(
    name = "A",
    main_class = "example.A",
    tags = ["manual"],
    runtime_deps = [
        ":main"
    ],
)

java_binary(
    name = "B",
    main_class = "example.B",
    runtime_deps = [
        ":main"
    ],
)
```

Context menu shows wrong target when trying to run class A:
<img width="691" alt="Screenshot 2020-07-31 at 23 36 53" src="https://user-images.githubusercontent.com/62020066/89075399-cc9ad900-d386-11ea-98f3-034297663c07.png">

```
/usr/local/bin/bazel run --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no -- //:B
Loading: 
Loading: 0 packages loaded
Analyzing: target //:B (0 packages loaded, 0 targets configured)
Analyzing: target //:B (0 packages loaded, 0 targets configured)
Analyzing: target //:B (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:B (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 6] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:B up-to-date:
  bazel-bin/B.jar
  bazel-bin/B
INFO: Elapsed time: 5.142s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/B
INFO: Build completed successfully, 1 total action
B
```

When `tag = ["manual"]` is absent, everyting works correctly.
1. Why IDE picks up wrong target?
2. Is there a workaround for this case?

**Comment by brendandouglas** [comment]
The plugin logic to find a matching target relies on the target having been synced. If it's tagged as 'manual', then it's likely not in your .bazelproject 'targets' (manual targets are skipped when expanding wildcard target patterns).

You can workaround this by explicitly adding that individual target to your project.

**Comment by MikhailTymchukFT** [comment]
Yes, I understand that behavior, but IDEA's behavior is confusing. Instead of indicating that this target is skipped/absent, it points to another existing target.
I think it's a UI bug.

**Comment by brendandouglas** [comment]
The plugin doesn't know that there's a missing target which would have been associated with the source code, and tries to pick the best target it can find, using a set of heuristics. This case is a bug with our heuristics (a java_binary with a known runtime_class attribute should never be associated with a different class, even if it's in the target's classpath), but it's not a trivial one to fix given how the code is structured.

It's not currently possible to resolve target information like this without building the target, though it's something we'd like to add support for.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
