### ISSUE TITLE
Nice to have an option to have non source directories

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#202]
Currently, you set root directory as a source directory. Nice to get a way to make only some directory source.

**Comment by brendandouglas** [comment]
Could you include some details on this use case? Why do you want directories in the project which aren't marked as source directories?

**Comment by solomatov** [comment]
For example, I want to create folders and use other IntelliJ actions which aren't available in source directories. I also don't want IntelliJ to highlight errors in files outside of source directories.

**Comment by chaoren** [comment]
> I also don't want IntelliJ to highlight errors in files outside of source directories.

You can exclude those directories in your project view:

```
directories:
  .
  -foo
  -bar/baz
```

**Comment by solomatov** [comment]
@chaoren I want to edit this files. AFAIU, if I exclude them, I won't be able to edit them.

**Comment by chaoren** [comment]
You should still be able to edit them just fine.

**Comment by solomatov** [comment]
@chaoren Ok. Then, it will help. Thank you!

**Comment by brendandouglas** [comment]
Closing this one, as there's a workaround.
