### ISSUE TITLE
Break points in BUILD files and WORKSPACES don't work

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/intellij#2035]
It is impossible to set a break point in a BUILD file or WORKSPACE in order to debug macros and rules when developing them, though this is supported in VS Code.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
