### ISSUE TITLE
Nodejs debugging problems

### ISSUE THREAD

**Issue by yueyingjuesha** [bazelbuild/intellij#2044]
Hi, my current working project are using bazel. the project is using nodejs_binary as the entry point, thing is I can click the green run button in intellij to use bazel to start the program, but the debug button is disabled, is there any way to enable debugging or it just don't support nodejs debug yet?

**Comment by brendandouglas** [comment]
There's no support for nodejs in the plugin, and no plans to add it unfortunately.
