### ISSUE TITLE
Generated files should be added to sources

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#205]
I created a generated file, but when I navigate to it in IDE, I navigate to a compiled .class file. Nice to be able to navigate to generated .java file instead.

**Comment by brendandouglas** [comment]
Could you include an example of when this happens? How is the file generated, and how are you navigating to it in the IDE?

**Comment by solomatov** [comment]
I can't copy the complete example but I can describe how it's structured.

1. I have a rule which uses ctx.actions.expand_template(). It output java file.
2. The generated file is compiled as port of a java library which is included via srcs.
3. There's a module which depends on the generated file.

I press Cmd+B (Ctrl+B) to navigate to generated file and I navigate to a class file. Sources for it aren't available. If I do similar thing with protobufs, integration is so much better.

**Comment by brendandouglas** [comment]
Ah, I see. The plugin isn't able to handle arbitrary genrules in the way you want.

It will only associate class files with their original sources if they were compiled with a standard Bazel rule (e.g. java_library) or with a custom rule implementing the java_common.provider API (https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html#modules.JavaInfo).

**Comment by solomatov** [comment]
> It will only associate class files with their original sources if they were compiled with a standard Bazel rule (e.g. java_library) 

I compiled them with java_library. They were just generated by a different rule.

**Comment by BrentDouglas** [comment]
@brendandouglas From what I have seen, and what I think @solomatov is seeing is:

- If the rule generating the sources returns a depset of .java files then the src jar in .blaze/libraries for the java_library using the generated code will be empty.
- If the rule generating the sources returns a .srcjar with those java files then src jar for the java_library in .blaze/libraries will have the generated sources.

I suspect @solomatov would like the sources to be included in the first case as well.

**Comment by solomatov** [comment]
@BrentDouglas That seems to be the problem which I have.

**Comment by brendandouglas** [comment]
@BrentDouglas do you have an example of this kind of genrule I could look at?

Currently, the plugin is only aware of source files communicated via the 'java' or 'java_common.provider' providers. The documentation on the bazel website describing these providers is incorrect, but JavaRuleOutputJarsProvider$OutputJar is the struct we're expecting -- associating a class jar / header jar with a source jar.

**Comment by BrentDouglas** [comment]
@brendandouglas While creating a reproducer I more clearly understood the issue. The java_library is happy to accept java files in either the current dir or in the package path (e.g. `./Foo.java` and `./com/whatever/Foo.java` are both valid). It also accepts both of these paths within a srcjar (e.g. `$jarroot/com/whatever/Foo.java` and `$jarroot/Foo.java` are both valid). The IDEA plugin however is more picky and will only attach sources for files in the current dir, or files in a srcjar in the package dir. i.e, it will attach `./Foo.java` but not `./com/whatever/Foo.java` and it will attach `$jarroot/com/whatever/Foo.java` but not `$jarroot/Foo.java`. The cases that it does pick up make sense to me, it actually seems more surprising that java_library accepts the other cases, however I would say the miss-match between the two is the source of confusion.

Hopefully that at least clarifies what the issue is. I created a project showing the four cases at https://github.com/BrentDouglas/bazel-intellij-205.

**Comment by mattnathan** [comment]
I recently came across this issue while migrating our project to bazel. The sample application @BrentDouglas wrote was very helpful for me to help diagnose the setup that will work for me. TL;DR always generate files in packages and create a srcjar to be safe.

I've updated the example to include a few cases that weren't covered before, specifically around the generated files java package not matching the bazel package defining the target. See https://github.com/vanti-public/bazel-intellij-205

The tests show that this is current state of play: 

- `{java file, source root, packages equal}` - sources attached
- `{java file, source root, sub package}` - no source
- `{java file, source root, super package}` - no source
- `{java file, source root, another package}` - no source
- `{java file, in package, *}` - no source
- `{srcjar, source root, *}` - no source
- `{srcjar, in package, *}` - sources attached

Where 
- `package equal` represents cases like `/src/foo/BUILD` and `package foo;`
- `sub package` represents cases like `/src/foo/BUILD` and `package foo.bar;`
- `super package` represents cases like `/src/foo/BUILD` and `package bar.foo;`
- `another package` represents cases like `/src/foo/BUILD` and `package bar;`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
