### ISSUE TITLE
Test/Coverage throws exception NoClassDefFoundError in GoLand

### ISSUE THREAD

**Issue by humphrej** [bazelbuild/intellij#2053]
When I run Run 'Bazel test xxx.go' with Coverage, my test is run successfully (see output) but the plugin throws NoClassDefFoundError in the IDE Fatal Errors

GoLand version:

> GoLand 2020.1.4
> Build #GO-201.8538.43, built on July 8, 2020
> macOS 10.15.5

Bazel plugin version:
2020.07.13.0.2

Test output: 

> Testing started at 09:26 ...
> /opt/bazel-3.4.1/bin/bazel coverage --tool_tag=ijwb:GoLand --curses=no --color=yes --progress_in_terminal_title=no --combined_report=lcov --runs_per_test=1 --flaky_test_attempts=1 --build_event_binary_file=/var/folders/4b/grxh2y496_91wtm6mdt1hdvm0000gn/T/intellij-bep-af8b29d4-e673-4208-a787-fc26eebb53b4 --nobuild_event_binary_file_path_conversion --action_env=DATABASE_URL -- //turps/internal/grpc:go_default_test
> Loading: 
> Loading: 0 packages loaded
> INFO: Using default value for --instrumentation_filter: "//turps/internal/grpc[/:]".
> INFO: Override the above default with --instrumentation_filter
> Analyzing: target //turps/internal/grpc:go_default_test (0 packages loaded, 0 targets configured)
> INFO: Analyzed target //turps/internal/grpc:go_default_test (0 packages loaded, 0 targets configured).
> INFO: Found 1 test target...
> [2 / 5] [Prepa] BazelWorkspaceStatusAction stable-status.txt
> INFO: LCOV coverage report is located at /private/var/tmp/_bazel_humphrej/9dfec7968f33e443d3cc1a95cb9e68fe/execroot/__main__/bazel-out/_coverage/_coverage_report.dat
>  and execpath is bazel-out/_coverage/_coverage_report.dat
> Target //turps/internal/grpc:go_default_test up-to-date:
>   bazel-bin/turps/internal/grpc/go_default_test_/go_default_test
> INFO: Elapsed time: 0.125s, Critical Path: 0.00s
> INFO: 0 processes.
> INFO: Build completed successfully, 1 total action
> //turps/internal/grpc:go_default_test                           (cached) PASSED in 1.0s
>   /private/var/tmp/_bazel_humphrej/9dfec7968f33e443d3cc1a95cb9e68fe/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/turps/internal/grpc/go_default_test/coverage.dat
> 
> Executed 0 out of 1 test: 1 test passes.
> There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
> INFO: Build Event Protocol files produced successfully.
> INFO: Build completed successfully, 1 total action
> INFO: Build completed successfully, 1 total action

IDE Fatal Error:

> java.lang.NoClassDefFoundError: com/intellij/psi/PsiClass
> 	at com.google.idea.blaze.java.run.coverage.BlazeCoverageProjectViewClassDecorator.getPsiFileForJavaClass(BlazeCoverageProjectViewClassDecorator.java:86)
> 	at com.google.idea.blaze.java.run.coverage.BlazeCoverageProjectViewClassDecorator.decorate(BlazeCoverageProjectViewClassDecorator.java:55)
> 	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0(CompoundProjectViewNodeDecorator.java:47)
> 	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach(CompoundProjectViewNodeDecorator.java:58)
> 	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate(CompoundProjectViewNodeDecorator.java:47)
> 	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:168)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:864)
> 	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:141)
> 	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:137)
> 	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
> 	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
> 	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
> 	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
> 	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:137)
> 	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:74)
> 	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:27)
> 	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:453)
> 	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:435)
> 	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:427)
> 	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:421)
> 	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:391)
> 	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:298)
> 	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:292)
> 	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:312)
> 	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:573)
> 	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:468)
> 	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:434)
> 	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:323)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
> 	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:206)
> 	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:184)
> 	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:524)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
> 	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by humphrej** [comment]
Updated title as it also happens on "Run test" not just "Run with Coverage"

**Comment by BabisK** [comment]
I have the same issue.

**Version information:**
GoLand 2023.1
Build #GO-231.8109.199, built on March 30, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-1037-azure

Non-Bundled Plugins:
    org.toml.lang (231.8109.91)
    com.intellij.kubernetes (231.8109.91)
    com.google.idea.bazel.ijwb (2023.03.10.0.1-api-version-231)
    com.github.intellij.ginkgo (0.9.4)

Current Desktop: ubuntu:GNOME
