### ISSUE TITLE
Bazel plugin for IntelliJ IDEA 2020.2.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by achinmishra** [bazelbuild/intellij#2064]
Build #IU-202.6948.69, built on August 24, 2020
I do not find the compatibles in the source to compile it from. Also, Jetbrains plugins repository is incompatible. Please advise.

**Comment by sseveran** [comment]
You will need to downgrade to 2020.1 at this time.

**Comment by ve6yeq** [comment]
@sseveran Is there any notes anywhere on what needs to be done to achieve 2020.2+ compatibility?

**Comment by ve6yeq** [comment]
Duplicate of #1998

**Comment by sseveran** [comment]
@ve6yeq Not that I know of. I believe we are just waiting for Google's internal tools team to update the plugin and they tend to lag a few months.

**Comment by alice-ks** [comment]
Closing this as a duplicate of #1998.
