### ISSUE TITLE
The problem of constructing tensorflow project by clion

### ISSUE THREAD

**Issue by xiaoyaozhuzi** [bazelbuild/intellij#2070]
Hi,
    I want to build tensorflow project based on CLION.
    CLion version:2019.3.6
    tensorflow:commitID 417f1481a7937399bc70f243d35de7ab3cd7fbcc
    bazel version:3.1.0
    OS Platform and Distribution:macOS 10.14.4
[bazelproject.zip](https://github.com/bazelbuild/intellij/files/5186606/bazelproject.zip)

    .bazelproject is shown in the attachment.
    The error information is shown in the attachment.

    I want to view and compile tensorflow code through CLION.
[clion.error.log](https://github.com/bazelbuild/intellij/files/5186593/clion.error.log)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
