### ISSUE TITLE
NPE when parsing Blaze XML output for exceptions without a message

### ISSUE THREAD

**Issue by cthornton** [bazelbuild/intellij#2086]
It looks like when running tests, if you raise an exception without a message (i.e. `throw new NullPointerException()`) it results in test xml output like so:

```xml
<error type='java.lang.NullPointerException'><![CDATA[java.lang.NullPointerException"
  at com.example.MyClass.myMethod(MyClass.java:55)
  at ... 
]]></error>
```
What happens is there's a bug in the parser that always assumes there's a message in this case, and throws a NPE.

I have a draft PR against my own fork here for an example -- https://github.com/cgthornt/intellij/pull/1. Could I go ahead and open a PR against this repo?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
