### ISSUE TITLE
Link IDE bazel cache with system bazel cache

### ISSUE THREAD

**Issue by Mdp11** [bazelbuild/intellij#2108]
Whenever I build targets within the IDE a different bazel cache is used from the one that is used when I build from outside the IDE (e.g. the terminal).
Is it possible to link the two caches, so that building a target in one environment, results in finding the same target already built in the other?

**Comment by sgowroji** [comment]
Hello @Mdp11, Could you please respond if you are still seeing the issue with latest bazel plugin and IDE versions.  Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
