### ISSUE TITLE
Feature request: improve scala test integration

### ISSUE THREAD

**Issue by jhp-stripe** [bazelbuild/intellij#212]
When running tests in a scala project, the test output isn't parsed by the IDE and the left pane of the test runner ends with the state 'Test framework quit unexpectedly'. It would be very helpful for the test integration to work more like other test runners in IJ.

**Comment by gkossakowski** [comment]
Chiming in.
Can be reproduced with: https://github.com/gkossakowski/bazel-scala-example
I believe this is a regression. I think test reporting used work better 2-3 months ago.

**Comment by chaoren** [comment]
Yes. It's a regression. We fixed the bug before the holidays so it should be in the next release.
