### ISSUE TITLE
Creating new Java class throws error

### ISSUE THREAD

**Issue by dillon-giacoppo** [bazelbuild/intellij#2127]
This plugin is impacted by this upstream bug in IntelliJ https://youtrack.jetbrains.com/issue/IDEA-244645.

The full steps to reproduce are in the upstream ticket. The impact of the bug is the following error when creating new Java classes:

```
Cannot Create Class

Unable to parse template "Class"
Error message: unknown error
```

The fix is `com.intellij.psi.codeStyle.CodeStyleManager.scheduleReformatWhenSettingsComputed` must be overriden in `DelegatingCodeStyleManager.java`.

**Comment by alice-ks** [comment]
Thanks for the report. We fixed this issue in #2229.
