### ISSUE TITLE
Debug button becomes disabled Clion

### ISSUE THREAD

**Issue by tadeegan** [bazelbuild/intellij#213]
![image](https://user-images.githubusercontent.com/1289052/35015219-357d3c00-fac8-11e7-830c-9a0dfd429515.png)

When running a test target, the debug button becomes disabled after the first run. After restarting Clion, the green debug button is restored and works as intended.

Clion Version:
2017.2

**Comment by brendandouglas** [comment]
Perhaps you're getting an exception when debugging? Do you see anything in the logs that might be related?

**Comment by tadeegan** [comment]
Where do the logs go? I'll take a look

**Comment by brendandouglas** [comment]
Thanks. 'Help > Show Log in File Manager' will open the logs directory. The latest 'idea.log' should show any recent exceptions.

**Comment by brendandouglas** [comment]
We haven't been able to reproduce this -- I'll close it for now, but please reopen if it's still happening.
