### ISSUE TITLE
Golang: Out of Sync / right-click test configurations

### ISSUE THREAD

**Issue by promiseofcake** [bazelbuild/intellij#214]
```
Versions: IDEA Ultimate 2017.3.3 / 2018.01.02.0.1
          IDEA Ultimate 2017.3.1 / 2017.11.20.0.4
```
We are missing the right-click Run/Debug options in Golang projects that we have for Java/Scala.

We can execute tests form the corresponding BUILD file, but not from the context of the test file itself either as a whole unit or an individual method.

It also appears that the Workspace is frequently out-of-sync (via the light in the toolbar).

Sample `.bazelproject`:
```
directories:
  .

targets:
  //...

additional_languages:
  go
```

I am interesting in contributing, would we just need to port somethings over from the Java/Scala invocations?

**Comment by chaoren** [comment]
You don't see these from right clicking?
![screenshot from 2018-01-17 14-30-58](https://user-images.githubusercontent.com/10055601/35062793-40d38eb2-fb93-11e7-8495-0ac0628f104e.png)
![screenshot from 2018-01-17 14-31-28](https://user-images.githubusercontent.com/10055601/35062830-5519936c-fb93-11e7-8cc2-5190c9958a56.png)

Can you share your project? Or a minimal repro case?

**Comment by promiseofcake** [comment]
Thanks for the reply @chaoren, yeah I am missing those options. Let me see if I can create a reproducible example outside our private monorepo context.

**Comment by promiseofcake** [comment]
@chaoren, here is one of our public projects that I was able to repro the issue with: 
https://github.com/vsco/domino

I setup the project via:
* Import Bazel Proejct
* Use existing workspace (GOPATH to repo)
* Create project view from scratch (using above)
* Re-syncing project / allow indexing to complete

Via `Test..` context:
![screen shot 2018-01-17 at 2 39 59 pm](https://user-images.githubusercontent.com/1462322/35063186-541c067e-fb94-11e7-91c7-ac16e4592166.png)

Via BUILD:
![screen shot 2018-01-17 at 2 40 20 pm](https://user-images.githubusercontent.com/1462322/35063199-62ec751c-fb94-11e7-94bd-b35cc0c99454.png)

**Comment by chaoren** [comment]
Problem seems to be in rules_go.
ctx.rule.attr is empty for go_test targets.

**Comment by chaoren** [comment]
https://github.com/bazelbuild/rules_go/issues/1251

**Comment by promiseofcake** [comment]
Thank you @chaoren 👍 !

**Comment by chaoren** [comment]
Bad news. Those providers are not usable unless we load their definitions from the rules_go repo into our aspect, but we also run the aspect for non-go workspaces, and there's no such thing as a conditional load. We'll need to talk with the bazel people about potentially changing the providers API.

**Comment by promiseofcake** [comment]
Is the `rules_go` project the only one that is not following the same convention for those providers? It would seem that in that case if let's say `rules_scala` made a similar change we would lose functionality there as well right?

**Comment by brendandouglas** [comment]
We're in discussions with the Skylark folks now to come up with a solution for this (likely adding support for a conditional load).

The only reason our plugin currently works for java-like languages (java, scala, kotlin) is that the java providers we use are bundled with Bazel. This is something we're going to have to solve for all languages.

**Comment by promiseofcake** [comment]
It works as of the latest plugin and IDE.
