### ISSUE TITLE
Opening Bazel project corrupts status bar widgets and doesn't allow to open a project in a new window

### ISSUE THREAD

**Issue by avshenuk** [bazelbuild/intellij#2147]
Environment:
MacOS 10.15.7
Intellij IDEA 2020.1
Bazel plugin 2020.10.06.0.1

Steps to reproduce:
1. Have a any existing project already opened. 
2. Try to open a different Bazel project by selecting the root folder as opposed to ".ijwb" folder.
3. The bottom-right status bar widgets get squashed together:
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/4578760/97077888-a84a4380-15e7-11eb-8306-a8735d07593e.png">

Additionally, the functionality of opening a project in a new window doesn't get triggered in that case.

So the problem seems to be in that `com.google.idea.blaze.base.project.BlazeProjectOpenProcessor.doOpenProject` 
calls `com.intellij.openapi.project.ProjectManager.closeProject(com.intellij.openapi.project.Project);` which does not dispose the project as opposed to `com.intellij.openapi.project.ex.ProjectManagerEx.closeAndDispose(com.intellij.openapi.project.Project)`, for instance. 

So the fix that worked for me was to replace in the class `BlazeProjectOpenProcessor`:
```
  public Project doOpenProject(
      VirtualFile file, @Nullable Project projectToClose, boolean forceOpenInNewFrame) {
    ProjectManager pm = ProjectManager.getInstance();
    if (projectToClose != null) {
      pm.closeProject(projectToClose);
    }
    try {
      VirtualFile ideaSubdirectory = getIdeaSubdirectory(file);
      if (ideaSubdirectory == null) {
        return null;
      }
      VirtualFile projectSubdirectory = ideaSubdirectory.getParent();
      return pm.loadAndOpenProject(projectSubdirectory.getPath());
    } catch (IOException | JDOMException e) {
      return null;
    }
  }
```
with 
```
  public Project doOpenProject(
      VirtualFile file, @Nullable Project projectToClose, boolean forceOpenInNewFrame) {
    VirtualFile ideaSubdirectory = getIdeaSubdirectory(file);
    if (ideaSubdirectory == null) {
      return null;
    }
    VirtualFile projectSubdirectory = ideaSubdirectory.getParent();
    return ProjectUtil.openProject(projectSubdirectory.getPath(), projectToClose, forceOpenInNewFrame);
  }
```
which solves 2 problems at once: asks the user how to open the project and disposes the existing project correctly. 

Hope this is helpful...

**Comment by tpasternak** [comment]
I know it's been a while, but it seems that the issue is not reproducible any more with IJ 2022.2
