### ISSUE TITLE
JetBrains WORKSPACE targets give 404

### ISSUE THREAD

**Issue by jasonps01** [bazelbuild/intellij#215]
I'm getting a HTTP 404 when trying to build //ijwb:ijwb_bazel from a freshly cloned repository.
`src/bazelbuild/intellij/third_party/scala/BUILD:7:1: no such package '@scala_2017_3//': Error downloading [https://download.plugins.jetbrains.com/1347/40959/scala-intellij-bin-2017.3.9.zip] to /home/user/.cache/bazel/_bazel_user/0446081692ec05d8fad40230bafbe8f3/external/scala_2017_3/scala-intellij-bin-2017.3.9.zip: GET returned 404 Not Found and referenced by '//third_party/scala:scala_internal'`

I believe JetBrains has changed their plugin URLs from https://download.plugins.jetbrains.com to https://plugins.jetbrains.com/files.

I was able to fix this issue locally with:
`sed 's/download.plugins.jetbrains.com/plugins.jetbrains.com\/files/g' --in-place WORKSPACE`

**Comment by meteorcloudy** [comment]
@brendandouglas This is causing [intellij to fail](https://ci.bazel.build/blue/organizations/jenkins/intellij/detail/intellij/339/pipeline) on Bazel CI, can you fix it?

**Comment by brendandouglas** [comment]
This is fixed upstream, just pending a repo update now. We'll likely do one later today.
