### ISSUE TITLE
The 2020.10.19.0.3 update of the bazel plugin broke @rules_python library resolution

### ISSUE THREAD

**Issue by crutcher-dunnavant-techlabs** [bazelbuild/intellij#2175]
Since installing the plugin, I can no longer follow code into python libraries included via @rules_python includes.

**Comment by samhowes** [comment]
I am also getting this, ex:  `from rules_python.python.runfiles import runfiles` shows "Unresolved reference 'rules_python' "
I downgraded to ijwb `2020.10.06.0.1` and `IntelliJ Idea CE 2020.1.4`, but I am still getting this issue. 

What was your last working version?
