### ISSUE TITLE
Support CLion 2020.2

### ISSUE THREAD

**Issue by sambercovici** [bazelbuild/intellij#2185]
Please add support to CLion 2020.2

**Comment by sambercovici** [comment]
Please review https://github.com/sambercovici/intellij

**Comment by zhuker** [comment]
@sambercovici how do i compile your plugin?

**Comment by sambercovici** [comment]
bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-2020.2

**Comment by illera88** [comment]
can you please do a PR so this gets merge to master?

Thanks for the code!

**Comment by illera88** [comment]
question. Does this version works for any 2020.2.X version?
thanks

**Comment by illera88** [comment]
I just tested it and it works with 2020.2.4

**Comment by zhuker** [comment]
works for me on 2020.2.4

**Comment by zhuker** [comment]
thanks @sambercovici

**Comment by sambercovici** [comment]
see: #2202
