### ISSUE TITLE
Allow customization of the bazel command line ran by the IJ plugin

### ISSUE THREAD

**Issue by RaresI** [bazelbuild/intellij#219]
The IJ plugin calls bazel with a hard-wired set of parameters. For example, when running build:

`bazel build --tool_tag=ijwb:IDEA:community --keep_going --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@intellij_aspect//:intellij_info.bzl%intellij_info_aspect --override_repository=intellij_aspect=C:\Users\Rares\.IdeaIC2017.2\config\plugins\ijwb\aspect --output_groups=intellij-compile-java -- //...
`
It is important that the user is able to customize those parameters. For example, on windows, passing the --output_base parameter makes possible to circumvent some long paths, when running from command line. 

Please place the command line templates on which substitution is performed either in the Settings/Bazel page or in a user editable resource file.

**Comment by chaoren** [comment]
You can add flags via

```
build_flags:
  --foo
  
sync_flags:
  --bar
```
in your .bazelproject file.

You can also edit each run configuration individually and add flags.
