### ISSUE TITLE
Is there some way to disable the key binding for showing "Bazel Problems" window

### ISSUE THREAD

**Issue by b4hand** [bazelbuild/intellij#2191]
Currently, when I press Ctrl-X followed by Ctrl-B this pops up the "Bazel Problems" view pane. However, I already have this shortcut configured in my IntelliJ Keymap and the plugin seems to override this key binding. Also, the shortcut for the Bazel plugin doesn't itself show up in the Keymap, so I can't figure out how to disable it. Is there some way to disable this shortcut or at least configure it to be something else in the plugin?

**Comment by alice-ks** [comment]
I can't reproduce the issue you're describing. I'm also not aware that that there was a default shortcut for it.

In any case, "Bazel Problems" is a tool window and thus can use IntelliJ's built-in mechanism for keyboard shortcuts. If you go to IntelliJ's keymap in the settings, look for "Bazel Problems" under "Tool Windows".
