### ISSUE TITLE
[question] Synchronizing files in bazel-out 

### ISSUE THREAD

**Issue by illera88** [bazelbuild/intellij#2204]
My project generates some `.cpp` and `.h` files in the `bazel-out` directory which I would like them to get indexed so I can jump between references in the code. I've tried to add `bazel-out` and the real full path to `bazel-out` since `bazel-out` is a symbolic link but the files does not get indexed (they show up as `unsynced`).

 
![image](https://user-images.githubusercontent.com/5193128/99020310-1c0aac80-2513-11eb-95a4-d771fafa58f4.png)

What can I do to sync the `bazel-out` directory too?

**Comment by illera88** [comment]
Any comments?
@vsiva @chaoren

**Comment by sgowroji** [comment]
Hello @illera88, Can you please try with latest bazel plugin and IDE versions and let us know if you are still seeing the issue. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
