### ISSUE TITLE
Kotlin: Safe delete should ignore glob patterns.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#221]
When it comes to build files safe delete should trigger on class references (main class) but not for glob patterns. Before implementing this verify the behaviour of the Java plugin.

**Comment by brendandouglas** [comment]
BuildFileSafeDeleteProcessor handles this for Java -- we'd want to either do something similar for Kotlin, or expand BuildFileSafeDeleteProcessor#handlesElement via an extension point (implemented in the Kotlin code to provide Kotlin-specific PsiElements)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
