### ISSUE TITLE
Golang Test Debugger runs with PWD being the project root

### ISSUE THREAD

**Issue by drastawi** [bazelbuild/intellij#2213]
The tests should execute in the build directory.

Right now when you "run" a test with the "run" button, it will use the build directory (bazel-out/k8-dbg/bin/...) and use the command `bazel test`. If you run with the "debug" button it will run in the project root and with the `bazel run` command.

**Comment by rodrigodiez** [comment]
Can replicate this on:

- GoLand Version `2021.1.3`
- GoLand Bazel Plugin Version `2021.08.24.0.0-api-version-211`

**Comment by simontoens** [comment]
Hi @rodrigodiez I upgraded to the latest GoLand (GoLand 2021.2.4 Build #GO-212.5457.54, built on October 15, 2021) and Bazel Plugin (2021.10.19.0.1-api-version-212) and I am also seeing this (I am seeing the same behavior with IJ).  This bug makes it difficult to debug tests that load files using a relative path.
