### ISSUE TITLE
clion bazel plugin error on mac

### ISSUE THREAD

**Issue by ynl** [bazelbuild/intellij#222]
![image](https://user-images.githubusercontent.com/5300032/35560058-4090524c-05e7-11e8-93b8-01ea2c0401a6.png)
Clion verion 2017.2.3 
After import bazel WORKSPACE  , the project cannot be load success

**Comment by brendandouglas** [comment]
Do you have a bazel binary at '/Users/ynl/research/examples/cpp-tutorial/stage1/bazel'?

If not, you'll need to set it in 'Settings > Other Settings > Bazel Settings' (or just Ctrl+Shift+A, then type 'bazel binary')

**Comment by ynl** [comment]
after change setting，it works
