### ISSUE TITLE
CLA vs `git commit -s`

### ISSUE THREAD

**Issue by sreev** [bazelbuild/intellij#2231]
what's the difference between CLA and git signoff `commit -s` ?

can it be streamlined with this workflow ?

git users use `git commit -s`.
CLA process picks up that event and do their internal updates.

this benefits contributors from additional step of CLA and email matching (google / github).
it also, saves contributors time from the focus.

**Comment by philwo** [comment]
Hi @sreev,

Thanks for your suggestion!

Google will only accept contributions to its open-source projects from people who have signed the Google CLA document, as with this signature "you give Google the legal permission to use and distribute your contribution" (source: https://cla.developers.google.com/about). Bazel and its related projects in this GitHub org are Google projects, so we have to adhere to this requirement.

In comparison, `git commit -s` as documented by Git means: "Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin" (source: https://git-scm.com/docs/git-commit).

This is not the same, so unfortunately one cannot replace the other. Hope this helps!
