### ISSUE TITLE
Targets generated by macros do not support "Find usages" and "Go to definition"

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/intellij#2244]
Targets generated by macros cannot be traced back to the corresponding macro rule target via the "Find usages" or "Go to definition" IDE actions. 

The logic to detect such macros has already been added as an experiment in https://github.com/bazelbuild/intellij/commit/bb953d070b93d92b3c175bb44599ad11d1a4324b, but it isn't used yet in `BuildFile#findRule`. I would suggest to move `BuildFileUtils#findMacroWithMatchingPrefix` into `BuildFile` and use it as a fallback in `BuildFile#findRule` if no rule with an exact name match is found. 

I have a working implementation of this at https://github.com/bazelbuild/intellij/commit/05692fdbad21c85b1c498f7523cf047146d92d70 that could serve as the basis of a discussion.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
