### ISSUE TITLE
2020.3 support

### ISSUE THREAD

**Issue by leoluk** [bazelbuild/intellij#2248]
Tracking issue for the IntelliJ 2020.3 major release, which the plugin isn't compatible with.

We're new to this ecosystem, is it normal for the Bazel plugin to trail ~1/2 year behind the IJ release? (not complaining, just wondering - if this is normal, we'll probably have to ask external contributors to our project to pin their IJ release)

**Comment by uri-canva** [comment]
Duplicate of https://github.com/bazelbuild/intellij/issues/2102.

**Comment by leoluk** [comment]
Oh, I somehow missed that. Thanks!
