### ISSUE TITLE
[question] Modern IntelliJ SDK

### ISSUE THREAD

**Issue by greenboxal** [bazelbuild/intellij#2266]
I recently spent quite some time digging into how the plugin works, and brainstorming improvements for our development flow (we have many monorepos with multiple languages such Go, Kotlin, Proto, JS, Python, etc).

Something that I noticed is that the IntelliJ SDK now has its own [external project system](https://jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/external_system_integration.html), which is used by the Gradle plugin, and it has an uncanny resemblance with the Bazel plugin, but built as a generic framework. I imagine JetBrains somewhat forked it from this plugin a long time ago (or the other way around). The [Pants plugin](https://github.com/pantsbuild/intellij-pants-plugin) is built on top of it as well.

My question is, are there any advantages on the modern architecture vs this plugin current implementation? Are there any plans to eventually migrate to this new framework? Even if far in the future?

The main reason driving this question to me is that developing using the IntelliJ framework seems easier than extending the current plugin, given the lack of documentation, we're investigating if there any major improvements in the development experience for any language that we use, including adding support for new ones.

**Comment by jastice** [comment]
The external system API predates the public release of this plugin, and at this point is considered legacy. Many IntelliJ subsystems are now being migrated to the so-called Workspace Model API (still in barely-stable state, so mostly undocumented).

There are no plans to migrate this plugin to either external system or workspace model APIs. However, we are building a new plugin at JetBrains that will use the new workspace model directly.
