### ISSUE TITLE
Kotlin js - imports from kotlin-stdlib-js are not resolved in Intellij

### ISSUE THREAD

**Issue by sudopk** [bazelbuild/intellij#2267]
E.g. None of the following are resolved.
```
import kotlinx.browser.document
import kotlinx.browser.window
import kotlinx.dom.createElement
```

Note that the bazel build etc works fine; this issue is with the plugin, where it is not handling the `.kjsm` files or something along those lines.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
