### ISSUE TITLE
Kotlin: breakpoints aren't hit in 2017.3 when Bazel plugin is installed

### ISSUE THREAD

**Issue by brendandouglas** [bazelbuild/intellij#227]
See https://youtrack.jetbrains.com/issue/KT-22422. I think this is happening for non-bazel projects.

If so, ExternalFilePositionManager is a likely culprit. Unlike other plugin-specific extensions, it's changing behavior without checking whether the project is a Bazel one.

**Comment by hsyed** [comment]
@brendandouglas [Is this the fix ?](https://github.com/bazelbuild/intellij/pull/217/files/8705af2cb73de8bafbefd3691fa9e132e7950beb#diff-353f8efa12fc2ab8df51f3ca25d30942)

**Comment by brendandouglas** [comment]
This particular bug is referring to our plugin interfering with Kotlin debugging for non-bazel projects, so the current fix (upstream) just disables ExternalFilePositionManager in that case (none of our plugin code should be changing the behavior of non-bazel projects, where possible).
