### ISSUE TITLE
python pip dependency rules - intellisense

### ISSUE THREAD

**Issue by IvanAtanasov89** [bazelbuild/intellij#228]
After importing a project into IntelliJ that uses the pip_import rule the IDE does not recognise that the libraries have been installed. i.e. import statements are highlighted as errors and there is no intellisense when using any of the objects provided by the library.

Is it possible to make this work? Not sure where the dependencies get installed to but it must not be a location present on the path that IntelliJ uses.

Running the application in the IDE works fine even when using the third party dependency, so they are getting installed just IntelliJ doesn't know about them or index them.

Thanks,
Ivan

**Comment by brendandouglas** [comment]
We don't yet support 'pip_import' (this is the first I've heard of it, though I hadn't looked at bazelbuild/rules_python for a while).

This is something we'd like to support, though it may take a while to find the time to do so.

**Comment by IvanAtanasov89** [comment]
Think it is a recently added rule: https://github.com/bazelbuild/rules_python

Thanks for considering it, would be useful to have this implemented.

**Comment by mtsgrd** [comment]
@brendandouglas at a high level, what is required to make this work?

**Comment by brendandouglas** [comment]
Someone with knowledge of the plugin would need to spend time understanding how pip_import rules work (in particular, how import statements are resolved, whether there's any generated code, etc.).

Then we'd need to add support for that into the plugin. That might require:
- specific handling for these targets in our skylark aspect
- adding another PyImportResolverStrategy

**Comment by mtsgrd** [comment]
I'm curious about how plugin development works so I tried to understand how the above could be added.. but, I seem unable to sync this project in Intellij 2018.1 on OS X. Could you confirm if this is meant to be working? One of the errors I see is about the `product_version` flag not being defined and I'm unsure of how that can be set when syncing.

**Comment by brendandouglas** [comment]
I don't see any issues syncing this project. Steps I took:
- checkout project, synced to master branch
- import in IntelliJ with bazel plugin (choosing ijwb/ijwb.bazelproject as the .bazelproject file)
- it syncs on startup without errors

If that doesn't work for you, could you paste the full error you see?

**Comment by mtsgrd** [comment]
Ah, silly me, I was creating the project from scratch. Thank you. :)

**Comment by mtsgrd** [comment]
I have some observations and a question. I found that aspects for external libraries are produced as expected, such as `external/pypi__httplib2_0_11_3/pkg-111052.intellij-info.txt`.

- sources in the aspects are processed [here](https://github.com/bazelbuild/intellij/blob/369ec0911356207231bffee0995095159ae8c93d/python/src/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategy.java#L98-L109), and put into a map from an "import string" (based on relative path, e.g. httplib2/__init__.py) to a `PsiElementProvider` object.
- when resolving an import [here](https://github.com/bazelbuild/intellij/blob/369ec0911356207231bffee0995095159ae8c93d/python/src/com/google/idea/blaze/python/resolve/PyDynamicImportResolverInitializer.java#L51) we return that `PsiElementProvider` [here](https://github.com/bazelbuild/intellij/blob/369ec0911356207231bffee0995095159ae8c93d/python/src/com/google/idea/blaze/python/resolve/provider/AbstractPyImportResolverStrategy.java#L58).
- the above can only happen if `toImportString` over [here](https://github.com/bazelbuild/intellij/blob/369ec0911356207231bffee0995095159ae8c93d/python/src/com/google/idea/blaze/python/resolve/provider/BazelPyImportResolverStrategy.java#L50-L55) returns a non-null value.

So I removed a condition excluding external sources in [this commit](https://github.com/mtsgrd/intellij/commit/97dec63c6dc58c02daab35ca96e845026e0c9442) and now the imports seem to work. Am I missing something or can the solution be quite easy like this?

**Comment by brendandouglas** [comment]
Thanks for investigating this. Is that how imports from external workspaces are referenced in Bazel (with no indication in the import string that they're external)?

If so, then your change should be all that's required -- I'll upstream it.

**Comment by brendandouglas** [comment]
Do you have a publicly available example of this I can look at?

**Comment by mtsgrd** [comment]
Right here: https://github.com/mtsgrd/intellij/commit/97dec63c6dc58c02daab35ca96e845026e0c9442

**Comment by mtsgrd** [comment]
And, yes, I believe that's how imports from external workspaces work. Nothing indicates it's an external source, such as the import statement `from absl import app`.

While debugging, I also noticed two more things.

- The CWD isn't set unless your `WORKSPACE` file declares a workspace name equal to the repo directory name. It seems the default workspace name is `__main__`, and would need to be handled [here](https://github.com/bazelbuild/intellij/blob/369ec0911356207231bffee0995095159ae8c93d/python/src/com/google/idea/blaze/python/run/BlazePyRunConfigurationRunner.java#L266).
- On OS X, debugging the extension doesn't work if the Intellij app name contains spaces (default is "Intellij IDEA CE"). The debugger exists saying "Error: Could not find or load main class IDEA" because the classpath argument to the command now contains spaces.

**Comment by mtsgrd** [comment]
I created a pull request here https://github.com/bazelbuild/intellij/pull/419, to highlight that `addImportCandidates` also seems to need tweaking to suggest fixes for packages.
