### ISSUE TITLE
Android Studio Plugin CI failing

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/intellij#2282]
Failing just as of yesterday (Jan 6, 2021)

Example failure:
https://buildkite.com/bazel/android-studio-plugin/builds/9599#cdb50c8f-00da-40ad-8876-3decea32c34a/87

Looks like a lot of class def errors, such as:

```
testNoReportNonStandardAndroidManifestNameInDependency(com.google.idea.blaze.android.rendering.BlazeRenderErrorContributorTest)
--
  | java.lang.UnsupportedClassVersionError: com/android/layoutlib/bridge/impl/RenderSessionImpl has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
  | at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by alice-ks** [comment]
Thanks for the report. There were several different issues (e.g. the referenced Android Studio version is based on Java 11 but our tests ran with Java 8). We fixed them and since yesterday, the build has been green again.
