### ISSUE TITLE
Error:Could not run Bazel info

### ISSUE THREAD

**Issue by lifeiteng** [bazelbuild/intellij#230]
How to solve those errors (I can build the project in Terminal using bazel)
```
Error:Cannot run program "bazel" (in directory "/xxx/xxx"): error=2, No such file or directory
Error:Could not run Bazel info
```

**Comment by lifeiteng** [comment]
dumped with #88

**Comment by david-wg2** [comment]
The solution in the linked issue is:
* Navigate to `Settings > Other Settings > Bazel Settings` 
* Update `Bazel binary location` to `/usr/local/bin/bazel`

**Comment by selvin** [comment]
Is there a way to bootstrap this value to `/usr/local/bin/bazel` when the bazel IJ plugin is installed?

**Comment by copbint** [comment]
On windows, you can install bazel from: [https://github.com/bazelbuild/bazel/releases](https://github.com/bazelbuild/bazel/releases), and then operate as `david-wg2` described.
