### ISSUE TITLE
Cannot debug `go_test` targets

### ISSUE THREAD

**Issue by XSAM** [bazelbuild/intellij#2313]
Goland cannot debug a `go_test` target that is fine to run.

```
API server listening at: [::]:56569
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1103.0.22
 for x86_64.
Got a connection, launched process /xxx/bazel-out/darwin-dbg/bin/ldap/go_default_test_/go_default_test.runfiles/xxx/go_default_test_/go_default_test (pid = 64624).
Exiting.
could not launch process: decoding dwarf section info at offset 0x0: too short
```

Then I found an issue that Bazel will strip debug symbols to reduces `go test` time. https://github.com/bazelbuild/rules_go/issues/2691. After I manually added `--@io_bazel_rules_go//go/config:debug`, it works.

-----

It might be worth adding this flag by default while debugging.

**Comment by jschaf** [comment]
I'm not sure if it's related, but testdata (maybe any `data` attribute`) isn't accessible when debugging using the `--@io_bazel_rules_go//go/config:debug`.  If I run the test target, it works as expected.

**Comment by fmeum** [comment]
> I'm not sure if it's related, but testdata (maybe any `data` attribute) isn't accessible when debugging using the `--@io_bazel_rules_go//go/config:debug` flag. If I run the test target, it works as expected and the test can access the testdata.

Looks like the plugin includes an experiment that is enabled by default and breaks the usual runfiles lookup. I was able to fix this by
1. Going to `Help -> Edit Custom Properties...` in IntelliJ.
2. Adding
```
blaze.experiment.blaze.go.script.path.enabled.2=false
```

@jschaf Does that fix the issue for you as well?

**Comment by fmeum** [comment]
@mai93 I verified that the script path experiment does not forward the `RUNFILES_*` variables for Go tests, but then launches the Go test binary from its runfiles. This makes the runfiles lookup process fail (see https://docs.google.com/document/d/e/2PACX-1vSDIrFnFvEYhKsCMdGdD40wZRBX3m3aZ5HhVj4CtHPmiXKDCxioTUbYsDydjKtFDAzER5eg7OjJWs3V/pub). I submitted #3120, which simply adds all `RUNFILES_*` vars to the environment of the test to start. I also checked that this fixes the problem and makes `go_test` targets find their runfiles. Do you agree with these changes?

**Comment by alice-ks** [comment]
With https://github.com/bazelbuild/rules_go/pull/3029 and https://github.com/bazelbuild/intellij/pull/3120 submitted, all mentioned issues should be addressed.
