### ISSUE TITLE
Please support latest IntelliJ

### ISSUE THREAD

**Issue by walles** [bazelbuild/intellij#2314]
Would it be possible for you to have support ready for new releases of IntelliJ as soon as they are out?

I would like to be able to upgrade IntelliJ when it prompts me to, and that's not possible right now if I want to use the Bazel plugin.

# Data
On **December 1:st 2020**, Jetbrains released **IntelliJ 2020.3**: <https://www.jetbrains.com/idea/download/other.html>

**A month and a half later**, on January 18:th 2021, the **Bazel IntelliJ plugin** was released, only **supporting IntelliJ 2020.2** <https://plugins.jetbrains.com/plugin/8609-bazel/versions>

# Definition of Done

`$SOMETHING` is in place to ensure that whenever a new release is made of IntelliJ, the Bazel plugin has already been updated to support the new release.

**Comment by chulkilee** [comment]
[IntelliJ IDEA 2021.1 is Out!](https://blog.jetbrains.com/idea/2021/04/intellij-idea-2021-1/) on 2021-04-07.

**Comment by mai93** [comment]
Closing since the plugin now supports the latest versions of IntelliJ and CLion.
