### ISSUE TITLE
What do releases mean?

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/intellij#2339]
Today, as often, I got a notification that there was a new release on this repo. (`v2021.02.02`).

When I look at the [Bazel IntelliJ plugin versions page](https://plugins.jetbrains.com/plugin/8609-bazel/versions), I see this most recent release:

- Bazel plugin version `2021.01.29.1.1`
- Date of release: `Feb 01, 2021`
- What's new:
    ```
    v2021.01.19

    ===========

    * Bug fixes and internal cleanup.
    ```

note that `v2021.01.19` is the *previous* release.

It would be nice to be able to line up the different versions. Is this documented somewhere / can you explain what they mean?

The thing that seems most true, possibly, is that that the IntelliJ plugin is released ~1-2 days before the next GitHub release (Bazel plugin released yesterday, GitHub release today), but claims to be for the *prior* release.

* Is this mislabeling, or accurate?
* If accurate, is the intent to let releases "bake" in GitHub before releasing them in IntelliJ repo? Who is using the github release tags vs from the IntelliJ distribution?

Anything as a user I can do to help with the release process or beta-test early versions?

**Comment by jvolkman** [comment]
I'm not familiar with the exact release process for this plugin, but I do know that there is a Jetbrains-mandated review period for new versions in their repo. Releases aren't listed there immediately, unlike Github.

**Comment by AlexeyGy** [comment]
@jvolkman is correct, we like to release early here so people who want to build the plugin themselves can have early access to bugfixes and features.
The changelog has the aforementioned default message if we don't have any noteworthy new features (we don't intend to include every commit in the changelog).

**Comment by dhalperi** [comment]
@AlexeyGy  - The current pattern I've seen is that every single time there's a new release in IntelliJ, the next day there's a new GitHub release. This has held up at least since I filed this issue, in maybe 3 releases.

IIUC, you're saying that the IntelliJ release is always for the prior GitHub release? And this is desired -- as opposed to, say, the IntelliJ release being a few days after the GitHub release -- independent of the next GitHub release?

**Comment by AlexeyGy** [comment]
@dhalperi it's very simple: the JetBrains release is last week's Github release*.

* unless there are bugs which we may hotfix before uploading to JetBrains. We don't create a new Github release for them but you can get the fixes via `git pull`.

**Comment by dhalperi** [comment]
Okay, nice. Sorry -- the part that I missed is that you are now committed to doing weekly releases? So that the JetBrains release is actually only 7 days after the last release?

(Observationally, the timing of the JetBrains release is tied to subsequent github, not prior github, release).

**Comment by AlexeyGy** [comment]
> you are now committed to doing weekly releases?
We release every two weeks.

> So that the JetBrains release is actually only 7 days after the last release?
approximately
