### ISSUE TITLE
Issues with sysroot cpp compiler and compiler version check.

### ISSUE THREAD

**Issue by tadeegan** [bazelbuild/intellij#238]
We recently implemented the crosstool sysroot option which causes the cpp compiler to be pulled down as an external dependency (deb package).  The problem we are running into is that to reference this compiler binary in our cc_wrapper, we have to point to a binary unpacked in our external execroot dir. like so:

```
CPU_COMPILER = 'external/com_ubuntu_sysroot/usr/bin/clang-3.8'
```

Our project builds fine except that now the bazel plugin fails to synchronize at this step:

https://github.com/bazelbuild/intellij/blob/d5e4e5073473a4a66d869d40743a08f8846063d5/cpp/src/com/google/idea/blaze/cpp/CompilerVersionCheckerImpl.java#L34

I believe the reason is that it calls the compiler binary with --version with the CWD to be the Workspace root. This is fine in most cases because usually the compiler is referenced with an absolute path (/usr/bin/clang...) but in this case, we are referencing a compiler expanded from a bazel dependency.  I believe the solution is to change this version checker to use the execrootpath rather than workspace root here:
https://github.com/bazelbuild/intellij/blob/d5e4e5073473a4a66d869d40743a08f8846063d5/cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationToolchainResolver.java#L182

See the failure from the idea.log below:
```

2018-02-13 15:17:21,031 [349719473]   WARN - cpp.CompilerVersionCheckerImpl - Error getting compiler version: "Traceback (most recent call last):
  File "/home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/execroot/xxx/external/xxx/tools/toolchain/cc_wrapper", line 264, in <module>
    sys.exit(main())
  File "/home/thomas/.cache/bazel/_bazel_thomas/925d2bb91b60f375fce428dfba68c0e1/execroot/xxx/external/xxx/tools/toolchain/cc_wrapper", line 242, in main
    return subprocess.call([CPU_COMPILER, "--version"])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
" 
```

**Comment by jvoung** [comment]
Do you happen to have a public example to test changes against? Thanks!

**Comment by tadeegan** [comment]
No, unfortunately not, although I suspect you could reproduce the issue by replacing this binary with a "/bin/pwd" you would see that the working directory is different for bazel compiles vs the version check in the plugin.
https://github.com/tensorflow/tensorflow/blob/b2a0f1c45b2283910548ebd88ee5aaf4b6fc6077/third_party/toolchains/gpus/crosstool/CROSSTOOL#L278

**Comment by jvoung** [comment]
I've committed a fix, which should show up in the next release branch.

CLion also runs the compiler to do some feature detection and dump the predefined macros, so I also changed the following wrapper to switch to the execution root first: https://github.com/bazelbuild/intellij/blob/d5e4e5073473a4a66d869d40743a08f8846063d5/cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationToolchainResolver.java#L296

Thanks!

**Comment by jvoung** [comment]
Changes synced (https://github.com/bazelbuild/intellij/blob/7801ae72aa44d4057f4ff88f9774efc1c81d791e/cpp/src/com/google/idea/blaze/cpp/CompilerVersionCheckerImpl.java#L33)
