### ISSUE TITLE
Working set target search includes manual&no-ide targets

### ISSUE THREAD

**Issue by jsannemo** [bazelbuild/intellij#2398]
When "Expand Sync to Working Set" is enabled, syncing may include building targets marked as `manual` and `no-ide`. Generally syncing seems to be good at avoiding them - project directory targets are filtered out using the manual tag.

I don't think the IDE should be responsible for syncing working set targets that are only built by `manual` targets. This is for example used in [j2cl](https://github.com/google/j2cl) to exclude some work-in-progress rules that are added but not used right now, causing failures when syncing targets using it.

Perhaphs the same filter for manual targets should be added to https://github.com/bazelbuild/intellij/blob/fe6d97de761903327095545d3bd4a24220800bb8/base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java#L101 ?

**Comment by sgowroji** [comment]
Hello @jsannemo, Could you please respond if you are still looking support on the above issue and It would be great if you can send us PR i can arrange it for review. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
