### ISSUE TITLE
ADB path appended to end of command and treated as target pattern

### ISSUE THREAD

**Issue by holmes** [bazelbuild/intellij#240]
I just started seeing this error when attempting to build and run an Android app from Android Studio. I have no idea what changed, it just stopped working.

Same error from the command line, but if I drop the values after the target (`--device emulator-5554 --adb_path /Users/holmes/Library/Android/sdk/platform-tools/adb`) it builds just fine. 

```
Waiting for mobile-install device target...
Command: /Users/holmes/Development/catalog/bazelw mobile-install --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --experimental_build_event_binary_file=/var/folders/_7/zdkhxrgx3t3_x1yb7bbhw1bm0000gn/T/intellij-bep-41b640ff-f581-4990-8304-fa3efd80dae7 --noexperimental_build_event_binary_file_path_conversion -- //src/test/java/com/squareup/shared/appointments/parsley/app/android:parsley --device emulator-5554 --adb_path /Users/holmes/Library/Android/sdk/platform-tools/adb

WARNING: Config values are not defined in any .rc file: bazelw.

ERROR: Skipping '/Users/holmes/Library/Android/sdk/platform-tools/adb': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/Users/holmes/Library/Android/sdk/platform-tools/adb'.
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/Users/holmes/Library/Android/sdk/platform-tools/adb'.
INFO: Elapsed time: 0.743s
INFO: Waiting for Build Event Protocol upload: 0s

```

**Comment by holmes** [comment]
Note that if I switch the configuration to "Run without using Bazel" it works just fine.

**Comment by chaoren** [comment]
Looks like bazel's mobile-install command changed its arguments around. You should file a bug against bazel.

**Comment by i-mann** [comment]
The bug seems to be in the plugin sending parameters through to bazel, rather than bazel itself given the sequence of events locally for me (i.e. upgrading the plugin immediately crashed it on a previously-working version of Bazel - 0.8.x).
I also had the issue of upgrading python (as requested by the Bazel upgrade to 0.11.1) causing further issues, and had to switch down to  3.6.3 from 3.6.4_3.

This work-around worked for me - thanks!

**Comment by chaoren** [comment]
`mobile-install` should work again after the next release in a week or two.
