### ISSUE TITLE
JS common library directory project configuration support for IJ-UE.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#241]
This only applies to IJ-UE I think.

I have started thinking about the JS aspect of the Kotlin rules. To get IJ to index JS we need to provide the directory.I don't know how much we need to configure from what is possible, but for the Kotlin rules I just need to be able to configure the the location of JS directories for now.  This could mean:

1. An extension point that allows JS plugins to contribute library directories similar to the Java sync plugin.
2. We could provide a project view setting to declare the location of a global JS directory (node_modules). This would have to allow label(s) as non-trivial uses of [rules_nodejs](https://github.com/bazelbuild/rules_nodejs#using-auto-managed-dependencies) will have  `node_modules`(s) (potentially multiple!!) directories as external repositories.

Just approach 2 should be enough -- read the project view if it's IJ-UE and update the project settings. Adding 1 is probably overkill since IJ-CE doesn't have advanced JS support.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
