### ISSUE TITLE
Windows CLion bazel sync error

### ISSUE THREAD

**Issue by ratanparai** [bazelbuild/intellij#242]
Whenever I try to import a bazel project into CLion with `VS 2017 C++ Build Tools` I get the error - 
```
Error:Unable to determine version of compiler D:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\cl.exe
```
I can build the project and run it after manually setting `Run/Debug Configurations` without any trouble. But  CLion code completion doesn't work and also show error on code (keywords in red font with can't find error) in the editor.

**Comment by brendandouglas** [comment]
We don't yet support Windows. There is some discussion in https://github.com/bazelbuild/intellij/issues/113 -- I'll close this one as a duplicate.
