### ISSUE TITLE
Patch proto jar with KtToolchainIdeInfo

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#243]
I am working on toolchain support for Kotlin. For now this is just to configure the compiler settings but I'll rework how the stdlibs and kotlin_home are managed afterwards. 

There will be a `KtToolchainIdeInfo` added to the `TargetIdeInfo`.  This only contains a `ArtifactLocation` to  the real ide_info which is a Json file compiled from a `kt_toolchain_ide_info` rule which gathers info from the `kt_toolchain` toolchain. `kt_toolchain_ide_info`  is a singleton rule defined in `io_bazel_rules_kotlin`. 

The proto jar in the repo seems to be packaged elsewhere. So I am currently rendering `KtToolchainIdeInfo` reflectively in `IdeInfoFromProtobuf`. Could the following update be applied to the proto jar. 

```
message KtToolchainIdeInfo {
  ArtifactLocation location=1;
}

message TargetIdeInfo {
  string label = 1 [deprecated = true];
  repeated string dependencies = 4 [deprecated = true];

  // kind is one of {JAVA,ANDROID}_{LIBRARY,BINARY,TEST} and JAVA_IMPORT
  JavaIdeInfo java_ide_info = 7;
  AndroidIdeInfo android_ide_info = 8;

  repeated string tags = 9;
  repeated string runtime_deps = 10 [deprecated = true];

  ArtifactLocation build_file_artifact_location = 11;

  CIdeInfo c_ide_info = 12;
  CToolchainIdeInfo c_toolchain_ide_info = 13;

  string kind_string = 14;

  TestInfo test_info = 15;

  ProtoLibraryLegacyJavaIdeInfo proto_library_legacy_java_ide_info = 16;
  JavaToolchainIdeInfo java_toolchain_ide_info = 17;

  PyIdeInfo py_ide_info = 18;

  TargetKey key = 19;

  repeated Dependency deps = 20;

  reserved 21;

  AndroidSdkIdeInfo android_sdk_ide_info = 22;

  reserved 23;

  repeated string features = 24;

  GoIdeInfo go_ide_info = 25;
  JsIdeInfo js_ide_info = 26;
  TsIdeInfo ts_ide_info = 27;
  DartIdeInfo dart_ide_info = 28;
  KtToolchainIdeInfo kt_toolchain_ide_info = 29;

  // Next available: 30
}
```

**Comment by hsyed** [comment]
I could update all of the paths to use `com.google.devtools.intellij.ideinfo.IntellijIdeInfo` instead, but I suspect there is a reason the repackaged version is used ?

**Comment by hsyed** [comment]
@brendandouglas @chaoren I've got toolchains working end-to-end. As mentioned I'm picking up the actual toolchain file from a singleton rule defined in the rule repo. At the moment I am piggy backing the location of the json file via the java toolchain ide info ([see](https://github.com/hsyed/intellij/blob/f84dfb97f7c1f53f8425fe3c06ab1672c22d3d4a/aspect/intellij_info_impl.bzl#L405-L427)) . 

Will it take long to patch the proto jar ?

**Comment by brendandouglas** [comment]
To handle incompatible versions in the classpath, we need to repackage the base protobuf classes. There's no need to repackage our own generated proto classes though (such as IntellijIdeInfo).

I'm making a change now to no longer repackage those classes, which should unblock you in the short term.

We'll also look at exposing our repackaging rule (we didn't do it originally due to missing dependencies, but after a recent refactor the only remaining dep is jarjar, which we can add here). That will take longer though.

**Comment by hsyed** [comment]
@brendandouglas any updates on this one ?

**Comment by hsyed** [comment]
Done
