### ISSUE TITLE
Error: Deriving targets from project directories failed on Clion 2019.3.6 using Version 2020.07.13.0.2 of this Plugin

### ISSUE THREAD

**Issue by DrewGlinsman** [bazelbuild/intellij#2434]
I'm trying to get this bazel project building on my version of clion on windows but keep getting this error when trying to sync the project. If I try to partially sync one file I get this error: Error: Failed to parse target pattern even though it was previously parsed successfully: Invalid package name 'Reactor\Base': package names may contain A-Z, a-z, 0-9, or any of ' !"#$%&'()*+,-./;<=>?[]^_`{|}~' (most 7-bit ascii characters except 0-31, 127, ':', or '\')

The strangest part of this is my partner working on this repo with me has no issues importing and building this project with the exact same version of clion and this plugin.

Does anyone know what could be going wrong?

**Comment by samhowes** [comment]
Any update on this?

I am also getting this issue when clicking "Partially Sync" from the context menu:

> ERROR: Error while parsing 'same_pkg_direct_rdeps(//src\tools\launcher:python_launcher.h)': syntax error at '\tools \launcher:python_launcher.h )' 

<img src="https://user-images.githubusercontent.com/6216665/112920344-c3f5d080-90d6-11eb-9d15-36c20fef9d84.png" height="400">

![image](https://user-images.githubusercontent.com/6216665/112920412-e7b91680-90d6-11eb-89c0-938ea7fdf767.png)

#### Version information

> CLion: 2020.2.5
> Platform: Windows 10 10.0
> Bazel plugin: 2021.03.02.2.3
> Bazel: 4.0.0

**Comment by sgowroji** [comment]
Hello @DrewGlinsman, Could you please verify the above with the latest clion and bazel plugin. Thanks!

**Comment by kshyanashree** [comment]
Hello @DrewGlinsman! Could you please respond to above comment? Thanks!
