### ISSUE TITLE
Migrate from dom.fileDescription EP

### ISSUE THREAD

**Issue by YannCebron** [bazelbuild/intellij#2439]
https://github.com/bazelbuild/intellij/blob/9600e57d3471026558322fc41c7cbb9e463a7518/aswb/src/META-INF/aswb.xml#L50

If your plugin targets 2019.1 or later, please use extension point com.intellij.dom.fileMetaData instead and specify rootTagName and domVersion/ stubVersion in plugin.xml.

**Comment by alice-ks** [comment]
Thanks for the heads up. Is there a specific reason you're explicitly pointing us to this (e.g. will dom.fileDescription vanish in the next major version)?

So far, we've mimicked the registration of ResourcesDomFileDescription of the Android plugin as BlazeResourcesDomFileDescription is just a simple extension to allow unusual locations for AndroidManifest.xml. On 211, ResourcesDomFileDescription seems to be still registered as dom.fileDescription. Do you expect this to change?

**Comment by YannCebron** [comment]
`dom.fileDescription` is unlikely to go away in foreseeable future. `dom.fileMetaData` is a 1:1 replacement extension point avoiding unnecessary class-loading, so it should be a trivial change (if possible w/r to base target platform).

**Comment by alice-ks** [comment]
Fixed in #2525.
