### ISSUE TITLE
Better support for python

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/intellij#244]
Nice to have the following things:
* On project import, a interpreter should be create via virtualenv where all declared dependencies should be installed
* On project reimport all dependencies should be updated

Currently, I have to create a virtualenv and start bazel out of it which isn't really a good experience.

**Comment by ilanKeshet** [comment]
Any news or updates about downloading python dependencies and making them available inside the IDE?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
