### ISSUE TITLE
Build intellij aspect in the container

### ISSUE THREAD

**Issue by blindchaser** [bazelbuild/intellij#2443]
Hello!
I'm trying to build target from the IDE on a mac OSx, with bazel running inside a local docker container. similar to this use case: https://github.com/bazelbuild/intellij/issues/397 .  

Instead of using the --override_repository=intellij_aspect way, I'd like to download it and build it in the container by using the http_archive() in root WORKSPACE. Any idea how can I achieve this goal?

**Comment by mai93** [comment]
I think you will need to update the flags specified in [AspectStrategyBazel](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java#L45) class to use another aspect and not add `--override_repository=intellij_aspect`.
