### ISSUE TITLE
Change InteliJ Python interpreter to custom python py_runtime_pair

### ISSUE THREAD

**Issue by rmporsch** [bazelbuild/intellij#2447]
within the root of my workspace I have something like the following BUILD.bazel

```
load("@rules_python//python:defs.bzl", "py_runtime_pair")

py_runtime(
    name = "python3_runtime",
    files = ["@python_interpreter//:files"],
    interpreter = "@python_interpreter//:python_bin",
    python_version = "PY3",
    visibility = ["//visibility:public"],
)

py_runtime_pair(
    name = "my_py_runtime_pair",
    py2_runtime = None,
    py3_runtime = ":python3_runtime",
)

toolchain(
    name = "my_py_toolchain",
    toolchain = ":my_py_runtime_pair",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
```
In which `@python_interpreter` is the associated project where I build my python executable. The toolchain is then registered in the WORKSPACE with `register_toolchains("//:my_py_toolchain")`

This works fine when building in the command line my targets. The same accounts for building within the IDE. However I noticed that my Pycharm Python interpreter defaults back to the system interpreter. This also relates back that the plugin seems not to be able to pick up `pip_install` #2239 .
What would be the best way to change to the interpreter I registered in my toolchain?

**Comment by sgowroji** [comment]
Hello @rmporsch, Could you please respond if you are still looking support on the above issue. Thanks!

**Comment by cnsgsz** [comment]
I'm looking for this support too.
