### ISSUE TITLE
Unexpected test_filter for nested test classes

### ISSUE THREAD

**Issue by littleclay** [bazelbuild/intellij#245]
If you have the following test class (using JUnit Jupiter annotations for the test code):

```
package com.foo;

public class FooTest {

    @Nested
    public class BarTest {

        @Test
        public void testFooBar() {
            // stuff
        }
    }
}
```

Then I click on the green "run/debug" arrow next to the test method `testFooBar` to generate a run configuration for it. It creates a configuration with a `--test_filter` flag that has a `.` between the outer class and the inner class rather than the qualified class name which would have a `$` between them.

*Actual*
```
--test_filter=com.foo.FooTest.BarTest#testFoo
```

*Expected*
```
--test_filter=com.foo.FooTest$BarTest#testFoo
```

OS:
`macOS 10.13.3`

Bazel Plugin Version:
`Version: 2018.01.29.0.2`

IntelliJ Version:
`Ultimate IDEA 2017.3.4 Build# IU-173.4548.28`

**Comment by brendandouglas** [comment]
Thanks for the details. It's definitely a bug, but one that we'd previously left because it almost never causes problems with JUnit4 ('.' is treated as a wildcard). I take it this isn't the case with JUnit5?

**Comment by littleclay** [comment]
Yeah, the JUnit5 ConsoleLauncher requires the fully qualified test method name for selection by method name and the '.' is invalid in this case.

**Comment by littleclay** [comment]
Also, you usually couldn't have nested test classes in JUnit 4 but you can in JUnit 5.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by carolosf** [comment]
It looks like bazel 6 offers some JUnit 5 support looks like JUnit 5 support might be in a position now to be supported by the IntelliJ plugin.
