### ISSUE TITLE
Add support for WebStorm

### ISSUE THREAD

**Issue by IgorMinar** [bazelbuild/intellij#246]
The bazel plugin officially supports only Intellij IDEA. I'd like to be able to use it also with WebStorm for building Angular/Typescript/web applications (see http://g.co/ng/abc).

### Installation
- download the latest plugin build from https://plugins.jetbrains.com/plugin/8609-bazel
- install the plugin from disk using the downloaded file

### Run Configuration
- the plugin can't be used to create Run Configuration, so the way to run builds/tests is to setup a Run Configuration via Bash plugin

## Current experience
Editing of build and bzl files is supported by autocompletion, but that's about all the support one gets when installing the extension using the method described above.

//cc @alexeagle

**Comment by brendandouglas** [comment]
We do support IntelliJ UE, which as I understand it is a functional superset of WebStorm. Can you add some details on the use case for standalone WebStorm, and whether using IJ UE instead is a valid workaround?

**Comment by IgorMinar** [comment]
Front-end engineers don't use IDEA. They use WebStorm because it's more lightweight and provides only the relevant functionality. This is why IntelliJ created the product after all.

It's very rare for front-end engineers to use IDEA unless they are required to do so via an corporate policy.

**Comment by brendandouglas** [comment]
Thanks for the background. We don't currently have any plans to support other IDEs, except where they provide functionality not available in IntelliJ, Android Studio, or CLion (the 3 IDEs we currently support).

That might change in the future, but we currently don't have the resources to take on the additional maintenance burden.

**Comment by mgol** [comment]
Frontend engineers also use WebStorm because it's almost 3 times cheaper than IntelliJ IDEA Ultimate (and who'd pay 3x more for features they don't need?) and the free IDEA Community doesn't support Web features so it's useless for frontend programmers.

**Comment by brendandouglas** [comment]
Noted, thanks. We don't currently have the resources to support this, as we're a small team whose primary purpose is supporting internal users (who don't use WebStorm).

That would likely change if there was sufficient demand and/or this became important enough to some other team willing to dedicate resources to it (Bazel, whoever's working on http://g.co/ng/abc, etc.).

**Comment by alexeagle** [comment]
We've had the same discussion internally at Google when the go/typescript install instructions pointed developers to Webstorm instructions, and our team purchased the license pool that was later turned down.
If we fix this, we should do it for both, IMO

**Comment by IgorMinar** [comment]
Both? Can you clarify please?

**Comment by alexeagle** [comment]
both -> support internally in Google as well as externally.
Pro: it's convergence, and we make sure things work
Con: maybe it's still more maintenance work for the IJ team even if the plugin were externally supported
Sorry, this is not really relevant, we should start with making the plugin work at all.

Do we know if there is any work required here aside from changing the min/max range in the plugin descriptor?

**Comment by IgorMinar** [comment]
I'm not sure. Syntax highlighting works if you follow my workaround.

In the past I also saw some exceptions related to junit (reporter?) which
I'm guessing is used to show build progress and results - this plugin is
not currently available for Webstorm. I haven't seen these exceptions
recently so maybe something has changed.

**Comment by brendandouglas** [comment]
I've added nominal support for WebStorm in the latest plugin. There are no additional features, I've just moved all the IntelliJ-specific code behind an optional dependency.

**Comment by IgorMinar** [comment]
I'll give it a try. Thanks!

**Comment by brendandouglas** [comment]
I'll close this FR -- please open separate FRs for any specific features you'd like us to add to the plugin.

**Comment by Ubehebe** [comment]
Is code completion for Bazel-generated files expected to work in WebStorm? In IDEA, that's one of the plugin's most valuable features (workflow: add proto file, add java_proto_library target, Bazel > Sync > Sync Project with BUILD Files). But in WebStorm, I don't even see a Bazel menu.

(I'm using WebStorm 2018.1, build #WS-181.5087.27, with version 2018.05.21.0.0 of the Bazel plugin.)

**Comment by brendandouglas** [comment]
If you don't see a Bazel menu, then the Bazel plugin isn't enabled, or didn't properly load.

You should have an error message on startup if there was a problem loading the plugin.
