### ISSUE TITLE
Missing IntelliJ releases

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/intellij#2461]
The latest release available for IntelliJ is `2021.03.02` (from [here](https://plugins.jetbrains.com/plugin/8609-bazel/versions/stable)). There have been [two releases](https://github.com/bazelbuild/intellij/releases) on this repo since then. Same goes for [Android Studio](https://plugins.jetbrains.com/plugin/9185-bazel/versions).

How are those versions usually pushed? Can this be automated when a new release is tagged?

**Comment by alice-ks** [comment]
After tagging a release, we typically test it first with a smaller amount of users. Only after the testing period (typically ~2 weeks), we push the new release to the plugin repository. Hence, you should see the v2021.03.22 release show up in the plugin repository within the next 1-2 weeks. v2021.03.15 was a release we decided to drop, which happens rarely. So, typically, you should just see one release which might not have been pushed to the plugin repository yet.

**Comment by Kernald** [comment]
I see, thanks for the explanation!
