### ISSUE TITLE
embedded sources are not resolved

### ISSUE THREAD

**Issue by dududko** [bazelbuild/intellij#2480]
When use embedding in go_library then references from go_default_library to the golang entities(funcs, structs, interfaces) in the embedded sources are not resolved. By embedding I mean the following feature in rules_go:
https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#embedding

### How to reproduce the bug:

```
// foo.go
package foo

type (
	Foo struct {
		bar  Bar // <-- the following type is not resolved by bazel plugin for IDEA
	}
)
```

```
// bar.go
package foo

type (
	Bar struct {

	}
)
```
```
# BUILD.bazel
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "foo_and_bar",
    srcs = ["foo.go"],
    embed = [":bar"],
    importpath = "example.com/foo",
)

go_library(
    name = "bar",
    srcs = ["bar.go"],
    importpath = "example.com/foo",
)
```

Of course I can put all source files in a single go_library, but in my particular case I need two go_library targets + embed.

**Comment by excavador** [comment]
any updates?

**Comment by excavador** [comment]
any updates?

**Comment by sgowroji** [comment]
Hello @dududko, Are you still seeing the above issue with latest bazel plugin release version. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
