### ISSUE TITLE
HEAD (1.9.4) causes non-bazel java projects to go "(unsynced)"

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/intellij#25]
I loaded up github.com/google/closure-templates with Intellij with Bazel built from master and all of the java code says is marked as "(unsynced)" and the tabs show up red.

That closure-templates has no bazel BUILD files in it, so IJWB should probably not even matter. But we did the debugging work in https://intellij-support.jetbrains.com/hc/en-us/requests/787044?page=1 and only disabling ijwb fixed the problem.

Think ijwb got a little greedy with what java files it thinks it should own.

Also, unclear what "(unsynced)" means in this context!

**Comment by brendandouglas** [comment]
'Unsynced' denotes files which aren't covered by a Bazel build target.

This (along with all the other IJwB features) will only appear for Bazel projects -- projects which were imported by this plugin.

To import non-Bazel projects, like the one your describing, just use the standard IntelliJ import options (i.e. not the "Import Bazel Project..." action), and you should have no problems.

**Comment by ittaiz** [comment]
One can even argue this is a feature and not a bug since the plugin is
vocal in expressing what it doesn't support. Otherwisev one might baffle at
why their mixed Java closure project doesn't work "properly" in IntelliJ as
it works from the command line

**Comment by jmhodges** [comment]
I think there's been a miscommunication.

This happens when I create closure-templates as a new maven project from the existing source but have the bazel plugin installed (and globally, but not project specifically, enabled) in Intellij.

I just did it again and confirmed that's what's happening. I'll see if GitHub will let me upload a video for y'all.

**Comment by jmhodges** [comment]
Okay, here's the video of me importing the new maven project with ijwb installed but not enabled for that project: https://youtu.be/kT-8TTndOKw

And here's me globally disabling the plugin, restarting intellij, and the project then working correctly: https://youtu.be/QveozT6UfYc

By the way, thanks for responding so quickly!

**Comment by brendandouglas** [comment]
Ah, sorry for the misunderstanding. You're quite right, it's incorrectly annotating files for non-bazel projects (a bug in SyncStatusHelper).

Thanks for the catch -- we'll fix this in the next build.

**Comment by jmhodges** [comment]
Dope. Thanks much!

**Comment by jmhodges** [comment]
Oh, by "build", do you mean an import from some other repo? Any idea when that might happen?

Thanks!

**Comment by brendandouglas** [comment]
The fix should be in the latest release on JetBrains plugin repository (https://plugins.jetbrains.com/plugin/8609, v1.10.2).

**Comment by jmhodges** [comment]
Oh! Confirmed and closing.
