### ISSUE TITLE
Feature Request: Populate "Target" for Run/Debug Configuration "Application"

### ISSUE THREAD

**Issue by JohanLaine** [bazelbuild/intellij#250]
For CMake projects, CLion adds CMake targets automatically when detecting `add_executable` in CMake scripts and populates the "Target" field for the Run/Debug Configuration "Application". (See [here](https://www.jetbrains.com/help/clion/quick-cmake-tutorial.html) and [here](https://www.jetbrains.com/help/clion/run-debug-configurations-dialog.html).)

We have a shared C++ library that is dynamically linked to an external application, and we need to be able to debug the shared library with breakpoints set in Clion. Currently we are doing this with an Application Configuration for CMake targets.

We are currently porting this library from CMake to Bazel and want to be able to keep debugging it in the same way. However, Bazel targets in .bazelproject don't populate this field, and there seems to be no way of populating this manually. So far I haven't managed to find a workaround. Is this in some kind of road map?

**Comment by brendandouglas** [comment]
If I'm understanding the situation, as part of porting to Bazel you'll create a cc_binary target for the application.

Run can manually create a run configuration for that target by any of:
- right-clicking the target in the BUILD file, and choosing '[Run/debug/create] Bazel run...'
- manually creating a 'Bazel command' run configuration in the run config editor, then filling in the 'target' field (will autocomplete targets in your project).
- adding that specific target to your .bazelproject 'targets' section, then running 'Bazel > Sync > Sync Project' -- run configurations will be automatically created during sync for any explicitly specified binary or test targets (not wildcard targets) in your .bazelproject file.

**Comment by JohanLaine** [comment]
Our cc_binary is a shared library, we need to execute it by starting another binary (which is external and isn't a Bazel binary target), so we can't use 'Bazel command' run configurations.

**Comment by brendandouglas** [comment]
Thanks for the details. This isn't something we can do in the Bazel plugin -- we'd need to add an entirely new run configuration type just for this purpose.

**Comment by bleppard** [comment]
The ability to specify an executable to debug, seems like a pretty fundamental functionality for a debugger.

**Comment by chaoren** [comment]
You do have the ability to specify an executable to debug.
If your executable is external to the build system, then it will take some extra steps.

**Comment by cjolivier01** [comment]
+1 for this need
