### ISSUE TITLE
Error import bazel project

### ISSUE THREAD

**Issue by salvita001** [bazelbuild/intellij#2512]
I have IntelliJIdea installed in windows 10 and an ubuntu 18 (with my repo) downloaded to work from intelliJidea.
I'm trying to import a BAZEL project from my Ubuntu system installed into windows and always get the same error:
[FATAL 19:05:15.720 src/main/cpp/blaze.cc:1293] blaze_util::MakeCanonical('c:\users\ssanchez\appdata\local\packages\canonicalgrouplimited.ubuntu18.04onwindows_79rhkp1fndgsc\localstate\rootfs\home\salva\workspace\masmovil\mm-monorepo') failed: (error: 3): El sistema no puede encontrar la ruta especificada.

**Comment by baisijian** [comment]
i got the same error

**Comment by sgowroji** [comment]
Hello @salvita001, Can you please try with the latest bazel plugin and intellij release and let us know if you still see the above error. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
