### ISSUE TITLE
Bazel IntelliJ integration ignores custom rules outputting Go libraries

### ISSUE THREAD

**Issue by lorenz** [bazelbuild/intellij#2534]
We have some custom rules generating Go libraries with the help of rules_go's Starlark API. They all have a `go_generated_srcs` output group so that the aspect can pick them up with minimal patching. But IntelliJ doesn't pick up the output from the aspect as it doesn't process aspect output if it doesn't know the `kind_string` of the rule. This requires rather invasve workarounds like forcibly propagating metadata along the `embed` edges to a go_library rule so that IntelliJ can pick up the generated files.

Is there a good reason why it cannot just evaluate all rules which generate a `go_ide_info` structure?

**Comment by sgowroji** [comment]
Hello @lorenz, Let us know if you are still looking support on the above issue.  Please reach us back. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
