### ISSUE TITLE
Bazel Sync failed   Error:Deriving targets from project directories failed.

### ISSUE THREAD

**Issue by gaobin881201** [bazelbuild/intellij#2537]
#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Error:Deriving targets from project directories failed.
#### Version information
AndroidStudio: 4.0
Platform: Windows 10 10.0
Bazel plugin: 2020.06.25.0.3
Bazel: 4.0.0

**Comment by mai93** [comment]
Hello @gaobin881201 Do you still get this error with newer plugin and IDE versions? If so, can you provide us with more details about the project and project view file to reproduce this error?

**Comment by mai93** [comment]
Closing this issue, if you still see this problem please feel free to reopen the issue and provide us with more information to reproduce it.
