### ISSUE TITLE
Error while parsing 'same_pkg_direct_rdeps(target with spaces)'

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/intellij#2570]
Sometimes an error `Error while parsing 'same_pkg_direct_rdeps(<...>)'`  appears when syncing bazel repo:
```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no --
Command: git diff --name-status --no-renames 39decda9b1b4f711ce850a48de940518eafb6df2
INFO: Invocation ID: b776fb7b-1749-4a98-abc1-d22fcccaa87c
Computing VCS working set...
  ...
  some path/with spaces (modified)
  ...
  (and 10 more)
Querying targets building source files...
Command: /usr/local/bin/bazel query --tool_tag=ijwb:IDEA:community --output=label_kind --keep_going "same_pkg_direct_rdeps(some
path/with
spaces
Loading: 0 packages loaded
ERROR: Error while parsing 'same_pkg_direct_rdeps(some
path/with
spaces...[truncated]': syntax error at 'path/with'
Loading: 0 packages loaded
Loading: 0 packages loaded
Sync finished
Sync failed
```

This can be fixed easily if `same_pkg_direct_rdeps` argument is quoted, see
https://github.com/MikhailTymchukFT/intellij/commit/d97c71bb97fbebcb5e0c06f97c631c9b0c6dcb09

**Comment by mai93** [comment]
I think this is fixed by https://github.com/bazelbuild/intellij/commit/acc4c701732103854543ddd4cc80d7b86804d7ae. If you are still seeing this error, feel free to reopen the issue.

**Comment by sbabcoc** [comment]
This issue still occurs, affecting project sync with BUILD files in the Selenium project. I'm running on Windows 10, which may be a significant factor in this issue.

**Comment by sbabcoc** [comment]
Here's the error I get when syncing the Selenium project on Windows 10:
```
Error: Querying blaze targets building project source files failed.  
ERROR  
Error: Error while parsing 'same_pkg_direct_rdeps(//common\private:passwd.bzl+//deploys\docker:docker.bzl+//java\test\org\openqa\selenium\netty\server:SimpleHttpServer.java+//:.bazelignore+//:.bazelrc+//:Rakefile+//:WORKSPACE+//deploys\docker:selenium.sh+//dotnet\private:nuget.bzl+//java:maven_deps.bzl+//java:maven_install.json+//java\src\org\openqa\selenium\chrome:ChromeDriverService.java+//java\src\org\openqa\selenium\chromium:ChromiumDriver.java+//java\src\org\openqa\selenium\devtools:CdpEndpointFinder.java+//java\src\org\openqa\selenium\devtools:SeleniumCdpConnection.java+//java\src\org\openqa\selenium\edge:EdgeDriverService.java+//java\src\org\openqa\selenium\firefox:FirefoxDriver.java+//java\src\org\openqa\selenium\grid\node:ProxyNodeWebsockets.java+//java\src\org\openqa\selenium\json:Json.java+//java\src\org\openqa\selenium\json:JsonOutput.java+//java\src\org\openqa\selenium\remote\http\jdk:JdkHttpClient.java+//java\test\org\openqa\selenium:ProxySettingTest.java+//java\test\org\openqa\selenium\g[truncated]': syntax error at '\private:passwd.bzl + //deploys'
```

**Comment by sbabcoc** [comment]
I haven't tracked down the code that's actually throwing the error, but perhaps the backslash characters are being interpreted as escapes by some part of the implementation. This would certainly lead to confusion.

**Comment by sbabcoc** [comment]
This commit resolved part of the problem by ensuring that each source entry is handled as a single value, even if it contains spaces: https://github.com/bazelbuild/intellij/commit/acc4c701732103854543ddd4cc80d7b86804d7ae

**Comment by sbabcoc** [comment]
If the platform is WIndows, escape backslashes by doubling them up. I think this is the only check that's required. As for the HOME variable, if the platform is Windows and the **HOME** variable isn't defined, adopt the value of the ""USERPROFILE"" variable.

**Comment by sbabcoc** [comment]
The check for Windows: `System.getProperty("os.name").matches("(?i).*win.*")`

**Comment by sbabcoc** [comment]
Hmmm... seems I may have spoken too soon. The reason that all of the error marks got removed is that IntelliJ now thinks none of the source files are "outside of source root".
