### ISSUE TITLE
CI only tests intellij-beta (2020.3) and allows other products to break

### ISSUE THREAD

**Issue by caseyduquettesc** [bazelbuild/intellij#2572]
If I pull the last release (v2021.04.26) and try to build with `--define=ij_product=intellij-2021.1`, the build fails. Admittedly, 2021.1 isn't officially supported AFAIK, but the point is the CI tests only run for one version of intellij (intellij-beta) and can risk allowing other products to break.

![image](https://user-images.githubusercontent.com/16676170/116310264-9dbb6300-a75e-11eb-90c0-599a7c49a167.png)

For example, see https://buildkite.com/bazel/intellij-plugin/builds/11433#9c280dbc-4c33-41b4-9b3f-967d6d028ee5, which tests intellij, but I only see one product in the log -

![image](https://user-images.githubusercontent.com/16676170/116310349-b9266e00-a75e-11eb-955b-575270993463.png)

I would have expected at the very least `intellij-latest` and `intellij-beta` to be tested and ideally also `intellij-canary`. I opened this issue specifically for intellij, but the other products may have a similar deficit.

**Comment by caseyduquettesc** [comment]
Dupe: https://github.com/bazelbuild/intellij/issues/2595
Fixed by: https://github.com/bazelbuild/intellij/pull/2596

**Comment by mai93** [comment]
Closing issue since pull request #2596 is merged.
