### ISSUE TITLE
Not able to install the Bazel for intellj 

### ISSUE THREAD

**Issue by thecoder8890** [bazelbuild/intellij#2580]
![image](https://user-images.githubusercontent.com/33773206/116804735-de402580-ab3e-11eb-93c3-545399cb7ddd.png)

Can you please suggest the appropriate version

**Comment by santoch** [comment]
Yes, please!  I desparately need this for CLion 2021.1
My company basically blocks software that has newer versions.  I can't downgrade my CLion.

**Comment by thecoder8890** [comment]
Which version is compatible, can you let me know if you are aware

**Comment by Kernald** [comment]
You can find the compatibility matrix for any plugin on Jetbrains' website: https://plugins.jetbrains.com/plugin/8609-bazel/versions/stable

**Comment by thecoder8890** [comment]
@Kernald  can you let me know if you know any compatible version of bazel plugin for 
![image](https://user-images.githubusercontent.com/33773206/117301492-5177cd80-ae98-11eb-89d2-cee927f8abba.png)

**Comment by chulkilee** [comment]
See #2406

You can see compatibilities with product version names at https://plugins.jetbrains.com/plugin/8609-bazel/versions
