### ISSUE TITLE
[ASWB] AndroidTestContext can't handle kotlin + java mixed targets

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/intellij#2613]
Original problem is described in https://github.com/bazelbuild/intellij/pull/2319

Recently [a fix for this issue](https://github.com/bazelbuild/intellij/commit/681770a1b369f153db3fb400ef457458d76b63e7#diff-c3327f7750ba399273adc2ebb8382c7e89fa4d773b8b9948df20561f0d73e2baR57-R62) has been merged. However, this only addressed the issue where the target itself only contains kotlin files. In the case of target containing both java and kotlin classes. This solution will not work correctly since the psi element for java classes will try to return a java test context while the class itself is inside a kotlin target context.

my original proposed fix still works, please consider adopting it  https://github.com/bazelbuild/intellij/pull/2319

**Comment by sgowroji** [comment]
Hello @ThomasCJY, Can you please respond on the [comments](https://github.com/bazelbuild/intellij/pull/2319#issuecomment-1237660597) mentioned in your  PR . Thanks!

**Comment by nkoroste** [comment]
This fix is still needed

**Comment by nkoroste** [comment]
awaiting-maintainer
