### ISSUE TITLE
[Docs] The bazel_binary configuration option is undocumented

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/intellij#2642]
https://ij.bazel.build currently lacks documentation for the project specific `bazel_binary` override that can be specified in your `bazelproject`. 

That section is defined here https://github.com/bazelbuild/intellij/blob/37486d833cd2cb06cff8146ad80c208a00378f4c/base/src/com/google/idea/blaze/base/projectview/section/sections/BazelBinarySection.java#L30

**Comment by mai93** [comment]
Thanks, a section was added for `bazel_binary` in the plugin documentation: https://ij.bazel.build/docs/project-views.html#bazel_binary
