### ISSUE TITLE
Error:Cannot run program "G:\mediapipe-master\BUILD.bazel" (in directory "G:\mediapipe"): CreateProcess error=2cannot find file

### ISSUE THREAD

**Issue by salier** [bazelbuild/intellij#2647]
Version information
AndroidStudio: 4.2.1
Platform: Windows 10 10.0
Bazel plugin: 2021.05.12.1.5
![image](https://user-images.githubusercontent.com/28691601/120134811-8231f500-c201-11eb-9e90-0f21c3950ad8.png)
I'm following the tutorial https://google.github.io/mediapipe/getting_started/android.html#option-2-build-with-bazel-in-android-studio
![image](https://user-images.githubusercontent.com/28691601/120134844-9118a780-c201-11eb-8d8f-534ec95c7247.png)
The SDK and NDK problems are not shown. However, they are still unable to compile normally
.It seems that the import failed.Log means missing file. But I didn't find this file missing.
![image](https://user-images.githubusercontent.com/28691601/120135075-0dab8600-c202-11eb-8a40-0691cb7c49be.png)

**Comment by sgowroji** [comment]
Hello @salier, Please follow the latest documentation from [here](https://google.github.io/mediapipe/getting_started/android#building-android-example-apps-with-bazel )
