### ISSUE TITLE
support IDEA in windows 10?

### ISSUE THREAD

**Issue by baisijian** [bazelbuild/intellij#2669]
support IDEA in windows 10?

**Comment by AlexeyGy** [comment]
Hey @baisijian,

unfortunately, we do not support Windows at this moment. Please refer to [the support matrix](https://ij.bazel.build/docs/bazel-support.html) for an overview of supported systems.

We understand that there is community interest in Windows support and are open to contributions (see [README.md](https://github.com/bazelbuild/intellij#readme)) but currently are not able to work on Windows support as we want to focus on keeping the open source version compatible with new IntelliJ versions and improve on core features.
