### ISSUE TITLE
Strange project view

### ISSUE THREAD

**Issue by MIOB** [bazelbuild/intellij#268]
1. Clone project https://github.com/MIOB/bazel-idea-plugin-usage-sample
2. Import it into idea. 
3. Expand items java8/src and java7 items

Actual: 
1. See two item "java" right under java8/src
2. java7/src/main/java is not marked as source folder.
 
<img width="356" alt="screen shot 2018-03-26 at 11 04 21" src="https://user-images.githubusercontent.com/932034/37914723-da19eeb8-30e5-11e8-95c9-058f0e2fdccf.png">

Expected: 
1. There should be way to distinguish two java items.
2. java7/src/main/java should be marked as source folder

**Comment by chaoren** [comment]
What do you have in your bazelproject file?
1. Make sure `//java7:java7` is covered by targets.
2. You could add a `test_sources` section to make `src/test/java` green.

**Comment by MIOB** [comment]
1. I have bazelproject file generated by IDEA, without any manual modifications. Right now it contains only one line in targets 
```
targets:
  //...:all
```
Manual adding java7 target does not help:
```
targets:
  //...:all
  //java7:java7
```
2. Thanks, it helps. But two java folder on the same level still looks strange, but atleast I could distinguish it.

**Comment by brendandouglas** [comment]
Closing, as it appears to be an upstream bug (see discussion in #196)

**Comment by chaoren** [comment]
> java7/src/main/java is not marked as source folder.

appears to be a separate issue.

**Comment by brendandouglas** [comment]
That's expected --  java7/src/main/java/sample/App.java has package string "java7.src.main.java.sample", so the source root is also the workspace root (which is a source folder).

If you change the package string to "src.main.java.sample", then 'java7' will be a source folder.
