### ISSUE TITLE
Packages with different java source level in one project

### ISSUE THREAD

**Issue by MIOB** [bazelbuild/intellij#269]
1. Clone project https://github.com/MIOB/bazel-idea-plugin-usage-sample
2. Import it into idea.
3. Uncomment code from java7/src/main/java/sample
4. Build project with command bazel build //...
5. See compilation error in console

Actual: No compilation errors in idea is shown
Expected: There should be errors shown idea about lambda usage in java7 package.

**Comment by chaoren** [comment]
Same deal as https://github.com/bazelbuild/intellij/issues/179
You can set one language level for the entire project, and it's unrelated to what you have for bazel.
`Project Structure -> Project -> Project language level`
