### ISSUE TITLE
Intellij IDEA crash when using bazel plugin

### ISSUE THREAD

**Issue by nrrajguru** [bazelbuild/intellij#2690]
On Mac I am running IntelliJ IDEA CE 2019.2.4 and bazelPlugin 2020.01.28.0.3
Bazel crashes (attaching screenshot below) and keeps giving following error when I sync my ws…anyone seen this issue before ?

Error:Cannot run program "bazel" (in directory "/Users/nrajguru/workspaces/nsxt5/nsx"): error=2, No such file or directory
Error:Could not run Bazel info

Above dir is my workspace…
[nrajguru@nrajguru-a02 ~/workspaces/nsxt5/nsx]# ls
xyz ... ...

[nrajguru@nrajguru-a02 ~/workspaces/nsxt5/nsx]# java -version
java version "1.8.0_271"

Intellij IDEA crash…attaching same		

I tried getting latest IDEA version but bazel plugin is not supported with latest versions. Please let me know if there is a workaround for above issue/crash.

Attachments: "Intellij IDEA Crash.png", "Intellij IDEA Crash2.png"

![Intellij IDEA Crash](https://user-images.githubusercontent.com/85895522/121929179-c808b600-ccf5-11eb-84b2-0c8c19f9d0d9.png)
![Intellij IDEA Crash2](https://user-images.githubusercontent.com/85895522/121929205-cccd6a00-ccf5-11eb-85e0-19eb788e1700.png)

**Comment by alice-ks** [comment]
IntelliJ 2019.2 is pretty old and we don't push plugin updates for that version anymore. Could you try IntelliJ 2020.2 or 2020.3? If you can only go to 2021.1, please use the beta channel for the plugin (see https://github.com/bazelbuild/intellij/issues/2406#issuecomment-854745034).

**Comment by nrrajguru** [comment]
Thanks yeah I would like to move to 2021.1.x but bazel plugin is not supported there. Anyway we can unlock bazel for IDEA 2021.x ?

![image](https://user-images.githubusercontent.com/85895522/122115661-910bd080-cdd9-11eb-8399-2aab86fe52a1.png)

**Comment by AlexeyGy** [comment]
Please check the aforementioned comment description, you need to subscribe to the beta channel.
