### ISSUE TITLE
CLion + VS 2019 - compile errors not shown

### ISSUE THREAD

**Issue by stefan1000** [bazelbuild/intellij#2694]
Just tried the basic "cpp" example from bazel.build and change something (identifier): when running CLion it shows that CL.exe failed, but it does not report the compile error in the hello-world.cc file.

Line 21 - change argc to argcx:
![CLion_screenshot](https://user-images.githubusercontent.com/2741523/122062528-c8857780-cdef-11eb-9206-a0523bcee7ae.png)

The only output as seen in the screenshot is a failure of CL.exe (Exit 2), but no info about the compile error. This is a fresh (evaluation) install of CLion, no other plugins.

Command: bazel.exe build --tool_tag=ijwb:CLion --keep_going --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=C:\Users\sbrabec\AppData\Roaming\JetBrains\CLion2020.3\plugins\clwb\aspect --output_groups=intellij-compile-cpp -- //examples/cpp:hello-world

I don't know if this is related, but:
- when started there is a message about "Warning:Unable to check compiler version for "C:\Program Files (x86)\Microsoft Visual Studio\2019...": ignoring unknown option '--version'
- derive_targets_from_directories does not work, it always results in "Error:Deriving targets from project directories failed.". I get the same error also on IntelliJ.

#### Version information
CLion: 2020.3.4
Platform: Windows 10 10.0
Bazel plugin: 2021.05.31.0.1
Bazel: 4.0.0
VisualStudio: 2019 16.9.6

**Comment by AlexeyGy** [comment]
We officially do not support Windows (see https://ij.bazel.build/docs/bazel-support.html). Please see/subscribe to #113 for the current state of Windows support and community contributions/forks on the topic
