### ISSUE TITLE
No ability to run custom main method

### ISSUE THREAD

**Issue by MIOB** [bazelbuild/intellij#270]
1. Clone project https://github.com/MIOB/bazel-idea-plugin-usage-sample
2. Import it into idea.
3. Go to java8/src/main/java/sample/java8/App.java
4. See run markers in gutter
5. Click to run marker 

Actual: Nothing here is shown

<img width="412" alt="screen shot 2018-03-26 at 11 18 39" src="https://user-images.githubusercontent.com/932034/37915410-7603fc3c-30e7-11e8-9696-5a292c0ba423.png">

Expected: There should be ability to run main method in this class.

**Comment by chaoren** [comment]
You need a `java_binary` target.

**Comment by MIOB** [comment]
Project could have a lot of utility main classes which are not designed to be run outside of IDE. For example in my project there is runnable class which generate ids. Also sometimes I write small temporary runnable classes for checking some hypothesis. It would be nice If I would have ability to run it from IDE without changing build scripts.

**Comment by ittaiz** [comment]
I suggest opening an issue with Bazel asking them to support an implicit
output of deploy jar for java_library for this purpose.
Don’t know if they’ll agree but it’s worth a shot.
I definitely agree it’s very comfortable.
For what it’s worth scala_library from rules_scala supports a java only
input set and does have this exact feature already implemented in the plugin

**Comment by peaceandserenity** [comment]
Why is this closed? There is no support for running custom main methods in IntelliJ. Can we reopen this. This is critical for adoption. The maven plugin for intellij automatically detects a main method. Can we get this in asap?

**Comment by brendandouglas** [comment]
It's not something we've previously viewed as critical, can you add some more information supporting this?

There are technical reasons why this has not been done (detailed above), but we've also seen very little demand for it, both internally and externally.

**Comment by Avarga954** [comment]
+1

**Comment by chetansingh1987** [comment]
i wished bazel was supported in eclipse.

**Comment by danielblazevski-square** [comment]
Just hit a small wall this this, we really ought to be able do a quick test run of some code via a custom main method.

**Comment by amalgawa** [comment]
Faced same problem in 2024, can we please fix this?
In intellij, we can debug things on thread level, and see the thread flow when we debug a program by directly running the main file. Same is not supported when we run via java_library.

**Comment by tpasternak** [comment]
@amalgawa thank you for reaching us. Is the case that you have a main file without a corresponding java_binary?

@jastice @agluszak can you please look into that?

Also, @amalgawa did you have a chance to try the new bazel plugin? https://github.com/JetBrains/hirschgarten/

**Comment by tpasternak** [comment]
ok, @amalgawa that's intentional, we explicitly disable many run configuration producers here https://github.com/bazelbuild/intellij/blob/2ae67dd02b4790660eff7543ee4835852d009417/java/src/com/google/idea/blaze/java/run/producers/NonBlazeProducerSuppressor.java#L25

Imo it's a good default because in most cases as it often prevents awkwardness rather than providing additional benefit.

However, each project is different, so if you would like to re-enable it, I would be happy to review a PR. Please only hide it behind a flag (or a projectview setting)
