### ISSUE TITLE
Can't stop bazel builds in CLion 

### ISSUE THREAD

**Issue by qq7te** [bazelbuild/intellij#2729]
I'm building in CLion 2020.3 using the latest bazel plugin (2021.05.31.0.1) , on ubuntu 20.04 with bazel 4.0.0

I can start a build, but once it starts, I can't stop it by pressing the stop button on the side of the Bazel Console.

If I find the process and kill it, then it works:), but would still prefer to use the button :slightly_smiling_face:

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
