### ISSUE TITLE
Bazel Plugin Syn Failed 

### ISSUE THREAD

**Issue by Kiru3014** [bazelbuild/intellij#2730]
#### Description of the issue. Please be specific.

![image](https://user-images.githubusercontent.com/36956488/123209959-f9943500-d4de-11eb-94db-0edf7335beb1.png)

Syncing project: Sync Working Set (full)...
Updating VCS...
Running Bazel info...
Command: C:\Users\Arsofin\Bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --

Sync finished
Sync failed

#### Version information
AndroidStudio: 4.2.1
Platform: Windows 10 10.0
Bazel plugin: 2021.05.31.0.1

**Comment by AlexeyGy** [comment]
We officially do not support Windows (see https://ij.bazel.build/docs/bazel-support.html). Please see/subscribe to #113 for the current state of Windows support and community contributions/forks on the topic
