### ISSUE TITLE
Android Studio Plugin (internal canary, under development) projects broken with Bazel@HEAD

### ISSUE THREAD

**Issue by comius** [bazelbuild/intellij#2732]
Example of breakage:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2078#9b88aa23-1c1b-49ab-a56f-f162d68fd24b

First breakage with this error message happened on 2021-05-18.

/cc @mai93

**Comment by alice-ks** [comment]
Thanks for the notice. We fixed the builds by now. They should be all green on your side now. If not, please re-open this issue.
