### ISSUE TITLE
Cannot compile "base" package when opening this workspace in intellij

### ISSUE THREAD

**Issue by th0masb** [bazelbuild/intellij#2735]
#### Description of the issue. Please be specific.

I would like to do some development work in this repository, specifically I would like to try and make some changes in the base package. In the readme it was recommended to use the ijwb/ijwb.bazelproject file for importing but this produces compilation errors during the build.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
 - Clone this repo
 - Checkout `tags/2021.04.07`
 - Open intellij and import bazel project using the `ijwb/ijwb.bazelproject`
 - The build fails for me ![image](https://user-images.githubusercontent.com/21277763/123288740-bef2c280-d507-11eb-86e8-a97a67b07a79.png) 
![image](https://user-images.githubusercontent.com/21277763/123289405-5c4df680-d508-11eb-8ac0-7e5ee1e97d84.png)

 - I delete the `//:ijwb_ue_tests` target from `ijwb.bazelproject` and resync and the build works.
 - Open `base/src/com/google/idea/blaze/base/actions/BlazeCompilerFileAction.java` and see 
![image](https://user-images.githubusercontent.com/21277763/123289095-0a0cd580-d508-11eb-965e-acf7ecc3ebdd.png)

where dependencies appear to be missing. I have tried playing around with the `ijwb.bazelproject` to no avail. Everything builds fine outside of intellij. Any ideas?

#### Version information
IdeaCommunity: 2020.3.4
Platform: Linux 5.11.0-7614-generic
Bazel plugin: 2021.05.12.1.5
Bazel: 4.1.0

**Comment by AlexeyGy** [comment]
This is on us. Please change your Bazel project (under Bazel/Project/Open Project View File) to have
```
build_flags:
  --define=ij_product=intellij-ue-latest
```

The issue is caused by the build flag having `intellij-latest` instead of `intellij-ue-latest`. During the build, this makes the SDK be the CE sdk which doesn't contain the proper libraries to run `//:ijwb_ue_tests`.

**Comment by th0masb** [comment]
> This is on us. Please change your Bazel project (under Bazel/Project/Open Project View File) to have
> 
> ```
> build_flags:
>   --define=ij_product=intellij-ue-latest
> ```
> 
> The issue is caused by the build flag having `intellij-latest` instead of `intellij-ue-latest`. During the build, this makes the SDK be the CE SDK which doesn't contain the proper libraries to run `//:ijwb_ue_tests`.

Thanks that fixes the first issue. I still see errors throughout the workspace relating to a missing dependency though like so: 
![image](https://user-images.githubusercontent.com/21277763/123331681-82d75600-d537-11eb-8e15-1681789efcc1.png)

from a class in the "base" package. Do you have any idea about why the plugin api cannot be resolved?
