### ISSUE TITLE
Executing test programs in the debugger unconditionally adds a "--gtest_color" flag

### ISSUE THREAD

**Issue by jwnimmer-tri** [bazelbuild/intellij#274]
This is a follow-up to #131.

CLion 2017.3.3.
Plug-in version 2018.01.29.0.0.

In CLion, select "Debug //some_package:myprogram" where `myprogram` is a `cc_binary` that uses `@gflags`, but not a `cc_test` with `@gtest`.  The console shows the message `ERROR: unknown command line flag 'gtest_color'` because IJWB is passing `--gtest_color` always during debugging, even if the program does not use googletest.

In #131 we fixed the `gunit_color` spelling to say `gtest_color`, but for non-googletest binaries `gtest_color` is unknown.

The only general work-around I know is to add a `DEFINE_bool(gtest_color, false, "");` temporarily to the source code.  ~I am also going to attempt a work-around by wrapping `tools/bazel` and stripping the argument, though that would be high friction for most users.~

As a resolution, I suggest setting `GTEST_COLOR=no` in the runtime environment, instead of passing a command-line flag.  This will disable color when gtest is in effect, but hopefully is mostly harmless otherwise.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
