### ISSUE TITLE
CLion tests are started with the wrong working directory in debug

### ISSUE THREAD

**Issue by ccciudatu** [bazelbuild/intellij#2745]
The working directory for tests started with `Debug '<target>'` is not the expected `.runfiles` folder, while using `Run '<target>'` works just fine.

**Comment by ccciudatu** [comment]
The trivial patch [here](https://github.com/bazelbuild/intellij/pull/2746) was tested with CLion `2020.3.4` on MacOs and it fixes the problem.

**Comment by alice-ks** [comment]
We merged the fix into the repository. Thanks for providing it!
