### ISSUE TITLE
Argument list is too long

### ISSUE THREAD

**Issue by Elentary** [bazelbuild/intellij#2756]
The issue #1081 is still relevant for us and should be reopened. Check out my comment via the link below
https://github.com/bazelbuild/intellij/issues/1081#issuecomment-871800109

**Comment by Elentary** [comment]
@jin @brendandouglas @AlexeyGy

**Comment by Elentary** [comment]
@mai93

**Comment by AlexeyGy** [comment]
Before we go down the route of a more sophisticated solution, can you try meddling with [ArgMaxShardSizeLimit](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/sync/sharding/ArgMaxShardSizeLimit.java). Increase either variable and see if this helps:
```
int envSizeBytes = 20000;
int targetStringSizeBytes = 150;
```
 1. build the plugin with the increased amounts. You can find info on how to build yourself in our [README](https://github.com/bazelbuild/intellij#an-intellij-plugin-for-bazel-projects). 
 2. Then load the new plugin into CLion.
 3. Remember to set `shard_sync: true` in your .blazeproject before building.
 
If it helps, we could A. make these variables configurable which would mitigate the issue in case it occurs again. We could also, B. make them more sensible to the actual environment but that would necessitate some testing. As a last step, C. reading from file sounds like a good idea as @brendandouglas mentioned but it needs a lot more code and has the potential to break things.

**Comment by kormide** [comment]
> I'm experiencing the same issue in IntelliJ Ultimate Edition when "Expand Sync to Working Set" is checked. The bazel query that gets run after the step
> 
> ```
> Querying targets building source files...
> ```
> 
> causes the argument list too long error. I tried adjusting `envSizeBytes` and `targetStringSizeBytes` and building from source, but that didn't fix the issue.

I found a solution to my specific problem. I have a workflow where I pull from a remote that isn't my origin remote into my master branch. It seems like this query was looking at everything that's changed between my local version of `master` and `origin/master`. By updating `origin/master` with the latest changes from the other remote, I no longer get the argument list too long error.

**Comment by sgowroji** [comment]
Thanks for the [workaround](https://github.com/bazelbuild/intellij/issues/2756#issuecomment-908507917) shared. @Elentary Are you still seeing the above error. Could you please respond. Thanks!

**Comment by mai93** [comment]
You can also try unchecking the "Bazel -> Sync -> Expand Sync to Working Set" option if the problematic query is related to the working set. Please feel free to reopen the issue if none of the workarounds resolved it.
