### ISSUE TITLE
scala sub-directories do no appear in project view in "hide Empty Middle Packages"

### ISSUE THREAD

**Issue by nadavwe** [bazelbuild/intellij#276]
I just upgraded my intellij to 2018.01 and my bazel plugin to 2018.01.02.0.1.
I see that all of my code sources are gone from project view!
each directory with main/scala or test/scala does not appear.
main/resources and test/resources do appear.

Thanks!

@ittaiz

**Comment by johnynek** [comment]
Cc @gkk-stripe @andygscott

**Comment by nadavwe** [comment]
Hey @chaoren,
did you see something similar?
what am I doing wrong?
Thanks...

**Comment by nadavwe** [comment]
due to @natansil advice i removed the "hide Empty Middle Packages" checkbox and now I can see the files.
so this is a minor issue.

**Comment by brendandouglas** [comment]
Closing as a dupe of #268. It is something I've been meaning to fix -- though as you found, there is a workaround.
