### ISSUE TITLE
Error:Deriving targets from project directories failed.

### ISSUE THREAD

**Issue by Laxiyan** [bazelbuild/intellij#2775]
#### Version information
AndroidStudio: 4.2.2
Platform: Windows 10 10.0
Bazel plugin: 2021.06.15.0.4
Bazel: 5.0.0

**Comment by sgowroji** [comment]
Hello @Laxiyan, Could you please elaborate your issue with complete details and also with minimal steps to reproduce the above issue.

**Comment by mai93** [comment]
Closing this issue. If you still see it with newer plugin versions, please reopen with more information on how to reproduce it.
