### ISSUE TITLE
Bazel plugin support for Android Studio 3.1

### ISSUE THREAD

**Issue by oferb** [bazelbuild/intellij#278]
### Description of the problem / feature request:

Bazel plugin is not supported in Android Studio 3.1 ([released March 26](https://android-developers.googleblog.com/2018/03/android-studio-3-1.html)).

![image](https://user-images.githubusercontent.com/5137671/38198793-d9b74388-3696-11e8-8a2c-1952d4dc8750.png)

**Comment by jin** [comment]
cc @brendandouglas @chaoren

**Comment by brendandouglas** [comment]
We don't have any plans to support 3.1, which has no support for internal workflows. Instead, we'll likely skip straight to 3.2, which does.

**Comment by oferb** [comment]
Ok, good to know. Thanks!

**Comment by brendandouglas** [comment]
The latest AS bazel plugin was built against 3.2 (for future reference, you can check the exact list of supported versions on the JetBrains plugin repo: https://plugins.jetbrains.com/plugin/9185-bazel).

That particular beta build of 3.2 had some major problems (unrelated to the bazel plugin), but it should work just as well with the latest beta build.
