### ISSUE TITLE
Use java provider rather than testing for old-style info

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/intellij#279]
We would like to adopt providers in the scala rules, see https://github.com/bazelbuild/rules_scala/issues/450

But we don't want to break intellij integration so we have this issue to track how this plugin depends on the scala rules:
https://github.com/bazelbuild/rules_scala/issues/466

It seems like here
https://github.com/bazelbuild/intellij/blob/master/aspect/intellij_info_impl.bzl#L408

We expect there to be a java-like provider accessible via `.scala`. Why can we not just access the java provider directly as in:
https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L341

Where you use
```python
if java_common.provider in some_rule:
  some_rule[java_common]
```

Is there any known reason this would not work?

cc @ittaiz @gkk-stripe

**Comment by brendandouglas** [comment]
I believe this is just a historical artifact -- when the scala rules were first written, java_common.provider didn't expose the information required by our aspect (e.g. jdeps, output jars).

I don't know of any remaining issues though, so if you move to java_common.provider and remove .scala entirely, the plugin should continue working as is (we fall back to returning java_common.provider if the old-style 'scala' provider isn't present).

**Comment by johnynek** [comment]
@brendandouglas we do have a java provider, and java rules can depend on scala, but @ittaiz says that is still not enough here:
https://github.com/bazelbuild/rules_scala/issues/466#issuecomment-378026644

that java_provider still does not give you all the information you want.

**Comment by ittaiz** [comment]
Actually Brendan is the one who said it a while ago.
Brendan,
What does the plugin need?

**Comment by johnynek** [comment]
The comment says:

```
  # java_common.provider is a work in progress. It will soon expose the information
  # we require (e.g. outputs jars, jdeps), but does not yet do so.
```

I don’t know if that statement is still accurate. Would be nice to link to any bazel issues to track and get that comment removed hopefully soon.

We want to use only modern providers, but we can’t afford a regression in intellij support.

**Comment by ittaiz** [comment]
I agree.
Brendan,
Can you say what the plugin needs exactly? Take into account we still
haven’t moved to the new richer API of JavaInfo (which for example has
source jars).
Please remember that currently we pass None as source jars via the scala
attribute

**Comment by johnynek** [comment]
My read of the docs here suggest that the providers have everything needed and the comment may no longer be accurate:

https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html

**Comment by ittaiz** [comment]
The docs aren’t good enough I’m afraid since they relate to master and not
something that is released and I’m also not sure we can move to the latest
constructor

**Comment by johnynek** [comment]
Imagine a world where the docs were ✨versioned✨

**Comment by ittaiz** [comment]
There’s actually a ticket about this 😉

**Comment by brendandouglas** [comment]
The API already has everything you'll need for scala. There are technical issues around edge cases internally, but I don't think these are an issue here.

That comment in the aspect is certainly no longer up to date, though we're still not ready to move from 'java' to 'java_common.provider'

**Comment by brendandouglas** [comment]
The comment in the aspect has been removed, so AFACT there's nothing else actionable on the bazel plugin side of things.

We'll eventually preferentially consume JavaInfo, rather than the old-style 'java' provider, but for now we already support both.
