### ISSUE TITLE
Remote bazel build + bazel test is not supported in GoLand

### ISSUE THREAD

**Issue by nishantroy** [bazelbuild/intellij#2798]
I develop on a Mac, but my usual testing flow is on a remote machine. I write my code locally, rsync it to my remote machine, SSH to the remote machine, and run my commands such as `bazel test //my_project/package1/...` through CLI on the remote host.

I would like to be able to use the bazelbuild plugin to run these targets remotely through GoLand.

**Comment by nishantroy** [comment]
@AlexeyGy I noticed you've helped with quite a few of the issues in the past, would you be able to take a look at this? Thanks!

**Comment by AlexeyGy** [comment]
The easiest way would be to create a Bazel wrapper and just tunnel all commands to the other machine. 

Getting a debugger would be a bit harder but should be possible via [ssh-port-forwarding](https://www.ssh.com/academy/ssh/tunneling/example):
```
    ssh -L 80:intra.example.com:80 gw.example.com
```

The solution described above should be able to cover some basic use-cases.

**Comment by sgowroji** [comment]
Hello @nishantroy, Are you still looking support on the above issue and did it [helped](https://github.com/bazelbuild/intellij/issues/2798#issuecomment-929590965). Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
