### ISSUE TITLE
plugin not shown in settings.

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/intellij#28]
I can only find the BUILD formatter.

I have no repostories configured, so I assume I get the default JetBrains one.

i'm running 2016.1.3, build 145.1617

**Comment by hanwen** [comment]
looks like a version issue; with a newer IJ it does work. Maybe you can mention this on the webpage?

**Comment by brendandouglas** [comment]
Thanks, we'll update the website to mention the version restrictions.

The definitive compatibility notes are available at JetBrains' plugin repo:
https://plugins.jetbrains.com/plugin/8609

**Comment by hanwen** [comment]
btw my compliments to you & tom; the plugin looks pretty smooth.

**Comment by brendandouglas** [comment]
Thanks!
