### ISSUE TITLE
Import C++ project failure

### ISSUE THREAD

**Issue by tony-shi** [bazelbuild/intellij#281]
I have trying to import C++ project in Clion with version as 2017.3.4. However, every time i try to import the project it always gives such s failure as below in the Bazel Console.
Syncing project: Full Sync (full)...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel  info --tool_tag=ijwb:CLion --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --

==== TIMING REPORT ====

Sync: 9ms
    BazelInfo: 6ms

Timing summary:

BlazeInvocation: 6ms
Sync failed

Also i got the error in Blaze Problems like this:
Error:Cannot run program "/usr/local/bin/bazel " (in directory "/Users/username/hello-world/stand-alone-bazel-project"): error=2, No such file or directory

I have make sure that i can manually run the bazel build in terminal. Any suggestion for this? Tks a lot.

**Comment by brendandouglas** [comment]
Does the '/usr/local/bin/bazel' file exist?

**Comment by chaoren** [comment]
Where's your bazel binary located? Try `$ which bazel`.

**Comment by jvoung** [comment]
If that's the exact error message, it looks like there is an extra space at the end of the bazel binary location: "/usr/local/bin/bazel " instead of "/usr/local/bin/bazel". Can you try editing the location in settings to remove the extra space?

**Comment by tony-shi** [comment]
Tks bros @jvoung. I have re-config from IDE other settings. This time i have select the bazel path with IDE UI instead of typing. It must be some kind miss typing makes this happen. It's my fault. Tks a lot!!

**Comment by chaoren** [comment]
We could probably trim that field too.
