### ISSUE TITLE
Android Studio Arctic Fox support

### ISSUE THREAD

**Issue by geaden** [bazelbuild/intellij#2823]
Unable to install Bazel plugin in Android Studio Arctic Fox with the following error:

```
Plugin 'Bazel' (version '2021.07.13.0.1') is not compatible with the current version of the IDE, because it requires build 211.7628 or newer but the current build is AI-203.7717.56
```

**Comment by geaden** [comment]
I was able to use 2021.06.15.0.4 by manually installing it from plugin page https://plugins.jetbrains.com/plugin/8609-bazel/versions/stable. However sync fails with 

```
Error:(16, -1) Could not parse: 'android_sdk_platform: "android-29"'
```

**Comment by geaden** [comment]
Turned out I used IntelliJ IDEA plugin, but Android Studio Plugins are in different location https://plugins.jetbrains.com/plugin/8609-bazel/versions/stable. And there is no supported version for AI-203.7717.56

**Comment by Hiteshpatel10** [comment]
Not able to use material theme and github login failed using credential and token

**Comment by nikunjparadva** [comment]
@Hiteshpatel10 
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037

**Comment by geaden** [comment]
> Not able to use material theme and github login failed using credential and token

@Hiteshpatel10 Is it related to Bazel plugin in Android Studio Arctic Fox? Did you manage to use Bazel plugin in Android Studio Arctic Fox?

**Comment by alice-ks** [comment]
We already adjusted the plugin code to work with Android Studio 2020.3. So far, we haven't built and pushed a plugin version for it yet. That's planned for the current release cycle (-> `android-studio-oss-stable` is set to 2020.3 right now), which should result in an upload in ~2 weeks.

If you don't want to wait that long, you can check out the code of this repository and build it for Android Studio according to the build instructions of the README file.

**Comment by AlexeyGy** [comment]
We have a version [released for 203 (Arctic Fox support)](https://plugins.jetbrains.com/plugin/9185-bazel/versions/stable) as of today.
