### ISSUE TITLE
2021.07.27.1.0-api-version-212 doesn't support 2021.2

### ISSUE THREAD

**Issue by jameslan** [bazelbuild/intellij#2843]
The version of my IntelliJ is 212.4746.92, while 2021.07.27.1.0-api-version-212 supports 212.4638—212.4638.* only.

**Comment by AlexeyGy** [comment]
Hey @jameslan. This was a bug in our export scripts which we fixed, we now always support up to ${api_prefix}.*, e.g., 212.*. For example, https://plugins.jetbrains.com/plugin/8609-bazel/versions/beta/133609.
