### ISSUE TITLE
 Cannot run program "bazel".. No such file or directory 

### ISSUE THREAD

**Issue by oferb** [bazelbuild/intellij#285]
Hi,
I'm trying to import a Bazel project in Android Studio, and am getting this error:
`Cannot run program "bazel" (in directory "/home/oferb/devel/hasadna"): error=2, No such file or directory `
Full log: https://pastebin.com/eDMpnK6C

Running `bazel` from the terminal works.

To fix this, I set Settings > Other Settings > Bazel Settings = `/path/to/my/bazel` in Android Studio.

This seems related to https://github.com/bazelbuild/intellij/issues/88, but opening a new issue since the logs changed, and for succinctness and clarity.

**Comment by brendandouglas** [comment]
I don't think there's much we can do on the plugin side. The '/path/to/my/bazel' isn't accessible from either the directory "/home/oferb/devel/hasadna" or the environment from which the IDE was launched.
