### ISSUE TITLE
Working directory support

### ISSUE THREAD

**Issue by zhangleipro** [bazelbuild/intellij#2855]
Could you provide working directory options in the Run/Debug Configurations ?

**Comment by AlexeyGy** [comment]
I am assuming that you would want to have an option to change outputRoot as per [Bazel guide](https://docs.bazel.build/versions/main/guide.html) and this thread on [the Bazel page](https://github.com/bazelbuild/bazel/issues/4248). Did I get that right?

**Comment by zhangleipro** [comment]
No, what I want to change is the working directory when debugging, so that the running program can read the config file or write the log file in this path, just like the "Working directory" option in the CMake's Run/Debug Configurations panel.

"platform settings -w path" in lldb has the same effect, but it needs to be set before the program is run, Clion does not support this.

**Comment by sgowroji** [comment]
Hello @zhangleipro, Could you please respond if you are still looking support on the above issue. Thanks!

**Comment by kshyanashree** [comment]
Closing this issue as there is no significant update from long duration. Please feel free to reopen if the above issue still exists. Thank you!

**Comment by Malinskiy** [comment]
@kshyanashree 

Not sure what kind of update you're looking for, is there an option now in the plugin to specify workdir for running bazel run?

I understand the problem is likely rooted in the bazel itself and not the plugin, but the UX of this feature starts in the UI of the plugin.

Please reopen
