### ISSUE TITLE
Register *.sky and *.star IDE file associations as "Bazel BUILD Language"

### ISSUE THREAD

**Issue by keithl-stripe** [bazelbuild/intellij#2863]
Our company uses Starlark code stored in `.sky` files to generate configuration files. (We do not use Bazel for this - just pure Starlark.) Unfortunately everyone who edits these files needs to know how to open them as _Bazel BUILD Language_ in IntelliJ.

It would be a pretty simple change to [BuildSystemProvider](https://github.com/bazelbuild/intellij/blob/2fee2ddf95842c10581dde8ee85bc2a01c44dce2/base/src/com/google/idea/blaze/base/bazel/BuildSystemProvider.java#L169).

NOTE: I'm not actually sure this is appropriate. It's possible that there are some inspections or internal indexing processes that would be affected negatively by this.

**Comment by AlexeyGy** [comment]
We can discuss this internally,

as a mitigation, the easiest way to have this as default for your users, would be to add an entry like
```
 <mapping ext="sky" type="BUILD" />
```
to filetypes.xml which is located at
```
$HOME/.config/JetBrains/IntelliJIdea2021.1/options/filetypes.xml
```
on linux and for IntelliJ 2021.1. Which is equivalent to making the association manually when opening a file or under Settings and can be done by a config script.

**Comment by AlexeyGy** [comment]
@keithl-stripe We've discussed this internally and decided that it's safe to go ahead with associating `*.sky` and `*.star`. Expect the change to arrive in one of the following releases.

**Comment by keithl-stripe** [comment]
Cool!! Thanks for considering it!

**Comment by AlexeyGy** [comment]
This has now been in the plugin for a couple of releases. Closing the bug @keithl-stripe .

**Comment by keithl-stripe** [comment]
Cool! We haven't upgraded yet but will try it out as soon as I can. Thank you!
