### ISSUE TITLE
Debugging Error: Process finished with exit code 130 (interrupted by signal 2: SIGINT)

### ISSUE THREAD

**Issue by fjaccarino** [bazelbuild/intellij#2875]
Tested with a "hello world" example.  Launching the debug configuration crashes but the run configuration is fine.  Is this a known issue?  Something I'm doing wrong?
Thanks in advance

Error
`Process finished with exit code 130 (interrupted by signal 2: SIGINT)`

OS
```
Macos Big Sur
Version 11.5.1
```

IDE
```
PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96, built on July 27, 2021
```

Plugin
`Bazel 2021.08.10.0.2-api-version-211`

**Comment by jameslan** [comment]
Since you are using 2021.2, you need the plugin this version, i.e. version ending with `-api-version-212`. Check the beta channel of the plugins.

**Comment by phil-osk** [comment]
I have the same issue on Ubuntu 21.04, with

PyCharm 2021.2.2 (Professional Edition)
Build #PY-212.5284.44, built on September 14, 2021

and

Bazel 2021.09.21.0.1-api-version-212

**Comment by sgowroji** [comment]
Hello @fjaccarino, Could you please respond if you are still seeing the above issue with latest stable versions of pycharm and bazel plugin. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
