### ISSUE TITLE
The beta IJ Plugin is a chunky boi, an absolute unit, and a just a tad bloated

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/intellij#2896]
The current stable IJ plugin (`Bazel 2021.08.10.0.2-api-version-211`) weighs in at 23.04MB. The current beta (`Bazel 2021.08.10.0.2-api-version-212`) is a hefty 172.22 MB. At some point, the plugin put on a ton of bloat.

Unzipping the plugin shows:

```shell
Archive:  bazel-bin/ijwb/ijwb_bazel.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       35  01-01-2000 00:00   ijwb/aspect/WORKSPACE
     2876  01-01-2000 00:00   ijwb/aspect/artifacts.bzl
     5073  01-01-2000 00:00   ijwb/aspect/fast_build_info.bzl
     1569  01-01-2000 00:00   ijwb/aspect/intellij_info_bundled.bzl
    46856  01-01-2000 00:00   ijwb/aspect/intellij_info_impl.bzl
     1113  01-01-2000 00:00   ijwb/aspect/java_classpath.bzl
     3907  01-01-2000 00:00   ijwb/aspect/make_variables.bzl
     1054  01-01-2000 00:00   ijwb/aspect/BUILD.bazel
      324  01-01-2000 00:00   ijwb/aspect/tools/CreateAar.jar
    12371  01-01-2000 00:00   ijwb/aspect/tools/CreateAar
 92552857  01-01-2000 00:00   ijwb/aspect/tools/JarFilter_deploy.jar
 92552861  01-01-2000 00:00   ijwb/aspect/tools/PackageParser_deploy.jar
     8838  01-01-2000 00:00   ijwb/lib/libfast_build_javac.jar
  9558952  01-01-2000 00:00   ijwb/lib/ijwb_bazel.jar
---------                     -------
194748686                     14 files
```

That suggests that there's a transitive dep of `JarFilter` and `PackageParser` that's extraordinarily large. 

While the plugin still functions as it should, this large size, and the rate of growth, seems unexpected.

**Comment by alice-ks** [comment]
Thanks for noticing and reporting this. If you figure out what to change in the dependencies specification, please let us know.

**Comment by chris-bannister-privitar** [comment]
@intellij_ue_2021_2//:lib/3rd-party.jar now depends on rocksdb which has the following files in the jar

```
 10474648  00-00-1980 00:00   librocksdbjni-linux32-musl.so
  9379619  00-00-1980 00:00   librocksdbjni-linux32.so
 10509808  00-00-1980 00:00   librocksdbjni-linux64-musl.so
 10354808  00-00-1980 00:00   librocksdbjni-linux64.so
  7025000  00-00-1980 00:00   librocksdbjni-osx.jnilib
```

These are included in both the jars

**Comment by alice-ks** [comment]
Chris, thanks for digging in. A dependency on `3rd-party.jar` is necessary to pull in the right version of Guava (= use the Guava version which comes along with the IntelliJ platform). See the setup in the BUILD files (e.g. [here](https://github.com/bazelbuild/intellij/blob/fd0ed00c60f1e83e1e6fd52f17173de580c7de12/intellij_platform_sdk/BUILD.ue213#L30)). Some distributions like CLion also pull in the library for jsr305 from `3rd-party.jar` (see [here](https://github.com/bazelbuild/intellij/blob/44e6ed9f51d3678065a17c267a592c89e5265abc/intellij_platform_sdk/BUILD.clion213#L37)).

In the past, there were separate libraries in the IntelliJ platform (e.g. the 2020.3 plugin [referred](https://github.com/bazelbuild/intellij/blob/82403d762a7da9f69a7db51c60a1cd26b8fc65e5/intellij_platform_sdk/BUILD.ue203#L32) to just the Guava library). If we want to reduce the size of the plugin again, it seems that we need to figure out a different solution.

**Comment by sgowroji** [comment]
Hello @shs96c, Are you still looking support on the above issue with the latest releases. Thanks!
