### ISSUE TITLE
IntelliJ IDEA Java debugger does not automatically attach

### ISSUE THREAD

**Issue by Mrmann87** [bazelbuild/intellij#2905]
When debugging a binary or test in IntelliJ IDEA, the debugger does not automatically attach to the remote debugging session and will continue to run while waiting for a debugger to be attached.

The Console tab contains the following log lines:
```
/usr/local/bin/bazel test --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no --runs_per_test=1 --flaky_test_attempts=1 --build_event_binary_file=/var/folders/lw/j7k1638j7qzbrytssdwx1pgc0000gp/T/intellij-bep-50ce87e7-83ff-4d69-a88a-80c2118c7336 --nobuild_event_binary_file_path_conversion --test_filter=demo.DemoTest# --java_debug --test_arg=--wrapper_script_flag=--debug=5005 -- //examples/bazel:test
Testing started at 10:29 AM ...
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
Loading: 
Loading: 0 packages loaded
Analyzing: target //examples/bazel:test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //examples/bazel:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Listening for transport dt_socket at address: 5005
[1 / 2] Testing //examples/bazel:test; 1s darwin-sandbox
[1 / 2] Testing //examples/bazel:test; 21s darwin-sandbox
[1 / 2] Testing //examples/bazel:test; 45s darwin-sandbox
```

![Screen Shot 2021-09-03 at 10 30 11 AM](https://user-images.githubusercontent.com/1608111/132044887-333e9ccb-874b-48eb-8e65-60c4ce8cae0c.png)

The Debugger tab has the informational message:
```
Connecting to target VM, address: 'localhost:5005', transport: 'socket
```
![Screen Shot 2021-09-03 at 10 24 45 AM](https://user-images.githubusercontent.com/1608111/132044309-90b73597-eadc-4efd-b3b1-ae6bbd5ede76.png)

Manually attaching a remote debugging session to `localhost:5005` does cause the test to proceed as expected, however, this results in stepping through the code in a new debugger tab, rather than the one containing the test output which is a fairly awkward experience.

![Screen Shot 2021-09-03 at 10 31 21 AM](https://user-images.githubusercontent.com/1608111/132045015-6948dd3f-4f81-4f03-b380-a342b1da7632.png)

IntelliJ IDEA 2021.2 Ultimate Edition (Build #IU-212.4746.92)
Bazel Plugin 2021.08.10.0.2-api-version-212
OSX 10.14.6

**Comment by sgowroji** [comment]
Hello @Mrmann87, Could you please verify the above with the latest Intellij and bazel plugin. Thanks!

**Comment by Mrmann87** [comment]
@sgowroji This appears to be fixed!
