### ISSUE TITLE
IntelliJ should support android workspaces

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/intellij#2912]
IntelliJ (at least Ultimate) has pretty good Android support. Using it with a `workspace_type` set to `java` disables this integration, making it impossible to open e.g. the logcat window.

Is there any reason why IntelliJ doesn't support `android` as a `workspace_type`?

**Comment by alice-ks** [comment]
The version of this plugin for Android Studio supports `android` as `workspace_type`. Isn't it possible for you to use Android Studio instead of IntelliJ?

**Comment by Kernald** [comment]
While it indeed works, having an IntelliJ Ultimate licence and working on both Android and back-end, using a single IDE would be much easier than having to sync the settings between the two (and potentially multiple computers... especially when IntelliJ Ultimate comes with a settings sync plugin) etc. It's definitely not a major blocker, but it would be quite nice to unlock.

**Comment by alice-ks** [comment]
Changing this would be quite some work as all Android-related parts of the code are currently only bundled when the plugin is built for Android Studio. In addition, checks which currently test for Android Studio would need to additionally detect the Android plugin instead.

**Comment by Kernald** [comment]
Would there be any objection to a PR doing this? I definitely don't have the bandwidth to work on that at the moment, just trying to get a sense of whether that something you'd want to have at all (even without having the resources for such a low priority item) or not.

**Comment by alice-ks** [comment]
I'd expect that a lot of classes would need to be moved/changed, which would also affect our internal usages of these classes. So, this wouldn't be a PR we could easily merge and I don't see us having the resources to do the necessary internal changes.

**Comment by idanakav** [comment]
I'd like to chime in and add a few more use cases for supporting android workspace in IntelliJ:

- Android Studio stable releases are based on approximately year lagging IntelliJ version
- Gateway/remote dev requires IntelliJ Ulitmate, thus will not support AS

A Gradle Android project in IntelliJ along with the Android plugin has almost feature parity with Android Studio, it would be great if this could be similar with Bazel.

**Comment by idanakav** [comment]
> > I'd like to chime in and add a few more use cases for supporting android workspace in IntelliJ:
> > 
> > * Android Studio stable releases are based on approximately year lagging IntelliJ version
> 
> Is that true? Canary versions of Android Studio are rapidly catching up to IntelliJ.

Canary, yes, but not stable, latest stable as for now is Dolphin which is based on IJ 2021.3.1.
