### ISSUE TITLE
plugin built from source is incompatible

### ISSUE THREAD

**Issue by sheldonneuberger** [bazelbuild/intellij#294]
I built the plugin with `bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-latest` and then tried to install ijwb_bazel.zip to Android Studio 3.0.1 but it gives an error: `Plugin 'Bazel' is incompatible with this installation`. I also tried with Studio 3.2 C11.

Git hash I'm building: b0ed3e65ccac1b61640114ce19cf25faaf92cd6d.

**Comment by chaoren** [comment]
> `--define=ij_product=intellij-latest`

You want `--define=ij_product=android-studio-latest`.

**Comment by sheldonneuberger** [comment]
Ran `bazel build //ijwb:ijwb_bazel_zip --define=ij_product=android-studio-latest` and got error:

```
ERROR: /Users/sheldon.neuberger/Snapchat/Dev/intellij/third_party/scala/BUILD:10:15: Configurable attribute "exports" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest
ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: 

/Users/sheldon.neuberger/Snapchat/Dev/intellij/third_party/scala/BUILD:10:15: Configurable attribute "exports" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest
INFO: Elapsed time: 0.163s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
