### ISSUE TITLE
gazelle:resolve mapping is "red" in Intellij

### ISSUE THREAD

**Issue by Enrico2** [bazelbuild/intellij#2953]
[Gazelle directives](https://github.com/bazelbuild/bazel-gazelle#directives)

I was specifically looking into `proto`, e.g.
```
# gazelle:resolve proto foo/foo.proto //foo:foo_proto
```
If I open a .proto file in IntelliJ that contains 
```proto
import "foo/foo.proto";
```
The path will be red and all protobuf tooling won't work as expected.

This is especially painful when the imported proto comes from another repository that is brought into the bazel workspace via a gazelle integration.

I'm not sure if this is an issue with resolving other types as well, though I image it may be.

**Comment by sgowroji** [comment]
Hello @Enrico2, Could you please verify the issue with the latest bazel plugin versions. Thanks!

**Comment by Enrico2** [comment]
Apologies, unfortunately I can't, I no longer work with that repository.

**Comment by sgowroji** [comment]
Thanks for update. We are closing this issue now. Please feel free to reopen if you or anybody able to reproduce it.
