### ISSUE TITLE
How do I enable the plugin for an existing project?

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/intellij#2957]
I am porting an existing repository's build system to Bazel. I already have an IntelliJ project set up for this repository, with many project customizations that I don't want to lose. How do I enable the Bazel plugin for this project? I've read [Importing a Project](https://ij.bazel.build/docs/import-project.html), but this seems to generate a new IntelliJ project from scratch, discarding all my customizations.

**Comment by sgowroji** [comment]
Hi @jfirebaugh, Do you still looking support on the above issue. Thanks!

**Comment by jfirebaugh** [comment]
Yes, if possible. Thank you.

**Comment by mai93** [comment]
Can you use the `.ijwb/.idea` directory to transfer these customization to the project created by the plugin? 

([useful link about the configuration subdirectory](https://blog.bazel.build/2019/09/29/intellij-bazel-sync.html#intellij-configuration-subdirectory))
