### ISSUE TITLE
Import project view should have the BUILD file first and default

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#3]
I started out with the plugin by trying to import bazel (had problems which I might open a different ticket for) and during the course of that I somehow chose "from scratch" in the import. I don't remember if the plugin defaulted to it or I chose it but I think that even if I chose it then it's related to the order of options. 
I want to suggest making the import from BUILD file the first option and be it checked by default since it sounds to me like that is the main use-case of importing. I'd also move the from scratch option to the bottom of the list since that sounds the most advanced.

Additionally the plugin remembers what you chose last and will default to that, maybe it shouldn't and should default to BUILD file anytime so that even if you make a mistake one time you aren't pushed to it over and over

**Comment by ittaiz** [comment]
Hi,
What do you think about this?

**Comment by brendandouglas** [comment]
Reordering the options and defaulting to 'generate from BUILD file' sounds good -- we'll look into it.

Remembering the last choice seems beneficial -- remembering a previous mistake should only be an issue for new users, whereas existing users can benefit from fewer clicks for whatever their standard workflow is.

My expectation would be that first-time users would almost always choose 'generate from BUILD file', but frequent users, or users with more complex projects, would benefit from using .bazelproject files checked into source code (e.g. as with this project, where we have a .bazelproject file for each plugin API).

**Comment by ittaiz** [comment]
@brendandouglas sounds like you can close this one since you disagree with my suggestion and see other user stories. That might be unfortunate but of course your prerogative :)

**Comment by brendandouglas** [comment]
OK, sounds good.
