### ISSUE TITLE
Blaze references within the bazel plugin

### ISSUE THREAD

**Issue by patrickwmcgee** [bazelbuild/intellij#30]
While using the: 
`Intellij with Bazel` plugin v `1.10.2`
![image](https://cloud.githubusercontent.com/assets/1474750/20009355/92922646-a27a-11e6-885c-005696c62093.png)

I noticed that there were some small references to `Blaze` within the configuration settings in `Intellij`. I know this isn't a pressing issue but I would just like to point it out.
![image](https://cloud.githubusercontent.com/assets/1474750/20009322/6d548a7c-a27a-11e6-864a-bcbb4d6869a4.png)

**Comment by brendandouglas** [comment]
Thanks for pointing this out. We've fixed it for the next release.

**Comment by patrickwmcgee** [comment]
Thanks for the quick response time!
