### ISSUE TITLE
Bazel console always scrolls

### ISSUE THREAD

**Issue by yaelz** [bazelbuild/intellij#301]
When running Bazel in Intellij and trying to follow a specific error while bazel is still running, the scrolling doesn’t stop even though “scroll to the end” is not checked. 

![image](https://user-images.githubusercontent.com/8150588/39525644-38a54dfe-4e25-11e8-835a-fe0c71f8db9d.png)

**Comment by brendandouglas** [comment]
I haven't been able to reproduce this. It could be environment specific (e.g. broken on macs, or similar).

Anther possibility: it has a limited buffer, and will start dropping lines from the top (and hence scrolling) if it reaches that maximum size. Could this be what is happening?

**Comment by brendandouglas** [comment]
Closing as we haven't been able to reproduce. Please let us know if it's not dropping lines from the top.
