### ISSUE TITLE
Doesn't work when username contains a space

### ISSUE THREAD

**Issue by maxgerhardt** [bazelbuild/intellij#3037]
#### Description of the issue. Please be specific.

I'm trying to run basel in CLion while being guilty of the crime of having a space in my username, `Max Gerhardt`. This username is controlled by my organization and I can't change it.

I tried importing the [simplest possible example project](https://github.com/bazelbuild/examples/tree/main/cpp-tutorial/stage1) but I immediately ran into the error 

```
WARNING: Output user root "C:/Users/Max Gerhardt/_bazel_Max Gerhardt" contains a space. This will probably break the build. You should set a different --output_user_root.
ERROR: bazel does not currently work properly from paths containing spaces (C:/users/max gerhardt/downloads/examples-main/cpp-tutorial/stage1).
Sync finished
Sync failed
```
with it. Okay, I thought, I musn't have Bazel and the project directory in a path containing spaces -- no problem.

I relocated `bazel.exe` and the example project to a path without spaces, `C:\dev`. Now it can't possibly fail.

Well, it still does. Creating the project anew (to prevent any caching issues) and syncing the project gives

```
Syncing project: Full Sync (full)...
Updating VCS...
Running Bazel info...
Command: C:\dev\bazel.exe info --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no --

WARNING: Output user root "C:/Users/Max Gerhardt/_bazel_Max Gerhardt" contains a space. This will probably break the build. You should set a different --output_user_root.
Computing VCS working set...
Querying targets in project directories...
Command: C:\dev\bazel.exe query --tool_tag=ijwb:CLion --output=label_kind --keep_going "attr(\"tags\", \"^((?!manual).)*$\", //main/...:all)" --

Sync finished
Sync failed
```

Even tough Bazel is in `C:\dev\bazel.exe` now, it (I assume it's `bazel.exe` and not the extension) still creates the folder `C:\Users\Max Gerhardt\_bazel_Max Gerhardt` (which contains two spaces) and tries to.. redirect the output in there? 

The output hints that the `--output_user_root` option can be used to possibly change the folder and make it work. Can the extension do that? Or, can it be tested with a simple command that I can execute whether that *would* work? 

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

* Download https://github.com/bazelbuild/examples/tree/main/cpp-tutorial/stage1 to `C:\dev`
* Download https://github.com/bazelbuild/bazel/releases/download/6.0.0-pre.20211019.1/bazel-6.0.0-pre.20211019.1-windows-x86_64.zip to `C:\dev`
* Use File -> Import Bazel Project -> Workspace: "C:\dev\stage1" -> Next -> Generate from BUILD file, "main\BUILD" -> Next -> Finish 
* Open Project in this Window
* Observe error

#### Version information
CLion: 2021.2.3
Platform: Windows 10 10.0
Bazel plugin: 2021.10.19.0.1-api-version-212
Bazel: 6.0.0

**Comment by AlexeyGy** [comment]
Hey Max, we don't support Windows, see #113

**Comment by maxgerhardt** [comment]
Wow, awesome.
