### ISSUE TITLE
 cc_binary rules do not appear to be linked in CLion

### ISSUE THREAD

**Issue by ghost** [bazelbuild/intellij#304]
I have a `.bazelproject` file that looks like this:

```
directories:
  .

targets:
  //middleware/kafka/simulator:kafka-simulator
```

When I press ctrl+F9 to compile, I get this output:

```
Command: bazel build --tool_tag=ijwb:CLion --keep_going --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/maximus/.CLion2017.3/config/plugins/clwb/aspect --output_groups=intellij-compile-cpp,intellij-compile-py -- //middleware/kafka/simulator:kafka-simulator


Another command (pid=21050) is running.  Waiting for it to complete on the server...
INFO: Loading complete.  Analyzing...
INFO: Found 1 target...
INFO: Elapsed time: 1.068s, Critical Path: 0.19s

==== TIMING REPORT ====

Make: 1.2s

Timing summary:

BlazeInvocation: 1.2s
```

However, no binary is produced.

If I attempt to run `bazel build //middleware/kafka/simulator:kafka-simulator` on the command line, I'm presented with a bunch of link errors.  My expectation is that I would see those same link errors when building in CLion.

If I introduce an error into one of the source files used by my `cc_binary` rule, the error is correctly reported when building.  So, it appears the the rule is being compiled but not linked.

I can't tell if this is by design, a limitation of CLion, a misunderstanding on my part, or a bug.

**Comment by chaoren** [comment]
Do you get the same behavior on the command line if you add the `--keep_going` flag?

**Comment by akowpak-ssimwave** [comment]
The `--keep-going` flag is already set.

I forgot to mention this earlier, but, if I copy the command that bazel runs onto the command line, I get the same behaviour (no linking).  However, if I remove the `--output_groups=intellij-compile-cpp,intellij-compile-py`, then it links.

**Comment by akowpak-ssimwave** [comment]
After further investigation, it appears that the plugin isn't working correctly with bazel version 0.13.0.  I upgraded yesterday morning after we team made some changes that wouldn't work with bazel 0.12.0.  

I was doing some refactoring, and expected my build to fail, but, when I compiled in CLion (with bazel 0.13.0). I received this output:

```
Command: bazel build --tool_tag=ijwb:CLion --keep_going --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/maximus/.CLion2017.3/config/plugins/clwb/aspect --output_groups=intellij-compile-cpp,intellij-compile-py -- //...


Starting local Bazel server and connecting to it...
.........
INFO: Loading package: deploy
INFO: Loading package: livemonitor/slave
INFO: Loading package: third_party/cpp/curl/fakes
INFO: Loading package: shelf
INFO: Loading package: common/cpp/time
INFO: Loading package: @bazel_tools//tools/cpp
INFO: Loading package: @local_config_cc//
INFO: Loading complete.  Analyzing...
INFO: Loading package: @bazel_tools//platforms
INFO: Loading package: @bazel_tools//third_party/py/gflags
INFO: Loading package: @boost//
INFO: Loading package: @bazel_tools//src/tools/launcher
INFO: Loading package: @bazel_tools//src/main/cpp/util
INFO: Found 545 targets...
INFO: Building...
INFO: Elapsed time: 11.819s, Critical Path: 0.22s
INFO: 0 processes.

==== TIMING REPORT ====

Make: 13.5s

Timing summary:

BlazeInvocation: 13.5s
```

I couldn't figure out why it wasn't compiling anything as I had obviously made changes.  After realizing that I had upgraded bazel, I attempted to downgrade to version 0.12.0.  The output in this case was:

```
Command: bazel build --tool_tag=ijwb:CLion --keep_going --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/maximus/.CLion2017.3/config/plugins/clwb/aspect --output_groups=intellij-compile-cpp,intellij-compile-py -- //...


..........
INFO: Loading package: livemonitor/gurusync
INFO: Loading package: livemonitor/snmptrap
INFO: Loading package: common/cpp/sdi
INFO: Loading package: @bazel_tools//tools/cpp
INFO: Loading package: @local_config_cc//
INFO: Loading complete.  Analyzing...
INFO: Loading package: @bazel_tools//platforms
INFO: Loading package: @bazel_tools//tools/jdk
INFO: Loading package: @librdkafka//
INFO: Loading package: @bazel_tools//src/main/cpp/util
INFO: Found 545 targets...
INFO: Building...
[157 / 164] Executing genrule //common/cpp/version:build-info
[369 / 373] Compiling livemonitor/analyzer/ServiceConfig.test.cpp
[387 / 391] Compiling livemonitor/analyzer/StaticAlert.test.cpp
[397 / 401] Compiling livemonitor/analyzer/MessageConnector.test.cpp
[417 / 421] Compiling livemonitor/analyzer/DBConnector.test.cpp
...
a bunch of expected compile errors
...
INFO: Building complete.
INFO: Elapsed time: 28.445s, Critical Path: 11.37s
Make failed

==== TIMING REPORT ====

Make: 30.1s

Timing summary:

BlazeInvocation: 30.1s
```

Using the command line, bazel 0.13.0 works fine, but, as soon as I add `--output_groups=intellij-compile-cpp,intellij-compile-py`, it stops working.

Any chance this is a known issue that's going to be fixed in the next release of the plugin?

**Comment by brendandouglas** [comment]
This is probably a known issue -- to compile C++ targets, we rely on requesting the contents of the "compilation_outputs" output group (formerly called "files_to_compile_INTERNAL" until it was changed at the start of April).

We updated the plugin to match the new name, but if you're on a bazel plugin version prior to 2018.04.09.0.2, you'll hit this problem.

**Comment by chaoren** [comment]
`compilation_outputs` doesn't work now either. I think they changed it again.

**Comment by chaoren** [comment]
> print(target, target.output_group("compilation_outputs"))

```
DEBUG: /path/to/external/intellij_aspect/intellij_info_impl.bzl:300:3: <target //:library, keys:[CcCompilationContextInfo, CcRunfilesInfo, CcExecutionDynamicLibrariesInfo, link_params, OutputGroupInfo]> depset([<generated file _objs/library/library.pic.o>])
DEBUG: /path/to/external/intellij_aspect/intellij_info_impl.bzl:300:3: <target //:binary, keys:[CcCompilationContextInfo, CcExecutionDynamicLibrariesInfo, OutputGroupInfo]> depset([<generated file _objs/binary/binary.pic.o>])
DEBUG: /path/to/external/intellij_aspect/intellij_info_impl.bzl:300:3: <target //:test, keys:[CcCompilationContextInfo, CcExecutionDynamicLibrariesInfo, OutputGroupInfo]> depset([<generated file _objs/test/test.pic.o>])
```

Looks like only `_objs/<target>/<target>.pic.o` exists in `compilation_outputs` now.

**Comment by akowpak-ssimwave** [comment]
Hmm... apparently I'm using version 2018.02.26.0.3 of the plugin.  Totally missed that there was an update in April.

**Comment by chaoren** [comment]
Oh, even with bazel 0.12.0, there's no link output with `--output_groups=intellij-compile-cpp,intellij-compile-py`.

**Comment by chaoren** [comment]
Disregard https://github.com/bazelbuild/intellij/issues/304#issuecomment-386685548. compilation_outputs in 0.13.0 is the same as files_to_compile_INTERNAL in 0.12.0. It's just that neither does linking.

**Comment by akowpak-ssimwave** [comment]
Yep, I just finished upgrading to the latest plugin and have verified that my compile problem is fixed.  My apologies for the confusion.  I should have noticed that there was a new version of the plugin.

Resetting the name of the issue to reflect the fact that linking still appears to be an issue.

Thanks for the quick responses

**Comment by mai93** [comment]
Hello @ghost do you still see this issue with the latest version of CLion and the plugin?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
