### ISSUE TITLE
Allow Bazel plugin to use WSL

### ISSUE THREAD

**Issue by stabai** [bazelbuild/intellij#3063]
In many situations, the Windows Subsystem for Linux (WSL) is a much cleaner interface with Bazel than Bazel for Windows. It would be extremely helpful if the IntelliJ plugin provided the option to run Bazel commands through the WSL instead of in normal Windows.

I tried creating a simple custom cmd file to do this using [wsl.exe](https://docs.microsoft.com/en-us/windows/wsl/filesystems#run-linux-tools-from-a-windows-command-line), but command line arguments like `override_repository` being passed to Bazel would also need adjustment to rewrite paths in Linux form (and possibly other things).

**Comment by sgowroji** [comment]
Dupe of #3112
