### ISSUE TITLE
"Attach Blaze Source Jars" links sources with wrong path

### ISSUE THREAD

**Issue by kobersotzek** [bazelbuild/intellij#31]
Our project uses Maven artifacts via Bazel to reference other libraries. The jar-files of those libraries are downloaded to a subdirectory of the Bazel cache directory. The same holds for the source files.

When I navigate to a class of such a library, "Attach Blaze Source Jars" shows up. After triggering it, it simply vanishes and the standard IntelliJ Options "Download..." and "Choose Sources..." are displayed. The source code isn't displayed, though.
After these steps, there seems to be an additional entry for the sources which is shown when going to "Project Settings > Libraries > specific library".  However, the path points to a non-existent source jar. Instead of referencing the subdirectory of the Bazel cache directory, the path consists of the directory containing the code of the project followed by the correct subdirectory structure.

**Comment by brendandouglas** [comment]
This is fixed for the next IJwB release (v1.13+). For the fix to take effect, you'll need to either wait for another bazel release, or build it from head.

**Comment by kobersotzek** [comment]
Thank you for fixing this issue. It works for me with IJwB 2017.01.09.1 and Bazel 0.4.4.

**Comment by ittaiz** [comment]
How can this be fixed when #42 which sounds the same is open.
Is this working?

**Comment by ittaiz** [comment]
I played with this a bit and I see that jars from maven central and sonatype are automatically searched and downloaded.
Is this the difference between this ticket and #42?

**Comment by brendandouglas** [comment]
This bug isn't about automatically downloading source jars. It's just about correctly attaching already downloaded source jars to the project libraries.

AFAIK, Bazel won't yet automatically download source jars for maven_jar targets -- but if you force it to (e.g. via your own [custom rule type](https://gerrit.googlesource.com/gerrit/+/master/tools/bzl/maven_jar.bzl)), the IntelliJ plugin now handles it properly.
