### ISSUE TITLE
Feature request: support "partial sync" of multiple selected packages

### ISSUE THREAD

**Issue by roblg** [bazelbuild/intellij#310]
Current behavior: if you select multiple packages in the IntelliJ 'project' view, right-click and click 'Partially Sync...', it only syncs one of them. (IntelliJ IDEA 2017.x, ijwb: 2018.02.26.0.3)

Requested behavior: if you select multiple packages, and partially sync, include all of those packages in the sync.

Background: we have two java webapps that are frequently run side-by-side. On the command-line, we can build both simultaneously with bazel, but in IntelliJ we have to build+run them one at a time (or sync _everything_ on every pull, which is really slow). This could be a pretty significant time-saver for us.

Also, no promises, but: is this something that might be suitable for an outside contribution? I'd imagine it's not super involved, but I haven't dug in yet either.

**Comment by chaoren** [comment]
I have a change for this under review. Should be released in a couple of weeks.
