### ISSUE TITLE
Build Bazel Plugin for Clion_2021_3 error (clion-oss-under-dev)

### ISSUE THREAD

**Issue by wniu9** [bazelbuild/intellij#3101]
Building error when running the command (without any further code changes) on both Ubuntu 20.04 and macOS:
`
bazelisk build //clwb:clwb_bazel_zip --define=ij_product=clion-oss-under-dev --verbose_failures
`

The outputs from the terminal:
`
bazelisk build //clwb:clwb_bazel_zip --define=ij_product=clion-oss-under-dev --verbose_failures                                                                                                                                                                              2m 16s py base
INFO: Analyzed target //clwb:clwb_bazel_zip (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/user_name/opt/Bazel/intellij/aspect/tools/BUILD:18:13: Building aspect/tools/liblib.jar (6 source files) failed: (Exit 1): java failed: error executing command 
  (cd /home/user_name/.cache/bazel/_bazel_user_name/4b8d771e7a452a6eecba6ad1168d3b14/execroot/intellij_with_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
    LD_LIBRARY_PATH=...... \
    PATH=/home/user_name/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.2-linux-x86_64/bin:...... \
  external/remotejdk11_linux/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_linux/java_tools/java_compiler.jar' '--patch-module=jdk.compiler=external/remote_java_tools_linux/java_tools/jdk_compiler.jar' '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-opens=java.base/java.nio=ALL-UNNAMED' '--add-opens=java.base/java.lang=ALL-UNNAMED' -jar external/remote_java_tools_linux/java_tools/JavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/aspect/tools/liblib.jar-0.params @bazel-out/k8-fastbuild/bin/aspect/tools/liblib.jar-1.params)
Execution platform: @local_config_platform//:host
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:18: error: package com.google.common.annotations does not exist
import com.google.common.annotations.VisibleForTesting;
                                    ^
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:19: error: package com.google.common.base does not exist
import com.google.common.base.Splitter;
                             ^
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:20: error: package com.google.common.collect does not exist
import com.google.common.collect.ImmutableList;
                                ^
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:29: error: cannot find symbol
@VisibleForTesting
 ^
  symbol: class VisibleForTesting
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:33: error: cannot find symbol
  private static final Splitter SPLITTER = Splitter.on(',');
                       ^
  symbol:   class Splitter
  location: class ArtifactLocationParser
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:18: error: package com.google.common.annotations does not exist
import com.google.common.annotations.VisibleForTesting;
                                    ^
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:19: error: package com.google.common.base does not exist
import com.google.common.base.Preconditions;
                             ^
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:20: error: package com.google.common.io does not exist
import com.google.common.io.ByteStreams;
                           ^
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:21: error: package com.google.common.io does not exist
import com.google.common.io.Files;
                           ^
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:54: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:20: error: package com.google.common.annotations does not exist
import com.google.common.annotations.VisibleForTesting;
                                    ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:21: error: package com.google.common.base does not exist
import com.google.common.base.Preconditions;
                             ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:22: error: package com.google.common.collect does not exist
import com.google.common.collect.ImmutableList;
                                ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:23: error: package com.google.common.collect does not exist
import com.google.common.collect.Lists;
                                ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:24: error: package com.google.common.io does not exist
import com.google.common.io.Files;
                           ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:25: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.Futures;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:26: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.ListenableFuture;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:27: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.ListeningExecutorService;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:28: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.MoreExecutors;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:60: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/OptionParser.java:18: error: package com.google.common.collect does not exist
import com.google.common.collect.ImmutableList;
                                ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:18: error: package com.google.common.annotations does not exist
import com.google.common.annotations.VisibleForTesting;
                                    ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:19: error: package com.google.common.base does not exist
import com.google.common.base.Preconditions;
                             ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:20: error: package com.google.common.collect does not exist
import com.google.common.collect.Maps;
                                ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:21: error: package com.google.common.io does not exist
import com.google.common.io.Files;
                           ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:22: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.ListenableFuture;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:23: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.ListeningExecutorService;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:24: error: package com.google.common.util.concurrent does not exist
import com.google.common.util.concurrent.MoreExecutors;
                                        ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:49: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParserIoProvider.java:18: error: package com.google.common.annotations does not exist
import com.google.common.annotations.VisibleForTesting;
                                    ^
aspect/tools/src/com/google/idea/blaze/aspect/PackageParserIoProvider.java:28: error: cannot find symbol
@VisibleForTesting
 ^
  symbol: class VisibleForTesting
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:35: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class ArtifactLocationParser
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:62: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:75: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:70: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:104: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:286: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:55: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:104: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:109: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:129: error: cannot find symbol
  @VisibleForTesting
   ^
  symbol:   class VisibleForTesting
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:33: error: cannot find symbol
  private static final Splitter SPLITTER = Splitter.on(',');
                                           ^
  symbol:   variable Splitter
  location: class ArtifactLocationParser
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:45: error: package ImmutableList does not exist
    ImmutableList.Builder<ArtifactLocation> builder = ImmutableList.builder();
                 ^
aspect/tools/src/com/google/idea/blaze/aspect/ArtifactLocationParser.java:45: error: cannot find symbol
    ImmutableList.Builder<ArtifactLocation> builder = ImmutableList.builder();
                                                      ^
  symbol:   variable ImmutableList
  location: class ArtifactLocationParser
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:89: error: cannot find symbol
      Preconditions.checkNotNull(options.outputAar);
      ^
  symbol:   variable Preconditions
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:90: error: cannot find symbol
      Preconditions.checkNotNull(options.manifestFile);
      ^
  symbol:   variable Preconditions
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:91: error: cannot find symbol
      Preconditions.checkNotNull(options.resourceRoot);
      ^
  symbol:   variable Preconditions
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:119: error: cannot find symbol
      ByteStreams.copy(fis, zos);
      ^
  symbol:   variable ByteStreams
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/CreateAar.java:130: error: cannot find symbol
      return Files.readLines(paramFile, StandardCharsets.UTF_8).toArray(new String[0]);
             ^
  symbol:   variable Files
  location: class CreateAar
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:106: error: cannot find symbol
    Preconditions.checkNotNull(options.filteredJar);
    ^
  symbol:   variable Preconditions
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:109: error: cannot find symbol
      options.filterJars = ImmutableList.of();
                           ^
  symbol:   variable ImmutableList
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:112: error: cannot find symbol
      options.filterSourceJars = ImmutableList.of();
                                 ^
  symbol:   variable ImmutableList
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:115: error: cannot find symbol
    final List<String> archiveFileNamePrefixes = Lists.newArrayList();
                                                 ^
  symbol:   variable Lists
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:141: error: cannot find symbol
      return Files.readLines(paramFile, StandardCharsets.UTF_8).toArray(new String[0]);
             ^
  symbol:   variable Files
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:149: error: cannot find symbol
    ListeningExecutorService executorService =
    ^
  symbol:   class ListeningExecutorService
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:150: error: cannot find symbol
        MoreExecutors.listeningDecorator(
        ^
  symbol:   variable MoreExecutors
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:153: error: cannot find symbol
    List<ListenableFuture<String>> futures = Lists.newArrayList();
         ^
  symbol:   class ListenableFuture
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:153: error: cannot find symbol
    List<ListenableFuture<String>> futures = Lists.newArrayList();
                                             ^
  symbol:   variable Lists
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:165: error: cannot find symbol
      List<String> archiveFileNamePrefixes = Futures.allAsList(futures).get();
                                             ^
  symbol:   variable Futures
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:166: error: cannot find symbol
      List<String> result = Lists.newArrayList();
                            ^
  symbol:   variable Lists
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/JarFilter.java:182: error: cannot find symbol
    List<String> result = Lists.newArrayList();
                          ^
  symbol:   variable Lists
  location: class JarFilter
aspect/tools/src/com/google/idea/blaze/aspect/OptionParser.java:87: error: cannot find symbol
    return result == null ? ImmutableList.of() : result;
                            ^
  symbol:   variable ImmutableList
  location: class OptionParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:73: error: cannot find symbol
    Preconditions.checkNotNull(options.outputManifest);
    ^
  symbol:   variable Preconditions
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:96: error: cannot find symbol
      return Files.readLines(paramFile, StandardCharsets.UTF_8).toArray(new String[0]);
             ^
  symbol:   variable Files
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:133: error: cannot find symbol
    ListeningExecutorService executorService =
    ^
  symbol:   class ListeningExecutorService
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:134: error: cannot find symbol
        MoreExecutors.listeningDecorator(
        ^
  symbol:   variable MoreExecutors
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:137: error: cannot find symbol
    Map<ArtifactLocation, ListenableFuture<String>> futures = Maps.newHashMap();
                          ^
  symbol:   class ListenableFuture
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:137: error: cannot find symbol
    Map<ArtifactLocation, ListenableFuture<String>> futures = Maps.newHashMap();
                                                              ^
  symbol:   variable Maps
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:141: error: cannot find symbol
    Map<ArtifactLocation, String> map = Maps.newHashMap();
                                        ^
  symbol:   variable Maps
  location: class PackageParser
aspect/tools/src/com/google/idea/blaze/aspect/PackageParser.java:142: error: cannot find symbol
    for (Entry<ArtifactLocation, ListenableFuture<String>> entry : futures.entrySet()) {
                                 ^
  symbol:   class ListenableFuture
  location: class PackageParser
Target //clwb:clwb_bazel_zip failed to build
INFO: Elapsed time: 0.349s, Critical Path: 0.25s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
`

**Comment by oceanusxiv** [comment]
So, this particular error is actually pretty easy to fix, https://github.com/bazelbuild/intellij/blob/7881568fd4c029d36b6a4d681258645b90135c01/intellij_platform_sdk/BUILD.clion213#L31
just needs to be changed to `"clion-*/lib/3rd-party-rt.jar"`.

However, there are a _lot_ more breaking changes in the CLion internal interface that needs to get fixed before the plugin can remotely work again.

**Comment by alice-ks** [comment]
With PR #3131, these errors are gone now. The plugin compiles successfully against CLion 2021.3 and the CI is green. I hence went ahead and pushed a corresponding version of the plugin to the beta channel of JetBrains' marketplace. It's currently pending approval by JetBrains, which is typically given within a day.
