### ISSUE TITLE
Enable 'Autoscroll to console' feature by default

### ISSUE THREAD

**Issue by edio** [bazelbuild/intellij#3106]
The _Autoscroll to console_ feature should be enabled by default, as it seems to be the _reasonable default_.

The default Bazel output parser and many custom parsers only emit the first line of the error to the _Bazel problems_ view, and this is an optimal behavior since it is often not possible to reliably detect the beginning and the end of a multi-line error message. At the same time, many modern tools emit multi-line error messages.

Hence to understand the error when working with a Bazel-powered project in Intellij IDEA developer has to look through Bazel output, and _Autoscroll to console_ feature is a lifesaver here.

In our organization, we use Bazel to build Scala projects, and over time we've collected enough evidence to conclude that
1. developers do not know about _Autoscroll to console_ feature
2. developers are excited to use this feature after they discover it

Changing the default from `false` to `true` would improve the experience for the majority of our devs.
The change is also pretty straightforward (a one-line change https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/ui/problems/ProblemsViewConfiguration.java#L33).
I believe the change also does not have any negative side-effects (but let me know please if I'm wrong).

Let me know, what you think. If you're fine with this change, I can prepare a PR.

**Comment by sgowroji** [comment]
Hello @liucijus, Above PR https://github.com/wix-playground/intellij/pull/69 looks merged. Anything is  pending  to close this issue ?

**Comment by edio** [comment]
@sgowroji , from what I see, the default value of the `autoscrollToConsole` in the master branch is still `false`
https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/ui/problems/ProblemsViewConfiguration.java#L33

Please note, the https://github.com/wix-playground/intellij/pull/69 adresses the issue in our private fork.
However we'd like this change to be accepted _upstream_ (in this repo).

FWIW, we are happy with the private fork change, and we haven't observed any negative side-effects nor issues so far.

I opened a PR (#4006). When merged it will fix this issue.
