### ISSUE TITLE
"partial sync" has unintuitive behavior on parent package

### ISSUE THREAD

**Issue by roblg** [bazelbuild/intellij#312]
We have a package structure like:

```
imports/
    BUILD
    listing/
        BUILD
    property/
        BUILD
  # etc.
```

Currently, when doing a partial sync on `imports`, the generated build command has `//imports:all`, which is sort of unintuitive.

From our perspective, the ideal behavior in this case would be to generate a target spec like `//imports/...:all`.

**Comment by roblg** [comment]
Hmm... On the one hand, I agree that bazel's default behavior is to treat subpackages as unrelated, but I'd expect that it's pretty common that they _are_ somehow related, right? Otherwise, why would bazel support the shorthand for building/testing all subpackages under a particular package, e.g. `bazel build //imports/...`.

For me, when I'm working in the IDE specifically, I'm looking at a folder, not a package per se, and that folder obviously has sub-folders, so if I partially sync the top one it seems like it should sync all of them. I totally understand that that might not be the expectation of every ijwb user though. Maybe as a compromise (even though it feels a little hacky) there could be two "Partial Sync" actions that appear in the context menu:

```
 - Partially Sync _only_ //imports
 - Partially Sync  //imports/...
```

As it is, the combination of this issue and #310 (can't multi-select to partial sync) makes any sort of partial syncing after pulling in changes pretty painful, and a full sync can take 25+ minutes.

**Comment by chaoren** [comment]
I would much prefer #310 to an additional context menu item.

**Comment by chaoren** [comment]
Implementing #310 should sufficiently address this use case, correct? I'll close this in favor of #310 then.

**Comment by roblg** [comment]
Closing this pains me, since I still feel like `//imports/...:all` is the more intuitive behavior for the partial sync action on a _folder_ when initiated through the UI. Another option might be to have a flag in the bazel menu like `Expand sync to working set` -- `Expand partial sync to subpackages`? 

Fixing #310 provides a functional, but not particularly satisfactory workaround for this issue. It'll end up being a lot of clicking.

**Comment by ittaiz** [comment]
+1 to Robert

**Comment by chaoren** [comment]
You can expand `imports`, click imports, shift click the last directory under imports to select everything.

**Comment by chaoren** [comment]
Perhaps we can make clicking on the `BUILD` file be `foo:all` and clicking on the directory be `foo/...:all`.

@brendandouglas what do you think?

**Comment by brendandouglas** [comment]
I agree recursively syncing is more intuitive, and is consistent with what we already do for the 'Add directory to project' action (and a few others, such as running all tests below a directory).

My main concern is giving users (especially internal ones) extra rope to run build operations that will never finish. But it should be pretty clear what's happened, so let's do it.

**Comment by ittaiz** [comment]
Thanks!

**Comment by chaoren** [comment]
Done. Should be available in a few weeks.
