### ISSUE TITLE
package-view: Double counting of package in the package view. 

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#313]
In general we need to improve the "package" view for Jvm languages so that it's a reliable tool for large repos.

@brendandouglas perhaps create a label in gh for this ? 

--- 

This issue is about cases where packages are double counted.

`com.donkey.kong` is showing up as

```
com
| - donkey
     |- kong
com.donkey.kong
```

**Comment by chaoren** [comment]
I'm not seeing this.
Are there any other files under com/ or com/donkey/?

**Comment by hsyed** [comment]
I have tried to find a common pattern for it occurring in our mono repo where it occurs for java and Kotlin -- more cases of it for the Kotlin case. 

In `kotlin_rules` I am seeing the following:

![screen shot 2018-05-14 at 19 43 25](https://user-images.githubusercontent.com/1143140/40016726-282e0cd4-57af-11e8-95ca-54c45d181465.png)

I expect `io.bazel.kotlin.builder` and `io.bazel.kotlin.testing` to both be rooted at `io.bazel`. 
`io.bazel.kotlin.builder` only has kotlin files under it so it has not reason to have separate root.  `io.bazel.kotlin.testing` has skylark and BUILD files as well.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
