### ISSUE TITLE
Android Studio Sync Failed

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/intellij#3133]
New bazel plugin version (v2021.12.14) failed to sync on kotlin related rules. Relate to [this commit](https://github.com/bazelbuild/intellij/commit/13287a2e386b516d69727f4d83b31b344a10a24e)

```
ERROR: ... in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on kt_android_library rule ...
File ".cache/_bazel_root/53ad39fbc746a9a796d5456c4457d007/external/intellij_aspect/intellij_info_bundled.bzl", line 54, column 37, in _aspect_impl
return intellij_info_aspect_impl(target, ctx, semantics)
File ".cache/_bazel_root/53ad39fbc746a9a796d5456c4457d007/external/intellij_aspect/intellij_info_impl.bzl", line 1114, column 32, in intellij_info_aspect_impl
handled = collect_java_info(target, ctx, semantics, ide_info, ide_info_file, output_groups) or handled
File ".cache/_bazel_root/53ad39fbc746a9a796d5456c4457d007/external/intellij_aspect/intellij_info_impl.bzl", line 650, column 64, in collect_java_info
plugin_processor_jar_files = java.annotation_processing.processor_classpath.to_list()
Error: 'struct' value has no field or method 'processor_classpath'
Available attributes: class_jar, enabled, source_jar
```

**Comment by ThomasCJY** [comment]
non-issue. close

**Comment by sgammon** [comment]
@ThomasCJY how did you fix this?

**Comment by rockwotj** [comment]
+1

**Comment by hsestupin** [comment]
Why is it closed? It's still the case.
Build #IU-213.7172.25, built on March 15, 2022
bazel plugin version 2022.04.05.0.1-api-version-213
kotlin rules version - "v1.5.0"

**Comment by jesseschalken** [comment]
Doing a fresh build from master (currently b13da748a528f7f2872b2139d2e0ca27c1e1299e) fixed the issue for me. I got the error while on commit 934f183f03d690e526a737136419b6af8c2a1e3f. Not sure what fixed it.

**Comment by rockwotj** [comment]
This got fixed in https://github.com/bazelbuild/intellij/issues/3384
