### ISSUE TITLE
goland bazel plugin: Unexported function

### ISSUE THREAD

**Issue by duguying** [bazelbuild/intellij#3134]
#### Description of the issue. Please be specific.
![image](https://user-images.githubusercontent.com/3050360/147746657-77825a01-cdd3-4d1e-bcbf-51e1dca2fcfa.png)
Unexported function in go test files

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Unexported function in go test files. the test file and unexported function in the same package

#### Version information
GoLand: 2021.1.3
Platform: Mac OS X 12.1
Bazel plugin: 2021.10.19.0.1-api-version-211
Bazel: 4.2.0

**Comment by sulewicz** [comment]
I ran into the same issue. The only way to fix the indexing is to add the test file to go_library (or go_binary) srcs.
Similar problem occurs with nested internal packages referenced from a test, which results in a "Use of internal package is not allowed" error.
It is like the IDE treats output of go_library and go_test as independent packages, while from Go perspective they are one and the same package.

**Comment by sgowroji** [comment]
Hello @duguying, Did you get a chance to check this [comment](https://github.com/bazelbuild/intellij/issues/3134#issuecomment-1107353320) . Are you still looking resolution for the above issue. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by sfc-gh-shsharma** [comment]
Hello there. My team and I are still experiencing this issue. We currently just ignore the error, but this issue should probably not be closed.

**Comment by sfc-gh-mizhang** [comment]
Hi there! Our team is having this issue and the workaround above will mess up our build file which is not efficient in prod use.  Please prioritize this issue. It needs to be fixed. Anyone using Go with bazel will not be able to use JetBrains.

**Comment by srabraham** [comment]
I commented on a JetBrains ticket about the problem too, as it's at least quite similar to this issue. https://youtrack.jetbrains.com/issue/GO-8698

**Comment by JamyDev** [comment]
Seems to be similar to my issue: https://github.com/bazelbuild/intellij/issues/4349 

This was fixed, but you have to re-sync after updating the plugin.

**Comment by sgowroji** [comment]
Hi @duguying, Could you please respond if you are still seeing the above error.

**Comment by weaseal** [comment]
I was able to resolve this problem by using `embed` under `go_test`: https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/rules.md#go_test-embed

Example:
```
go_library(
    name = "lib",
    srcs = [
        "project.go",
    ],
)

go_test(
    name = "my-test",
    srcs = [
        "project_test.go",
    ],
    embed = [":lib"],
)
```

Then you can avoid including both files under `srcs`

**Comment by duguying** [comment]
> Hi @duguying, Could you please respond if you are still seeing the above error.

I've turned to vscode.

**Comment by edaniels** [comment]
This is still an issue.
