### ISSUE TITLE
package-view: for mvn/gradle style projects merge BUILD (and resource?) files with the java package roots.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#314]
As a simple example see the noise generated from bazel related dummy package entries:

![screen shot 2018-05-14 at 14 34 13](https://user-images.githubusercontent.com/1143140/40000580-197f9458-5784-11e8-817f-71d89a7dc7b9.png)

For maven/gradle projects there should be a heuristic to determine the Java root a BUILD file belongs to and the file can then be placed there. 

This probably also applies to resource files.

**Comment by brendandouglas** [comment]
What do you mean by merging the BUILD file with the package roots? Could you give an example of what you expect in the example above?

**Comment by hsyed** [comment]
This applies to bazel package following maven conventions or in general any package with it's java source root beginning in another directory --e.g., `src` directory. 

```
bar
|- BUILD
|-src
  | - Foo.java
```

where `Foo.java` is in package `bar.baz`. 

This Should not result in 2 distinct entries in the packages view --i.e., not:

```
bar.baz
|- Foo
bar
| - BUILD
```
the package view should look as follows

```
bar.baz
|- Foo
|- Build
```

This assumes the package in question has a non whacky layout -- i.e., we can have a sensible heuristic to choose a common root where the BUILD file should be assigned.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
