### ISSUE TITLE
IDEA has access to all projects files (Java/Kotlin)

### ISSUE THREAD

**Issue by neee** [bazelbuild/intellij#3161]
I have a several services in one workspace (java/kotlin), the code of the services are not shared but they are using shared libs from the same repo and workspace.

My problem that when I write the code I have access to all files from the whole workspace not only shared libs.
The problem produce the situation when I can use some classes (add import and etc) but get error on compile time due to classes are not available in the current project.
I would like to have in the classpath when do developing process only classess/libs described in the bazel file of the particular project not whole workspace.

The problem looks like that packages/jars/projects are not isolated in the one workspace between projects

**Comment by sgowroji** [comment]
Hello @neee, Could you please provide a sample repo to reproduce the above issue, if you are still looking for support on the above. Please try to verify the same with the latest versions. Thanks!

**Comment by kshyanashree** [comment]
Hello @neee, Did you have an opportunity to check the above [comment](https://github.com/bazelbuild/intellij/issues/3161#issuecomment-1337925955)? Thanks!
