### ISSUE TITLE
Plugin 'Bazel' is incompatible with this installation

### ISSUE THREAD

**Issue by achraf-boussaada** [bazelbuild/intellij#317]
I followed this [issue](https://github.com/bazelbuild/intellij/issues/294) to install Bazel plugin in Android Studio since I couldn't find it when I browse repositories. But I encountered the problem mentioned in the title. 

I have Android Studio 3.1.2 and to my understanding I'm having this problem because you don't support this version yet. So what is the latest version of Android studio that you support and when the plugin is going to be updated? 

Final question : where can I find the information about the Bazel compatibility with Android Studio ? because I can't seem to find it that's why I had to open this issue in the first place.

Keep up the good work and thank you

**Comment by brendandouglas** [comment]
The latest supported version is 3.0 -- we'll skip straight to 3.2 from there, probably in around 2 months from now (see https://github.com/bazelbuild/intellij/issues/278).

You can find the versions we support here: https://plugins.jetbrains.com/plugin/9185-bazel

You'll need to convert from IDEA build versions to the Android Studio numbering system, but the plugin repo site is the source of truth here.
