### ISSUE TITLE
What should ij_product be when building for GoLand

### ISSUE THREAD

**Issue by MichaelSnowden** [bazelbuild/intellij#3178]
I'm reading the [building instructions here](https://github.com/bazelbuild/intellij#building-the-plugin), and they say we should define the ij_product flag, but I couldn't find one for GoLand in https://github.com/bazelbuild/intellij/blob/master/intellij_platform_sdk/build_defs.bzl . What should this flag be?

**Comment by alice-ks** [comment]
There is no specific setup for GoLand. Just compile the plugin for IntelliJ UE. The result should be compatible with IntelliJ UE, IntelliJ CE, Goland, PyCharm, and WebStorm.
