### ISSUE TITLE
PyCharm isn't resolving namedspaced packages correctly

### ISSUE THREAD

**Issue by caseyduquettesc** [bazelbuild/intellij#3185]
Seems that PyCharm can no longer (I'm not sure if it ever worked or if it did might have just be indeterministic) resolve python modules that share a package. `google-cloud-*` is a good example.

I depend on 

```
google-api-core==1.26.3
google-auth==1.30.0
google-cloud-monitoring==1.1.0
google-cloud-pubsub==2.6.0
```

And my editor cannot find `google.cloud.pubsub_v1`.

![image](https://user-images.githubusercontent.com/16676170/150054184-9f16ff5e-6443-4991-9e0e-11762f124bde.png)

When I go to the declaration for `google.cloud` it takes me here, which is inside `google.cloud.monitoring`

![image](https://user-images.githubusercontent.com/16676170/150054254-7d93b5b9-30e9-4069-b725-a273fbacfbd5.png)

I'm using Python 3.9 with `rules_python` 0.6.0 and I am using `pip_parse` to install the dependencies.

**Comment by sgowroji** [comment]
Hello @caseyduquettesc, Could you please elaborate your query with more details like how is it related to bazel plugin. Thanks!

**Comment by caseyduquettesc** [comment]
I only experience the problem when I use bazel, otherwise the packages resolve fine.
