### ISSUE TITLE
Support CLion 2018.2

### ISSUE THREAD

**Issue by stsundermann** [bazelbuild/intellij#320]
I'd like to use the bazel plugin with CLion 2018.2 EAP since it has a lot of bugfixes and performance is a lot better than with 2018.1. Can you also support 2018.2 EAP at this point or did build system API change again under the hood?

Current 2018.2 EAP version is CL-182.2371.31.

**Comment by brendandouglas** [comment]
The plugin API almost certainly changed (and will likely change more before 2018.2 is officially released). More importantly though, we haven't finished tracking down and fixing all the problems with 2018.1, so it will be some months before we get to 2018.2.

**Comment by brendandouglas** [comment]
Case in point: https://github.com/bazelbuild/intellij/issues/325

Even the 2018.1 plugin API hasn't stabilized yet. Any work we did for 2018.2 EAP might have to be redone for the stable 2018.2 release.

**Comment by evantorrie** [comment]
[CLion 2018.2](https://www.jetbrains.com/clion/whatsnew/) final has just been officially released.

**Comment by jiepony** [comment]
Any update please?

**Comment by brendandouglas** [comment]
You can see the supported IDE versions for CLion here: https://plugins.jetbrains.com/plugin/9554-bazel

2018.2 has been supported since Oct 8th, but we forgot to close this issue.
