### ISSUE TITLE
I got in to error while running intelij on wsl2, seems like bazel plugin trying to acces the bazel bin from windows terminal. Is there any way to change the terminal to wsl2

### ISSUE THREAD

**Issue by marutha51** [bazelbuild/intellij#3203]

**Comment by dpoluyanov** [comment]
There is a way to change bazel binary location in Bazel-plugin settings:
<img width="1094" alt="settings" src="https://user-images.githubusercontent.com/2296372/150813665-76d6af63-e4ec-4063-b658-7b77e35114bb.png">
 
But unfortunatelly, windows-based IntelliJ & bazel plugin expecting windows binary and couldn't launch bazel inside in WSL2, so I've created small adapter from windows-based IntelliJ to wsl2 bazel installation https://github.com/dpoluyanov/bazel-wsl for my colleagues who prefer to work from windows machines.
Even such adapter wasn't enough for smooth interoperability with wsl, so I've open an issue https://github.com/bazelbuild/intellij/issues/3112 with patch proposal and rebuilt IntelliJ plugin with this change in https://github.com/dpoluyanov/bazel-wsl/releases/tag/v0.0.3

**Comment by sgowroji** [comment]
Dupe of #3112.
