### ISSUE TITLE
Test functionality in IntelliJ 2021.3 plugin does not work

### ISSUE THREAD

**Issue by christi-square** [bazelbuild/intellij#3217]
(copied from https://github.com/bazelbuild/intellij/issues/3001#issuecomment-1022315177)

In IntelliJ 2021.2.4 with Bazel plugin 2022.01.11.0.0-api-version-212, if I open a file with junit tests, I can click to run tests with bazel within the file. This creates a run configuration which I can select and run again using the configuration/play toolbar items.

Fig.1 - Run menu within a test file:
![Screen Shot 2022-01-26 at 10 17 14 AM](https://user-images.githubusercontent.com/84724835/151191187-38adefee-699f-46ab-b5ac-2e7da5dafd94.png)

Fig.2 - Bazel configuration created by clicking the "Run 'Bazel Test..." menu item in the above screenshot:
![Screen Shot 2022-01-26 at 10 17 51 AM](https://user-images.githubusercontent.com/84724835/151191207-0f7344a7-5ed2-4001-8e9e-60ec998bca0a.png)

Fig.3 - Configuration selected in toolbar:
![Screen Shot 2022-01-26 at 10 18 08 AM](https://user-images.githubusercontent.com/84724835/151191227-e33dd705-4eef-4ab3-9ce6-244b1e4bb7db.png)

In IntelliJ 2021.3.1 with Bazel plugin 2022.01.20.0.1-api-version-213, the behavior is completely different and I can barely run tests with Bazel.

Fig.4 - Run menu within a test file, note that the word "Bazel" is not present; this creates a JUnit configuration rather than a Bazel one:
![Screen Shot 2022-01-26 at 10 21 57 AM](https://user-images.githubusercontent.com/84724835/151192338-31675dca-a197-4db2-9f53-c0e4bc306f75.png)

Fig.5 - Error that occurs when I select run from the above screenshot:
![Screen Shot 2022-01-26 at 10 22 05 AM](https://user-images.githubusercontent.com/84724835/151192374-c95bc64a-8478-48f5-9716-9b08117bc0f9.png)

Fig.6 - Configuration that was created when I selected run from the above screenshot, note that this is a JUnit configuration rather than a Bazel configuration; you can see the original Bazel test configuration from the older version above the selected config:
![Screen Shot 2022-01-26 at 10 22 41 AM](https://user-images.githubusercontent.com/84724835/151192413-399fb2f0-32cb-49ad-b6e4-702d2ea3a45b.png)

Fig.7 - JUnit configuration selected in the toolbar:
![Screen Shot 2022-01-26 at 10 22 14 AM](https://user-images.githubusercontent.com/84724835/151192388-3254d8d9-d3f6-4fd5-9c8f-b835272925b7.png)

Fig.8 - Original Bazel configuration selected in the toolbar; note that the run button is disabled:
![Screen Shot 2022-01-26 at 10 22 25 AM](https://user-images.githubusercontent.com/84724835/151192399-0105a36d-1552-438e-9300-97f5811d78ae.png)

I can use the debug button from Fig.8 to debug a test with Bazel, so it is seemingly able to run a single test class. I do have a "Bazel test java:all" configuration that worked in the older version that has both run and debug disabled, so I don't think I can run all of my unit tests in the new version, but would have to run them one at a time and manually create new configurations for each test class. Basically, this is unusable for me.

**Comment by christi-square** [comment]
@YasmineMaheeb Which version of the Bazel plugin should I test?

**Comment by YasmineMaheeb** [comment]
The functionality will only be included in the plugin version which we'll publish Friday next week. If you want to test it earlier, you would need to build the plugin yourself from the sources.
However, I am more confident now we fixed this issue with pull request #3305.

**Comment by christi-square** [comment]
This does not appear to have been fixed with 2022.02.23.0.0-api-version-213. I tried with IntelliJ 2021.3.2 and 2021.3.3.

**Comment by YasmineMaheeb** [comment]
Yes, please try it with Bazel 2022.03.08.0.1-api-version-213 instead.

**Comment by christi-square** [comment]
I updated to 2022.03.22.0.5-api-version-213 and it appears to be fixed, thank you!
