### ISSUE TITLE
"Compiled binary cannot be executed" when trying to debug Go code

### ISSUE THREAD

**Issue by ronisec** [bazelbuild/intellij#3221]
Running:
1. GoLand 2021.2
1. Bazel Plugin 2021.11.09.0.2-api-version-212

When trying to debug a Go unit test I am getting the following output:

```
Compilation finished with exit code 0

Compiled binary cannot be executed
```

See:
![image](https://user-images.githubusercontent.com/88718157/151702372-e224b07d-1cac-41bf-ae41-09a837869f25.png)

**Comment by ronisec** [comment]
Solved, this was caused due to the following config in my `.bazelrc`:

```
build --symlink_prefix=/
```

Removed that config and it is working again. It would be nice if the plugin would be able to handle this case or print out a more informative debug message.

**Comment by sgowroji** [comment]
Thanks for sharing your resolution and Glad to see you resolve. We are closing this issue now. Please feel free to reach us if you have any further queries.

**Comment by kopax** [comment]
I have same issue and no `.bazelrc`, any clue what could cause that ?

**Comment by tpasternak** [comment]
Can you please share a minimal repro?

**Comment by kopax** [comment]
I just download GoLand, but I started first with intellij, then:

```bash
mkdir -p ~/workspace/github.com/ethereum
cd ~/workspace/github.com/ethereum
git clone https://github.com/ethereum/go-ethereum.git
cd go-ethereum
``` 

I use gvm (Go Version manager), and this is my go version : go1.23.0,

Then I open the go-ethereum directory, and  try to run / run & debug.

Whatever I do, I am unable to run in debug with idea and intellij, ex of build cmd with intellij:

```
 GOROOT=/home/dka/.gvm/gos/go1.23.0 #gosetup
GOPATH=/home/dka/.gvm/gos/go1.23.0/bin #gosetup
/home/dka/.gvm/gos/go1.23.0/bin/go build -o /home/dka/.cache/JetBrains/IntelliJIdea2024.2/tmp/GoLand/___2go_build_gethfork_ -gcflags all=-N -l . #gosetup

Compilation finished with exit code 0

Compiled binary cannot be executed
```

It seems like intellij idea ultimate or goland add this `-l` flag:

```
❯ /home/dka/.gvm/gos/go1.23.0/bin/go build -o /home/dka/.cache/JetBrains/IntelliJIdea2024.2/tmp/GoLand/___2go_build_gethfork_ -gcflags all=-N -l . #gosetup
flag provided but not defined: -l
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
```

Which can be the problem.

**Comment by tpasternak** [comment]
wait, but it's not even a bazel project

**Comment by kopax** [comment]
Yeah sorry i just wanted an hint. :) you can close this again ^^

**Comment by tpasternak** [comment]
Np, please migrate the project to bazel and we'll provide support here :D
