### ISSUE TITLE
Kotlin: tests for source navigation

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#323]
It would be good to be able yo verify navigation to various types of sources. (Stdlib, kt_jvm_import / kt_stdlib and ap generated) this is quite the moving target. It is easy to check against a production repo though.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
