### ISSUE TITLE
Indexing of third party libraries breaks in Go running gazelle from the terminal

### ISSUE THREAD

**Issue by blorente** [bazelbuild/intellij#3234]
## Problem

Running a Bazel command (in this case `bazel run //:gazelle`) from the CLI breaks IntelliJ indexing of Go files.

## Versions of IntelliJ

IntelliJ Ultimate 2021.3.2

## Steps To Reproduce

Repro: https://github.com/blorente/standalone-repros/tree/bazel_intellij/refresh-bug

1. Import a Bazel+Go project with the plugin (e.g. [blorente/standalone-repros:bazel_intellij/refresh-bug](https://github.com/blorente/standalone-repros/tree/bazel_intellij/refresh-bug)).
2. Observe how the symbols from `google.golang.org/grpc` are indexed, and one can go to their definition.
3. In a terminal, run `bazel run //:gazelle`. 
4. Observe how `grpc.Server` no longer resolves.

## Notes

- One can run gazelle as a standalone binary (i.e. `gazelle fix` instead of `bazel run //:gazelle`). In these cases, indexing does not break, no matter how many files Gazelle touches.
- Running `bazel run //:gazelle` doesn't seem to trigger re-indexing in the IDE.
- Indexing only seems to break for third party dependencies, particularly those imported via a workspace dependency. Internal source references seem unaffected (see the `lib` package in the example).
- Manually syncing seems to fix the issue.

My current hypothesis is that, when re-fetching the repostories for those 3rdparty dependencies, Bazel removes and recreates the files, which somehow invalidates IntelliJ's indexing.

**Comment by blorente** [comment]
On inspection, it seems pretty clear that things that wipe out the exec root are the ones that break the indexing.
I wonder if the solution is to put the resolved third party code into a different path, or have the plugin read from a more stable location.

**Comment by fkorotkov** [comment]
I think this is the same issue as #2057 which I have a fix for in https://github.com/bazelbuild/intellij/pull/3165

**Comment by blorente** [comment]
Duplicate of https://github.com/bazelbuild/intellij/issues/2057
