### ISSUE TITLE
Running BlazeFastRun on Mac Fails with local_jdk directory not found

### ISSUE THREAD

**Issue by dtaveras** [bazelbuild/intellij#3245]
https://github.com/bazelbuild/intellij/blob/f894c76e3f492cf9322a9142b43fc0cf2526b39f/java/src/com/google/idea/blaze/java/run/fastbuild/BazelFastBuildTestEnvironmentCreator.java#L28

Hoping this is a simple one. When running the BlazeFastRun command I get an error local_jdk not found. As of now I've been manually adding a symlink at that path. Is there a way to configure this path? I found fast.build.notifications.xml however it doesn't seem to be the place to make the change.

**Comment by sgowroji** [comment]
Hello @dtaveras, IF you are still looking support on the above issue. Could you please share complete steps to reproduce it. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
