### ISSUE TITLE
Properly support --symlink_prefix

### ISSUE THREAD

**Issue by joca-bt** [bazelbuild/intellij#3252]
Changing `--symlink_prefix` results in IntelliJ becoming confused. For example, our `.bazelrc` has `build --symlink_prefix=.bazel/`. This makes IntelliJ say that all our code is duplicated, i.e. that there are 2 of each file. One in the original directory `<repo>/...` and one under `<repo>/.bazel/<repo>/...`. When using the default `<repo>/bazel-<repo>/` it works fine.

The paths seem to be hardcoded in `com.google.idea.blaze.base.bazel.BazelBuildSystemProvider::buildArtifactDirectories()`.

Using plugin version 2022.01.25.0.0-api-version-212 and IntelliJ IDEA version 2021.2.2 (Community Edition) on a Java project.

**Comment by joca-bt** [comment]
No longer seems to be happening with Bazel 5.0.0, plugin 2022.06.14.0.1-api-version-221, and IntelliJ IDEA 2022.1.3 (Ultimate).

**Comment by sgowroji** [comment]
Hello @joca-bt, If you are still looking resolution for this issue, Could  you please  provide a example code to verify the above request. Thanks!

**Comment by joca-bt** [comment]
Hey, I haven't seen the problem manifest itself recently. I'll try a bit harder this week.

**Comment by joca-bt** [comment]
I think it is no longer happening. We can close and re-open again in the future if needed.
