### ISSUE TITLE
An exception from junit runner during filtering will cause an empty test.xml file to be created

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#326]
During the creation of the test model from a JUnit `Description`, if an exception occurs in the underlying runner, the model won't be created successfully, and an empty test.xml file will remain on disk.

The actual problem occurs in the underlying test runner (in this case, specs2 implementation of `getDescription` throws an exception), and during applying filtering, will cause a crash 
```
    ...
    at com.google.testing.junit.runner.junit4.JUnit4Runner.applyFilter(JUnit4Runner.java:159)
    at com.google.testing.junit.runner.junit4.JUnit4Runner.applyFilters(JUnit4Runner.java:207)
    at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:95)
    at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:144)
    at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:82)
```

Perhaps there should be some check that a model actually exists, prior to attempting to write the xml?

**Comment by brendandouglas** [comment]
Sounds like this is a bazel-side bug (with the JUnit test runner) -- the bazel intellij plugin doesn't create the xml, it just reads it after the 'bazel test' invocation returns.

**Comment by hmemcpy** [comment]
Yeah, I discovered two separate cases with this, unfortunately. An exception could be thrown during creation of the test model (by asking the underlying runner for `Description`), and when using `--test_filter`, which would cause an exception earlier (as in the stack trace above), during application of the filter to the description.
I sent a [PR to rules_scala](https://github.com/bazelbuild/rules_scala/pull/500) to gracefully handle the exception from specs2 in particular, but perhaps there should be a more general solution.

**Comment by brendandouglas** [comment]
Thanks for the details. This isn't something that can be solved in the bazel plugin (we have no control over what the test runner does, and only consume its outputs). Perhaps there's a more general solution available in bazel itself?

**Comment by hmemcpy** [comment]
Oh damn, I can't believe I did this again. I meant to open this issue in the bazel repo directly! 😳
Wow, I'm sorry, I'll open this in the correct repo! 😅
