### ISSUE TITLE
Wrong build android in windows

### ISSUE THREAD

**Issue by xtoolkit** [bazelbuild/intellij#3267]
hi
I use android studio and run this commad to build my application: `bazel build //app:qawtler`
but see use `/bin/bash` and not build

error:
```
Desugaring app/qawtler_resources.jar for Android; 0s worker
    .../java/com/google/devtools/build/android/r8:r8; 0s multiplex-worker
ERROR: C:/users/arshen/androidstudioprojects/qawtler/app/BUILD.bazel:3:15: Desug
aring app/qawtler_resources.jar for Android failed: Worker process did not retur
n a WorkResponse:

---8<---8<--- Start of log, file at C:/users/arshen/_bazel_arshen/pmw4pl22/bazel
-workers/worker-2-Desugar.log ---8<---8<---
/bin/bash: C:\Users\Arshen\_bazel_arshen\pmw4pl22\execroot\qawtler\bazel-out\x64
_windows-opt-exec-2B5CBBC6\bin\external\bazel_tools\tools\android\desugar_java8:
 command not found
---8<---8<--- End of log ---8<---8<---
```

how can i fixed this?

my build file:
```bzl
load("@rules_android//android:rules.bzl", "android_binary")

android_binary(
    name = "qawtler",
    custom_package = "io.github.xtoolkit.qawtler",
    visibility = ["//visibility:public"],
    multidex = "native",
    manifest = "AndroidManifest.xml"
)
```

#### Version information
AndroidStudio: Bumblebee | 2021.1.1 Patch 1
Platform: Windows 10 10.0
Bazel plugin: 2022.02.08.0.1-api-version-211
Bazel: 5.0.0

**Comment by sgowroji** [comment]
Hello @xtoolkit, Are you still seeing the issue with the latest intellij and bazel plugin release ? I see the above issue is fixed in [bazel](https://github.com/bazelbuild/bazel/issues/11618).

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
