### ISSUE TITLE
Run configurations not auto generated

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#33]
Consider this repository. https://github.com/dfabulich/intellij-auto-run-config

It has a blank `WORKSPACE` and a very simple `BUILD` file.

```python
java_binary(
  name='x',
  srcs=['x/src/main/java/X.java'],
  main_class='X',
)
```

`X.java` just prints hello world.

```java
public class X {
  public static void main(String[] args) {
    System.out.println("hello world");
  }
}
```

If you `bazel run x` it prints "hello world."

There's a checked-in `.bazelproject` file that explicitly names `x` as a target:
```
directories:
  .

targets:
  x
```

Now use the IntelliJ plugin to import the project.

Expected: https://ij.bazel.io/docs/run-configurations.html says:

> The IDE automatically creates run configurations for supported targets explicitly listed in your project view

So there should be an `x` run configuration autogenerated.

Actual: No run configurations were autogenerated

I'm on Ubuntu 16.04.1 64-bit, IntelliJ IDEA CE 2016.3.

**Comment by dfabulich** [comment]
In principle this could be a manifestation of issue #32 (there are some errors on project startup) but re-syncing the Bazel project works without additional errors and the run configuration is never automatically created.

**Comment by dfabulich** [comment]
I downgraded to IntelliJ 2016.2 to workaround issue #32. This issue still happens even in 2016.2.

**Comment by brendandouglas** [comment]
This is a bug in our target validation when parsing the project view. Targets should all be specified in absolute form (i.e. '//package/path:target', or '//:target'), not in relative form (':target' or 'target').

We'll update the docs to reflect this, and add validation errors in this case.

**Comment by brendandouglas** [comment]
In the meantime, you can workaround this by specifying "//:x" instead of "x" in the targets section.

**Comment by brendandouglas** [comment]
This should be fixed in the latest build.
