### ISSUE TITLE
'Compact empty middle packages' makes non-empty packages (and sources) disappear

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#331]
In this example, you can see the `java` package when this option is unchecked:
![image](https://user-images.githubusercontent.com/601206/40886236-ff2ac7f8-673c-11e8-87a3-0fbd90ccb953.png)

After checking 'Compact empty middle packages', `java` and its subfolders completely disappear:
![image](https://user-images.githubusercontent.com/601206/40886235-fc4c8a30-673c-11e8-9239-d374831933e6.png)

This happens in various scala/java projects, I was yet unable to pinpoint exact repro scenario.

**Comment by roblg** [comment]
This looks like the same issue I'm seeing from #328. However, afaict I don't have any "Compact empty middle packages" checkbox in Bazel Settings in Preferences, or any of the menus. (IntelliJ Ultimate 2018.1.2; ijwb 2018.05.07.0.2).

**Comment by jvoung** [comment]
Can you try plugin version 2018.05.21.0.0 (just uploaded to the Jetbrains repo today)? I think that has a change that will help for 2018.1.

**Comment by hmemcpy** [comment]
@jvoung I just tried it with the latest plugin - looks like you're right, I don't see the issue anymore, the feature now behaves correctly!

Closing this for now, thanks!
