### ISSUE TITLE
Bazel plugin not displaying source or test files

### ISSUE THREAD

**Issue by bkeyser** [bazelbuild/intellij#332]
### Steps to Reproduce

The following was performed with IntelliJ 2018.1.4 and Bazel-IntelliJ plugin version 2018.05.07.0.2.

1.  Clone the Bazel examples from (https://github.com/bazelbuild/examples/)
1.  Import the java-maven project
    1.  Generate the .bazelproject using the included BUILD file
    1.  Add the following settings

    Parameter | Value
    ---------- | -----
    workspace_type | java
    java_language_level | 8
    test_sources | src/test/java/*

### Expected Result

The source and test can be navigated to in IntelliJ

### Actual Result

The source file as listed in the project explorer is empty as shown in the diagram below

![image](https://user-images.githubusercontent.com/6879440/40895069-93b23f5a-676a-11e8-8ca8-7fd4b1af2532.png)

**Comment by ittaiz** [comment]
Can you check if “compact empty packages” is checked? If so I think
@hmemcpy reported a similar issue yesterday or so

**Comment by bkeyser** [comment]
Thanks @ittaiz!  That was indeed the problem.  I apologize for missing @hmemcpy's report.

**Comment by knarukulla** [comment]
We are using IntelliJ IDEA 2021.2.2 (Ultimate Edition), unable to view the project files on root folder(WORKSPACE etc).
