### ISSUE TITLE
Internal error when trying to import go project in IntelliJ

### ISSUE THREAD

**Issue by jameslan** [bazelbuild/intellij#3329]
Error:Internal error: Cannot load class com.google.idea.blaze.golang.resolve.BlazeGoPackage (
  error: com/goide/psi/impl/GoPackage,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Bazel, id=com.google.idea.bazel.ijwb, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.3/plugins/ijwb, version=2022.02.23.0.0-api-version-213, package=null, isBundled=false), packagePrefix=null, instanceId=338, state=active)
)

**Comment by cwlbraa** [comment]
I had this problem recently and I fixed it by manually specifying the `bazel` binary path (I use bazelisk) and then restarting IDEA.

**Comment by sgowroji** [comment]
Hello @jameslan, Could you please check this with latest release and let us know if you still seeing the same error. Thanks!

**Comment by jameslan** [comment]
Hi @sgowroji, verified on IntelliJ IDEA 2022.2.2 Build #IU-222.4167.29, with Bazel plugin 2022.09.20.0.1-api-version-222, the go code in the project successfully loaded within the IDE!

Thanks!
