### ISSUE TITLE
ERROR: Unrecognized option: --noexperimental_run_validations

### ISSUE THREAD

**Issue by huange1234** [bazelbuild/intellij#3349]
#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

Plus 58 more targets
Building Bazel targets...
...
ERROR: Unrecognized option: --noexperimental_run_validations
INFO: Writing tracer profile to '/private/var/tmp/_bazel_huange/d65cb94d0d8be8b904e19c4b69ebd9a7/command.profile.gz'
build invocation result: fatal_error
Sync finished

any other solution which do not need to downgrading CLion and the Bazel plugin
#### Version information
CLion: 2021.2
Platform: Mac OS X 11.3.1
Bazel plugin: 2021.11.09.0.2-api-version-212
Bazel: 1.1.0

**Comment by sgowroji** [comment]
Hello @huange1234, Could you please try the above with latest intellij and bazel plugin versions.  And reach us back with complete repro steps, if you still see the error . Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
