### ISSUE TITLE
Integration with a label indexing service

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#335]
We're developing a service that would index all known target labels, and would lookup matching labels by a given a (partial) class name or a package name.
We want to integrate it with the plugin, providing code completion and adding matching targets to existing BUILD files.

To increase the chance of this being considered for wider adoption (we're eventually going to opensource this service/API), we need to make it all configurable (i.e. service URL, possible authentication). 
We were thinking of adding a separate tab to the Bazel configuration UI in IntelliJ, and specify those features there, so they would be explicitly enabled by the user.

Do you think this is an acceptable proposal?

**Comment by brendandouglas** [comment]
That sounds great! I like the idea of auto-complete suggestions based on partial package names.

I think it's something we'd like to support internally as well. My preference would be to pull out a very general extension point in the bazel plugin, without any implementation details (e.g. an interface with methods similar to:
List<Label> matchingTargets(String fragment);

For adding matching targets to existing BUILD files, there are also the (not yet combined) extension points SourceToTargetProvider and SourceToTargetFinder.

**Comment by ittaiz** [comment]
Where would an implementation (any implementation for that matter) sit?

**Comment by brendandouglas** [comment]
Up to you -- it's easiest to put it in the bazel plugin, so that there are no versioning concerns. But a separate plugin depending on the bazel plugin would be fine to (assuming you wanted to put the extension point in the bazel plugin).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
