### ISSUE TITLE
New behavior for partial sync on folders not containing BUILD files

### ISSUE THREAD

**Issue by mp42** [bazelbuild/intellij#336]
Assume the following directory structure:

ProjectA
--> packageA
---------> ClassA.java
--> packageB
---------> ClassB.java
--> BUILD

On Bazel plugins prior to version 2018.05.21.0.0, if new classes are added to packageA or packageB I was able to partially sync those folders by right clicking on them in Intellij's project view and selecting "Partially Sync <folder name>".

On version 2018.05.21.0.0, right clicking on the folder to partially sync instead expands to `Partially Sync <folder name>:all`. It seems to just default to the `:all` target. Selecting this results in an error during the partial sync because there are no targets defined in those folders (because those folders don't have a BUILD file inside of them) and leaves the new classes unsynced.

Here's an example log when attempting to partially sync the folder packageA:
```
ERROR: (06-06 18:01:24.632) Skipping '//projectA/packageA/...:all': no targets found beneath 'projectA/packageA/'.
WARNING: (06-06 18:01:24.633) Target pattern parsing failed.
INFO: (06-06 18:01:24.835) Loading complete.  Analyzing...
INFO: (06-06 18:01:24.843) Found 0 targets...
ERROR: (06-06 18:01:24.910) command succeeded, but there were errors parsing the target pattern.
```

Is this an expected behavior change moving forward?

**Comment by brendandouglas** [comment]
Previously, it partially synced the first parent directory containing a BUILD file. Now, it tries to build all targets in the selected directory and any child packages, recursively.

Given the current behavior, the action shouldn't be shown for directories without a child bazel package. OTOH, we don't want to check this for performance reasons.

I'm inclined to leave as is -- the action description and error messages make it fairly clear what's going to happen, and what's gone wrong when there are no targets underneath the selected directory.

The previous behavior (syncing all targets in some unspecified parent directory) seems less intuitive. If a user selects packageA in your example, they're unlikely to expect packageB to be synced as well, but that's what was previously happening.

**Comment by mp42** [comment]
Ah that makes sense - slightly unfortunate that there isn't reasonable way to disable that action where not applicable.  Closing this issue then since it seems like the right thing to do.
