### ISSUE TITLE
configuration drop down menu is too narrow

### ISSUE THREAD

**Issue by brown** [bazelbuild/intellij#337]
Only about the first 40 characters of each Run/Debug Configuration name are visible in the entries of the plugin's configuration drop down menu.  That's not enough.  The menu should get wider when Run/Debug Configurations have longer names.

**Comment by brendandouglas** [comment]
This is a general IDE setting. You can change it via 'Help > Edit Custom Properties', by adding a line like:
```
run.configuration.max.name.length=100
```
then restarting the IDE.

**Comment by brown** [comment]
Thanks!  That seems to work.
