### ISSUE TITLE
Error "Cannot set package name for compiled files" when moving Kotlin file to different packe 

### ISSUE THREAD

**Issue by pettermahlen** [bazelbuild/intellij#3374]
Steps to reproduce:

1. Have a Kotlin file with two class definitions in it.
2. Drag and drop it from one package to another. 

I'm not 100% sure, but it seems to happen consistently whenever a .kt file has more than one class/interface definition in it. 

Plugin version: 2022.03.08.0.1-api-version-211 (it was also happening on the previous one)

**Comment by sgowroji** [comment]
Hello @pettermahlen, Can you share a sample repo to reproduce the above issue. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
