### ISSUE TITLE
IntelliJ doesn't recognize Scala package with hyphen in name as package

### ISSUE THREAD

**Issue by FabienLamonarca** [bazelbuild/intellij#3378]
While creating a package with an hyphen in name "scala-package" for instance intelliJ doesn't recognize this one as a package

My tree folder is like this : `my-package.src.main.scala.com.x.y.classA`
My directive in classA is `package com.x.y`

Then intelliJ doesn't recognize "_my-package_" as one, and trigger an error: 
"Package name 'com.x.y' does not correspond to the file path `my-package.src.main.scala.x.y`"

**Comment by sgowroji** [comment]
Hello @FabienLamonarca, Are you still seeing the same observation with the latest release of intellij and bazel plugin. Could you please provide more details on the above request. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
