### ISSUE TITLE
"Test sources root" (green) becomes regular blue "Sources root" after a sync

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#339]
Given a skeleton project:
WORKSPACE:
```
maven_jar(
	name='junit',
	artifact='junit:junit:4.12'
)
```
BUILD:
```
java_test(
	name='test',
	srcs=['src/test/java/com/example/MyTest.java'],
	deps=['@junit//jar'],
  test_class = "com.example.MyTest"
)
```

and a test class `MyTest`, the `java` directory will always revert to the blue "sources root" after a sync, even if manually set to "Test sources root".

This causes additional visual confusion if "Compact empty middle packages" is enabled - which causes two blue `java` directories appear one next to the other (if there's both `src/main/java/...` and `src/test/java/...`)

**Comment by brendandouglas** [comment]
Any manual changes to the project structure will be wiped on the next sync -- the intended way to mark directories as test sources is in the .bazelproject file (the `test_sources` section).

The 'compact empty middle packages' behavior should also be fixed in the latest plugin version.

**Comment by ittaiz** [comment]
Brendan,
WDYT about having the plugin mark it as test sources if a package has only
"testonly =1" targets?
We just have repositories with hundreds of test sources and manual managing
will be very hard

**Comment by brendandouglas** [comment]
We could do that, though I'd prefer not to add too much complexity to this part of the code.

'test_sources' does have limited regex support (using intellij's WildcardFileNameMatcher), so we typically handle this by having a consistent naming of directories containing tests.

**Comment by ittaiz** [comment]
I see. So I could set “.../src/test/*” or something like it?

**Comment by brendandouglas** [comment]
You can -- you'd probably want to use: `*/src/test*`

There are examples in this project's .bazelproject files.
