### ISSUE TITLE
Can't run two Bazel processes at once

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#34]
Consider this repository. https://github.com/dfabulich/two-processes

It has an empty `WORKSPACE` and two simple targets, `//x:x` and `//y:y`.

The `x` `BUILD` file declares a `java_binary`.

```python
java_binary(
  name='x',
  main_class='X',
  srcs=['X.java'],
)
```

`X.java` just sleeps for 30 seconds.

```java
public class X {
  public static void main(String[] args) throws Exception {
    Thread.sleep(30000L);
  }
}
```

The `y` target is identical to the `x` target, replacing `x` with `y`.

It's a well-established problem that you can't `bazel run` two processes at the same time, e.g. if you `bazel run x` in one tab and `bazel run y` in another tab, the `y` process will wait until `x` is finished. https://groups.google.com/forum/#!searchin/bazel-discuss/fabulich$20bazel$20run%7Csort:relevance/bazel-discuss/mS98nXz9PbY/Kcuhn0VEIQAJ

EDIT: Filed on the Bazel side as https://github.com/bazelbuild/bazel/issues/2337

The workaround recommended in that thread is to use `--script-path` to generate a script; you can use a `bazel-run.sh` wrapper script to reduce boilerplate.

Now, load up this workspace with the IntelliJ Bazel plugin, using the included `.bazelproject`.

```
directories:
  .
targets:
  //x:x
  //y:y
```

Run `x` and, while it's sleeping, run `y`.

Actual: `y` refuses to start, because `x` has a lock. Since the IDE plugin is running Bazel, there's no visible way to use the `--script-path` workaround.

Expected: The IDE should use the `--script-path` workaround for me, automatically.

**Comment by dfabulich** [comment]
I should have mentioned that I tested this on Ubuntu 16.04 and IntellJ 2016.2 (and 2016.3, which has issue #32)

**Comment by dfabulich** [comment]
You can work around this bug by using a `tools/bazel` script, documented in a comment on the corresponding issue in the `bazel` project. https://github.com/bazelbuild/bazel/issues/2337#issuecomment-276295577

**Comment by jin** [comment]
`bazel run` no longer holds a lock now. Is this still an issue?

**Comment by asad-awadia** [comment]
@jin which version doesn't hold a lock? 
```
▶ bazel version
Build label: 0.24.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Apr 2 16:32:47 2019 (1554222767)
Build timestamp: 1554222767
Build timestamp as int: 1554222767
```

I still can't do multiple runs

`bazel-run.sh` is also not really doing anything

**Comment by jin** [comment]
The Bazel server lock is still held up to the point where the executable starts running. Can you elaborate what you're trying to achieve?

**Comment by asad-awadia** [comment]
@jin what was the behaviour before then?

I have `container_push` targets that we want to deploy to AWS#ECR but because of the lock we can only do one image at a time

we are trying to parallelise it

**Comment by jin** [comment]
The previous behavior occupies the Bazel server lock while running the executable, even after the build for the executable completes.

To rephrase this, you can issue a `bazel run` after another `bazel run` once the latter finishes the `bazel build` part and starts executing the target to run. 

1) Loading - holds Bazel server lock, part of `bazel build`.
2) Analysis - holds Bazel server lock, part of `bazel build`.
3) Execution - holds Bazel server lock, part of `bazel build`.
4) Running the built executable - does not hold Bazel server lock, part of `bazel run`.

**Comment by asad-awadia** [comment]
@jin do I still need to use the `bazel-run.sh` file?

**Comment by jin** [comment]
No.

**Comment by alice-ks** [comment]
As per the last comment, there's a lockless `bazel run` in Bazel 0.12+. Nowadays, there's even Bazel 4.0. So, it seems we can close this issue.
