### ISSUE TITLE
Debugging --compilation_mode can't be set

### ISSUE THREAD

**Issue by tadeegan** [bazelbuild/intellij#340]
https://github.com/bazelbuild/intellij/blob/3bf968669adc237ee795e219daaef2e613cece13/clwb/src/com/google/idea/blaze/clwb/run/BlazeCidrRunConfigurationRunner.java#L96

Because the hard coded `-c dbg` is always after the user specificed configuration, there is no way to configure your own -c.  For example, if in my bazel run configuration, I specify -c fastbuild, the final command will look like:

`bazel build //xxx -c fastbuild -c dbg ...`

so my -c options will be be overpowered by the plugin defaults.  Building my entire binary in dbg mode isn't feasible as switching between dbg and fastbuild can take an hour to build.

**Comment by tadeegan** [comment]
Also, in general, forcing the entire dependency tree to be rebuilt with `--copt=-O0`. I wish this was configurable.

**Comment by chaoren** [comment]
We can't debug without those. If you don't use the debugger, then those won't be set. If you do use the debugger then you'll need those.

**Comment by tadeegan** [comment]
`fastbuild` still has minimal debugging information (I can still use gdb on a fastbuild binary). What I want is to turn on -g and -O0 for specific packages but not my entire dependency tree using `--per_file_copt`. This doesn't seems possible with the current state of this plugin.

https://docs.bazel.build/versions/master/user-manual.html#flag--per_file_copt
https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode

**Comment by chaoren** [comment]
@brendandouglas we could move all of those flags to overridable?

**Comment by brendandouglas** [comment]
Yep, it's on our internal bug list, and something we definitely intend to do.

**Comment by chaoren** [comment]
Looks like we already did this. Problem solved. Looks like the change didn't make the cut last week. So it'll be available in 2-3 weeks.
