### ISSUE TITLE
Language 'scala' is not supported by this plugin

### ISSUE THREAD

**Issue by exp0nge** [bazelbuild/intellij#3407]
Intellij: `2021.3.2`
Scala: `2021.3.20`
Plugin: `2022.02.23.0.0-api-version-213`

<img width="366" alt="Screen Shot 2022-04-01 at 10 40 23 AM" src="https://user-images.githubusercontent.com/11747245/161286084-da2ac6f1-9ac3-43f3-9218-6317ea5358bb.png">

workaround:

This can be resolved by following executing the following:

In Intellij, sellect: File > Manage IDE Settings > Restore Default Settings
NOTE: you will lose any Intellij settings customization you did up to this point, including additionally installed/removed plugins

Once Intellij restarts, add back the Scala and Bazel plugins. Restart again, and import your project

**Comment by sgowroji** [comment]
Hello @exp0nge, Could you please test the above with the latest release and share the update. Thanks !

**Comment by exp0nge** [comment]
> Hello @exp0nge, Could you please test the above with the latest release and share the update. Thanks !

I no longer face this, also the workaround did work before
