### ISSUE TITLE
Display name of parameterized tests is not being showed

### ISSUE THREAD

**Issue by joca-bt** [bazelbuild/intellij#3413]
When running JUnit 5 tests, the display name of `@ParameterizedTest` is not being showed when it is customized.

Here I am running my tests in the terminal using the default display name:
![default-terminal](https://user-images.githubusercontent.com/1297942/161535321-a7e6239b-8541-4798-a428-723472bb66d3.png)

Here is how it looks in the terminal using custom display names:
![custom-terminal](https://user-images.githubusercontent.com/1297942/161535317-6e6f0568-9c1a-4032-9211-0d51ae0b4232.png)

The default display name in IntelliJ:
![default-intellij](https://user-images.githubusercontent.com/1297942/161535319-68dc8c4e-5183-4b93-bc5e-6f2f4c95d916.png)

When using custom display names in IntelliJ, IntelliJ does not show them in the UI:
![custom-intellij](https://user-images.githubusercontent.com/1297942/161535311-87eb38f0-5b52-4cc3-95cc-40cefe25b25f.png)

**Comment by joca-bt** [comment]
IntelliJ is able to pick up the custom names if they start with `[{index}]`.

**Comment by sgowroji** [comment]
Hello @joca-bt, Could you please provide an example to reproduce the above error. Thanks!

**Comment by joca-bt** [comment]
I've attached a simple example.

I am using an old plugin version (2022.09.20.0.1-api-version-222) as the most recent version of the plugin breaks test display even further.

Using `@ParameterizedTest(name = "{0}")`:

On the terminal (`bazel run //:tests`):
```
└─ JUnit Jupiter ✔
   └─ DemoTest ✔
      ├─ test() ✔
      └─ parameterizedTest(String) ✔
         ├─ test name 1 ✔
         └─ test name 2 ✔
```

On IntelliJ:
![no index](https://user-images.githubusercontent.com/1297942/200785963-c52927c1-fa74-4882-a03f-7473065d175e.png)

Using `@ParameterizedTest(name = "[{index}] {0}")`:

On the terminal (`bazel run //:tests`):
```
└─ JUnit Jupiter ✔
   └─ DemoTest ✔
      ├─ test() ✔
      └─ parameterizedTest(String) ✔
         ├─ [1] test name 1 ✔
         └─ [2] test name 2 ✔
```

On IntelliJ:
![index](https://user-images.githubusercontent.com/1297942/200785974-7360ce55-04d4-4dc7-9032-4d10074260ae.png)

[intellij.zip](https://github.com/bazelbuild/intellij/files/9969243/intellij.zip)

**Comment by joca-bt** [comment]
@sgowroji updated with an example. Sorry for the delay.

**Comment by joca-bt** [comment]
not stale

**Comment by joca-bt** [comment]
This was an issue in the test runner and not the plugin.
