### ISSUE TITLE
Sync failed - Unable to find a JDK 11

### ISSUE THREAD

**Issue by pkrishnaiah** [bazelbuild/intellij#3424]
#### Description of the issue. Please be specific.
Sync failed with error message

```
Error:Unable to find a JDK 11 - Local variable syntax for lambda parameters installed.
After configuring a suitable JDK in the "Project Structure" dialog, sync the project again.

```
#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
1. Set up java project with SDK set to JDK 1.8
2. Language level set to SDK default
3. Partial Sync package
4. Note bazel build of same package works from command line. 

#### Version information
IdeaUltimate: 2021.3.3
Platform: Mac OS X 12.3
Bazel plugin: 2022.03.22.0.5-api-version-213
Bazel: 4.2.2

**Comment by pkrishnaiah** [comment]
Installing JDK 11 in the project resolves the issue, but Intellij defaults project SDK to JDK 11 after sync.

**Comment by plaird** [comment]
A user in my company reported this issue. She was able to resolve it by setting _JAVA_HOME_.

"Restarting unset the _JAVA_HOME_. Setting _JAVA_HOME_ to _path/on/the/machine/openjdk_11.0.X.Y.Z_x64_ resolved the issue."

**Comment by DeCarabas** [comment]
I am also having this problem. Why would I need or want a JDK 11 when my whole project is using JDK 8?

**Comment by mai93** [comment]
Did you try adding `java_language_level: 8` to your project view file? ([java_language_level documentation](/Users/messa/plugin-code/intellij/examples/java/greetings_project/.ijwb))

**Comment by mai93** [comment]
Closing this issue, please reopen if the described workaround did not resolve the problem.

**Comment by antoninbas** [comment]
> Did you try adding `java_language_level: 8` to your project view file?

I can confirm that this worked in my case.
The link is broken now, here is the new one: https://ij.bazel.build/docs/project-views.html#java_language_level

**Comment by dkashyn-sfdc** [comment]
This is happening again in June 2024 with recent plugin versions. 21 surfacing from nowhere and manual version spec is required to make things work.

**Comment by mai93** [comment]
@dkashyn-sfdc  is it a regression in one IDE/plugin version?

**Comment by dkashyn-sfdc** [comment]
We've got one of our hosts in a weird state when project structure had language level 11 yet for Bazel operations 21 got pulled from somewhere. 

We have 17 and 11 toolchains for our build, Bazel uses 21 runtime. So it feels like Bazel runtime toolchain got used in spite of not being used for our project.

**Comment by dkashyn-sfdc** [comment]
This was for 2024.1.3+ and for June versions of `ijwb`
