### ISSUE TITLE
ScalaTest stdout does not show under the tests output in the Test Panel

### ISSUE THREAD

**Issue by anagrius** [bazelbuild/intellij#3426]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/157210/162057430-6aec7e0c-52b3-4f1d-8983-cb98722c7af0.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/157210/162057788-d0fdd8b4-fb29-432e-8c30-1701a0bff88a.png">

**Comment by sgowroji** [comment]
Hello @anagrius, Can you provide minimal steps to reproduce the above request. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
