### ISSUE TITLE
Remove "experimental" from two build_event_binary_file build flags.

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/intellij#345]
Currently, there are two `build_event_binary_file flags` are added as build flags. They are listed as experimental. According to the Bazel source code, these have been upgraded from experimental to regular flags, see [build_event_binary_file](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/transports/BuildEventStreamOptions.java#L56)
```java
  @Option(
      name = "build_event_binary_file",
      oldName = "experimental_build_event_binary_file",
      ...
  )
```

and [build_event_binary_file_path_conversion](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/transports/BuildEventStreamOptions.java#L67)
```java
  @Option(
      name = "build_event_binary_file_path_conversion",
      oldName = "experimental_build_event_binary_file_path_conversion",
      ...
  )
```

### where they are set in this project: 
The [experimental_build_event_binary_file](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolUtils.java#L52) is declared here
```java
  /** Returns a build flag instructing blaze to write build events to the given output file. */
  public static ImmutableList<String> getBuildFlags(File outputFile) {
    return ImmutableList.of(
        "--experimental_build_event_binary_file=" + outputFile.getPath(), LOCAL_FILE_PATHS);
  }
```
and the `LOCAL_FILE_PATHS` is set to [`--noexperimental_build_event_binary_file_path_conversion`](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolUtils.java#L30) here
```java
  // Instructs BEP to use local file paths (file://...) rather than objfs blobids.
  private static final String LOCAL_FILE_PATHS =
      "--noexperimental_build_event_binary_file_path_conversion";
```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
