### ISSUE TITLE
Non-bazel project gets added a bazel pre-build task during Run

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#346]
This is a possible bug caused by #288, will investigate and update with more information.
cc @ittaiz

**Comment by hmemcpy** [comment]
Looks like `DeployableJarRunConfigurationProducer`, which extends `BlazeRunConfigurationProducer` (and, supposedly, handles checking whether or not it's a Bazel project) is at fault here. This needs further investigation, otherwise this bug affects any newly created `ApplicationConfiguration` configurations.

**Comment by brendandouglas** [comment]
The before-run task needs to check whether the configuration is produced by DeployableJarRunConfigurationProducer (and may as well also check whether it's a bazel project). I've made that change for the next release.
