### ISSUE TITLE
Test names (from specs2) are incorrectly displayed in the runner

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#347]
![image](https://user-images.githubusercontent.com/601206/41664060-84f21b7a-74ad-11e8-839d-e74615522a39.png)

the `::` part should be trimmed.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
