### ISSUE TITLE
Resolve Python SDK by looking for py_toolchain

### ISSUE THREAD

**Issue by manageryzy** [bazelbuild/intellij#3478]
I found there is only an default system SDK resolver of `PySdkSuggester`. I'm working on a project that cpython was bootstraped during build. So it is nice for me to to have this function.

I have no idea about how to get correct toolchain selection for python target in a project. I just assueme all targets shares a common toolchain in a WORKSPACE. So after configure py_toolchain rule target label in plugin. It is easy to get infomation about toolchains.

So I have already implemented these function in [my folk](https://github.com/manageryzy/intellij/tree/py-resolver).  I found there is no way to get PyInfo from bazel project sync data. So I query every targets of py_library in workingsets.

**Comment by sgowroji** [comment]
Hello @manageryzy, Could you please respond if you are still looking support on the above issue. Thanks!

**Comment by caseyduquettesc** [comment]
Seems related to https://github.com/bazelbuild/intellij/issues/2447

**Comment by manageryzy** [comment]
I did implementation this feature in my folk. But my folk plugin does not work well in every situation.
