### ISSUE TITLE
Intellij red on bazel CI since 

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/intellij#349]
Hi all,
intellij is red on bazel ci, thanks for looking into it!

Log: https://buildkite.com/bazel/intellij-plugin/builds/415
Example error:
```
ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-5p57-1/bazel/intellij-plugin/intellij_platform_sdk/BUILD:311:1:
 no such package '@intellij_ce_2018_1//': 
    Error downloading [https://download.jetbrains.com/idea/ideaIC-2018.1.3.tar.gz] to 
      /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/61ef28eb6747e26beaa5c0294f776c0c/external/intellij_ce_2018_1/ideaIC-2018.1.3.tar.gz: 
        Checksum was 754cfdc24088621854e428f42e1500111fd185587b4ce5db05e65fb917d24573 
        but wanted 2fbbc2ad29082ccdda0422fa082556c180eb80f0d7238865604a49855e5bbb68
        and referenced by '//intellij_platform_sdk:terminal'
```
Broken (I believe) by https://github.com/bazelbuild/intellij/commit/6aae6733c4a770e62775077fe197309e2bd57df0

**Comment by mhlopko** [comment]
CC @brendandouglas just in case it slipped under the radar... Thanks!

**Comment by brendandouglas** [comment]
Thanks for the reminder -- I fixed upstream, but forgot to apply here.

By the way, do you know if it's possible to whitelist certain authors so we don't need to click 'verify pull request' (and wait for the results) before every merge from upstream?

**Comment by mhlopko** [comment]
I don't, but I'm sure our github hero @buchgr does :)

**Comment by buchgr** [comment]
@brendandouglas yep it is. just add them as collaborators of the intellij project (In settings)

**Comment by brendandouglas** [comment]
Thanks @buchgr, we've done that, but it doesn't work for our copybara syncs from piper (e.g. https://github.com/bazelbuild/intellij/pull/353). The author (bazelbuild-intellij) is in the collaborators list, with write access.

**Comment by chaoren** [comment]
The last time I asked, this was the reply from @buchgr :

> this is a known bug in our CI setup. The automatic unblocking of builds only works when sending a PR from a Github fork. It appears you are creating feature branches directly on the upstream project. See https://github.com/bazelbuild/continuous-integration/issues/226

That issue is still open.

**Comment by chaoren** [comment]
Looks like this is fixed.
Today's builds didn't require unblocking: https://buildkite.com/bazel/intellij-plugin/builds/548
(while yesterday's did: https://buildkite.com/bazel/intellij-plugin/builds/546)
