### ISSUE TITLE
Cannot set breakpoint in CLion

### ISSUE THREAD

**Issue by taegeonum** [bazelbuild/intellij#3499]
I try to debug tensorflow using CLion but cannot set breakpoint. 
When I run a python process, attach gdb, and try to set breakpoint, it says "The breakpoint will not currently be hit..."

The breakpoint works well if I do not use bazel plugin. (If I do not import tensorflow with bazel plugin in Clion)
Do you know why it isn't working?

**Comment by dav1d-wright** [comment]
I am currently seeing the same issue, does anybody know how to fix this?

**Comment by jesseschalken** [comment]
Put in `~/.gdbinit`

```
set auto-load local-gdbinit on
add-auto-load-safe-path /
```

Then put in `.gdbinit` in your repo root

```
directory .
directory bazel-tensorflow
```

The two `directory` lines might need to be in the opposite order, I can't remember.

**Comment by sgowroji** [comment]
I'll close the issue. Let us know if you are still looking resolution for the above issue.

**Comment by mikemykhaylov** [comment]
Can reproduce on CLion 2022.3.3 and Bazel Plugin 2023.02.07.0.1-api-version-223 with LLDB, breakpoints are skipped

**Comment by nicmeyer** [comment]
Also experiencing this problem using CLion 2022.3.3 and Bazel Plugin 2023.02.07.0.1-api-version-223, and I did try the suggestion above.

**Comment by kishorenc** [comment]
@nicmeyer did you get a chance to figure this out?
