### ISSUE TITLE
Add ability to add custom skylark rules to the intellij-compile-java output group

### ISSUE THREAD

**Issue by ghost** [bazelbuild/intellij#351]
I apologise if this is already possible, but, I have been unable to find a way to do this.

I have added a custom rule to package my spring boot applications.  It very closely resembles this gist: https://gist.github.com/Zetten/4918d56da9e4edb7bdc7192b9f648b8f

As a result, I have a BUILD file that looks like this:

```
load("//tools/spring-boot:spring-boot.bzl", "boot_jar")

java_library(
    name = "hello-world-jar",
    srcs = [
        "Application.java",
        "Controller.java"
    ],
    deps = [
        "//third_party/java/generated/org/springframework/boot:spring_boot_starter_web",
    ]
)

boot_jar(
    name = "hello-world",
    target = ":hellow-world-jar"
)
```

When I build in intellij, the `java_library` rule runs correctly, but, the boot_jar rule is not run because it is not in the `intellij-compile-java` output group.

I'm hoping there is just something I can do to add the `boot_jar` rule to the output group, and I just haven't been able to figure out what that is.

If there isn't anything that can be done, then I would like to request that that plugin somehow support this.  If that is not possible, I would be happy enough if I could have the option to run the compile command without any output groups.

Thank you for considering this request.  If more man-power is needed to get this done, I'd be happy to volunteer my services if someone can point me at where to start.

**Comment by akowpak-ssimwave** [comment]
Thanks for the input.  I will give it a try.

**Comment by akowpak-ssimwave** [comment]
I played with this for a few hours and haven't been able to come up with anything that works.  I ended up with this:

```
def _boot_jar_impl(ctx):
  deps = ctx.attr.target.java.transitive_runtime_deps + ctx.attr._spring_boot_loader.java.transitive_runtime_deps

  args = ctx.actions.args()
  args.add(ctx.attr.include_launch_script)
  args.add(ctx.file.target.path)
  args.add(ctx.outputs.executable.path)
  args.add([d.path for d in deps])

  ctx.actions.run(
      inputs = deps + [ctx.file.target],
      outputs = [ctx.outputs.executable],
      executable = ctx.executable._spring_boot_packager,
      arguments = [args],
  )

  java_provider = java_common.create_provider(
      use_ijar = False,
      source_jars = [ctx.file.target],
      transitive_runtime_jars = deps
  )

  return struct(providers = [java_provider])


spring_boot_jar = rule(
    attrs = {
      "target": attr.label(allow_single_file=[".jar"]),
      "include_launch_script": attr.bool(),
      "_spring_boot_loader": attr.label(allow_single_file=[".jar"], default="//third_party/java/generated/org/springframework/boot:spring_boot_loader"),
      "_spring_boot_packager": attr.label(executable=True, cfg="host", default="//tools/spring-boot:spring_boot_packager"),
    },
    fragments = ["jvm"],
    host_fragments = ["jvm"],
    implementation = _boot_jar_impl,
    executable = True
    
)
```

Good chance I'm doing something wrong, but, I've used up all the time that I have to work on this :).  If anyone stumbles upon this issue in the future and has a working solution, I'd love to hear about it.  Otherwise, maybe I'll revisit this next time I have free time.

**Comment by ittaiz** [comment]
Shouldn’t you also add ctx.attr._spring_boot_loader.java to the JavaInfo
provider you’re creating?

**Comment by akowpak-ssimwave** [comment]
I am guess that I probably should be doing this, but, unfortunately, I don't quote understand what `cxt.attr._spring_boot_loader.java` is, or how I would go about adding it the the `JavaInfo` provider.

I'm learning all of this as I go, so, if there are other docs that I can read, or any other helpful examples, I'd appreciate it.  I've been searching through the kotlin and scala repos, but, perhaps I've missed something.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
