### ISSUE TITLE
Is it possible to set the --override_repository flag in IntelliJ plugin?

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/intellij#352]
We do local development with multiple bazel repos (internal mono-repo, multiple open source projects). I can't figure out how to add this flag to the IntelliJ config for the bazel project...

**Comment by dhalperi** [comment]
Ideally, I'd get all such repositories into the same IntelliJ editor so that I can co-develop them.

**Comment by brendandouglas** [comment]
You could add `sync_flags` or [`build_flags`](https://ij.bazel.build/docs/project-views.html#build_flags) to your .bazelproject file.

Alternatively, you could set up these flags in a client-specific [bazelrc](https://ij.bazel.build/docs/project-views.html#build_flags).

**Comment by brendandouglas** [comment]
The plugin doesn't support multiple source repositories in a single project though -- you'd need one project per repository.

**Comment by dhalperi** [comment]
> The plugin doesn't support multiple source repositories in a single project though -- you'd need one project per repository.

Ack, hmm, thanks. That's probably a showstopper, if I can't (say) use IntelliJ to find consumers of public APIs across repositories or to perform automated refactorings globally.

**Comment by brendandouglas** [comment]
You could find usages across repositories, but yes, editing actions like refactorings are restricted to the current project.

**Comment by excavador** [comment]
We need some way to develop multiple local bazel repositories.
Right now it's really hell to switch between several IDEA windows

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
