### ISSUE TITLE
Feature Request: Provide ability to switch between --config flags

### ISSUE THREAD

**Issue by ghost** [bazelbuild/intellij#354]
By default, we use gcc to build our C++ code, but, we also enforce that our code compiles and passes tests with clang.  To use clang, we use the flag `--config=clang-5.0`.  Currently, pressing CTRL+F9 in CLion will cause bazel to build using gcc.  In order to build with clang, I've defined a run configuration that has flags identical to the ones used by the default build, plus the `--config` flag.

This works, but, it doesn't scale great.  It means that for each bazel command I want to define (i.e. I have a "test all" command), I need to make a copy of that for each `--config` that we support.  Ideally, there would be a drop down that would let me choose between any configs that our build system may support.  It would then apply that config with CTRL+F9 or with any Run Configuration.

I expect that this is super low priority and am not counting on it being implemented any time soon, but, still figured I would request.  Thanks.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
