### ISSUE TITLE
Error while building apollo project using CLion 

### ISSUE THREAD

**Issue by GPrathap** [bazelbuild/intellij#356]
Environment :- Build label: 0.5.3, CLion: clion-2018.1.5, Bazel plugin versiion: 2018.06.11.0.3

I am trying to build  [apollo](https://github.com/ApolloAuto/apollo) project in CLion where it is giving this error message, 

```
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling
INFO: Loading package: @local_config_xcode//
ERROR: /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/external/intellij_aspect/intellij_info_impl.bzl:318:43: name 'cc_common' is not defined (did you mean 'java_common'?).
ERROR: Extension 'intellij_info_impl.bzl' has errors.
INFO: Found 1651 targets...
INFO: Building...
ERROR: command succeeded, but not all targets were analyzed.
INFO: Elapsed time: 2.269s, Critical Path: 0.00s
Prefetching genfiles...
Prefetching files...
Computing directory structure...
Committing project structure...
Workspace has 0 libraries
Workspace has 2 modules
Sync was successful, but there were BUILD file errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Blaze > Sync > Expand Sync to Working Set' and try again.
Updating in-memory state...
0 unique C configurations (0 reused), 0 C targets
```
Any help regarding this is appriciated.

**Comment by jvoung** [comment]
cc_common comes from bazel:
https://docs.bazel.build/versions/master/skylark/lib/cc_common.html
https://github.com/bazelbuild/bazel/blob/95a40bea2d0488ba3afc803b9082b16cadef1deb/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/cpp/CcModuleApi.java

It's fairly new. Can you upgrade to a newer bazel version?

**Comment by GPrathap** [comment]
Yeap, sorrrrry to make a new issue. I upgraded to 0.15.x and it gave a new set of errors. But I was able to make them fixed. So you can close this issue.  :+1:

**Comment by jvoung** [comment]
No worries, glad you got things working!

**Comment by jokla** [comment]
Hi @GPrathap are you using docker?  Or are you working directly on the host pc?

**Comment by GPrathap** [comment]
I was trying on using docker ubuntu 16:04. I did not work out for me. There were lots of dependencies were to update. I just gave up.
