### ISSUE TITLE
Directory named build

### ISSUE THREAD

**Issue by joetoth** [bazelbuild/intellij#357]
I have a rule in my WORKSPACE for snappy
new_local_repository(
    name = "snappy",
    build_file = "//third_party:snappy.BUILD",
    path = "third_party/snappy/build",     <--- problem
)

third_party/snappy.BUILD 
cc_library(
  name = "snappy",
  hdrs = glob(["include/*.h"]),
  srcs = ["lib/libsnappy.a"],
  includes = ["include"]
)

If I compile everything to a directory called 'build' it seems that the intellij bazel tries to treat it specially and compile it.
ERROR: Skipping '//third_party/snappy:all': while parsing '//third_party/snappy:all': no such package 'third_party/snappy': BUILD file not found on package path.

If I rename the directory to anything but 'build', refreshing the project works fine.

**Comment by gjasny** [comment]
Does naming your build file `BUILD.bazel` work?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
