### ISSUE TITLE
"Run arbitrary main" configuration should not be created if a matching bazel_binary exists

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#358]
After adding #288, there's now a situation where trying to run a main that already has a `bazel_binary` target for it, will also create the deployable-based run.
The latter should be disabled in such situations.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
