### ISSUE TITLE
support "inject language reference" action and language annotations on multi strings in the build language

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#359]
use-case make it easy to write writing complex scripts (bash / python) in skylark files. 

intellij has support for annotating strings with their language type and multi strings temporarily or permanently by placing a annotation above the multi string expression. Once intellij knows the language type the multi-string / string is treated as an embedded language.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
