### ISSUE TITLE
go_library's with cgo enabled are not present in .project/.gopath

### ISSUE THREAD

**Issue by bithoarder** [bazelbuild/intellij#360]
OS: Ubuntu 17.10
Intellij plugin:  2018.06.11.0.3
Bazel: 0.15.0
IntelliJ IDEA: 2018.1.5 (ULTIMATE)

This prevents Intellij from seeing the files and suggesting code completion.
The example BUILD file below deponstrates

Example build file that shows the problem, when the line "cgo = True" is commented out, Intellij will synchronize the project and the test_???.go is linked under .project/.gopath/somewhere.net/test. But when cgo=True is enabled the file vanishes from the .gopath.

load("@io_bazel_rules_go//go:def.bzl", "go_prefix", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["test.go"],
    cgo = True,
    importpath = "somewhere.net/test",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "test",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

**Comment by chaoren** [comment]
Same issue as https://github.com/bazelbuild/rules_go/issues/1251.
The ctx.rule.attr.srcs is just empty for `go_library` with `cgo = True`.

**Comment by promiseofcake** [comment]
This is still affecting the current Goland / Bazel Plugin releases.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
