### ISSUE TITLE
"Scanning files to index" never finish (tar with hard links)

### ISSUE THREAD

**Issue by brt-alexei** [bazelbuild/intellij#3600]
When one of the external dependencies referenced by http_archive is a tar that contains hard links, "scanning files" is incredibly slow and never finish. 

These lines in a log file indicate that fsnotifier is unhappy; 

`2022-05-11 22:37:25,828 [ 105981]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: /home/user/.local/share/JetBrains/Toolbox/apps/Goland/ch-1/212.5712.34/bin/fsnotifier 
2022-05-11 22:37:30,367 [ 110520]   WARN - pl.local.NativeFileWatcherImpl - table error: collision at 262112 (new /home/user/.cache/bazel/_bazel_user/7d43dab3d0cc664965f875a807583f99/external/compiled_sysroot_aarch64/bin/bzcat, existing /home/user/.cache/bazel/_bazel_user/7d43dab3d0cc664965f875a807583f99/external/compiled_sysroot_aarch64/bin/bunzip2) 
2022-05-11 22:37:30,586 [ 110739]   WARN - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 3 
2022-05-11 22:37:30,586 [ 110739]   WARN - api.vfs.impl.local.FileWatcher - File watcher failed repeatedly and has been disabled 
20`

Quick search shows that it was a known problem for IDEA. https://youtrack.jetbrains.com/issue/IDEA-126491

Somehow it is extra critical for IDEA with bazel plugin starting version 2021.3. Older versions behave differently.

**Comment by jalkjaer** [comment]
I have tried the patch the fsnotifier as suggested in 
https://youtrack.jetbrains.com/issue/IDEA-126491/File-watcher-failed-to-start-table-error-collision-messages-in-the-log#focus=Comments-27-5914263.0-0
the above error dissapears, but the "scanning files" stall is still there.

**Comment by kaaquist** [comment]
:+1: I see that error too. Did not try the patch suggested in the link above.

**Comment by jalkjaer** [comment]
> Yes, patch helped with non bazel projects and with previous versions of IDEA (2021.3 and before)
I'm on 2022.1.2 and had to apply the patched ver in order for the fsnotifier to stay up when there are multiple symlinks pointing to the same file

**Comment by stdll00** [comment]
Have you try `build --symlink_prefix=/` to suppress `bazel-*` symlinks? 
This seems good workaround in my local env.

`.bazelrc`
```
build --symlink_prefix=/
```
Environment: 
IntelliJ 2022.1.4
MacOS(M1Pro)

**Comment by sgowroji** [comment]
Hello @brt-alexei, Could you please respond if you are still looking support for the above issue. And have you tried the above suggested workarounds. Thanks!

**Comment by brt-alexei** [comment]
Thank you for follow up. 

Somehow I've discovered that issue was linked to enabled "Python Community Edition" plugin. Once I've disabled it, scan passed through. Yet, I cannot reproduce the issue aymore with latest version of Idea and the plugin.
