### ISSUE TITLE
Bazel option not available in Menu and toolbar after installing plugin in IntelliJ

### ISSUE THREAD

**Issue by fivetran-mandeepsingh** [bazelbuild/intellij#3613]
After installing bazel plugin, bazel option is not available in Menu bar or the toolbar as it used to earlier.
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/83605042/168802911-0256cada-5a1a-4e98-902c-34228ef15618.png">
Bazel plugin version: 2022.02.23.0.0-api-version-212
Bazel version: 4.2.2
IntelliJ IDEA version: 2021.2.3

I tried with different (but compatible) versions of IntelliJ IDEA and bazel plugin as well but the problem still persists.

Bazel 4.2.2 is installed on my system and Bazel settings in IntelliJ are also set correctly:
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/83605042/168803698-901115b0-00b2-4a9e-ab6c-753e513340da.png">

**Comment by fivetran-mandeepsingh** [comment]
I think I found the reason behind this.
My project did not already have .ijwb folder when I first opened it in IntelliJ. Due to this even after installing bazel and bazel plugin, my project was not being detected as a bazel project and hence bazel options were not available in menu and toolbar.
I navigated to "File"->"Import Bazel Project" and provided my WORKSPACE and BUILD file paths and again opened the same project. And Voila! Now my project is detected as a bazel project and I get bazel options in menu and toolbar.

**Comment by jfirebaugh** [comment]
I had the same problem but that solution doesn't work for me. I just get two projects: the original one (no Bazel menu shows up) and a new one with .jwb extension and no files.

**Comment by matthewjh** [comment]
> I had the same problem but that solution doesn't work for me. I just get two projects: the original one (no Bazel menu shows up) and a new one with .ijwb extension and no files.

Same for me.

**Comment by trinque** [comment]
This bug still exists. I'm currently experiencing it in a Github Codespace with IntelliJ UE. I don't see any relevant backtraces in either stdout.log or stderr.log. There is only this mention of starting an incremental sync:

```
2023-11-25 15:33:13,429 [  19296]   WARN - #c.i.o.a.i.ActionUpdater - 361 ms to grab EDT for IncrementalSyncProjectAction#update@MainToolbar (com.google.idea.blaze.base.sync.actions.IncrementalSyncProjectAction)
```

There are no Bazel icons nor actions in the menu. I've got an .ijwb folder, and this project works with the Bazel plugin in local development, and even when using SSH remote access to another machine (but not a devcontainer in a codespace). I'd be happy to provide more debugging information if someone can direct me where to look. Thank you.

**Comment by trinque** [comment]
This is not a resolved issue. This plugin does not work in devcontainers, which makes it unusable for many people.
