### ISSUE TITLE
Spurious invisible warnings on WORKSPACE and BUILD files

### ISSUE THREAD

**Issue by the-nick-of-time** [bazelbuild/intellij#3617]
![intellij bazel spurious warnings](https://user-images.githubusercontent.com/16628713/169170988-b797e37f-4d27-410a-9d46-e4dcfe599bc2.png)

WORKSPACE and BUILD files are marked with a weak warning on every keyword argument. These warnings have no text associated with them.

**Comment by sgowroji** [comment]
Hello @the-nick-of-time, If you are still looking support for the above issue. could you please provide more details like minimal steps to reproduce it and sample code to test. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
