### ISSUE TITLE
Allow a way to disable auto-exclude of `file://$MODULE_DIR$/..`

### ISSUE THREAD

**Issue by thewoolleyman** [bazelbuild/intellij#362]
The plugin automatically adds the following exclusions:

```diff
diff --git a/.project/.blaze/modules/.project-data-dir.iml b/.project/.blaze/modules/.project-data-dir.iml
index 7ec45ac..1badedb 100644
--- a/.project/.blaze/modules/.project-data-dir.iml
+++ b/.project/.blaze/modules/.project-data-dir.iml
@@ -2,7 +2,10 @@
 <module external.system.id="Blaze" type="JAVA_MODULE" version="4">
   <component name="NewModuleRootManager">
     <exclude-output />
-    <content url="file://$MODULE_DIR$/../.." />
+    <content url="file://$MODULE_DIR$/../..">
+      <excludeFolder url="file://$MODULE_DIR$/.." />
+      <excludeFolder url="file://$MODULE_DIR$/../../.idea" />
+    </content>
     <orderEntry type="inheritedJdk" />
     <orderEntry type="sourceFolder" forTests="false" />
     <orderEntry type="library" name="kotlin-stdlib_b9131a" level="project" />
```

I like to check in most of my `.idea` folder contents, including `*.iml` files, and this prevents me from doing so (or else I have to keep throwing away this change).

Yes, I know it's not common to commit `.idea`, but it's possible with some effort and very useful if you switch machines or have multiple people working on a project.

So, any chance (of accepting a PR) to provide a way to disable this auto-exclusion?

Thanks,
-- Chad

**Comment by chaoren** [comment]
You're using git I presume? 

> and this prevents me from doing so

Do you mean you can't commit the file through the IDE's git operations? Can't you just commit the file on command line?

**Comment by thewoolleyman** [comment]
You know what, on second thought this request doesn't make sense.  There's no need to NOT exclude these, so I can just commit these changes.  Wasn't thinking it through when I wrote the issue.

Sorry for the noise, closing this issue :)
