### ISSUE TITLE
Resolve JDK by looking for a java_toolchain

### ISSUE THREAD

**Issue by emidln-imc** [bazelbuild/intellij#3625]
Rather than manually setting up my JDK in my project settings in IntelliJ, it would be nice to discover the JDK that bazel uses and configure this JDK. In particular, since my JDK can change based on a config in my .bazelrc (11 vs 17) having the JDK determined via the sync process would allow for a seamless experience for the user.

**Comment by mai93** [comment]
I think this is already supported, it is mentioned in the [plugin documentation ](https://ij.bazel.build/docs/project-views.html#java_language_level). I verified this on the case you described with this [example project](https://github.com/bazelbuild/intellij/tree/master/examples/java/greetings_project) by default jdk-11 is used and when I add `build --java_language_version=17` to the `.bazelrc` jdk 17 is selected. If you have a specific case where this is not working, please provide us with more details.

**Comment by emidln** [comment]
not stale
