### ISSUE TITLE
IDEA autocomplete of go generated sources

### ISSUE THREAD

**Issue by slamdev** [bazelbuild/intellij#3635]
If `go_library` is created via custom rule, IDEA fails to autocomplete generated sources.

sample project: https://github.com/slamdev/bazel-go-gen-idea-autocomplete/
idea version: `Build #IU-221.5591.52, built on May 10, 2022`
bazel plugin version: `2022.05.03.0.1-api-version-221`

custom rule has [go_generated_srcs](https://github.com/slamdev/bazel-go-gen-idea-autocomplete/blob/main/defs.bzl#L30) output group.

**Comment by sgowroji** [comment]
Hello @slamdev, If you are still looking for support on the above issue. Could you please provide more details of it. Thanks!

**Comment by slamdev** [comment]
hi @sgowroji ! yeah, you can clone the project above, run `bazel build //...` and see that IDEA\GoLand marks `rulew.PrintRule()` call in `main.go` file as undefined.
