### ISSUE TITLE
Invalid test_filters generated for JUnit5 tests

### ISSUE THREAD

**Issue by deadmoose** [bazelbuild/intellij#365]
Example test case w/ detailed README in https://github.com/deadmoose/junit5_from_bazel

TLDR:
The Intellij plugin generates `--test_filter`s like `com.deadmoose.foo.FiveTest#foo$` when, for a JUnit5 test, it should really be `FiveTest#foo()$`

**Comment by brendandouglas** [comment]
We don't yet support JUnit5. It's something we'd like to add support for, but has never been a high priority.

**Comment by brendandouglas** [comment]
Closing as a dupe of https://github.com/bazelbuild/intellij/issues/245
