### ISSUE TITLE
Allow user-defined rules  in `New Bazel package` action

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#367]
Hi,
Currently when one chooses `New Bazel package` action it can choose from a small list of rules (java_library, android_library, cc_library, cc_binary, proto_library).
I'd like to be able to type my own rule in there.
Alternatively allow choosing no rule.

**Comment by ittaiz** [comment]
@brendandouglas wdyt?

**Comment by brendandouglas** [comment]
I've been meaning to just remove the rule name/type fields entirely, and just create an empty BUILD.bazel file.

The rule type/name stuff is a throwback to when we didn't have basic autocomplete support in BUILD files.

**Comment by ittaiz** [comment]
Sounds good. From my discussions with people they indeed expect to just be
able to create an empty BUILD.bazel file.
Just as an additional piece of information an alternative request we’ll try
to tackle internally is have a scaffolding/live template solution for new
packages.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
