### ISSUE TITLE
In Android Studio, When target is recognized as an android_binary,  what the bazel-plugin do to build command and android_binary()?

### ISSUE THREAD

**Issue by wingdi** [bazelbuild/intellij#3678]
Because when target is an android_binary, the built apk works fine, but when target is aar, when the aar imported into an android project, the generated apk don't work normally .

<img width="827" alt="0EB4CF0C06037E15201117D49DEA7807" src="https://user-images.githubusercontent.com/25787391/173210342-dd2b9d2c-cfbd-4074-b519-49ef472d48c0.png">

**Comment by sgowroji** [comment]
Hello @wingdi, Could you please elaborate your query with complete details and minimal steps to reproduce it. Thanks!

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
