### ISSUE TITLE
Allow customizing the default build file extension

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#368]
I'd really love to only have `BUILD.bazel` files due to OS X case insensitivity and conflicts.
Intellij plugin creates `BUILD` files and I have to remember to rename them.
It would be really cool to configure in the settings to use `BUILD.bazel` and forget about it.

Thanks!

**Comment by ittaiz** [comment]
@brendandouglas wdyt?
see also https://github.com/bazelbuild/bazel/issues/4517 for recommendation to use BUILD.bazel by default

**Comment by brendandouglas** [comment]
Done for the release after next.

**Comment by brendandouglas** [comment]
I've just gone with using BUILD.bazel by default for bazel in the one place the plugin creates BUILD files (the 'new package' action).

**Comment by ittaiz** [comment]
great, thanks!
