### ISSUE TITLE
Improve performance of Java package parser by making it a Bazel worker

### ISSUE THREAD

**Issue by keithl-stripe** [bazelbuild/intellij#3685]
Here at Stripe, project sync performance is a big issue, and costs our engineers a lot of time. We found that project syncs often spend 10-30% of the overall build time just doing "package parsing," which is used when constructing IntelliJ project source roots.

The package parser tool is a Java application and the majority of the time spent executing it is in starting up the JVM and loading classes. It would benefit from being a Bazel worker.

**Comment by Bencodes** [comment]
This is also something that we've seen here at Lyft in our Android mono repo. We also built out worker support for all of the JVM processes inside the aswb plugin and have seen a ton of performance improvements in sync times as a result.

**Comment by mai93** [comment]
Closing as https://github.com/bazelbuild/intellij/pull/3686 is merged

**Comment by Bencodes** [comment]
Created a separate issue to track worker support in the other two JVM based actions https://github.com/bazelbuild/intellij/issues/4860
