### ISSUE TITLE
Unable to use environment variables/macros in Bazel flags

### ISSUE THREAD

**Issue by govisi** [bazelbuild/intellij#3690]
I tried to use Intellij macros in bazel flags but it doesn't seem to work, is there any support or workaround for this? Has anyone tried?
ex: `--instrumentation_filter=$MODULE_WORKING_DIR$`

**Comment by mai93** [comment]
I'm not sure but maybe this can help: https://ij.bazel.build/docs/run-configurations.html#variable-expansion
So you example should be: --instrumentation_filter=${MODULE_WORKING_DIR}

**Comment by mai93** [comment]
I'll close this issue. If the suggested solution is not working, please reopen.
