### ISSUE TITLE
MSVC not found on Windows.

### ISSUE THREAD

**Issue by dpeter99** [bazelbuild/intellij#3695]
Hi!
I'm getting this error when running inside CLion but not when I run the same command in cmd.
![image](https://user-images.githubusercontent.com/7725817/174441766-1f913f1f-3c59-4069-bb1b-25a01967ce2c.png)
My plugin version is: ``2022.05.31.0.0-api-version-221``

**Comment by kshyanashree** [comment]
Hi there! Thank you for raising this issue. We're doing a clean up of old issues and will be closing this one since it seems to have stalled. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
