### ISSUE TITLE
support Golang

### ISSUE THREAD

**Issue by sjamesr** [bazelbuild/intellij#37]
Is there any interest in support Golang with the IntelliJ plugin? It would be nice to open a Bazel project with [Gogland](https://www.jetbrains.com/go/) and have everything work.

**Comment by brendandouglas** [comment]
We have no plans to support any other IDEs (beyond IntelliJ, Android Studio, and CLion). However we are looking at adding support for additional languages (including Go) within these IDEs.

There's a Go plugin for IntelliJ which seems to be quite widely used (at least, if the download numbers are anything to go by).

If we do support Go, it will likely be by integrating with that plugin (unless JetBrains end up providing their own Go plugin for IntelliJ, similar to the situation with PyCharm and the IntelliJ python plugin).

**Comment by sjamesr** [comment]
Gogland is a Jetbrains fork of the Go plugin for IntelliJ. It is a similar product to CLion (based on the same codebase as IntelliJ, but branded differently). I imagine that the main contributors to the open source plugin, who work for Jetbrains, will now focus on the paid Gogland product, leaving the open source plugin behind.

**Comment by brendandouglas** [comment]
Yes, that's our expectation too. We're certainly open to reconsidering support for additional IDEs in the future (perhaps when Gogland has sufficiently diverged from the open-source plugin).

**Comment by brendandouglas** [comment]
Hi @sjamesr, an update on this issue -- we're not planning to support the Gogland IDE, but we do intend to add support for the corresponding IntelliJ UE plugin, which JetBrains' intend to release along with the public EAP (https://www.jetbrains.com/help/go/1.0/faq.html).

I expect they'll have basically identical features, similar to the python situation.

**Comment by brendandouglas** [comment]
The latest code drop has basic support for Go projects, integrating with the Go plugin.

When JetBrains release their own Go plugins, we're planning to expand support.
