### ISSUE TITLE
Documentation Tooltip for Rules

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/intellij#3702]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/12849602/175108095-f9de0f8a-1cf2-4fa7-a6b3-e561b95d0daa.png">

If anyone wants to post any ideas about how to implement, would be glad to take a look.

**Comment by mai93** [comment]
Hello @aryeh-looker, can you give us an example of a project where you see this issue? I can see the documentation when I try with [this example kotlin project](https://github.com/bazelbuild/intellij/tree/master/examples/kotlin/simple_project)

![image](https://user-images.githubusercontent.com/70515749/192058920-4b402934-c47c-4909-ab71-57d2c6b9d937.png)

**Comment by mai93** [comment]
Closing the issue, if you can still reproduce it please reopen.
