### ISSUE TITLE
Debugging IntelliJ Bazel Plugin Itself

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3724]
It would be useful to document a means for debugging the plugin itself; i.e. run it and set breakpoints, etc. Do devs have a means by which they do this at the moment?

**Comment by mai93** [comment]
@blorente is helping us with adding instructions on the plugin development and debugging in https://github.com/bazelbuild/intellij/pull/3912

**Comment by blorente** [comment]
Hey @abhillman , could you check if the instructions added [here](https://github.com/bazelbuild/intellij/blob/master/DEV_IDE_SETUP.md), and see if they work for you?
