### ISSUE TITLE
Test Coverage Information

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3725]
It would be useful to have a means of looking at coverage information and to document that

**Comment by sgowroji** [comment]
Hello @abhillman, Could you please elaborate  your request with more details and it would be helpful if you can send us any PR on the above request.

**Comment by mai93** [comment]
To get coverage data showing up in the IDE, you need to choose the `Run 'Test_NAME' with Coverage` option from the icon next to test class, method or target.

**Comment by kshyanashree** [comment]
Hello @abhillman! Did you have an opportunity to check the above [comment](https://github.com/bazelbuild/intellij/issues/3725#issuecomment-1338130522)? Thanks!
