### ISSUE TITLE
Add .bazelrc to .gitignore

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3726]
Allows devs to specify settings for all build targets. Example use-case:

```
$ cat .bazelrc
build --define=ij_product=intellij-ue-oss-stable
```

**Comment by abhillman** [comment]
cc/ @mai93 @vsiva please take a look

**Comment by abhillman** [comment]
It looks like the "better" way to do this is to add `build_flags` to `.bazelproject`

```
build_flags:
  --define=ij_product=intellij-ue-oss-stable
```

I would propose, instead of this approach, perhaps adding some documentation for how to import and run sources to the README.

**Comment by mai93** [comment]
@abhillman I see that we mention this in the repo README [here](https://github.com/bazelbuild/intellij#compatibility-with-ide-versions) and instructions about using existing .bazelproject files are mentioned in the last line of [Building the plugin](https://github.com/bazelbuild/intellij#building-the-plugin) section
"You can import the project into IntelliJ (with the Bazel plugin) via importing the ijwb/ijwb.bazelproject file."

**Comment by blorente** [comment]
@abhillman Could you let me know if the instructions pointed to by Mai (plus the dev instance instructions) are enough?
