### ISSUE TITLE
External Dependencies link to wrong path CLion

### ISSUE THREAD

**Issue by brandonpollack23** [bazelbuild/intellij#373]
If i go to definition in CLion it will jump to a cache directory ala

bazel_$USERNAME/HASH/execroot/\_\_main\_\_/external/ ...

instead of my actual dependency (a local_repository located in my workspace).

**Comment by RNabel** [comment]
This is generally not the case, although it is possible that `local_repository` is broken in CLion - could you provide a minimum reproducable example?

**Comment by brandonpollack23** [comment]
Sure, forgive the clearly still WIP:

git clone https://github.com/brandonpollack23/grok3dtests --recursive

cd grok3dtests

import into CLion

before you build, none of the third_party/grok3d dependencies are even visible to the project so it's red all over

bazel build :grokgame

all the red is gone, but if you jump to definition (Go to GRK_Engine from movebackandforthtests.cpp)

it'll not open the third_party repo.

**Comment by RNabel** [comment]
Just as a sanity check: did you click the blaze 'B' button on the top right of the CLion window to sync the project?

**Comment by brandonpollack23** [comment]
Sure did haha I'm used to this flow from the similar internal Google tool.


On Wed, Jul 25, 2018 at 7:37am, Robin Nabel < notifications@github.com [notifications@github.com] > wrote:
Just as a sanity check: did you click the blaze 'B' button on the top right of the CLion window to sync the project?

**Comment by brandonpollack23** [comment]
I should note that the workspace includes these as external dependencies, they are not compiled as packages

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
