### ISSUE TITLE
Native Build Rules Point to 404'ing URL

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3730]
Example:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1097794/175791947-542fc082-86c1-4df4-9a52-7f572d17a3e4.png">

Furnished link points to https://bazel.build/docs/be/overview.html, which 404s:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1097794/175791906-b059d81b-745f-4825-839b-d6492263311e.png">

Location in source that needs to be updated: https://github.com/bazelbuild/intellij/blob/2da78ef14e4469e965bff854f8447920f6fcd17e/base/src/com/google/idea/blaze/base/bazel/BazelBuildSystemProvider.java#L52

**Comment by mai93** [comment]
Fixed with a1e7637a2d2f5776455ad7fb364c043717e37349
