### ISSUE TITLE
Jump to Source from Test Results

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3731]
Observed:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1097794/175793644-8acc4f6a-9826-40a6-91c9-c3019f5dc7d1.png">

Expected (comes from a maven project):

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1097794/175793650-ec34503e-822a-4a12-b4ca-aaf19ad89c93.png">

**Comment by mai93** [comment]
Hello @abhillman I also used `//:ijwb_common_tests` to run tests and I was able to see the jump to source option when right-clicking on the test results. Can you provide more details on how to reproduce it if you still have the same problem with the latest plugin version?

<img width="896" alt="Screen Shot 2022-10-14 at 4 26 19 PM" src="https://user-images.githubusercontent.com/70515749/195957340-6b6e47c2-7fd2-4b14-8b19-7aaa216bd24f.png">
