### ISSUE TITLE
Target List Unpopulated for "Bazel IntelliJ Plugin" Configuration Modal

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3732]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1097794/175793716-a4b406da-dfca-4a51-ba45-d61a6de22297.png">

Repro steps:
* checkout this repository
* open the `WORKSPACE` file
* add the latest release of this plugin to IntelliJ
* go to "Edit Configurations"

**Comment by sgowroji** [comment]
Hello @abhillman, Can you share an example repo to test the above scenario. Thanks!

**Comment by sgowroji** [comment]
Hello @abhillman, Did you get a chance to check the above [comment](https://github.com/bazelbuild/intellij/issues/3732#issuecomment-1275993989). Thanks!

**Comment by sgowroji** [comment]
Due to lack of update on the above issue.  We are closing this issue now. Please feel free to reach us if you can provide above information. Thanks!
