### ISSUE TITLE
Document Necessity of Adding IntelliJ Platform Plugin SDK

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3733]
The IntelliJ Platform Plugin SDK allows for the resolution of symbols in the IntelliJ IDE when working on the plugin itself.

Without the IntelliJ Platform Plugin SDK:
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1097794/175833912-a8ea845f-916c-4a30-a116-182e0348fea6.png">

Screenshot of how to enable via project settings:

![image](https://user-images.githubusercontent.com/1097794/175833924-5a95f8c9-3d16-4bad-b2cb-76d995fc934d.png)

**Comment by sgowroji** [comment]
Hello @abhillman, Could you please elaborate your query with complete details. Thanks!

**Comment by mai93** [comment]
Thank you @abhillman! We recently added these [instructions](https://github.com/bazelbuild/intellij/blob/master/DEV_IDE_SETUP.md) on setting up the environment for working on the plugin.
