### ISSUE TITLE
CLion submodule/external dependencies marked "unsynced"

### ISSUE THREAD

**Issue by brandonpollack23** [bazelbuild/intellij#374]
targets:
 //...:all

all directories still included, it is definately synced

**Comment by RNabel** [comment]
Could you provide some more information on how to reproduce this error?

**Comment by chaoren** [comment]
This is expected. We don't handle external repositories yet.

**Comment by brandonpollack23** [comment]
Any chance it could be added? Would be amazing if i could combine bazel and git submodules

**Comment by chaoren** [comment]
> It's odd because it's still in the workspace

It's not actually in the same workspace. The submodule has its own `WORKSPACE` file, so it's a separate workspace. And you had to import it in your base `WORKSPACE` file too.

**Comment by brandonpollack23** [comment]
I see.  I think I have an unrealistic expectation and desire to keep repositories totally seperate, even under development.  It probably makes more sense to just do this:

Workspace liba
Workspace libb
Workspace Project

Remove Workspace liba and libb

Create a single github repository for the project and move Workspace Project into that

create a directory for liba, libb, and project, each with their own BUILD trees (this is starting to sound familiar to google3...almost like they knew what they were doing).

Commit to each library and the project as I go in one repository.

When I decide to make a release, Create a new repository for each liba libb libc...project etc and copy paste, define a new workspace file for each with external dependencies as necessary and work in these now.  Things should be stable enough to continue to work in seperate repositories, or I can continue to develop them all together and fork off for releases.

The only issue here is when I do decide to fork off I'll have to edit all the BUILD files to use
//@liba:foo
instead of
//liba:foo targets

I guess a simple script could do it...

**Comment by widmoser** [comment]
Any news on this issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
