### ISSUE TITLE
Poor "Refreshing Files" Performance

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/intellij#3746]
In my experience, the gradle plugin is a lot faster here on much larger projects than the one I am working with. This tends to happen if I add a dep. Likely an opportunity to optimize.

<img width="666" alt="Screen Shot 2022-07-01 at 9 04 39 PM" src="https://user-images.githubusercontent.com/12849602/176985885-c3cce486-3219-4070-87ea-d07ab12d681f.png">

**Comment by sgowroji** [comment]
I'll close the issue. If you still can reproduce it, please reopen.
