### ISSUE TITLE
Allow Import of Bazel View file w/out Recreation

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3757]
Repro:
* import an existing bazel project
* a view file is created
* close the project
* go to "import bazel project"
* go to workspace
* select "import project view file"

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1097794/178121552-b729ba33-9e39-449d-8fec-8e36575c566d.png">

* note that the _existing_ view file shows up in the modal

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1097794/178121563-3bbfdd04-5f22-452d-9291-89ad86fc5b81.png">

* click "create"
* get an error about the view / `.ijwb` file already existing

<img width="639" alt="image" src="https://user-images.githubusercontent.com/1097794/178121585-f6b47ea8-39ce-439d-997a-744cb62d20cb.png">

Alternative:
* have an ability to import view files without recreating them

**Comment by mai93** [comment]
@abhillman I think you can use a different **Project data directory** (in the first field at this step)
![image](https://user-images.githubusercontent.com/70515749/192064186-fb9b756e-0afc-49ef-a039-f7ba25bca548.png)


this will create the .ijwb in the directory you specify.

**Comment by sgowroji** [comment]
Hello @abhillman, Could you please check the [resolution](https://github.com/bazelbuild/intellij/issues/3757#issuecomment-1256732019) provided in the above comment. Thanks!

**Comment by abhillman** [comment]
This is certainly a workaround. Supposing `.ijwb/**/*` is checked into source control or one reinstalls IntelliJ -- it seems reasonable to be able to import without recreation.

**Comment by mai93** [comment]
I think in these cases opening the project with the IDE Open action should work, as you do not need to reimport it with the plugin. I tried using Open and pointing to the directory containing the `.ijwb` and it worked.

**Comment by sgowroji** [comment]
Hello @abhillman, Can you try the workaround mentioned in the above [comment](https://github.com/bazelbuild/intellij/issues/3757#issuecomment-1264244003) and share us the update. Thanks!

**Comment by mortenmj** [comment]
@sgowroji @mai93 

I attempted the solution you outlined above in GoLand, and it did not work for me. If I remove the project from my project list, and attempt to open it using the Open dialog, the project is opened as a normal folder, not using the bazel project view.
