### ISSUE TITLE
Debug for Starlark not Always Available

### ISSUE THREAD

**Issue by abhillman** [bazelbuild/intellij#3758]
See comment here

https://github.com/bazelbuild/intellij/issues/1706#issuecomment-1179635807

Repro:
* clone https://github.com/bufbuild/rules_buf
* create bazel project by opening the dir that contains`examples/workspace/WORKSPACE`
* attempt to debug `buf_breaking_test` / label `fooapis_proto_breaking` in `fooapis/BUILD.bazel`

**Comment by mai93** [comment]
Hello @abhillman, based on [this check](https://github.com/bazelbuild/intellij/blob/master/skylark/src/com/google/idea/blaze/skylark/debugger/run/SkylarkDebugRunner.java#L69) Starlark debugging is only available for build commands. So you need to create a run configuration with the bazel command set to `build` and the debugging should be enabled for it.

**Comment by sgowroji** [comment]
I'll close the issue. If you still can reproduce it, please reopen.
