### ISSUE TITLE
url for "intellij_ce_2018_1" dependency returns 403

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/intellij#376]
The link for the new_http_archive for "intellij_ce_2018_1" (https://github.com/bazelbuild/intellij/blob/master/WORKSPACE#L14) returns a 403 and the project won't build. I noticed this on Bazel's test with downstream projects: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/360#6b0848d6-69b5-4635-9a4e-aa717a36214e

**Comment by plumpy** [comment]
Whoops, they hide old versions when they push bugfix releases out. For now you can change it to 2018.1.6.

Thanks!
