### ISSUE TITLE
Enabling fast builds - checkbox not showing up 

### ISSUE THREAD

**Issue by demichej** [bazelbuild/intellij#378]
Hello, I am using Intellij 2018.1 and bazel plugin 2018.07.09.0.1. I was excited when I saw that fast builds was included in the latest plugin:
https://ij.bazel.build/docs/fast-builds.html

However, I was then dismayed to not see a checkbox for a test that I ran and went to Run Configurations. Here's what I see:
![screenshot from 2018-07-30 15-36-16](https://user-images.githubusercontent.com/422315/43422102-55ebd55c-940e-11e8-83ed-78c3109fdc75.png)

It sounded like the versions I'm on should support this :(

**Comment by plumpy** [comment]
Sorry, I changed the UI to make it simpler, but I forgot to upload the new docs. For some reason I'm unable to upload the new docs at the moment, but what you want to do now is click the icon next to your configuration that looks like a 'run' icon overlaid with a lightning bolt (near the normal 'run' icon). Let me know if you can't find it.

It's only enabled for java_test targets for now, however.

**Comment by plumpy** [comment]
Okay, the docs are updated now: https://ij.bazel.build/docs/fast-builds.html
