### ISSUE TITLE
[Feature Request]  Add depend targets of listed targets in project view

### ISSUE THREAD

**Issue by kkpattern** [bazelbuild/intellij#3786]
Currently, we have two ways to add targets with intellij plugin:

1. Specificly list the targets
2. Enable `drive_targets_from_directories`

Neither way suites our project very well. Our project targets multiple platforms including iOS, Android and PC. When import the project in Android Studio many target are not needed.

Our project is relatively large so it's not convinent to list all wanted targets in project view.

It's also a little cumbersome to tag all targets we don't need in Android Studio.

What we want is to list the "root" target like a `android_binary` target in project view. Then have a config like `add_depend_targets` enabled in project view. Then all the depend targets of the `android_binary` will be imported. We use this pattern in other bazel related tools in our project and seems work prety well.

Is this a suitable feature for bazel intellij plugin?

Thanks.

**Comment by mai93** [comment]
Hello @kkpattern I think when you add a target to the targets list all the files reachable from it and its dependencies will be synced. For example in the project view file of the plugin itself, only a small set of targets are declared and their dependencies are built to resolve the relevant code ([ijwb targets example](https://github.com/bazelbuild/intellij/blob/master/ijwb/ijwb.bazelproject#L8)). Please let me know if this will not work for your case.
