### ISSUE TITLE
`BlazeAndroidSyncBuildFlagsProvider` should parse `fat_apk_cpu` flag from `build_flags` too

### ISSUE THREAD

**Issue by kkpattern** [bazelbuild/intellij#3787]
Currently, bazel intellij plugin will try to [parse `fat_apk_cpu` flag from `sync_flags`](https://github.com/bazelbuild/intellij/commit/ad4aa276b54a7f12553c99423f2a57f864638231#diff-4bbe37e21cc3121d4616fec9d8c9c254c6f3696bb2dbb46952ecb6b6f6396e45R55). If no flag found `x86_64` would be added to sync flags.

However, according to [doc](https://github.com/bazelbuild/intellij/commit/ad4aa276b54a7f12553c99423f2a57f864638231#diff-4bbe37e21cc3121d4616fec9d8c9c254c6f3696bb2dbb46952ecb6b6f6396e45R55) `sync_flags` should be used only when absolutely necessary, as it can defeat bazel caching. So normally we will add `fat_apk_cpu` in `build_flags` since it will also be added to sync flags.

But now if bazel intellij plugin doesn't find the `fat_apk_cpu` flag in `sync_flags`, it will add `--fat_apk_cpu=x86_64` which further override the `fat_apk_cpu` in `build_flags`. This may cause sync to fail if the project doesn't target `x86_64` platform.

**Comment by sgowroji** [comment]
Please refer [this](https://github.com/bazelbuild/intellij/issues/3703#issuecomment-1336714010) for workaround

**Comment by mai93** [comment]
`BlazeAndroidSyncBuildFlagsProvider` is removed in https://github.com/bazelbuild/intellij/commit/583537c63866eac13169ce128bb53aa0017bc6e0, this commit will be included in 10.01.2023 release, please reopen if this did not resolve the issue.
