### ISSUE TITLE
Bazel Plugin is incompatible with GoLand 2018.2

### ISSUE THREAD

**Issue by SNestertsev** [bazelbuild/intellij#385]
Tried on the following configuration:
GoLand 2018.2
Build #GO-182.3684.99, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-693.17.1.el7.x86_64

**Comment by chaoren** [comment]
Did you build from source or download from here? https://plugins.jetbrains.com/plugin/8609-bazel

We haven't published 2018.2-compatible builds yet.

**Comment by chaoren** [comment]
Should build for `--define=ij_product=intellij-2018.2` now.

**Comment by SNestertsev** [comment]
Yes, now it was built successfully and loaded into IDE. 
Thanks!

**Comment by mennanov** [comment]
@SNestertsev were you able to use this plugin normally?
If so, could you tell me please how you configured GoLand: things like GOROOT, GOPATH?

thanks!
