### ISSUE TITLE
OS=mac  IDE=CLION  "Found 0 toolchains." happend

### ISSUE THREAD

**Issue by remilelei** [bazelbuild/intellij#386]
![image](https://user-images.githubusercontent.com/30251297/43776273-e79ffb80-9a81-11e8-936e-0d02889f04d2.png)

![image](https://user-images.githubusercontent.com/30251297/43776372-354fca9a-9a82-11e8-8915-7f31397ff016.png)
---
ide is clion 2018.1.3

 emm.. I have no idea how to fix this problem..
somebody has some advices?

**Comment by RNabel** [comment]
Please see this issue for more context: https://github.com/bazelbuild/intellij/issues/109

Note that your `crosstool_top` flag usage doesn't do anything since you're just setting it to the default value. There's some more info and possible resolutions in the above issue.

**Comment by RNabel** [comment]
Also, I only ever got the `Bazel` plugin to work on 2017.3.4, but that could be out of date, since there's been a bunch of updates since I last checked (about a month ago).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
