### ISSUE TITLE
Bazel syntax highlighting as a separate plugin

### ISSUE THREAD

**Issue by davestibrany-dd** [bazelbuild/intellij#3876]
### Description of the feature request:

Having the ability to add Bazel syntax highlighting to .bzl/.bazel files without having to install the entire IntelliJ plugin.

### What underlying problem are you trying to solve with this feature?

Installing the entire intellij-bazel plugin pins you to an older version of IntelliJ, which is not desirable. There doesn't exist an IntelliJ plugin solely for syntax highlighting, so it would be amazing if you released just this portion independently.

**Comment by jastice** [comment]
We are now releasing up-to-date versions for current IJ releases, so I think this is obsolete?

**Comment by mai93** [comment]
I agree, I'll close this issue.
