### ISSUE TITLE
Generated files not added to sources

### ISSUE THREAD

**Issue by PoncinMatthieu** [bazelbuild/intellij#389]
Hi,
We have a build file with a genrule for handling different configurations. The genrule looks like this:
```
filegroup(
    name = "selected_config",
    srcs = select({
                ":dev_mode": ["config/dev.py"],
                ":staging_mode": ["config/staging.py"],
                ":prod_mode": ["config/prod.py"],
                "//conditions:default": ["config/dev.py"]
           })
)

genrule(
    name = "make_default_link",
    srcs = [":selected_config"],
    outs = ["config/default.py"],
    cmd = "cp $(location :selected_config) $@"
)
```
So on build, we generate a file `default.py` based on the selected configuration. That file will be located in the bazel-genfiles folder but we are able to import it in python just like any other source file from a py_binary rule. 

Our issue is that Intellij is unable to resolve the imports on the default file because the location of the generated file `bazel-genfiles` is not added to the project configuration. We can add it ourselves manually on the Project structure as a source directory but it will be erased every time we resync the project.  

It would be great if the genfile location could be added as a source dir or else have the ability to add any arbitrary folder from the .bazelproject file.
This issue might be a duplicate of https://github.com/bazelbuild/intellij/issues/205 but it seemed to me to be a relatively different kind of issue.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
