### ISSUE TITLE
[New sync Window] Java fast test compilation failure does not output a link

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#3919]
### Description of the bug:

Java fast test has the ability to output a "rerun" link when compilation fails under the assumption that it's likely the next run with bazel will fix the issue.
After moving from "bazel console" to the new console this stopped working.
https://github.com/bazelbuild/intellij/blob/53f9331fe83de4c57c7116b507b3d1ea87a59569/java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildConfigurationRunner.java#L200

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Make sure you're running on 2021.2 since for some reason singlejar is faulty on 2022.2
2. Add to `//base` the following `javacopts` flags
```
       "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
        "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
        "--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
```
3. Add to `//base` the following `data` attribute
```
     data = ["@local_jdk//:bin/java"],
```
4. Add to `//base:unit_tests` the below attribute 
```
    jvm_flags = [
        "-Dcom.google.testing.junit.runner.shouldInstallTestSecurityManager=false",
    ],
``` 
5. Run a test (for example `BlazeCommandNameTest`) via fast test once so that the uber jar is built
6. Break compilation of this test somehow and run fast test again
7. See a small red notification on the bottom left side saying to "see bazel console" and expect a link but no bazel console exists. See in the new console this message does not appear.
8. If you're outside of the experiment you will see the clickable link.

### Which Intellij IDE are you using? Please provide the specific version.

2021.2.4

### What programming languages and tools are you using? Please provide specific versions.

scala 2.12, java 11

### What Bazel plugin version are you using?

v2022.08.09 Stable

**Comment by ittaiz** [comment]
Hi @sgowroji I wrote in the issue a reproducible example. Is it not clear? It took me many hours to be honest to be able to nail it down since I'm working on something adjacent and it wasn't easily to get a minimal issue.

Btw,
I just now saw your reply and wanted to share that I have a fix for the issue https://github.com/wix-playground/intellij/commit/5f34f3e7632ef79a5e00c08ad2b2ba21e69c7f72

**Comment by ittaiz** [comment]
Sure thing https://github.com/bazelbuild/intellij/pull/3921

**Comment by ittaiz** [comment]
I think the problem is the experiment for the new bazel console.
Any chance you know if you had the experiment on or off when trying to reproduce?
If you're not sure I'll follow the instructions again and this time I'll explicitly turn on the experiment

**Comment by ittaiz** [comment]
1. Checkout IJ plugin repository at commit d07856ca1ed16b34419e0c76055e46a973a91d8d (was the head when I did the repro)
2. Edit `common/experiments/src/com/google/idea/common/experiments/experiment.properties` and set `blazeconsole.v2.rollout=100` (to make sure you get the new sync window)
3. build the plugin `bazel build --define=ij_product=intellij-2021.2 --tool_java_runtime_version=remotejdk_11 --java_runtime_version=remotejdk_11 --java_language_version=8 --tool_java_language_version=11 --nocheck_visibility //ijwb:ijwb_bazel_zip`
4. Open IJ 2021.2 and install the IJWB version that you built on step 3 
5. Import the plugin workspace via [this](https://gist.github.com/ittaiz/0cf0f21f074e76cd9617aab7c8aa4b17) .bazelproject file (I think it doesn't matter but I'm trying to be as specific as possible)
6. Add to `//base:unit_tests`
```
data = ["@local_jdk//:bin/java"],
jvm_flags = [
     "-Dcom.google.testing.junit.runner.shouldInstallTestSecurityManager=false",
],
7. Run a test (for example BlazeCommandNameTest) via fast test once so that the uber jar is built
8. Break compilation of this test somehow and run fast test again
9. See a small red notification on the bottom left side saying to "see bazel console" and expect a link but no bazel console exists. See in the new console this message does not appear. 
![Screen Shot 2022-09-14 at 14 56 28](https://user-images.githubusercontent.com/1378327/190150049-2abe6b29-c32a-4c96-b9a2-180607c8bca7.png)
10. If you're outside of the experiment (do the same from step 1 but in step 2 do `blazeconsole.v2.rollout=0`) you will see the clickable link.
![Screen Shot 2022-09-14 at 15 15 21](https://user-images.githubusercontent.com/1378327/190150843-c44f921a-6225-4060-bd60-ce00b5d80cd6.png)

Btw,
I did many experiments and I think I needed to add the below flags to IJ `Edit Custom VM options...` menu to even get fast-test compilation to work but now when I tried removing them and restarting then I still got fast-test compilation to work (of course without the link) so maybe they're not needed  
```
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
```
I also pushed the above changes [here](https://github.com/wix-playground/intellij/commit/a515869654dc2da81d79723b3a8cee308da8b145)

Please let me know if this doesn't repro because for me it reproduces every time

**Comment by mai93** [comment]
Thank you @ittaiz for reporting this, I replied to https://github.com/bazelbuild/intellij/pull/3921.

Also thanks for pointing out that there is a problem with fast-test in 2022.2, do you have any findings that can help us fix it?

**Comment by ittaiz** [comment]
Hi @mai93 I was OOO on vacation.
I think you can take my repro and run it on 2022.2 and see the issue.
The problem was something with singlejar being faulty but I don't fully remember.
It's a shame quite honestly. We're trying to use fast test with scala which doesn't need this but for java users this can be a very valuable feature.

**Comment by ittaiz** [comment]
@mai93 I tried again with 2022.2 and given the above "hacks" (the `data`, the `jvm_flags` and the `Edit Custom VM options...`) then fast test does work for java. 
Might also be related to my bazel version which is `release 5.3.2`.
I think that you should consider streamlining this experience or at least document it but that's your call.
If you want me to open a new ticket LMK (and to which end)

**Comment by mai93** [comment]
Thank you @ittaiz.

For my example, adding the options to `Custom VM options...` was enough to make it work, I will add this note to the plugin documentation.

**Comment by ittaiz** [comment]
Saw the issue again on 2022. This is when I'm debugging the plugin so maybe that's the issue (I sometimes debug and sometimes build the zip locally and install it and I don't remember which of my previous attempts were which).
`singlejar_local: src/tools/singlejar/input_jar.cc:119: external/intellij_ce_2022_2/lib/app.jar is corrupt, expected ECD64 record at offset 0x17b6de20 is missing`

**Comment by mai93** [comment]
I've not seen this error before, can you please open a new bug for that?

**Comment by ittaiz** [comment]
Yes
