### ISSUE TITLE
Single module workspace limits kotlin to one platform.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#398]
A kotlin platform is primed as a module facet and only one kotlin facet can be active per module.

I have recently added js support, basic ij features dont work unless the platform is switched to js.

I dont know what the solution for this is. I think we could probably force multiple kotlin facets into the module config, but Somehow i think it won’t work.

should we ask JB to add support for this ? Or are there plans for multiple modules ?

**Comment by brendandouglas** [comment]
I'm surprised they use facets actually, I thought they were moving away from that.

We don't have any plans for multiple modules, so pushing for support for multiple facets in a single module is probably the best way forward here.

**Comment by hsyed** [comment]
Yeah I think so too. I have created an [Issue in Youtrack](https://youtrack.jetbrains.net/issue/KT-26168). Hopefully it lines up with what we want.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
