### ISSUE TITLE
Importing C++ Bazel Project fails in CLion on macOS

### ISSUE THREAD

**Issue by pmanjunath8085** [bazelbuild/intellij#399]
I installed Bazel plugin on my CLion and am trying to import a new Bazel C++ project and I keep hitting into these errors-

```
tensorflow_gpu-1.8.0lft1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

ERROR: error loading package '': 
Encountered error while reading extension file 'requirements.bzl': no such package '@my_deps//': Traceback (most recent call last):     
File "/private/var/tmp/_bazel_pmanjunath/0f9184e7a61c3740275307da0cc42014/external/io_bazel_rules_python/python/pip.bzl", line 39       _pip_import_impl(repository_ctx, "python")
File "/private/var/tmp/_bazel_pmanjunath/0f9184e7a61c3740275307da0cc42014/external/io_bazel_rules_python/python/pip.bzl", line 35, in _pip_import_impl      fail(("pip_import failed: %s (%s)" % ...)))
pip_import failed:  (tensorflow_gpu-1.8.0lft1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform. ).
```
On googling I found people were having this problem on their linux boxes and the solution was to upgrade pip. I did try

```$ sudo pip install --upgrade pip
$ pip --version
pip 18.0 from /Library/Python/2.7/site-packages/pip (python 2.7)
```
but to no avail. I am suspecting that it is picking up the wrong .whl file since the name clearly states its for linux_x86_64.

Any ideas?

**Comment by RNabel** [comment]
This looks like an error in an imported package, in this case either [`rules_python`](https://github.com/bazelbuild/rules_python) or [`tensorflow`](https://github.com/tensorflow/tensorflow). Try opening an issue against either of those two :)

**Comment by RNabel** [comment]
As a follow-up question, I'm assuming you get the error even when building from the terminal - is this true? If you can build from the terminal but not CLion this indicates it's a problem with the plugin. In that case, it may fall under https://github.com/bazelbuild/intellij/issues/109#issuecomment-315745285.

**Comment by pmanjunath8085** [comment]
@RNabel We don't build from the terminal at all(For various other reasons like some libraries not available on OS X). For that, we use Linux machines. I am trying to setup CLion with bazel so that I can at least browse code, make changes, push to git remote etc from my Mac.

**Comment by brendandouglas** [comment]
The Bazel plugin is just invoking bazel as you would from the terminal (with whatever environment variables, etc. are provided to the CLion process at startup).

So if you can't build properly from the terminal, you also won't be able to sync properly from CLion.

**Comment by jin** [comment]
Closing this, as it looks like a problem with the build, not the plugin.

**Comment by ccnankai** [comment]
@brendandouglas 
I successfully build tensorflow  from source  on the terminal, but there will be a bunch of errors with clion.How can I configure the instructions? Thank you.
![image](https://user-images.githubusercontent.com/33537489/65102439-a59d1800-d9fd-11e9-909b-e56d79fae425.png)
