### ISSUE TITLE
Automatically identify targets on import

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#4]
Currently when importing a project the plugin suggests `//...:all` or manually specifying the targets. [Pants intellij plugin](https://github.com/pantsbuild/intellij-pants-plugin) automatically identifies the targets and enables you to checkbox which of the existing targets you want to be added to your project view.

![import_file2](https://cloud.githubusercontent.com/assets/1378327/16755286/a682f300-4803-11e6-9c03-a83a2eee77a5.png)

I think this can be a great feature (just give a bit more real-estate for selecting the targets :wink:)

**Comment by ittaiz** [comment]
@brendandouglas should we close this given your work on deriving targets from directories?

**Comment by brendandouglas** [comment]
Yes, I think this is basically solved now. I'd definitely recommend all users derive targets from directories automatically.

We'll likely need further refinements for this, so if people notice issues with the feature, please let us know -- I'm always interested in improving it.
