### ISSUE TITLE
Environment variable not passed to executable

### ISSUE THREAD

**Issue by elrapha** [bazelbuild/intellij#400]
I am building my java project with bazel. I want to use environmental variable at build/run time. According to the [documentation](https://bazel.build/designs/2016/06/21/environment.html) `--action_env=APP_ENV=Development` should work.

So i do `bazel run myproject:app --action_env=APP_ENV=Development`

But `System.getenv("APP_ENV");` is null

In my intellij IDE I have the following. Neither `--action_env=APP_ENV=Development` nor `--action_env APP_ENV=Development` work

[![Using IntelliJ][1]][1]

Did i get something wrong here?

  [1]: https://i.stack.imgur.com/6bJqa.png

**Comment by brendandouglas** [comment]
Does it work when you run from the command line? If so, it might just be a formatting problem with the flags -- could you try putting the entire flag on a single line in the run config editor?
`--action_env=APP_ENV=Development`

**Comment by elrapha** [comment]
No the command line fails also

**Comment by chaoren** [comment]
I think `--action_env` is intended for rule actions. E.g., compiler and linker invocations.
`--test_env` is for tests.

For binaries you're supposed to set the environmental variables as you would when executing a regular binary.
E.g.,
```
FOO=bar bazel run :binary
```
we don't have that support in the run configuration editor. But you *could* create a bazel wrapper script that sets the variables, and set the IDE's bazel binary to the script.

E.g.,
```
$ cat bazel
FOO=bar exec bazel "$@"
```

**Comment by brendandouglas** [comment]
In that case, we should close this, as it's not specific to the bazel plugin. I'd recommend opening an issue at https://github.com/bazelbuild/bazel, or just asking directly on stackoverflow (https://stackoverflow.com/questions/tagged/bazel) or bazel-discuss@googlegroups.com
