### ISSUE TITLE
Installing the Bazel Plugin on the client when using Jetbrains Gateway causes some inconsistent UI

### ISSUE THREAD

**Issue by JamyDev** [bazelbuild/intellij#4001]
### Description of the bug:

If you have a gateway instance with the bBazel plugin active (.ijwb opened and working) and you install the Bazel Plugin into the Client (within Jetbrains client there's 2 places to install plugins, `Plugins (On Host)` aka the remote server; and `Plugins` aka the Jetbrains Client); the Bazel menu in the toolbar will not show. Likely because the client doesn't consider itself to be in a Bazel project.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Have JB Gateway setup with .ijwb project
2. Install the Bazel plugin on the Host (But not the client)
3. Notice that the Bazel toolbar menu shows up
4. Now install the plugin on the Client
5. Restart and notice that the Bazel menu does not show up.

### Which Intellij IDE are you using? Please provide the specific version.

GoLand 2022.2.2 / #GO-222.3739.57

### What programming languages and tools are you using? Please provide specific versions.

Go 1.19.2

### What Bazel plugin version are you using?

v2022.08.09

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Probably super low priority, or even not an issue at all. But maybe we can change the config to disallow installing it JBClient.

**Comment by sgowroji** [comment]
Hello @JamyDev, Could you please share the inconsistent UI screen and sample project used to test the above. Thanks!

**Comment by JamyDev** [comment]
@sgowroji as I went to try and repro this, it seemed like the plugin isn't available for the client and it was more of an issue on our side. Closing.
