### ISSUE TITLE
Project Sync Slow and Uses Only 1 CPU Core

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/intellij#4028]
### Description of the bug:

Syncing a project is extremely slow and appears to only utilize one core (i.e. is not parallelized).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out _this_ repository; i.e. `intellij/bazelbuild` and attempt to sync the project.

### Which Intellij IDE are you using? Please provide the specific version.

Build #IU-213.7172.25, built on March 15, 2022

### What programming languages and tools are you using? Please provide specific versions.

kotlin, protobuf, etc.

### What Bazel plugin version are you using?

latest

### Any other information, logs, or outputs that you want to share?

<img width="734" alt="Screenshot 2022-10-19 at 4 35 03 PM" src="https://user-images.githubusercontent.com/12849602/196826868-cda7a23a-23cb-463b-8351-84a05563d7c0.png">
<img width="188" alt="Screenshot 2022-10-19 at 4 34 44 PM" src="https://user-images.githubusercontent.com/12849602/196826869-24d3bc96-ce1f-4fb1-8a14-d125d4342e0f.png">
<img width="422" alt="Screenshot 2022-10-19 at 4 34 31 PM" src="https://user-images.githubusercontent.com/12849602/196826871-b265495b-f81b-43a3-ae38-d4ca3b07c1ec.png">

**Comment by sgowroji** [comment]
Hello @aryeh-looker, Can you share the minimal steps followed in testing the above issue. Thanks!

**Comment by raoarun** [comment]
closing this out.  please re-open @aryeh-looker if this is still an issue.
