### ISSUE TITLE
Controlling build flags from Clion

### ISSUE THREAD

**Issue by galshulkind** [bazelbuild/intellij#403]
Hi, are you planning to allow control of the various flags the Clion plugin passes to Bazel. As an example, is there an easy way to not pass the flag --tool_tag=ijwb:CLion?

**Comment by deadmoto** [comment]
That would be amazing to have this feature!
Especially in cases when the host platform and the target platform differ (e.g. building a Linux-only solution on macOS host).

**Comment by deadmoto** [comment]
@mikenicholson sure, I was referring to https://github.com/bazelbuild/intellij/issues/1740

**Comment by alice-ks** [comment]
The last comments sound as if putting the settings into .bazelrc or .bazelproject helped to solve your issues. Please re-open this issue if there's still something missing.

**Comment by illera88** [comment]
Using the .bazelrc sounds more like a hack than actually fixing the problem (showing all the flags passed to bazel and let the user edit them).
