### ISSUE TITLE
Unable to sync entire bazel project on macOS using dazel

### ISSUE THREAD

**Issue by BjarkeTornager** [bazelbuild/intellij#4048]
#### Description of the issue. Please be specific.
The setup of the bazel project that I am working on does not support macOS so I am using dazel as a wrapper to execute it on linux in docker, which works fine from the command line. My bazel configuration in IntelliJ uses dazel to execute in linux in docker and looks like this:
![Bazel Settings](https://user-images.githubusercontent.com/28363006/198291859-85817785-9d23-46bf-8ff1-5792d0b477f7.png)

Syncing individual targets in IntelliJ works, although slow - several minutes for a component. However, when I try to do a full project sync IntelliJ errors with the following stacktrace:

![Stacktrace](https://user-images.githubusercontent.com/28363006/198292536-ab471658-ec31-42ef-8c25-434d7a19dcca.png)

And trying again and again to sync just gives a "sync finished with errors" message and a Bazel Problems message of "Error: Deriving targets from project directories failed":
![Bazel sync errors](https://user-images.githubusercontent.com/28363006/198294097-46c82253-76ea-48c2-af5b-fc21c1fa441e.png)

It should be noted that my colleagues who are using linux and bazel instead of the wrapper dazel are able to sync the entire project.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
Use dazel as a wrapper for bazel in IntelliJ and do a full project sync. This results in the stacktrace shown above. 

#### Version information
IdeaUltimate: 2022.2.3
Platform: Mac OS X 12.6
Bazel plugin: 2022.10.18.0.1-api-version-222
Bazel: 4.1.0

**Comment by sgowroji** [comment]
Dupe  of https://github.com/bazelbuild/intellij/issues/418

**Comment by BjarkeTornager** [comment]
> Dupe of #418

Yes possibly. But I don't see a suggested resolution on that issue. It looks like somehow the messages between docker and IntelliJ gets corrupted when syncing the entire project. However, it does not happen for sub-targets and individual targets.

**Comment by mai93** [comment]
@ittaiz I know that https://github.com/bazelbuild/intellij/issues/418 was reported long time ago, but if you can help us with more details about your findings and how you worked around it, that will be great.

**Comment by ittaiz** [comment]
We had our own dazel project back then (of course called wazel 😁) and we scraped it for other reasons so I don't remember the exact details.
Having said that I think the issue was about our wrapper printing additional bytes and that failed the strict proto parsing IJWB had/has.
To this day in our wrapper we have logic which makes sure to not print anything additional if the commands are with tool IJWB and are sync related.
@ZachiNachshon @joeyfwix any ideas given you know our existing wrapper a lot better than me now :)
