### ISSUE TITLE
[IntelliJ] Importing from Project view file results in error about external project.

### ISSUE THREAD

**Issue by crazyjat** [bazelbuild/intellij#4066]
### Description of the bug:

Trying to import from a .bazeproject file into IntelliJ results in the below error message: 

![image](https://user-images.githubusercontent.com/12353450/199587581-54a88f06-5074-49c5-8a34-b5b377d30d73.png)

The file I'm importing is in that path. Seems like a bug to me.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Import a .bazelproject file into IntelliJ

### Which Intellij IDE are you using? Please provide the specific version.

2022.2.3

### What programming languages and tools are you using? Please provide specific versions.

scala

### What Bazel plugin version are you using?

2022.10.04.0.1-api-version-222

### Have you found anything relevant by searching the web?

no

**Comment by sgowroji** [comment]
Hello @crazyjat, Could you please share the sample code with project view file used in reproducing the above issue. Thanks!

**Comment by sgowroji** [comment]
Due to lack of details on the above issue.  We are closing this issue now. Please feel free to reach us if you can provide above information. Thanks!
