### ISSUE TITLE
Syncing is incompatible with bazel-6

### ISSUE THREAD

**Issue by matts1** [bazelbuild/intellij#4067]
### Description of the bug:

I filed https://github.com/bazelbuild/bazel/issues/16644, but they said to file a bug here.

It apppears that bazel 6.0 changed the API so that override_repository silently fails if the repository did not previously exist, while in bazel 5.3.2, it worked.

This is especially relevant, because the bazel intellij plugin relies on this feature to sync by adding a repository for the bazel aspect:
`--override_repository=intellij_aspect=/opt/intellij-ue-2021.3/plugins/g3plugins/aspect`

When attempting to sync with bazel 6, I get the following error:
`ERROR: Unable to find package for @[unknown repo 'intellij_aspect' requested from @]//:intellij_info_bundled.bzl: The repository '@[unknown repo 'intellij_aspect' requested from @]' could not be resolved: Repository '@intellij_aspect' is not visible from repository '@'.`

The sync works fine if I add the following to my WORKSPAPCE.bazel:
`http_archive(name = "intellij_aspect")`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Open any project with intellij with the bazel plugin installed (or the g3plugin if you're a googler)
* Put 6.0.0-pre.20221012.2 in your .bazelversion.
* Run bazel > sync

### Which Intellij IDE are you using? Please provide the specific version.

Intellij IDEA 2021.3.3 Ultimate edition

### What programming languages and tools are you using? Please provide specific versions.

N/A

### What Bazel plugin version are you using?

G3plugin bundled 2022.10.19.0.0-api-version-213 (but you should be able to repro with regular bazel plugin)

### Have you found anything relevant by searching the web?

I filed https://github.com/bazelbuild/bazel/issues/16644

**Comment by fmeum** [comment]
Adding some info from https://github.com/bazelbuild/bazel/issues/16644:

I think that this can be solved in the plugin by replacing `@intellij_aspect//:fast_build_info.bzl%fast_build_info_aspect` with `@@intellij_aspect//:fast_build_info.bzl%fast_build_info_aspect` if the Bazel version is at least 6.0.0. Even though the error only comes up with `--enable_bzlmod`, this label type is understood even if the flag is not enabled.

**Comment by meteorcloudy** [comment]
@mai93 This is an quite important issue to fix to allow Bzlmod users to use the Bazel intellij plugin. Is it possible to fix the aspect label by a version check, basically:

- For Bazel version <=5.x: `@intellij_aspect//:fast_build_info.bzl%fast_build_info_aspect`
- For Bazel version >=6.x: `@@intellij_aspect//:fast_build_info.bzl%fast_build_info_aspect`

**Comment by fmeum** [comment]
@mai93 The linked commit seems to fix the issue. Has it been merged yet?

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/commit/420a2a52129e3e85667aeceb431a2652ed0968d1
