### ISSUE TITLE
Allow setting custom bep file location

### ISSUE THREAD

**Issue by talya** [bazelbuild/intellij#407]
Our use case:
To allow developing from the IDE on a mac OSx, with bazel running inside a local docker container.

We need the bep file to be available to IntelliJ from inside the docker container, and since today it's location is [hardcoded](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolUtils.java#L38) to the java.io.tmpdir, we currently need to change the java.io.tmpdir of IntelliJ itself via idea.vmoptions, which we'd rather not do.

Feature request - provide an environment variable such as `IDEA_BAZEL_BEP_PATH`, which if set would take priority

@hmemcpy

**Comment by brendandouglas** [comment]
I've added a check for the IDEA_BAZEL_BEP_PATH environment variable -- will be in the next release, scheduled for next Friday.

**Comment by ittaiz** [comment]
Thanks!

**Comment by talya** [comment]
just for visibility for anyone reading this - a better solution than an environment variable was added in the recent release - using a system property called `bazel.bep.path`, which takes [precedence](https://github.com/bazelbuild/intellij/blob/f054292b07806a288eb205d13f336badbbe1464b/base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolUtils.java#L60) over other options.

this still means users need to manually edit `idea.vmoptions` and restart the IDE, but it only affects bazel plugin which is much better than changing the whole ide's tmp path.

@brendandouglas - fwiw, we are using the new system property, so if relevant you could drop the env var part.
