### ISSUE TITLE
[Android] Choose appropriate ABI when running depending on target device

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/intellij#409]
For Android applications with native dependencies (`cc_library` etc), compiling each architecture can be quite expensive (`arm64-v8a` for device and `x86_64` for simulator). 

Our current workflow either requires us to specify `--fat_apk_cpus=arm64-v8a,x86_64` ahead of time and spend twice as long to build, or go in and change the configuration before each build. 

Would it be possible to behave more like Xcode's 'build only active architecture' where the target architecture is derived from the device to be run on?

**Comment by vsiva** [comment]
Does `mobile install` not do this optimization?

**Comment by jgavris** [comment]
@vsiva `mobile-install` is currently broken for Android 9 (see https://github.com/bazelbuild/examples/issues/77). I don't believe it does, either. I've heard rumors that `mobile-install` is being replaced with a v2 version so no further efforts are being made to fix the current version.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
