### ISSUE TITLE
UI components repeated on titlebar when NewUI is enabled, on 2022.3 EAP

### ISSUE THREAD

**Issue by jameslan** [bazelbuild/intellij#4094]
### Description of the bug:

Please refer to the attached screenshot.

Tried on
- Non-Bazel project on 2022.3 EAP NewUI enabled
- Bazel project on 2022.3 EAP NewUI disabled
- Bazel project on 2022.2 NewUI enabled

They are all good.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3 Beta (Ultimate Edition) Build #IU-223.7571.4

### What Bazel plugin version are you using?

2022.11.07.0.1-api-version-223

### Any other information, logs, or outputs that you want to share?

![image](https://user-images.githubusercontent.com/1083331/201186920-e0900166-0ee3-4b4d-a442-8e8461f7b675.png)

**Comment by sgowroji** [comment]
Hello @jameslan, Can you provide complete steps to reproduce the above issue. Thanks!

**Comment by kristiandrucker** [comment]
@sgowroji this issue is for Intellij with 2022.3+ update which includes the new ui. I've got the same issue.
1. Enable the new ui on intellij 2022.3
2. Load bazel project
