### ISSUE TITLE
Variables are not resolved when run Run Configuration without debugging

### ISSUE THREAD

**Issue by vicpl** [bazelbuild/intellij#4112]
### Description of the bug:

 - Create a Run Configuration for bazel binary target
 - Specify Executable flags using variables, for example:
   --envfile=$WorkspaceRoot$/current.env

 - Run configuration with debugger - "$WorkspaceRoot$" is resolved into an actual path
 - Run configuration without debugger - "$WorkspaceRoot$" is not resolved and application receives "$WorkspaceRoot$/current.env" as an argumen

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.2.3 (Ultimate Edition)

### What programming languages and tools are you using? Please provide specific versions.

go

### What Bazel plugin version are you using?

2022.10.18.0.1-api-version-222

**Comment by sgowroji** [comment]
Hello @vicpl, Can you provide an sample code to reproduce the above issue. Thanks!

**Comment by vicpl** [comment]
Hey @sgowroji,

Thanks for looking into this. Here is a sample repo: https://github.com/vicpl/bazel-4114

**Comment by vicpl** [comment]
Is there any update on this? This issue is a blocker for us to migrate from vs code.

**Comment by blorente** [comment]
@vicpl Please check if this was solved.

**Comment by blorente** [comment]
Closing, feel free to reopen if the issue wasn't fixed.
