### ISSUE TITLE
Bazel plugin don't open Activity when run configuration

### ISSUE THREAD

**Issue by Kadanza** [bazelbuild/intellij#412]
I set up Bazel configuration. When I run this config application assembled and installed to my phone, but don't auto opened like gradle is doing

![2018-09-18 16 50 59](https://user-images.githubusercontent.com/35968229/45692443-6e362a00-bb63-11e8-808c-603db83e26e3.png)

my log

![2018-09-18 16 51 12](https://user-images.githubusercontent.com/35968229/45692544-b48b8900-bb63-11e8-9399-c36fad0789b7.png)

**Comment by jgavris** [comment]
I believe you'll need to add `--start_app` to the bazel flags section. See https://docs.bazel.build/versions/master/mobile-install.html.
