### ISSUE TITLE
How generate signed release apk?

### ISSUE THREAD

**Issue by Kadanza** [bazelbuild/intellij#415]
How generate signed release apk in bazel project?

Bazel plugin for android studio doesn't have tab "Build signed apk"   only compile  tabs

![default](https://user-images.githubusercontent.com/35968229/45892026-aa6dc280-bdcf-11e8-9f76-7496e56a5154.png)

**Comment by vsiva** [comment]
We don't support this feature in the UI. So you'd need to invoke this from the command line. I recommend reading through https://github.com/bazelbuild/bazel/issues/1613 and https://groups.google.com/d/msg/bazel-discuss/2BPWVRnsiGc/yhZb7kdMAgAJ for more information.
