### ISSUE TITLE
Extend kotlin test context provider to work with kotest

### ISSUE THREAD

**Issue by nikunjy** [bazelbuild/intellij#4150]
### Description of the feature request:

Currently this plugin is able to understand regular kotlin tests which might be written in a junit like manner. However it doesn't support https://github.com/kotest/kotest  test style. 

### What underlying problem are you trying to solve with this feature?

Support https://github.com/kotest/kotest  style tests. Since it is such a popular library I think it might make sense to extend this plugin to support tests like 
```
class MyTest: DescribeSpec() {
 init {
    describe("first") {
       it("part1") {
         ....
       }
   }
 }
}
``` 

I think I can extend this https://github.com/bazelbuild/intellij/blob/master/kotlin/src/com/google/idea/blaze/kotlin/run/producers/KotlinTestContextProvider.java 
to make sense of this syntax. 

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

IntelliJ IDEA 2022.2.1 (Ultimate Edition)

### Have you found anything relevant by searching the web?

No

**Comment by nikunjy** [comment]
I think I can extend it. Please let me know what you think

**Comment by nikunjy** [comment]
@mai93  thoughts ? How can I get this prioritized ?

**Comment by mai93** [comment]
Thank you @nikunjy! We can review a PR addressing this.
