### ISSUE TITLE
error_prone missing from upstream PR.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/intellij#416]
```ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: no such package 'third_party/java/error_prone': BUILD file not found on package path```

I tried this a few weeks ago, the problem still exists in 37a256c0b36d74d83102b9039e3e585da8406d89.

**Comment by brendandouglas** [comment]
This isn't broken at HEAD, and is fixed upstream. It should land in the upstream branch today.
