### ISSUE TITLE
Unable to load targets in CLion 2022.3

### ISSUE THREAD

**Issue by cmburn** [bazelbuild/intellij#4168]
#### Description of the issue. Please be specific.

Unable to load any target correctly.

Upon opening a synced target, I'm met with "This file does not belong to any project target; code insight features might not work properly", with a number of issues in C/C++ code resolution, highlighting, and others. All works fine when compiling the project.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

1. Install fresh CLion, version 2022.3
2. Install Bazel plugin from Plugins menu
3. Open fresh project- I used the [example repo](https://github.com/bazelbuild/bazel/tree/master/examples/cpp-tutorial/stage1) as a sanity check.
4. Sync
5. Load any file- in the example I listed, it was hello-world.cc

It seems the master branch does not support 2022.3 yet, or I would try that as well.

#### Version information
CLion: 2022.3
Platform: Linux 6.0.0-5-amd64
Bazel plugin: 2022.11.07.0.1-api-version-223
Bazel: 5.3.2

**Comment by sgowroji** [comment]
Hi @cmburn, Can you provide more details on the above error. Like a screenshot of the error or the error logs.

**Comment by kaliaumem** [comment]
Hi @sgowroji I've encountered the same problem on two different projects on two separate installs of CLion. Here's an example even after a successful sync:
![image](https://user-images.githubusercontent.com/36928048/206700446-15244f45-0d33-40f9-be38-304fff2f74e4.png)
I don't get any error log during sync (be it incremental or non-incremental):
![image](https://user-images.githubusercontent.com/36928048/206700784-3ec0cda7-3600-4a85-93b3-763a15cf8f6c.png)
Here are the CLion logs after that sync:
https://gist.github.com/kaliaumem/5152d953edd349d850f750c8876728d5#file-bazel-clion-logs

**Comment by cmburn** [comment]
Apologies- somehow this didn't show up in my email. @kaliaumem is showing the same error I'm having, if you need me to check anything else, I'll watch this more carefully.

**Comment by connoranderson** [comment]
Seeing this as well on the latest clion release. Had to revert so that the warning wouldn't show up.
