### ISSUE TITLE
TEST_SRCDIR and TEST_TMPDIR env vars are not populated while debugging

### ISSUE THREAD

**Issue by amir-f** [bazelbuild/intellij#4181]
### Description of the bug:

The environment variables `TEST_TMPDIR` and `TEST_SRCDIR ` are populated when you run `bazel test <target>`per [this doc](https://bazel.build/reference/test-encyclopedia).

In IntelliJ when you create a bazel configuration to run a bazel test these are populated when you _Run_ the configuration because it uses `bazel test` under the hood. However when you run the config in _Debug_ mode then these env vars are not populated. This creates a discrepancy between debug env vars and the run env vars.

Additionally what's a good way to get the path to the test temp dir in debug mode?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a `py_test` target containing
```
import os

print(os.getenv('TEST_SRCDIR'))
print(os.getenv('TEST_TMPDIR'))
```

2. Create a bazel config for running the said target.
3. Run the config in _Run_ mode and _Debug_ mode and you'll notice the difference.

### Which Intellij IDE are you using? Please provide the specific version.

PyCharm 2022.2.3 (Community Edition) Build #PC-222.4345.23, built on October 10, 2022 Runtime version: 17.0.4.1+7-b469.62 aarch64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. macOS 12.6.1 GC: G1 Young Generation, G1 Old Generation Memory: 752M Cores: 10 Metal Rendering is ON Non-Bundled Plugins:     idea.plugin.protoeditor (222.4345.14)     com.google.idea.bazel.ijwb (2022.11.15.0.1-api-version-222)     com.google.gct.core (22.12.1-222)

### What programming languages and tools are you using? Please provide specific versions.

Python 3.8

### What Bazel plugin version are you using?

2022.11.15.0.1-api-version-222

**Comment by sgowroji** [comment]
Hello @amir could you please share the code reproducing example to test the error. Thanks!
