### ISSUE TITLE
I cannot jump to thirdparty sources in Clion+bazel condition.

### ISSUE THREAD

**Issue by lxinfei** [bazelbuild/intellij#4185]
#### Version information
CLion: 2022.3
Platform: Mac OS X 13.0.1
Bazel plugin: 2022.11.07.0.1-api-version-223
Bazel: 5.3.2

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/118719392/206910491-358cab9e-5add-4f0e-8906-214eb2af4a2e.png">

**Comment by sgowroji** [comment]
Hello @lxinfei, Could you please provide minimal steps to reproduce the above issue. Thanks !

**Comment by lxinfei** [comment]
I got the reason. The bazel files are soft links pointing to other directories. Could I change the bazel work mode to solve this problem?
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/118719392/207216076-2c87afd8-63db-4fa1-8646-7c336f63d3b1.png">

**Comment by lxinfei** [comment]
ok，I use https://github.com/hedronvision/bazel-compile-commands-extractor to generate the compile_commands.json to solve this problem.
