### ISSUE TITLE
Support new .bazelignore file

### ISSUE THREAD

**Issue by mtsgrd** [bazelbuild/intellij#421]
Bazel 0.17.1 introduced a `.bazelignore` file that lets you ignore a list of directories. How about marking these as excluded on sync?

**Comment by mtsgrd** [comment]
Perhaps something like this? https://github.com/mtsgrd/intellij/commit/0e0034eae38a356a80357d4f6dbad9718044d23b

**Comment by ittaiz** [comment]
@brendandouglas this sounds useful. WDYT? We have people who need this `.bazelignore` but I'm not sure they use intellij. I think we'll have that intersection soon.
@mtsgrd are you seeing a slowdown due to intellij trying to index these directories?

**Comment by mtsgrd** [comment]
@ittaiz I added this to my own fork such that intellij doesn't index a `node_modules` folder I keep in the workspace. Interestingly, even though I have this folder excluded I can still jump to definitions inside of it from my angular code. Is this expected behaviour? The angular app I am working on is largely based on https://github.com/alexeagle/angular-bazel-example.
