### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break IntelliJ Plugin Aspect Google in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/intellij#4212]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking IntelliJ Plugin Aspect Google. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-4af5-4f0f-b210-a8bc53dc2a30)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-4af2-4446-bfab-24a8d74e2d5d)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-4af7-465b-827b-23bc5b62642f)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-4afc-4532-9b35-a42b7306f517)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-4afa-4b25-9644-b488cef16618)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154b-4aff-4819-ac6d-a9edbfe3305c)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/commit/340cf764603c362216ab51d657723f5e8952b3ab
