### ISSUE TITLE
ERROR: python.exe not found on PATH of bazel

### ISSUE THREAD

**Issue by zdenek-zzz** [bazelbuild/intellij#424]
Hello,
I tried to import ONOS project to intelliJ IDEA using bazel.
I use windows 10.
Bazel does not have python in his path.
I am not sure how to add the pass correctly.
I tried .baselrc file and also windows path settings.

Can someone give me a help?
Thanks

p.s. error message is bere:
Running Bazel info...
Command: C:\Users\zdvorakx\bazel\bazel.exe info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --

ERROR: python.exe not found on PATH
Command: git diff --name-status --no-renames 6a7b524ef2795e12f19b33bc38d3811c8a788011

**Comment by jin** [comment]
Please see step 2 in the Bazel installation instruction for Windows. https://docs.bazel.build/versions/master/install-windows.html#getting-bazel
