### ISSUE TITLE
There is a problem working in WSL

### ISSUE THREAD

**Issue by lee8165** [bazelbuild/intellij#4248]
#### Description of the issue. Please be specific.

Updating VCS...
Running Bazel info...
Command: bazel info --tool_tag=ijwb:IDEA:ultimate --curses=no --color=yes --progress_in_terminal_title=no --

[FATAL 02:41:24.330 src/main/cpp/util/file_windows.cc:493] MakeCanonical(\\wsl$\xx\home\project\xx\xx): AsAbsoluteWindowsPath failed: network paths are unsupported

#### Version information
IdeaUltimate: 2022.3.1
Platform: Windows 11 10.0
Bazel plugin: 2022.11.07.0.1-api-version-223

**Comment by sgowroji** [comment]
Hi @lee8165, Could you please provide minimal steps to reproduce the above issue. Thanks!

**Comment by lee8165** [comment]
The version of bazel is 6.0.0, the version of bazel plug-in is 2022.11.07.0.1-api-version-223, WORKSPACE is in wsl, bazel and ide are in Windows system, this problem is because the project path has '\\wsl $' prefix; if you use bazel in wsl, there will be an error 'createProcess error = 3;'

**Comment by sgowroji** [comment]
Dupe of https://github.com/bazelbuild/intellij/issues/3112
