### ISSUE TITLE
Allow setting custom blaze-script file location

### ISSUE THREAD

**Issue by mindscratch** [bazelbuild/intellij#4253]
### Description of the feature request:

To allow debugging an application from the IDE on a mac OSx, with bazel running inside a local docker container.

We need the blaze-script file to be available to IntelliJ from inside the docker container, and today it's location uses the [TempDirectoryProvider](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/run/BlazeBeforeRunCommandHelper.java#L165) which defaults to the value for `java.io.tmpdir` (such as `/tmp`), we currently need to change the java.io.tmpdir of IntelliJ itself via idea.vmoptions, which we'd rather not do.

We'd like to set a system property in `idea.vmoptions` akin to `bazel.bep.path` (see issue #407), that the `BlazeBeforeRunCommandHelper` can use.

### What underlying problem are you trying to solve with this feature?

To allow debugging an application from the IDE on a mac OSx, with bazel running inside a local docker container.

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

Mac OSX

### Have you found anything relevant by searching the web?

Yes, #407 which was the same issue but for a different section of the plugin code.

### Any other information, logs, or outputs that you want to share?

When trying to debug an application from the IDE (while developing inside a docker container) I get: `/bin/bash: /tmp/blaze-script-14352988423531282696: Permission denied` (because of the way the container is run).

**Comment by mai93** [comment]
Fixed with https://github.com/bazelbuild/intellij/pull/4690

**Comment by mindscratch** [comment]
Thank you!
