### ISSUE TITLE
Fast build "Couldn't determine test class"

### ISSUE THREAD

**Issue by james-deee** [bazelbuild/intellij#426]
I have not been able to get Fast Build to work for our tests. I am happy to give more information, but it's not clear to me what information I can give you, let me know.

If I do a regular "Run " on a JUnit test class in Intellij, everything works, and runs the tests in the Test Class.

Yet, if I run "Fast Run" right after this, I get a Successful build in the Bazel Console:

```
Aspect @intellij_aspect//:fast_build_info.bzl%fast_build_info_aspect of //foo.core:tests_deploy.jar up-to-date (nothing to build)
INFO: (10-17 10:16:25.035) Elapsed time: 6.160s, Critical Path: 1.14s
INFO: (10-17 10:16:25.035) 1 process: 1 linux-sandbox.
success (0): bazel build --tool_tag=ijwb:IDEA:community --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --test...
```
BUT I am then given an immediate failure that says 
```
Error running 'Bazel test DemichejTest': Couldn't determine test class
```

Again, let me know what else I can do to help you diagnose. I really really really want to use Fast Builds. Thanks.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
