### ISSUE TITLE
Android Studio Plugin won't install built from source

### ISSUE THREAD

**Issue by pswaminathan** [bazelbuild/intellij#4264]
### Description of the bug:

When building Android Studio plugin from source at [this point in the tree](https://github.com/bazelbuild/intellij/tree/3ae65381457c35f2c9076c9a3362cd24e7242e6f), the plugin fails to install.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Check out commit [3ae6538](https://github.com/bazelbuild/intellij/commit/3ae65381457c35f2c9076c9a3362cd24e7242e6f)
2. Build for Android Studio as described in instructions: `bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-oss-latest-stable`
3. Install plugin in Android Studio, enable, restart
4. Plugin fails to load with [this error log](https://gist.github.com/pswaminathan/48ac2aa38c653b986ea4f188efa3d93a)

### Which Intellij IDE are you using? Please provide the specific version.

Android Studio Dolphin | 2021.3.1 Patch 1  Build #AI-213.7172.25.2113.9123335

### What programming languages and tools are you using? Please provide specific versions.

Bazel 6.0.0, OpenJDK 11

### What Bazel plugin version are you using?

Commit 3ae65381457c35f2c9076c9a3362cd24e7242e6f

### Any other information, logs, or outputs that you want to share?

Building at the release branch (https://github.com/bazelbuild/intellij/tree/v2022.11.29-aswb) and installing from disk succeeds, so this appears to be a regression from the release.

**Comment by mai93** [comment]
Thanks @pswaminathan for reporting this, I'm getting a slightly different error when I try to reproduce it. I did some analysis and in my case I started seeing the error with commit https://github.com/bazelbuild/intellij/commit/b3c2b00a3d1323312503d07648a376e1a24678ea. Can you please check if you can see this problem with the plugin built before this commit, i.e. checkout d3369ffd1b39dc99516191317c14150dd17e44eb?

**Comment by mai93** [comment]
This should be fixed with https://github.com/bazelbuild/intellij/commit/07d622caa058974fb3ee16a60924fea907e0efd3
