### ISSUE TITLE
Fastbuild suggestion has corp-only links in it

### ISSUE THREAD

**Issue by dhalperi** [bazelbuild/intellij#429]
https://github.com/bazelbuild/intellij/blob/369ec0911356207231bffee0995095159ae8c93d/java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildSuggestion.java#L80

This popped up on my IntelliJ, but I clicked the link and got a `@google.com`-only appengine signin dialog for `go/`. Seems like we shouldn't do that for Bazel, just Blaze.

**Comment by plumpy** [comment]
Thanks! I actually never meant to suggest fast builds for Bazel, where they're generally less useful. I fixed the link, fixed our export script to throw errors if it sees links to goto.google.com, and furthermore fixed it to only suggest fast builds on tests that contain >500 jars in their classpath (which is probably somewhat rare in the Bazel world, but common internally).

So, I appreciate the notice!
