### ISSUE TITLE
Target navigation of external repositories with shorthand notation is broken

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#431]
Clicking on an external repository dependency like this, `@com_google_guava_guava`, does not bring you to the relevant build file.
If however you write `@com_google_guava_guava//:com_google_guava_guava` and then click on it then you're brought to the correct build file.
Problem is that buildifier will change the latter form to the former one.
This means we need to choose between buildifier and ease of navigation in intellij.
cc @hmemcpy

**Comment by brendandouglas** [comment]
Thanks, this will be fixed for the next release (https://github.com/bazelbuild/intellij/issues/435).
