### ISSUE TITLE
IntelliJ IDEA cannot navigate to relative source files from an external Bazel rules source file

### ISSUE THREAD

**Issue by hisener** [bazelbuild/intellij#4310]
### Description of the bug:

IntelliJ IDEA has the ["Go to Declaration" action](https://www.jetbrains.com/help/idea/navigating-through-the-source-code.html#go_to_declaration) to navigate to the declaration of a symbol. However, this feature does not work inside a source file of an external Bazel rules repository. Currently, we get the "Cannot find declaration to go to" error.

I suspect it's related to using a relative path (e.g., `:artifact.bzl`) or an absolute path (e.g., `//private/rules:artifact.bzl`). Because it seems to work when referenced by the workspace name (e.g., `@workspace_name//private/rules:artifact.bzl`)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Open a source file from an external Bazel rules repository and try to navigate to another symbol. For instance, in `/external/rules_jvm_external/defs.bzl`, I get the following when I "go to declaration" (cmd + b)

<img width="747" alt="image" src="https://user-images.githubusercontent.com/7688949/214033896-5b9223d6-4a0d-4e9d-931a-c8b2b1ea683e.png">

I can jump to `defs.bzl` from a `BUILD.bazel` file, though. E.g.,

<img width="402" alt="image" src="https://user-images.githubusercontent.com/7688949/214033709-f6be053d-b425-4f5b-9ed5-6e2aaed8577f.png">

**Steps to reproduce**

Assuming bazelbuild/bazel repo is set up on IntelliJ IDEA:

1. Open the WORKSPACE file and go to the [load statement of the `maven_install` macro](https://github.com/bazelbuild/bazel/blob/59c5a0fd0c45fd57bff8cc08c9da3b2d554ac075/WORKSPACE#L610) and go to declaration (cmd + b).
2. It should open the `external/rules_jvm_external/defs.bzl` file.
3. Try to go to declaration of a symbol in load statements, e.g., `artifact`. (See the screenshot above.)

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.2.2 (Ultimate Edition)

### What programming languages and tools are you using? Please provide specific versions.

Not relevant.

### What Bazel plugin version are you using?

2022.11.01.0.1-api-version-222

### Have you found anything relevant by searching the web?

No. We also discussed this issue in the last IntelliJ plugin for Bazel meeting; there are also other folks seeing the same issue.

**Comment by sgowroji** [comment]
Hi @hisener , Can you share a sample repo to test the above request. Thanks!

**Comment by hisener** [comment]
@sgowroji, added steps to reproduce in the bazelbuild/bazel repo. I think it's also possible to reproduce in any repo with rules_jvm_external or rules_python dependency. Let me know if it's sufficient.

**Comment by mai93** [comment]
This should be fixed with https://github.com/bazelbuild/intellij/pull/5164
