### ISSUE TITLE
Unable to save settings if .ijwb already exists

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#434]
![image](https://user-images.githubusercontent.com/601206/47990619-a2a07e00-e0f0-11e8-8260-cfd3e309ece9.png)

This happens when attempting to import (from scratch) a bazel project that may already contain a `.ijwd` directory.

This is a regression, this used to work fine if `.project` was already present.

**Comment by chaoren** [comment]
We decided that was not a desirable feature, because it nukes your existing project data. If you really want this you should manually delete the existing directory, or name the new directory something else.

**Comment by joprice** [comment]
@hmemcpy I found that you can put the .bazelproject elsewhere in your tree, and import it using the wizard, and it will generate an import statement to the other file. That way, you can wipe away the .ijwd dir, even with local changes to the .bazelproject file, and re-import.
