### ISSUE TITLE
external dependency target is not clickable in intellij

### ISSUE THREAD

**Issue by natansil** [bazelbuild/intellij#435]
Currently **external** dependencies of the label format ` "@com_google_guava_guava"` are not clickable in intellij. i.e. can't navigate to the external folder.

"@com_google_guava_guava//:com_google_guava_guava"  on the other hand is clickable, so one can navigate to the external BUILD file containing this target.

This problem is **more common** now that `buildifier` removes the target name which duplicates the external repo name.

context examples:
`some_rule(
     name = "foo"
     deps = [
         "@com_google_guava_guava",
     ]
`

`some_rule(
     name = "foo"
     deps = [
         "@com_google_guava_guava//:com_google_guava_guava",
     ]
`

**Comment by brendandouglas** [comment]
Thanks, the plugin simply never supported that label format (I didn't realize it was even accepted by Bazel).

I'll fix this up for the next release.

**Comment by or-shachar** [comment]
@brendandouglas was this released already?

**Comment by brendandouglas** [comment]
It will be in the upcoming release (in the next couple of days).

For reference, you can check the release history on JetBrains plugin repo: https://plugins.jetbrains.com/plugin/8609-bazel

The version number there corresponds to the day the release branch was cut, so any (future) release cut on November 5th onwards will have this fix.

**Comment by ittaiz** [comment]
Thanks!
