### ISSUE TITLE
AP generated sources don't get resolved in Kotlin sources

### ISSUE THREAD

**Issue by utikeev** [bazelbuild/intellij#4363]
### Description of the bug:

I'm using [Kotlin rules](https://github.com/bazelbuild/rules_kotlin/) and get something like a regression of https://github.com/bazelbuild/intellij/issues/495. 
Inherited methods in classes generated by AP are resolved correctly when used in Java:
![image](https://user-images.githubusercontent.com/12977355/215849165-13f68b0d-8098-4b4e-85ae-cca424f4cdb5.png)
But they display as unresolved when used in Kotlin:
![image](https://user-images.githubusercontent.com/12977355/215849217-08194f16-dfb9-4084-9220-1e58e4077469.png)
Running both mains produces the same correct result.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The reproduction project can be found here: https://github.com/utikeev/kotlin-resolve-ap-issue

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3.2 (#IU-223.8617.56)

### What programming languages and tools are you using? Please provide specific versions.

Kotlin 1.7.22

### What Bazel plugin version are you using?

2023.01.10.0.1-api-version-223

### Have you found anything relevant by searching the web?

Looks pretty similar to https://github.com/bazelbuild/intellij/issues/495, but it is marked as fixed.

**Comment by AlexBeggs** [comment]
This is also a problem when using Dagger.  As you can see with this [project](https://github.com/AlexBeggs/bazel-dagger-example) that generated Dagger component isn't resolved. 

![image](https://user-images.githubusercontent.com/4483842/224168110-da8d75b9-ddd3-4bec-a327-7b5b06dcf51d.png)

**Comment by wdfinch** [comment]
Any updates on this? I'm trying to use this plugin with dagger, and it can't index my generated code.
