### ISSUE TITLE
Fast Builds recommendation text refers to Blaze and go/intellij-fast-build

### ISSUE THREAD

**Issue by fis** [bazelbuild/intellij#438]
This may have been fixed already -- I don't know how to re-trigger the tooltip to verify.

On the Android Studio v2018.10.08 version of the plugin, there was a quick tooltip the first time I ran a Java unit test via Bazel, suggesting trying out Fast Builds. I didn't have the chance to grab a screenshot, but the text of the tooltip referred to "Blaze", and the more-details link was a go-link (go/intellij-fast-build).

**Comment by brendandouglas** [comment]
Thanks for letting us know, it's fixed in the latest build (#429)
