### ISSUE TITLE
Errors when trying to run bazel project with Android Studio or Intellij

### ISSUE THREAD

**Issue by stijnvn** [bazelbuild/intellij#439]
While following this codelab https://codelabs.developers.google.com/codelabs/bazel-android-intro, I got the following error message when I try to run the application:

```
Error:Could not read apk deploy info from build
```

How can I resolve this issue?

Android Studio 3.2.1 
Bazel plugin  2018.10.22.0.2

When I try to follow the codelab with Intellij 2018.2.5, I only get the bazel option to run but not to debug or install when i right-click on the `android_binary` target. When I click on run, I get the following error message:

```
ERROR: Cannot run target //mediarecorder/java/com/example/android/mediarecorder:mediarecorder: Not executable.
```

Any ideas how to solve these errors?

**Comment by mai93** [comment]
Closing this issue, please reopen if you are still getting this error with newer versions of the plugin.
