### ISSUE TITLE
Plugin should disable one of IntelliJ's inspections

### ISSUE THREAD

**Issue by vmax** [bazelbuild/intellij#440]
'Package name does not correspond to the file path' inspection should **not** be applied to `bazel` projects because `bazel` (unlike Maven) does not enforce directory structure for Java code.

If there's a relevant API in IntelliJ IDEA's plugin support, I think it makes sense to disable that inspection.

**Comment by ittaiz** [comment]
I actually think this should be configurable because I’d like that
inspection if, for example, I do follow maven structure (which Bazel
supports)
