### ISSUE TITLE
Importing C/C++ BUILD on Ubuntu Shows "No Python Facet Found"

### ISSUE THREAD

**Issue by pauldelmusica** [bazelbuild/intellij#442]
PyCharm 2018.2.4 Community edition. Try to import "wav_to_spectrogram" in Tensrflow example directory. The program build correctly using Bazel command line.

**Comment by brendandouglas** [comment]
Thanks for letting us know, I've fixed this upstream. The fix didn't make it into the upcoming release, but will be in the one after (scheduled for December 7th)
