### ISSUE TITLE
Sync targets from working set path separator issue on Windows 10.

### ISSUE THREAD

**Issue by anil-roy** [bazelbuild/intellij#443]
The project view file for a Java project has the following sync targets from project view:
 //flip/src/au/com/hsta/projname/scheduler/...

Sync targets from working set:
 //flip\src\au\com\hsta\projname\scheduler:all

The working set target has a mix of path separators which breaks the Bazel sync process.  Any ideas how to configure this?

At some stage I'll see a break: 
Error:Internal error. Error: java.lang.RuntimeException: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^

**Comment by brendandouglas** [comment]
We don't have support for windows yet (https://github.com/bazelbuild/intellij/issues/113). It's something we'd like to do eventually, but it's not on the roadmap -- we simply don't have the bandwidth for it.

**Comment by anilroychoudhry** [comment]
So I wrapped bazel.exe with a parent exe.  The parent exe  fixed all the path separator types to make it consistent and then calls the original bazel.exe.  I get a lot further.  

But I now run into an issue identical to https://github.com/bazelbuild/intellij/issues/418

**Comment by anilroychoudhry** [comment]
With WSL in Win 10 1803, I have moved from the Mac to Win 10 for dev.  It's a good experience overall.  I'll see if I can figure out this last remaining issue.  Any hints on where start in the code will be useful.
