### ISSUE TITLE
Unrecognized import after importing and syncing a bazel project using .bazelproject file

### ISSUE THREAD

**Issue by YuanHao97** [bazelbuild/intellij#4430]
### Description of the bug:

I'm following this [guide](https://ij.bazel.build/docs/import-project.html) and trying to import this [project](https://github.com/YuanHao97/bazel) into IntelliJ. I clone the repo and import it from `script/ij.bazelproject`. Then after the automatic syncing is succeed. But when I look into those source java files like `src/main/java/com/google/devtools/build/lib/bazel/execlog/StableSort.java`, there are a lot of import statement not recognized. I'm not sure whether my project setting is correct or not, but it seems a little bit odd that the project's root directory is set to 'sources'. If I change source directories, and re-sync the project, then the changes I made to source directories will restore. Is this normal? How can I resolve those unrecognized imports?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Import this [project](https://github.com/YuanHao97/bazel) using `script/ij.bazelproject` and set bazel version to 6.0.0, then run bazel sync on this project. Open `src/main/java/com/google/devtools/build/lib/bazel/execlog/StableSort.java` or `src/test/java/com/google/devtools/build/lib/bazel/execlog/StableSortTest.java`. Then you can see some unrecognized import.

### Which Intellij IDE are you using? Please provide the specific version.

Ultimate 2020.3.

### What programming languages and tools are you using? Please provide specific versions.

Java in IntelliJ IDEA

### What Bazel plugin version are you using?

2021.07.27.1.0-api-version-203

**Comment by mai93** [comment]
@YuanHao97 IJ 2020.3 is no longer supported by the plugin, I tried importing your project with a recent IJ version specifically 2022.3.2 and the imports in `src/main/java/com/google/devtools/build/lib/bazel/execlog/StableSort.java` was resolved correctly.
![image](https://user-images.githubusercontent.com/70515749/218899280-cc9049f4-9c45-4684-bef0-703d96048a2d.png)

**Comment by YuanHao97** [comment]
@mai93 It works. Thanks!
BWT, maybe it's better to point out supported version for IntelliJ  somewhere in this [guide](https://ij.bazel.build/docs/bazel-plugin.html), might be helpful for others.

**Comment by mai93** [comment]
Thanks for the advice, we can sure add them!
