### ISSUE TITLE
JUnit 5 Support

### ISSUE THREAD

**Issue by blorente** [bazelbuild/intellij#4433]
### Description of the feature request:

Bazel 6 supports JUnit 5 for Java tests. Furthermore, some third party rulesets (e.g. [`contrib_rules_jvm`](https://github.com/bazel-contrib/rules_jvm) already offer facilities to allow it.

As far as I can tell, the plugin does not yet offer support for these tests.
I've given the implementation a shot in this branch: https://github.com/blorente/intellij/tree/blorente/junit5 (leveraging the existing testbed: [commit](https://github.com/blorente/intellij/commit/ab2ade87085d516fd3c9131a859600ee36893416), but it looks like it will need at least a few days more of investment.

### What underlying problem are you trying to solve with this feature?

Currently, the plugin accidentally supports some of its features. As far as I can tell, I can:
- Right-click run a test, and most of the time it will be run correctly (but with the JUnit4 runner)
- Import JUnit 5 as a library, and get autocompletion and symbol resolution.

The plugin does not, however:
- Recognize a file as JUnit 5 for the purposes of gutter annotation:

JUnit 4:
<img width="363" alt="Screenshot 2023-02-13 at 13 33 23" src="https://user-images.githubusercontent.com/5861182/218471823-2c12aec2-0bc1-4bcd-9745-f80dcf7fbb5e.png">

JUnit 5 (missing the icons):
<img width="348" alt="Screenshot 2023-02-13 at 13 33 14" src="https://user-images.githubusercontent.com/5861182/218471981-0f34fa22-546c-4f0d-8b01-6110e42461b9.png">

- I suspect (but haven't validated yet) that it doesn't support a JUnit 5 runner either.
- And looking through the code, I found a lot of references to JUnit 4 and 3 and none to JUnit 5, which makes me believe that any JUnit 5 support is provided by IntelliJ itself and not the plugin.

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

I use an arm macOS. This reproduces in IntelliJ UE 2022.2 and 2022.3, on the plugin's `master` branch.

### Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/intellij/issues/245 -> Closed for being old.
- https://github.com/bazelbuild/intellij/issues/3413 -> Outlines that some JUnit 5 features work.

### Any other information, logs, or outputs that you want to share?

I'm happy to work on this. The main reason for the ticket is to make sure nobody is looking into it before sinking significant time.

**Comment by rdesgroppes** [comment]
Did you replace `java_test` by [`java_junit5_test`](https://github.com/bazel-contrib/rules_jvm#java_junit5_test)?
Once done, it should work pretty well:
![image](https://user-images.githubusercontent.com/7901596/219291208-664eec26-3103-4ec2-847f-e51ba53f50d9.png)

**Comment by blorente** [comment]
Fixed by https://github.com/bazelbuild/intellij/pull/4473

**Comment by blorente** [comment]
@rdesgroppes Thanks for the pointer! I've added a `junit5` example to the example repository, using `contrib_rules_jvm`.

After looking at it, it looks like JUnit 5 and JUnit 4 share a lot of the test filtering language (which is the main responsibility of the bazel plugin), so most of the work was in making the tests tests against junit 5, and making the code support it explicitly instead of accidentally.
