### ISSUE TITLE
Bazel requires restart between intellij and CLI runs

### ISSUE THREAD

**Issue by mjduijn** [bazelbuild/intellij#444]
Whenever I execute a Bazel command from the command line, and then using the IntelliJ plugin, it shows the following message and restarts.

`WARNING: Running Bazel server needs to be killed, because the startup options are different.`

Whatever I do, I can't seem to get these startup options exactly the same, even when I copy/paste the commands shown in the IntelliJ Bazel console.
I have also tried removing /etc/bazel.bazelrc and my workspace status command script.

My setup: Bazel 0.19.0, IDEA ultimate 2018.2.5, bazel plugin 2018.10.08.0.2, ubuntu 1804

**Comment by brendandouglas** [comment]
You're likely launching the IDE with a different set of environment variables (at least one of which bazel is sensitive to).

Try launching the IDE from the same terminal you're running these commands in.

**Comment by mjduijn** [comment]
Yes, thank you!

JAVA_HOME was present in the shell but not in IntelliJ
