### ISSUE TITLE
"Rerun Failed Tests" causes invalid test_filter

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/intellij#446]
Clicking the "Rerun Failed Tests" icon constructs an empty `--test_filter=` parameter to Bazel which always causes the test to fail.

## Steps to Reproduce

- Checkout [this example project](https://github.com/aherrmann/reproduce-intellij-project-view-issue/tree/74d65e08f15155429acef56448343cb3c7df0a95)
- Import into IntelliJ using this project view file
    ```
    directories:
      .
    targets:
      //:tests_test_suite_src_test_scala_org_example_hello_HelloSpec.scala
    additional_languages:
      scala
    ```
- Modify [the test-case](https://github.com/aherrmann/reproduce-intellij-project-view-issue/blob/74d65e08f15155429acef56448343cb3c7df0a95/src/test/scala/org/example/hello/HelloSpec.scala#L11) to make it fail. E.g.
    ``` diff
       it should "greet the given name" in {
    -    assert(Hello.hello("Some Name") === "Hello Some Name!")
    +    assert(Hello.hello("Some Name") === "Hello some Name!")
       }
    ```
- Click "Run selected configuration" on the `Bazel test :tests_..._HelloSpec.scala` run configuration.
    ![run_test_case](https://user-images.githubusercontent.com/732652/48563925-b1a7dd00-e8f5-11e8-9b2d-71d462430d6c.png)

- Click "Rerun Failed Tests"
    ![run_failed_test](https://user-images.githubusercontent.com/732652/48563959-c1272600-e8f5-11e8-8d9d-8c0611d7060d.png)

- Observe the following test failue
    ```
    ...
    //:tests_test_suite_src_test_scala_org_example_hello_HelloSpec.scala     FAILED in 1.1s
    ...    
    Executed 1 out of 1 test: 1 fails locally.
    Empty test suite.
    ```
- Notice how Bazel is passed an empty `--test_filter=` argument
    ```
    bazel test --tool_tag=ijwb:IDEA:community --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --runs_per_test=1 --flaky_test_attempts=1 --build_event_binary_file=/tmp/intellij-bep-1d9f67b5-e323-4392-bd49-4c2ec1464a7b --nobuild_event_binary_file_path_conversion --test_filter= -- //:tests_test_suite_src_test_scala_org_example_hello_HelloSpec.scala
    ```

## Details

- Executing the following command reveals the actual error
    ```
    $ bazel test --test_filter= --cache_test_results=no --test_output=errors -- //:tests_test_suite_src_test_scala_org_example_hello_HelloSpec.scala
    ...
    ==================== Test output for //:tests_test_suite_src_test_scala_org_example_hello_HelloSpec.scala:
    *** RUN ABORTED ***
      java.lang.ClassNotFoundException:
      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    ...
    INFO: Build completed, 1 test FAILED, 2 total actions
    ...
    INFO: Build completed, 1 test FAILED, 2 total actions
    ```
- Expected behavior: Call bazel with a non-empty `--test_filter` argument such as
    ```
    --test_filter=org.example.hello.HelloSpec
    ```

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
