### ISSUE TITLE
Failed to build Android apk target due to empty option string

### ISSUE THREAD

**Issue by ThomasCJY** [bazelbuild/intellij#4462]
### Description of the bug:

After upgrading to the latest android studio plugin, full apk build from IDE is broken due to empty option string. 
This regression is related to https://github.com/bazelbuild/intellij/commit/3f39fcadb2082216dcd56497668adb500d819ecb#diff-60594ed699457ac04f3d9c936c335815f810037083f52c5a978dc1206ed74327R112-R115 

which introduced an empty string into the build options 
```
Command: bzl build --tool_tag=ijwb:AndroidStudio --tool_tag=version:2023.01.24 --output_groups=+android_deploy_info "" --curses=no --color=yes --progress_in_terminal_title=no --build_event_binary_file=/var/folders/04/l0dbn8vx6k3d22cwy8c9r0200000gn/T/intellij-bep-7494bc2c-849e-4270-bf43-c592044deeaa --nobuild_event_binary_file_path_conversion -- //apps/apk:apk
```
 
![Screenshot 2023-02-15 at 5 01 52 PM](https://user-images.githubusercontent.com/6951238/219231226-9d895abe-e443-4967-8364-583a985f4b2a.png)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build apk target from IDE

### Which Intellij IDE are you using? Please provide the specific version.

Android Studio 2021.3

### What Bazel plugin version are you using?

v2023.01.24

**Comment by jagobagascon** [comment]
A simple (and ugly) workaround to this is creating a `bazel.sh` file like this: https://github.com/bazelbuild/intellij/issues/1922#issuecomment-1339097708

And then setting the `Bazel binary location` in Android Studio.

**Comment by ThomasCJY** [comment]
Close this as it's fixed in https://github.com/bazelbuild/intellij/pull/4527
