### ISSUE TITLE
Option to sync ignoring .jdeps files and instead add all external libraries to IJ

### ISSUE THREAD

**Issue by wcurrie** [bazelbuild/intellij#447]
At $WORKPLACE we're using a jdk toolchain with `source_version = "10"`. This works except bazel writes .jdeps files that are missing external libraries (https://github.com/bazelbuild/bazel/issues/5723#issuecomment-437138252). The cause is known and fixed in the error prone compiler (https://github.com/bazelbuild/bazel/issues/5723#issuecomment-437157856) but that change has not made its way into bazel.

@cushon suggested (https://github.com/bazelbuild/bazel/pull/6587#discussion_r232033852):
> It might make more sense to just provide a way to disable the Intellij plugins' jdeps handling and use the full classpath.

Would it make sense to add a checkbox or flag to configure ignoring .jdeps files during import? We're planning on using this patch in the interim https://github.com/uri-canva/intellij/pull/1.

**Comment by wcurrie** [comment]
I read the https://github.com/bazelbuild/intellij/issues/207#issuecomment-356627500 about the performance hit of importing all libraries. We'd rather accept the initial sync taking a while than having a IDE that looks entirely broken due to the missing external libraries.

**Comment by brendandouglas** [comment]
Unfortunately I don't think we can justify adding another setting to the already cluttered UI or adding complexity to the sync process to work around this (hopefully temporary) bug in bazel.
