### ISSUE TITLE
Autodetect java language level past 9.

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/intellij#448]
54f5b0709e9a74d4cd1c5a0fdcd4f7cf8c76500d added support for explicitly specifying the language level to a level past 9, but it hasn't updated the part of the code that infers the level from the Bazel toolchain, which is still capped at 9: https://github.com/bazelbuild/intellij/blob/54f5b0709e9a74d4cd1c5a0fdcd4f7cf8c76500d/java/src/com/google/idea/blaze/java/sync/JavaLanguageLevelHelper.java#L51

See https://github.com/uri-canva/intellij/commit/188cf8b7f353ce9d5aec768ffed1df21b29563cd for example (not opening a PR for my change assuming you'd like to fix this in a more future proof way than adding new cases to the switch every new java version).

**Comment by brendandouglas** [comment]
Thanks, we'll fix this up for the release after next.
