### ISSUE TITLE
Trailing space in specs2's "should" block causes the test to fail

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#455]
Example:
```scala
class MyTest extends SpecWithJUnit {
  "trailing space " should {
    "fail the test" >> {
      success
    }
  }
}
```
Note there's a single space at the end of "trailing space ".

Will produce the following test_filter: `"--test_filter=src.it.scala.foo.test.MyTest#\Qtrailing space should::fail the test\E$"`

The name "trailing space should" does not contain the extra space, causing the test runner to fail during filtering.

**Comment by chaoren** [comment]
We use TestConfigurationUtil.getStaticTestNameOrDefault for the scope name, and it does trimming.
Would this work in a non-blaze project? Should probably file an upstream bug if it happens there too.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
