### ISSUE TITLE
Running tests with specs2 with nested "should" blocks fails

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#456]
e.g.
```
class MyTest extends SpecWithJUnit {
  "trailing should" should {
    "nested" should {
      "fail the test" >> {
        success
      }
    }
  }
}
```

The test filter for this will only consider the inner "nested" block, and the runner will fail to find the test.
Also, seems that placing `"nested should" should` causes the runner to fail with error.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
