### ISSUE TITLE
PackageParser: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil

### ISSUE THREAD

**Issue by wcurrie** [bazelbuild/intellij#458]
When running with java 11 the IJ bazel console shows a stream of:
```
INFO: From Parsing java package strings for //services/foo:foo:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.repackaged.UnsafeUtil (file:/Users/$USER/Library/Application%20Support/IntelliJIdea2018.3/ijwb/aspect/tools/PackageParser_deploy.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.repackaged.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Looks like https://github.com/bazelbuild/intellij/pull/433 was an intended fix. IIUC the flags need to be in `BUILD.aspect` instead. Eg https://github.com/wcurrie/intellij/pull/1/files#diff-87833d0278b7ae3937c9d438dea20e33R22

Could we get this applied upstream please?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
