### ISSUE TITLE
clion plugin - unable to specify GDB

### ISSUE THREAD

**Issue by asa** [bazelbuild/intellij#46]
I am unable to setup a debugger with the clion plugin. I get an error in the console: Error running Bazel run my_project:example: GDB executable not specified

I have tried to use --run_under, as well as setup gdb remote debugger, with no luck. 
Perhaps I just need better docs?

**Comment by brendandouglas** [comment]
Hi @asa, you can specify the GDB binary in Settings > Build, Execution, Deployment > Toolchains.

**Comment by brendandouglas** [comment]
I'll close this -- please reopen if that didn't fix it.

**Comment by asa** [comment]
I believe the problem is that I am running on OSX.  The debugger is not
found. Perhaps its assuming GDB?

**Comment by brendandouglas** [comment]
We currently only support linux. We have support for OSX and Windows planned at some stage, but it's not a current priority. Some things may work on OSX (and do indeed seem to, based on some of the comments here), but it's completely untested.

As a separate issue, CLwB currently only supports gdb (see BlazeCidrLauncher for the relevant code). Still, if you have gdb installed on your system, and specify the binary path in the settings, I'd expect this to work.

**Comment by david-german-tri** [comment]
@asa, you may be interested in https://github.com/bazelbuild/bazel/issues/2537.  With the workarounds I've described on that thread, I've been able to generate `dSYM` files in `bazel-bin`.  I was then able to specify "Bundled GDB 7.11.1" in the CLion 2016.2.2 settings, and to debug Bazel-built binaries using GDB on OS X.  

One additional caveat: if your breakpoints don't take effect, check the console.  GDB may be complaining that it can't find your source files, which can be worked around by adding `set directories /path/to/my/workspace/root` to your `.gdbinit`.
