### ISSUE TITLE
Problem importing a project in IntelliJ - Invalid aspect

### ISSUE THREAD

**Issue by alessiocnit** [bazelbuild/intellij#4601]
### Description of the bug:

I'm trying to import onosproject with IntelliJ after installation of the bazel plugin. I did many times and every time I got some bazel problems... this time the problem is appearing during sync as follows:

Invalid aspect '@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect': invalid repository name '@@intellij_aspect': repo names may contain only A-Z, a-z, 0-9, ... ... ...

During Sysc in the Bazel Problems window. It suggest to retry without the option "Expand Sync to Working Set' but this does not solve the problem.

I'm running Intellij 2022.3.3 on Ubuntu 20.04

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Clone the ONOS project https://github.com/opennetworkinglab/onos
2. Import it in IntelliJ using the bazel plugin

### Which Intellij IDE are you using? Please provide the specific version.

2022.3.3

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2023.02.22.0.1-api-version-223

### Have you found anything relevant by searching the web?

none

**Comment by mai93** [comment]
Thanks @alessiocnit  for reporting this, what version of Bazel are you using?

**Comment by alessiocnit** [comment]
Yes indeed I'm using 6.0.0-pre.20220421.3 that is required by the ONOS project. I have installed it from the binary installer...

**Comment by mai93** [comment]
Can you use the stable release version of Bazel 6.0.0 instead of pre.20220421.3? The flag for unambiguous labels was flipped in https://github.com/bazelbuild/bazel/commit/b1113f801da87ed2e089ff4122aa13400c177804 after the version you're using.
