### ISSUE TITLE
Publish individual commits from google internal repo instead of batches

### ISSUE THREAD

**Issue by wcurrie** [bazelbuild/intellij#462]
With https://github.com/bazelbuild/bazel Copybara seems to be configured so individual commits are pushed to github. With this repo Copybara seems to publish batches. Having individual commits would make it possible for external folks to see when and how issues like https://github.com/bazelbuild/intellij/issues/225#issuecomment-442580506 are fixed.

Please 🙏. Maybe there aren't enough external folks to make this worth the effort..

**Comment by ittaiz** [comment]
+1

**Comment by jin** [comment]
The changes are published individually now.
