### ISSUE TITLE
sync project err

### ISSUE THREAD

**Issue by Lost-Temple** [bazelbuild/intellij#4631]
#### Version information
CLion: 2022.3.3
Platform: Mac OS X 13.2.1
Bazel for CLion plugin: 2023.02.07.0.1-api-version-223
Bazel: 5.0.0

1. In CLion, I set proxy http://127.0.0.1:7890 
2. bazel -> sync project with build file, got  "  Proxy address 127.0.0.1:7890 is not a valid URL" errors

**Comment by sgowroji** [comment]
Hi @Lost-Temple, Could you please elaborate your query with complete details. And can you confirm, above shared url is valid proxy. Thanks!
