### ISSUE TITLE
Downloaded dependencies are not available through intellij

### ISSUE THREAD

**Issue by soheil1987** [bazelbuild/intellij#4640]
### Description of the bug:

I am using IntelliJ IDEA 2022.3.2 (Ultimate Edition). My issue is after setting up a simple hello world project with BUILD and WORKSPACE files I attempt to import some external libraries using bazel query @maven//... command. the dependencies are downloaded and I see no issue while running bazel query command. But then i am not able to see the dependencies at External libraries section of intellij on the left side and I am not able to load any external class into my code. 

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3.2 (Ultimate Edition)

### What programming languages and tools are you using? Please provide specific versions.

Java 11

### What Bazel plugin version are you using?

6.1.1

### Have you found anything relevant by searching the web?

no

**Comment by idanakav** [comment]
Running the Bazel query has nothing to do with the IDE.
If you want a new dependency to be picked by the IDE (assuming it was already added to your WORKSPACE) just add it as a dependency to any BUILD file of a target that is already indexed on the IDE then sync the project again, I have just tested that and had no issues.

**Comment by soheil1987** [comment]
I have set the BUILD file too with proper instructions. I am attaching screenshot of my BUILD file inside the package, WORKSPACE file in the project root level and result of executing bazel query @maven//... command from terminal. 
<img width="1307" alt="build file" src="https://user-images.githubusercontent.com/5890256/227741563-c80d4c26-f639-40e5-ae3f-df057ec0757c.png">
<img width="528" alt="maven query" src="https://user-images.githubusercontent.com/5890256/227741564-146310a8-dd6d-48d2-8f91-2e9e1d7a6dd8.png">
<img width="1494" alt="workspace file" src="https://user-images.githubusercontent.com/5890256/227741565-575904da-ce1b-497e-be96-a2c61ca5350a.png">

**Comment by sgowroji** [comment]
Hi @soheil1987, Can you share a sample code to test the same with an example. Thanks !

**Comment by soheil1987** [comment]
the problem is intellij is not able to find the libraries downloaded by bazel, the code to show the issue can be as simple as this:

package soheil.pkg;

import com.github.javafaker.Faker;

public class MainClass {
    public static void main(String[] args) {
        System.out.println("helloo");
        Faker faker;
    }
}

import com.github.javafaker.Faker; is not working since although bazel downloaded the dependency but cannot be found and used as an external dependency in intellij. is there any additional step i need to take to make external dependencies visible to intellij?

**Comment by mai93** [comment]
@soheil1987 I tried with [this example project](https://github.com/bazelbuild/intellij/tree/master/examples/java/greetings_project) and the external dependencies like junit where brought into the IDE. If this project is also working for you, can you share with us the simple project you're seeing the problem with?

**Comment by raoarun** [comment]
@soheil1987 please help with @mai93 's question.  thanks.

**Comment by soheil1987** [comment]
Thanks for the help, I downloaded and checked the project and it works. I can now see the dependencies as external libraries. I close this issue then.
