### ISSUE TITLE
bazel project do not support for debug step by step in Clion

### ISSUE THREAD

**Issue by leland17** [bazelbuild/intellij#4653]
#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
My project is developed by C and compiled by bazel in the Clion，but Bazel Command （bazel run xxx）do not support for my code debug？
the Debug button is gray，the Run button is green for running。

how should i solve this problem？

#### Version information
CLion: 2023.1 RC
Platform: Linux 4.18.0-240.10.1.el8_3.x86_64
Bazel for CLion plugin: 2023.03.10.0.1-api-version-231
Bazel: 6.1.0

**Comment by sgowroji** [comment]
Hi @leland17, Could you please provide a sample code to test the same. Thanks !

**Comment by sgowroji** [comment]
Thanks for update. We are closing this issue now. Feel free to reach us for any further details.
