### ISSUE TITLE
Import incorrect package name prevents 221 build //aswb:aswb_bazel_zip failure

### ISSUE THREAD

**Issue by AlexBeggs** [bazelbuild/intellij#4658]
### Description of the bug:

`bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-2022.1` fails because of the import being incorrectly specified in the [DeploymentTimingReporterTask.java](https://github.com/bazelbuild/intellij/blob/master/aswb/sdkcompat/as221/com/google/idea/blaze/android/run/binary/DeploymentTimingReporterTask.java#L18) file

`import com.android.tool.idea.BaseAsCompat;` should be `import com.android.tools.idea.BaseAsCompat;`

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

attempt to build using the `bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-2022.1`

### Which Intellij IDE are you using? Please provide the specific version.

2022.1

### What programming languages and tools are you using? Please provide specific versions.

Java

**Comment by sgowroji** [comment]
Hi @AlexBeggs, Can you provide minimal steps required to reproduce the above problem. Thanks!
