### ISSUE TITLE
CLion tries to find out the compiler version by executing a raw gcc

### ISSUE THREAD

**Issue by Jonpez2** [bazelbuild/intellij#467]
CLion version 2018.12.5
Plugin version 2018.11.12.0.4.

Upon sync of the bazel setup, clion invokes the compiler as a raw command, outside of the bazel infra, in order to determine the version (gcc --version, for example).  This means that if you have wrapped your compiler in a shell script to help with vectoring between toolchains, any environment variables you set as part of your toolchain config aren't set, which makes things not work.

**Comment by jvoung** [comment]
To be clear, the symptom is that you then end up with
* "0 unique C configurations..." in the Bazel console
* an error message in the Bazel problems view?

Perhaps we could make the version not a hard requirement.
It's mainly used to have some incrementality (if nothing has changed we skip some C++ workspace setup steps, which can be slow in large projects). If we can't get the compiler version, just say that something may have changed and *not* skip.

Ideally, we'd match what bazel does to detect toolchain changes (assuming it doesn't involve running a binary)

This could also help with https://github.com/bazelbuild/intellij/issues/242 (msvc doesn't use the same flags format).

**Comment by Jonpez2** [comment]
Actually in my case the symptom is that my gcc script fails completely - I need to define a couple of variables to vector the specific gcc based on a --config arg.  Executing that outside a bazel command means I don't know which gcc to pick.

**Comment by Jonpez2** [comment]
Actually in my case the symptom is that my gcc script fails completely - I need to define a couple of variables to vector the specific gcc based on a --config arg.  Executing that outside a bazel command means I don't know which gcc to pick.

Agreed that it would fix that - would it be better to make a target that invokes the compiler command inside bazel and outputs the version, similar (ish!) to what you do to output the intellij-info.txt files?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
