### ISSUE TITLE
Importing a project does not correctly mark tests as being test sources they are just normal sources

### ISSUE THREAD

**Issue by paulduffin** [bazelbuild/intellij#4676]
### Description of the bug:

After migrating a Maven based project to Bazel, resulting in a structure that looks like this:
```
module/BUILD
module/src/main/java/...
module/src/test/java/....
```

Syncing the project marks both `java` directories as sources, the test one is not marked as test sources.

I thought it might have something to do with names so I moved the files into a more Bazel like structure:
```
module/BUILD
module/java/...
module/javatests/....
```

But that didn't work either.

I then thought it might be because the `BUILD` file is outside the `java/javatests` directories so I split it into two parts and moved them into this structure:
```
module/java/...
module/java/BUILD
module/javatests/....
module/javatests/BUILD
```

But that had no effect either. I tried switching to `test sources` manually but syncing just switched it back to `sources`.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 10, 2023 Runtime version: 17.0.6+1-b653.34 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Linux 5.19.0-38-generic GC: G1 Young Generation, G1 Old Generation Memory: 2048M Cores: 32 Non-Bundled Plugins:     com.javampire.idea-openscad (2.3.3)     com.google.idea.bazel.ijwb (2023.02.22.0.1-api-version-223)  Kotlin: 223-1.8.0-release-345-IJ8836.41 Current Desktop: ubuntu:GNOME

### What programming languages and tools are you using? Please provide specific versions.

$ bazel --version
bazel 6.1.1

### What Bazel plugin version are you using?

2023.02.22.0.1-api-version-223

### Have you found anything relevant by searching the web?

It is similar to #1993 but that was about resources this is about sources.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by sgowroji** [comment]
Hi @paulduffin, Could you please confirm the above maven project is build and run through bazel. Can you share code to test the same. Thanks !

**Comment by mai93** [comment]
Thanks @paulduffin! documentation for `test_sources` section was added to the plugin site (https://ij.bazel.build/docs/project-views.html#test_sources).
