### ISSUE TITLE
Wrong arguments passed to the debug program when debugging in bazel project using CLion

### ISSUE THREAD

**Issue by hzhr** [bazelbuild/intellij#4679]
### Description of the bug:

Error messages:
INFO: Running command line: /bin/bash -c ''\''bash'\'' '\''/home/user/.local/share/JetBrains/CLion2023.1/clwb/gdb/gdbserver'\'' '\''/usr/bin/gdbserver'\'' --once localhost:5006 --target bazel-bin/nginx'
Process /home/user/.cache/bazel/_bazel_user/8afda7aa452b64da121e2701f5367421/execroot/nginx/bazel-out/aarch64-dbg/bin/nginx created; pid = 1048459
Listening on port 5006
Remote debugging from host 127.0.0.1, port 38688
nginx: invalid option: "1>/tmp/gdbserver_wrapper.NXqkAGxJ/inferior.out"

Child exited with status 1

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Get nginx source from https://nginx.googlesource.com/nginx/
2. Import Bazel Project using CLion
3. Find & locate cc_binary: nginx in BUILD
4. Click "Debug 'Bazel run :nginx'"
5. Your should notice wrong argument "1>/tmp/gdbserver_wrapper.NXqkAGxJ/inferior.out" has passed to nginx and nginx reports invalid option.

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.1

### What programming languages and tools are you using? Please provide specific versions.

C

### What Bazel plugin version are you using?

6.1.1

**Comment by emidln** [comment]
This is the same bug as https://github.com/bazelbuild/intellij/issues/2958.

**Comment by emidln-imc** [comment]
This is fixed in the gdbserver wrapper here: https://github.com/imc-trading/intellij/commit/e13ee9ed31aa5ea7801217797b264e0804591eb2
