### ISSUE TITLE
Sometimes tool window has "Blaze" name instead of "Bazel" in IDEA

### ISSUE THREAD

**Issue by AnnaPrints** [bazelbuild/intellij#4684]
### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**Steps:**
1. Join a bazel project
2. Configure it
3. Check the name of the tool window

**Result:** Sometimes the tool window has "Blaze" name instead of "Bazel". But this bug is really ocassional 

### Which Intellij IDE are you using? Please provide the specific version.

Build #IU-231.8643, built on April 3, 2023

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

Bazel for Intellij 2023.03.10.0.1-api-version-231

**Comment by sgowroji** [comment]
Hi @AnnaPrints, Can you share the screenshot of it. Thanks!

**Comment by AnnaPrints** [comment]
![Screenshot 2023-04-03 at 16 08 10](https://user-images.githubusercontent.com/65970510/229757637-06f793e0-038f-4061-90d5-2061c0af3a1e.png)
