### ISSUE TITLE
Default Bazel Binary Preference to bazelisk IFF there is a .bazelversion

### ISSUE THREAD

**Issue by vorburger** [bazelbuild/intellij#4693]
### Description of the bug:

The plugin currently defaults the Bazel Binary Preference to `bazel`.

But Bazel may not actually be pre-installed and on the `$PATH` ..

... when using https://github.com/bazelbuild/bazelisk.

This is a follow-up to #3365 proposing to automate that.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Import any open source project using Bazelisk.

For example https://github.com/enola-dev/enola.

This will only work (correctly) after one manually changes the Bazel Binary Preference from `bazel` to `bazelisk`.

It's easy to work around (once you know about it), but in an ideal world, perhaps the plugin could detect the presence of a `.bazelversion` or `.bazeliskrc` file, and automagically change the binary from `bazel` to `bazelisk`?

**Comment by mai93** [comment]
You can add `bazel_binary: PATH_TO_BAZELISK` to the project view file and it will be used for the project. This can be used in projects that have `.bazelversion` or `.bazeliskrc` as you mentioned without adding this check in the plugin.

**Comment by vorburger** [comment]
@mai93 sorry but what's a "project view file"?

https://www.google.com/search?q=intellij+project+view+file

**Comment by mai93** [comment]
the `.bazelproject` file ([link](https://ij.bazel.build/docs/project-views.html)) used to configure your project while importing it with the Bazel plugin.

**Comment by vorburger** [comment]
@mai93 perhaps this would be something worthwhile to document on https://ij.bazel.build/docs/project-views.html ? 

There is no mention of a `bazel_binary` option on that page.

I would raise a PR to contrib, but apparently the doc is not open / on GitHub?

**Comment by mai93** [comment]
Fixed the documentation to show the `bazel_binary` section: https://ij.bazel.build/docs/project-views.html#bazel_binary
