### ISSUE TITLE
Gazelle support does not respect partial sync subtree

### ISSUE THREAD

**Issue by chadxzs** [bazelbuild/intellij#4699]
### Description of the bug:

When I configure the gazelle support and run a partial sync on my project, gazelle runs against the whole project instead of the subtree I have selected the partial sync on.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. setup gazelle support by adding `gazelle_target: //:gazelle` to the project view file `.ijwb/.bazelproject`.
2. right-click a subtree of the project that contains some of the files gazelle should operate on, then click "Partial Sync"

Gazelle will generate BUILD files outside the subtree selected for the partial sync.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2023.1 (Ultimate Edition) Build #IU-231.8109.175, built on March 28, 2023 Licensed to Chad Mcelligott Subscription is active until February 16, 2024. Runtime version: 17.0.6+10-b829.5 aarch64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. macOS 13.2.1 GC: G1 Young Generation, G1 Old Generation Memory: 16384M Cores: 10 Metal Rendering is ON Registry:     debugger.new.tool.window.layout=true     ide.experimental.ui=true     scala.erase.compiler.process.jdk.once=false  Non-Bundled Plugins:     com.jetbrains.plugins.ini4idea (231.8109.199)     net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)     org.intellij.plugins.hcl (231.8109.91)     com.vexus2.intellij.marked (0.2)     org.jetbrains.plugins.go-template (231.8109.91)     name.kropp.intellij.makefile (231.8109.91)     org.sylfra.idea.plugins.linessorter (1.0.1)     org.jetbrains.plugins.go (231.8109.175)     com.intellij.kubernetes (231.8109.91)     com.codename1.plugin.intellij (7.03)     String Manipulation (9.7.1)     reasonml (0.110-2023.1)     com.intellij.lang.jsgraphql (3.4.0)     me.mbolotov.cypress (1.5.2)     org.intellij.scala (2023.1.15)     MavenRunHelper (4.23.222.2964.0)     Pythonid (231.8109.175)     net.seesharpsoft.intellij.plugins.csv (3.1.0-231)     mobi.hsz.idea.gitignore (4.5.0)     com.google.idea.bazel.ijwb (2023.03.10.0.1-api-version-231)     ru.adelf.idea.dotenv (2023.1)  Kotlin: 231-1.8.20-IJ8109.175

### What programming languages and tools are you using? Please provide specific versions.

go version go1.19.1 darwin/arm64

### What Bazel plugin version are you using?

2023.03.10.0.1-api-version-231

**Comment by blorente** [comment]
Hello!
Unfortunately, this is a known limitation. It will actually run against (roughly) whatever you have specified in `directories`.
The main reason is how gazelle operates. 
Let's say you have the following directory structure:
```
├── a
│   ├── BUILD.bazel # defines //a:a_lib
│   └── a.go
└── b
    ├── BUILD.bazel # defines //b:depends_on_a
    └── b.go
```
And say that `//b:depends_on_a` needs `a:a_lib` to build.
Let's say you rename `a` to `c`, and then run a partial sync on `c`.

If we only ran gazelle on `c`, we'd run the equivalent of `bazel run //:gazelle -- c`, so `//b:depends_on_a` wouldn't be updated to depend on `c`.

There's an argument to be made about running gazelle on the contents of `targets`, not `directories`,  but I'm not sure it would be such a big performance gain.

**Comment by blorente** [comment]
No problem! Have a great day.
