### ISSUE TITLE
Dependencies in goland not taken

### ISSUE THREAD

**Issue by jgimeno** [bazelbuild/intellij#471]
Hi! I just installed a project using bazel, what I found is that once I build it creates some folders. In one of them there are the dependencies in a external folder.

But all dependencies that are not in my ~/go folder are not detected. This means that all the project looks broken.

Is there anything I need to do in order to detect them (avoiding downloading by hand all the broken dependencies into go folder)?

Thanks!!

**Comment by chaoren** [comment]
> it creates some folders

You mean bazel creates these new directories? E.g., `bazel-out`, `bazel-bin`, `bazel-<project name>`?

> In one of them there are the dependencies in a external folder.

Under `bazel-<project name>/external`?

> But all dependencies that are not in my ~/go folder are not detected.

Is `~/go` the project that you're opening in IntelliJ? The parent directory of the `bazel-*` directories?

Can you share your bazel project? Are you declare your go target dependencies correctly? Does your project view (.bazelproject file) properly contain your top level go BUILD targets?

**Comment by prestonvanloon** [comment]
Hey @chaoren, I was trying to help @jgimeno work through this earlier. The specific project they are trying to build is https://github.com/prysmaticlabs/prysm.

We are using rules_go for dependency management. I don't have goland license so i'm not able to verify their issue or configuration.

**Comment by jgimeno** [comment]
Thanks @prestonvanloon!

@chaoren just a stupid question, it is needed that I start the bazel project from scratch with the option from the goland wizard to import Bazel project? Because I did it after installing all dependencies via command-line console.

I can try this way to check if it acts diferently.

**Comment by chaoren** [comment]
> it is needed that I start the bazel project from scratch with the option from the goland wizard to import Bazel project?

Yes. You'll need to import bazel project, as opposed to just opening the directory as an IntelliJ project.

> I did it after installing all dependencies via command-line console.

Did you do this with the go command or the bazel command? You shouldn't use the go command directly on a bazel project.

**Comment by chaoren** [comment]
The current available bazel plugin has some bugs with package names, but that should be fixed in the next release.

Or if you want to build from source:
```
$ git clone https://github.com/bazelbuild/intellij.git
$ cd intellij
$ bazel build --define=ij_product=intellij-ue-latest ijwb:ijwb_bazel_zip
$ cd ~/.IntelliJIdea2018.2/config/plugins/
$ rm -r ijwb
$ unzip $OLDPWD/bazel-bin/ijwb/ijwb_bazel.zip
```

So I did the following:

1. `$ git clone https://github.com/prysmaticlabs/prysm.git`
2. `Import Bazel Project`
3. Navigate to the `prysm` directory.
4. Select project view -> Create from scratch.
5. Project View:
```
directories:
  .

targets:
  //...

additional_languages:
  go
```
6. Finish.
7. Wait for bazel build and indexing to finish.
8. Navigate to `prysm/beacon-chain/main.go`

Everything resolves.

**Comment by jgimeno** [comment]
Thanks @chaoren ! I am trying it but with this new build it autodisables Bazel by default.

Do you know if it is because I use goland instead of intellij?

Is there another product that I should use when building it?

bazel build --define=ij_product=**intellij-ue-latest** ijwb:ijwb_bazel_zip

Thanks!

Another thing I found is by default it sets the binary as bazel, but in mac I needed to set it in the settings with the full path.

**Comment by chaoren** [comment]
> I am trying it but with this new build it autodisables Bazel by default.

You might have an incompatible version of the IDE.
intellij-ue-latest currently points to intellij-ue-2018.2.
You can also try intellij-ue-2018.3.

> I needed to set it in the settings with the full path.

Yes, you can update the path in File -> Settings -> Other Settings -> Bazel Settings.

**Comment by jgimeno** [comment]
Ok! I can confirm that it works with IntelliJ version 2018.2 and the plugin compiled by hand. We can close, after the release it will be easier.
