### ISSUE TITLE
CLion plugin is incompatible to bazel flag incompatible_struct_has_no_methods

### ISSUE THREAD

**Issue by martis42** [bazelbuild/intellij#4713]
### Description of the bug:

A Bazel project using `incompatible_struct_has_no_methods` to make sure it is not by accident using deprecated behavior is not compatible to the CLion Bazel plugin.

Desired solution:
Changing the implementation to use the forward path pattern and then to use `incompatible_struct_has_no_methods` in the CI to make sure the issue does not reappear until Bazel flips this flag in a future release.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Setup a Bazel project with CLion
2. Create a `.bazelrc` file in the project and add `--incompatible_struct_has_no_methods`
3. Start a project sync

Exemplary error:
```
ERROR: <path_to_build_file>/BUILD:3:11: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on py_library rule //src/analyze_includes:lib: 
Traceback (most recent call last):
	File "<path_into_cache>/e663c61e10a8ed8d3fb71670c233b37b/external/intellij_aspect/intellij_info_bundled.bzl", line 67, column 37, in _aspect_impl
		return intellij_info_aspect_impl(target, ctx, semantics)
	File "<path_into_cache>/e663c61e10a8ed8d3fb71670c233b37b/external/intellij_aspect/intellij_info_impl.bzl", line 1136, column 42, in intellij_info_aspect_impl
		ctx.actions.write(ide_info_file, info.to_proto())
Error: 'struct' value has no field or method 'to_proto'
Available attributes: build_file_artifact_location, deps, features, key, kind_string, py_ide_info, tags
```

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.1.1 Build #CL-231.8109.2222

### What programming languages and tools are you using? Please provide specific versions.

Python 3.8, rules_python 0.8.0, bazel_skylib 1.4.1

### What Bazel plugin version are you using?

2023.03.10.0.1-api-version-231

### Have you found anything relevant by searching the web?

Bazel changed with version 4.0.0 how one is supposed to create proto and json output: https://blog.bazel.build/2021/01/19/bazel-4-0.html#starlark

### Any other information, logs, or outputs that you want to share?

Changing this would make the plugin incompatible to Bazel version < 4.0.0. In my opinion Bazel 3.x is far enough in the past that this is viable. Especially, given the rapid development of Bazel.
That much said, being incompatible to potential users is of course always a tricky decision to make.

**Comment by mai93** [comment]
> #4772

Yes, I created that but as you can see we have failing tests because this change is not compatible with Bazel 1.2.0

**Comment by mai93** [comment]
fixed in https://github.com/bazelbuild/intellij/commit/895876f7f2c29f9b483339dac09d2f024b073820

**Comment by martis42** [comment]
@tpasternak , @mai93 
Thanks a lot for fixing this.
I see you fixed the code causing the warnings. Would it make sense to you to also adjust the CI to use the corresponding incompatibility flag so the old style cannot be introduced again by accident?

**Comment by mai93** [comment]
Thanks for the suggestion @martis42! I tried adding the flag to the project .bazelrc but some external dependencies need to be updated first (https://buildkite.com/bazel/intellij-plugin-aspect/builds/19569#0189508f-0476-4830-8ec6-2b03f2263f64)

**Comment by martis42** [comment]
Too bad. Still, thanks for trying!
