### ISSUE TITLE
Clion navigation support not working with bazel project - no project indexing.

### ISSUE THREAD

**Issue by burghardt92** [bazelbuild/intellij#4719]
#### Description of the issue. 

CLion isn't indexing the bazel project like it does with CMake, so I am unable to jump to function definitions or file declarations with ctrl+click in my existing project.

#### Version information
CLion: 2023.1.1
Platform: Linux 5.4.0-146-generic
Bazel for CLion plugin: 2023.03.10.0.1-api-version-231
Bazel: 5.4.0

**Comment by Pavank1992** [comment]
Hi @burghardt92,
The fix of the issue provided [here](https://github.com/bazelbuild/intellij/issues/938#issuecomment-1481179667). If you are looking for different behaviour please post with a video reference so we can dive deep into this. Thanks!

**Comment by burghardt92** [comment]
Hi @Pavank1992,  
Thank you for your quick response.
I can navigate to external standard headers (i.e. `#include <vector>`), as shown in that video, and I can navigate to external symbols (i.e. right click on `std::vector` takes me to `stl_vector.h` for some, but not all usages).
However, I cannot navigate to headers internal to my project, nor symbols internal to my project.
Similarly, I cannot navigate to headers/symbols from non-standard external libraries linked to my project (i.e. `eigen`).
The project builds from command line and the Clion "sync project with BUILD files" works as well.
