### ISSUE TITLE
Running tests on a broken package looks successful (UI)

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/intellij#472]
When running tests from a broken package, the console view shows the Bazel build failure, but the tests panel shows an empty test result labeled "Test Results" and marked with a green V icon, which is very similar to successful test results when "Show Passed" is turned off, and can be very confusing.

I'm trying to solve that and I'm seeking some good advice. Here is where I got so far:
I was trying to intercept that condition in [BuildEventProtocolOutputReader](https://github.com/bazelbuild/intellij/blob/b55f77a6d13fa4c03e7be21a1ea599f13551d72d/base/src/com/google/idea/blaze/base/command/buildresult/BuildEventProtocolOutputReader.java#L67), by adding a case for `BUILD_FINISHED` events, checking whether the build was successful and trying to figure out what was the reason for that failure from the value of `event.getFinished().getExitCode()`. My problem is that the information is there, but it's a string and I prefer to avoid relying on hard-coded strings in the plugin. I saw that there is a corresponding representation of `ExitCode` [in the Bazel project](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/ExitCode.java), but depending on Bazel code is not really an option here, so I'm looking for another way to extract that information safely and nicely or maybe another approach to solve the whole problem.

Thanks!

**Comment by or-shachar** [comment]
Note: this behavior was observed on latest released plugin `2018.11.12.0.4` with intellij 2018.3.1 
cc: @brendandouglas @chaoren  - @sha1n would like to contribute a fix for it. 

Can you pls help @sha1n with his exploration or mention the right person here?

**Comment by chaoren** [comment]
> My problem is that the information is there, but it's a string and I prefer to avoid relying on hard-coded strings in the plugin.

Haha. Hardcoded strings are everywhere in this plugin.
You basically want to translate a bazel `ExitCode` into a `TestStatus` enum, right?
I think it's probably best to just add a `fromExitCode` method to `TestStatus`, and hardcode all the strings there in a giant switch.

**Comment by chaoren** [comment]
Wouldn't they all just be `FAILED_TO_BUILD`? So there's no need to parse the string.

**Comment by brendandouglas** [comment]
This should already be fixed at HEAD -- BlazeXmlToTestEventsConverter#flushBufferOnProcessTermination now checks the exit code (BlazeTestExitStatus#forExitCode).

**Comment by sha1n** [comment]
Thanks @chaoren! I haven’t covered all cases, but I saw that when build files are invalid, I get PARSING_FAILD..

@brendandouglas thanks for the update! I’ll check it out early next week.

**Comment by sha1n** [comment]
Fixed indeed - closing this one.

Thank you guys 👍

**Comment by sha1n** [comment]
@brendandouglas this issue is reproducible again. I debugged it and saw that BlazeXmlToTestEventsConverter#flushBufferOnProcessTermination fails to identify the condition because `testResults == BlazeTestResults.NO_RESULTS` evaluates to `false`. Looking further, I saw that `BuildEventProtocolOutputReader#parseTestResults` indeed returns an empty `BlazeTestResults` instance and not the specific instance `BlazeTestResults.NO_RESULTS`, which to my understanding returns only in case `BuildEventProtocolOutputReader#parseTestResults` throws an exception. It seems to me that something needed to change underneath (in the BEP event stream?) in order to break this..

I think it would be more robust if we could rely on BEP events to determine whether we have a build failure or not. WDYT?

Thanks!

**Comment by sha1n** [comment]
@brendandouglas looks like I have made a mistake and confused our forked repo with this one.. I will close this for now and run some more tests, to make sure I was indeed wrong.

In any case, my observation regarding how the code determines whether the build has failed or not still stands. 

Thanks and sorry for the noise - I will report back if there are issues.

**Comment by odisseus** [comment]
This issue has reappeared in [v2025.04.01-rc-1](https://github.com/bazelbuild/intellij/releases/tag/v2025.04.01-rc-1).

### Steps to reproduce
1. Import `examples/kotlin/simple_project.`
2. Open `GreetingTest.kt` and edit it so that the compilation fails.
3. Click the green triangle next to the class name and run the tests.

<img width="1457" alt="Image" src="https://github.com/user-attachments/assets/b162f59c-f724-4eb9-bc85-a744cb3f24d9" />

It has been addressed by #7562, but that pull request has introduced another problem (#7586).
