### ISSUE TITLE
Intellij unable to find proper cc_toolchain_config rule @local_config_cc

### ISSUE THREAD

**Issue by cdickson-sum** [bazelbuild/intellij#4732]
### Description of the bug:

Unable to sync a project in the IDE that works without any issues from the command line. The SYNC fails with multiple errors on everything that has a dependency on a tool that needs to be compiled such as protobuff or rules_docker's parts that need GO. For the same project, same machine, all build, test and run targets along with several complicated queries execute perfectly from the terminal (even the one inside IDE). 

/private/var/tmp/_bazel_xxxxxxx/2100b069ba018abf9fc21d3f28094df0/external/local_config_cc/BUILD
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:tvos_arm64: 
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:watchos_arm64: 
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:ios_arm64e: 
Error:(92, 24) Analysis of target '@local_config_cc//:ios_arm64e' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:ios_x86_64: 
Error:(92, 24) Analysis of target '@local_config_cc//:ios_x86_64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:ios_arm64: 
Error:(92, 24) Analysis of target '@local_config_cc//:ios_arm64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:tvos_sim_arm64: 
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:ios_i386: 
Error:(92, 24) Analysis of target '@local_config_cc//:ios_i386' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:darwin_x86_64: 
Error:(92, 24) Analysis of target '@local_config_cc//:darwin_x86_64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:ios_armv7: 
Error:(92, 24) Analysis of target '@local_config_cc//:ios_armv7' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:watchos_armv7k: 
Error:(92, 24) Analysis of target '@local_config_cc//:watchos_armv7k' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:darwin_arm64: 
Error:(92, 24) Analysis of target '@local_config_cc//:darwin_arm64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:watchos_x86_64: 
Error:(92, 24) Analysis of target '@local_config_cc//:watchos_x86_64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:tvos_x86_64: 
Error:(92, 24) Analysis of target '@local_config_cc//:tvos_x86_64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:watchos_i386: 
Error:(92, 24) Analysis of target '@local_config_cc//:watchos_i386' failed
Error:(92, 24) Analysis of target '@local_config_cc//:tvos_sim_arm64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:ios_sim_arm64: 
Error:(92, 24) Analysis of target '@local_config_cc//:ios_sim_arm64' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:watchos_arm64_32: 
Error:(92, 24) Analysis of target '@local_config_cc//:watchos_arm64_32' failed
Error:(92, 24) in cc_toolchain_config rule @local_config_cc//:darwin_arm64e: 
Error:(92, 24) Analysis of target '@local_config_cc//:darwin_arm64e' failed
Error:(92, 24) Analysis of target '@local_config_cc//:watchos_arm64' failed
Error:(92, 24) Analysis of target '@local_config_cc//:tvos_arm64' failed

This is on an M1 Mac using the latest IDE and plugin versions. 
There are no IDE specific settings in .bazelrc

What is the IDE doing that would a) not resolve the same as bazel and b) not be using the artifacts for the rules that are already available from the command line run?

Is there a flag or some IDE setting that can resolve this? 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have not found a simple way to reproduce this issue.

### Which Intellij IDE are you using? Please provide the specific version.

2023.1

### What programming languages and tools are you using? Please provide specific versions.

Java 11, Kotlin 1.7, rules_docker, rules_detekt

### What Bazel plugin version are you using?

2023.03.10.0.1-api-version-231

### Have you found anything relevant by searching the web?

Nothing, asked about this in Bazel intellij slack channel, no responses.

**Comment by mai93** [comment]
I am not sure I can investigate this without a minimal example to reproduce the issue. 
> What is the IDE doing that would a) not resolve the same as bazel and b) not be using the artifacts for the rules that are already available from the command line run?

You can check the command invoked by the plugin in the Sync window to see what flags are used. Maybe try running it from command line if anything interesting comes up.

**Comment by cdickson-sum** [comment]
Sorry for the delay in response. I was able to work around this by commenting out:
#common --incompatible_existing_rules_immutable_view in my .bazelrc. I worked on getting a smaller project together to show the issue, but was unable to get anything sufficiently complex enough to cause it. rules_docker seems to play some role also. My primary concern is the build/test/run all being successful from the command line, and the IDE sync failing. Looking over the build options, the IDE and the command line appear to be using the same flags.

**Comment by cdickson-sum** [comment]
I believe I have a clue to the issue. My command line version (pulled via bazelisk) is properly pulling the ARM64 bazel version (on an M2 Mac), while the IDE is pulling the incorrect x86_64 version:
`Downloading https://releases.bazel.build/6.1.2/release/bazel-6.1.2-darwin-x86_64...` which might help explain not finding a proper cc toolchain.

**Comment by mai93** [comment]
You can point the plugin to use `bazelisk` (or any specific bazel binary) by setting it from Settings -> Other settings -> Bazel Settings -> Bazel binary location. This way the selected binary will be used for all projects that you import. To select a binary specificly for a certain project, you can specify it in the project view file using `bazel_binary` (https://ij.bazel.build/docs/project-views.html#bazel_binary)
