### ISSUE TITLE
FR: Use configurable buildozer + buildifier for BUILD file modify + formatting

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/intellij#477]
For build file modification the plugin uses [simple text modifier](https://github.com/bazelbuild/intellij/blob/194f34b0690827918356eab5ae84fe85c8f6c50c/base/src/com/google/idea/blaze/base/lang/buildfile/actions/BuildFileModifierImpl.java)

For build file formatting the plugin uses [hardcoded version of buildifier](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/buildmodifier/BazelBuildifierBinaryProvider.java). Currently set to 0.12.0 when the last released version is 0.20.0

We should use **`buildozer`** for modifications and allow configuring local binaries

### Feature requests:

1) Use **`buildozer`** for build file modification. Have a built-in buildozer binary as well. Change buildModifier to drive the binary and not change text manually. (note: `buildozer` expects to find `buildifier` on PATH, but I'm sure we can solve it, eg: modifying the PATH according to configured buildifier)
2) Allow overriding the built-in tools by providing path to locally installed tools (so we can use newer versions). We already have configuration for bazel binary - let's add configuration for those tools as well.

###  Related issues

https://github.com/bazelbuild/intellij/issues/261

**Comment by idankWix** [comment]
@brendandouglas WDYT?

**Comment by ignasl** [comment]
Configurability with sane defaults should always be a good idea. I am looking into this issue. Starting with the `buildifier`, the idea is to allow user choose either built-in tool or pre-installed in the system:
- Add checkbox in "Bazel Settings" to use built-in `buildifier` binary
- Add `Buildifier` binary location file edit box to set the alternative binary
The [`BazelBuildifierBinaryProvider`](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/buildmodifier/BazelBuildifierBinaryProvider.java) then makes appropriate choices to provide the binary file.

**Comment by or-shachar** [comment]
@brendandouglas  - @ignasl is taking this task. 
Please comment as soon as you can if this is done in any way in your upstream repository to avoid redundant work

**Comment by or-shachar** [comment]
@brendandouglas ?

**Comment by brendandouglas** [comment]
What's the use case for customizing the buildifier/buildozer binaries?

Rather than a user setting, how about allowing any version already present on PATH to override the bundled version?

**Comment by ignasl** [comment]
The alternative solution, as you say, would be to use any version present in PATH and if it is not present (i.e. process create fails), fall back to the built-in one. This would work, but:

- user may want to choose a different version for different projects she is working on, say to maintain legacy code
- use configuration to point to some scripts to append some options
- test-drive new version before replacing the one found in PATH

All that can be achieved using symbolic links, scripting, and other tools. The question is convenience -- for most it would be much faster to just change the path to the executable than create a link or write a script that would make necessary choices.

**Comment by ignasl** [comment]
Another use-case for having buildifier and buildozer configuration is that on MacOS X (at least on 10.14) `/usr/local/bin` does not appear in PATH that Java gets from environment and this is where these tools would normally be installed if access to `/usr/bin`, `/bin' or other system folders is restricted.

**Comment by kylecordes** [comment]
I notice this issue starkly while switching back and forth between this plugin and VScode with its plugin... which (while not without its own open issues) "just works" with the `buildifier` already on the PATH.
