### ISSUE TITLE
clion: external repositories do not sync with the IDE

### ISSUE THREAD

**Issue by isaactorz** [bazelbuild/intellij#4775]
### Description of the bug:

Projects added in `WORKSPACE.bazel`, using `local_repository`, or `new_local_repository`, are not indexed or synced into the IDE.

As a result none of the intellisense features work.

Trying to partially sync the projects makes matters worse and results in the file text being completely grey'd out.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Load any C++ project into CLion that uses `local_repository` or `new_local_repository`. The files are not present in the IDE, and when debugging into them, none of the intellisense features work.

Debug information is also not present.

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2022.3.2

### What programming languages and tools are you using? Please provide specific versions.

C++14

### What Bazel plugin version are you using?

2023.01.10.0.1-api-version-223

### Have you found anything relevant by searching the web?

No

**Comment by sgowroji** [comment]
Closing this issue as there is already a Duplicate https://github.com/bazelbuild/intellij/issues/4774
