### ISSUE TITLE
Find Usages on a symbol shows all usages in "production" (when grouping by test/production)

### ISSUE THREAD

**Issue by berman7** [bazelbuild/intellij#479]
There are no usages in tests, even if they exist. The test usages appear in "production" as well.

**Comment by brendandouglas** [comment]
What language is involved here? Is the test file highlighted green in the project view? (you'll need to add the parent directory to your .bazelproject test_sources section -- https://ij.bazel.build/docs/project-views.html#test_sources)

**Comment by ittaiz** [comment]
Scala.
What do you mean by green? Is it synced? It’s synced.
We tried adding:
```
test_sources:
*/src/test/scala/*
*/src/it/scala/*
*/src/e2e/scala/*
```
*BUT* we got several complaints from internal users that the IDE gets stuck
frequently.
We need the above since we have many many distinct test modules.

**Comment by brendandouglas** [comment]
Test sources have a different background highlight color in the project tab (green by default).

Specifying test_sources in your project view shouldn't cause slowness -- it's not something we've seen before. Is the original problem resolved when adding those test sources?

**Comment by ittaiz** [comment]
It is resolved. Once we got a few complaints we told people to stop using
it.
I’ll ask more people to try and see if the data was incidental.

**Comment by or-shachar** [comment]
I think we can close it now... Our users use the test_sources feature without special performance hit
