### ISSUE TITLE
Allow synchronization via `bazel query`

### ISSUE THREAD

**Issue by DeCarabas** [bazelbuild/intellij#4792]
#### Description of the issue. Please be specific.

We have a number of targets tagged "manual" that we have to irritatingly sync by hand.

I believe these are excluded from the regular sync because the regular sync uses bazel wildcards, and the targets are excluded from the wildcard. 

It would be great if the bazel plugin could use `bazel query` to determine the targets to sync rather than `bazel build`: this would allow everything to be discovered, and still let us exclude some of our targets from wildcard build and test.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.

1. Have a project with some manual targets and an extremely minimal project view. (In particular, the project view should reference the manual targets implicitly via wildcard, not explicitly.)
2. Sync the project.
3. Note the manual targets are missing.

#### Version information
IdeaUltimate: 2022.3.1
Platform: Linux 5.19.0-1023-aws
Bazel for IntelliJ plugin: 2023.03.21.0.1-api-version-223
Bazel: 5.3.0

**Comment by mai93** [comment]
I think this is similar to https://github.com/bazelbuild/intellij/issues/4546. @rogerhu is planning to provide a fix.

**Comment by rogerhu** [comment]
Sorry for the delay - here is the proposed patch. https://github.com/bazelbuild/intellij/pull/5085

**Comment by rogerhu** [comment]
This ticket i believe can be closed?
