### ISSUE TITLE
Bazel with incompatible_disallow_data_transition

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/intellij#482]
Based on the CI, the plugin doesn't work with `bazel --incompatible_disallow_data_transition`: https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/48#de3c42b3-4841-4c2f-9c0c-272f51568af7

Since the error message is in scala.bzl, can you please update the dependency on Scala? It has been fixed there.

**Comment by brendandouglas** [comment]
Thanks, this should be fixed at head now.
