### ISSUE TITLE
Missing Scratches and Consoles node in Project window

### ISSUE THREAD

**Issue by tekumara** [bazelbuild/intellij#483]
The `Scratches and Consoles` node is missing in the Project window for Bazel projects opened on macOS with:

IntelliJ IDEA 2018.2.7 (Ultimate Edition)
Build #IU-182.5107.41, built on November 27, 2018

**Comment by brendandouglas** [comment]
This is fixed for newer plugin releases, but they're only available for 2018.3 (https://plugins.jetbrains.com/plugin/8609-bazel).
