### ISSUE TITLE
MODULE.bazel needs syntax highlighting

### ISSUE THREAD

**Issue by amir-f** [bazelbuild/intellij#4851]
### Description of the feature request:

`MODULE` or `MODULE.bazel` does not come with syntax highlighting currently. See the [documentation here](https://bazel.build/external/module).

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

MacOS Ventura 13.3.1 ; PyCharm 2022.3.1

**Comment by emidln** [comment]
bzlmod-related files, MODULE and MODULE.bazel should be syntax-highlighted by the bazel plugin in a similar manner to BUILD/WORKSPACE/*.bazel

**Comment by amir-f** [comment]
Thanks @emidln . @sgowroji what more details are needed?

**Comment by Vertexwahn** [comment]
Waiting for this also for CLion!
