### ISSUE TITLE
Clion plugin doesn't work with custom CROSSTOOL

### ISSUE THREAD

**Issue by ghost** [bazelbuild/intellij#486]
I configured a custom CROSSTOOL for clang on ubuntu 18.04. I was able to build my workspace by setting --crosstool_top=//bazel/tools/cpp:toolchain --cpu=k8 --compiler=clang

and I added 
` build --crosstool_top=//bazel/tools/cpp:toolchain --cpu=k8  --compiler=clang`
to .bazelrc, which works well in command line.  But CLion fails to sync build file. 

Got the following error
"intellij_aspect/intellij_info_impl.bzl", line 365, in collect_c_toolchain_info

	cc_common.configure_features(cc_toolchain = cpp_toolchain, requ..., ...))
expected value of type 'CcToolchainInfo' for parameter 'cc_toolchain', in method call configure_features(ToolchainInfo cc_toolchain, list requested_features, list unsupported_features) of 'cc_common'.

**Comment by mnlnl4** [comment]
Let me update bazel and clion then report back.

**Comment by mnlnl4** [comment]
CLion bazel plugin 2018.12.03.0.2
CLion 2018.2.7
bazel 0.21.0

**Comment by kevin-nuro** [comment]
Also saw this on Bazel 0.24.1.

It seems that this line is returning an instance of ToolchainInfo instead of CcToolchainInfo:
https://github.com/bazelbuild/intellij/blob/f3399ff15516fa93f0df490c6d0649c6e32a60e1/aspect/intellij_info_impl.bzl#L435-L436

**Comment by speedskater** [comment]
I just stumbled across the this issue with bazel 0.29 and the latest version of the clion bazel plugin using a custom c++ toolchain.

Thanks @kevin-nuro for pointing me in the right direction for a workaround.

A workaround is to define `tags = ["no-ide"]` on targets created with the `cc_toolchain` rule. Using this workaround the plugin picks up the CCToolchainInfo from your defined `cc_toolchain_suite` and everything works as expected.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
