### ISSUE TITLE
Question : 

### ISSUE THREAD

**Issue by bnadim** [bazelbuild/intellij#4873]
Hi, 

Thanks for the great work with this plugin.
I am trying to write a set of rules for terraform and I define terraform modules(library) as dependcies of other modules or a build (binary)

Intellij with the help of terraform plugin support auto complete.
When I create a terraform module and try to reference it through its generated path in the binary or as a dependency Intellij reports that it can not find the directory and of course auto complete does not work.

Is their a way to help this plugin understand run files or files structure so Intellij detects build folder the same way it does for a go dependency or does it requires additional development on this plugin it self.

Here is an exemple : 
Let's say I define this module : 
`terraform_library(
    name = "a_module",
    srcs = [
        "module_main.tf",
    ],
    importname = "a_module",
    visibility = ["//visibility:public"],
)`

and a binary such as 
`terraform_binary(
    name = "with_module",
    srcs = [
        "main.tf",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//some_path.../modules/a_module",
    ],
)`

And let's say that the main file content is something such as
`module "a_module" {
  source = ".modules/a_module"
}`

Intellij reports that it can not find the path .modules/a_module.
However, .modules/a_module is set as a file and a runfile of my terraform_binary target

If something is not clear please let me know.

Thank you for your help.

NB: the terraform rules are not official, it's custom developed.

**Comment by bnadim** [comment]
Hi, 

Thanks for the great work with this plugin.
I am trying to write a set of rules for terraform and I define terraform modules(library) as dependcies of other modules or a build (binary)

Intellij with the help of terraform plugin support auto complete.
When I create a terraform module and try to reference it through its generated path in the binary or as a dependency Intellij reports that it can not find the directory and of course auto complete does not work.

Is their a way to help this plugin understand run files or files structure so Intellij detects build folder the same way it does for a go dependency or does it requires additional development on this plugin it self.

Here is an exemple : 
Let's say I define this module : 
`terraform_library(
    name = "a_module",
    srcs = [
        "module_main.tf",
    ],
    importname = "a_module",
    visibility = ["//visibility:public"],
)`

and a binary such as 
`terraform_binary(
    name = "with_module",
    srcs = [
        "main.tf",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//some_path.../modules/a_module",
    ],
)`

And let's say that the main file content is something such as
`module "a_module" {
  source = ".modules/a_module"
}`

Intellij reports that it can not find the path .modules/a_module.
However, .modules/a_module is set as a file and a runfile of my terraform_binary target

If something is not clear please let me know.

Thank you for your help.

NB: the terraform rules are not official, it's custom developed.

**Comment by sgowroji** [comment]
Hi @bnadim, Could you please provide complete steps to reproduce the above issue and please update the title accordingly. Thanks!
