### ISSUE TITLE
IntelliJ plugin does not handle Kotlin associates

### ISSUE THREAD

**Issue by jdai8** [bazelbuild/intellij#4914]
### Description of the bug:

Direct dependencies are not synced if they come from Kotlin [`associates` attributes](https://bazelbuild.github.io/rules_kotlin/kotlin#kt_jvm_library-associates).

I think this is happening because `associates` is not in the list of known dep-like attributes here: https://github.com/bazelbuild/intellij/blob/3c68f0b663468524fce2b70073d6fae2d44d01e5/aspect/intellij_info_impl.bzl#L29

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
# .bazelproject
targets:
  //examples/kotlin/project_with_associates/a
```

```
# examples/kotlin/project_with_associates/a/BUILD
load(
    "@io_bazel_rules_kotlin//kotlin:kotlin.bzl",
    "kt_jvm_library",
)

kt_jvm_library(
    name = "a",
    srcs = ["A.kt"],
    associates = [
        ":b"
    ],
)

kt_jvm_library(
    name = "b",
    srcs = ["B.kt"],
)
```

If we load this into IntelliJ, then `B.kt` will be un-synced, despite being a direct dependency of A.

Changing `associates` to `deps` does cause `B.kt` to become synced.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2023.1.1 (Community Edition)

### What programming languages and tools are you using? Please provide specific versions.

Kotlin

### What Bazel plugin version are you using?

2023.05.02.0.1-api-version-231

**Comment by mai93** [comment]
Closing as https://github.com/bazelbuild/intellij/pull/4915 is merged.
