### ISSUE TITLE
Facing an issue with transitive dependencies

### ISSUE THREAD

**Issue by soheil1987** [bazelbuild/intellij#4917]
### Description of the bug:

So I am not able to access transitive dependencies in my code. I use maven_install to import external dependency. the dependency is imported correctly and I can access it in the code but transitive dependencies are not available. so in this screen shot as you see i use maven_install to import HTTPClient library.

<img width="1075" alt="Screen Shot 2023-05-25 at 3 03 25 PM" src="https://github.com/bazelbuild/intellij/assets/5890256/5b02b18e-71e6-480a-acaa-ada1f450f2b2">

while what i was expecting was having all my transitive dependencies available at the compile time as shown by the following screenshot

<img width="1025" alt="Screen Shot 2023-05-25 at 3 21 00 PM" src="https://github.com/bazelbuild/intellij/assets/5890256/8a6c3b65-2144-48e5-8f46-db9aab4bdacc">

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

just in intellij try to import an external dependency which you are sure has some transitive dependencies too such as 
https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.14 and then on the left side check if you are able to see transitive dependencies are brought in.

### Which Intellij IDE are you using? Please provide the specific version.

2022.3

### What programming languages and tools are you using? Please provide specific versions.

java 17

### What Bazel plugin version are you using?

bazel plugin for intellij

### Any other information, logs, or outputs that you want to share?

I am using bazel 6

**Comment by Pavank1992** [comment]
Hi @soheil1987, Could you please share exact steps with sample code/repo you are following to reproduce the issue? Thanks!

**Comment by PertsevRoman** [comment]
UPD: I just added java_binary resourse and it helped to resolve all the dependencies after sync. Not sure why in MacOS it's not necessary. Plugin debug session hasn't shown any issue.

**Comment by soheil1987** [comment]
would you please elaborate about what you mean by adding java_binary resource?
