### ISSUE TITLE
The IntelliJ project tree is sometimes hilariously wrong

### ISSUE THREAD

**Issue by DeCarabas** [bazelbuild/intellij#4928]
### Description of the bug:

Sometimes, in some folders, the project view is very wrong. Here's an example of something it's generating today:

<img width="329" alt="image" src="https://github.com/bazelbuild/intellij/assets/9754/892bad47-9764-482d-b268-90701705081d">

Note that it's consistent per commit, that is, the state of the source tree at a given commit hash generates the same set of glitches.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't have a good repro for arbitrary repositories, but in our repository:

- Clone the repository
- Import the project
- Click around, you'll find something busted

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA Ultimate 2022.3.1 (Build 223.8214.52)

### What programming languages and tools are you using? Please provide specific versions.

Java (coretto-1.8)

### What Bazel plugin version are you using?

2023.05.02.0.1-api-version-223

### Have you found anything relevant by searching the web?

I have not been able to find anything. :(

**Comment by Pavank1992** [comment]
Hi @DeCarabas, Thanks for creating the issue. Could you please help us to reproduce the issue by sharing the sample repo? Thanks!

**Comment by tarique-lw** [comment]
@Pavank1992 We don't have a sample repo at the moment. It is our organisation's codebase where we are seeing this issue.

I would suggest to reproduce issue in some large codebase which has multiple modules and those modules have `src/main/java` and `src/test/java` folder structure.
Once you do `bazel sync` the complete project you should be seeing this issue.

**Comment by mai93** [comment]
I was not able to reproduce this, I will keep it open if someone faced this and detected a clear reproducible pattern.
