### ISSUE TITLE
CLion does not find stdlib `assert()` macro on macOS

### ISSUE THREAD

**Issue by dwtj** [bazelbuild/intellij#493]
## Problem

I've created a simple Bazel workspace including a `cc_binary` target using the standard library's `assert()` macro.

```cpp
#include <cassert>
#include <assert.h>

int main() {
  assert(2 + 2 == 5);
  return 0;
}
```

This target builds and runs fine from both the command line and from within CLion.

However, CLion cannot find the C++ standard library's `assert()` macro.

I've made a repository, [dwtj/clwb-bugs-example](https://github.com/dwtj/clwb-bugs-example), where this program is built in both a CLion+CMake project and a CLion+Bazel project. The image below demonstrates that `assert()` is found in the former but not the latter.

<img width="1517" alt="cmake_vs_bazel-assert_not_found" src="https://user-images.githubusercontent.com/2457848/51068716-c055fc00-15e7-11e9-9798-9ee3d7944775.png">

The two error messages are

- 'assert.h' file not found
- Use of undeclared identifier assert

CLion should not be reporting these errors.

## My Development Environment

- macOS 10.14.2 (Mojave)
- CLion v2018.2.7 (Though CLion v2018.3.0+ are more recent, they don't seem to be compatible with the latest versions of the plugin.)
- I've observed the above problem when using two versions of the [bazelbuild/intellij](https://github.com/bazelbuild/intellij) plugin:
    - v2018.12.03.0.2 (currently the latest pre-built release; retrieved with standard CLion plugin manager)
    - `0f45ef4` (built from source)
- File System: APFS (Case-sensitive, Encrypted)

```
$ xcodebuild -version
Xcode 10.1
Build version 10B61
$ c++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: d1b8eba4-dc65-4103-9351-c84a51b0c384
Build label: 0.21.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:57:09 2018 (1545224229)
Build timestamp: 1545224229
Build timestamp as int: 1545224229
```

## Other Observations

It looks like this is a wider problem than just assert. It appears that the CLion indexer isn't finding certain system C header files. I haven't done a full accounting of all C system headers, but some, like `assert.h` above, are _not_ found

- `time.h`
- `unistd.h` (Not stdlib, but present for my platform.)

whereas some others  _are_ found

- `stdio.h`
- `complex.h`

**Comment by dwtj** [comment]
FYI: The above-described problem is still observed when the environment variable `BAZEL_USE_CPP_ONLY_TOOLCHAIN` is set, as suggested here: https://github.com/bazelbuild/intellij/issues/109#issuecomment-434722597

**Comment by dwtj** [comment]
## A Workaround

I found a workaround which seems to have fixed the above-described problem for me.

When I originally reported this problem, I had a CLion custom property, `idea.case.sensitive.fs`, set to `true`. I've now set `idea.case.sensitive.fs=false`. Now, the above-described problem disappears when I pass the `BAZEL_USE_CPP_ONLY_TOOLCHAIN` environment variable to CLion (as suggested here https://github.com/bazelbuild/intellij/issues/109#issuecomment-434722597).

The following image illustrates the fix.

<img width="904" alt="workaround" src="https://user-images.githubusercontent.com/2457848/51070182-9e1da780-1602-11e9-97cf-e81f23607dc3.png">

`idea.case.sensitive.fs` is set in the `idea.properties` file, which can be opened in CLion via "Help" > "Edit Custom Properties...".


## Some Background

As stated above, my disk is case-sensitive APFS formatted. (Case-_insensitive_ filesystems are traditional for macOS.)

The first time that I booted up CLion on this system, I was greeted with a warning that looked like this:

<img width="370" alt="warning" src="https://user-images.githubusercontent.com/2457848/51070284-4b44ef80-1604-11e9-8dd1-69d07ebfdc64.png">

This links to [this JetBrains article](https://confluence.jetbrains.com/display/IDEADEV/Filesystem+Case-Sensitivity+Mismatch).

So, I dutifully set `idea.case.sensitive.fs=true`.

Now that I've set, `idea.case.sensitive.fs=false`, CLion+Bazel doesn't exhibit the above-described problem, but I always get this warning on startup. I can live with that. I'm not sure what other downsides to expect though. The above JetBrains article makes it sound potentially pretty bad. (It looks like `idea.case.sensitive.fs` has long history that I don't want to parse through.)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
