### ISSUE TITLE
Package name X does not correspond to the file path 'src.main.java.X' 

### ISSUE THREAD

**Issue by jimmyzzxhlh** [bazelbuild/intellij#4937]
### Description of the bug:

After importing a Bazel project into Intellij, the Java files cannot be compiled correctly. For example, I'm getting `Package name 'helloworld' does not correspond to the file path 'src.main.java.helloworld' `

![image](https://github.com/bazelbuild/intellij/assets/11505867/9ac70477-a6de-4fb9-833e-e2a61a8409aa)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- `git clone https://github.com/jimmyzzxhlh/bazel_hello_world`
- In Intellij, File -> Import Bazel Project -> Select the repository -> Use the `.bazelproject` file

Note that the Hello World program can be run correctly using the command `bazel run //src/main/java/helloworld:helloworld_app` on command line.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2021.3.3 (Ultimate Edition)

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2022.06.28.0.0-api-version-213

**Comment by Pavank1992** [comment]
Hi @jimmyzzxhlh,

Seems you are using very old Bazel plugin version, could you please update the latest version (2023.05.16.0.1-api-version-231)? I verified with latest version and can conform its working as expected. Please find screenshot for the same.
<img width="1208" alt="image" src="https://github.com/bazelbuild/intellij/assets/127178870/cfcd0683-6339-420e-8e32-d16cc853a7cc">

Please let us know if you are still facing the issue.
Thanks!
