### ISSUE TITLE
Class level debugging broken due to not having a getBuildInvoker implementation

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/intellij#4939]
### Description of the bug:

This [commit](https://github.com/bazelbuild/intellij/commit/fe2e8a63a9a80f9292dad69b063933d405a10c2b) breaks the class level debug runner from working, causing it to hit the `default` `getBuildInvoker` function defined here https://github.com/bazelbuild/intellij/commit/fe2e8a63a9a80f9292dad69b063933d405a10c2b#diff-1847a8f40d38664b366852ab7041de1a55a8211ee7ccf603e9897effdc691f7bR98-R101

The error message we now see:
<img width="387" alt="image" src="https://github.com/bazelbuild/intellij/assets/2177687/463af05f-dcc4-4d71-93b7-0ef909559c06">

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm able to reproduce this in both Java and Kotlin source files.

Steps:
1. Sync a module that contains a test class
2. Navigate to the test class and attempt invoke "Debug 'Bazel test ..."

The error popup will show up immediately.

### Which Intellij IDE are you using? Please provide the specific version.

Android Studio Flamingo | 2022.2.1 Patch 1

### What programming languages and tools are you using? Please provide specific versions.

Kotlin, Java

### What Bazel plugin version are you using?

7.x rolling releases

### Have you found anything relevant by searching the web?

Reverting this commit fixes the issue https://github.com/bazelbuild/intellij/commit/fe2e8a63a9a80f9292dad69b063933d405a10c2b

**Comment by rdesgroppes** [comment]
Java debugging also doesn't work for me since I upgraded the plugin to version **2023.05.16.0.1-api-version-231**.
Java debugging works again after reverting back to version **2023.05.02.0.1-api-version-231**.
Hope this helps tracking down...

**Comment by ben-pomelo** [comment]
Same!

**Comment by vzubkovs** [comment]
I am having the same issue with Scala.

**Comment by mai93** [comment]
yes, https://github.com/bazelbuild/intellij/commit/04141ef93a8a1a8f4452274845b53c59a093cceb should fix this.

**Comment by robherb-trumid** [comment]
Any ETA on a release? Much thanks to all who reported and fixed!

**Comment by Pavank1992** [comment]
We have release the fix in [Beta version](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/beta) [2023.05.30.0.2] and expected to launch in stable by 8th June. Please let us know if you see any broken in beta version.

**Comment by rdesgroppes** [comment]
I just gave [2023.05.30.0.2-api-version-231](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/beta/343536) which didn't exhibit the problem, thanks!

**Comment by Pavank1992** [comment]
Hi, Thanks for being patience.
Bazel plugin release in [stable](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions) channel. Please report if you face any broken challenges.
