### ISSUE TITLE
Source jars not correctly attached for some libraries

### ISSUE THREAD

**Issue by treuherz** [bazelbuild/intellij#496]
IntelliJ version: 2018.3.3
Bazel version: 0.21.0
Bazel plugin version: 2018.11.12

For 99% of java libraries in my project, everything works fine. Jumping to source takes me to the full original source file. For a handful of them, though, the sources don't seem to be correctly attached. They're listed as having "invalid sources root" in the Project Structure panel. I can manually attach the sources, but that only lasts till the next Bazel Sync. If I do attach them myself, Jump To Source and things work fine, but the files all have a banner saying the source doesn't match the bytecode. I assume this means that when Bazel is trying to wire up the sources, it doesn't see the source jars of these libraries as matches, and doesn't register them.

The libraries that this happens to are hamcrest-library, querydsl-core, and various Spring Data libraries. My best guess is that these libraries are more heavily annotation-processed, causing the mismatch, but I haven't investigated in detail.

Is there any way to override the "does not match" issue and force IntelliJ to recognise these sources?

The problem persists regardless of whether I have the "Show Add source to project notifications" or the "Local jar cache" settings enabled.

**Comment by treuherz** [comment]
Afraid it's not publicly available, will see if I can put together a minimal repro repo

**Comment by brownry1986** [comment]
My source jars are being properly attached, however I am seeing the banner at the top stating 

> Library source does not match the bytecode for class

I have recreated this in the following sample project: https://github.com/brownry1986/BazelIssues/tree/issue-496

Following is my environment info:
OS: macOS 10.14.2
Intellij version: 2018.3.2 (Ultimate Edition)
Bazel plugin version: v2019.01.02.0.2

I am also able to recreate this by downgrading to the prior version of the plugin.

After opening the project and performing a sync, I command-click on LoggerFactory.getLogger:
![image](https://user-images.githubusercontent.com/6344677/51402114-3a1f4580-1b12-11e9-80c9-80c2780b05fe.png)

The source code from the source jar is opened and I seem to have full navigation functionality, however the banner appears at the top of the page:
![image](https://user-images.githubusercontent.com/6344677/51402129-43101700-1b12-11e9-8f0c-544a7bd6cdd2.png)

Under Project Structure I can see that the Classes jar and Sources jar appears to have been attached properly:
![image](https://user-images.githubusercontent.com/6344677/51402271-a5691780-1b12-11e9-8b00-f916835863d1.png)

**Comment by brownry1986** [comment]
I partially retract my prior comment as it seems to be dependent upon some order of operations. I had this sample project imported into Intellij for a couple weeks and have done many things to it. However, if I do a fresh clone of the sample project and open in intellij, the sources are not attached and code navigation only partially works (go to declaration of an external class works, but find usages or scroll to source of that external class does not work) after syncing.

After performing a `bazel clean --expunge` on the command line and resyncing in intellij the sources are attached and code navigation works (albeit with the "source does not match bytecode" message).

After adding a new external dependency without a `bazel clean --expunge` I see that the new dependency is not properly attached and code navigation only partially works (as described above) on the new dependency.

I have recreated this multiple times in a sample project; steps to recreate will follow shortly.

**Comment by brownry1986** [comment]
I actually can't recreate the "source code does not match bytecode" issue with a fresh checkout. I consistently see it in the sample project that I originally imported, but when cloning the repo to a new location I cannot get past the issue where the source jar of the external dependency is not attached.

**Comment by naturalwarren** [comment]
I see the "source code does not match byte code" when consuming generated sources from `java_proto_library`. I have to manually link the source JAR produced by this rule and upon doing so receive the warning in a red banner.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
