### ISSUE TITLE
Bazel IntelliJ plugin showing incorrect color code for new files add in git repo

### ISSUE THREAD

**Issue by tarique-lw** [bazelbuild/intellij#4981]
### Description of the bug:

In my git cloned repo, I have added a new java class. Ideally the new class in the first go should be displayed in red color code in IntelliJ however, it is in grey color and unsynced.

Later, I partially synced my module and then it converted to red color code.

![image](https://github.com/bazelbuild/intellij/assets/92775528/60ca46e0-48b9-48c2-9719-ad9426dc20d9)
![image](https://github.com/bazelbuild/intellij/assets/92775528/0dc116ff-4a92-4bea-8fff-e3a83570ad34)
![image](https://github.com/bazelbuild/intellij/assets/92775528/6a48406a-6b07-4aa4-8104-ea683290c970)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add new file to git repo and check for color code status

### Which Intellij IDE are you using? Please provide the specific version.

JetBrains Client 2022.3.1

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

bundled 2023.05.30.0.1-api-version-223

**Comment by tarique-lw** [comment]
@mai93 any updates on this issue pls?

**Comment by Pavank1992** [comment]
Hi @tarique-lw, Issue is assigned to the maintainer and they will respond once they will triaged it (based on available bandwidth and priority). Thanks for being patience.

**Comment by mai93** [comment]
I think this is WAI, the file is grayed out and marked as unsynced to warn you that a sync is needed for this file, after it is synced it is highlighted to red to be added to the git repo I think.

**Comment by gspofford-lw** [comment]
@mai93 Question: why is this the intent? There are multiple independent attributes available to the file information. For example, when the file is being synced, the syncing status is in italics while the file name remains the same. For an unsynced file, there is the technical capability to indicate unsynced with a feature like italic words and git status with color together.
It just seems unnecessarily one-dimensional to treat being unsynced as the most important aspect of the file over all others.

**Comment by mai93** [comment]
I think this is more of an inconvenience. I can reopen it with P3 if you want to send a PR to fix it as we do not have the capacity to address it.
