### ISSUE TITLE
Debugging is disabled when "executable flags" field is set

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#4985]
### Description of the bug:

Debug icon becomes greyed-out after "executable flags" field is set

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In this repository, as in the movie below:

https://github.com/bazelbuild/intellij/assets/1066003/0c6c9e38-3e67-49f4-9530-d4b5f0a87fce

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ 2023.2

### What programming languages and tools are you using? Please provide specific versions.

Java

**Comment by mai93** [comment]
It is not reproducible with 2023.06.13.0.2-api-version-231. Can you try with this version? I tried on the example java project btw.

**Comment by viliam-durina** [comment]
I'm having exactly this issue in IntelliJ `2024.3.1.1`, bazel plugin version `2024.12.03.0.1-api-version-243`. As soon as I add any executable flag, debugging is disabled. If I remove the flags, debugging is not re-enabled, I have to delete the run configuration and re-create it. I'm trying to run a `java_binary`.

**Comment by viliam-durina** [comment]
I worked it around by using `args` parameter directly in the `BUILD.bazel` file, not in the IDE's run configuration.

**Comment by mai93** [comment]
@viliam-durina can you open a new issue with a small repro? I tried with the `java_binary` [here](https://github.com/bazelbuild/intellij/blob/master/examples/java/greetings_project/hi/BUILD#L2) and I could not reproduce the issue.

**Comment by viliam-durina** [comment]
@mai93 I no longer can reproduce it.. Of course, it happened in a large, many-module project, so making a reproducer will be hard. But it happened.

Maybe if you can point me to the code where enabled/disabled status of the debug option is determined, that will give some clue?

**Comment by mai93** [comment]
> Maybe if you can point me to the code where enabled/disabled status of the debug option is determined, that will give some clue?

I think this function is related https://github.com/bazelbuild/intellij/blob/master/java/src/com/google/idea/blaze/java/run/BlazeJavaDebuggerRunner.java#L46
