### ISSUE TITLE
Bazel intelliJ gives wrong "invalid package name" errors

### ISSUE THREAD

**Issue by tarique-lw** [bazelbuild/intellij#4986]
### Description of the bug:

While trying to create a package, IntelliJ give incorrect error message but can create a package
<img width="439" alt="Screenshot 2023-06-15 at 4 25 00 PM" src="https://github.com/bazelbuild/intellij/assets/92775528/987225e2-eb14-4cfc-b537-7a5f640bc220">

I tried to reproduce wrt to maven project but couldn't see any error there
<img width="365" alt="Screenshot 2023-06-15 at 4 27 17 PM" src="https://github.com/bazelbuild/intellij/assets/92775528/2bac9c85-1443-424f-a56e-4014111397ba">

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
having bazel plugin installed, create a package in IntelliJ and check for error

_No response_

### Which Intellij IDE are you using? Please provide the specific version.
JetBrains Client 2023.1.2

_No response_

### What programming languages and tools are you using? Please provide specific versions.
Java

_No response_

### What Bazel plugin version are you using?
bundled 2023.05.30.0.1-api-version-231

_No response_

### Have you found anything relevant by searching the web?
No

_No response_

**Comment by mai93** [comment]
I tried using this project: https://github.com/bazelbuild/intellij/tree/master/examples/java/greetings_project. After importing it, I clicked right click on `greeting_lib/src/com/example` then `New->Package`. Can you try with this project and give us more details if you are able to reproduce it there.
