### ISSUE TITLE
How to run a new test file programmatically

### ISSUE THREAD

**Issue by ankushj-sapientai** [bazelbuild/intellij#4991]
Hi, I am building an intellij plugin that depends on this `Bazel for IntelliJ` plugin. I am generating a test file from my plugin. I want to execute tests from this file once I generate this file. I saw this `BlazeCommandRunner` file has a runTest api, but it requires multiple inputs and I am totally confused on how to get those. 

I just have the virtual file where tests are written, I am able to run partial sync on this file, and after running the sync I would like to call runTest and get the results. Is there any way to do it?

**Comment by Pavank1992** [comment]
Hi @ankushj-sapientai, Could you please help us to reproduce the issue and behaviour you are expecting ?

**Comment by ankushj-sapientai** [comment]
Hi @Pavank1992 , its more of a feature request or a query whether the said feature already exists. 

What I need is a way to run test on a file, I have run partial sync on this file, but now I want to run bazel test query from my plugin. So just wanted to know if there already exists an api for this? Or how best to proceed with this?

**Comment by mai93** [comment]
I'm not sure if there are more but maybe classes under https://github.com/bazelbuild/intellij/tree/master/java/tests/integrationtests/com/google/idea/blaze/java/run can help.

**Comment by ankushj-sapientai** [comment]
I was able to do this with TestContextRunConfigProducer to produce a run config and then using default run executor of intellij.
