### ISSUE TITLE
Support “regular” import

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#5]
Support importing via “regular” import and choosing a folder and have intellij show you bazel as an option. Currently you have blaze as an option and once that is chosen a runtime exception is thrown saying: `Build system 'Blaze' not supported by this plugin`

**Comment by brendandouglas** [comment]
Should be fixed in the latest build.

**Comment by ittaiz** [comment]
I'm sorry for waking up this old issue but when you wrote "fixed" you meant that one can use the below option ("Import Bazel Project")?
![screen shot 2017-05-14 at 09 30 04](https://cloud.githubusercontent.com/assets/1378327/26031763/f4993dfe-3887-11e7-82d2-cf36f773eabb.png)

Because I was referring to the ability to "import project from external model" which currently for me only shows Eclipse, Gradle and Maven.
![screen shot 2017-05-14 at 09 31 04](https://cloud.githubusercontent.com/assets/1378327/26031766/24be43b2-3888-11e7-9f8e-6f2a7976f261.png)

**Comment by brendandouglas** [comment]
We've looked at hooking into IntelliJ's 'external system' API in the past, but it isn't suitable for our project model.

We could try to hook into this particular import action without fully implementing an 'external system' (it would be nice to integrate more cleanly into the existing actions), but it may not be practical.

For now, there's an easy workaround (the 'Import Bazel Project' item directly below File > New).
