### ISSUE TITLE
Android Studio 3.3

### ISSUE THREAD

**Issue by steeve** [bazelbuild/intellij#501]
Opening this issue to track support for Android Studio 3.3, which is now released.

**Comment by omo** [comment]
For someone who found this through Google and is lazy enough not to read the project's README,
The installable artifact is: `./bazel-bin/aswb/aswb_bazel.zip`

**Comment by steeve** [comment]
Here is an already built version:
[aswb_bazel.zip](https://github.com/bazelbuild/intellij/files/2782855/aswb_bazel.zip)

**Comment by plumpy** [comment]
There's an AS 3.3-compatible build in the plugin repository now. You should remove any custom-built versions, since they will inhibit updates from the plugin repository.

**Comment by steeve** [comment]
Thanks!

**Comment by senpo** [comment]
I have a fresh installed Android Studio 3.3.2 on Mac, but still have a hard time finding the Bazel plugin within the IDE (Settings > Plugins > Install > Browse Repositories, and search for ‘Bazel’).
