### ISSUE TITLE
.bazelproject targets cannot be external repository labels

### ISSUE THREAD

**Issue by brown** [bazelbuild/intellij#5012]
### Description of the bug:

In the targets section of a .bazelproject file external repository labels are not allowed.  For instance, the target

@ext//:external-binary

is not legal.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Below is a small set of files that reproduces the problem.  Create the files and create a new project using the file plugin/bazel/.bazelproject.  The result is an error.  Instead, it should be possible to specify external repository targets.

```
====================
plugin/ext/Ext.java
====================
package ext;

public class Ext {
    public static String world() {
        return "world";
    }

    public static void main(String[] args) {
        System.out.println("hello");
    }
}
====================
plugin/bazel/BUILD.ext
====================
java_binary(
    name = "external-binary",
    main_class = "ext.Ext",
    runtime_deps = [":external-library"],
)

java_library(
    name = "external-library",
    srcs = ["Ext.java"],
    visibility = ["//visibility:public"],
)
====================
plugin/bazel/WORKSPACE
====================
new_local_repository(
    name = "ext",
    build_file = "BUILD.ext",
    path = "../ext",
)
====================
plugin/bazel/.bazelproject
====================
directories:
  local
targets:
  @ext//:external-binary
  //local:local-binary
workspace_type: java
====================
plugin/bazel/local/Local.java
====================
package local;

import ext.Ext;

public class Local {
    public static void main(String[] args) {
        System.out.println("hello " + Ext.world());
    }
}
====================
plugin/bazel/local/BUILD
====================
java_binary(
    name = "local-binary",
    main_class = "local.Local",
    runtime_deps = [":local-library"],
)

java_library(
    name = "local-library",
    srcs = ["Local.java"],
    visibility = ["//visibility:public"],
    deps = ["@ext//:external-library"],
)

```

**Comment by sgowroji** [comment]
Hi @brown, Could you please provide more details like error logs, Environment used for the above query. Thanks!

**Comment by brown** [comment]
I'm not sure what you mean by environment.  I'm running Idea on Linux.  I can provide more info.  Just let me know what you need.

I see the following output in the Bazel problems window:

Updating VCS...
Command: bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no --
Running Bazel info...
Starting local Bazel server and connecting to it...
Computing VCS working set...
19:44:29	Initial directory update started
19:44:32	Initial directory update finished
19:44:33	Sync started
19:45:25	Sync finished with errors

and the following error:

Error:Internal error: java.lang.IllegalArgumentException: Explicit workspace names not supported: @ext//:external-binary

**Comment by mai93** [comment]
I'm not sure if this will work, but at least this error should not occur after https://github.com/bazelbuild/intellij/commit/9a3ef59b6c09cc03196b458240b4467b087715c4.

**Comment by brown** [comment]
Thanks very much.  I will try to build a recent version of the plugin and will report back whether or not using an external label causes any other problems.

**Comment by brown** [comment]
I just tried plugin version 2023.08.08.01 with Idea Community Edition 2023.1.2.  External labels no longer produce the error message I reported and Idea can build and run a target specified by an external label.  It looks like this issue has been fixed.

Thanks very much!
