### ISSUE TITLE
Java Sync will reset IntelliJ Platform Plugin SDK to Java SDK

### ISSUE THREAD

**Issue by xzhang-brex** [bazelbuild/intellij#5013]
### Description of the bug:

I'm currently developing with the Bazel IntelliJ plugin and facing an issue related to SDK settings. To have the IntelliJ editor recognize classes like `com.intellij.openapi.module.ModuleType`, I need to set the project's SDK to IntelliJ Platform Plugin SDK.

I have followed the steps in DEV_IDE_SETUP.md to ensure the Internal Java Platform is configured correctly to use the JDK I have locally (jdk17).

However, whenever I sync any Java source code, the project SDK gets reset to JDK17. As a result, the IntelliJ editor is unable to recognize classes like `com.intellij.openapi.module.ModuleType` again. Consequently, I need to reset the project's SDK each time after sync.

I tried to debug the Bazel plugin code and it seems that this issue arises from this line of code: `&& currentSdk.getSdkType() == JavaSdk.getInstance()`. The currentSdk, set to IntelliJ Platform Plugin SDK, has a type of IDEA SDK not Java SDK.

Nonetheless, this IDEA SDK does have a field getSdkAdditionalData, which in turn has a field myJavaSdk pointing to my local JDK (jdk17).

Please find attached a screenshot illustrating the situation:
![Screenshot 2023-06-21 at 9 49 24 PM](https://github.com/bazelbuild/intellij/assets/95645815/1d03c49c-94f2-484d-bd8a-98a54d95b3dc)
.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Set up your development environment following the DEV_IDE_SETUP.md instructions.
2. Make sure that the Internal Java Platform is set to your local JDK (JDK 17 in your case).
3. Open a project in IntelliJ that uses the Bazel IntelliJ Plugin.
4. Set the project's SDK to IntelliJ Platform Plugin SDK to allow the IntelliJ editor to recognize classes like `com.intellij.openapi.module.ModuleType`.
5. Sync any Java source code in the project.

Expected result:
The project SDK remains as IntelliJ Platform Plugin SDK.

Actual result:
The project SDK gets reset to JDK 17. As a result, IntelliJ is unable to recognize certain classes such as import com.intellij.openapi.module.ModuleType.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2023.1 (Ultimate Edition)

### What Bazel plugin version are you using?

Bazelisk version: development Build label: 6.2.1 Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar Build time: Fri Jun 2 17:00:10 2023 (1685725210) Build timestamp: 1685725210 Build timestamp as int: 1685725210

**Comment by mai93** [comment]
I was not able to reproduce this, I tried importing the plugin code using https://github.com/bazelbuild/intellij/blob/master/ijwb/ijwb.bazelproject. @tpasternak do you see this problem during your work on the plugin?
