### ISSUE TITLE
New beta released plugin(v2023.05.13) not giving output while running test for Intellij and syncing issue with CLion plugins

### ISSUE THREAD

**Issue by Pavank1992** [bazelbuild/intellij#5018]
### Description of the bug:

We release beta plugin (v2023.05.13) for Intellij and CLion. 

Please find the below observation while testing (observation is similar for oldest stable and latest stable). 
* JAVA> Hello World! is not printing while running HelloGreeter class (but in debug mode 'Hello World!' is getting printed)
* KOTLIN > Hello World! is not printing while running ProjectRunner class (but in debug mode Hello World! is getting printed)
* GOLANG > `AddToTwo(3) = 5' not printing while running the class but its printing when running on debug mode
* C++ > Sync finished with errors

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Perform manual testing as per give [doc](https://docs.google.com/document/d/1McGW3hBbaaDQl8_aTRjqyGay-9tKwrJE5TW79Hvywbc/edit#heading=h.mzncccjc2a31) for oldest stable or latest stable with v2023.05.13.

Testing screenshots attached here: https://docs.google.com/spreadsheets/d/1NJ5DgG8e7yQRmIbJBzA8g7zxmJSv87km9YaC9vL-2CY/edit#gid=0&range=57:60

### Which Intellij IDE are you using? Please provide the specific version.

2023.1 (Testing api-version-231 )	2022.3 (Testing api-version-223 )

### What programming languages and tools are you using? Please provide specific versions.

JAVA, KOTLIN, GOLANG

### What Bazel plugin version are you using?

2023.06.13.0.1-api-version-231 and 2023.06.13.0.1-api-version-223

**Comment by mai93** [comment]
Fixed with reversing https://github.com/bazelbuild/intellij/commit/0e033f574c2daf5166025506b81bafca135bef85
