### ISSUE TITLE
Tests not running from tests folder

### ISSUE THREAD

**Issue by tarique-lw** [bazelbuild/intellij#5026]
### Description of the bug:

I have a repo which has `/src/test/java` folder. I am trying to run the individual tests by mouse right click --> Run 'Bazel test //...' option. However this doesn't runs my test.

When I try to run the complete module using same way I can see the tests running.

If bazel cannot run individual tests why this option is needed for individual tests. This misleads to run thee bazel tests.

Snapshots - 

**Successful when trying to run complete module -** 
<img width="731" alt="Screenshot 2023-06-27 at 11 56 49 AM" src="https://github.com/bazelbuild/intellij/assets/92775528/e96e92e0-0d92-47d3-ad3e-34624daa082d">
<img width="732" alt="Screenshot 2023-06-27 at 11 52 32 AM" src="https://github.com/bazelbuild/intellij/assets/92775528/7cad0079-c8a4-4914-8330-b4e4742c9bf2">

**Tests Not running while running individual tests -** 
<img width="539" alt="Screenshot 2023-06-27 at 11 54 31 AM" src="https://github.com/bazelbuild/intellij/assets/92775528/aecaee65-2108-4d54-adfa-502ac0aeddfa">
<img width="1058" alt="Screenshot 2023-06-27 at 11 53 10 AM" src="https://github.com/bazelbuild/intellij/assets/92775528/5e90e8a5-63bf-46bb-b29c-52a1ccce7a51">

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run tests in complete module vs individual tests in tests folder.

### Which Intellij IDE are you using? Please provide the specific version.

JetBrains Client 2023.1.2

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

bundled 2023.05.30.0.1-api-version-231

**Comment by mai93** [comment]
@tarique-lw The difference between the 2 cases you described is not clear to me, we have a simple java project in https://github.com/bazelbuild/intellij/tree/master/examples/java/greetings_project, can you try importing it and let us know how to reproduce the problem using this project? (even if we need to restructure or update it)

**Comment by tarique-lw** [comment]
@mai93 Below are the things I tried - 
1. Executed tests by `Right Click --> Run Bazel test...` to `*/src/test` folder. The tests didn't run.
`Loading: 0 packages loaded
ERROR: no targets found beneath 'cfg-collection/cfg-types/src/test'
INFO: Elapsed time: 0.209s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded)
INFO: Build Event Protocol files produced successfully.`

2. Executed tests by `Right Click --> Run Bazel test...` to the module and was able to run the tests successfully.
`Executed 3 out of 3 tests: 3 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build completed successfully, 16 total actions
INFO: Build Event Protocol files produced successfully.` 

The project you shared is a very simple codebase and things to be working fine there. Ours is a very heavy codebase. Could you please try reproducing this at your end with a bug and heavy codebase and let me know.

**Comment by mai93** [comment]
I think it will be hard to find the underlying reason for this without you providing a project to reproduce it. But maybe if `*/src/test` in your project contains packages that do not have tests like a `util` package for example, this can be the reason for the error message `ERROR: no targets found beneath 'cfg-collection/cfg-types/src/test'`
