### ISSUE TITLE
Can't get any files to sync

### ISSUE THREAD

**Issue by olszowka-cargurus** [bazelbuild/intellij#5038]
### Description of the bug:

Whenever I try any full sync, incremental sync, or re-import of my project, the result is that no classes are in sync and, therefore, most IDE capabilities are inactive such as debugging or automatically managing imports.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Other users at my company have been unable to reproduce the bug.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3.3 (Ultimate Edition) Build #IU-223.8836.41, built on March 9, 2023 Licensed to Peter Olszowka You have a perpetual fallback license for this version. Subscription is active until June 12, 2024. Runtime version: 17.0.6+1-b653.34 x86_64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. macOS 13.4.1

### What programming languages and tools are you using? Please provide specific versions.

openjdk version "1.8.0_282" OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08) OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)

### What Bazel plugin version are you using?

com.google.idea.bazel.ijwb (2023.05.30.0.1-api-version-223)

### Have you found anything relevant by searching the web?

Nothing relevant found.

#### Output

INFO: Found 5888 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 78.349s, Critical Path: 0.52s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/eb37f2be-d6b1-4c9d-86e1-c56381b65897
FAILED: Build did NOT complete successfully
Build command finished. Retrieving BEP outputs...

#### Recipe I used to try to initial as much as possible

shut down IJ
bazel shutdown
rm -rf /private/tmp/cg-main-cache
rm -rf /private/var/tmp/_bazel_polszowka
rm -rf /Users/polszowka/Library/Caches/JetBrains/IntelliJIdea2022.3/blaze/projects
bazel clean
bazel shutdown
rm -rf .ijwb
start IJ 
import .bazelproject

**Comment by Pavank1992** [comment]
Hi @olszowka-cargurus, Could you please try to use [2023.05.30.0.2](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/beta/343536) and let us know if issue still persist. If yes, could you please share minimal steps to reproduce the issue?

**Comment by Pavank1992** [comment]
Hi @olszowka-cargurus, Intellij Stable version release.
If your IDE version is: 2022.3.3, please use [api-version-223](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/stable/356607)
IDE version is: 2023.1.2, please use [api-version-231](https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/stable/356609)

**Comment by olszowka-cargurus** [comment]
Hi,

I tried using version 2023.06.13.0.1-api-version-223 as you suggested, but
it is not compatible with bazel version 3.7.2 which I am using as I stated
in the original report. We have a project underway to upgrade bazel, but
expect it to take over a month.

  --PeterO

**Comment by Pavank1992** [comment]
**Please Note**: Bazel version older than Bazel 4 are no longer supported, Bazel users are recommended to upgrade to the latest LTS release or use rolling releases if you want to keep up with the latest changes at HEAD.

Latest Bazel release version is [6.2.1](https://github.com/bazelbuild/bazel/releases/tag/6.2.1)

Please refer the [support matrix](https://bazel.build/release#support-matrix) for bazel releases. All Bazel releases can be found on the [release page](https://github.com/bazelbuild/bazel/releases) on GitHub.
