### ISSUE TITLE
IntelliJ Plugin Aspect tests are failing with Bazel@HEAD on CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#5057]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3149#01892e1b-b74b-41a1-834a-6a032d8314fe

Platform : Ubuntu  Aspect tests 18.04, 20.04

Logs : 
```
//aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javabinary:JavaBinaryTest FAILED 
//aspect/testing/tests/src/com/google/idea/blaze/aspect/java/javatest:JavaTestTest FAILED
```
Steps : 
```
git clone -v https://github.com/bazelbuild/intellij.git
git reset 023a786e711d47d1ce873ed0ad53b4ff25089ad5 --hard
export USE_BAZEL_VERSION=fcfefc15b17dd70ab249e3d8d09d1ccc5da7d347
bazel test --define=ij_product=intellij-latest --test_output=errors --notrim_test_configuration -- //aspect/testing/...

```

Culprit :https://github.com/bazelbuild/bazel/commit/67c31eedb189d0b320bd4b2a011f25e9c57548c6

CC Green team @Wyverald

**Comment by mai93** [comment]
culprit is reverted in https://github.com/bazelbuild/bazel/commit/9819a4029c786a13a2223a7a1869bd219f855053

**Comment by sgowroji** [comment]
Hi @mai93, We are still seeing this error in few of the Aspect tests in both stable and beta channels. Can you please check. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3160#018947de-b33a-4a6e-85df-344ce5d61f7a
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3160#01894849-354a-4ce7-b08f-4cdcee17316a

**Comment by mai93** [comment]
I think it is now failing with a different reason. I think this is related to https://github.com/bazelbuild/bazel/commit/d0e29582a2e788e8acdaf53fe30ab7f7dc592df3. @kotlaja can you please confirm and let `rules_scala` know what needs to be changed?

**Comment by kotlaja** [comment]
I confirm that this error is because of my change since any rule which uses java_common must register java toolchain type. This is needed because of migration of Automatic Exec Groups, but I'll not get into details here (unless you prefer otherwise). 

In this case, we should just add `toolchains = ['@bazel_tools//tools/jdk:toolchain_type']` inside `_scala_import_impl` and the error will be fixed.

**Comment by sgowroji** [comment]
> Hi @mai93, We are still seeing this error in few of the Aspect tests in both stable and beta channels. Can you please check. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3160#018947de-b33a-4a6e-85df-344ce5d61f7a https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3160#01894849-354a-4ce7-b08f-4cdcee17316a

**Comment by kotlaja** [comment]
I've added https://github.com/bazelbuild/rules_scala/pull/1505 which fixes the previously mentioned error. Please have a look.

**Comment by mai93** [comment]
Thanks @kotlaja! I think we also need to update `scala_library_for_plugin_bootstrapping` in rules_scala. Error: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3173#0189672c-e7dc-4de0-91a3-00a2999610c3

**Comment by mai93** [comment]
Created https://github.com/bazelbuild/rules_scala/issues/1507 to request a fix in rules_scala
