### ISSUE TITLE
CLion Plugin resolves headers in other packages to symlinked header

### ISSUE THREAD

**Issue by brownry1986** [bazelbuild/intellij#509]
When attempting to jump to the declaration of a header in CLion, I am instead taken to the symlinked header under bazel's virtual includes. As this file is not a part of the project, I get a warning that code insight features might not work properly.

![screen shot 2019-02-13 at 12 27 20 pm](https://user-images.githubusercontent.com/6344677/52734674-6f8d4680-2f8b-11e9-811e-1a6d2ac538fc.png)

![screen shot 2019-02-13 at 12 27 34 pm](https://user-images.githubusercontent.com/6344677/52734680-71efa080-2f8b-11e9-898f-f2758f839c9f.png)

If you attempt to edit the file you have to confirm that you want to edit a file that is outside of your project, and if you have the actual file open in a different tab the edits will not be shown in the other tab until after a resync.

I have recreated this in a sample project available here: https://github.com/brownry1986/ClionBazelHeaderSymlinks

This sample project is based off of one of the bazel tutorials but has been restructured to more closely match the structure of our project.

Is it possible for the bazel plugin to derive the realpath of the header from the symlink and pass the real path to CLion instead of the symlink?

Below is my version information. I am working on a mac, but we have also been able to recreate this issue with the same sample project on the same CLion/bazel/plugin versions on FC29.

Operating System: macOS 10.14.2
Bazel Version: 0.22.0-homebrew
CLion Version: 2018.3.4 Build #CL-183.5429.37
Bazel Plugin Version: v2019.01.28.0.2

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
