### ISSUE TITLE
The `{` character is incorrectly handled in command line arguments when debugging java targets

### ISSUE THREAD

**Issue by theospears** [bazelbuild/intellij#512]
IntelliJ Version: 2018.3
Bazel Version: 0.19.2
Bazel Plugin Version: v2019.01.28.0.2

Reproduction steps:
1. Create a run configuration for a java target that prints its arguments
2. Include e.g. `{hello,hi}world` as a command line argument
3. Run this run configuration. Observe `{hello,hi}world` is printed
4. Debug this run configuration.

Expected Behavior:
`{hello,hi}world`

Observed Behavior:
`helloworld hiworld` is printed.

Discussion:
We believe this is due to the two different ways bazel is invoked based on whether or not `canHotSwap` is enabled. We believe the path that goes through `getBashCommandsToRunScript` is wrong because it does not escape `{` characters before passing the command line arguments to bash.

See: https://github.com/bazelbuild/intellij/blob/b55f77a6d13fa4c03e7be21a1ea599f13551d72d/java/src/com/google/idea/blaze/java/run/BlazeJavaRunProfileState.java#L146

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
