### ISSUE TITLE
Open multiple Bazel projects in one IntelliJ environment/window

### ISSUE THREAD

**Issue by haikalpribadi** [bazelbuild/intellij#513]
Hi everyone, is it possible to open multiple Bazel projects in one IntelliJ environment/window? We work with multiple repositories at the same time and it's difficult (especially when it comes to refactoring) when the whole codebase is not in one IDE. We used to do this when we were still with Maven, but we haven't figured out a way to do it with Bazel+IntelliJ yet. Thank you!

**Comment by brendandouglas** [comment]
This isn't supported with the plugin, it's currently only one bazel workspace per IntelliJ project.

**Comment by haikalpribadi** [comment]
Is there any plan on enabling multiple bazel project in intellij, @brendandouglas?

**Comment by brendandouglas** [comment]
There's no plan to do this sorry, and I don't think it would be feasible without a major rewrite of the plugin.

Unless you can think of a way to construct a single bazel workspace containing each of your individual workspaces.
