### ISSUE TITLE
Only Linux build of buildifier is bundled

### ISSUE THREAD

**Issue by ignasl** [bazelbuild/intellij#514]
The plugin is usable in multiple platforms where IntelliJ and Bazel can be installed, but bundled [`bazel-buildifier`](https://github.com/bazelbuild/intellij/blob/master/base/resources/binaries/bazel-buildifier) is X86-64 Linux build, the excerpt of `readelf -h bazel-buildifier` output:
```
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
```
There are basically two ways of fixing this problem:

- Bundle `buildifier` for each major platform and then select the right one at runtime
- Provide a way to use a pre-installed version on the host machine (see https://github.com/bazelbuild/intellij/issues/477)

**Comment by ignasl** [comment]
@or-shachar

**Comment by kasedy** [comment]
"Automatically format BUILD\Starlark files on file save" feature doesn't work on Mac

**Comment by dontstabai** [comment]
Is there any workaround for this? It would be lovely to get this to work on my Mac.

**Comment by jesseschalken** [comment]
I think this was fixed by https://github.com/bazelbuild/intellij/commit/00da6c357e93ddafecb11858c7691c2ccebda8b4 (at least it says so in the commit message)

**Comment by dontstabai** [comment]
Awesome! 🎉  When will we be able to download the updated plugin to get the fix?

**Comment by AlexeyGy** [comment]
@dontstabai The change should already be in the newest version. There is no more bundled buildifier, see the changelog of https://plugins.jetbrains.com/plugin/8609-bazel.

**Comment by dontstabai** [comment]
Whoops, my IDE was out of date so the plugin didn't update. Seeing it now and life is good!
