### ISSUE TITLE
In-memory mode for syncing files

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#515]
I'm looking to start a discussion on adding a sort of lightweight/in-memory mode for working with code files being added/removed.

We've been experimenting with an interim solution of calling a sync automatically, directly on the target that was changed (without going through all the `BlazeSyncTask` flow). This improved the experience somewhat, but it may still take a few seconds between adding the file, and it being available for use.

We want to introduce a mode of updating the underlying `targetMap` directly with a newly added files, skipping calling bazel directly. Have you ever considered doing this, and what were your concerns/issues?

Alternatively, would you consider accepting a (feature-toggled) "in-memory" mode PR?

**Comment by brendandouglas** [comment]
This is something I've been looking into for a while, and we do have some initial support for automatic syncing on changes to BUILD files or protos (see AutoSyncProvider).

We'll definitely be expanding support for auto-syncing this year, though the primary use case is delegating bazel builds to an external service (in our internal case, remote worker machines).

As part of that, I'll be rewriting a large part of the sync machinery, to support multiple concurrent syncs and more incremental updates to the project state.

I don't think it's feasible to get good general language support without bazel builds though. Updating only the target map will provide run/debug support in a lot of cases, but not much else without the additional information provided by bazel.

I'm definitely interested in discussing this -- how are you planning on getting the target information? Given that this is core sync code, affects all languages, and we have our own rewrite planned, I'd prefer not to accept a PR for this though, at least not without first nailing down the implementation details.

**Comment by hmemcpy** [comment]
Excellent, thanks for your response on this! We'll do some brainstorming here as well. Will keep posted!

**Comment by hmemcpy** [comment]
We'd like to experiment with implementing an `AutoSyncProvider` - would it be possible to make it public, so we can do this outside the plugin?

**Comment by brendandouglas** [comment]
We're in the process of completely rewriting auto-sync support, and AutoSyncProvider/AutoSyncHandler will probably disappear as part of that.

What kind of usage where you thinking of?

**Comment by ittaiz** [comment]
@brendandouglas Any chance for an update on where you are at with respect to the rewrite?

**Comment by brendandouglas** [comment]
I've been working on other things for quite a while now, but plan to get back to auto sync handling soon (and have some in-progress work).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
