### ISSUE TITLE
Intellij builds are broken with Bazel latest release 6.3.0

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#5150]
Android Studio Plugin Google: https://buildkite.com/bazel/android-studio-plugin-google/builds/4811#01898f88-8e27-46b0-8f8e-b9e7fcb2aba4

CLion Plugin Google: https://buildkite.com/bazel/clion-plugin-google/builds/4807#01898f88-bafc-49a7-99f9-58b49ae7b40e

IntelliJ Plugin Google : https://buildkite.com/bazel/intellij-plugin-google/builds/4794#01898f8c-45fc-4774-8701-f74449b4ae4d

IntelliJ UE Plugin Google : https://buildkite.com/bazel/intellij-ue-plugin-google/builds/4803#01898f8c-b0ee-4893-9267-5f15c4d835c7

IntelliJ Plugin Aspect Google:https://buildkite.com/bazel/intellij-plugin-aspect-google/builds/4811#01898f8c-ae31-4aab-8c66-d654731ea787

Logs : 
```
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java:217: warning: as of release 10, 'var' is a restricted type name and cannot be used for type declarations or as the element type of an array
      var unused = result.sourceOwners();
          ^
querysync/java/com/google/idea/blaze/qsync/project/BuildGraphData.java:217: error: cannot find symbol
      var unused = result.sourceOwners();
      ^
  symbol:   class var
  location: class Builder
```
Steps:
```
git clone https://github.com/bazelbuild/intellij.git
export USE_BAZEL_VERSION=6.3.0
# reproducing for  Android-Studio-internal-stable
bazel build --define=ij_product=android-studio-latest //aswb/...
```

CC GreenTeam @fweikert

**Comment by mai93** [comment]
fixed with https://github.com/bazelbuild/intellij/commit/8c48e5bebfba46131927434637b552de58d7d8c3
