### ISSUE TITLE
Unable to run go file via editor

### ISSUE THREAD

**Issue by mattnathan** [bazelbuild/intellij#516]
In a project that contains some go files, I'm used to being able to click the little green run icon in the editor gutter. I'm in the process of migrating to Bazel but this feature doesn't appear to be available anymore:

![image](https://user-images.githubusercontent.com/708746/53258048-8f2b1a00-36c3-11e9-842f-66bbed07f97e.png)

Is there something I'm missing in my setup that's causing this not to work or is this a real bug?

### Setup
- Some java, some go packages separated by a top level language folder.
- BUILD.bazel files generated using gazelle
- Using go.mod

### Versions
Plugin: v2019.01.28.0.2
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by chaoren** [comment]
Can you share your `.bazelproject` file? Make sure `go` is enabled under `addition_languages`.

**Comment by mattnathan** [comment]
It's a default `.bazelproject` with `go` in `additional_languages`, exactly as you say

**Comment by mattnathan** [comment]
I haven't looked into this in detail but it appears that the issue is because the plugin associates the go file with the `go_library` rule, the check in [GoBinaryContextProvider.java#L83](https://github.com/bazelbuild/intellij/blob/master/golang/src/com/google/idea/blaze/golang/run/producers/GoBinaryContextProvider.java#L83) only exposes the 'run this file' functionality if the file is directly associated with a `go_binary` rule.

**Comment by mattnathan** [comment]
I should also say that changing our `go_library` rule to `go_binary` (and removing duplicates) reinstates this functionality. However, we are generating these rules via [gazelle](https://github.com/bazelbuild/bazel-gazelle) so will see if there's a way to do that instead.

Ideally the plugin would be expanded to provide the run target of 'closely related go_binary rules' if the actual target is a go_library

**Comment by mattnathan** [comment]
I wrote a quick patch (though there's probably a better way to do this) that searches a little father for a binary rule to run a file

```patch
Index: golang/src/com/google/idea/blaze/golang/run/producers/GoBinaryContextProvider.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- golang/src/com/google/idea/blaze/golang/run/producers/GoBinaryContextProvider.java	(revision e76fdadb0bdabbe2be913cba03d9014eb2366374)
+++ golang/src/com/google/idea/blaze/golang/run/producers/GoBinaryContextProvider.java	(date 1551456701434)
@@ -17,21 +17,26 @@
 
 import com.goide.execution.GoRunUtil;
 import com.goide.psi.GoFile;
+import com.google.common.collect.ImmutableMultimap;
 import com.google.idea.blaze.base.dependencies.TargetInfo;
 import com.google.idea.blaze.base.ideinfo.TargetIdeInfo;
+import com.google.idea.blaze.base.ideinfo.TargetKey;
+import com.google.idea.blaze.base.ideinfo.TargetMap;
 import com.google.idea.blaze.base.model.BlazeProjectData;
 import com.google.idea.blaze.base.model.primitives.LanguageClass;
 import com.google.idea.blaze.base.model.primitives.RuleType;
 import com.google.idea.blaze.base.run.BlazeCommandRunConfiguration;
 import com.google.idea.blaze.base.run.producers.BinaryContextProvider;
 import com.google.idea.blaze.base.sync.data.BlazeProjectDataManager;
+import com.google.idea.blaze.base.targetmaps.ReverseDependencyMap;
 import com.google.idea.blaze.base.targetmaps.SourceToTargetMap;
 import com.intellij.execution.actions.ConfigurationContext;
 import com.intellij.openapi.vfs.VirtualFile;
 import com.intellij.psi.PsiElement;
 import com.intellij.psi.PsiFile;
 import java.io.File;
-import java.util.Objects;
+import java.util.Deque;
+import java.util.LinkedList;
 import javax.annotation.Nullable;
 
 /** Go-specific handler for {@link BlazeCommandRunConfiguration}s. */
@@ -76,13 +81,32 @@
       return null;
     }
     File file = new File(vf.getPath());
-    return SourceToTargetMap.getInstance(psiFile.getProject()).getRulesForSourceFile(file).stream()
-        .map(projectData.getTargetMap()::get)
-        .filter(Objects::nonNull)
-        .filter(t -> t.getKind().getLanguageClass().equals(LanguageClass.GO))
-        .filter(t -> t.getKind().getRuleType().equals(RuleType.BINARY))
-        .map(TargetIdeInfo::toTargetInfo)
-        .findFirst()
-        .orElse(null);
+
+    // attempt to find a go_binary rule that can run this file
+    // this ensures we support splitting go_library from go_binary rules (as gazelle does)
+    ImmutableMultimap<TargetKey, TargetKey> reverseDeps = ReverseDependencyMap.get(psiFile.getProject());
+    SourceToTargetMap sourceToTarget = SourceToTargetMap.getInstance(psiFile.getProject());
+    TargetMap targetMap = projectData.getTargetMap();
+
+    // while searching dependents we try to stay as close to the source files rule as possible
+    Deque<TargetKey> targetsToCheck = new LinkedList<>(sourceToTarget.getRulesForSourceFile(file));
+
+    while (!targetsToCheck.isEmpty()) {
+      TargetKey currentKey = targetsToCheck.removeFirst();
+      TargetIdeInfo t = targetMap.get(currentKey);
+      if (t != null) {
+        if (t.getKind().getLanguageClass().equals(LanguageClass.GO)) {
+          if (t.getKind().getRuleType().equals(RuleType.BINARY)) {
+            return t.toTargetInfo();
+          }
+
+          // the target isn't a BINARY target, but it might be depended on by something that is
+          // add to the end of the queue so we're searching in breadth first order
+          reverseDeps.get(currentKey).forEach(targetsToCheck::addLast);
+        }
+      }
+
+    }
+    return null;
   }
 }
```

**Comment by chaoren** [comment]
Just to make sure, your go_library contains the main() method, right? And it has package name of "main"?
The same as files in the go_binary? Do their import paths match as well?

**Comment by mattnathan** [comment]
Correct, this is how gazelle generates the rules. One go_library per directory with .go files in, if the files are in package main and have a main method then generate a go_binary rule that `embed`s the go_library. The go_binary doesn't reference the files directly.

**Comment by mattnathan** [comment]
Here is an example application:

```go
package main

import "fmt"

func main() {
	fmt.Print("Hello, World!")
}
```

And generated build file:

```bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["hello_world.go"],
    importpath = "example.com/go/playground/hello",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "hello",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
```

**Comment by plombardi89** [comment]
I've also hit this problem. No run or debug options. Clicking the little green run icon shows `Nothing here`. Go is uncommented in the `.bazelproject`

**Comment by asv** [comment]
Is there any progress on this issue? Very annoying workaround with copying `go_library` contents to go_binary "by hands"...
