### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/intellij#517]
Based on our CI, Bazel cannot build this project when the flag `--incompatible_no_target_output_group` is set: https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags/builds/113#4fb46066-def8-449c-953e-36d209ee6b4d

In order to detect other issues in advance, you can try Bazelisk:
[`bazelisk --migrate test //...`](https://github.com/philwo/bazelisk)

**Comment by brendandouglas** [comment]
We currently rely on accessing the 'compilation_outputs' output group -- this information is necessary for IDE support.

Until that information is available in some other way, for each language we currently need it for (just Go and C++), we can't migrate off it without impacting a lot of internal users.

**Comment by laurentlb** [comment]
cc @c-parsons

**Comment by brendandouglas** [comment]
I misinterpreted the explanation in the 'Fixing Starlark Rule Outputs' doc, all the information we need is already available via OutputGroupInfoApi.

Fixed upstream, just need to fix the other CI breakages here before merging.

**Comment by laurentlb** [comment]
I don't think this issue should be closed.

Based on our latest CI run (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/28#0ce981a8-efbe-481c-8105-72ee6098a934), migration is needed for the following flags:
  * --incompatible_depset_is_not_iterable
  * --incompatible_depset_union
  * --incompatible_disable_deprecated_attr_params
  * --incompatible_disable_legacy_cc_provider
  * --incompatible_disallow_legacy_py_provider
  * --incompatible_merge_genfiles_directory
  * --incompatible_new_actions_api
  * --incompatible_use_toolchain_providers_in_java_common

In particular, I plan to flip `--incompatible_merge_genfiles_directory` very soon.
