### ISSUE TITLE
No auto-complete for types in third party jars that have no usages (yet)

### ISSUE THREAD

**Issue by mattnathan** [bazelbuild/intellij#518]
I'm fairly new to Bazel but something I'm having issues with is a lack of auto-complete for types in jars that are defined (via bazel-deps), dependend on (via `java_library(deps=[...])`), but aren't currently used anywhere in my projects java files. For example when adding a brand new jar to the project.

The problem I'm seeing is that until I manually write an `import some.Type;` in one of my java files and sync the project, IntelliJ doesn't seem to be aware that the library dependency exists at all:

- Doesn't show up in _External Libraries_
- No auto-complete of the package during writing an `import` statement
- No auto-complete of types in the library
- No find class/file/etc for symbols that exist in that jar

Manually adding the `import` statement and using the library types without auto-complete compiles/runs fine which indicates to me that there's no issue with my usage of bazel.

**Versions**
Plugin: v2019.01.28.0.2

Build label: 0.22.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jan 28 12:59:27 2019 (1548680367)
Build timestamp: 1548680367
Build timestamp as int: 1548680367

IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by cgruber** [comment]
More broadly, auto-completing any external/ workspaces would be supremely helpful.  Maybe I am doing something wrong, but I don't get auto-complete for even external workspace targets/packages even when there are usages.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
