### ISSUE TITLE
Macros with suffix test_suite are not runnable as test suites

### ISSUE THREAD

**Issue by thirtyseven** [bazelbuild/intellij#5183]
### Description of the bug:

Custom test_suite macros like contrib_rules_jvm's [java_test_suite](https://github.com/bazel-contrib/rules_jvm#java_test_suite) should be runnable from BUILD files like standard test_suite rules. However, it appears the heuristics for detecting custom test_suites does not currently pick them up:
https://github.com/bazelbuild/intellij/blob/935db0a69a66a67a9845e3f11c92d72676e4399e/base/src/com/google/idea/blaze/base/model/primitives/Kind.java#L204

Instead of checking if a rule ends in `test_suite`, it checks if it exactly matches "test_suite" or ends in "test_suites".

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Write a BUILD file in IntelliJ with these contents:
```starlark
load("@contrib_rules_jvm//java:defs.bzl", "java_test_suite")

java_test_suite(
    name = "tests",
    srcs = glob(["*Test.java"]),
)
```

A green arrow should appear in the margin, but doesn't.

### Which Intellij IDE are you using? Please provide the specific version.

Build #IU-232.8660.185, built on July 25, 2023

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2023.07.21.0.1-api-version-232

**Comment by mai93** [comment]
Merged https://github.com/bazelbuild/intellij/pull/5184
