### ISSUE TITLE
Incorrect assumption around jdeps parsing in ExecutionPathHelper

### ISSUE THREAD

**Issue by mattnathan** [bazelbuild/intellij#521]
In [ExecutionPathHelper#39](https://github.com/bazelbuild/intellij/blob/master/java/src/com/google/idea/blaze/java/sync/importer/ExecutionPathHelper.java#L39) there is a comment that says `// Bazel should always use '/' as the file separator char for these paths.` This isn't true.

![image](https://user-images.githubusercontent.com/708746/53580835-5c29d000-3b74-11e9-9459-df3d8808a57a.png)

The attached image shows what the value looks like under windows.

This results in sources for generated classes not being attached sometimes, specifically if `com.google.idea.blaze.java.sync.importer.BlazeJavaWorkspaceImporter#guessSrcJarLocation` can't guess correctly, which is the case for java_proto_library output as that puts the source jar into the `genfiles/` dir instead of just appending a `-src.jar` suffix.

It's worth noting that the aspect generated `*-intellij-info` files correctly identify the source location in the above case.

I'm sure there's a better place to fix this but replacing `\` with `/` in the above linked code line attaches proto library sources just fine.
```java
executionRootRelativePath = executionRootRelativePath.replace('\\', '/');
```

I understand that Windows isn't officially supported (#113)

**Comment by mattnathan** [comment]
Can I suggest the following patch:

```patch
Index: java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java	(revision e76fdadb0bdabbe2be913cba03d9014eb2366374)
+++ java/src/com/google/idea/blaze/java/sync/importer/BlazeJavaWorkspaceImporter.java	(date 1551374276445)
@@ -179,7 +179,10 @@
       if (sourceFilter.jdepsPathsForExcludedJars.contains(artifact.getRelativePath())) {
         continue;
       }
-      BlazeJarLibrary library = jdepsPathToLibrary.get(artifact.getRelativePath());
+      BlazeJarLibrary library = jdepsPathToLibrary.get(jdepsPath);
+      if (library == null) {
+        library = jdepsPathToLibrary.get(artifact.getRelativePath());
+      }
       if (library == null) {
         // It's in the target's jdeps, but our aspect never attached to the target building it.
         // Perhaps it's an implicit dependency, or not referenced in an attribute we propagate
@@ -213,10 +216,12 @@
     ArtifactLocation interfaceJar = libraryArtifact.getInterfaceJar();
     if (interfaceJar != null) {
       jdepsPathToLibrary.put(interfaceJar.getRelativePath(), library);
+      jdepsPathToLibrary.put(interfaceJar.getExecutionRootRelativePath(), library);
     }
     ArtifactLocation classJar = libraryArtifact.getClassJar();
     if (classJar != null) {
       jdepsPathToLibrary.put(classJar.getRelativePath(), library);
+      jdepsPathToLibrary.put(classJar.getExecutionRootRelativePath(), library);
     }
   }
```

When I test locally with this patch applied it fixes the above _generated proto sources not attached_ issue, but also fixes all third_party jar sources not being attached too. I don't know if this'll fix the other bugs relating to source jars (#500 for example).

**Comment by zhzhxtrrk** [comment]
Any update on this? This is really very helpful to make this plugin much more usable on Windows.
