### ISSUE TITLE
Clarify what "additional languages" means when importing projects

### ISSUE THREAD

**Issue by nnmm** [bazelbuild/intellij#5238]
### Description of the feature request:

The `.bazelproject` that is generated when choosing "Create from scratch" in the import wizard currently contains 

```
additional_languages:
  # Uncomment any additional languages you want supported
  # dart
  # javascript
  # python
  # typescript
```

It is unclear what the _default_ languages are (C++? Java?), and if this list is the complete list of possible additional languages, or if not, where to find the correct spelling of any other additional languages.

It would also be good to explain further what this setting does. E.g. will a project fail to import if it contains code in a non-supported language, or will certain features (which ones?) be simply unavailable? There is currently no mention on https://ij.bazel.build/docs/import-project.html either.

### What underlying problem are you trying to solve with this feature?

Avoid user confusion.

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

Ubuntu 20.04, CLion 2023.2

### Have you found anything relevant by searching the web?

No.

**Comment by mai93** [comment]
There is an explanation for all project view sections in https://ij.bazel.build/docs/project-views.html including `additional_languages`: https://ij.bazel.build/docs/project-views.html#additional_languages. We can add more details to it as you described.
