### ISSUE TITLE
CLion + Ubuntu + GDB Debugging Regressions in Plugin v2019.02.13.0.3

### ISSUE THREAD

**Issue by dwtj** [bazelbuild/intellij#525]
I can no longer debug a simple bazel project in CLion after upgrading the latest version of the bazel plugin, v2019.02.13.0.3.

I am observing two new problems in this version.

1. If I attempt to debug with the debugger set to "Bundled GDB", I get a red error popup saying "Debugger executable not specified".
2. If I attempt to debug with the debugger with the system GDB, `/usr/bin/gdb`, I get a "Permission Denied" error, specifically,

```
INFO: Running command line: /bin/bash -c ''\''/home/dwtj/.CLion2018.3/config/plugins/clwb/gdb/gdbserver'\'' gdbserver --once localhost:5006 --target bazel-bin/hello_world '
/bin/bash: /home/dwtj/.CLion2018.3/config/plugins/clwb/gdb/gdbserver: Permission denied

Process finished with exit code 126
```

Problem 2 appears to be because of incorrect permissions on this `gdbserver` binary; it didn't initially have execute permissions.

(Note: I don't currently have Clang/LLDB installed, so I'm not sure what happens when a clang build and "Bundled LLDB" is used.)

**Workaround:** I switched to using `/usr/bin/gdb` and ran `chmod u+x gdbserver` on the offending file. Debugging now seems to work.

**Comment by nickolasrossi** [comment]
I have the same problem. Plugins beyond version 2019.01.14.0.5 give me the "Debugger not specified" error... but unlike the above post, the system gdb doesn't work for me either. I have held my plugin at 2019.01.14.0.5 to keep working.

I'm on ubuntu 16.04, clion 2018.3.4, bazel 0.19.2.

**Comment by dwtj** [comment]
FYI, I am still seeing this behavior on the latest versions.

- Ubuntu v19.04
- CLion v2019.1.3
- Bazel v0.25.2
- Plugin v2019.05.01.0.3

Fortunately, the workaround that I said above still works for me.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
