### ISSUE TITLE
Cannot run tests in CLion with latest version of bazel

### ISSUE THREAD

**Issue by dwtj** [bazelbuild/intellij#526]
The latest version of Bazel, v0.23.1, no longer appears to support the `--testing_strategy=local` option. However, this option appears to be appended to the test invocations launched in CLion v2018.3.4 when running the `bazel` plugin v2019.02.13.0.3. This results in errors like the following:

```
Building debug binary
Command: bazel build --tool_tag=ijwb:CLion --run_under='/home/dwtj/.CLion2018.3/config/plugins/clwb/gdb/gdbserver' gdbserver --once localhost:5006 --target --compilation_mode=dbg --strip=never --copt=-g --dynamic_mode=off --fission=yes --test_timeout=3600 --nocache_test_results --test_strategy=local --test_sharding_strategy=disabled --curses=no --color=yes --experimental_ui=no --progress_in_terminal_title=no --build_event_binary_file=/tmp/intellij-bep-bb7b2e6a-c060-4a93-8b40-238dec319845 --nobuild_event_binary_file_path_conversion -- //phasicj/tracelogger/testing/integration:hello_jdk11_hotspot
...
ERROR: 'local' is an invalid value for test strategy. Valid values are: exclusive, standalone.
```

**Comment by dwtj** [comment]
It appears that `local` is not a valid testing strategy in any of these Bazel versions:

- v0.21.0
- v0.22.0
- v0.23.0
- v0.23.1

**Comment by dwtj** [comment]
**Workaround:** I reverted to plugin v2019.01.14.0.5 to temporarily side-step the issue. (v2019.02.28.0.2 uses `--testing_strategy=local` too.)

**Comment by Elentary** [comment]
+1

**Comment by mirko-ars** [comment]
+1

**Comment by brendandouglas** [comment]
For the latest commenters, this has been fixed for the last 3 CLion plugin releases (https://plugins.jetbrains.com/plugin/9554-bazel/versions).

You probably need to upgrade to CLion 2018.3.4 (and then upgrade the bazel plugin) if you're still seeing this.

**Comment by Elentary** [comment]
No, I can reproduce it in 2018.3.4
