### ISSUE TITLE
 Spring Framework Gutter Not Shown For Bazel Project

### ISSUE THREAD

**Issue by AlexBurdu** [bazelbuild/intellij#5296]
### Description of the bug:

Spring framework gutter icon is no longer showing up in latter versions of the Bazel plugin. ([Intellij supports gutter icons for spring](https://blog.jetbrains.com/idea/2018/09/spring-kotlin-gutters-and-navigation/)). This used to work fine in the past; unsure when and why it stopped working. Neither the HTTP nor the Spring beans/services gutters are shown.

![image](https://github.com/bazelbuild/intellij/assets/1262636/91236bb8-ff25-48c0-83d7-a39b8be34e62)
![image](https://github.com/bazelbuild/intellij/assets/1262636/c70d75f1-4062-4170-890f-39a03e253b14)
![image](https://github.com/bazelbuild/intellij/assets/1262636/bca64736-0b0c-4ab3-9108-0eb20e044954)
![image](https://github.com/bazelbuild/intellij/assets/1262636/8c8d5c4b-bbec-46af-be3d-425097483a36)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a simple Bazel Spring (Boot) framework project.

### Which Intellij IDE are you using? Please provide the specific version.

IU-232.9559.62, JRE 17.0.8+7-b1000.8x64 JetBrains s.r.o., OS Linux(amd64) v6.2.0-26-generic, screens 3840.0x2160.0

### What programming languages and tools are you using? Please provide specific versions.

Kotlin (compiler 1.9, language level 1.8), openjdk 17.0.6 2023-01-17 (Temurin-17.0.6+10)

### What Bazel plugin version are you using?

2023.08.01.0.1-api-version-232

### Have you found anything relevant by searching the web?

Reported at https://youtrack.jetbrains.com/issue/IDEA-331107/Spring-Boot-Gutter-Not-Shown-For-Bazel-Project and support was able to repro the issue and confirm that it doesn't happen for a non-Bazel project (Gutter icons in a simple Spring Boot Java Maven project generated via Spring initializr works fine.)

**Comment by AlexBurdu** [comment]
Is there any timeline to have this issue addressed? It's quite inconvenient to have it missing when developing using Spring

**Comment by mai93** [comment]
I'm afraid we do not have the capacity to look at this but we can accept PRs that fix it.

**Comment by AlexBurdu** [comment]
Is there any documentation on how this plugin integrates with that that could be used for reference?

**Comment by blorente** [comment]
Hello, @AlexBurdu !
I'm sorry for the long delay. I finally got a few cycles to look into this, and (perhaps unfortunately) I can see the gutter icons.

I created this small repo: https://github.com/blorente/bazel-springboot-example
And, with the following versions of the plugin:
- IntelliJ UE 2023.3
- Bazel Plugin 2024.01.02.0.1-api-version-233
- Scala Plugin 2023.3.20

I can see the gutter icons:

- Java side: 
<img width="950" alt="Screenshot 2024-01-31 at 11 31 24" src="https://github.com/bazelbuild/intellij/assets/5861182/8e18b88c-0652-440c-914f-c30fe113b99b">

- Scala side:
<img width="853" alt="Screenshot 2024-01-31 at 11 56 11" src="https://github.com/bazelbuild/intellij/assets/5861182/001214c3-a08f-4495-ae67-29da0bac12b7">


Could you try IJ and the plugin, and checking again?
Additionally, could you make sure there are no sync errors in your project?

If it doesn't solve your problem: I'm not an expert in SpringBoot, so there might be a use case I'm failing to repro. Could you provide us with an example project reproducing your issue?

**Comment by AlexBurdu** [comment]
Hi @blorente,

Thank you for looking into this! It appears that the issue was incidentally partially resolved :tada:, as in I now see the Spring Framework Beans gutter.

![image](https://github.com/bazelbuild/intellij/assets/1262636/395f70b1-2bd2-4854-9fbd-55dd8aa512ae)

I do not see HTTP Client ones, BUT this may somewhat a different issue, as I created a Grade project and it looks like that gutter was moved inline.

![image](https://github.com/bazelbuild/intellij/assets/1262636/18aa572a-374a-4928-a0ec-4b3c2aa7884d)
![image](https://github.com/bazelbuild/intellij/assets/1262636/bc398cd6-674f-40e7-a475-0626ac487a6e)

In your screenshot the `@GetMapping` annotation is missing a gutter as well. Do you have HTTP Client plugin enabled?

Is the integration for that gutter similar to the one on the left side of the editor?
