### ISSUE TITLE
How to run “Bazel->Sync->Sync Projects with BUILD Files” using a command

### ISSUE THREAD

**Issue by ponagraj** [bazelbuild/intellij#5309]
I’m trying to find if there is a way to mimic
“Bazel->Sync->Sync Projects with BUILD Files” using a command from the terminal.
I noticed that doing sync from the menu bar runs quite a bunch of commands. I tried running’bazel sync’ command but seems it doesn’t solve the purpose. It would be great if we can invoke the same from command line.

**Comment by Pavank1992** [comment]
@ponagraj  Could you please provide sample code to reproduce this issue?

**Comment by ponagraj** [comment]
@Pavank1992 Thank you for looking into this. This is actually not a issue. From IDE we run ‘Sync Projects With Build Files’, as shown in the image attached. 
![IMG_1367](https://github.com/bazelbuild/intellij/assets/52603711/4afcacf5-6e68-4028-a0c7-3fcdd6c754ac)

 I want to know if there is a command to do the same from command line.

**Comment by Pavank1992** [comment]
No, there is not a command for this. The plug-in identifies the build files then runs bazel build on them.
