### ISSUE TITLE
Import Statements for external libraries are not working even after complete/partial sync in IntelliJ

### ISSUE THREAD

**Issue by USB-05** [bazelbuild/intellij#5313]
### Description of the bug:

After doing complete sync and partial sync using Bazel plugin in IntelliJ still many import statements are not working in the Java classes and i am working in red. I am using macOS M1 chipset.

IntelliJ version: 2022.3.3 
Bazel Plugin version: 2023.07.04.0.1-api-version-223 
macOS version: M1 chipset (Ventura 13.5.1)

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Import bazel + java project
2. Do the partial/complete sync of project from bazel plugin in intellij
3. Open any Java class and see if all the import statements are getting resolved or not.

### Which Intellij IDE are you using? Please provide the specific version.

2022.3.3 

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2023.07.04.0.1-api-version-223

### Have you found anything relevant by searching the web?

Nope, did not find any concrete solution to this.

### Any other information, logs, or outputs that you want to share?

I am not sure what to share here. You can tell me what you need and i will share.

**Comment by USB-05** [comment]
<img width="1120" alt="image" src="https://github.com/bazelbuild/intellij/assets/80256915/ef4da462-093e-4f09-9737-79eff336b69a">

**Comment by mai93** [comment]
I was not able to reproduce this with https://github.com/bazelbuild/intellij/tree/master/examples/java/greetings_project. Can you make sure that the sync succeeded? Also if you can send a small project where this problem happens, it will be easier to investigate.
