### ISSUE TITLE
Getting notifications about build issues (and their `IssueOutput`s)

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#533]
We'd like to implement quickfixes for fixing certain issues that are flagged during build. For this, we'd like to get notified when new `IssueOutput`s are available. We use a separate plugin to augment IntelliJ with functionality specific to our builds, so we'd like to do this without adding those to the Bazel plugin code.

What would be the best way to get notified about this? Right now, I've thought about modifying the `IssueScope` class to raise a message via pub/sub (via IntelliJ's `messageBus`), instead of directly adding new issues to the `BlazeProblemView`. The `BlazeProblemView` could be the consumer of those messages, as well as my own custom listener. `onScopeBegin` could send a "reset" message so that old state can be cleared.

Do you have better ideas/suggestions on how to hook/implement into that?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
