### ISSUE TITLE
Feature Request: ability to dynamically set custom flags for Bazel test commands

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/intellij#537]
### Background 
At Wix, since most developers work with Bazel on MacOS, there are some custom Bazel flags we want to add when developers run **specific** types of tests, in order to work around MacOS sandboxing limitations. To facilitate that, we created some macros that produce targets for the different testing scenarios, each macro attaches corresponding tags to the target, so we can later use `--test_tag_filters` to run only tests with a specific set of tags. We would typically have a config sesction per use-case in our `.bazelrc`, for example, to run integration tests, we would execute `bazel test --config=it //xxx`, which selects the following config flags from our `.bazelrc` file:

```
test:it --test_tag_filters=IT
test:it --strategy=TestRunner=standalone
test:it --local_test_jobs=1
```

### Desired IntelliJ Dev Experience
The most common way of running a test in intellij, is to click the little green arrow next to the test class declaration, or from the test class context menu. The problem is that when you do that, you get the default run configuration flags, which in our case is not desired for some tests. In order to able to set the right flags, we need to be able to intercept the creation of the run configuration and based on the test that's being executed, either leave the default untouched, or add some flags. 

I realize that this requirement is specific to the way we work at Wix, so I started exploring the possibility of implementing this functionality in a separate plugin, that's built on top of the public Bazel plugin (we already have that at Wix). The extension point `BuildFlagsProvider` could have solved my problem if it received enough context to allow me make a decision. Ideally I would have access to the tags of the target to which the test class belongs, but I could probably live with a heuristic based on the test class name, or even the source file name, because we have naming conventions for the different types of tests.

I would love to get some advice regarding how I can achieve my goal, either from an external plugin using extension points, or in the public plugin, if we can generalize our requirement. 
Collapse

**Comment by sha1n** [comment]
@brendandouglas I believe that with the right abstraction, we allow us to develop a private solution for the use-case presented in #474 in out extension plugin. Now that we agreed on closing that PR, this becomes more important to us..

Thanks.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
