### ISSUE TITLE
Attach Maven source jars

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#54]
Apropos https://github.com/bazelbuild/bazel/issues/308 and perhaps also https://github.com/bazelbuild/bazel/issues/1410 the plugin should be able to download and attach source jars to maven artifacts.

**Comment by brendandouglas** [comment]
See #42 for a Skylark-based workaround and related comments.

Our current plan is to wait for Bazel to support this. Our general philosophy with this plugin is to treat Bazel as the source of truth -- if Bazel doesn't supply source artifacts, we'd prefer not to add probably-fragile special-case support.
