### ISSUE TITLE
Errors on bazel ci with bazel from HEAD

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/intellij#541]
The intellij plugin fails when tested with Bazel from HEAD

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-1zsw/bazel-downstream-projects/intellij/aswb/BUILD:102:12: Configurable attribute "srcs" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/855#6dcbc3d5-0523-4355-9e64-41db71e4bc39

We'll disable testing until this issue is resolved. Thanks!

**Comment by brendandouglas** [comment]
Thanks for letting us know. This had already been fixed by https://github.com/bazelbuild/intellij/commit/a6022f78697f75509aed08d3b7062ac2ee00b35c -- could you re-enable the CI tests?
