### ISSUE TITLE
Migrate to Bzlmod for managing external dependencies

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/intellij#5432]
With future Bazel LTS versions, Bzlmod will become the default system for external dependencies management.

Please consider migrating all your external dependencies in WORKSPACE to MODULE.bazel

For more information, please check https://github.com/bazelbuild/bazel/issues/18958

**Comment by agluszak** [comment]
I can take care of this, but please first tell me if you're not working on it in your google-internal version.
cc @mai93

**Comment by mai93** [comment]
Thanks @agluszak! I've not started working on this
