### ISSUE TITLE
Enhance "Test Runner Tab" view

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#55]
Hi,
Just tried the new "Test Runner Tab" and it's a huge improvement so thank you!
There are two issues which I think are still substantially off with respect to the current view:
1. Console log of tests- When one goes into a specific test class you can't see any of the console log. You can see the exception message if the test failed but that's it. The entire log is on the root.
2. Incrementally add test names as they pass/fail- Not sure if this is related to the streaming part of the experimental UI in Bazle but maybe.

**Comment by brendandouglas** [comment]
Good to hear it's getting used!

Those were both trade-offs we made when implementing the test UI integration, unfortunately.

We went with a solution that was applicable across multiple languages (parsing the output XML from Bazel). The XML only gets written after the test execution completes, so no in-progress data. The XML also doesn't contain per-test-case stdout/stderr (as you saw, the only per-test data is for failures).

We (the IntelliJ team) don't have any plans to modify bazel itself to support these, though I believe there are plans for bazel to at some point implement a centralized 'build event protocol', which will likely solve (1).

**Comment by ittaiz** [comment]
The XML of all tests classes gets written at the end? I saw you use
streaming, doesn't that help?

**Comment by brendandouglas** [comment]
That's right -- regardless of the 'test_output' mode, there's not enough information in stderr/stdout (e.g. which test is currently running, etc.).

**Comment by ittaiz** [comment]
@brendandouglas thanks for the clear explanations. I'm seeing another weird behavior which I'm not sure if it's related to my setup or the plugin- After I run many tests where some fail the plugin shows the `problems` in the `messages` view instead of the `run` view. Any idea why?

@damienmg Is there a correlating Bazel ticket I can follow?

**Comment by damienmg** [comment]
I don't think there is a specific bug for this yet. We have a lot going on for the BEP to support our internal services and we are prioritizing this work for now.  Hopefully by end of Q1 we can start adding stuff for IDE support.

**Comment by brendandouglas** [comment]
I'm not sure what could be causing problems to show in the messages view. I've personally never seen anything appear there (the 'Messages' tool window option has always been disabled for me), though Blaze build errors do get mirrored in the 'Problems' view.

I might be missing something though -- could you please post a screenshot showing an example?

**Comment by ittaiz** [comment]
I was mistaken, it's the `Problems` view indeed.
I'm taking it with the copybara team and will report here if it traces back here.

**Comment by ittaiz** [comment]
@damienmg any news about BEP and IDE support?

**Comment by brendandouglas** [comment]
I've actually just moved us to using BEP internally to parse test results (and other build outputs). That will be in the Bazel plugin from v2016.06.20+.

It doesn't address either of your requests though, because:
- BEP test output is currently extremely limited -- it's basically a pointer to the same output XML file we were previously parsing. So we still can't associate stdout/stderr with specific test cases.
- the output XML is only written when the Bazel invocation finishes, so we still can't stream results.

**Comment by brendandouglas** [comment]
Had another look at this, and it's very unlikely this will be addressed in the future, so closing as infeasible.

Streaming test results and better matching of stdout/stderr to individual test cases require changes to all the test runners as well as upstream changes to Bazel, neither of which our plugin team will realistically have the time to do (at least not without a significant commitment from Bazel, which we don't have the bandwidth to push for).

Closing for now, but if this is important to you, I'd recommend opening a Bazel-side issue.

What we'd need to achieve this:
- per test case stdout/stderr reliably set in the test result output xml
- some mechanism for streaming test results on a per-test-case basis (either via the build event service, or by attaching to something like JUnit's RunListener API, but applied across all test runners).
