### ISSUE TITLE
Add option to specify projects location

### ISSUE THREAD

**Issue by TimvdLippe** [bazelbuild/intellij#554]
I am using IntelliJ to both work on open source projects (usually on GitHub) and internally with Bazel. My open source projects are thus git clones of GitHub repositories, which I placed in `~/Projects/`. Since this plugin stores metadata for all Bazel projects, I would like to keep them separate from my git repositories. That way, it is clear for me which projects I have locally cloned.

The current edit view control (https://github.com/bazelbuild/intellij/blob/4ed6c96949255499adf4f98010ae64ab8e918ef8/base/src/com/google/idea/blaze/base/wizard2/ui/BlazeEditProjectViewControl.java#L386-L409) uses the location of the last opened project. In this case, if I opened a git repository from `~/Projects/`, it will open any future Bazel project in that same directory. But I would like that to be placed in `~/BazelProjects/` instead.

Could an option be added to the edit view control which allows you to control where the Blaze-specific metadata is located? (Similar to how you are able to specify the Bazel binary location in the plugin settings)

**Comment by brendandouglas** [comment]
Moved to an internal bug -- this doesn't happen for bazel projects.
