### ISSUE TITLE
Add section in https://ij.bazel.build/ about allow_manual_targets_sync: true

### ISSUE THREAD

**Issue by rogerhu** [bazelbuild/intellij#5590]
### Description of the feature request:

Add section in Bazel intellij docs: (https://ij.bazel.build/docs/project-views.html) 

`allow_manual_targets_sync: true`

If this option is set the true, build targets labeled with the `manual` tag can still be synced, which will enable them to appear as debuggable targets. Enabling this option will also implictly enable the `shard_sync: true` to enable Bazel to query for targets especially in cases where `derive_targets_from_directories: true` is not also set.

Related to: 

- https://github.com/bazelbuild/intellij/issues/4546
- https://github.com/bazelbuild/intellij/issues/4546
- https://github.com/bazelbuild/intellij/pull/5458

Per conversation: https://bazelbuild.slack.com/archives/C025SBYFC4E/p1697741079375969

### What underlying problem are you trying to solve with this feature?

Adding existing documentation

**Comment by mai93** [comment]
Thanks @rogerhu! Added the new section documentation: https://ij.bazel.build/docs/project-views.html#allow_manual_targets_sync

**Comment by rogerhu** [comment]
Thanks! Is https://ij.bazel.build/docs/project-views.html#allow_manual_targets_sync still being published? I just took a look and don't see it reflected on the web site.

**Comment by mai93** [comment]
It should be published, I can see it. Maybe try again later. 
![image](https://github.com/bazelbuild/intellij/assets/70515749/2d3621a2-a822-494d-8191-dbe2758bfa67)

**Comment by rogerhu** [comment]
Thanks I see it now!
