### ISSUE TITLE
Debug session is launched in paused state in CLion since 2023.3

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#5651]
### Description of the bug:

Cannot debug `examples/cpp/simple_project` project

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/bazelbuild/intellij/assets/1066003/4dc2bb19-1e23-4205-ab94-c067f6112d84

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.3

**Comment by ujohnny** [comment]
So debugging works, this is a change in CLion 2023.3 as we pause the execution on the attach, see https://youtrack.jetbrains.com/issue/CPP-35922. Probably we should make "pause" optional, let me check if we can make some workaround.

**Comment by nd** [comment]
> but why it jumps to the assembly?

Because we don't have sources for _start

**Comment by ujohnny** [comment]
> but why it jumps to the assembly?

this is a `libc` assembly from `start`, that's how GDB interrupts on start. so you can just click resume and it will bring you to your sources.

**Comment by ujohnny** [comment]
I'm closing this bug as it's a CLion bug and the relevant youtrack link is already available in the thread
