### ISSUE TITLE
Allow to tolerate absence of import files referenced in `projectview`

### ISSUE THREAD

**Issue by dkashyn-sfdc** [bazelbuild/intellij#5688]
### Description of the feature request:

In some cases, when we are using templates, we'd like to have options to have user-specific customizations.
IJWB supposed to tolerate files absence in such cases. 

It is ok to render a warning if the file is not there yet Bazel flows supposed to ignore this fact otherwise.

There should be a registry key to activate this mode and by default imports are not optional.

### What underlying problem are you trying to solve with this feature?

Customization of templates.

**Comment by dkashyn-sfdc** [comment]
Proposed PR is here https://github.com/bazelbuild/intellij/pull/5689

**Comment by ujohnny** [comment]
@dkashyn-sfdc could you please elaborate what is the template in your context and share some more details on the usecase?

**Comment by dkashyn-sfdc** [comment]
When you import the project you can use `.projectview` template. We have such submitted to our VCS https://github.com/bazelbuild/intellij/pull/5227/files

![image](https://github.com/bazelbuild/intellij/assets/50216138/817ac2ee-d700-4290-968d-29a127218eeb)
