### ISSUE TITLE
Unit_tests  are failing with Bazel@HEAD                                                       

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#5690]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3459#018bcb95-7021-416e-b76d-860eb90a8fca
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3459#018bcb95-7cd4-4b69-b6ed-493e7e6b4b58
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3459#018bcb95-7237-4027-b5a9-20e03a63471a

Platform : Internal stable & Oldest stable Ubuntu

Logs:

```
//base:unit_tests                                                        FAILED in 3 out of 3
```

Steps:

```
git clone -v https://github.com/bazelbuild/intellij.git
git reset 23970569028fa51d1493c4ebfdfdc6208c657498 --hard
export USE_BAZEL_VERSION=dfcb9efc255535103d75981536112df3fd1993db
bazel test  --define=ij_product=android-studio-latest --test_output=errors  //:aswb_tests
```

CC Greenteam @SalmaSamy

**Comment by mai93** [comment]
should be fixed with https://github.com/bazelbuild/intellij/commit/73cde7e24b6446b6b3a7994ef144aa52ddbca5eb
