### ISSUE TITLE
Confusing error message when you right-click Run a class with no binary

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/intellij#57]
Consider this repository. https://github.com/dfabulich/right-click-main

It contains a blank `WORKSPACE` and a single `X.java` source file with a main method:

```java
public class X {
        public static void main(String[] args) {
                System.out.println("hello");
        }
}
```

The `BUILD` file declares only a `java_library`, not a `java_binary`.

```python
java_library(
        name='x',
        srcs=['X.java'],
)
```

The `.bazelproject` file includes everything.

```
directories:
  .
targets:
  ...
```

Open this project in IntelliJ with the Bazel plugin. Now right-click on `X` in IntelliJ's "Project" Tool Window and click "Run."

Actual: The "Run" menu item is called "Run 'X.main()'" and makes no mention of Bazel. When you run it, IntelliJ creates a non-Bazel "Application" Run Configuration, which fails with this baffling error message:

> Cannot start compilation: the output path is not specified for the module ".workspace". Specify the output path in Configure Project.

Expected: Don't allow IntelliJ to even try to run its own built-in compiler. If the user tries to "Run" something that doesn't have an associated `java_binary`, the Bazel plugin should intercept that and display a message like:

> No runnable Bazel target could be found for 'X.java'. Please define a java_binary target in the BUILD file.

**Comment by dfabulich** [comment]
It would be even better if the plugin would offer to autogenerate a `java_binary` target in the `BUILD` file:

```python
java_binary(
    name='X_runner',
    runtime_deps=['x'],
    main_class='X',
)
```

… and then run it!

**Comment by brendandouglas** [comment]
Good idea -- we'll suppress IntelliJ's run configuration producer (done for v2017.02.27+).

We're not really intending to include a plugin tool to fix BUILD deps at the moment. If we do at some future stage, we'll look at autogenerating the target.

**Comment by dfabulich** [comment]
In that case, will the effect be that the "Run" menu item won't appear when you right click? (Would "Run" only appear if the class has an associated binary?)

**Comment by brendandouglas** [comment]
That's right, the bazel run configuration only appears when there's an associated binary, and the IntelliJ 'run' option will never appear.

**Comment by dfabulich** [comment]
That's better than what we have now, but I think users will be confused if they add a main method to a class and try to right-click Run it and the option is simply missing. They won't know what to do to fix the problem.

It would be better to have a menu item that pops up a clear error message.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
