### ISSUE TITLE
Exception from bazel plugin while opening Goland project

### ISSUE THREAD

**Issue by Aoao54** [bazelbuild/intellij#5703]
#### Description of the issue. Please be specific.
With bazel plugin enabled, there will be an error when openning non-bazel project.

> java.lang.IllegalStateException: Non-blaze project is provided

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
just open a non-bazel project in goland , you will see this error.

#### Version information
GoLand: 2023.2.2
Platform: Mac OS X 13.5
Bazel for IntelliJ plugin: 2023.10.24.0.2-api-version-232
Bazel: 6.3.2

**Comment by sgowroji** [comment]
Hi @Aoao54, Can you please share the complete error logs. Thanks!

**Comment by blorente** [comment]
I think I recently implemented a fix in https://github.com/bazelbuild/intellij/pull/5674
