### ISSUE TITLE
Debug Support fading away

### ISSUE THREAD

**Issue by sosborn-trumid** [bazelbuild/intellij#5737]
### Description of the bug:

Previously, I was able to run my tests in both Run and Debug Mode.

Several weeks ago, although I was still able to choose either, only Debug Mode gave me output that included a list of tests run and status of each test.  
![image](https://github.com/bazelbuild/intellij/assets/119779153/7b3a3720-38db-44ed-9ac7-583a913ec6b6)

So, I just started using Debug mode all the time.

In the last couple days, Debug mode is missing entirely for some tests, and I cannot figure out why it is available for some and not others.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I do not know, but it is consistent in my environment.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 9, 2023

### What programming languages and tools are you using? Please provide specific versions.

Scala 2.12, Docker 228.8836.46, GitHub Copilot 1.4.1.3828

### What Bazel plugin version are you using?

2023.07.04.0.1-api-version-223

### Have you found anything relevant by searching the web?

No

**Comment by mai93** [comment]
IJ 2022.3.3 is no longer supported, Currently the plugin supports 2023.1, 2023.2 and 2023.3, does this issue happen on any of these versions?

**Comment by sosborn-trumid** [comment]
I upgraded to 2023.5 (which was the default), and fwiw, it happens there.  I will try to downgrade to one of these versions and test again.

**Comment by sosborn-trumid** [comment]
Problem persists in 2023.2.5

**Comment by mai93** [comment]
I cannot reproduce it on the example java project https://github.com/bazelbuild/intellij/tree/master/examples/java/greetings_project. can you provide a simple scala project to reproduce it?

**Comment by sosborn-trumid** [comment]
Probably not - I suspect it's something about my env.  Haven't heard anyone else on the team having the same issue with the same project, though I will ask again tomorrow.  Are there not logs that I could look at for more info?  For example, when I _do_ have the Debug option, try to run, and it appears to do nothing, would there not be logs somewhere?

**Comment by sosborn-trumid** [comment]
Solved.  This appears to have beed due to a PR adding an `org.scalameta.semanticdb.scalac` dependency to our scala.bzl file.
