### ISSUE TITLE
test_macro_expansion.xml is in the wrong directory?

### ISSUE THREAD

**Issue by ahmedyarub** [bazelbuild/intellij#5758]
The file [examples/go/with_go_source/with_go_source.bazelproject](https://github.com/bazelbuild/intellij/blob/master/examples/go/with_go_source/with_go_source.bazelproject) references [examples/go/with_proto/run_configurations/test_macro_expansion.xml](https://github.com/bazelbuild/intellij/blob/master/examples/go/with_proto/run_configurations/test_macro_expansion.xml) which seems to be in the wrong directory.

**Comment by sgowroji** [comment]
Hi @ahmedyarub, Could you please elaborate your query with clear details. Thanks!

**Comment by ahmedyarub** [comment]
There are two Go examples: with_go_source and with_proto. with_go_source references the file run_configurations/test_macro_expansion.xml in its with_go_source.bazelproject, while the file does not exist there. On the other hand, with_proto does contain the file run_configurations/test_macro_expansion.xml in its directory but it does not use it. This leads me to believe that the folder run_configurations should be under with_go_source  and not with_proto.

**Comment by ahmedyarub** [comment]
PR created https://github.com/bazelbuild/intellij/pull/5772.
