### ISSUE TITLE
Git repo is not detected upon importing project due to missing escaping in git command

### ISSUE THREAD

**Issue by ahmedyarub** [bazelbuild/intellij#5773]
### Description of the bug:

The following line uses [git rev-parse @{u}](https://github.com/bazelbuild/intellij/blob/master/base/src/com/google/idea/blaze/base/vcs/git/GitBlazeVcsHandlerProvider.java#L168) to detect whether the workspace folder is a valid Git repo. However, the @{u} is not quoted or escaped which causes the command to fail on multiple operating systems.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Import a Bazel project that has Git already initialized.

### Which Intellij IDE are you using? Please provide the specific version.

GO-233.11799.68

### What programming languages and tools are you using? Please provide specific versions.

Go with Goland

### What Bazel plugin version are you using?

Custom build of the latest master branch

### Have you found anything relevant by searching the web?

No

**Comment by sgowroji** [comment]
Hi @ahmedyarub, Could you please confirm this is happening for only Goland or other ID's too ?

**Comment by ahmedyarub** [comment]
It does, yes. It's an escaping problem and I've provided a PR.

**Comment by ahmedyarub** [comment]
The problem was that I did not have an upstream configured for that local repo.
