### ISSUE TITLE
Kotlin KSP generated code not resolving

### ISSUE THREAD

**Issue by ianb-pomelo** [bazelbuild/intellij#5778]
### Description of the bug:

When updating the plugin from `v2023.10.24.0.2-api-version-232` to `v2023.11.07`, Intellij no longer is able to resolve Kotlin code generated via KSP. The code compiles fine but it is not accessible in the IDE. 
KAPT generated code works as intended

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

[Use the KSP demo app](https://github.com/bazelbuild/rules_kotlin/tree/master/examples/ksp) and sync the target

### Which Intellij IDE are you using? Please provide the specific version.

Intellij Ultimate 2023.2.5

### What programming languages and tools are you using? Please provide specific versions.

Kotlin 1.7, Bazel 5.4.0, Bazel Kotlin Rules 1.8.1

### What Bazel plugin version are you using?

v2023.11.07

### Any other information, logs, or outputs that you want to share?

Intellij is running on Apple Silicon Macs

**Comment by rob-pomelo** [comment]
seems specifically that the *intellij-info.txt is missing a:
```
java_ide_info {
  generated_jars {
    jar {
      ...
      relative_path: "path/to/code/*-kt.jar"
    }
...
}
```
for the ksp related plugin code (which was present for kapt).

not sure if the plugin version is related and instead may just be stale ide info enabling discovery of the jar and updating invalided it

**Comment by mai93** [comment]
@ianb-pomelo is this a regression in version v2023.11.07 or it was already broken before that?

**Comment by ianb-pomelo** [comment]
It worked when I used version `v2023.10.24.0.2-api-version-232` and broke when I upgraded but when I tried to rollback and install v2023.10.24 via file it didn't work either so I'm not sure if it was a regression introduced by 11.07 or not
