### ISSUE TITLE
hope to support import alias

### ISSUE THREAD

**Issue by thorseraq** [bazelbuild/intellij#5841]
### Description of the feature request:

Hope to support import alias(seems currently not), example:

Relative path of `BUILD.bazel`is `path/to/api`, and importpath is `path/to/proto/api`, symbols under `path/to/proto/api` package cannot be indexed
```go
// BUILD.bazel
go_proto_library(
    name = "some_application_go_proto",
    importpath = "path/to/proto/api",
   // ...
)

```

**Comment by blorente** [comment]
Hello @thorseraq ,

Unfortunately, I don't have the bandwidth right now to add these features. I'll add it to my TODO list, but it's unlikely I'll be able to pick it up in the next months, so assigning a P3 label. I'd be happy to review a PR or provide some guidance though.
