### ISSUE TITLE
Facing error in Java project for Fast run & fast debug feature

### ISSUE THREAD

**Issue by rakshitasingh05** [bazelbuild/intellij#5845]
### Description of the bug:

1. Import Java Project
2. Check if the project is synced with no compilation errors
3. Click on the class name and click run to fetch the o/p
4. Click on the class name and click debug to fetch the o/p
5. Click on the class name and fast run which reproduced errors in the o/p
6. Click on the class name and fast debug which reproduced errors in the o/p
7. PFB the screenshots of the errors in fast run & fast debug

https://screenshot.googleplex.com/65V27w7JMZSkQRo
https://screenshot.googleplex.com/7YCg4aycnNfRK7h

### Which Intellij IDE are you using? Please provide the specific version.

2023.2.4

**Comment by mai93** [comment]
The error in console is ```ERROR: Skipping '//greeting_lib:greeting_test_deploy.jar': no such target '//greeting_lib:greeting_test_deploy.jar': target 'greeting_test_deploy.jar' not declared in package 'greeting_lib' ```, this only happens with Bazel 7.0.0

@hvadehra is there a known fix for this?

**Comment by mai93** [comment]
A fix will be included in a patch release of Bazel 7. I will leave this open until we implement the rest of the solution in the plugin but we can move forward with the release to Stable despite this issue.

**Comment by tanishktyagii** [comment]
We are also seeing this issue in the latest  beta version v2023.12.19 .

**Comment by tanishktyagii** [comment]
We are also seeing this issue in the latest beta version v2024.01.02 .

**Comment by mai93** [comment]
This require a fix in Bazel 7.0.0 which is going to be released in Bazel 7.0.1.

**Comment by mai93** [comment]
this is fixed for bazel 7.0.1 in https://github.com/bazelbuild/intellij/commit/a61a2561a5733a7e441863b681fccd431b1ff3df

**Comment by dtaveras** [comment]
@mai93 I'm using bazel 7.4.1, and the changes to fastbuildserviceImpl don't generate the auto_deploy.jar. I'm wondering if it's due to is_test_class_rule check here https://github.com/bazelbuild/bazel/commit/103830fd6431f0de7cc43fc5b5522c906f8fd076#diff-bbd96187ededd4fcae6f508791b4024100b8ba2f6a944836f139333e604de11eR299. Please let me know if I'm missing anything, I'd like to get fastbuild working once again.
