### ISSUE TITLE
CcLibraryTest failing with Bazel@HEAD in Downstream 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#5863]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3534#018c7b77-5711-4e33-a8f9-bf15da690da2

Platform : Ubuntu Aspect tests

Logs:
```
//aspect/testing/tests/src/com/google/idea/blaze/aspect/cpp/cclibrary:CcLibraryTest FAILED 
```
Steps:
```
git clone -v https://github.com/bazelbuild/intellij.git
git reset 24cd9c2954525014fa663cbe6498702359a2921c --hard
export USE_BAZEL_VERSION=bbc4b12eb562de5e5daeec9700fa258dfdc5a51b
bazel test   --define=ij_product=intellij-latest --test_output=errors --notrim_test_configuration  //aspect/testing/...
```

CC Greenteam @Wyverald

**Comment by mai93** [comment]
the culprit seems to be https://github.com/bazelbuild/bazel/commit/f4632dfa7753179d84b05e469259057798a2cce3. @comius is there a known migration to fix this?

**Comment by mai93** [comment]
I think the plugin tests are now passing in the last tests with Bazel@head: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3552
