### ISSUE TITLE
[FR] Add support for bazel prelude

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/intellij#587]
bazel allows you to have a file called `tools/build_rules/prelude_bazel` with some prefix that will be attached to each BUILD file in the repo.

Many use it to provide common load of macros and rules.

Using the plugin, if the macro / rule `load` command is declared explicitly in the same BUILD file , I can easily navigate to its code.

**But**, if the load command comes from the prelude I lose that ability.

We should support also definitions that comes from the prelude.

cc: @sha1n @ittaiz

**Comment by tpasternak** [comment]
Probably could be fixed here https://github.com/bazelbuild/bazel/issues/16150

**Comment by sgowroji** [comment]
Hello @or-shachar, We are closing this issue w.r.t above [comment](https://github.com/bazelbuild/intellij/issues/587#issuecomment-1224035047). Please reach us if you still have any further queries. Thanks!
