### ISSUE TITLE
CLion formats MODULE.bazel inconsistent to buildifier

### ISSUE THREAD

**Issue by martis42** [bazelbuild/intellij#5886]
### Description of the bug:

CLion formats `MODULE.bazel` files differently than [buildifier](https://github.com/bazelbuild/buildtools) does.
Concretely, buildifier clusters expressions which belong semantically together whereas CLion enforces empty lines between all statements.

This makes it annoying to work with CLion on projects which use buildifier to ensure a consistent formatting of their Bazel files.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a new Bazel project and add a `MODULE.bazel` file with content
```
bazel_dep(
    name = "rules_python",
    version = "0.27.0",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.10.11",
)
```

Also get buildifier: https://github.com/bazelbuild/buildtools/releases/tag/v6.4.0

Formatting the `MODULE.bazel` file with CLion will add an empty line between `python = ...` and `python.toolchain(` wheras formatting the file with buildifier will remove this empty line again.

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2023.3.2  Build #CL-233.13135.93

### What programming languages and tools are you using? Please provide specific versions.

NA

### What Bazel plugin version are you using?

2023.11.23.0.1-api-version-233

**Comment by mai93** [comment]
Maybe this is fixed with https://github.com/bazelbuild/intellij/pull/5829

**Comment by martis42** [comment]
Can confirm the latest release resolves this problem due to incorporating https://github.com/bazelbuild/intellij/pull/5829
