### ISSUE TITLE
Plugin treats bazel packages as UNC paths in Windows

### ISSUE THREAD

**Issue by malkia** [bazelbuild/intellij#5895]
### Description of the bug:

IDE crawls down being unuseable, until a minute passes on a project I'm working on. Procmon shows that for some reason, on Windows, the IDE and/or bazel plugin tries to access actual bazel packages, as UNC paths (!)

for example - 

![image](https://github.com/bazelbuild/intellij/assets/51738/47a41f84-2009-43d2-8627-b8bdb2e3ebb3)

Because these UNC paths do not exists - e.g. no `api` machine (`\\api`) or others, my machine would take completely long time to finish. (like ~5 secs per unc path on my machine).

That to be said, I understand that Windows is not supported, so I don't expect this to be fixed. It's more FYI when you have the time to look into it! Thanks!

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

With Visual Studio 2019, or 2022, but with 2019 toolset (e.g. BAZEL_VC_FULL_VERSION=14.29.30133) import this project into `CLion Nova` - https://github.com/malkia/opentelemetry-cpp - notice the whole IDE crawls for a long time, until it resolves.

### Which Intellij IDE are you using? Please provide the specific version.

CLion Nova

### What programming languages and tools are you using? Please provide specific versions.

C++

### What Bazel plugin version are you using?

Latest stable one

**Comment by LeFrosch** [comment]
@malkia Hi, I am not able to reproduce the UNC accesses using the latest version of the bazel plugin. Can you confirm that this still is an issue?

**Comment by malkia** [comment]
Sorry, I was not able time to test this today, I'll try later. Please close if you haven't seen an issue, and If I see one (with that version of the plugin), I'll update!

Thanks!!!
