### ISSUE TITLE
Navigation should not be hidden on project's website 

### ISSUE THREAD

**Issue by steren** [bazelbuild/intellij#59]
By default, the navigation on https://ij.bazel.build/ is hidden behind an hamburger menu.

This makes sense on mobile, but not on desktop. When there is room, this navigation should be expanded. 

It is the case when we go to sub pages (e.g. https://ij.bazel.build/docs/bazel-plugin.html)

**Comment by brendandouglas** [comment]
In practice, we're very unlikely to have the bandwidth to fix this. There's little point making small cosmetic changes to the website, for closing for now. If we ever get around to properly redoing the website, this will be addressed then.
