### ISSUE TITLE
2024.01.30.0.1-api-version-233 analysis cache discarded

### ISSUE THREAD

**Issue by brt-alexei** [bazelbuild/intellij#5942]
### Description of the bug:

Every time I run bazel command either in OS or IDEA terminal, I'm getting notification that cache is discarded: 
INFO: Build option --test_env has changed, discarding analysis cache.
And vise versa, project sync and run/test actions also discard cache.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a bazel run in terminal and then do it via run action. 

### Which Intellij IDE are you using? Please provide the specific version.

Build #GO-233.13135.104, built on December 19, 2023

### What programming languages and tools are you using? Please provide specific versions.

Go 1.21.4

### What Bazel plugin version are you using?

2023.12.19.0.1

### Any other information, logs, or outputs that you want to share?

it seems like problem applicable to all IDEs that uses Bazel plugin including CLion

**Comment by mai93** [comment]
I could not reproduce this but we had another report in https://github.com/bazelbuild/intellij/issues/5939, can you try with plugin version 2023.12.19.0.2?

**Comment by brt-alexei** [comment]
Yes, it seems like 2023.12.19.0.2 fixes the problem

**Comment by brt-alexei** [comment]
Problem re-appeared in 2024.01.30.0.1-api-version-233

**Comment by mai93** [comment]
2024.02.13.0.1-api-version-233 is also out, can you reproduce there?

**Comment by brt-alexei** [comment]
@mai93 please reopen

**Comment by brt-alexei** [comment]
@mai93 preliminary 2024.02.13.0.1-api-version-233 does not have problem. Let me try more and I'll confirm

**Comment by brt-alexei** [comment]
i cannot reproduce problem with 2024.02.13.0.1-api-version-233, please close
