### ISSUE TITLE
Golang test are failing  while executing on go_binary target in go/BUILD.

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#5943]
### Description of the bug:

While performing GoLang test cases from the IntelliJ examples through **Go tests** are failing.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Open any Bazel Golang project from intelliJ examples (https://github.com/bazelbuild/intellij/tree/master/examples/go/with_proto)
2. Open Go/Build file in that project
3. Click on Go Binary to execute GoLang test cases.
4. The Go test cases are failed.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ 2023.2.2

### What programming languages and tools are you using? Please provide specific versions.

Go Lang

### What Bazel plugin version are you using?

Bazel Plugin v2024.01.02 

### Any other information, logs, or outputs that you want to share?

<img width="1120" alt="Screenshot 2024-01-11 at 11 48 40" src="https://github.com/bazelbuild/intellij/assets/48122892/a264dbec-49f2-4b8f-93cd-5a1dc1745e28">

**Comment by blorente** [comment]
I think this is because macro expansion in test flags has been broken, so some part of https://github.com/bazelbuild/intellij/pull/4368/files got changes or reverted or invalidated.

**Comment by blorente** [comment]
Alright, I got to the bottom of this. The main issue is that, when running the tests in `Debug` mode, the test runner doesn't pass the env vars. So it doesn't work in `Debug`, but it does in `Run`. We must have changed how we pass flags to the debug runner. 
I'm not sure how `Debug` worked in the first place, but it definitely shouldn't. The flags should be passed via Env var in debug configurations.

Actions from here:
- I'll try to land https://github.com/bazelbuild/intellij/pull/5885. Once that lands, I can fix the project.
- Before then, I think it's safe to ignore the failure in `Debug`, and just be happy that it works in `Run`.

**Comment by mai93** [comment]
Thanks @blorente. I also wanted to add that this test should not be invoked from the BUILD file but from the run configuration that should be already imported because it contains the env var needed.

**Comment by tanishktyagii** [comment]
We are still  seeing this issue in the latest beta version v2024.01.16 .
