### ISSUE TITLE
Running external bazel commands de-syncs IJ

### ISSUE THREAD

**Issue by beala-stripe** [bazelbuild/intellij#599]
# Description

Partially syncing one file causes other partially synced files to de-sync. Running almost any `bazel` command in an external terminal also causes partially synced files to de-syc.

# Repro

https://github.com/beala-stripe/ij-sync-repro

1. Load the project in IJ (2018.3.6 CE, Bazel plugin v2019.03.18.0.2, Bazel 0.24.0).
2. Notice that `x/OtherTest.scala` contains symbols that don't resolve.
3. Partially sync `x/OtherTest.scala`. The symbols should now resolve.
4. Partially sync `x/B1.scala`. Notice that `x/OtherTest.scala` no longer resolves.

You can also swap (3) out for running an external command like `bazel build //x:b1`.

**Comment by brendandouglas** [comment]
In 'Settings > Other Settings > Bazel Settings', do you have 'Use a local jar cache' checked?

If not, then we're reading generated jars directly from bazel-out, and those files could disappear after subsequent bazel builds (or, for example, a 'bazel clean').

**Comment by beala-stripe** [comment]
@brendandouglas Thanks! So far enabling that has fixed the issue.
