### ISSUE TITLE
Auto sync (auto import in intellij slang)

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#6]
Allow setting auto-sync when importing a project.
This is very helpful in maven, exists in pants and I think that given your support of BUILD files editing will be helpful here

**Comment by tomlu** [comment]
Hmm, yes, we did have support for this in the past but turned it off because it was too slow (by orders of magnitude) for our typical large projects. Perhaps for small bazel projects this can be re-investigated.

**Comment by ittaiz** [comment]
I indeed think it can help people experimenting with Bazel.
If I'm not mistaken once that's supported one can just use "idea ." Import
from the CMD

**Comment by brendandouglas** [comment]
The auto-sync action Tom mentioned can be enabled in "Settings > Blaze Settings > Automatically re-sync project when BUILD files change".

This will trigger a blaze sync whenever changes are made to BUILD files or the .bazelproject file.

**Comment by ittaiz** [comment]
Not sure where you mean.
Couldn't find it in my blaze settings:
<img width="1123" alt="screen shot 2016-07-18 at 16 14 56" src="https://cloud.githubusercontent.com/assets/1378327/16915956/1cc5b7a6-4d03-11e6-82ce-16e9dae7e51a.png">

**Comment by brendandouglas** [comment]
Ah, sorry about that -- it is disabled. We'll put it back in the next release.

**Comment by ittaiz** [comment]
👍🏽

**Comment by ittaiz** [comment]
Any update? Was this re-enabled?

**Comment by brendandouglas** [comment]
Thanks for the reminder! The option should be appearing in the settings in the current release, though it's still turned off by default.

**Comment by ittaiz** [comment]
Great, thanks.
Totally agree with the default btw
