### ISSUE TITLE
clion sync fails due to experimental_repo_remote_exec

### ISSUE THREAD

**Issue by cnsgsz** [bazelbuild/intellij#6147]
### Description of the bug:

Clicking on "Sync Project with BUILD files" in Clion gives me the following error.

> Command: bazel query --tool_tag=ijwb:CLion --output=label_kind --keep_going same_pkg_direct_rdeps(\...
...
> ERROR: Traceback (most recent call last):
	File "/home/swang/.cache/bazel/_bazel_swang/ff2a6157a8aefe45e3eec5c0d2d5d22c/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1465, column 40, in <toplevel>
		remote_cuda_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: Traceback (most recent call last):
	File "/home/swang/.cache/bazel/_bazel_swang/ff2a6157a8aefe45e3eec5c0d2d5d22c/external/org_tensorflow/third_party/py/python_configure.bzl", line 41, column 42, in <toplevel>
		remote_python_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: Traceback (most recent call last):
	File "/home/swang/.cache/bazel/_bazel_swang/ff2a6157a8aefe45e3eec5c0d2d5d22c/external/org_tensorflow/tensorflow/tools/toolchains/cpus/aarch64/aarch64.bzl", line 312, column 43, in <toplevel>
		remote_aarch64_configure = repository_rule(
Error in repository_rule: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
 

The `repository_rule`s with issues mostly comes from tensorflow that I depend on. 

`bazel build ...:all` works.

My `.bazelproject` file is mostly default.
```
directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  .

targets:
  # Add targets that reach the source code that you want to resolve here
  # By default, we've added all targets in your workspace
  //...

additional_languages:
  # Uncomment any additional languages you want supported
  # dart
  # javascript
  # typescript
  python

# I already has this flag in .bazelrc. Adding this here does not resolve the issue.
build_flags:
  --experimental_repo_remote_exec
```

### Which category does this issue belong to?

CLion

### Which Intellij IDE are you using? Please provide the specific version.

clion 2023.3.4 (also has issue at 2023.3.x from which I upgraded when debugging)

### What Bazel plugin version are you using?

2024.01.30.0.1-api-version-233 (also has issue at an earlier version from which I upgraded when debugging)

**Comment by sgowroji** [comment]
Hi @cnsgsz, Can you provide sample code to test the same. Thanks!

**Comment by cnsgsz** [comment]
Adding tensorflow as a external dependency can re-produce this issue. Please see [tensorflow serving](https://github.com/tensorflow/serving) for an example (.bazelrc, WORKSPACE, etc).

**Comment by cnsgsz** [comment]
@mai93 suggested adding `query --experimental_repo_remote_exec` to `.bazelrc`, which fixed my issue.
