### ISSUE TITLE
Env vars are lost in bazel run configurations

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#6163]
### Description of the bug:

1. Run any code printing environment variables using bazel's run configuration
2. Run a shell script using shell run configuration and print the same variables

**Comment by mai93** [comment]
Based on @tpasternak analysis this is expected to be due to https://github.com/bazelbuild/intellij/pull/5885. @blorente can you please take a look?

**Comment by blorente** [comment]
I'll take a look first time tomorrow.

**Comment by blorente** [comment]
Hello! I'm trying to repro this issue to add some automated tests, but I'm not seeing any difference between CONSOLE and SYSTEM. 
I have the following setup:

- `BUILD .bazel`
```starlark
sh_binary(
    name = "test_env_vars_bin",
    srcs = ["test_env_vars.sh"],
)

```

- `test_env_vars.sh`
```shell
#!/usr/bin/env bash
set -euo pipefail

echo "USER: $USER"
echo "PATH: $PATH"
echo "HOME: $HOME"
echo "GOROOT: $GOROOT"
```

And both SYSTEM and CONSOLE print the same thing as running the script with a "Run Shell" run configuration.
Could you give an example of an env var that you'd expect to be there that is not?
