### ISSUE TITLE
Base:Unit_tests are failing with Bazel@HEAD in CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/intellij#6172]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-5ea3-4372-bcaa-99f8ee002e85

 Platform: Ubuntu

 Logs: 
```

FAIL: //base:unit_tests (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f177a7553c2b5378efd424b080c7e48f/execroot/_main/bazel-out/k8-fastbuild/testlogs/base/unit_tests/test_attempts/attempt_2.log)
--
  | (02:11:32) [401 / 405] 6 / 10 tests; 4 actions running; last test: //cpp:integration_tests
  | Testing //aswb:normal_integration_tests; 23s remote-cache, linux-sandbox
  | Testing //base:integration_tests; 16s remote-cache, linux-sandbox
  | Testing //java:integration_tests; 15s remote-cache, linux-sandbox
  | Testing //base:unit_tests; 11s remote-cache, linux-sandbox
  | buildkite-agent artifact upload base/unit_tests/test_attempts/attempt_2.log
  | 2024-02-28 02:11:33 INFO   Found 1 files that match "base/unit_tests/test_attempts/attempt_2.log"
  | (02:11:37) FAIL: //base:unit_tests (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f177a7553c2b5378efd424b080c7e48f/execroot/_main/bazel-out/k8-fastbuild/testlogs/base/unit_tests/test.log)
  |  
  | FAILED: //base:unit_tests (Summary)


``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/intellij
git reset 2fd70a88f20d37244656bd3b5f104c9d50e051e7  --hard
export USE_BAZEL_VERSION=8fa62447f76ae586dc39edab8740dd7e5d9fa11e
bazel build --define=ij_product=android-studio-oss-oldest-stable  -- //aswb/... 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
Clion : [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-4dc9-4376-a05d-5c390c7c6e22](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-4dc9-4376-a05d-5c390c7c6e22) 

IntelliJ : [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-6c1b-4340-a602-ea7d92ea4ed6](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-6c1b-4340-a602-ea7d92ea4ed6)

Aspects : [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-6d93-4ab0-a887-f5e54c3f672f](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3685#018ded76-6d93-4ab0-a887-f5e54c3f672f) 

Also see the failures in the above CI

**Comment by mai93** [comment]
@meteorcloudy the test is passing with released Bazel as the version was part of the jar path, so it looked like `@@rules_jvm_external~6.0~maven~com_google_guava_guava//jar:jar` but with bazel@head it is `@@rules_jvm_external~~maven~com_google_guava_guava//jar:jar`, is this the new format and we should adjust the test for it?

**Comment by meteorcloudy** [comment]
Indeed, this was due to https://github.com/bazelbuild/bazel/pull/21035 which is also backported to 7.1.0. In general, the canonical repo name is not an API you should depend on if that's possible.
