### ISSUE TITLE
Both bazel run and sync will recompile

### ISSUE THREAD

**Issue by kekxv** [bazelbuild/intellij#6252]
### Description of the bug:

Both bazel run and sync will recompile.
They don't seem to be using the same cache.

<img width="395" alt="截屏2024-03-11 13 50 37" src="https://github.com/bazelbuild/intellij/assets/15551108/3e6efc89-3a5a-4b77-ba82-e127cb2546c1">

### Which category does this issue belong to?

CLion

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Any code regarding rules_foreign_cc.

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2024.1 EAP (Nova)

### What programming languages and tools are you using? Please provide specific versions.

clang or gcc

### What Bazel plugin version are you using?

Build label: 7.0.2-homebrew

### Have you found anything relevant by searching the web?

<img width="875" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/46f3fc65-860f-43a2-98e6-a6da54b6e249">

### Any other information, logs, or outputs that you want to share?

 `clion 2022.3.3` does not have this problem

**Comment by ujohnny** [comment]
@LeFrosch could you please help me with this one?

**Comment by LeFrosch** [comment]
Hi, @kekxv the fact that you have two sync buttons is a bit strange. Do you experience this issue with both of them? And by any chance do you know if they execute the same action?

**Comment by kekxv** [comment]
> Hi, @kekxv the fact that you have two sync buttons is a bit strange. Do you experience this issue with both of them? And by any chance do you know if they execute the same action?

@LeFrosch 
both, and not chance.

> It's not the two syncs I set up myself. It happened suddenly in a certain version. I thought it was a new feature.
> (不是我自己设置的两个sync，他是在某个版本突然这样，我还以为是新功能)

<img width="594" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/f600a6bb-b611-4af6-81ff-5f1dea144502">

this is `.clwb` 
[clion.clwb.zip](https://github.com/bazelbuild/intellij/files/14557654/clion.clwb.zip)

**Comment by LeFrosch** [comment]
Since sync runs 
```
bazel build … --output_groups=intellij-resolve-cpp,intellij-info-cpp,intellij-info-generic … -- <project targets>
```
sync does not actually build any project targets because they are excluded by the `output_groups` flag. Therefore, when a run configuration is invoked it still needs to build the required targets.

As far as I can tell sync and run configurations do use the same cache.

**Comment by kekxv** [comment]
@LeFrosch I thought it was strange too, but sync did it!

```
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: 139 targets (0 packages loaded, 0 targets configured)
Analyzing: 139 targets (0 packages loaded, 0 targets configured)
[0 / 1] checking cached actions
Analyzing: 139 targets (34 packages loaded, 23447 targets configured)
[1 / 1] checking cached actions
Analyzing: 139 targets (36 packages loaded, 35267 targets configured)
[195 / 211] Foreign Cc - CMake: Building zstd; 0s darwin-sandbox ... (5 actions, 4 running)
Analyzing: 139 targets (36 packages loaded, 35300 targets configured)
[195 / 245] Foreign Cc - CMake: Building zstd; 1s darwin-sandbox ... (8 actions running)
```

<img width="639" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/8d24bd9a-0d71-4b8e-a6de-79e2db635c77">

<img width="1274" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/c7924ee2-5bf8-447c-8638-72b0fb8b0e80">

<img width="1588" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/d6e674fa-407a-4301-8cf6-58f94bac7281">

**Comment by LeFrosch** [comment]
@kekxv Thank you for the further information. Could you send me the command which is run in your last screenshot. The one of the `Build shared 6ef...`

**Comment by kekxv** [comment]
Build shared 6ef... :

```
Command: bazel build --tool_tag=ijwb:CLion --keep_going --build_event_binary_file=/var/folders/q_/pryc8hhx60sb72vx2_cm813c0000gn/T/intellij-bep-1dfe723a-2cf1-4096-8878-067eeffe4c70 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --noexperimental_run_validations --aspects=@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/caesar/Library/Application Support/JetBrains/CLionNova2024.1/plugins/clwb/aspect" --output_groups=intellij-resolve-cpp,intellij-info-cpp,intellij-info-generic -- //unified-service/unified-auth-service:all //unified-service/unified-database-service:all //basic/tools:all //unified-service/core:all //basic/tools:tools //unified-service/core:core //unified-service/unified-database-service:unified-database-service //basic/BmpTool:BmpTool //basic/BmpTool:cBmpTool //basic/CameraTool:CameraTool //basic/UTF8Url:UTF8Url //basic/WXBizMsgCrypt:WXBizMsgCrypt //basic/...
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: 139 targets (0 packages loaded, 0 targets configured)
Analyzing: 139 targets (0 packages loaded, 0 targets configured)
[0 / 1] checking cached actions
Analyzing: 139 targets (34 packages loaded, 23447 targets configured)
[1 / 1] checking cached actions
Analyzing: 139 targets (36 packages loaded, 35267 targets configured)
[195 / 211] Foreign Cc - CMake: Building zstd; 0s darwin-sandbox ... (5 actions, 4 running)
Analyzing: 139 targets (36 packages loaded, 35300 targets configured)
[195 / 245] Foreign Cc - CMake: Building zstd; 1s darwin-sandbox ... (8 actions running)

```


bazel run : 
```
bazel run --tool_tag=ijwb:CLion --curses=no --color=yes --progress_in_terminal_title=no -- //unified-service/unified-config-service:unified-config-service
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //unified-service/unified-config-service:unified-config-service (0 packages loaded, 0 targets configured)
Analyzing: target //unified-service/unified-config-service:unified-config-service (0 packages loaded, 0 targets configured)
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
INFO: Analyzed target //unified-service/unified-config-service:unified-config-service (49 packages loaded, 333 targets configured).
[47 / 134] Foreign Cc - Configure: Building iconv; 1s darwin-sandbox ... (8 actions running)
```
@LeFrosch  bazel run Rebuilding iconv

**Comment by kekxv** [comment]
@LeFrosch 
hi. any progress?

**Comment by LeFrosch** [comment]
Hi @kekxv, sorry for the late response. I can confirm that sometimes bazel sync does build some stuff but I am not sure why and what causes this. However, I did notice that most of the time it only builds dependencies or generates something. Also I was not able to find any difference in behavior between 22.3 and 23.3 or Nova. On the other hand there is a difference between bazel 6 and 7.

Also in the logs you send me I think it’s interesting that it says:
```
CMake: Building zstd
```
So it’s not bazel directly building something.

**Comment by kekxv** [comment]
Hi @LeFrosch, 
```
CMake: Building zstd
```
Because my project introduced a third-party `zstd`:

<img width="790" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/33891f11-d84e-4754-8118-ea15c4e3a696">


```
"""A module defining the third party dependency zstd"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

def zstd_repositories():
    maybe(
        http_archive,
        name = "zstd",
        build_file_content = all_content,
        strip_prefix = "zstd-1.5.5",
        urls = [
            "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5.tar.gz",
        ],
        integrity = "sha256-nEOWzIKc+uMZpuJhUgLoKq1BNyBzSC/OKG+seGRtPuQ=",
    )
```

In the latest version, `sync` no longer conflicts with `terminal`, but it still conflicts with `the Run`.

> `sync`:
> 
> <img width="107" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/7f674d2c-f978-4fbe-b955-6134ec5cb5fe">
> 
> `terminal`:
> 
> <img width="466" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/ad6e4e79-aff0-4b72-b0d1-62d22061842e">
> 
> `the Run`:
> 
> <img width="563" alt="image" src="https://github.com/bazelbuild/intellij/assets/15551108/ef76c5b2-fce4-4fe2-9005-137aa20f8e21">

**Comment by LeFrosch** [comment]
@kekxv Thanks for the further information. I am sorry but I am still struggling to recreate your issue. If it is not too much trouble could you create a simple project where you experience this issue and share this project with me.

**Comment by kekxv** [comment]
@LeFrosch 
I created a new project, but this phenomenon does not occur. I will close the current issue first and wait until I have time to sort out the project again to see if it will still happen.
(我创建了新的项目，但是并没有这个现象，我先将当前issue关闭，等我有时间讲将项目重新梳理一遍看看还会不会出现。)

Thanks you .
