### ISSUE TITLE
Wrong java root src dir in IDEA

### ISSUE THREAD

**Issue by andrewmed** [bazelbuild/intellij#63]
Hi
I tried different configurations, IDEA shows instead of `java` dir the directory right beneath it i.e. the domain name, thus wrong package naming etc.

like:                  main -> java -> `org`
should be:      main -> `java` -> org

My setup: 

```
idea 163.12024
plugin 02.13.01

andy@laptop:~/repo/someapp$ bazel version
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261
```

**Comment by brendandouglas** [comment]
Hi,
We try to parse package paths during bazel execution, and only in the case where that fails, we fall back to skipping "java" / "javatests" at the start of a path (to adhere to an internal convention).

Are these java sources covered by a target in your .bazelproject file?

**Comment by andrewmed** [comment]
Now it is back to normal, but back then there where no other java directory beneath, and sources were set all above, anyway, cant reproduce reliably now

**Comment by brendandouglas** [comment]
Ok, thanks for letting us know. I'll close for now, but please reopen if this happens again, and you have java sources below the directory covered by your .bazelproject 'targets'.

**Comment by andrewmed** [comment]
ok. thanks. one other question though -  did not find any forum to ask that. 
what is the right way to link external (maven) dep into idea project? I figured out where external  jar is kept in bazel directories, but it looks like I cant add them into idea project, because these directories are set up by default as "ignored"

**Comment by brendandouglas** [comment]
Any external jars covered by the 'targets' in your .bazelproject file should be indexed as external libraries during bazel sync (you can see them in the 'External Libraries' section of the project tab).

So you should be able to navigate to external imports in java classes, etc.

Or do you mean navigating in BUILD files (e.g. following an external target like '@junit//:junit.jar')?

**Comment by andrewmed** [comment]
Hm.. Cant add external jar there, I get
```
Error:(2, -1) Workspace path must be relative; cannot start with '/': /external:junit4
```
when i set i .bazelproject:
```
directories:
  .
  //external:junit4
```

**Comment by brendandouglas** [comment]
Sorry, I meant covered by the transitive closure of your targets.

You can't add external workspace deps directly into the .bazelproject file -- that's only for specifying project targets. Any external libs must be brought in as dependencies of your project targets.
