### ISSUE TITLE
Using plugin with bazel wrapper under tools/bazel (Android Studio)

### ISSUE THREAD

**Issue by AnDevi** [bazelbuild/intellij#6313]
### Description of the bug:

I'm using this plugin with Android Studio 2023.3. (I also tried 2022.3 version)
It works fine when I don't have a wrapper for bazel placed under path `{workspace}/tools/bazel`,
but when I put wrapper under `tools/bazel` plugin fails during syncing the project. 
I got an error: `Error:ERROR: Skipping 'Support/Google/AndroidStudio2023.2/plugins/aswb/aspect'`

This wrapper is something that I really need in my setup of bazel. Is it possible to use wrapper to bazel alongside with this plugin ? 
Or I need to do something else to setup this correctly ?

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run simplest bazel project for android with wrapper under the path `{workspace}/tools/bazel`
`bazel` is an bash script with content:
```
#!/usr/bin/env bash
$BAZEL_REAL $@
```

### Which Intellij IDE are you using? Please provide the specific version.

Android Studio 2023.3

### What programming languages and tools are you using? Please provide specific versions.

Bazel: 7.1.0, sdk: android-33, java, cpp 

### What Bazel plugin version are you using?

Bazel for Android Studio plugin: 2024.02.27-aswb.0.1-api-version-232

**Comment by mai93** [comment]
I was not able to reproduce the issue with the simple wrapper provided, did you specify the path to this wrapper in `Settings -> Bazel Settings -> Bazel Binary Location`?

**Comment by AnDevi** [comment]
Under the `Settings -> Bazel Settings -> Bazel Binary Location` I got set  just `bazel`.
When I set there path to this wrapper I `tools/bazel` I got different error:
```
Command: tools/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --config=android --
tools/bazel: line 2: info: command not found
```

I think that is cuz when I run `./tools/bazel` `bazelisk` is not setuping `BAZEL_REAL` variable, you need to use `bazel` binary to run that wrapper with `BAZEL_REAL` see I think. 

I tried to change wrapper code to avoid lack of `BAZEL_REAL`:
```
#!/usr/bin/env bash
bazelisk $@ // can't use `bazel` in here cuz it'll cause infinite loop of recursive callings
```
but even with that I still got an error `Error:Could not run Bazel info` during syncing

**Comment by mai93** [comment]
can you try running the wrapper from command line to make sure it is working?

Also you may need to specify the absolute path of the wrapper in the `Bazel Binary Location` setting.
