### ISSUE TITLE
CI test failures on Google branch 

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#6317]
### Description of the bug:

Hi Team,

There are CI test failures in Google branches which is a blocker for upcoming release.

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1>  Click on https://github.com/bazelbuild/intellij/tree/google
2>  Click on the CI test checks and failures can be seen

### Any other information, logs, or outputs that you want to share?

![Screenshot 2024-03-25 11 36 32 AM](https://github.com/bazelbuild/intellij/assets/159875083/778cb3ed-e608-45ec-9d4f-cedeb5c10111)

**Comment by mai93** [comment]
Thanks, fixed with 0d214dbd9c851da213dd13d0699892697012d21c
