### ISSUE TITLE
"Add file to project" should be more Bazel-aware

### ISSUE THREAD

**Issue by dkashyn-sfdc** [bazelbuild/intellij#6358]
### Description of the feature request:

For the projects that not using 1:1:1, and `glob` is used to include sub-folders, we cannot expect that we can just add `module/src/java/a/b/c` as a directory for `a.b.c.Cl.java` file with an appropriate `glob` that takes care of `src/java` here.

In such cases `BUILD` or `BUILD.bazel` file can be located in `module` folder while the full path to the class will be `module/src/java/a/b/c/Cl.java`

We need to make sure that there is a real Bazel build file in the folder(or one of the parent folder) before adding it to `directories`. If there is no such folder we'll add `a/b/c` that is used currently.

### Which category does this issue belong to?

Intellij

### What underlying problem are you trying to solve with this feature?

IJ is unable to Compile(or Sync) Bazel project cleanly if a wrong `directories` entry is there.

`ERROR: Skipping '//module/java/src/a/b/...:all': no targets found beneath 'module/java/src/a/b'

**Comment by tpasternak** [comment]
fixed in #6388
