### ISSUE TITLE
CI check failure on Google branch

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#6396]
### Description of the bug:

We have CI check failure below which is a blocker for Release for this week. Could you please have a look ?

**buildkite/intellij-plugin-aspect-google** 

### Which category does this issue belong to?

Android Studio

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1) Open https://github.com/bazelbuild/intellij/tree/google
2) Click on the checks, failures can be seen.

### Any other information, logs, or outputs that you want to share?

![Screenshot 2024-04-22 2 43 21 PM](https://github.com/bazelbuild/intellij/assets/159875083/b63fb638-72ae-4811-b826-169a641c8caa)

**Comment by mai93** [comment]
thanks @satyanandak, the culprit is https://github.com/bazelbuild/intellij/commit/aed9b766704a249bb0be91daa85ba0227f566a6d. I contacted the author for a roll back.
