### ISSUE TITLE
Goland 2024.1 Editor Problems Analysis Stuck

### ISSUE THREAD

**Issue by amjadtalib** [bazelbuild/intellij#6406]
#### Description of the issue. Please be specific.
Syntax highlighting and indexing features stop working in GoLand after upgrading to 2024.1. Sometimes syntax highlighting works and I can cmd-click but the top-right corner of editor window is mostly stuck in perpetual `Analyzing...` state without any indication of IDE processing/indexing.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
README from MRE https://github.com/amjadtalib/mre-bzl-goland-2024

#### Version information
GoLand: 2024.1
Platform: Mac OS X 14.4.1
Bazel for IntelliJ plugin: 2024.04.09.0.1-api-version-241
Bazel: 7.1.1

**Comment by amjadtalib** [comment]
Issue was related to [PY-70729](https://youtrack.jetbrains.com/issue/PY-70729/Class-com.jetbrains.python.psi.PyElementType-must-not-be-requested-from-main-classloader-of-Pythonid-plugin).

Fix for me was to install the [JB Toml Plugin](https://plugins.jetbrains.com/plugin/8195-toml).

Thanks to @tpasternak for helping to resolve!

**Comment by tpasternak** [comment]
Thanks, I hope the actual fix will also land soon
