### ISSUE TITLE
`-filtered-gen.jar` and `-filtered-gen-src.jar` generated for packages without any `.java` files

### ISSUE THREAD

**Issue by dkashyn-sfdc** [bazelbuild/intellij#6407]
### Description of the feature request:

We do have "resources"-only packages that generate Java code and then compile it as part of the build. 
Those packages are consumed by others, and sources/classes are certainly used downstream. 
Some of such modules have absolutely no `.java` sources present that results in missing `-filtered-gen.jar` entries.

Since there are no source artifacts generated for such packages, there is nothing in `.intellij-info.txt` after aspects pass, and IDE cannot navigate to legitimate sources.

I suspect that https://github.com/bazelbuild/intellij/blame/86e31292434875ca1f86a02230cde5a3de5a70cf/aspect/intellij_info_impl.bzl#L794 should detect such cases to be able to generate required jars anyway here https://github.com/bazelbuild/intellij/blame/86e31292434875ca1f86a02230cde5a3de5a70cf/aspect/intellij_info_impl.bzl#L653

### Which category does this issue belong to?

Intellij

### What underlying problem are you trying to solve with this feature?

Navigation to the generated source code for non-standard targets without any `.java` sources.

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

Any

### Any other information, logs, or outputs that you want to share?

Before:
```
❯ ls -l bazel-bin/pppp/ | grep gen
dr-xr-xr-x. 4 user group  4096 Apr 25 14:59 rrr_generated
-rwxr-xr-x. 1 user group 10577 Apr 18 13:51 rrr_generated-0.params
```

Then I've created a dummy class that was just an empty file 
<img width="1014" alt="image" src="https://github.com/bazelbuild/intellij/assets/50216138/be07b7ff-2d1c-465d-a4e7-79fb7b48ee96">

After running `Bazel Sync` next time I see
```
❯ ls -l bazel-bin/pppp | grep gen
-r-xr-xr-x. 1 user group  1843 Apr 25 20:05 pppp_lib-filtered-gen.jar
-r-xr-xr-x. 1 user group  1808 Apr 25 20:05 pppp_lib-filtered-gen-src.jar
dr-xr-xr-x. 4 user group  4096 Apr 25 14:59 rrr_generated
-rwxr-xr-x. 1 user group 10577 Apr 18 13:51 rrr_generated-0.params
```

**Comment by tpasternak** [comment]
I'm not sure honestly. Maybe these targets could be just added to the libraries section in IntelliJ Project Structure? Would it be possible to prepare a minimal reproducible example?

**Comment by dkashyn-sfdc** [comment]
This is part of our large project and generation is happening inside a macro. So I don't even have a good repro to share here :(

I need to introduce some Code generation to `greetings_project` to even give you a repro. 

Is there a way to do this now, @tpasternak ?
> Maybe these targets could be just added to the libraries section in IntelliJ Project Structure

**Comment by dkashyn-sfdc** [comment]
We not using targets and `directories` is the only mechanism that we using.

**Comment by dkashyn-sfdc** [comment]
Please note that we have hundreds of such "targets" so if we want to include all of those as part of `.bazelproject` we need to use some wildcards, and even this might not be possible. I need to explore our graph more and probably rename some things to make it work.

**Comment by dkashyn-sfdc** [comment]
@tpasternak you can find repro here https://github.com/bazelbuild/intellij/pull/6415/files. It probably not a wrong idea to add some code generation to sample project as well...

With 
```
directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  greeting_lib

# Automatically includes all relevant targets under the 'directories' above
derive_targets_from_directories: true

targets:
  # If source code isn't resolving, add additional targets that compile it here

additional_languages:
  # Uncomment any additional languages you want supported
  # android
  # dart
  # go
  # javascript
  # kotlin
  # python
  # scala
  # typescript
```

<img width="665" alt="image" src="https://github.com/bazelbuild/intellij/assets/50216138/af7a778c-21e1-4453-97f4-54167da9d077">

With
```
directories:
  # Add the directories you want added as source here
  # By default, we've added your entire workspace ('.')
  .

# Automatically includes all relevant targets under the 'directories' above
derive_targets_from_directories: true

targets:
  # If source code isn't resolving, add additional targets that compile it here

additional_languages:
  # Uncomment any additional languages you want supported
  # android
  # dart
  # go
  # javascript
  # kotlin
  # python
  # scala
  # typescript
```

<img width="670" alt="image" src="https://github.com/bazelbuild/intellij/assets/50216138/bbd504b2-15f9-4335-8fe6-0a1beb586738">

**Comment by dkashyn-sfdc** [comment]
With a dummy java class

<img width="1879" alt="image" src="https://github.com/bazelbuild/intellij/assets/50216138/6440d919-ebf5-4291-8155-a20716392b4d">
<img width="1233" alt="image" src="https://github.com/bazelbuild/intellij/assets/50216138/5b3efc10-c9ec-4717-bb73-53364e84efbf">

**Comment by tpasternak** [comment]
Ok, to me it seems to be unrelated to the JarFilter logic. The generated library is correctly attached with the source jar, but the contents of the source jar doesn't match the contents of the jar. Doesn't it look like a bazel bug?

![image](https://github.com/bazelbuild/intellij/assets/1066003/3a197f0d-c287-4c9d-8fbf-a23c7ab57f6b)

![image](https://github.com/bazelbuild/intellij/assets/1066003/1e1927c1-3606-40ec-8238-94cc45da65ab)

**Comment by tpasternak** [comment]
Reported to bazel https://github.com/bazelbuild/bazel/issues/22254

**Comment by dkashyn-sfdc** [comment]
This issue is more nuanced and not only `filtered-gen-src.jar` can be used as lib source.

`_lib-src.jar` is used when package with generated module referred from some other module.
