### ISSUE TITLE
CI Checks failure on Master branch

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#6417]
### Description of the bug:

Hi Team, 
One of the checks is failing on Master branch, which is a blocker for release this week. Kindly have a look.

buildkite/intellij-ue-plugin - Build #11397 failed (2 minutes, 8 seconds)

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1) Click on https://github.com/bazelbuild/intellij
2)  Click on CI checks, failures can be seen.

### Any other information, logs, or outputs that you want to share?

![image](https://github.com/bazelbuild/intellij/assets/159875083/aa9bd89a-1e6c-4383-bd75-773cb656b526)

**Comment by tpasternak** [comment]
seems to be a network issue

**Comment by satyanandak** [comment]
Thanks @tpasternak, it's passing now.
