### ISSUE TITLE
Importing an existing repository shows no relevant files

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/intellij#6423]
#### Description of the issue. Please be specific.
I tried to open https://github.com/aspect-build/aspect-cli. The project doesn't show any of the files in this repository.

#### What's the simplest set of steps to reproduce this issue? Please provide an example project, if possible.
1. Clone https://github.com/aspect-build/aspect-cli.
2. File -> Open...
3. Select the aspect-cli directory

Expected result:
Project view shows all of the files in the directory.

Actual result:
Project view shows only the .ijwb directory, nothing else.

#### Version information
IdeaUltimate: 2024.1
Platform: Mac OS X 14.4.1
Bazel for IntelliJ plugin: 2024.03.26.0.1-api-version-241
Bazel: 7.0.2

**Comment by tpasternak** [comment]
@jfirebaugh When you import the project with the "Open" button, by default you end up with an empty import. Please edit the projectview file and sync.

**Comment by jfirebaugh** [comment]
That's a pretty confusing behavior... I think the average user, like me, is just going to think the plugin is broken. Could the default be to include everything, instead of excluding everything? Or could the "Open" button just use the default IntelliJ behavior for generating a project?

**Comment by nchepanov** [comment]
I just stepped into this as well, after 15 mins of clicking around I still don't understand how to bring my full project back, can you please provide instructions or point to the relevant documentation? I found no way of opening my actual project without nuking `.ijwb` folder first

**Comment by ujohnny** [comment]
I assume this is resolved as of #6596, @tpasternak wdyt?

**Comment by tpasternak** [comment]
Yeah, I think so

**Comment by Krechals** [comment]
I'm still experiencing the issue in:

```
IdeaUltimate: 2024.3.1
Platform: Ubuntu 20.04
Bazel for IntelliJ plugin: v2024.11.19-rc-1
Bazel: 6.5
```
