### ISSUE TITLE
Unable to build ASWB locally on mac

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/intellij#6426]
### Description of the bug:

This commit https://github.com/bazelbuild/intellij/commit/094215013d3c8d8c20056bd7674cd916c2cbe57a introduces the following build error:

```
ERROR: /intellij/aspect/BUILD:79:8: Executing genrule //aspect:create_intellij_info_impl_bundle failed: (Exit 1): bash failed: error executing Genrule command (from target //aspect:create_intellij_info_impl_bundle) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
sed: -e: No such file or directory
Target //aswb:aswb_bazel_zip failed to build
```

### Which category does this issue belong to?

Android Studio

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Can be produced by running `bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-oss-latest-stable`

**Comment by dkashyn-sfdc** [comment]
https://github.com/dkashyn-sfdc/intellij/commit/75a712485efe0b9365f76f3ddd7017e886f75a6e caused this. 

Probably it is happening not with all of Bazel versions and `.bazelversion` is not there so hard to say what Bazel version is required for `ijwb`
