### ISSUE TITLE
feat: support --remote_download_outputs=minimal

### ISSUE THREAD

**Issue by rbtcollins** [bazelbuild/intellij#6456]
### Description of the feature request:

We use --remote_download_outputs=minimal with remote build to avoid downloading large blobs unnecessarily. However intellij users found that project syncing left unresolved symbols until we disabled that, leaving `--remote_download_outputs` set to the default.

I'm not familiar enough with the bazel internals here to suggest resolution, but supporting configurations with this flag would be great.

### Which category does this issue belong to?

Intellij

### What underlying problem are you trying to solve with this feature?

Allow developers using IntelliJ to do so without needing a custom bazelrc for them.

### What operating system, Intellij IDE and programming languages are you using? Please provide specific versions.

Ubuntu 24.04, IntelliJ IDEA 2024.1.2, Kotlin

**Comment by tpasternak** [comment]
I think you could try with `toplevel` (and maybe tweaking `targets` in the project view file). But the way it would be pretty cool if bazel had another setting - `direct_deps` that would download toplevel targets and their direct deps

**Comment by rbtcollins** [comment]
Yah - toplevel works. We have a wrapper program around bazel, and we're using that to detect intellij and inject ...=toplevel instead of our minimal default; this seems to be working nicely.

**Comment by tpasternak** [comment]
So I'm going to close it now, feel free to reopen in case of further problems. Btw everything might with the introduction of the Bazel Output Service protocol
