### ISSUE TITLE
CI check failure on Google branch

### ISSUE THREAD

**Issue by tanishktyagii** [bazelbuild/intellij#6457]
### Description of the bug:

We have CI check failure below which is a blocker for Release for this week. Could you please have a look ?

[buildkite/android-studio-plugin - Build #21935 failed (5 seconds)](https://buildkite.com/bazel/android-studio-plugin/builds/21935)

### Which category does this issue belong to?

Android Studio

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1.Open https://github.com/bazelbuild/intellij/tree/google
2.Click on the checks, failures can be seen.

### Any other information, logs, or outputs that you want to share?

https://screenshot.googleplex.com/rYCzdSzHYERMGpq<img width="1723" alt="Screenshot 2024-06-04 at 11 49 19 AM" src="https://github.com/bazelbuild/intellij/assets/144092358/8e652cdf-f25f-46be-b7b3-7ed2ee4391fb">

**Comment by tpasternak** [comment]
Again, looks like a network issue

**Comment by sgowroji** [comment]
Thanks @tpasternak. We will initiate the release.
