### ISSUE TITLE
"invalid load syntax" when loading rules from external git repository

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/intellij#65]
I'm getting error when loading a rule from external repository:
![image](https://cloud.githubusercontent.com/assets/2962963/23953489/6469c7b2-099d-11e7-902a-c509b6d98442.png)

Full error text: 

> Invalid load syntax: missing Skylark module.

Might be related to issue #13 . 

**Env:**
- mac os X 10.12.3
- Bazel 0.4.4
- IntelliJ 2016.3.5
- IntelliJ Bazel plugin 2017.02.27.3.

I configured the external repository `@io_bazel_rules_scala`  as `git_repository` in the workspace file.
![image](https://cloud.githubusercontent.com/assets/2962963/23953674/f8c7dee4-099d-11e7-978f-7d94eb7a0911.png)

bazel runs without problems from the shell.

**Comment by brendandouglas** [comment]
Thanks for letting us know. This is fixed for the next release, which should arrive in around two weeks -- we've added a lot more external workspace (and WORKSPACE file) support (e.g. syntax highlighting in WORKSPACE files, navigation/find usages for external workspace targets).

**Comment by or-shachar** [comment]
Great! Thanks @brendandouglas !
