### ISSUE TITLE
Correct handling of `imports` rule attribute on `py...` rules

### ISSUE THREAD

**Issue by andponlin-canva** [bazelbuild/intellij#6599]
### Description of the bug:

**Note:** See the associated [PR](https://github.com/bazelbuild/intellij/pull/6606).

I have marked all IDEs because I assume they will all experience the same problem when handling Python targets.

Some of the `rules_python` rules such as `py_library` and `py_binary` have the ability to supply an `imports` attribute. For example consider the following Bazel repo setup;

```
//
├── WORKSPACE
└── aaa
    └── bbb
        └── ccc
            ├── BUILD.bazel
            ├── ddd
            │   └── eee
            │       ├── doo.py
            │       └── fff
            │           └── poe.py
            └── zzz
                └── main.py
```

The `BUILD.bazel` may carry the following rule;

```
py_library(
    name = "lib",
    srcs = [
        "ddd/eee/doo.py",
        "ddd/eee/fff/poe.py",
    ],
...
)
```

At the point of use in `main.py`, some Python library functions in those files would be;

```
from aaa.bbb.ccc.ddd.eee.doo import print_fruit
from aaa.bbb.ccc.ddd.eee.fff.poe import print_tree
```

If the rule is changed to introduce the `imports` attribute...

```
py_library(
  name = "lib",
...
  imports = ["ddd"]
...
)
```

...then the associated Python module path is rooted at the same point as the `BUILD.bazel` file and includes the `imports`. At the point of use in `main.py`, the reference to the library functions would become;

```
from eee.doo import print_fruit
from eee.fff.poe import print_tree
```

The expected behavior of the Intelli-J plugin would be to identify the use of `imports` attribute in `py_...` rules and to adjust the module paths accordingly. The actual behavior seems to be to ignore the `imports` attribute.

Changes in can be made to support the `imports` feature. The data from the `imports` attribute needs to be fed through from the executed aspect via the proto and can then be post-processed in `AbstractPyImportResolverStrategy` to replicate the observed behavior of Bazel.

### Which category does this issue belong to?

Intellij, GoLand, CLion, PyCharm, Android Studio

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please find attached a tar-ball [`support-py-imports-example-20240729.tgz`](https://github.com/user-attachments/files/16407837/support-py-imports-example-20240729.tgz).

1. Unpack the tar-ball
2. Ensure that it can be run with `bazelisk run "//aaa/bbb/ccc:prog"`. On output you should see;
    ```
    Feijoa
    Rimu
    ```
3. Now import the project into Intelli-J.
4. Sync the project
5. Open the `BUILD.bazel` file
6. Observe the `imports` is set to `ddd`
7. Open the file `main.py`
8. Observe that the imports are highlighted as errors in the IDE
9. Adjust the imports' paths to be;
    ```
    from aaa.bbb.ccc.ddd.eee.doo import print_fruit
    from aaa.bbb.ccc.ddd.eee.fff.poe import print_tree
    ```
10. Observe that the imports are no longer highlighted as errors in the IDE

The Intelli-J plugin should be accepting the paths in consideration of the `imports`.

### Which Intellij IDE are you using? Please provide the specific version.

Intelli-J 2024.1

### What programming languages and tools are you using? Please provide specific versions.

Python 3.10

### What Bazel plugin version are you using?

7.2

## Screenshots

Screenshot before without the patch in place;

<img width="256" alt="support-py-imports-example-before" src="https://github.com/user-attachments/assets/d7cab9d4-d576-4b7d-9f90-f3094a2922a6">

Screenshot after with the patch in place;

<img width="256" alt="support-py-imports-example-after" src="https://github.com/user-attachments/assets/58038224-be66-4610-80ad-baeeade6c6ff">

## Further known issue

There is a further complication that occurs when intermediate module parts are empty. For example;

```
//
└── a
    └── b
        └── c
            ├── BUILD.bazel
            └── d
                └── e
                    └── f
                        └── doo.py
```

If the `imports` here were `["d"]` then the IDE plugin would fail to recognize the module part `e` because it does not contain anything. This issue does not cover this scenario; it is considered to be a separate issue.

**Comment by andponlin-canva** [comment]
PR merged - thanks. Closing this issue.

**Comment by aarontsharp** [comment]
@andponlin-canva I think this may also resolve https://github.com/bazelbuild/intellij/issues/350 🎊

**Comment by andponlin-canva** [comment]
Hello @aarontsharp ; From a quick read of that issue, I suspect it may be due to the problem I outlined above under "Further known issue" rather than the plugin not observing the `imports` rule attribute?

**Comment by aarontsharp** [comment]
Hmm, I pulled the example included in #350 [here](https://github.com/hsestupin/bazel-python-source-root) and it seems to be working when using the plugin including this fix. My understanding of that issue is it's caused by the plugin only considering imports from the root of the workspace rather than the `imports` statement, which I believe this fix addresses.

The further issue you bring up may also be in scope, but at least the example shared in the issue seems to be resolved by this fix

**Comment by andponlin-canva** [comment]
Thanks; OK it is good to hear it has resolved that problem too!

**Comment by tpasternak** [comment]
This contribution is great, thank you @andponlin-canva !
