### ISSUE TITLE
Resolving Symbols from External Bazel Projects

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/intellij#66]
I'm having an issue resolving symbols from external Bazel projects:
![image](https://cloud.githubusercontent.com/assets/9574750/24073191/dce3b8e6-0bc9-11e7-81b2-bc1c39684a64.png)

I've tried configuring the external project in my workspace file using the git_repository and local_repository rules, both have the same issue:
![image](https://cloud.githubusercontent.com/assets/9574750/24073193/e4f4ad42-0bc9-11e7-8f77-dd4980530b84.png)

However, Bazel builds without errors.

Env:
Arch Linux
IntelliJ IDEA 2016.3.5
Bazel 0.4.4
Bazel Plugin 2017.02.27.3

Thanks!

**Comment by brendandouglas** [comment]
Is that class covered by the 'targets' in your .bazelproject file?

Anything not in the transitive closure of those targets won't be resolved, so in this case, you'll need to include in your .bazelproject file (Bazel > Open Local Project View File) a java_binary / java_library Bazel target associated with that main class.

**Comment by Dig-Doug** [comment]
Yes, the Main class (first picture) is covered under the targets section of my .bazelproject. The Controller class is in the external bazel project ("multikinect") and is listed as a dependency of the Main class in its java_binary rule.

When I import a dependency using maven_jar, the IDE is able to resolve classes properly. Should external bazel dependencies (using git_repository and local_repository) work the same way?

I created a simple repo that replicates my issue here: https://github.com/Dig-Doug/externalbazeltest

If you open mainproject in Intellij and look at com.example.main.Main, you'll see that the class (ImmutableList) from the maven dependency is resolved properly but the class (TestClass) from the bazel dependency is not. The project should still build and run correctly.

Thanks!

**Comment by brendandouglas** [comment]
Thanks for the excellent repro steps.

It's a bug in our handling of external libraries. I'll fix it up for the next release (v2017.04.03+).

**Comment by pmbethe09** [comment]
In v2017.04.03+ this appears fixed for compilation, however is there a way to attach src?

When browsing a WORKSPACE dep, idea uses the de-compiler, rather than just the actual source which is there on disk.

**Comment by brendandouglas** [comment]
@pmbethe09 could you please expand on that -- what kind of WORKSPACE dep is it, what actions did you use to browse to the dep, etc.?

**Comment by pmbethe09** [comment]
... hmm, when I went to reproduce (clicking F4 on the class name), it was the decompiled .class, but...  it had this nice clickable link
"Analyze blaze source jars"
which when I clicked on, produced the source.

**Comment by brendandouglas** [comment]
Great, that's what it should do!
