### ISSUE TITLE
Correct handling of debugging of `py_binary` targets when there is a transition

### ISSUE THREAD

**Issue by andponlin-canva** [bazelbuild/intellij#6600]
### Description of the bug:

**Note:** Please see associated PR [here](https://github.com/bazelbuild/intellij/pull/6605).

I have marked all IDEs because I assume they will all experience the same problem when handling Python targets but am only testing with Intelli-J.

When using a pinned Python interpreter, the expected behavior is that any `py_binary` targets that use the pinned interpreter will continue to be able to be debugged. The actual behavior is that the `py_binary` that uses the pinned interpreter is no longer able to use the debugger features in the IDE.

This problem is happening because the Rule type comes through from the aspect as `_transition_py_binary` and the logic in the plugin does not recognize this as a `py_binary`.

### Which category does this issue belong to?

Intellij, GoLand, CLion, PyCharm, Android Studio

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please find attached an example project 
[`handle-rule-transitions-example-20240729.tgz`](https://github.com/user-attachments/files/16408222/handle-rule-transitions-example-20240729.tgz).

1. Unpack the tar-ball
2. Run the binary with `bazelisk run ":bin"` and observe the output text `Heizung`.
3. Open the workspace in the Intelli-J IDE with the Bazel plugin installed
4. Open `BUILD.bazel` and right click on the `bin` target.
5. Choose "Debug..."
6. Edit the configuration
7. Change "Bazel command:" to `run`
8. Click OK
9. Observe that the option to debug is showing as disabled

It should be the case that this `py_binary` is able to be debugged.

### Which Intellij IDE are you using? Please provide the specific version.

Intelli-J 2024.1

### What programming languages and tools are you using? Please provide specific versions.

Python 3.10

### What Bazel plugin version are you using?

Recent

### Any other information, logs, or outputs that you want to share?

Screenshot without the patch;

<img width="128" alt="handle-rule-transitions-example-before" src="https://github.com/user-attachments/assets/5906fc27-d8c9-4baa-9430-1f25c6c320d3">

Screenshot with the patch noting that the debug is now enabled;

<img width="128" alt="handle-rule-transitions-example-after" src="https://github.com/user-attachments/assets/b50acdc6-66e9-4b1f-979b-4cc285a4f534">

**Comment by andponlin-canva** [comment]
Change merged - thanks.

**Comment by tpasternak** [comment]
Thank you for the contribution!

**Comment by tpasternak** [comment]
@andponlin-canva the problem I described in the comments above seems to be a rules_python issue, I thought you might be in interested https://github.com/bazelbuild/rules_python/issues/2114

**Comment by rickeylev** [comment]
Just to clarify a comment from the PR:

> The root cause is the pinned rule exports `@@rules_python//python/private/common:providers.bzl%PyInfo` instead of PyInfo

This is, long term, WAI. The builtin PyInfo symbol will be dropped in favor of the symbol in `@rules_python`. The intellij plugin should be updated to recognize both.

**Comment by andponlin-canva** [comment]
@rickeylev;

> This is, long term, WAI. The builtin PyInfo symbol will be dropped in favor of the symbol in @rules_python. The intellij plugin should be updated to recognize both.

I don't see any further changes required in the scope of this specific PR for handling of the `rules_python` (Starlark native) `PyInfo` verses the Bazel built-in `PyInfo`; both should work OK here or do you see further handling being required?
