### ISSUE TITLE
Add build folder action to plugin

### ISSUE THREAD

**Issue by kitbuilder587** [bazelbuild/intellij#6613]
### Description of the feature request:

You can't build folder, you can only sync it. Building could be much faster. For example in our project sync of entire folder takes x2 time more than build. I've already added this feature to my local Bazel plugin. I've added button to compile directory below the partial sync. 
<img width="338" alt="image" src="https://github.com/user-attachments/assets/41b80dbd-088b-4f5d-a4f2-c170d628cb55">

It would be great if we can contribute it

### What underlying problem are you trying to solve with this feature?

Faster build to check compile errors without sync

**Comment by tpasternak** [comment]
Closed with #6615
