### ISSUE TITLE
"Don't build unnecessary jars" causes built-with-aspect failure

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#6614]
### Description of the bug:

https://github.com/bazelbuild/intellij/blob/78303d50d61874150c68378544df5de153384310/aspect/intellij_info_impl.bzl#L789-L802

In line 789 we assume that `java_outputs` is an iterable (it is a List), while in the other place, in line 801 we assume it has an attribute named `jars`. Hence, it is impossible to import even this repository (bazelbuild/intellij). It results in 

```Error: 'list' value has no field or method 'jars'```

**Comment by tpasternak** [comment]
cc @nkoroste

**Comment by nkoroste** [comment]
Related to https://github.com/bazelbuild/intellij/pull/5515
The fix should be simple

**Comment by tpasternak** [comment]
Yeah, but how it was working for you? Will it work if we just change `java_outputs.jars` to `java_outputs`?

**Comment by nkoroste** [comment]
Honestly I don't remember anymore, this PR took so long to get it. All existing and new tests are passing in this public repo on this PR. 

Did you inspect the output of `java_outputs` in the passing and failing case? Curious to see how it looks like and why you guys are only hitting it internally if I'm understanding it right.

**Comment by tpasternak** [comment]
so `java_outputs` is just a list. Is it possible that in your case the condition `if len(source_jar_artifacts) == 0 or len(jar_artifacts) == 0:` is never satisfied?

**Comment by nkoroste** [comment]
> so `java_outputs` is just a list. Is it possible that in your case the condition `if len(source_jar_artifacts) == 0 or len(jar_artifacts) == 0:` is never satisfied?

Yep that could be it. 

p.s. thanks for the fix!
