### ISSUE TITLE
Scala SDK needs to be set after every sync 

### ISSUE THREAD

**Issue by enforser** [bazelbuild/intellij#6628]
### Description of the bug:

This is happening consistently in our project, which is a large monorepo using bazel w/ Scala. 

When we first setup the project in IntelliJ we are prompted to "Setup Scala SDK": 
<img width="1077" alt="Screenshot 2024-08-08 at 10 57 03 AM" src="https://github.com/user-attachments/assets/79cd83dd-2dde-4b35-b910-7a2b457889e9">

Setting the version works and the prompt goes away until the next time I sync a target. That seems to reset back to where IntelliJ prompts for the SDK again. 

We had forked an old version (multiple years old) of the plugin and had a fix there. I believe the cause is that in our project the Scala library does not have the same name being expected by the plugin. We are using bazel-deps to resolve our scala-library dependency. The way it is resolve, the library does not start with `scala-library*`, as expected [here](https://github.com/bazelbuild/intellij/blob/master/scala/src/com/google/idea/blaze/scala/sync/BlazeScalaSyncPlugin.java#L73). Instead, it begins with `org_scala_lang_scala_library`. 

Would you be open to a PR that adds `org_scala_lang_scala_library` as another match for identifiying the scala library? 

### Which category does this issue belong to?

Intellij

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2024.2, but have repro'd with many older versions as well

### What programming languages and tools are you using? Please provide specific versions.

Scala 2.13.11

### What Bazel plugin version are you using?

2024.07.16.0.1-api-version-242, but this has been an issue for a long time

**Comment by enforser** [comment]
I went ahead and made a PR for if this is accepted: https://github.com/bazelbuild/intellij/pull/6629

**Comment by mai93** [comment]
Closing as PR is merged
