### ISSUE TITLE
bzlmod: correct code marked as wrong

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#6632]
### Description of the bug:

![image](https://github.com/user-attachments/assets/53809205-0d39-4dd9-9921-74ede6289c84)

**Comment by iancha1992** [comment]
@tpasternak Are you the one working on this?

**Comment by tpasternak** [comment]
No, I'm not, unfortunately. I just found it today

**Comment by tpasternak** [comment]
Duplicate of #6308

**Comment by tpasternak** [comment]
Closing as duplicate
