### ISSUE TITLE
GoLand plugin breaks PR template population

### ISSUE THREAD

**Issue by SpencerC** [bazelbuild/intellij#6633]
### Description of the bug:

This functionality does not work in Bazel projects: https://www.jetbrains.com/help/go/work-with-github-pull-requests.html#create-pull-request

Also tracking here: https://youtrack.jetbrains.com/issue/IJPL-158871?replyTo=27-10180176

### Which category does this issue belong to?

Intellij, GoLand

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://bazelbuild.slack.com/archives/C025SBYFC4E/p1722987863389869

### Which Intellij IDE are you using? Please provide the specific version.

GoLand 2024.1.4

### What programming languages and tools are you using? Please provide specific versions.

Go

### What Bazel plugin version are you using?

 2024.07.16.0.1-api-version-241

### Have you found anything relevant by searching the web?

No

**Comment by tpasternak** [comment]
I'm closing as this is rather a GoLand issue and should be tracked in YouTrack. Apart from that, it is very likely to be fixed in 2024.2
