### ISSUE TITLE
Incompatible: requires IDE build 241.* or earlier

### ISSUE THREAD

**Issue by anonrig** [bazelbuild/intellij#6647]
Intellij plugin is incompatible with the latest release of Clion 2024.2

Build #CL-242.20224.384, built on August 13, 2024

![image](https://github.com/user-attachments/assets/d326555f-13f2-41fe-8ce3-cc96c6d89fce)

**Comment by tpasternak** [comment]
@anonrig thanks for the report, how did you install the plugin?

**Comment by anonrig** [comment]
Through clion plugin marketplace

**Comment by tpasternak** [comment]
But did you download the plugin manually, or just clicked "install" in the plugins page?

**Comment by tpasternak** [comment]
I recommend uninstalling and reinstalling the plugin. We build separate bundles for version 2024.2 (suffix -242) and version 2024.1 (corresponding suffixes). If you do it from inside CLion, the right one will be selected.

**Comment by anonrig** [comment]
uninstalling and reinstalling the plugin works, but before the last clion update, it was working correctly. i assume something went wrong and forced me to use a separate bundle.
