### ISSUE TITLE
Bazel include with namespace doesn't work

### ISSUE THREAD

**Issue by anonrig** [bazelbuild/intellij#6648]
### Description of the bug:

- Clone github.com/cloudflare/workerd
- Open clion as bazel project
- Use BUILD.bazel
- Sync
- Go to `src/workerd/api/node/buffer.h`

![image](https://github.com/user-attachments/assets/6befdfcc-177a-4ae8-a4e3-432450ef54b6)

The recommendation is correct. The file has `#include <workerd/jsg/jsg.h>` but still `src/workerd` prefix is needed in include to resolve this macro correctly.

### Which category does this issue belong to?

Intellij

### Which Intellij IDE are you using? Please provide the specific version.

Clion 2024.2

### What programming languages and tools are you using? Please provide specific versions.

ts,js,c++,python,rust

### What Bazel plugin version are you using?

latest

**Comment by LeFrosch** [comment]
Should be addressed by #6759
