### ISSUE TITLE
Compilation failure information not visible in CLion

### ISSUE THREAD

**Issue by sherm1** [bazelbuild/intellij#67]
I modified some code in a test, right clicked on the file in project view and selected "Run". Something went wrong and I got this not-very-helpful message:
<img width="1121" alt="inclion" src="https://cloud.githubusercontent.com/assets/4088016/24380573/ea981a0c-1300-11e7-8f82-ded881336f9d.png">

I repeated this using a command line and got this much-more-useful message showing what I messed up:
<img width="1691" alt="commandline" src="https://cloud.githubusercontent.com/assets/4088016/24380601/0d6f5298-1301-11e7-86e5-6b534bc20f49.png">

It looks like the error messages got sent somewhere else in CLion. It would be very nice to be able to see them!

BTW, the Bazel CLion plugin is really great -- thanks for the hard work.

**Comment by sherm1** [comment]
P.S. I hunted through Tool Windows and found the error messages on the Run window in CLion which was hidden. Could that be displayed in addition to the Blaze Problems window?

**Comment by brendandouglas** [comment]
Bazel doesn't (yet) provide structured output here, so we're forced to rely on parsing stdout. For multi-line errors like this one, there's no reliable way of determining where the error output ends (and non-error stdout resumes), so the problems view only shows the first line of the error, as you mentioned.

At the moment, the only workaround is the one you mention -- referring back to the raw output, in the run/debug or 'Blaze console' windows.

Bazel has plans to provide more structured output which can be used by the IDE in cases like these. When that's in place, we can revisit this.

**Comment by brendandouglas** [comment]
Turns out Bazel does not in fact have plans for more structured error output, which makes better plugin-side support infeasible.

Closing this for bug hygiene reasons, but please feel free to open a feature request on Bazel's issue tracker.
