### ISSUE TITLE
Ease task of modifying IJ plugin .proto files

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/intellij#674]
As an experiment to address #350 , I want to experiment with the IJ plugin and begin surfacing the `imports` keyword from Starlark (via `PyInfo`) to the IJ plugin's resolution code. I need to tweak the plugin's `IntellijIdeInfo.PyIdeInfo` struct, but it comes from a precompiled `proto_deps.jar`, so I have no (easy) way to modify it.

As an open source project, it'd be nice if the IJ plugin was amenable to regenerating sources from .proto changes, even if just a limited set like `proto/intellij_ide_info.proto`.

#### Notes
- I grafted in Bazel 0.24.1 as a remote repository so that I was able to rebuild the other targets named in //proto/BUILD (ex: libintellij_ide_info_proto-speed.jar). However, I'm still missing things like the "repackaged" com.google.protobuf classes.

**Comment by brendandouglas** [comment]
We'd like to remove the checked-in jar entirely, and just generate the repackaged jar at runtime.

The only reason there are checked in jars is because the repackaging tool we use is internal, and not so easy to pull in here (and other places we mirror our project, such as android studio's repo).

**Comment by drudim** [comment]
@beasleyr-vmw working on exactly the same problem. As a workaround, decided to use the shortest path to `__init__.py` under `srcs` definition as a source directory. See the changes here: https://github.com/drudim/intellij/commit/5daf95776a56e092a1bfaed241d69a88f7d2c8af

**Comment by comchi** [comment]
any updates on this? Do you have any plans to remove check-in jar in a nearest time?

**Comment by c4urself** [comment]
@beasleyr-vmw -- any thing we can help with here?

**Comment by c4urself** [comment]
Getting the PyInfo['imports'] data would be a game changer for Python devs on IntelliJ that use Bazel

**Comment by greenboxal** [comment]
I have successfully modified the proto build so it doesn't depend on anything precompiled, ymmv as I'm not focused yet on a full PR, but if anyone wants to extract the necessary modifications, here is the PR: https://github.com/greenboxal/intellij/pull/1

Beware it has other unrelated changes

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
