### ISSUE TITLE
Run .. with Coverage report not shown while testing Java Project

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#6764]
### Description of the bug:

While Testing Java Project coverage report is not shown while  testing Run .. with Coverage …however testing is getting passed.

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1> Import the Bazel project for Java 
2> Click “Run .. with Coverage …” and make sure that a coverage report is shown to the left of the screen as follows:

### Which Intellij IDE are you using? Please provide the specific version.

2024.1.6 & 2024.2

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2024.09.10.0.1-api-version-241 & 2024.09.10.0.1-api-version-242

### Any other information, logs, or outputs that you want to share?

![image](https://github.com/user-attachments/assets/ba277d45-d559-40ea-991a-80d97bafd606)

**Comment by mai93** [comment]
I think the culprit is https://github.com/bazelbuild/intellij/commit/9b268506f3ee615043ac24fa3a111cc7c7224dee, I confirmed that the coverage result is shown for a plugin built right before that one. @tpasternak @mtoader can you advice on this release blocker?

**Comment by mtoader** [comment]
That PR shouldn't affect coverage display but one never knows. Let me take a look.

**Comment by mai93** [comment]
it does touch `base/src/com/google/idea/blaze/base/run/coverage/CoverageUtils.java` so maybe it has something to do with that

**Comment by mtoader** [comment]
> it does touch `base/src/com/google/idea/blaze/base/run/coverage/CoverageUtils.java` so maybe it has something to do with that

That change should be a no-op, but I might have missed something. Let me investigate

**Comment by mtoader** [comment]
> > it does touch `base/src/com/google/idea/blaze/base/run/coverage/CoverageUtils.java` so maybe it has something to do with that
> 
> That change should be a no-op, but I might have missed something. Let me investigate

Oh, I know what it is. Will put a fix soon, once I validate. 

the change should be ` File coverageRoot = new File(blazeInfo.getOutputPath(), "_coverage");` not  `File coverageRoot = new File(blazeInfo.getOutputBase(), "_coverage");`

**Comment by mtoader** [comment]
@mai93 posted a fix PR.

**Comment by mai93** [comment]
Thanks @mtoader! The fix is released in 2024.09.10.0.2, @satyanandak you can continue the manual test with it.
