### ISSUE TITLE
Clarify role of ts_config_rule in documentation

### ISSUE THREAD

**Issue by BrentDouglas** [bazelbuild/intellij#68]
I have been trying to make the intellij plugin work with my typescript build. I think it would be great if the documentation for ts_config_rule (http://ij.bazel.build/docs/project-views.html#ts_config_rule) was expanded to explain what the rule needs to do in order to make IDEA pick up typescript files.

**Comment by BrentDouglas** [comment]
Ah, wait. I think I completely missread what the plugin was doing. I will remove the second half of that of this issue.

**Comment by brendandouglas** [comment]
The bazel plugin has only very rudimentary support for typescript -- the ts_config_rule is purely there as a convenience after you've already set up typescript support in IntelliJ (via custom BUILD rules, etc.).

During sync, we'll run whatever Bazel target it points to (which presumably will update typescript libraries).

We're looking at adding additional javascript / typescript support in the future, but for now it's very limited.

**Comment by BrentDouglas** [comment]
Oh, ok cool. I guess all I was looking for is getting it to pick up my type files from npm. It struck me after posting this that if I stick them in a srcjar rather than a tarball they will probably get picked up, right?

**Comment by ensonic** [comment]
A example of such a rule would be miost helpful. If you enable ts support in intellij and run into this the project sync will fail and you either must fix it on the spot or disable typescript support again.
