### ISSUE TITLE
Problems Building the Plugin on MacOS

### ISSUE THREAD

**Issue by andponlin-canva** [bazelbuild/intellij#6804]
### Description of the bug:

It was previously possible to build the Intelli-J / Bazel Plugin on MacOS but now this seems to be failing from `HEAD` (`d1bd4a8d65d0aa493f02b013a6da36336b313ddd`) on `master`. The command I am running is;

```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2024.1
```

The relevant error trace is;

```
In file included from external/abseil-cpp~/absl/base/log_severity.cc:15:
external/abseil-cpp~/absl/base/log_severity.h:18:10: fatal error: 'array' file not found
   18 | #include <array>
      |          ^~~~~~~
1 error generated.
Target //ijwb:ijwb_bazel_zip failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: **OBFUSCATED**/bazelbuild_intellij/aspect/tools/BUILD:10:13 Building aspect/tools/liblib.jar (6 source files) failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@abseil-cpp~//absl/log/internal:nullguard) external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 64 arguments skipped)
``` 

This problem unfortunately also impacts being able to build and debug the Plugin generally; so it is not possible to launch Intelli-J from the plugin project and work on it.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On a MacOS machine, checkout the source code for this project and attempt to build it with;

```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2024.1
```

### What Bazel plugin version are you using?

7.3.1

**Comment by tpasternak** [comment]
We have CI builds on Mac so it's would be quite hard to figure out. Pure guess but these things sometimes happen after OS compiler upgrades, could you try bazel clean --prune?

**Comment by andponlin-canva** [comment]
I have tried `bazel clean --expunge` and it does not seem to have resolved the problem unfortunately.

**Comment by tpasternak** [comment]
btw do you have full Xcode installation, or only the CLI tools?

**Comment by andponlin-canva** [comment]
Appologies; it looks like it's my computer that is at fault somehow.
