### ISSUE TITLE
Greeting Test Class is missing while testing for Java Project 

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#6895]
### Description of the bug:

Hi Team, 
We have observed that the Greetings Test class is missing while testing for Java Project in Intellij

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2024.1.6 and IntelliJ IDEA 2024.2.2

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2024.10.08.0.1-api-version-242 & 2024.10.08.0.1-api-version-241

### Have you found anything relevant by searching the web?

![Screenshot 2024-10-15 2 57 17 PM](https://github.com/user-attachments/assets/da5ffc8f-a570-4340-a5b0-6e9ef883598e)

**Comment by mai93** [comment]
you can find the test classes under `junit4` and `junit5` folders. Please make sure tests in all these classes pass

**Comment by satyanandak** [comment]
Noted ! 
However, fast run and fast debug failing for both Junit4 and Junit5 Greeting Test Class.

**Comment by tpasternak** [comment]
I have looked at that. For some reason, the fast test requires deploy jars to be built, while these targets don't do that

**Comment by tpasternak** [comment]
@satyanandak can you please help us with rules_java issue 230?

**Comment by tpasternak** [comment]
ok, I managed to move forward, when I tried rules_java 8.1.0, and added these flags https://github.com/bazelbuild/rules_java/blob/9a8d8f32acb98e6a77ab2c455d24683623b14960/.bazelrc

However it still couldn't find java in bzlmod (because of new paths)

**Comment by tpasternak** [comment]
ok, so the conclusion is:
1. merge this PR https://github.com/bazelbuild/intellij/pull/6901
2. bump rules_java to 8.1.0
3. use .bazelrc flags from here https://github.com/bazelbuild/rules_java/blob/9a8d8f32acb98e6a77ab2c455d24683623b14960/.bazelrc

**Comment by mai93** [comment]
so users need to have the flags in https://github.com/bazelbuild/rules_java/blob/9a8d8f32acb98e6a77ab2c455d24683623b14960/.bazelrc for fast test to work?

**Comment by tpasternak** [comment]
they need these flags to get rules_java 8.1.0 to work

**Comment by tpasternak** [comment]
and versions prior to 8.1.0 are broken

**Comment by tpasternak** [comment]
🤷

**Comment by mai93** [comment]
@satyanandak should we close this bug? or we still need to fix something

**Comment by satyanandak** [comment]
Sure @mai93 , closing this issue !
