### ISSUE TITLE
Bazel plugin no longer working in CLion 2017.1

### ISSUE THREAD

**Issue by sherm1** [bazelbuild/intellij#69]
I just updated to Clion 2017.1 and can no longer use the Bazel plugin. I get this message when I attempt to Import Bazel Project:
<img width="232" alt="fatal-bazel" src="https://cloud.githubusercontent.com/assets/4088016/24485690/f8e56ac2-14ba-11e7-852c-0ae8c8133c4a.png">

Any advice?

**Comment by brendandouglas** [comment]
Hi, the bazel plugins don't yet support 2017.1.

We generally wait for a week or two after it's first released before beginning the update process, as there are sometimes major bug fixes in that time.

We're planning to roll out 2017.1 internally in late April, and will upload corresponding Bazel plugins around the same time.

**Comment by sonicgg** [comment]
any update?

**Comment by brendandouglas** [comment]
There were major regressions in 2017.1, so we waited until 2017.1.1 was released, which pushed this back  a couple of weeks.

We should release a 2017.1 compatible plugin around around mid May.

**Comment by brendandouglas** [comment]
A CLion 2017.1.1-compatible release is now pending review in JetBrains' plugin repository. Should be available in a few days.
