### ISSUE TITLE
Build issue for Aspect Build on Mac

### ISSUE THREAD

**Issue by andponlin-canva** [bazelbuild/intellij#6917]
### Description of the bug:

When performing an aspect test on a Mac...

```
bazel test //aspect/testing/... --define=ij_product=intellij-latest
```

...the following error comes up...

```
1) testCoptsPrefinedMakeVars(com.google.idea.blaze.aspect.cpp.coptsmakevars.CoptsMakeVarsTest)
expected to contain a match for: ^-DPREFINED_BINDIR=(blaze|bazel)-out/[-0-9a-z]+/bin$
but was                        : -DPREFINED_BINDIR=bazel-out/darwin_arm64-fastbuild/bin
```

The regex does not match the Mac's `bazel-out` directory pattern.

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On a Mac run the command above and observe the error.

### What Bazel plugin version are you using?

7.3.2

**Comment by mai93** [comment]
fixed with https://github.com/bazelbuild/intellij/pull/6918
