### ISSUE TITLE
SHA256 checksums for 2019.1 archives are wrong

### ISSUE THREAD

**Issue by tdyas** [bazelbuild/intellij#696]
The SHA256 checksums in the WORKSPACE file for the CE and UE archives of IntelliJ 2019.1 are wrong. Downloading the archives manually using the URLs in the WORKSPACE file, I get the following checksums on macOS 10.14.3 using `sha256sum`:

URL: https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.1.1/ideaIC-2019.1.1.zip
Expected SHA256 from WORKSPACE: d05abcfd50673c542558bcbd2c4853386e1e45b72759b8ed9bd374b87dc3a391
Actual SHA256: 600bfa4e334d7a03162a04deb9849be210cd34318efd76d83473171f221a8d27

URL: https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2019.1.1/ideaIU-2019.1.1.zip
Expected SHA256 from WORKSPACE: ef1d578bdbcc0a61607c096057822bd2d1a00319daa5ef4550934c7ca7f6ba4d
Actual SHA256: 388fb1b31e0a22ac3acf7dcf9cfee76aa63bee2b1e0aa68dee52fac30c4196b4

How were the checksums in the WORKSPACE computed?

This error manifests when I try to build the 2019.1 version of the plugin:

```
$ bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-2019.1
Starting local Bazel server and connecting to it...
DEBUG: Rule 'io_bazel_rules_scala' modified arguments {"shallow_since": "1552264604 -1000"}
DEBUG: Rule 'io_bazel_rules_kotlin' modified arguments {"shallow_since": "1543417067 +0100"}
WARNING: /Users/tdyas/Code/bazelbuild-intellij/java/BUILD:177:1: in java_import rule //java:jdk_tools_jar: target '//java:jdk_tools_jar' depends on deprecated target '@local_jdk//:langtools': Don't depend on targets in the JDK workspace; use @bazel_tools//tools/jdk:current_java_runtime instead (see https://github.com/bazelbuild/bazel/issues/5594)
ERROR: /Users/tdyas/Code/bazelbuild-intellij/intellij_platform_sdk/BUILD:157:1: no such package '@intellij_ce_2019_1//': java.io.IOException: Error downloading [https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2019.1.1/ideaIC-2019.1.1.zip] to /private/var/tmp/_bazel_tdyas/3df4a685bdf85d40dde60d602eb75804/external/intellij_ce_2019_1/ideaIC-2019.1.1.zip: Checksum was 600bfa4e334d7a03162a04deb9849be210cd34318efd76d83473171f221a8d27 but wanted d05abcfd50673c542558bcbd2c4853386e1e45b72759b8ed9bd374b87dc3a391 and referenced by '//intellij_platform_sdk:plugin_api_internal'
ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: Analysis failed
INFO: Elapsed time: 424.433s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (61 packages loaded, 1759 targets configured)
    Fetching @intellij_ce_2019_1; fetching 416s
    Fetching @intellij_ue_2019_1; fetching 414s
```

**Comment by brendandouglas** [comment]
Thanks, I'll fix this upstream. We have a script to download the SDKs internally which also calculates the hash.

Perhaps the hash has simply changed since April 18th -- I can't find any obvious bugs in the script, we haven't had issues with it in the past, it gives the correct results when I re-run it, and nothing else seems to have changed since I ran it last week.
