### ISSUE TITLE
CLion unit test gutter icon shows "nothing here"

### ISSUE THREAD

**Issue by ivan-golub** [bazelbuild/intellij#6981]
### Description of the bug:

Unable to run cc_tests (google tests or plain main function) from gutter icon. Same setup works with CMake
 
<img width="1390" alt="Screenshot 2024-11-08 at 2 28 48 PM" src="https://github.com/user-attachments/assets/b43dc4a9-569f-42b1-b0d0-0bd6f1b73fc2">

### Which category does this issue belong to?

CLion

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Import bazel project -> examples/cpp/simple_project/proj.bazelproject. 
2. Wait until loading and indexing completes
3. Navigate to lib/greeting_test.cc
4. Try to press gutter "play" button

### Which Intellij IDE are you using? Please provide the specific version.

2024.2.3

### What programming languages and tools are you using? Please provide specific versions.

C++, Bazel 7.4.0

### What Bazel plugin version are you using?

2024.10.22.0.1-api-version-242

**Comment by LeFrosch** [comment]
Maybe related to: https://youtrack.jetbrains.com/issue/CPP-36051

**Comment by connoranderson** [comment]
@LeFrosch I think you are correct. I'm seeing that with Nova enabled, the unit tests are not runnable. With Nova disabled, I can run / debug individual tests. It'd be nice to get Nova supported here as it supposedly is significantly faster than legacy, according to 2024.3 release notes.

**Comment by ghost** [comment]
I am seeing this issue again on clion2025.2.1 with bazel-for-clion-2025-08.04.

<img width="472" height="440" alt="Image" src="https://github.com/user-attachments/assets/5434caec-fe29-4607-87b3-4016b55dfbea" />

**Comment by ghost** [comment]
with nova disabled, the "test and run" options show up agian

<img width="500" height="240" alt="Image" src="https://github.com/user-attachments/assets/e31a8f31-b92e-4188-8041-0e95c0936ca4" />

**Comment by LeFrosch** [comment]
Thank you for submitting this. I'll take a look as soon as I find the time.

**Comment by LeFrosch** [comment]
@pinkfrog9 So I cannot reproduce the issue of the missing run configs. After I imported the ray project successfully, all the run configs where there (in Nova). However, I noticed an issue we have with make variables that initially kept me from properly importing the project. I am working on a workaround for this: #7896 

Did you had any problems importing the project when the run configs do not show up? 

<img width="1069" height="826" alt="Image" src="https://github.com/user-attachments/assets/b8ab92d0-1a63-454e-b720-385c20bfa98a" />

**Comment by ghost** [comment]
Thanks for the update.  So this might not be the bazel-plugin issue but more of my import of the ray project.
I did a fresh git clone and import the project bazel project by clicking through the guide and got some errors.
```
Loading: 0 packages loaded
INFO: Build option --test_env has changed, discarding analysis cache.
Analyzing: 495 targets (0 packages loaded, 0 targets configured)
Analyzing: 495 targets (64 packages loaded, 73 targets configured)
Analyzing: 495 targets (231 packages loaded, 10617 targets configured)
Analyzing: 495 targets (328 packages loaded, 25304 targets configured)
Analyzing: 495 targets (330 packages loaded, 26404 targets configured)
WARNING: Target //src/ray/common/tests:memory_monitor_test is incompatible and cannot be built, but was explicitly requested.
WARNING: Target //src/ray/gcs/store_client/tests:chaos_redis_store_client_test is incompatible and cannot be built, but was explicitly requested.
WARNING: Target //src/ray/object_manager/plasma/tests:mutable_object_test is incompatible and cannot be built, but was explicitly requested.
INFO: Analyzed 495 targets (330 packages loaded, 26527 targets configured).
 checking cached actions
INFO: Found 492 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[4,548 / 4,971] checking cached actions
ERROR: /Users/pinkfrog/Drive/dev/shed/ray/ray/src/ray/common/BUILD.bazel:3:15: Symlinking virtual headers for //src/ray/common:compat failed: missing input file '//src/ray/common:compat.h'
ERROR: /Users/pinkfrog/Drive/dev/shed/ray/ray/src/ray/common/BUILD.bazel:3:15: Symlinking virtual headers for //src/ray/common:compat failed: 1 input file(s) do not exist
ERROR: /Users/pinkfrog/Drive/dev/shed/ray/ray/src/ray/common/BUILD.bazel:3:15: //src/ray/common:compat, aspect //.clwb/aspects:intellij_info_bundled.bzl%intellij_info_aspect: missing input file '//src/ray/common:compat.h'
[5,083 / 5,085] Executing genrule @bazel_tools//tools/jdk:gen_include/jni.h; 0s remote-cache, darwin-sandbox
INFO: Elapsed time: 10.386s, Critical Path: 0.42s
INFO: 3 processes: 1 internal, 2 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
```

**Comment by LeFrosch** [comment]
@pinkfrog9 What's in your project view file, are you just using the default one? I had some success after this fix (#7897) by only importing the cpp subset:

```
directories:
  .

targets:
  //cpp/...
```

**Comment by dograt** [comment]
This issue is still present in Nova. I'm seeing it in my project. Any updates on a fix?

**Comment by ujohnny** [comment]
@dograt do you have it on every test or just on some? I recently noticed an issue that is being addressed in #8053, but it applies only to files with custom `main` specified. It’s possible to share logs with us via uploads.jetbrains.com.

**Comment by dograt** [comment]
@ujohnny It was for every test, but I'm unable to recreate after clearing my CMake cache files.

**Comment by IlyaShcherbakov-TomTom** [comment]
I have this consistently reproducible with `Nova.` This made me switch to `Classic Engine`, until it became too slow.
I am currently on `2025.3.4`

Sometimes it's fixed by right clicking on the file and selecting `Run All in...`, but that option is also not always available.
This makes `Nova` pretty much unusable

**Comment by ujohnny** [comment]
@IlyaShcherbakov-TomTom what test macro is used on the tests that have this issue? Also is the file containing the test included in `cc_test` or somehow else?

**Comment by IlyaShcherbakov-TomTom** [comment]
> what test macro is used on the tests that have this issue?

I think it's regardless of the macro. 
It defenetely happened with `TEST_F`.

> Also is the file containing the test included in cc_test or somehow else?

Not sure what you mean exactly. Is this `Bazel` ? 
We use `conan` and `CMake`. 

I just updated to `CL-261.22158.273`, turned `Nova` on and cleaned all the cache. 
For now it works, I'll try to monitor when it breaks.
