### ISSUE TITLE
CLion test summary is not available for succesful runs

### ISSUE THREAD

**Issue by ivan-golub** [bazelbuild/intellij#6982]
### Description of the bug:

Test run summary is not availabe when run with bazel (available with CMake)
<img width="1296" alt="Screenshot 2024-11-08 at 2 27 32 PM" src="https://github.com/user-attachments/assets/b4d44d58-3e79-408e-a69f-5c4cc29b50f7">

### Which category does this issue belong to?

CLion

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Import bazel project -> examples/cpp/simple_project/proj.bazelproject. 
2. Wait until loading and indexing completes
3. Navigate to lib/greeting_test.cc
4. Go to BUILD file
5. Run cc_test target

### Which Intellij IDE are you using? Please provide the specific version.

2024.2.3

### What programming languages and tools are you using? Please provide specific versions.

C++, Bazel 7.4.0

### What Bazel plugin version are you using?

2024.10.22.0.1-api-version-242

**Comment by ujohnny** [comment]
@ivan-golub so by default CLion does not show successfully passed tests, it was designed this way for some reason unclear to me. There's a 3rd icon in icons row that has to be pressed to get passed tests in the list as well.
