### ISSUE TITLE
Make command also under “Build” menu

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#7]
Currently the "Make project" command is under the "Bazel" menu.
I looked for it and didn't even notice a "Bazel" menu for the first few hours but luckily just noticed that the keyboard shortcut works and I used it. I looked for this command under the "Build" menu where it usually resides and I think adding it to there also can be great to lower surprises for new-comers.

**Comment by mai93** [comment]
We can review/accept a PR that fixes this.

**Comment by ittaiz** [comment]
Thanks @mai93 
Given a good few years have passed we have already gotten used to this.
I still think that devs moving from other tools (e.g. maven) would find this easier to work with.
Having said that I don't know how much time I'll have to contribute this given we have no need for it now (TBH our devs use now the sync button as sort of make)

**Comment by mai93** [comment]
Thank you @ittaiz, I just wanted to clarify that we are open for contributions on this from you or anyone else. I also expected that the plugin users got used to the current UI. I'll close the issue and if we get more requests about it we will reconsider it.
