### ISSUE TITLE
Unable to specify a `bazel test` Run Configuration with multiple specific targets

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/intellij#70]
I am running a suit of tests, and would like to use CLion to parse the compiler errors and ultimate program output. The functional equivalent of what I would like is something to the effect of:
```
$ cd drake/solvers
$ bazel test :equality_constrained_qp_solver_test :mathematical_program_test :moby_lcp_solver_test
```

If I specify this as a Run Configuration, and then specify the following as my Target expression:
```
//drake/solvers:equality_constrained_qp_solver_test //drake/solvers:mathematical_program_test //drake/solvers:moby_lcp_solver_test
```
I get the following error:
```
Error:ERROR: invalid target format '//drake/solvers:equality_constrained_qp_solver_test //drake/solvers:mathematical_program_test //drake/solvers:moby_lcp_solver_test': target names may not contain ' '
```

I believe this could be resolved if the individual arguments were permitted to be quoted separately, to still allow for generic patterns.

As a workaround, I am adding a temporary `test_suite` to my `BUILD` file.

**Comment by brendandouglas** [comment]
We don't support multi-target configurations yet. At the moment, the only workaround is the one you've found -- to use test_suites or similar.

You could also run '//drake/solver:all' if you wanted to run all the tests in that package, not just those three.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
