### ISSUE TITLE
external/intellij_aspect/intellij_info_impl_bundled.bzl:366:9: nested functions are not allowed. Move the function to the top level

### ISSUE THREAD

**Issue by hujianxin** [bazelbuild/intellij#7033]
### Description of the bug:

new version clion bazel plugin:

```
external/intellij_aspect/intellij_info_impl_bundled.bzl:366:9: nested functions are not allowed. Move the function to the top level
```

### Which Intellij IDE are you using? Please provide the specific version.

CLion

### What programming languages and tools are you using? Please provide specific versions.

c++

### What Bazel plugin version are you using?

2024.10.22.0.1-api-version-242 Download

**Comment by tpasternak** [comment]
Thank you for the report. Can you please share your bazel version?

**Comment by hujianxin** [comment]
@tpasternak bazel 4.2.4

**Comment by tpasternak** [comment]
Unfortunately we support only Bazel versions that are maintained by the Bazel team https://bazel.build/release

**Comment by LeFrosch** [comment]
Since Bazel 4 is no longer support I am going to close this issue. Feel free to reopen it, if you have similar issues with a supported Bazel version.
