### ISSUE TITLE
Bump Bazel 8 version

### ISSUE THREAD

**Issue by tpasternak** [bazelbuild/intellij#7058]
### Description of the bug:

This is just to track blockers, currently, we are blocked by this
- https://github.com/bazelbuild/rules_scala/issues/1652
- https://github.com/bazelbuild/bazel/issues/24543

**Comment by tpasternak** [comment]
Thanks @hvadehra , unfortunately, scala_doc.bzl also refers JavaInfo

**Comment by hvadehra** [comment]
I don't see any references to that file in this repository. Do you have a link to the failure you're seeing?

**Comment by tpasternak** [comment]
Sorry, my mistake, thanks

**Comment by hvadehra** [comment]
btw, since rules_scala depends on rules_java and is being used in a hybrid bzlmod+WORKSPACE mode, the full diff needed with Bazel 8 / Bazel@HEAD for now is:

```
$ git diff 
diff --git a/.bazelversion b/.bazelversion
index bf035f2b6..99078367a 100644
--- a/.bazelversion
+++ b/.bazelversion
@@ -1 +1 @@
-8.0.0rc2
+8.0.0rc6
diff --git a/WORKSPACE.bzlmod b/WORKSPACE.bzlmod
index 268e9e248..94b85f621 100644
--- a/WORKSPACE.bzlmod
+++ b/WORKSPACE.bzlmod
@@ -2,6 +2,12 @@ workspace(name = "intellij_with_bazel")
 
 load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 
+# Workaround for scala in this hybrid bzlmod+WORKSPACE mode
+load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")
+rules_java_dependencies()
+load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
+protobuf_deps()
+
 # LICENSE: The Apache Software License, Version 2.0
 rules_scala_version = "8f255cd1fecfe4d43934b161b3edda58bdb2e8f4"
 
@@ -17,7 +23,7 @@ load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")
 
 scala_config()
 
-load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
+load("@io_bazel_rules_scala//scala/private:macros/scala_repositories.bzl", "scala_repositories")
 
 scala_repositories()
```

**Comment by tpasternak** [comment]
well, it worked with the first patch, however we have a test for https://github.com/bazelbuild/bazel/issues/24543 so we have to disable it and reenable later https://github.com/bazelbuild/bazel/issues/24543

**Comment by hvadehra** [comment]
Interesting, I was basing that off https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4308#01938ab4-19c0-415e-a623-83cbcb4e4eb1
