### ISSUE TITLE
Kotlin testing running binary and tests, debugging doesn't stop at the break point added 

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#7066]
### Description of the bug:

While running binary and test for Kotlin Project, execution doesn't stop at the break point added. 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Open Project
Remove “examples” from v20YY.MM.DD/intellij/.bazelignore file
Open the IDE after installing the Bazel plugin you built
Select “Import Bazel Project”
Select v20YY.MM.DD/intellij as your workspace then click Next
Select “Import Project View File” and point it to v20YY.MM.DD/intellij/examples/kotlin/simple_project/simple_project.bazelproject then click Next.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2024.2 & 2024.3

### What programming languages and tools are you using? Please provide specific versions.

Kotlin

### What Bazel plugin version are you using?

2024.11.19.0.2-api-version-242 & 2024.11.19.0.2-api-version-243

### Any other information, logs, or outputs that you want to share?

![image](https://github.com/user-attachments/assets/be841d6a-d3ef-45d5-b2ab-c767ba916bb5)

**Comment by tpasternak** [comment]
ok, it's a bazel8-related problem

**Comment by satyanandak** [comment]
> ok, it's a bazel8-related problem

Sure @tpasternak, will it be fixed with the upcoming Bazel releases ?
