### ISSUE TITLE
Kotlin plugin not working with K2 Mode enabled

### ISSUE THREAD

**Issue by smocherla-brex** [bazelbuild/intellij#7121]
### Description of the bug:

K2 mode is considered stable https://blog.jetbrains.com/idea/2024/11/k2-mode-becomes-stable/ with IntelliJ 2024.3, but when enabling it on a project with the Bazel plugin, we keep running into a `Kotlin not configured` issue and features like syntax highlighting/autocomplete of the Kotlin plugin are broken even if a partial sync succeeds.

To rule out the issue being related to our repo, I created a simple repro here https://github.com/smocherla-brex/k2-intellij-bazel-bug with instructions.

It works in K1 mode, but not when K2 mode is enabled.

If I click on `Configure`, it adds the `KotlinJavaRuntime` library to the module and syntax highlighting works again but if I do a partial sync again, it gets removed again and I see `Kotlin not configured` errors. I saw that the Bazel plugin sets up the Kotlin facet in its setup, so wondering if K2 mode breaks something there?

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow instructions in https://github.com/smocherla-brex/k2-intellij-bazel-bug

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ 2024.3

### What programming languages and tools are you using? Please provide specific versions.

Kotlin (2.0), Bazel (6.4), rules_kotlin (2.0.0)

### What Bazel plugin version are you using?

2024.11.19.0.1-api-version-243

### Have you found anything relevant by searching the web?

Started a thread on Bazel slack https://bazelbuild.slack.com/archives/C025SBYFC4E/p1733361995492499 I checked on youtrack and Kotlin slack but couldn't find anything related to this.

### Any other information, logs, or outputs that you want to share?

I checked the IntelliJ logs, but there are no errors indicating any issues.

**Comment by tpasternak** [comment]
note: BlazeKotlinSyncPlugin is not even loaded when k2 is on

**Comment by smocherla-brex** [comment]
I suppose based on this https://kotlin.github.io/analysis-api/declaring-k2-compatibility.html
```
<extensions defaultExtensionNs="org.jetbrains.kotlin">
    <supportsKotlinPluginMode supportsK2="true" />
</extensions>
```
needs to be added here? https://github.com/bazelbuild/intellij/blob/master/kotlin/src/META-INF/kotlin-contents.xml#L16

> Even if the plugin does not use any of the old K1 analysis functions and no migration to the Analysis API is needed, compatibility with the K2 Kotlin plugin should be declared explicitly nonetheless.

The plugin doesn't use any of the Analysis APIs but it does need to declare its compatibility to it. If it's ok, I can open a PR for it?

**Comment by smocherla-brex** [comment]
Adding it in `kotlin-contents.xml` didn't work but adding it to `blaze-base.xml` works.  Let me know if this is the wrong place to add. https://github.com/bazelbuild/intellij/pull/7138

**Comment by tpasternak** [comment]
I think that blaze-kotlin.xml would be the right place.

kotlin-contents.xml is for things that are loaded optionally if the kotlin plugin is already loaded, while blaze-kotlin stuff is always present

**Comment by smocherla-brex** [comment]
Makes sense, it works when adding to `blaze-kotlin.xml`, I updated the PR.
