### ISSUE TITLE
"Compile Project" is failing

### ISSUE THREAD

**Issue by dkashyn-sfdc** [bazelbuild/intellij#7136]
### Description of the bug:

<img width="1683" alt="image" src="https://github.com/user-attachments/assets/0aea9ea1-632b-4202-b251-407417c8fdb9">

**Comment by sgowroji** [comment]
Hi @dkashyn-sfdc, Could you please provide complete steps to reproduce this issue?

**Comment by tpasternak** [comment]
@dkashyn-sfdc already fixed it in #7135, thank you!
