### ISSUE TITLE
Testing Kotlin Project - Debug doesn't stop at the break point 

### ISSUE THREAD

**Issue by satyanandak** [bazelbuild/intellij#7154]
### Description of the bug:

Hi Team,

While Testing Kotlin Project , debugger doesn't stop at line where breakpoint added and this is happening both for running binary and tests

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1) Open Project
2) Remove “examples” from v20YY.MM.DD/intellij/.bazelignore file
3) Open the IDE after installing the Bazel plugin you built
4) Select “Import Bazel Project”
5) Select v20YY.MM.DD/intellij as your workspace then click Next
6) Select “Import Project View File” and point it to 7)v20YY.MM.DD/intellij/examples/kotlin/simple_project/simple_project.bazelproject then click Next.
8) Open Project runner/Greeting Test class, add a breakpoint, click on Debug 

### Which Intellij IDE are you using? Please provide the specific version.

2024.2.5 & 2024.3

### What programming languages and tools are you using? Please provide specific versions.

Kotlin

### What Bazel plugin version are you using?

2024.12.03.0.2-api-version-242 & 2024.12.03.0.2-api-version-243

### Any other information, logs, or outputs that you want to share?

![image](https://github.com/user-attachments/assets/2ace2b59-13e6-4771-b1d5-9eb6b0766d9c)

**Comment by tpasternak** [comment]
FTR - I can't even execute `bazel run`  on the kotlin target
