### ISSUE TITLE
bazel build from cli passes, bazel build from clion fails

### ISSUE THREAD

**Issue by stu** [bazelbuild/intellij#7169]
### Description of the bug:

from CLI, bazel build //... works no errors. build in clion fails.

`error loading package 'external': the repository @@intellij_aspect does not exist, but has been specified as overridden with --override_repository. Use --inject_repository instead to add a new repository.
`

project fails to build.

### Which category does this issue belong to?

CLion

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

open the bazel repository examples/cpp-tutorial/stage3 in clion. hit build. fail.

### Which Intellij IDE are you using? Please provide the specific version.

clion 2024.3.1

### What Bazel plugin version are you using?

2024.11.19.0.3-api-version-243

**Comment by tpasternak** [comment]
Hi, can you please share the result of `bazel info release`?

**Comment by styurin** [comment]
Try this:

```
echo 7.1.2 > .bazelversion
```

and run the command again.

Bazel 8.0.0 was [released](https://github.com/bazelbuild/bazel/releases) 4 days ago. If you use Bazelisk, it will pick it up automatically unless Bazel version is configured explicitly.

**Comment by davidprueser** [comment]
Had the same issue using version 8.0.0. After downgrading to 7.1.2, everything worked fine again.

**Comment by ujohnny** [comment]
This is a bug in the plugin when a user migrates from bazel 7 to bazel 8. The workaround is to find a `projects/<your_project_name+somehash>` in IntelliJ/CLion [system directory](https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#system-directory) and remove it (or rename to `<name>.bak`).

**Comment by ujohnny** [comment]
oh, this seems to be more severe. working on it.
