### ISSUE TITLE
Support Android Studio 2.3

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/intellij#72]
When attempting to import an existing Bazel project using `File -> Import Bazel project`, I the import fails with some exceptions. I've pasted a couple of examples from the log: https://gist.github.com/kamalmarhubi/b96ef0ee18e8f96b3c7ba0b245992846

They both seem to be a result of some method not being found, either one of:
- `com.android.tools.idea.sdk.IdeSdks.getAndroidSdkPath()Ljava/io/File;`
- `org.jetbrains.android.sdk.AndroidSdkUtils.getAllAndroidSdks()Ljava/util/List;`

and in both cases, the immediate caller is in `com.google.idea.blaze.android.compatibility.Compatibility`:
- `com.google.idea.blaze.android.compatibility.Compatibility$AndroidSdkUtils.getAllAndroidSdks(Compatibility.java:53)`
- `com.google.idea.blaze.android.compatibility.Compatibility$IdeSdks.getAndroidSdkPath(Compatibility.java:69)`

Platform: Linux (Debian Stretch)
Plugin version:  v2017.02.27.3
Android Studio version: 2.3
JRE version: 1.8.0_112-release-b06

**Comment by brendandouglas** [comment]
The latest release doesn't support Android Studio 2.3 (only 2.2). Each new version contains plugin API changes, and we're in the process of rolling out support for 2.3.

Should be in the next release (v2017.04.03 onwards).

**Comment by kamalmarhubi** [comment]
Thanks for the update @brendandouglas. Looking forward to that release!

**Comment by kamalmarhubi** [comment]
Is this release coming any time soon? [Android Studio 2.4 preview is now out](https://developer.android.com/studio/preview/index.html), and ideally this plugin isn't over two releases old. :-)

**Comment by brendandouglas** [comment]
It's been submitted to the JetBrains plugin repo. It will likely arrive later this week.

**Comment by kamalmarhubi** [comment]
Thanks for the update @brendandouglas!
