### ISSUE TITLE
Checksum errors in Bazel CI

### ISSUE THREAD

**Issue by philwo** [bazelbuild/intellij#723]
Tests often fail on Bazel's CI with errors like this:

ERROR: /workdir/third_party/javascript/BUILD:7:1: no such package '@intellij_ue_2019_1//': java.io.IOException: Error downloading [https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2019.1.1/ideaIU-2019.1.1.zip] to /home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/external/intellij_ue_2019_1/ideaIU-2019.1.1.zip: Checksum was ef1d578bdbcc0a61607c096057822bd2d1a00319daa5ef4550934c7ca7f6ba4d but wanted 388fb1b31e0a22ac3acf7dcf9cfee76aa63bee2b1e0aa68dee52fac30c4196b4 and referenced by '//third_party/javascript:javascript_internal'
 
For whatever reason, the files provided by www.jetbrains.com do not have a consistent hash sum. If possible (not sure if we're allowed to?), I would recommend to mirror these artifacts on mirror.bazel.build to reduce the flakyness of your pipeline.

If you think it's fine, I can do the mirroring, just let me know.

**Comment by brendandouglas** [comment]
No idea whether it's OK to mirror it, or why we've only had this problem for this particular release.

Referencing the exact build number, rather than 2019.1.1, might be worth a try?

**Comment by philwo** [comment]
@dslomov @irengrig Do we know someone at JetBrains who could help us out here?

**Comment by irengrig** [comment]
Will try to reach to their people.

Irina Chernushina |  Software Developer |  ichern@google.com |


Google Germany GmbH

Erika-Mann-Straße 33

80636 München

Geschäftsführer: Paul Manicle, Halimah DeLaine Prado

Registergericht und -nummer: Hamburg, HRB 86891

Sitz der Gesellschaft: Hamburg

Diese E-Mail ist vertraulich. Falls sie diese fälschlicherweise erhalten
haben sollten, leiten Sie diese bitte nicht an jemand anderes weiter,
löschen Sie alle Kopien und Anhänge davon und lassen Sie mich bitte wissen,
dass die E-Mail an die falsche Person gesendet wurde.



This e-mail is confidential. If you received this communication by mistake,
please don't forward it to anyone else, please erase all copies and
attachments, and please let me know that it has gone to the wrong person.

**Comment by shalupov** [comment]
I found a corner case in our uploading procedure. Thanks for reporting it.
Currently checksum is `388fb1b31e0a22ac3acf7dcf9cfee76aa63bee2b1e0aa68dee52fac30c4196b4`

**Comment by divyekapoor** [comment]
If it helps anyone, here's a pre-built plugin you can install by Preferences -> Plugins -> Settings icon -> Install from Disk.

Built on my local machine. Works on Mac. Completely unsupported. Use as you would a random binary from the internet.
[ijwb_bazel.zip](https://github.com/bazelbuild/intellij/files/3159735/ijwb_bazel.zip)

**Comment by jin** [comment]
I believe this has been resolved.
