### ISSUE TITLE
BUILD file formatting sorts external deps idiosyncratically

### ISSUE THREAD

**Issue by david-german-tri** [bazelbuild/intellij#73]
The [buildifier binary](https://github.com/bazelbuild/intellij/blob/master/base/resources/binaries/bazel-buildifier) included with the plugin is a few months old.  On [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake), we've noticed that the plugin disagrees with an up-to-date version of https://github.com/bazelbuild/buildifier about the correct sort order for deps when some of the deps are WORKSPACE externals.

Modern buildifier:

```

drake_cc_library(
    name = "drake_visualizer_client",
    srcs = ["drake_visualizer_client.cc"],
    hdrs = ["drake_visualizer_client.h"],
    deps = [
        "//drake/lcmtypes:viewer",
        "//drake/math:geometric_transform",
        "//drake/multibody/shapes",
        "@eigen//:eigen",
    ],
)
```

Plugin buildifier:

```
drake_cc_library(
    name = "drake_visualizer_client",
    srcs = ["drake_visualizer_client.cc"],
    hdrs = ["drake_visualizer_client.h"],
    deps = [
        "@eigen//:eigen",
        "//drake/lcmtypes:viewer",
        "//drake/math:geometric_transform",
        "//drake/multibody/shapes",
    ],
)
```

**Comment by brendandouglas** [comment]
Thanks for letting us know -- we'll update to the latest version, or just stop bundling it, and reference that github project.

**Comment by ittaiz** [comment]
@brendandouglas is buildifier also available as an IntelliJ plugin?

**Comment by brendandouglas** [comment]
There is a buildifier plugin of sorts, but it doesn't include buildifier itself so isn't useful for the bazel plugin.
