### ISSUE TITLE
IJWB wants to attach aspect on generated file

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/intellij#74]
Trying to compile gerrit with a clean, local JGit checkout:

```
$ git diff origin/master HEAD 
diff --git a/lib/jgit/jgit.bzl b/lib/jgit/jgit.bzl
index 7b5acd81f8..47f2450167 100644
--- a/lib/jgit/jgit.bzl
+++ b/lib/jgit/jgit.bzl
@@ -10,7 +10,7 @@ _JGIT_REPO = GERRIT # Leave here even if set to MAVEN_CENTRAL.
 
 # set this to use a local version.
 # "/home/<user>/projects/jgit"
-LOCAL_JGIT_REPO = ""
+LOCAL_JGIT_REPO = "/usr/local/google/home/hanwen/vc/jgit"
 
 def jgit_repos():
   if LOCAL_JGIT_REPO:
```

The bazel build itself succeeds, but IntelliJ complains

/usr/local/google/home/hanwen/.cache/bazel/_bazel_hanwen/3dd1ab8ef3a0892fac2e8f719daba681/external/jgit/org.eclipse.jgit/BUILD
Error:(14, 1) @bazel_tools//tools/ide:intellij_info.bzl%intellij_info_aspect is attached to generated file libjgit-src.jar but aspects must be attached to rules.

this comes from a dependency chain
```
genrule2(
    name = "jgit_edit_src",
    outs = ["edit.srcjar"],
    cmd = " && ".join([
        "unzip -qd $$TMP $(location //lib/jgit/org.eclipse.jgit:jgit-source) " +
        "org/eclipse/jgit/diff/Edit.java",
        "cd $$TMP",
        "zip -Dq $$ROOT/$@ org/eclipse/jgit/diff/Edit.java",
    ]),
    tools = ["//lib/jgit/org.eclipse.jgit:jgit-source"],
)
```

//lib/jgit/org.eclipse.jgit:jgit-source -> 
```
alias(
    name = "jgit-source",
    actual = jgit_dep("@jgit_lib//jar:src"), # resolves to "@jgit//org.eclipse.jgit:libjgit-src.jar",
    visibility = ["//visibility:public"],
)
````

**Comment by hanwen** [comment]
I was going to complain that this was breaking something, but my real problem was caused by something else entirely, so this is low-priority.

**Comment by brendandouglas** [comment]
This is a general problem with bazel. There are some internal bazel-side bugs tracking this, @dslomov is looking into it I believe.

**Comment by brendandouglas** [comment]
Fixed for a future bazel release with https://github.com/bazelbuild/bazel/commit/fa50c3ddd67d835a134ea8da0cb9ba02fed704d1
