### ISSUE TITLE
java_proto_library not indexed by IntelliJ Bazel plugin

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/intellij#75]
Before Bazel released its own proto rules, I was using the third-party rules_protobuf proto rules. When I switched to the native proto rules, I discovered that my IDE (IntelliJ CE 2017.1 with Bazel plugin 2017.03.15.3) does not index the native java_proto_library targets, causing a lot of red squigglies, inability to navigate to proto gencode, etc.

Minimal repro: https://github.com/Ubehebe/java_proto_library_intellij_bug

I'm not sure if this is a bug in Bazel or the Bazel IntelliJ plugin, but either way, this will hinder adoption of the native java_proto_library rules.

(I initially filed this against Bazel [here](https://github.com/bazelbuild/bazel/issues/2827), but was told to file against this repo.) CC: @cgrushko

**Comment by cgrushko** [comment]
@tomlu

**Comment by brendandouglas** [comment]
The changes to support 'java_proto_library' never made it into the IntelliJ aspect bundled with Bazel (https://github.com/bazelbuild/bazel/blob/91d1ea0d1a1806b2f0fc9dd1f959b61e5ae1704e/tools/ide/intellij_info_impl.bzl).

I'll have a look at getting this in the next Bazel release.

**Comment by brendandouglas** [comment]
Actually, that's not right. The changes made it across to Bazel, they just weren't present in 0.4.5.

You could try building bazel from HEAD, or wait until the next release. Please reopen if it's also not working from HEAD.
