### ISSUE TITLE
Android Studio with Bazel plugin for 3.4 is not downloadable from within the IDE

### ISSUE THREAD

**Issue by jin** [bazelbuild/intellij#754]
AS Build: 183.5429.30.34.5452501

Plugin is available here, with the lowest supported version also being 183.5429.30.34.5452501: https://plugins.jetbrains.com/plugin/9185-bazel/update/61490

But the plugin is not available from within AS:

![aswb-missing](https://user-images.githubusercontent.com/347918/56998497-7cc4d500-6b79-11e9-832e-d9fb2d251bac.PNG)

**Comment by jin** [comment]
Discussed with @brendandouglas and reached out to JetBrains.

**Comment by jin** [comment]
From JetBrains:

```
Some IDEs send us 183.5429.30 build instead of 183.5429.30.34.5452501, that's why this update is not available for them. Now we are investigating why it happens.

If you can change the since version to 3-components builds, the plugin will be found in Android Studio. If the presence of five-component builds is important, you'll have to wait until we solve this issue.
```

Just so we're not blocked on upstream fixes, let's make a plugin build with 

```
<idea-version since-build="183.5429.30" until-build="183.*"/>
```

**Comment by mrk-han** [comment]
Still having trouble finding the plugin, do you know when the new plugin build will be available as the short-term fix?

**Comment by jin** [comment]
This is now fixed.

<img width="795" alt="Screenshot 2019-05-13 at 10 03 46 AM" src="https://user-images.githubusercontent.com/347918/57627680-7285dc00-7566-11e9-87bf-0e37b1e6b34c.png">
