### ISSUE TITLE
Debugger doesn't show correct variables in some scopes

### ISSUE THREAD

**Issue by daniellervik** [bazelbuild/intellij#78]
I'm running bazel in debug mode from IntelliJ and when hitting a break point inside some scopes, e.g. inside for loops, some variables isn't correct in the debugger. I'm uncertain which role this project has in this but I'm posting it here since it's at least related to my IntelliJ installation.

(B) indicates where breakpoint is located.

#### Assign variable inside indexed for loop
```
for (int i = 0; i < values.length; i++) {
    Integer valueFromIndex = values[i];
(B) System.out.println(i + " " + valueFromIndex);
}
```

This is kind of working, although a lot of `slot_N` is appearing in debugger which is somewhat noisy.

![indexed_for_loop](https://cloud.githubusercontent.com/assets/409708/25265345/d5972902-266c-11e7-9ed0-678c8eaa425d.jpg)

#### Iterator for loop
```
for (Integer value : values) {
(B) System.out.println(value);
}
```

`value` isn't available in "Evaluate expression" or debugger window. `values` is behaving as expected.

![simple_for_loop](https://cloud.githubusercontent.com/assets/409708/25265356/e90f77fa-266c-11e7-9c8d-73ca8b7f707c.jpg)

#### Reassign variable inside iterator for loop
```
for (Integer value : values) {
    Integer innerVariable = value;
(B) System.out.println(innerVariable);
}
```

`value` isn't available in "Evaluate expression" dialog. `innerValue` is same reference as `values` although it should be `value`.

![reassign_variable_for_loop](https://cloud.githubusercontent.com/assets/409708/25265362/f01b0bd6-266c-11e7-9d3d-2ec3bad5b62f.jpg)

**Comment by brendandouglas** [comment]
You can workaround this by adding these lines to your .bazelproject:

```
build_flags:
  --javacopt="-g"
```

That will cause slow bazel builds on the command line though (if the flag isn't present then), so adding it to your .bazelrc would be better.

I'm pretty sure the Bazel devs were intending to include debug information for all Java binaries by default -- I've filed https://github.com/bazelbuild/bazel/issues/2859 to remind them.

**Comment by daniellervik** [comment]
@brendandouglas Works! Would as you say be reasonable to include by default for java bins.

Thx for helping out!
