### ISSUE TITLE
Unable to debug java_binary targets with bazel 0.25

### ISSUE THREAD

**Issue by jordimac** [bazelbuild/intellij#783]
When using the latest plugin (v2019.04.15) with bazel 0.25, debugging a java_binary fails with:

```
ERROR: /private/var/tmp/.../external/intellij_aspect/java_classpath.bzl:3:1: file ':intellij_info_impl.bzl' does not contain symbol 'artifact_location'.
ERROR: Extension file 'java_classpath.bzl' has errors.
ERROR: Analysis of aspect '@intellij_aspect//:java_classpath.bzl%java_classpath_aspect of ... failed; build aborted: Extension file 'java_classpath.bzl' has errors.
```

This is due to the `incompatible_no_transitive_loads` change in bazel 0.25. https://github.com/bazelbuild/bazel/issues/5636

Workaround is to disable this bazel feature by setting `incompatible_no_transitive_loads=false` on command line or in .bazelrc

**Comment by brendandouglas** [comment]
Thanks for letting us know -- I'll fix this upstream, which will land in the release after next.

In the meantime, you can work around this by disabling hotswapping (the only code which uses this aspect), by adding "java.hotswapping.enabled=0" to an ".intellij-experiments' file in your home directory (e.g. ~/.intellij-experiments on linux)
