### ISSUE TITLE
Scala: make IntelliJ and bazel build use the same compilation flags

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/intellij#796]
I have this small code sample which compiles fine under `bazel build` command line:
```
object Main {
  def main(args: Array[String]): Unit = {
    List("1", "2", "3").find(_ == 1)
  }
}
```

However, under IntelliJ, it shows a warning:
![image](https://user-images.githubusercontent.com/1269388/57637703-758ec580-7582-11e9-934e-c13804f370c5.png)

Is there a way to make bazel build and IntelliJ use the same compiler flags?

**Comment by chaoren** [comment]
You can disable inspections in IntelliJ, but they have nothing to do with compiler flags.
