### ISSUE TITLE
IntelliJ Idea 2019 fails during project sync 

### ISSUE THREAD

**Issue by dnrusakov** [bazelbuild/intellij#805]
IntelliJ Idea 2019 fails during a project sync with the following error:

`Error:/home/parallels/.cache/bazel/_bazel_parallels/6b5e3957077f177bf52aedabef1dead0/external/intellij_aspect/BUILD.bazel:35:1: in values attribute of config_setting rule @intellij_aspect//:incompatible_py2_outputs_are_suffixed_setting: error while parsing configuration settings: unknown option: 'incompatible_py2_outputs_are_suffixed'. Since this rule was created by the macro 'define_flag_hack', the error might have been caused by the macro implementation in /home/parallels/.cache/bazel/_bazel_parallels/6b5e3957077f177bf52aedabef1dead0/external/intellij_aspect/intellij_info_impl.bzl:81:18.`

However, the same project was successfully synced with IntelliJ Idea 2018.

OS: Ubuntu Linux, 
CLion 2019.1.3

**Comment by jin** [comment]
What's your Bazel version?

**Comment by jin** [comment]
This flag was introduced in 0.24 and flipped in 0.25. https://github.com/bazelbuild/bazel/issues/7593

**Comment by dnrusakov** [comment]
We are currently on Bazel 0.23.2

**Comment by jin** [comment]
Are you able to upgrade to Bazel 0.24?

**Comment by dnrusakov** [comment]
Bazel 0.24 and Bazel 0.23.2 are fully backward compatible? 
If yes, i think we can upgrade it.
By the way, is there any solution to make it work with our current Bazel 0.23.2?

**Comment by dnrusakov** [comment]
@jin I was trying to use 0.25 but due to some backward incompatible changes in Bazel 0.25 (in comparison with 0.23.2) i have not managed to import the project in IntelliJ Idea... Unfortunately, we can not quickly migrate our project to Bazel 0.25 (it will require to spend some time).

I wonder, is there any workaround for our issue (`error while parsing configuration settings: unknown option: 'incompatible_py2_outputs_are_suffixed'`)? Is it possible to instruct the Idea plugin to just skip this error and proceed importing the project?

**Comment by dnrusakov** [comment]
Ok, i have installed the older version (v2019.03.05.0.1) of Bazel Clion Plugin which was released on Mar 15, 2019 and now everything magically works! There are no errors during project sync at all.

@jin the same project can not be opened with the newest Bazel CLion Plugin...

**Comment by jin** [comment]
Looks like this issue is resolved. Please open another issue with the problems with the latest CLion plugin.
