### ISSUE TITLE
IntelliJ can't "find usages" for protobuf fields

### ISSUE THREAD

**Issue by philwo** [bazelbuild/intellij#81]
### How to reproduce:
- Open Bazel's source code in IJWB (import using provided project file scripts/ij.bazelproject).
- Open file "test_status.proto".
- Right-click any field, e.g. "failed_logs".
- Click "find usages".

### Expected results:
- IntelliJ shows a list of all places in Bazel's code that use this field or any accessor method.

### Actual results:
- Error pop-up: "Cannot search for usages. Position to an element to find usages for, and try again."

### Additional details:
- macOS 10.12.4
- Bazel 0.4.5
- IntelliJ IDEA Ultimate 2017.1.2
- IJWB 2017.04.17.6
- [Protobuf Support](https://github.com/protostuff/protobuf-jetbrains-plugin) 0.8.0
  - Disabling the plug-in removes the "Find usages" button in protobuf files completely.

**Comment by brendandouglas** [comment]
That won't be related to the bazel plugin -- it's functionality purely provided by the protobuf plugin. I'd file a bug with them.

**Comment by philwo** [comment]
Thanks, @brendandouglas! I'll prepare a minimal example and file the issue with them. :)
