### ISSUE TITLE
Better support for modules per BUILD

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/intellij#823]
We have a growing monorepomostly in Java, Scala and kotlin with many independent services and clientes. I just started using bazel intellij plugin and it seems to create a single workspace module with all targets on it. When I'm using auto complete, it brings names from all possible targets. In other words, it does not follow BUILD file target dependencies.

What's proper way to use this plugin if I want to make sure dependencies in BUILD file must be respected?

**Comment by chaoren** [comment]
https://github.com/bazelbuild/intellij/issues/179
