### ISSUE TITLE
External dependencies are configured with invalid paths

### ISSUE THREAD

**Issue by Eipifi** [bazelbuild/intellij#83]
After adding an external dependency to WORKSPACE file and hitting the "Sync Project with BUILD Files", the library is detected and visible in Project Settings -> Modules -> Dependencies tab. However, the path to a library JAR file is not correct.

To reproduce:
1. Add the [`maven_jar`](https://bazel.build/versions/master/docs/be/workspace.html#maven_jar) rule to the WORKSPACE file:
```python
maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:18.0",
    sha1 = "cce0823396aa693798f8882e64213b1772032b09",
)
```
2. Hit `Bazel` -> `Sync` -> `Sync Project with BUILD Files`.
3. Inspect the project dependencies:
<img width="1021" alt="screen01" src="https://cloud.githubusercontent.com/assets/2813061/25726353/05bbbba4-3124-11e7-9515-a295df12f565.png">
<img width="1021" alt="screen02" src="https://cloud.githubusercontent.com/assets/2813061/25726358/08190924-3124-11e7-9c6c-63e0352fb78c.png">

You can also read the IntelliJ XMLs directly:
```bash
username@hostname:~/SomeProject$ cat .idea/libraries/guava_18_0_ijar_dc6ac314.xml
<component name="libraryTable">
  <library name="guava-18.0-ijar_dc6ac314">
    <CLASSES>
      <root url="jar:///private/var/tmp/_bazel_username/c0bcf34a998a89d27827c3237447ba16/execroot/WorkspaceName/bazel-out/local-fastbuild/com_google_guava_guava/jar/_ijar/jar/external/com_google_guava_guava/jar/guava-18.0-ijar.jar!/" />
    </CLASSES>
    <JAVADOC />
    <SOURCES />
  </library>
</component>
```
4. Inspect the filesystem:
```bash
# Go to the local-fastbuild directory.
username@hostname:~$ cd /private/var/tmp/_bazel_username/c0bcf34a998a89d27827c3237447ba16/execroot/WorkspaceName/bazel-out/local-fastbuild/

# Check that the declared library path is incorrect.
username@hostname:local-fastbuild$ stat com_google_guava_guava/jar/_ijar/jar/external/com_google_guava_guava/jar/guava-18.0-ijar.jar
stat: com_google_guava_guava/jar/_ijar/jar/external/com_google_guava_guava/jar/guava-18.0-ijar.jar: stat: No such file or directory

# Check that by adding **genfiles/external** we obtain a correct path.
username@hostname:local-fastbuild$ stat genfiles/external/com_google_guava_guava/jar/_ijar/jar/external/com_google_guava_guava/jar/guava-18.0-ijar.jar
16777221 78950315 -r-xr-xr-x 1 username wheel 0 1621418 "May  3 22:48:39 2017" "May  3 19:43:13 2017" "May  3 19:43:14 2017" "May  3 19:43:13 2017" 4096 3168 0 genfiles/external/com_google_guava_guava/jar/_ijar/jar/external/com_google_guava_guava/jar/guava-18.0-ijar.jar
```

- It looks like adding `genfiles/external` between `local-fastbuild` and the dependency name in the library path (in this example`com_google_guava_guava`) would solve the problem. Manually fixing the path works perfectly until the Sync button is pressed again.
- I did not check if the problem occurs for external dependencies in other languages.
- IDE version: `IntelliJ IDEA 2017.1.2, Build #IC-171.4249.39`
- Plugin version: `IntelliJ with Bazel, Version: 2017.04.17.6`

**Comment by brendandouglas** [comment]
Hi @Eipifi, sorry for the delay in replying.

I haven't been able to reproduce this -- which version of Bazel are you using?

**Comment by Eipifi** [comment]
After updating to bazel 0.4.5 the issue is gone. I'm not sure which version I had before updating.
