### ISSUE TITLE
Scala test events are handled by the wrong event handler

### ISSUE THREAD

**Issue by hmemcpy** [bazelbuild/intellij#835]
Looks like a change introduced in b067266755e36a2b907e16dd6e40cd1baf65ae3c caused processing of test events for `scala_junit_tests` to be handled by the `BlazeJavaTestEventsHandler` instead of `BlazeScalaTestEventsHandler`, causing names to be printed incorrectly in the test runner.

Looks like `JavaLikeLanguage.getAllHandledTestKinds()` now returns even kinds that have more specific handlers.

This also breaks navigation to test and other context actions:
![image](https://user-images.githubusercontent.com/601206/58241819-5a783e80-7d56-11e9-91e5-75802f014e6a.png)

FYI @brendandouglas

**Comment by hmemcpy** [comment]
A proposed fix to this is placing the `BlazeJavaTestEventsHandler` last in the order, giving more specific ones a chance to handle it first. 
```xml
<BlazeTestEventsHandler implementation="com.google.idea.blaze.java.run.BlazeJavaTestEventsHandler" order="last"/>
```

Would you like a PR for this?

**Comment by brendandouglas** [comment]
Looks like the appropriate fix here is to change ScalaJavaLikeLanguage#getHandledTestKinds to return an empty set.

BlazeScalaTestEventsHandler seems to handle all scala tests, so we should never be delegating to BlazeJavaTestEventsHandler.

If that sounds good to you, I can make the change upstream.

**Comment by hmemcpy** [comment]
In my case, I arrived from `BlazeXmlToTestEventsConverter#processParsedTestResults`, where it tries to locate the event handler by kind:
https://github.com/bazelbuild/intellij/blob/47b0fa9f0614f131f220fcdabf9276edd0c0be5e/base/src/com/google/idea/blaze/base/run/smrunner/BlazeXmlToTestEventsConverter.java#L173-L174
and it ends up going to the `BlazeJavaTestEventsHandler` which picks it up from `HANDLED_KINDS`, and it never makes it to the Scala-specific one.

So it does seem that by returning an empty set from `ScalaJavaLikeLanguage#getHandledTestKinds` would fix it! Sounds great, but I think you should leave a comment there, explaining why the empty set?

**Comment by hmemcpy** [comment]
Sounds great! It does seem like it would solve the problem since it won't be added to Java's `HANDLED_KINDS`. Looking forward to the fix!

**Comment by brendandouglas** [comment]
Thanks, should be fixed at head now.
