### ISSUE TITLE
Add support to report exceptions

### ISSUE THREAD

**Issue by olafure** [bazelbuild/intellij#841]
The latest bazel plugin (v2019.05.13.0.2) for intellij (2019.1.2) can't automatically report exceptions, image images.

![Workspace 1_080](https://user-images.githubusercontent.com/830918/58483979-1bccf480-8159-11e9-96bd-0e67168e1905.png)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
