### ISSUE TITLE
GoLand: debug bazel test don't run

### ISSUE THREAD

**Issue by asv** [bazelbuild/intellij#850]
Debugging does not work when trying to run `Debug 'Bazel test...` in GoLand.

rerpo repo: https://github.com/asv/bazel-goland-debug-bug

Steps:
1. Import Bazel Project...
2. Open `main_test.go`.
3. Right click on TestFoo and select "Debug 'Bazel test main_test'".

Expected: Debugger running.

Actual: Got error.

![image](https://user-images.githubusercontent.com/20145/58555446-eeed1000-8232-11e9-96bc-57d7340ffc2c.png)

Just `Run 'Bazel test ...'` works correctly.

**Comment by strican** [comment]
I also just hit this with just a `bazel run`. Is this a regression since #489 was fixed?

**Comment by chaoren** [comment]
What version of the bazel plugin are you running?

**Comment by strican** [comment]
I'm using the build close to master.

**Comment by chaoren** [comment]
In bazel, we assumed that you either have a library under test with an import path, or the test itself has an import path, but apparently you can just have a bare test without an import path as in your example.

Temporary workaround is to just set an import path attribute on the test target. It's never getting imported by anything so it shouldn't matter what it's set to, maybe we'll need to set a dummy import path value in this case.

**Comment by chaoren** [comment]
Turns out we don't even need to set the import path.

**Comment by strican** [comment]
Is this true for `go_binary` too? Because I'm hitting this while executing `bazel run` on one.

**Comment by chaoren** [comment]
Yes.

**Comment by strican** [comment]
Okay, that's good to know. I should have mentioned this but I tried adding an import path to my `go_binary` and that didn't solve the issue.

**Comment by chaoren** [comment]
Did it give a different error when you run it after adding the import path? Did you run a sync before running it?

**Comment by strican** [comment]
Nope, it's the same error. Forked @asv's example repo and added a `go_binary` with an `importpath`.

**Comment by strican** [comment]
That said, I checkout out your branch and I can confirm that solves the issue, even without the `importpath`. Thanks for the fix!
