### ISSUE TITLE
Intellij does not properly synchronize bazel's deps (and messes up auto-complete)

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/intellij#855]
I created a bazel workspace with Java, Kotlin and Scala. Each one of them has a `src` and a `test` folder. They also have `BUILD` files with `_library` and `_test` targets. I placed repro under https://github.com/igorgatis/intellij-bazel-bugs

Here is what Kotlin's BUILD file look like:
![image](https://user-images.githubusercontent.com/1269388/58572407-0071f000-8212-11e9-90a9-78515cffa841.png)

I'd expect `HelloKotlin` to be visible only to `HelloKotlin.kt`. Instead, it shows `HelloKotlinTest` plus all other classes in other folders which unrelated to `//kotlin:kotlin` target.

Here is the result: ![image](https://user-images.githubusercontent.com/1269388/58572305-cc96ca80-8211-11e9-9e73-00b186eab161.png)

**Comment by chaoren** [comment]
https://github.com/bazelbuild/intellij/issues/179
