### ISSUE TITLE
Bazel and Git in intellij

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#87]
Hi,
It seems that due to the fact that the plugin builds a project in a different directory than the source code then one loses the ability to work with IntelliJ's git support.
Is that true?
Can that be changed?
It's a real setback...

**Comment by brendandouglas** [comment]
I can't reproduce any problems working with IntelliJ's git support (we have several teams using it without an issue, AFAIK).

What git support features are you seeing a problem with?

Some things I've just verified WAE:
- local changes
- git history (integrated with 'show history' action)
- VCS > Git > fetch / rebase commands (rebase actually allows you to specify the git root, though this is prefilled correctly for me)

**Comment by ittaiz** [comment]
How do you import a project? When I import a project it creates one in a
sibling directory next to the code and then the project just doesn't have a
changes facet

**Comment by brendandouglas** [comment]
I see the same thing, but in addition I've never come across a changes facet.

Perhaps we're talking about a different Git plugin? I'm using JetBrains' Git Integration plugin (https://plugins.jetbrains.com/plugin/3033-git-integration) which comes bundled with the IDE.

I don't see any project facet code in that plugin, so perhaps you're using a different one?

**Comment by ittaiz** [comment]
I'm using the regular git client, I was just using incorrect terms. I'm sorry.
I don't see this view when I import copybara for example.
![screen shot 2017-05-14 at 09 19 36](https://cloud.githubusercontent.com/assets/1378327/26031750/5aae4798-3887-11e7-87dc-fbf2a727702b.png)

**Comment by brendandouglas** [comment]
I'm not sure what might cause that -- I just tried importing copybara as well, but can't reproduce.

If you go to Settings > Version Control, do you see the copybara source directory, listed as a Git VCS?

**Comment by ittaiz** [comment]
I think so. Is this what you mean?
![screen shot 2017-05-15 at 17 15 45](https://cloud.githubusercontent.com/assets/1378327/26062356/42a704f2-3993-11e7-9417-2eafb20f20ce.png)

**Comment by brendandouglas** [comment]
Not sure why it's 'unregistered', but that's likely the cause of the problems. Try adding your project to the registered VCS roots (some instructions here: http://blogs.candoerz.com/question/164960/configure-intellij-idea-such-that-source-detected-in-git-but-unregistered-vcs-root-detected.aspx)

**Comment by ittaiz** [comment]
The instructions were a bit confusing but I managed to find that selecting the unregistered git root and pressing + on the middle of the dialog solved it.
Thanks!
My question now becomes, why doesn't this work out of the box? I've tried it on a fresh copybara copy (and I'm seeing other issues but I think I'll open a separate ticket about them) and the issue persists.
Would the list of my plugins help?

**Comment by brendandouglas** [comment]
I'm not sure why it doesn't pick it up as part of project import. Possibly there's an IntelliJ setting to manage this? -- I haven't been able to reproduce the problem yet (e.g. by importing the copybara project into a newly installed IntelliJ).

**Comment by ittaiz** [comment]
If it's not clear then this works for other maven projects on my
installation

**Comment by ittaiz** [comment]
Closing for now since there are workspaces where this works.
If I'll be able to have a definitive definition of the problem I'll reopen.
Thanks.
