### ISSUE TITLE
Option to ignore java_binary without srcs

### ISSUE THREAD

**Issue by uri-canva** [bazelbuild/intellij#870]
We often use third party binary uber jars published to Maven in our repo, represented as `java_binary` with dependencies on those uber jars. This works perfectly from the Bazel side of things, but the IntelliJ plugin will include them when indexing the sources, since it treats the whole workspace as a single module, resulting in duplicate classes in the class path. I understand treating the whole workspace as a single module is important for its performance.

This issue can be worked around by using unshaded versions of the binary where available (example: https://github.com/google/closure-compiler), but that is not very common (example: https://github.com/OpenAPITools/openapi-generator/issues/3034). An alternative workaround is treating them as `sh_binary` so that Bazel won't know anything about them from a java point of view, but given that Bazel itself has no issue with them as they are, only the plugin does, we're would prefer not to have to change that.

Is it possible to have an option to ignore all `java_binary` transitive dependency jars if they don't transitively depend on any sources? I think in the common case that would be the expected behaviour as there are no source files to edit that depend on those jars. If it's an option it can be enabled when dealing with uncommon cases for example debugging those binaries.

If we wanted to implement this ourselves, where should we look? How should we make the change so that it can be then merged upstream?

**Comment by raz-canva** [comment]
bump - this would really be helpful for us

**Comment by chaoren** [comment]
You can ignore individual library dependencies,

1. Expand External Libraries section in Project tab
2. Find your uber jar library
3. Right click -> Exclude Library and Resync

Is this sufficient for you?
You could also navigate to a class from your uber jar and find the library using scroll from source.

**Comment by uri-canva** [comment]
Yes, that works perfectly, thanks!
