### ISSUE TITLE
Sync project & build fail when using rules_jvm_external

### ISSUE THREAD

**Issue by netdpb** [bazelbuild/intellij#871]
Project sync and build both fail with error:

```
ERROR: missing input file '@remote_java_tools_linux//:Genclass'
ERROR: /[redacted]/BUILD:1:1: //[redacted]: missing input file '@remote_java_tools_linux//:Genclass'
```

rules_jvm_external v2.2
bazel 0.26.0
IntelliJ IDEA 2019.1.3 #IC.191.7479.19

I did just update Bazel. Previously it all worked.
`bazel build` on the command line succeeds.

**Comment by netdpb** [comment]
Downgrading to bazel 0.25.3 makes the error go away.

**Comment by jin** [comment]
This is https://github.com/bazelbuild/intellij/issues/845
