### ISSUE TITLE
Bazel dirs in bazel/maven project in intellij kill the project 

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#89]
Hi,
I'm not sure if the issue should be here but this is the lesser of evils I could find.
We have a project which we're migrating from maven to bazel and since people want some side-by-side time they're using the maven intellij integration (partially since the intellij support for scala is still under work) to work inside the IDE.
The problem is that IntelliJ takes a lot of time (stopped waiting after 15 minutes) to scan the files in bazel-out and the like. I'm pretty sure this doesn't happen when the project is opened as Bazel since I guess the plugin somehow configures intellij to ignore/not scan those folders.

If I'm correct I wanted to ask if the plugin could define those directories as ignored globally and not only for bazel projects. Of course one can decide this setting should be opt-in for the unlikely case where I have a bazel-out folder which I want scanned but in general this would help ease the migration from maven to bazel.

cc @steren

**Comment by brendandouglas** [comment]
We have a pretty strict policy to wherever possible avoid impacting non-bazel projects, so I'm reluctant to do this by default.

I'd be open to an opt-in setting (especially if it's only applied to recognised bazel workspaces), but perhaps there's already a Maven-side workaround? (https://www.jetbrains.com/help/idea/2017.1/maven-ignored-files.html)

**Comment by ittaiz** [comment]
we currently resolve it by manually marking each directory as "excluded" in intellij.
Thanks!
