### ISSUE TITLE
Move intellij-latest to be 2019.1

### ISSUE THREAD

**Issue by strican** [bazelbuild/intellij#894]
Currently, `intellij-latest` still points to `intellij-2018.3`. We should move it forward to be consistent with the latest version of the plugin, which supports `2019.1`.

**Comment by brendandouglas** [comment]
intellij-latest / intellij-beta are internal categorizations. Our internal 'stable' branch is still on 2018.3, and won't move to 2019.1 until we've ironed out the currently known performance regressions in 2019.1, and have a little more confidence that there aren't unknown regressions lurking.
