### ISSUE TITLE
Plugin 'Bazel' is incompatible with this installation

### ISSUE THREAD

**Issue by strican** [bazelbuild/intellij#900]
When building and installing the latest of master, I get an error that the plugin is incompatible.

Commit: 32c16ca924758da875cb70c97c24c2f081beb11b

IntelliJ:
```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Licensed to Improbable / Steven Tricanowicz
Subscription is active until September 4, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```

Built using

```
bazelisk build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2019.1
```

**Comment by jin** [comment]
It looks like the IJ Utimate build you're using is older than the one specified in the `plugin.xml`:

```
<?xml version="1.0" encoding="utf-8"?><idea-plugin><version>9999</version><idea-version since-build="191.7141" until-build="191.*"/><change-notes><![CDATA[<p>v2019.06.03
```

Any chance you could update to build 191.7141 or later?

@brendandouglas should we make the since-build backwards compatible with UE 2019.1.1, even if we're building against 2019.1.2?

**Comment by jin** [comment]
For now, you can try reverting this commit (https://github.com/bazelbuild/intellij/commit/ced4d8a6ddad5b54b812cc8076d49362fa2dbaf9) in your local fork, which will bring 191.6707.61 back.

**Comment by strican** [comment]
Confirmed that updating to 2019.1.3 resolves the issue. Thanks!
