### ISSUE TITLE
"Missing classes" in UI designer

### ISSUE THREAD

**Issue by depthwise** [bazelbuild/intellij#904]
I've put together a trivial project in Android Studio, just a single activity, and inside that activity there's a button and a text view. No native dependencies or anything. Works fine in Gradle-based build, works fine with Bazel-based build, too. What doesn't work is the UI editor when I import the project into Android Studio 3.4.1 with the latest plugin (v2019.05.13.0.2, latest as of the time of this writing). 

The `.bazelproject` file looks as follows:
```
directories:
  android/simple_benchmark/app/src/main

targets:
  //android/simple_benchmark/app/src/main/...

additional_languages:
  c

workspace_type: android

android_sdk_platform: android-28
```

When I try to open the activity XML file in UI editor I get the following:
```
The following classes could not be found:
- org.companyname.simple_benchmark.R
- android.support.constraint.ConstraintLayout (    Add constraint-layout library dependency to the project, Fix Build Path, Edit XML, Create Class)
- android.support.design.widget.AppBarLayout (Fix Build Path, Edit XML, Create Class)
- android.support.design.widget.CoordinatorLayout (Fix Build Path, Edit XML, Create Class)
- android.support.v7.widget.Toolbar (Fix Build Path, Edit XML, Create Class)
 Tip: Try to build the project.   Tip: Try to refresh the layout.
```
Neither building nor refreshing seems to help. 

Is this supposed to work? What am I doing wrong? Would be good to document this either way, _especially_ if this is not supposed to work.

**Comment by depthwise** [comment]
Some more info: if I create a new activity XML based on LinearLayout, it works fine. But ConstraintLayout doesn't work. Bazel build completes fine, so the JAR is certainly available to it.

**Comment by jin** [comment]
This is currently a known issue with the plugin on Android Studio 3.4.x. Fixes to the ConstraintLayout and R classes are expected to be ready when the plugin is supported with AS 3.5.x onwards.

**Comment by Nikolas-LFDesigns** [comment]
AFAIK an aswb already supports (albeit, partially) an Android Studio 3.5+ but still we can't load ConstraintLayout et al.
Any status here?

**Comment by refi64** [comment]
Has anyone found any workarounds for this yet?

**Comment by jongerrish** [comment]
Hi @jin we're on AS 3.6.3 and this is still an issue. Is there an update on when this might get fixed?

**Comment by jin** [comment]
I don't have updates on this, sorry.

**Comment by refi64** [comment]
Is there any even vague idea of what the root cause may be?

**Comment by jin** [comment]
I haven't worked on Bazel's IDE support for about a year now, so I'm out of the loop - perhaps @vsiva would know?

**Comment by nkoroste** [comment]
Might be related to: https://github.com/bazelbuild/bazel/issues/2830 and potential fix: https://github.com/bazelbuild/bazel/commit/b9a2e9ded67bdf6fff0a611d174096269f68a981
