### ISSUE TITLE
Support python plugin API in version 2017.1.2+

### ISSUE THREAD

**Issue by BrendanDrewZippy** [bazelbuild/intellij#91]
Not sure what help I can offer with debugging this, but feel free to give me a yell if there's more I can provide. 

CLion configuration:

CLion 2017.1.2
Build #CL-171.4694.4, built on May 16, 2017
Licensed to Zippy / Brendan Drew
You have a perpetual fallback license for this version
Subscription is active until April 20, 2018
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

CLion with Bazel information:
<img width="393" alt="screen shot 2017-05-19 at 4 43 32 pm" src="https://cloud.githubusercontent.com/assets/27247908/26270749/5839d430-3cb2-11e7-9d60-aeb82dde7449.png">

Screenshot showing error:
<img width="1680" alt="screen shot 2017-05-19 at 4 40 38 pm" src="https://cloud.githubusercontent.com/assets/27247908/26270709/172cdf8c-3cb2-11e7-8020-a4d8842659ee.png">

**Comment by gruszczy** [comment]
+1, having exactly the same issue. I have a few python tests in my BUILD.

Syncing project...
Updating VCS...
Running Bazel info...
Command: /Users/gruszczy/bin/bazel info --tool_tag=ijwb:CLion --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


Computing VCS working set...
  BUILD (modified)
  CMakeCache.txt (added)
  CMakeFiles/3.7.2/CMakeCCompiler.cmake (added)
  CMakeFiles/3.7.2/CMakeCXXCompiler.cmake (added)
  CMakeFiles/3.7.2/CMakeDetermineCompilerABI_C.bin (added)
  CMakeFiles/3.7.2/CMakeDetermineCompilerABI_CXX.bin (added)
  CMakeFiles/3.7.2/CMakeSystem.cmake (added)
  CMakeFiles/3.7.2/CompilerIdC/CMakeCCompilerId.c (added)
  CMakeFiles/3.7.2/CompilerIdCXX/CMakeCXXCompilerId.cpp (added)
  CMakeFiles/CMakeOutput.log (added)
  CMakeFiles/clion-environment.txt (added)
  CMakeFiles/cmake.check_cache (added)
  CMakeFiles/feature_tests.bin (added)
  CMakeFiles/feature_tests.c (added)
  CMakeFiles/feature_tests.cxx (added)
  CMakeLists.txt (added)
  Makefile (added)
  WORKSPACE (modified)
  array.c (added)
  array.ll (added)
  (and 61 more)

Sync targets from project view:
  //...:all

Sync targets from working set:
  //:all

Building IDE info files...
Command: /Users/gruszczy/bin/bazel build --tool_tag=ijwb:CLion --keep_going --experimental_show_artifacts --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@bazel_tools//tools/ide:intellij_info.bzl%intellij_info_aspect --output_groups=intellij-info-text -- //...:all //:all


____Loading complete.  Analyzing...
____Found 18 targets...
____Building...
____Elapsed time: 0.310s, Critical Path: 0.01s
Total rules: 22, new/changed: 22, removed: 0
Reading IDE info result...
Loaded 22 aspect files, total size 35kB
Building IDE resolve files...
Command: /Users/gruszczy/bin/bazel build --tool_tag=ijwb:CLion --keep_going --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@bazel_tools//tools/ide:intellij_info.bzl%intellij_info_aspect --output_groups=intellij-resolve -- //...:all //:all


____Loading complete.  Analyzing...
____Found 18 targets...
____Building...
____Elapsed time: 0.267s, Critical Path: 0.00s
Command: /Users/gruszczy/bin/bazel info --tool_tag=ijwb:CLion build-language --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


Prefetching files...
Computing directory structure...
Committing project structure...
Workspace has 0 libraries
Sync failed

==== TIMING REPORT ====

Sync: 2.5s (195ms)
    BazelInfo: 503ms
    WorkingSet: 1ms
    IdeQuery: 652ms
        ExecuteBazelCommand: 625ms
        FetchAspectOutput: 0ms
        UpdateTargetMap: 26ms
    BazelBuild: 554ms
    UpdateSyncState: 378ms
        BUILD language spec: 378ms
    ReverseDependencies: 0ms
    PrefetchFiles: 0ms
    RefreshVirtualFileSystem: 12ms
    DirectoryStructure: 167ms
    UpdateProjectStructure: 26ms

Error:Internal error. Error: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/jetbrains/python/facet/PythonFacetType

**Comment by brendandouglas** [comment]
What version of the python plugin do you have?

Looks like the PythonFacet classes were recently moved from "com.jetbrains.python.facet" to "com.jetbrains.python.minor.facet".

I'd recommend downgrading to an earlier version of the python plugin (for reference, the latest version I can find compatible with 2017.1 appears to be 2017.1.171.4249.63, which doesn't have this change in it).

Realistically, we can't fix this until 2017.2, when everyone is (presumably) guaranteed to be using a python plugin with this package path change.

**Comment by gruszczy** [comment]
I am using whatever came automatically (or as part of initial configuration) for CLion. I am using 2017.1.2 and the only Python plugin I see Pycharm plugin 171.4694.4. I will take a look how I can downgrade it, thanks.

**Comment by brendandouglas** [comment]
Thanks. In that case, this will affect anyone using 2017.1.2. You can either downgrade to 2017.1, or specifically downgrade the python plugin (and ignore any subsequent prompts to upgrade it).

**Comment by BrendanDrewZippy** [comment]
Removing the python plugins appears to fix the problem.

**Comment by gruszczy** [comment]
Yep, that worked for me. It builds now. Thanks.
