### ISSUE TITLE
missing debug option in CLion

### ISSUE THREAD

**Issue by herbakamil** [bazelbuild/intellij#942]
I don't have debug option (only run) for Tensorflow.

CLion 2019.1
bazel plugin 2019.06.03.0.1

When I select //tensorflow/lite:all I don't have option to run //tensorflow/tools/benchmark:benchmark_model in debug mode.
After creating .clwb from scratch and selecting //tensorflow/tools/benchmark:benchmark_model to be build by the plugin I can debug the executable.

Do I need always to set the executable which I want to debug as the only target for bazel plugin when importing project? In particularly if I want to debug 5 different executables do I need to create 5 different projects?

**Comment by garethellis0** [comment]
I was able to get debugging working by cloning the repo, building with `bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-2019.2` and loading the plugin from disk into CLion.

CLion version: 2019.2.1
Plugin Git Hash Used: e216427dc9a0ac8fca8a

**Comment by ccnankai** [comment]
@garethellis0
Can you successfully import tensorflow, the code can jump successfully? Can you tell me how to configure it? Thank you.

**Comment by garethellis0** [comment]
Apologies, I had the same issue with a different codebase. Do you see this issue with CLion version 2019.2 and the corresponding bazel plugin?

**Comment by ccnankai** [comment]
I tried a many versions(include 2019.2), it won't work, I have been confused for a long time. If you can successfully import tensorflow, don't forget to tell me.Thanks.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
