### ISSUE TITLE
IDE shows no information (outside the blaze problems window) of visibility issues

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/intellij#944]
Having in-source-tree and in-BUILD-file breadcrumbs about visibility issues could be a powerful aid to finding and avoiding errors rooted in visibility issues.

**Comment by brendandouglas** [comment]
Up to this point, we've held off on assuming too much knowledge of BUILD file structure. The plugin can parse plain BUILD rules, but can't parse general starlark macros. So many classes of errors we could surface would be educated guesses, and we've erred on the side of relying on explicit blaze builds.

Visibility-related errors are much simpler though, as in most cases we know with certainty whether we've correctly parsed the visibility restrictions for a target / package.

We should be able to surface these in many cases.

**Comment by cgruber** [comment]
See, it always pays to ask. :D

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
