### ISSUE TITLE
Allow Workspace Relative bazel_binary path in .bazelproject file

### ISSUE THREAD

**Issue by brownry1986** [bazelbuild/intellij#949]
We have implemented a bazel wrapper inside of our workspace. We also provide *.bazelproject files for different workflows. We would like to utilize the bazel_binary tag to set the path to the bazel wrapper to ensure that all users are using the bazel wrapper, however this tag requires an absolute path. As the path will be different on each developers workstation, we would like to be able to use a relative path.

**Comment by jin** [comment]
I don't see why not: https://github.com/bazelbuild/intellij/pull/970
