### ISSUE TITLE
scala specs2 imports are not recognized by bazel plugin

### ISSUE THREAD

**Issue by natansil** [bazelbuild/intellij#96]
@chaoren,
scala specs2 imports are not recognized by bazel plugin.

example from rules_scala repo:
![image](https://user-images.githubusercontent.com/11754053/27072722-0894eb3c-502a-11e7-9a04-4d386d97c556.png)

versions:
intellij 2017.1.4
bazel 0.5.1
bazel intellij plugin 2017.05.08.1

project file:
```

directories:
  .

targets:
  //test/...
  //jmh/...
  //junit/...
  //scala/...
  //specs2/...
  //src/...
  //test/...
  //thrift/...
  //tut_rule/...
  //twitter_scrooge/...
  //bazel_test_runner/...

additional_languages:
  scala
```

**Comment by chaoren** [comment]
Can you share your project?

**Comment by natansil** [comment]
@chaoren, WDYM 

> Can you share your project?

Please elaborate

**Comment by chaoren** [comment]
Please share the project in your screenshot. I need to repro the issue. I'm not seeing that issue on my sample projects.

**Comment by chaoren** [comment]
Or any dummy project with that issue.

**Comment by chaoren** [comment]
Oh, that's the rules_scala project isn't it. Nevermind.

**Comment by chaoren** [comment]
![image](https://user-images.githubusercontent.com/10055601/27090825-4ddbfcd8-502c-11e7-8108-3fc7f8f5e42c.png)

It works fine if you reduce the scope.

Your project view file tries to include literally everything. Some of those things produces errors, cause conflicts, and/or are not supported yet (scrooge, it looks like?).
If you get the same problem with a more reasonable project view please reopen the issue.

**Comment by natansil** [comment]
@chaoren 
here is an example of an extremely simple scala project where this issue reproduces:
https://github.com/natansil/bazel-learning/tree/master/scala_project

(The repo contains several WORKSPACEs, i imported scala_project's workspace)
![image](https://user-images.githubusercontent.com/11754053/27092225-51da813a-506b-11e7-9eff-8118dd27d94c.png)

bazel project:
```

directories:
  .

targets:
  //...

additional_languages:
  scala
```

**Comment by chaoren** [comment]
![image](https://user-images.githubusercontent.com/10055601/27092809-a3668be0-5032-11e7-997e-6e2631043d5f.png)

Cannot reproduce here.
Intellij: 2017.1.1 (probably not relevant)
Bazel: 0.5.1
Intellij with Bazel: 2017.05.08.1

You are using Mac, correct? We don't actually officially support Mac yet. Do you have access to a Linux machine?

**Comment by chaoren** [comment]
Do you see any errors in the Bazel console (lower right corner)?

**Comment by natansil** [comment]
@dkomanov, can you help us out?
we are testing the new scala support in intellij's bazel plugin.

Currently I cannot get specs2 imports to get recognized on my machine: 
![image](https://user-images.githubusercontent.com/11754053/27092225-51da813a-506b-11e7-9eff-8118dd27d94c.png)

@chaoren has suggested the issue may be related to mac.
Can you help us try to reproduce this on linux?

**Comment by natansil** [comment]
@chaoren, I don't see any errors on bazel console.
```
Syncing project...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:IDEA:ultimate --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --


Computing VCS working set...
Sync targets from project view:
  //...

Building IDE info files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --keep_going --experimental_show_artifacts --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@bazel_tools//tools/ide:intellij_info.bzl%intellij_info_aspect --output_groups=intellij-info-text -- //...


____Loading complete.  Analyzing...
____Found 2 targets...
____Elapsed time: 0.166s, Critical Path: 0.01s
Total rules: 14, new/changed: 0, removed: 0
Reading IDE info result...
Loaded 0 aspect files, total size 0kB
Building IDE resolve files...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:IDEA:ultimate --keep_going --curses=no --color=no --noexperimental_ui --noprogress_in_terminal_title --aspects=@bazel_tools//tools/ide:intellij_info.bzl%intellij_info_aspect --output_groups=intellij-resolve -- //...


____Loading complete.  Analyzing...
____Found 2 targets...
____Elapsed time: 5.036s, Critical Path: 4.83s
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 2
Updating Jar Cache...
Prefetching files...
Computing directory structure...
Committing project structure...
Workspace has 3 libraries
Workspace has 2 modules
Updating in-memory state...

==== TIMING REPORT ====

Sync: 7.9s (240ms)
    BazelInfo: 852ms
    WorkingSet: 1ms
    IdeQuery: 868ms
        ExecuteBazelCommand: 867ms
        FetchAspectOutput: 0ms
        UpdateTargetMap: 0ms
    BazelBuild: 5.7s
    UpdateSyncState: 2ms
        LoadJdepsFiles: 1ms
            FetchJdeps: 1ms
        JavaWorkspaceImporter: 0ms
            ReadPackageManifests: 0ms
                FetchPackageManifests: 0ms
            CalculateSourceDirectories: 0ms
        ScalaWorkspaceImporter: 1ms
    ReverseDependencies: 0ms
    Jar Cache: 0ms
    PrefetchFiles: 0ms
    RefreshVirtualFileSystem: 0ms
    DirectoryStructure: 137ms
    UpdateProjectStructure: 24ms
    UpdateInMemoryState: 0ms
```

**Comment by dkomanov** [comment]
On my laptop (ubuntu 17.04) it reproduces:
* Test is unsynced
* Its dependencies are unresolved

```
$ bazel version
Build label: 0.5.2rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 13 11:14:04 2017 (1497352444)
Build timestamp: 1497352444
Build timestamp as int: 1497352444
```

Plugin version: 2017.05.08.1

**Comment by chaoren** [comment]
Your sync:
> Workspace has 3 libraries
> Workspace has 2 modules

My sync:
> Workspace has 11 libraries
> Workspace has 2 modules

If you open the External Libraries list, do you see something like this?
![image](https://user-images.githubusercontent.com/10055601/27152877-54314b64-511d-11e7-857b-a0484f696cc4.png)

Are you using a custom scala SDK? Do you have these libraries as filegroups instead of java_imports (or any java rule)?

**Comment by ittaiz** [comment]
@chaoren you can see what he has in the repo since he made the example for you. He basically has nothing other than calling the specs2_junit_repositories methods in rules_scala which uses native.maven_jar and bind.
On a side note on our actual project we will be using almost only maven_jar's file target since otherwise scala macros are messed up. Maybe we should discuss that in a different issue.

**Comment by chaoren** [comment]
Can you share this file from your project root please?
It should be generated by bazel.

bazel-scala_project/external/bazel_tools/tools/ide/intellij_info_impl.bzl

**Comment by natansil** [comment]
@chaoren, here you go:
[intellij_info_impl.bzl.txt](https://github.com/bazelbuild/intellij/files/1078112/intellij_info_impl.bzl.txt)

**Comment by chaoren** [comment]
@natansil Yeah, that's the correct version. I'm out of ideas. I guess wait two weeks for all of the changes to get released then try again?

**Comment by natansil** [comment]
@chaoren, what do you guess, from all of the changes will be relevant for this issue?

**Comment by chaoren** [comment]
Hi, can you still reproduce this?
https://github.com/bazelbuild/rules_scala/pull/241 should be able to fix this.

**Comment by natansil** [comment]
Hi @chaoren ,
I'm trying to reproduce but I'm getting this error, when re-syncing:
![image](https://user-images.githubusercontent.com/11754053/28165567-fe9f6c40-67dc-11e7-8988-050f8e5b4b76.png)

What am I doing wrong?

**Comment by chaoren** [comment]
> trying to run a test:

How are you running the test?

The gutter run icon?
![image](https://user-images.githubusercontent.com/10055601/28175833-5d35ab44-67c3-11e7-996f-ec3084537da0.png)
The menu run icon?
![image](https://user-images.githubusercontent.com/10055601/28175860-71516a3c-67c3-11e7-92f7-f19c84bd032f.png)
Or some shortcut?

**Comment by chaoren** [comment]
I can see the same error when I use "Run Scala Console" which is provided by the scala plugin, not the bazel plugin. It has no knowledge of how bazel runs things so it of course fails. I'm assuming you're using a similar action provided by the scala plugin instead of those provided by the bazel plugin. I have to hunt down all of these, and hide them from the user.

**Comment by natansil** [comment]
I right click on the Test name, then choose `run Test` (see below).
I don't see a gutter run icon next to the test class...

![image](https://user-images.githubusercontent.com/11754053/28245704-9643fe1e-6a15-11e7-83e8-cb1a1aee7be2.png)

**Comment by natansil** [comment]
@chaoren, can we make the `run test` shortcut on specs2 tests go to bazel plugin?

**Comment by chaoren** [comment]
> I don't see a gutter run icon next to the test class...

@natansil If you don't see the gutter icon, you probably don't have the correct bazel plugin version.

> can we make the run test shortcut on specs2 tests go to bazel plugin?

It does if you have the correct version.

**Comment by ittaiz** [comment]
@natansil is this still open?

**Comment by natansil** [comment]
issue resolved
