### ISSUE TITLE
Cant build after migrating to rules_jvm_external

### ISSUE THREAD

**Issue by mattjs** [bazelbuild/intellij#975]
I cant seem to build within IntelliJ any more. From the command line everything is good but when try to build in the IDE I get a bunch of errors that look like the following.

```
ERROR: /private/var/tmp/_bazel_phasic/81de3b92e9c1b9c874a29c83c3fbaed0/external/maven/BUILD:403:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on jvm_import rule @maven//:org_json_json: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_phasic/81de3b92e9c1b9c874a29c83c3fbaed0/external/maven/BUILD", line 403
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/private/var/tmp/_bazel_phasic/81de3b92e9c1b9c874a29c83c3fbaed0/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/private/var/tmp/_bazel_phasic/81de3b92e9c1b9c874a29c83c3fbaed0/external/intellij_aspect/intellij_info_impl.bzl", line 794, in intellij_info_aspect_impl
		[make_dep_from_label(label, COMPILE_TIME) for label in transitive_exports]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

I am on version 2.3 of `rules_jvm_external` and version 0.27.1 of Bazel.

Am I doing something wrong? Cant seem to figure it out.

**Comment by jin** [comment]
What's the version of your IntelliJ plugin? Please update to a version newer than 2019.06.03.

**Comment by mattjs** [comment]
I have v2019.04.15.0.5 but when I try to update, it says there are no updates.

**Comment by jin** [comment]
It sounds like you're using an older version of IntelliJ. 

You can work around this without updating by adding `--incompatible_depset_is_not_iterable=false` to the project's .bazelrc file.

**Comment by mattjs** [comment]
That was the issue, thanks Jin. I upgraded everything else but forgot about IntelliJ!
