### ISSUE TITLE
Running tests (junit/specs2/scala) misses some of them

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/intellij#98]
Hi,
I have a basic example [project](https://github.com/ittaiz/bazel-scala-getting-started) for bazel and scala.
When I try to run a test target which has a few tests (2 junit and 1 specs2) I see:
![screen shot 2017-06-14 at 15 14 10](https://user-images.githubusercontent.com/1378327/27131634-314492f4-5114-11e7-814f-533f8284be0a.png)
If we look at the bazel test.xml output we do see all three of them (rename the test.xml.txt to test.xml as github doesn't allow xml).
[test.xml.txt](https://github.com/bazelbuild/intellij/files/1074513/test.xml.txt)
If I change the package of SomeJunit2Test (which is missing) from `src.test.java.com.example` to `com.example` it starts appearing.
The Specs2 test doesn't appear at all and I think there is a correlation between them since its testsuite name is also unorthodox.  

Bazel console shows no errors and so does the problems view.
Versions:
rules_scala: 5d6ff512652b8b55f5d26f6ea69e05d86582d996 (this morning)  
Intellij bazel plugin: 2017.05.08.1
Bazel: 55f40c8ea4f1e7bf81552bfe4377e26768e85f2c (June 6th)
Intellij:
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by natansil** [comment]
I also recreated this.
If I have two different test targets (one for each test class), than both are run,
but if I merge the targets to one test target with `glob(["*.scala"])` than only one test class is run.

**Comment by ittaiz** [comment]
Natan,
That might be a different issue.
I was able to see two JUnit test classes from the same target using glob.
The problem with respect to the JUnit test was the package name (which I
wrote above). If both share the same package then it's not a problem.

**Comment by chaoren** [comment]
It has nothing to do with the package name either.
```
<testcase name='passingTest2' classname='src.test.java.com.example.SomeJunit2Test' time='0.0' />
```
We check if `status='run'` is present or `time=` is greater than 0 to determine if a test is run.
Time is 0 in this case so the bazel plugin thought the test wasn't run.
Can you make sure bazel was actually running this test? Add a loop or something.

**Comment by chaoren** [comment]
This happens in java too if the test runs too fast. I'll file a bug with bazel to set `status='run'` for test cases.

**Comment by ittaiz** [comment]
I see. This means that we'll need to wait for the next release, right?

**Comment by ittaiz** [comment]
Also,
I tried adding `Thread.sleep(1000L)` in both SomeJunit2Test and the Specs2 test and didn't see them show up

**Comment by chaoren** [comment]
I tried the same, but the test xml still says `time='0.0'`.

**Comment by chaoren** [comment]
Filed this for the 0.0 time vs not run issue: https://github.com/bazelbuild/bazel/issues/3201
The `Thread.sleep(1000L)` still producing `time='0.0'` in the xml is a problem with the scala test runner. We just read the xml.
