### ISSUE TITLE
tensorflow grpc++ symbol problem

### ISSUE THREAD

**Issue by strgrb** [bazelbuild/intellij#99]
when I load tensorflow with clion plugin, I found int the .cc files, grpc++ cannot be found by the plugin.

**Comment by strgrb** [comment]
and I may want to ask, can this project be handled by itself?

**Comment by jvoung** [comment]
How did you set up tensorflow with clion+bazel plugin?
Did you run the ./configure script like in https://www.tensorflow.org/install/install_sources?

What is an example .cc file + line number that is having problems with grpc++ headers and symbols?

They work for me after I run ./configure, and then just import with the bazel plugin. On Linux, with .bazelproject configured to:
====
directories:
  .
targets:
  //...:all
====

For file tensorflow/core/distributed_runtime/rpc/grpc_channel.cc, CLion can resolve the reference to ::grpc::CreateCustomChannel on line 69 just fine (see attached image). 
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_channel.cc#L69)

The other thing to keep in mind is that the .cc has to be reachable from a BUILD file target. For example, tensorflow/core/distributed_runtime/master_test.cc has a reference to grpc++.h that is unresolved, but it is commented out in the BUILD file (so not actually reachable as a target).

![tensorflow_grpc_resolve_fine](https://user-images.githubusercontent.com/1780154/27187618-abaf53d0-51b9-11e7-952d-d41971b2662c.png)

**Comment by strgrb** [comment]
Thank you very much for you reply. sorry for the late reply, I'm fixing my network these days, it seems some urls has been blocked, and now It's OK.

**Comment by jvoung** [comment]
Okay, closing issue then, thanks!
