### ISSUE TITLE
Bazel plugin incompatible with CLion on Mac

### ISSUE THREAD

**Issue by abhinavsingh** [bazelbuild/intellij#997]
Downloaded latest version from https://plugins.jetbrains.com/plugin/9554-bazel

CLion details:
```
CLion 2019.1
Build #CL-191.6183.77, built on March 25, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```

**Comment by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [comment]
Confirm this does not work for me either; 2019.2 also fails. 

Howeveer, CLion 2019.1.4 (Build: 191.7479.33) however does work, and be found at: https://www.jetbrains.com/clion/download/other.html.

**Comment by rmehlinger** [comment]
confirming that this is also broken for Pycharm

**Comment by libratiger** [comment]
Yes, this plugin can not be installed in Clion, any update?

**Comment by jin** [comment]
The Bazel plugins are not supported on 2019.2.x yet. They should work for 2019.1.x. @abhinavsingh @libratiger can you confirm that your CLion versions are in 2019.1.x?

**Comment by libratiger** [comment]
@jin Yes, the 2019.x can be installed, but it failed to import the bazel project, i do not deep into the reason.

**Comment by abhinavsingh** [comment]
@jin Unfortunately I have already auto-upgraded to 2019.2, that's when the problem started.

**Comment by jin** [comment]
@abhinavsingh is it possible for you to install 2019.1.x as well using something like the [JetBrains Toolbox](https://www.jetbrains.com/toolbox/app/)?

**Comment by alice-ks** [comment]
This looks like an outdated issue. By now, the plugin is compatible with versions even past 2019.2. Hence, I'm closing this issue now. Please refer to other tracking issues if you're interested in compatibility with newer IDE versions.
